### ISSUE TITLE
Distribute precompiled binaries for Alpine

### ISSUE THREAD

**Issue by ThomWright** [grpc/grpc-node#100]
From https://github.com/grpc/grpc-node/releases/tag/v1.7.2:

> Precompiled binaries are not yet distributed for musl libc. Installations on Alpine Linux will result in compiling the binary locally.

Any idea when this might change? It would be really useful.

**Comment by murgatroid99** [comment]
We have published grpc@1.8.0-pre2 which includes precompiled binaries for Alpine, so you can try those out now.

**Comment by ThomWright** [comment]
Testing pre-release versions is a bit tricky because I always end up with multiple versions of `grpc`, e.g.:

```
my-lib@1.0.0 /somewhere
├─┬ @google-cloud/pubsub@0.15.0
│ └─┬ google-gax@0.13.5
│   └── grpc@1.7.2 
└── grpc@1.8.0-pre2 
```

I'm not sure how I can tell NPM to use `grpc` at a given version all the way down the dependency tree, and loads of other Google libs use their own versions :confounded:

**Comment by murgatroid99** [comment]
As of version 1.8.x, we are distributing precompiled binaries for Alpine.
