### ISSUE TITLE
Allow overriding backoff parameters for channel

### ISSUE THREAD

**Issue by rivertam** [grpc/grpc-node#101]
In [channel.ts](https://github.com/grpc/grpc-node/blob/master/packages/grpc-js-core/src/channel.ts), the backoff parameters are hard-coded. In other implementations (or at least C++), it is possible to change these parameters. It should be easy to offer them as optional parameters in Channel creation.

**Comment by murgatroid99** [comment]
I agree. In the long run, the TypeScript channel implementation should support as many as possible of the channel arguments that apply to the existing implementation.

**Comment by murgatroid99** [comment]
#1200 will add support for the `grpc.initial_reconnect_backoff_ms` and `grpc.max_reconnect_backoff_ms` options.

**Comment by murgatroid99** [comment]
Those options have been implemented and are now available to use.
