### ISSUE TITLE
grpc_tools_node_protoc command not found

### ISSUE THREAD

**Issue by nhanpiti** [grpc/grpc-node#1014]
I follow README.md from static_codegen (examples/node). When I run this command

> grpc_tools_node_protoc --js_out=import_style=commonjs,binary:../node/static_codegen/ --grpc_out=../node/static_codegen --plugin=protoc-gen-grpc=`which grpc_tools_node_protoc_plugin` helloworld.proto

I get an error:

> -bash: grpc_tools_node_protoc: command not found

Protoc and grpc-tools have installed already.

libprotoc 3.9.1
grpc-tools@1.8.0

node: v10.16.3
npm: 6.9.0
MacOS Mojave

**Comment by tzsword** [comment]
>./scripts/pb_generator.sh 
    Input File: ./protos/*.proto
    Output Dir: ./src/pb/

```sh
npx grpc_tools_node_protoc \
  --js_out=import_style=commonjs,binary:./src/pb \
  --grpc_out=./src/pb \
  -I=./protos ./protos/*.proto
```

```sh
  # run in project root
  sh ./scripts/pb_generator.sh
```

hope this helps

**Comment by nhanpiti** [comment]
Thanks a lot !
