### ISSUE TITLE
Why doesn't `grpc-js` support Node LTS 10.16?

### ISSUE THREAD

**Issue by pelhage** [grpc/grpc-node#1016]
I'm just curious if there is any particular reason why grpc-js only supports `10.10` and whether it's possible to support `10.16`

Thanks!

**Comment by murgatroid99** [comment]
The supported version range is `^8.13.0 || >=10.10.0`, which includes 10.16.

**Comment by cjihrig** [comment]
10.16.x is supported - although after the recent security releases, you should be using 10.16.3 or greater.
