### ISSUE TITLE
does it still experimental

### ISSUE THREAD

**Issue by nawafHinai** [grpc/grpc-node#1018]
"This library is currently incomplete and experimental. It is built on the http2 Node module."
is that mean that I can't use it in production.

**Comment by murgatroid99** [comment]
"Beta" might be a better term now. I'm still not sure I would recommend using it in production, but I believe some people are doing that.

**Comment by murgatroid99** [comment]
We have published `@grpc/grpc-js` version 1.x. It is no longer considered "experimental" or "beta".
