### ISSUE TITLE
Typescript Implementation Of server.addService Is Incorrect

### ISSUE THREAD

**Issue by LouiseBC** [grpc/grpc-node#102]
It's [typed](https://github.com/lunarway/grpc-node/blob/00b4bc6e598f4ea846041b5e154f2b421bdb23aa/packages/grpc-native-core/index.d.ts#L196) as `addService(service: Service, implementation: { [name: string]: handleCall })` (Service defined [here](https://github.com/dcodeIO/protobuf.js/blob/952c7d1b478cc7c6de82475a17a1387992e8651f/index.d.ts#L1293)).

However, if you look at the implementation of [addService](https://github.com/grpc/grpc-node/blob/82b03c3f1b68972b019e43b56bfe6d7f7cdff920/packages/grpc-native-core/src/server.js#L870), it seems that none of the properties defined on Service are necessary to add a new service.

The example outlined [here](https://github.com/grpc/grpc/blob/v1.7.x/examples/node/static_codegen/greeter_server.js) using [this](https://github.com/grpc/grpc/blob/v1.7.x/examples/node/static_codegen/helloworld_grpc_pb.js) generated code, confirms that `services.GreeterService` doesn't actually implement the `Services` class, but I'm assuming that this example contains valid code.

**Comment by andrew8er** [comment]
This is because the implementation type is defined very generically. See my PR https://github.com/grpc/grpc-node/pull/84

**Comment by murgatroid99** [comment]
This is correct. That type should actually be `ServiceDefinition`, not `Service`.

**Comment by winguse** [comment]
I also find [Message](https://github.com/grpc/grpc-node/blob/master/packages/grpc-native-core/index.d.ts#L69) is using as generic, but [defined as none-generic](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/protobufjs/index.d.ts#L119).

**Comment by nicolasnoble** [comment]
Looks like this one got in fact resolved.
