### ISSUE TITLE
Retrying when client received "Error: 14 UNAVAILABLE"

### ISSUE THREAD

**Issue by nhanpiti** [grpc/grpc-node#1020]
I try many time googling, how gRPC-node handles requests when client received UNAVAILABLE status Or services stuck. In fact, gRPC-node doesn't have "retry mechanism". Can I write some code below to result this problem (without using 3rd node module), is good or bad idea ?

- Retry
```
for...loop
    client.callMethod(req, callback(error, result))
```

- Manual load balancing
```
(something % 2)
client1.callMethod(req, callback(error, result))
client2.callMethod(req, callback(error, result))
```

Please give me some advise for that.

**Comment by imjoey** [comment]
Hi @nhanpiti , as far as I can tell,  setting the `wait_for_ready` option to `true` when issuing gRPC requests probably should be a workaround for your problem. This option could do retrying automatically unless encountering unrecoverable failures and fortunately `UNAVAILABLE` is recoverable. Please refer to https://github.com/grpc/grpc-node/blob/9c274034d05690d5709d4064f627b774b8305c32/packages/grpc-native-core/test/surface_test.js#L944 for detailed usage.

**Comment by murgatroid99** [comment]
The `waitForReady` option does make the library retry requests, it just means that the request will not fail with an `UNAVAILABLE` status if the client fails to establish a connection before starting a call. It does not prevent any other `UNAVAILABLE` status if a connection drops after a call as started. So, it may reduce how many `UNAVAILABLE` errors you see depending on the cause, but you will probably still need to do retries in your own code.
