### ISSUE TITLE
How to prevent deadlocks? (Handling gRPC calls while in a gRPC call)

### ISSUE THREAD

**Issue by szekelyisz** [grpc/grpc-node#1024]
I have two gRPC servers, one in Node.js, the other is native (C++). The one in Node provides a call to log events and also initiates actions on the native server. These actions should send logs back to the Node server during the processing of the call.

I'm experiencing random hangups with this setup. I guess there's a classic deadlock situation as the native server is trying to log to the other while that one is in the middle of a gRPC call to the native server.

Is there any best practice to handle this situation? Thanks!

**Comment by murgatroid99** [comment]
Just to make sure I understand: you have a Node server with a log method that triggers requests to the C++ server, and those requests trigger requests to the Node log method, which triggers more requests to the C++ server, back and forth forever? If that is the case, this isn't a deadlock, it's infinite recursion, and new calls probably eventually get rejected because there are already too many active calls.

**Comment by szekelyisz** [comment]
> Just to make sure I understand: you have a Node server with a log method that triggers requests to the C++ server, and those requests trigger requests to the Node log method, which triggers more requests to the C++ server, back and forth forever?

No -- the node server's log method doesn't trigger any new calls. It only writes the message to the console, so there's no infinite recursion involved. The node server calls a method on the C++ server, which calls calls back to the node server to log any errors and debug messages while the original request is being processed.

**Comment by murgatroid99** [comment]
OK, so you have some other method on the Node server, which triggers calls to the C++ server, which calls the log method on the Node server, which doesn't trigger any more calls. In that case I don't see any problems, at least on the Node side. The Node server handles everything asynchronously and it can handle quite a few requests at once.

**Comment by murgatroid99** [comment]
I don't think there is a real problem here. If you experience a problem like the one described here, please file a new issue describing it.
