### ISSUE TITLE
Dependency on Old Protobufjs

### ISSUE THREAD

**Issue by Harmonickey** [grpc/grpc-node#103]
Wasn't there a fix to use the new protobufjs 6 version? 

https://github.com/grpc/grpc/issues/8991

However, when I pull down the latest grpc 1.7.2 version, it is still dependent on 5.0.0.  It would be useful to have version 6 in there so that I can use loading property and proto verification especially with messages that use the virtual oneof parameters.

```json
{
  "name": "grpc",
  "version": "1.7.2",
  "author": "Google Inc.",
  "description": "gRPC Library for Node",
  "homepage": "https://grpc.io/",
  "repository": {
    "type": "git",
    "url": "https://github.com/grpc/grpc-node.git"
  },
  "bugs": "https://github.com/grpc/grpc-node/issues",
  "contributors": [
    {
      "name": "Michael Lumish",
      "email": "mlumish@google.com"
    }
  ],
  "directories": {
    "lib": "src"
  },
  "scripts": {
    "build": "./node_modules/.bin/node-pre-gyp build",
    "electron-build": "./node_modules/.bin/node-pre-gyp configure build --runtime=electron --disturl=https://atom.io/download/atom-shell",
    "coverage": "./node_modules/.bin/istanbul cover ./node_modules/.bin/_mocha test",
    "install": "./node_modules/.bin/node-pre-gyp install --fallback-to-build --library=static_library"
  },
  "bundledDependencies": [
    "node-pre-gyp"
  ],
  "dependencies": {
    "arguejs": "^0.2.3",
    "lodash": "^4.15.0",
    "nan": "^2.8.0",
    "node-pre-gyp": "^0.6.39",
    "protobufjs": "^5.0.0"
  },
```

I am not doing anything special other than just 
`npm install grpc`

**Comment by murgatroid99** [comment]
That change that switched to Protobuf.js 6 was almost immediately reverted because it turned out to be a breaking change. We are currently working on a better way to do that.

**Comment by Harmonickey** [comment]
Ah, understood.  Thank you.

**Comment by shinzui** [comment]
Any updates on upgrading `protobuf.js` to the latest version?

**Comment by murgatroid99** [comment]
We are very close to publishing a new separate utility package for using Protobuf.js 6 with gRPC.

**Comment by murgatroid99** [comment]
We have now published `@grpc/proto-loader` which depends on the newest version of Protobuf.js. Please try it out and tell us about any issues you experience.

**Comment by Harmonickey** [comment]
So far looking good.  I think it's fair to close this ticket.
