### ISSUE TITLE
Grpc install hangs forever

### ISSUE THREAD

**Issue by volodyad** [grpc/grpc-node#1050]
Grpc version 1.17.0
Building in china mainland, so might be some relations to the bad internet

npm i cause hang up on step node-pre-gyp info install unpacking node-v57-linux-x64-glibc/grpc_node.node

Full version of log

node-pre-gyp info it worked if it ends with ok
node-pre-gyp verb cli [ '/usr/local/bin/node',
node-pre-gyp verb cli   '/chinaratings/node_modules/fabric-shim/node_modules/grpc/node_modules/.bin/node-pre-gyp',
node-pre-gyp verb cli   'install',
node-pre-gyp verb cli   '--fallback-to-build',
node-pre-gyp verb cli   '--library=static_library' ]
node-pre-gyp info using node-pre-gyp@0.12.0
node-pre-gyp info using node@8.11.3 | linux | x64
node-pre-gyp verb command install []
node-pre-gyp WARN Using needle for node-pre-gyp https download
node-pre-gyp info check checked for "/chinaratings/node_modules/fabric-shim/node_modules/grpc/src/node/extension_binary/node-v57-linux-x64-glibc/grpc_node.node" (not found)
node-pre-gyp http GET https://node-precompiled-binaries.grpc.io/grpc/v1.17.0-pre1/node-v57-linux-x64-glibc.tar.gz
node-pre-gyp http 200 https://node-precompiled-binaries.grpc.io/grpc/v1.17.0-pre1/node-v57-linux-x64-glibc.tar.gz
node-pre-gyp info install unpacking node-v57-linux-x64-glibc/grpc_node.node

**Comment by murgatroid99** [comment]
According to that log, the part of the installation script that requires the internet worked fine. There's nothing in the log that indicates why that wouldn't work. I suggest trying a newer version of the grpc library to see if that helps.
