### ISSUE TITLE
@grpc/grpc-js custom headers support

### ISSUE THREAD

**Issue by kamthamc** [grpc/grpc-node#1076]
### Is your feature request related to a problem? Please describe.
Hi, I am trying to set custom authentication headers to the call stream but couldn't find a way. If already available can anyone please help me how to add them? If not, I can help implementing it.

### Describe the solution you'd like
Custom headers needs to be added to the call stream.

**Comment by murgatroid99** [comment]
For authentication headers we recommend using the call credentials API. You can create a call credentials object using the [`grpc.credentials.createFromMetadataGenerator`](https://grpc.github.io/grpc/node/grpc.credentials.html#.createFromMetadataGenerator__anchor) or, if you're using the `google-auth-library`, [`grpc.credentials.createFromGoogleCredential`](https://grpc.github.io/grpc/node/grpc.credentials.html#.createFromGoogleCredential__anchor). Then you can either use it for a whole channel by attaching it to a channel credentials object (created by `grpc.credentials.createSsl`), or you can use it individually when making a request by passing it as the `credentials` member of the optional call options argument, which comes after the initial argument and before the callback. See the [`makeUnaryRequest`](https://grpc.github.io/grpc/node/grpc.Client.html#makeUnaryRequest__anchor) documentation for details. You can see that the other request types are similar.

More generally, you can pass any arbitrary custom metadata when making a request by constructing a `grpc.Metadata` object and then passing it as another optional argument, before the call options.

**Comment by kamthamc** [comment]
Thanks, using `grpc.credentials.createFromMetadataGenerator` works but it's not straight forward.

**Comment by murgatroid99** [comment]
The reason it has that complexity is to allow for dynamically constructing the auth header, for doing things like refreshing credentials information when they expire.
