### ISSUE TITLE
Uncaught TypeError: setInterval(...).unref is not a function (when called from electron)

### ISSUE THREAD

**Issue by mrfelton** [grpc/grpc-node#1077]
### Problem description
I'm getting this error when trying to use `@grpc/grpc-js@0.6.9` from within a web worker running under Electron.

> Uncaught TypeError: setInterval(...).unref is not a function

The same code works ok in grpc-js 5.x version.

### Reproduction steps

Try to use latest release in a node enabled web worker within electron.

### Environment
 - OS name, version and architecture: Mac
 - Node version 12.x
 - Node installation method nvm
 - Package name and version @grpc/grpc-js@0.6.9

### Additional context

```
Uncaught TypeError: setInterval(...).unref is not a function
    at new SubchannelPool (subchannel-pool.js?f8bb:55)
    at eval (subchannel-pool.js?f8bb:99)
    at Object../node_modules/@grpc/grpc-js/build/src/subchannel-pool.js (grpc.worker.js:504)
    at __webpack_require__ (grpc.worker.js:20)
    at eval (channel.js?e974:21)
    at Object../node_modules/@grpc/grpc-js/build/src/channel.js (grpc.worker.js:192)
    at __webpack_require__ (grpc.worker.js:20)
    at eval (index.js?0156:22)
    at Object../node_modules/@grpc/grpc-js/build/src/index.js (grpc.worker.js:276)
    at __webpack_require__ (grpc.worker.js:20)
```

**Comment by murgatroid99** [comment]
I am very hesitant to start supporting environments that do not properly implement the Node API. I suggest first filing an issue with Electron asking them to fix how their Node-enabled web workers implement the [timers API](https://nodejs.org/api/timers.html).

**Comment by mrfelton** [comment]
It's a fair comment @murgatroid99 . Unfortunately though I have not had much luck in trying to get to the bottom of the root issue and patching lower down the stack. So until I can do that, I feel that this simple fix would at least enable people to use this in a webpack/electron environment again as they could previously.

**Comment by murgatroid99** [comment]
My assumption is that the root cause of the issue is that the timers API you have access to in that context is not the Node timers API but the web timers API, which doesn't have the reference handling APIs. I would like to at least see an issue on Electron to see what action they will take, if any, to correct the problem.

**Comment by mrfelton** [comment]
https://github.com/electron/electron/issues/21162#issuecomment-554792447

Thoughts?

**Comment by murgatroid99** [comment]
Thank you. I see that they are unwilling to address the issue themselves.
