### ISSUE TITLE
npm install firebase fails due to grpc

### ISSUE THREAD

**Issue by Aswathi17** [grpc/grpc-node#1081]
I am using node 10.13 and trying to do npm i firebase where I get the error says failed to load grpc24.10.0. I browsed alot and found one solution worked for me which I gave was npm i firebase@4.32.
But can you please someone share the exact solution for this because my issue got resolved by installing the older version of firebase.

**Comment by juansmolano** [comment]
Hi, we are having the same problem with all our backends in our pipeline 
Have you found a workaround?

**Comment by Aswathi17** [comment]
@juansmolano It got resolved while installing with the old version of Firebase **firebase@4.6.2** but not sure whether its the correct solution.

**Comment by ambrice** [comment]
I resolved this by installing the system grpc package before installing firebase

**Comment by murgatroid99** [comment]
I believe Firebase now has a dependency on `@grpc/grpc-js` instead of `grpc`, so this should not be a problem going forward.
