### ISSUE TITLE
about waring

### ISSUE THREAD

**Issue by wellorange** [grpc/grpc-node#111]
C:\Users\wellorange\Desktop\document\rpc\grpc\src\dynamic_codegen>node greeter_server.js
(node:4392) DeprecationWarning: Server#addProtoService: Use Server#addService instead

？？？？？

**Comment by murgatroid99** [comment]
That looks like our examples. We haven't updated them in a while, and it's true that they are still using a function that has been deprecated, and that should be changed.

**Comment by wellorange** [comment]
@murgatroid99 ok
