### ISSUE TITLE
Broken windows build for electron

### ISSUE THREAD

**Issue by manu-st** [grpc/grpc-node#112]
Since version 1.7.2 where the module path now contains -{libc}, it won't compile properly when grpc is used in an electron app using `electron-builder`. The later still look for the path without -{libc}. Reverting to version 1.7.1 of grpc-node fixes the issue.

**Comment by murgatroid99** [comment]
This seems like some sort of version mismatch issue, because in both cases that path is defined by gRPC. Do you have an error message that you can share? Have you tried uninstalling and reinstalling your node_modules, to see if that fixes it?

**Comment by manu-st** [comment]
I'm getting an error at runtime:

```
module.js:472 Uncaught Error: Cannot find module 'C:\Dev\client\node_modules\grpc-caller\node_modules\grpc\src\node\extension_binary\electron-v1.7-win32-x64-unknown\grpc_node.node'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (C:\Dev\client\node_modules\electron\dist\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Dev\client\node_modules\grpc-caller\node_modules\grpc\src\grpc_extension.js:30:15)
    at Object.<anonymous> (C:\Dev\client\node_modules\grpc-caller\node_modules\grpc\src\grpc_extension.js:34:3)
```

**Comment by murgatroid99** [comment]
What is the contents of `C:\Dev\client\node_modules\grpc-caller\node_modules\grpc\src\node\extension_binary\`?

**Comment by manu-st** [comment]
The content is made of 2 folders:
- electron-v1.7-win32-x64-{libc}
- node-v57-win32-x64-unknown

Before it was just
- electron-v1.7-win32-x64
- node-v57-win32-x64

**Comment by murgatroid99** [comment]
That looks like you're building it from source. How exactly are you building it? What are the installed versions of `grpc` and `node-pre-gyp` (you can see this with `npm ls`)?

For now, I would suggest installing the precompiled electron binary by running `npm install --runtime=electron --target=1.7.0`.

**Comment by manu-st** [comment]
I'm using `yarn` instead of `npm` to compile my project and use `electron-builder` to build my electron app. Not sure how to translate the `npm` command in that context.

This fails with version 1.7.2 of grpc and version 0.6.39 of node-pre-gyp.

**Comment by murgatroid99** [comment]
I'm not sure if it will work the same, but hopefully you can just do the same thing but with `yarn install`.

**Comment by nicolasnoble** [comment]
Closing stale issues. Also, the supported method for installing gRPC is through the downloading of pre-compiled binaries with npm install and node-pre-gyp. Supporting all edge cases is impossible for us. We're happy to help debugging and troubleshooting issues, but we need more active communication for this.

**Comment by yovanoc** [comment]
Related or not? -> https://github.com/electron-userland/electron-builder/issues/3049

**Comment by nicolasnoble** [comment]
Please don't bump older issues like this. Also, please read our recent information on Electron. https://github.com/grpc/grpc-node/tree/master/packages/grpc-native-core
