### ISSUE TITLE
Intent to implement: use Prettier for formatting

### ISSUE THREAD

**Issue by merlinnot** [grpc/grpc-node#1169]
### Is your feature request related to a problem? Please describe.

Recently I started contributing to this repository and a lack of a formatter makes it a little harder, as I need to do that manually. Using a formatter also cuts all of the discussions about how a certain piece of code should be formatted.

### Describe the solution you'd like

I'd be eager to make a PR that introduces Prettier and makes it run as a part of the CI, so the code is always nicely formatted.

### Describe alternatives you've considered

Some Google repositories used to use clang for formatting, but I see a general shift towards Prettier. That's something to consider tho.

### Additional context

**Comment by murgatroid99** [comment]
We have a formatter and linter, they're just not run in the CI. `npm run check` errors if they detect any problems and `npm run fix` also fixes the formatting. We use the [`gts` package](https://www.npmjs.com/package/gts), which appears to delegate formatting to Prettier.

**Comment by merlinnot** [comment]
Many thanks for the link! I baked a small PR for one of the packages with small fixes and improvements to the config: https://github.com/grpc/grpc-node/pull/1172. Apparently gts runs TSLint and only if it's successful, runs formatting. So I fixed all of the linting issues and will follow up with a PR that formats all files if that's ok with you.

**Comment by merlinnot** [comment]
Great we aligned on this, I sent out PRs for `grpc-js` and `proto-loader` 👍
