### ISSUE TITLE
Support for binary mirror configuration

### ISSUE THREAD

**Issue by victorvess** [grpc/grpc-node#117]
Trying to use grpc-node behind a corporate firewall, which does not allow access to GCS buckets to download binary dependencies.  The attempts to download and/or compile with gyp time out unless proxy settings are applied.

Would be good to support binary mirror settings,  Similar to what SASS module supports: https://github.com/sass/node-sass#binary-configuration-parameters

**Comment by nicolasnoble** [comment]
I think @murgatroid99's answer closes this issue.
