### ISSUE TITLE
node_modules/grpc: Command faile

### ISSUE THREAD

**Issue by sachinkumaram-veoci** [grpc/grpc-node#1181]
### Problem description
[4/4] Building fresh packages...
error /home/circleci/code/node_modules/grpc: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build --library=static_library

### Reproduction steps
yarn install

### Environment
 - Linux
 - yarn install

**Comment by matheo** [comment]
`yarn install` is taking forever for me, I guess it will fail like this at the end...

**Comment by matheo** [comment]
wow, the installation with `npm` is broken too, here the verbose log:
```
> grpc@1.24.2 install /my/project/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp info it worked if it ends with ok
node-pre-gyp verb cli [ '/home/matheo/.nvm/versions/node/v10.16.3/bin/node',
node-pre-gyp verb cli   '/my/project/node_modules/grpc/node_modules/.bin/node-pre-gyp',
node-pre-gyp verb cli   'install',
node-pre-gyp verb cli   '--fallback-to-build',
node-pre-gyp verb cli   '--library=static_library' ]
node-pre-gyp info using node-pre-gyp@0.14.0
node-pre-gyp info using node@10.16.3 | linux | x64
node-pre-gyp verb command install []
node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp info check checked for "/my/project/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node" (not found)
node-pre-gyp http GET https://node-precompiled-binaries.grpc.io/grpc/v1.24.2/node-v64-linux-x64-glibc.tar.gz
node-pre-gyp http 200 https://node-precompiled-binaries.grpc.io/grpc/v1.24.2/node-v64-linux-x64-glibc.tar.gz
node-pre-gyp info install unpacking node-v64-linux-x64-glibc/grpc_node.node

```
and it stops there forever...

**Comment by matheo** [comment]
after `Ctrl+C` the output was:
```
^Cnpm verb lifecycle grpc@1.24.2~install: unsafe-perm in lifecycle true
npm verb lifecycle grpc@1.24.2~install: PATH: /home/matheo/.nvm/versions/node/v10.16.3/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/my/project/node_modules/grpc/node_modules/.bin:/my/project/node_modules/.bin:/home/matheo/.nvm/versions/node/v10.16.3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/matheo/.yarn/bin
npm verb lifecycle grpc@1.24.2~install: CWD: /my/project/node_modules/grpc
npm info lifecycle @firebase/firestore@1.7.0~install: @firebase/firestore@1.7.0
```

**Comment by matheo** [comment]
Now it's working fine, seems that the https download finds the requested file successfully now

**Comment by rturk** [comment]
maybe is related with https://github.com/grpc/grpc-node/issues/1086

**Comment by ruvany** [comment]
I have the same issue with macOS environment
Re-intalling Xcode solve the issue

```
sudo rm -rf /Library/Developer/CommandLineTools
xcode-select --install
```

**Comment by truongthuc** [comment]
I had the same issue with you @sachinkumaram-veoci  before.
Try to downgrade node version to v10.23.0, it's work smoot like a charm

**Comment by vwedesam** [comment]
> 
> 
> I had the same issue with you @sachinkumaram-veoci before.
> Try to downgrade node version to v10.23.0, it's work smoot like a charm

thanks - this solved mine

**Comment by beatsbybre** [comment]
Is there any solution to this that doesn't involve downgrading node?

**Comment by thuynt99** [comment]
if you get this error when run yarn install, try run this comman: `npm install grpc --verbose`.
It's work for me

**Comment by murgatroid99** [comment]
The `grpc` package is now deprecated. We recommend using `@grpc/grpc-js` instead.

**Comment by abhchand** [comment]
I'm also using `@grpc/grpc-js`. Downgrading to node `v14.17` fixed it for me as well. 

It seems like the installation is completely broken on newer versions of `node`. Not sure where the cutoff is, but I was previously using `v17.4` when it failed.

**Comment by murgatroid99** [comment]
We haven't published a `grpc` package for Node 17 or above. `@grpc/grpc-js` does not have this problem, and is compatible with Node 10+.

**Comment by lujakob** [comment]
For me using node v18 worked. (v16 did not work)

**Comment by SnehaParanjape-orange** [comment]
> For me using node v18 worked. (v16 did not work)

What sub-version of node 18 worked for you? 
18.14 and 18.16 are failing for me
