### ISSUE TITLE
npm ERR! Failed at the grpc@1.24.0 install script.

### ISSUE THREAD

**Issue by huturen** [grpc/grpc-node#1183]
Error as below:
```
npm ERR! Failed at the grpc@1.24.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-10-09T11_59_21_558Z-debug.log
Task quited with error: Task end with error: Error: Command failed: npm --registry=http://r.npm.oa.com install --production In file included from ../deps/grpc/third_party/upb/upb/msg.h:14:0, from ../deps/grpc/third_party/upb/upb/generated_util.h:10, from ../deps/grpc/src/core/ext/upb-generated/src/proto/grpc/gcp/transport_security_common.upb.h:12, from ../deps/grpc/src/core/tsi/alts/handshaker/transport_security_common_api.h:29, from ../deps/grpc/src/core/lib/security/credentials/alts/grpc_alts_credentials_options.h:26, from ../deps/grpc/src/core/lib/security/credentials/alts/alts_credentials.h:26, from ../deps/grpc/src/core/lib/security/credentials/alts/alts_credentials.cc:21: ../deps/grpc/third_party/upb/upb/upb.h:27:28: fatal error: upb/port_def.inc: No such file or directory compilation terminated. make: *** [Release/obj.target/grpc/deps/grpc/src/core/lib/security/credentials/alts/alts_credentials.o] Error 1 gyp ERR! build error gyp ERR! stack Error: `make` failed with exit code: 2 gyp ERR! stack at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23) gyp ERR! stack at ChildProcess.emit (events.js:198:13) gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12) gyp ERR! System Linux 3.10.107-1-tlinux2-0048 gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=~/dataServer/dataServer/src/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node" "--module_name=grpc_node" "--module_path=~/dataServer/dataServer/src/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc" "--napi_version=4" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64" gyp ERR! cwd ~/dataServer/dataServer/src/node_modules/grpc gyp ERR! node -v v10.16.0 gyp ERR! node-gyp -v v3.8.0 gyp ERR! not ok node-pre-gyp ERR! build error node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=~/dataServer/dataServer/src/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=~/dataServer/dataServer/src/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1) node-pre-gyp ERR! stack at ChildProcess. (~/dataServer/dataServer/src/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29) node-pre-gyp ERR! stack at ChildProcess.emit (events.js:198:13) node-pre-gyp ERR! stack at maybeClose (internal/child_process.js:982:16) node-pre-gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5) node-pre-gyp ERR! System Linux 3.10.107-1-tlinux2-0048 node-pre-gyp ERR! command "/usr/local/bin/node" "~/dataServer/dataServer/src/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library" node-pre-gyp ERR! cwd ~/dataServer/dataServer/src/node_modules/grpc node-pre-gyp ERR! node -v v10.16.0 node-pre-gyp ERR! node-pre-gyp -v v0.13.0 node-pre-gyp ERR! not ok npm ERR! code ELIFECYCLE npm ERR! errno 1 npm ERR! grpc@1.24.0 install: `node-pre-gyp install --fallback-to-build --library=static_library` npm ERR! Exit status 1 npm ERR! npm ERR! Failed at the grpc@1.24.0 install script. npm ERR! This is probably not a problem with npm. There is likely additional logging output above. npm ERR! A complete log of this run can be found in: npm ERR! /root/.npm/_logs/2019-10-09T11_59_21_558Z-debug.log (2)
```
dependency tree like below:
```
➜  DataServer git:(master) ✗ npm ls grpc 
dataserver@1.0.0 ~/DataServer
└─┬ @lag/ad-api@1.2.3
  └─┬ google-ads-api@3.4.2
    └─┬ google-ads-node@1.13.8
      └── grpc@1.24.0 
```

**Comment by matheo** [comment]
This error is gone for me without up/downgrading anything
I bet it's something about some bundles downloaded while it installs,
so it's basically an infrastructure issue.

**Comment by VincentMRA** [comment]
Any other solutions? I'm still facing this issue. 
I have node v12.13.0 
downgraded dependencies of grpc @1.23.3
This happened for me as well after upgrading to the latest firebase-tools

**Comment by santhoshlfms** [comment]
Any updates, same issue 
node version 10.17.0 and version 12.13.1
:(

**Comment by konradsofton** [comment]
Same issue. Just use Yarn

**Comment by AprilPolubiec** [comment]
Same issue with node@13.1.0... downgraded to grpc@1.23.3 but still getting the error

**Comment by jhimy-michel** [comment]
Delete the old node_modules and package.lock.json and then install the latest version for firebase. Hope this would help you. :)

**Comment by DmytroMysak** [comment]
Same issue with node v12.9.1
Having issue only in google cloud build during integration tests. As a temporary solution skip test.

**Comment by shahbazhaidry** [comment]
Same issue with node v13.5

**Comment by yasirjanjua** [comment]
> Delete the old node_modules and package.lock.json and then install the latest version for firebase. Hope this would help you. :)

Done it several times. Couldn't find the solution :disappointed:

**Comment by frederikocmr** [comment]
I have used Yarn instead.

In the folder of my package, where the error was occurring when using `npm link`

I just deleted the **node_modules** and **package.lock.json** and did the following steps:

`yarn && yarn build`

then 

`yarn link`

all of it worked well.

**Comment by StanfordLin** [comment]
was having trouble with Firebase cuz firebase needs grpc, so I went to package.json and updated firebase version to the current latest version "7.7.0". 
Yarn install and I don't see this error anymore

**Comment by waqaramjad** [comment]
same issue no solution worked

**Comment by DaniPB** [comment]
I fixed this error by using node v8.17.0

**Comment by scolcoin** [comment]
Same issue with node@13.1.0 grpc@1.24.0

**Comment by itzzmeakhi** [comment]
Any updates on this issue?

**Comment by scolcoin** [comment]
I try to cejecutar hyper fabric 1.4.4 and I have tried several versions of npm and node recommended by the system but the grpc is a problem. at the time of mounting the fabcar npm install the following error comes up
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! grpc@1.23.3 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the grpc@1.23.3 install script.

I also update and this error comes out:
npm install --save firebase
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! grpc@1.24.2 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the grpc@1.24.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
help please!

**Comment by JanuaryThomas** [comment]
Downgrade  the version of Node js

**Comment by MrEmanuel** [comment]
I found that the problem was that the package "request" was missing. 
Installing it before installing grpc fixed my issues. 
If you have a package depending on `grpc`, install `request` first.

`yarn add request` 
`yarn add grpc`

A colleague mentioned that some the package "spike" is used if request is not available and that doesn't play nice with the company proxy. Dunno if that's actually the problem, but adding `request`  did fix the issue.

**Comment by rupal-simform** [comment]
> Downgrade the version of Node js

This worked for me.
Mac OS Catalina

**Comment by AndrianD** [comment]
> > Delete the old node_modules and package.lock.json and then install the latest version for firebase. Hope this would help you. :)
> 
> Done it several times. Couldn't find the solution 😞

work for me..

**Comment by reymalahay** [comment]
First off, please do not upgrade/ downgrade your global environment libraries simply because a single library refuses to play nicely, save that as a super-last resort...

Try this:

1. Remove the lock file and the `node_modules` directory
```
rm -rfv package-lock.json node_modules
```

2. get the latest version of `firebase`
```
npm install --save-exact --save firebase@latest
```

3. check for vulnerabilities
```
npm audit fix
```

4. then run install
```
npm install
```

It worked for me with this combination:
```
node version: v13.7.0
npm version: 6.13.6
```

hth anyone who is still struggling...

**Comment by jvandy83** [comment]
reymalahay...saved my life.

node version: 13.5.0
npm version: 6.13.4

It worked for me!

**Comment by mctata** [comment]
@JanuaryThomas Thank you! It did work for me :)

**Comment by mctata** [comment]
> Downgrade the version of Node js

@JanuaryThomas Thank you! It did work for me :)

**Comment by JanuaryThomas** [comment]
> First off, please do not upgrade/ downgrade your global environment libraries simply because a single library refuses to play nicely, save that as a super-last resort...
> 
> Try this:
> 
> 1. Remove the lock file and the `node_modules` directory
> 
> ```
> rm -rfv package-lock.json node_modules
> ```
> 
> 1. get the latest version of `firebase`
> 
> ```
> npm install --save-exact --save firebase@latest
> ```
> 
> at the time of writing this, the latest version of `firebase` was `7.10.0`
> 
> 1. check for vulnerabilities
> 
> ```
> npm audit fix
> ```
> 
> 1. then run install
> 
> ```
> npm install
> ```
> 
> It worked for me with this combination:
> 
> ```
> node version: v13.7.0
> npm version: 6.13.6
> ```
> 
> hth anyone who is still struggling...

Good work around

**Comment by SteveRaskin** [comment]
@reymalahay
Thank you for pointing the way to the exit from today's visit to Dependency Hell

**Comment by isabelgk** [comment]
I am following the `grpc/grpc-web` Hello World [example](https://github.com/grpc/grpc-web/tree/master/net/grpc/gateway/examples/helloworld).

When I need to `npm install` grpc, I have the same error with `node-pre-gyp`. I have tried the suggested changes in grpc, Node, and npm versions without any luck.

```
13226 verbose pkgid grpc@1.24.2
13227 verbose cwd /home/ubuntu/grpc-web/net/grpc/gateway/examples/helloworld
13228 verbose Linux 4.15.0-96-generic
13229 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
13230 verbose node v13.12.0
13231 verbose npm  v6.14.4
13232 error code ELIFECYCLE
13233 error errno 6
13234 error grpc@1.24.2 install: `node-pre-gyp install --fallback-to-build --library=static_library`
13234 error Exit status 6
13235 error Failed at the grpc@1.24.2 install script.
13235 error This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by reymalahay** [comment]
@isabelgk 

do an `ls -l` to see if you have a `package-lock.json` file. if you do, delete it then run `npm install` again.

hth


> I am following the `grpc/grpc-web` Hello World [example](https://github.com/grpc/grpc-web/tree/master/net/grpc/gateway/examples/helloworld).
> 
> When I need to `npm install` grpc, I have the same error with `node-pre-gyp`. I have tried the suggested changes in grpc, Node, and npm versions without any luck.
> 
> ```
> 13226 verbose pkgid grpc@1.24.2
> 13227 verbose cwd /home/ubuntu/grpc-web/net/grpc/gateway/examples/helloworld
> 13228 verbose Linux 4.15.0-96-generic
> 13229 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
> 13230 verbose node v13.12.0
> 13231 verbose npm  v6.14.4
> 13232 error code ELIFECYCLE
> 13233 error errno 6
> 13234 error grpc@1.24.2 install: `node-pre-gyp install --fallback-to-build --library=static_library`
> 13234 error Exit status 6
> 13235 error Failed at the grpc@1.24.2 install script.
> 13235 error This is probably not a problem with npm. There is likely additional logging output above.
> ```
> 
> I also found another user having the same issue on [StackOverflow](https://stackoverflow.com/questions/59399488/error-when-installing-grpc-js-recently-states-bug-in-node-pre-gyp-install-fal).
> 
> Any suggestions? I'm on Ubuntu 18.04 and behind a corporate proxy, if that makes a difference.

**Comment by jaswantdhayalxebia** [comment]
> I found that the problem was that the package `request` was missing.
> Installing it before installing grpc fixed my issues.
> If you have a package depending on `grpc`, install `request` first.
> 
> `yarn add request`
> `yarn add grpc`
> 
> A colleague mentioned that the package "spike" is used if request is not available and that doesn't play nice with the company proxy. Dunno if that's actually the problem, but adding `request` did fix the issue.

This solution is worked for me

**Comment by nocraza** [comment]
> First off, please do not upgrade/ downgrade your global environment libraries simply because a single library refuses to play nicely, save that as a super-last resort...
> 
> Try this:
> 
> 1. Remove the lock file and the `node_modules` directory
> 
> ```
> rm -rfv package-lock.json node_modules
> ```
> 
> 1. get the latest version of `firebase`
> 
> ```
> npm install --save-exact --save firebase@latest
> ```
> 
> at the time of writing this, the latest version of `firebase` was `7.10.0`
> 
> 1. check for vulnerabilities
> 
> ```
> npm audit fix
> ```
> 
> 1. then run install
> 
> ```
> npm install
> ```
> 
> It worked for me with this combination:
> 
> ```
> node version: v13.7.0
> npm version: 6.13.6
> ```
> 
> hth anyone who is still struggling...

This solution worked for me. I used yarn though.

node version: v13.2.0
yarn version: 1.22.4

**Comment by duduwe** [comment]
> 
> 
> I fixed this error by downgrading my node version from the latest (13.1.0) to 12.13.0

Downgrading also worked for me.

**Comment by SoniaKaudjhis** [comment]
I have the same issue with Linux 18.04 and node 14.0.0
It seems it can't find the tar file for linux 64-bit arch 
Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://node-precompiled-binaries.grpc.io/grpc/v1.20.2/node-v83-linux-x64-glibc.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for grpc@1.20.2 and node@14.0.0 (node-v83 ABI, glibc) (falling back to source compile with node

**Comment by dipshojol** [comment]
> First off, please do not upgrade/ downgrade your global environment libraries simply because a single library refuses to play nicely, save that as a super-last resort...
> 
> Try this:
> 
> 1. Remove the lock file and the `node_modules` directory
> 
> ```
> rm -rfv package-lock.json node_modules
> ```
> 
> 1. get the latest version of `firebase`
> 
> ```
> npm install --save-exact --save firebase@latest
> ```
> 
> at the time of writing this, the latest version of `firebase` was `7.10.0`
> 
> 1. check for vulnerabilities
> 
> ```
> npm audit fix
> ```
> 
> 1. then run install
> 
> ```
> npm install
> ```
> 
> It worked for me with this combination:
> 
> ```
> node version: v13.7.0
> npm version: 6.13.6
> ```
> 
> hth anyone who is still struggling...

worked. thankz

**Comment by enigmaticmahesh** [comment]
> > I found that the problem was that the package `request` was missing.
> > Installing it before installing grpc fixed my issues.
> > If you have a package depending on `grpc`, install `request` first.
> > `yarn add request`
> > `yarn add grpc`
> > A colleague mentioned that the package "spike" is used if request is not available and that doesn't play nice with the company proxy. Dunno if that's actually the problem, but adding `request` did fix the issue.
> 
> This solution is worked for me

This Worked for me.... thank you

**Comment by andreijco** [comment]
> > > I found that the problem was that the package `request` was missing.
> > > Installing it before installing grpc fixed my issues.
> > > If you have a package depending on `grpc`, install `request` first.
> > > `yarn add request`
> > > `yarn add grpc`
> > > A colleague mentioned that the package "spike" is used if request is not available and that doesn't play nice with the company proxy. Dunno if that's actually the problem, but adding `request` did fix the issue.
> > 
> > 
> > This solution is worked for me
> 
> This Worked for me.... thank you

Yes this one worked for me to solve heroku failed build .. thank you

**Comment by srishab** [comment]
> First off, please do not upgrade/ downgrade your global environment libraries simply because a single library refuses to play nicely, save that as a super-last resort...
> 
> Try this:
> 
>     1. Remove the lock file and the `node_modules` directory
> 
> 
> ```
> rm -rfv package-lock.json node_modules
> ```
> 
>     1. get the latest version of `firebase`
> 
> 
> ```
> npm install --save-exact --save firebase@latest
> ```
> 
> at the time of writing this, the latest version of `firebase` was `7.10.0`
> 
>     1. check for vulnerabilities
> 
> 
> ```
> npm audit fix
> ```
> 
>     1. then run install
> 
> 
> ```
> npm install
> ```
> 
> It worked for me with this combination:
> 
> ```
> node version: v13.7.0
> npm version: 6.13.6
> ```
> 
> hth anyone who is still struggling.

thanks bro

**Comment by jimmy30** [comment]
> First off, please do not upgrade/ downgrade your global environment libraries simply because a single library refuses to play nicely, save that as a super-last resort...
> 
> Try this:
> 
> 1. Remove the lock file and the `node_modules` directory
> 
> ```
> rm -rfv package-lock.json node_modules
> ```
> 
> 1. get the latest version of `firebase`
> 
> ```
> npm install --save-exact --save firebase@latest
> ```
> 
> at the time of writing this, the latest version of `firebase` was `7.10.0`
> 
> 1. check for vulnerabilities
> 
> ```
> npm audit fix
> ```
> 
> 1. then run install
> 
> ```
> npm install
> ```
> 
> It worked for me with this combination:
> 
> ```
> node version: v13.7.0
> npm version: 6.13.6
> ```
> 
> hth anyone who is still struggling...

Great, this worked. Thanks

**Comment by JPSantistebanQ** [comment]
Fixed downgrade to Node LTS last version 12.18.2

**Comment by babytiger0929** [comment]
> Delete the old node_modules and package.lock.json and then install the latest version for firebase. Hope this would help you. :)

This is working well for me :) 👍

**Comment by jnisperuza** [comment]
> First off, please do not upgrade/ downgrade your global environment libraries simply because a single library refuses to play nicely, save that as a super-last resort...
> 
> Try this:
> 
> 1. Remove the lock file and the `node_modules` directory
> 
> ```
> rm -rfv package-lock.json node_modules
> ```
> 
> 1. get the latest version of `firebase`
> 
> ```
> npm install --save-exact --save firebase@latest
> ```
> 
> at the time of writing this, the latest version of `firebase` was `7.10.0`
> 
> 1. check for vulnerabilities
> 
> ```
> npm audit fix
> ```
> 
> 1. then run install
> 
> ```
> npm install
> ```
> 
> It worked for me with this combination:
> 
> ```
> node version: v13.7.0
> npm version: 6.13.6
> ```
> 
> hth anyone who is still struggling...

This really works

**Comment by eladcandroid** [comment]
Please implement @reymalahay solution on the repo - maybe just change firebase version to "firebase": "7.21.0" on pacakge.json.

**Comment by mrghasemi1992** [comment]
> Error as below:
> 
> ```
> npm ERR! Failed at the grpc@1.24.0 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2019-10-09T11_59_21_558Z-debug.log
> Task quited with error: Task end with error: Error: Command failed: npm --registry=http://r.npm.oa.com install --production In file included from ../deps/grpc/third_party/upb/upb/msg.h:14:0, from ../deps/grpc/third_party/upb/upb/generated_util.h:10, from ../deps/grpc/src/core/ext/upb-generated/src/proto/grpc/gcp/transport_security_common.upb.h:12, from ../deps/grpc/src/core/tsi/alts/handshaker/transport_security_common_api.h:29, from ../deps/grpc/src/core/lib/security/credentials/alts/grpc_alts_credentials_options.h:26, from ../deps/grpc/src/core/lib/security/credentials/alts/alts_credentials.h:26, from ../deps/grpc/src/core/lib/security/credentials/alts/alts_credentials.cc:21: ../deps/grpc/third_party/upb/upb/upb.h:27:28: fatal error: upb/port_def.inc: No such file or directory compilation terminated. make: *** [Release/obj.target/grpc/deps/grpc/src/core/lib/security/credentials/alts/alts_credentials.o] Error 1 gyp ERR! build error gyp ERR! stack Error: `make` failed with exit code: 2 gyp ERR! stack at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23) gyp ERR! stack at ChildProcess.emit (events.js:198:13) gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12) gyp ERR! System Linux 3.10.107-1-tlinux2-0048 gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=~/dataServer/dataServer/src/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node" "--module_name=grpc_node" "--module_path=~/dataServer/dataServer/src/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc" "--napi_version=4" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64" gyp ERR! cwd ~/dataServer/dataServer/src/node_modules/grpc gyp ERR! node -v v10.16.0 gyp ERR! node-gyp -v v3.8.0 gyp ERR! not ok node-pre-gyp ERR! build error node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=~/dataServer/dataServer/src/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=~/dataServer/dataServer/src/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1) node-pre-gyp ERR! stack at ChildProcess. (~/dataServer/dataServer/src/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29) node-pre-gyp ERR! stack at ChildProcess.emit (events.js:198:13) node-pre-gyp ERR! stack at maybeClose (internal/child_process.js:982:16) node-pre-gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5) node-pre-gyp ERR! System Linux 3.10.107-1-tlinux2-0048 node-pre-gyp ERR! command "/usr/local/bin/node" "~/dataServer/dataServer/src/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library" node-pre-gyp ERR! cwd ~/dataServer/dataServer/src/node_modules/grpc node-pre-gyp ERR! node -v v10.16.0 node-pre-gyp ERR! node-pre-gyp -v v0.13.0 node-pre-gyp ERR! not ok npm ERR! code ELIFECYCLE npm ERR! errno 1 npm ERR! grpc@1.24.0 install: `node-pre-gyp install --fallback-to-build --library=static_library` npm ERR! Exit status 1 npm ERR! npm ERR! Failed at the grpc@1.24.0 install script. npm ERR! This is probably not a problem with npm. There is likely additional logging output above. npm ERR! A complete log of this run can be found in: npm ERR! /root/.npm/_logs/2019-10-09T11_59_21_558Z-debug.log (2)
> ```
> 
> dependency tree like below:
> 
> ```
> ➜  DataServer git:(master) ✗ npm ls grpc 
> dataserver@1.0.0 ~/DataServer
> └─┬ @lag/ad-api@1.2.3
>   └─┬ google-ads-api@3.4.2
>     └─┬ google-ads-node@1.13.8
>       └── grpc@1.24.0 
> ```

In `package.json` firebase version fixed to 7.5.2 `"firebase": "7.5.2"`. I set it to be updated to the latest version `"firebase": "^7.5.2"` but before doing that I removed the `node_modules` folder and `package-lock.json`. Now get rid of the error.

**Comment by kennyish1173** [comment]
This worked for me! Thank you so mucho!

```
node version: v12.18.3
npm version: 6.14.6
```

**Comment by schapiroalexis** [comment]
> was having trouble with Firebase cuz firebase needs grpc, so I went to package.json and updated firebase version to the current latest version "7.7.0".
> Yarn install and I don't see this error anymore

this worked for me. I also removed (before) node-pre-gryp and then updated the firebase version

**Comment by YogPanjarale** [comment]
> First off, please do not upgrade/ downgrade your global environment libraries simply because a single library refuses to play nicely, save that as a super-last resort...
> 
> Try this:
> 
> 1. Remove the lock file and the `node_modules` directory
> 
> ```
> rm -rfv package-lock.json node_modules
> ```
> 
> 1. get the latest version of `firebase`
> 
> ```
> npm install --save-exact --save firebase@latest
> ```
> 
> at the time of writing this, the latest version of `firebase` was `7.10.0`
> 
> 1. check for vulnerabilities
> 
> ```
> npm audit fix
> ```
> 
> 1. then run install
> 
> ```
> npm install
> ```
> 
> It worked for me with this combination:
> 
> ```
> node version: v13.7.0
> npm version: 6.13.6
> ```
> 
> hth anyone who is still struggling...

It worked for me

**Comment by Histamina** [comment]
> In `package.json` firebase version fixed to 7.5.2 `"firebase": "7.5.2"`. I set it to be updated to the latest version `"firebase": "^7.5.2"` but before doing that I removed the `node_modules` folder and `package-lock.json`. Now get rid of the error.

This worked for me as well and I didn't even have to remove `node_modules` or `package-lock.json`.

**Comment by damiththiwanka** [comment]
> First off, please do not upgrade/ downgrade your global environment libraries simply because a single library refuses to play nicely, save that as a super-last resort...
> 
> Try this:
> 
> 1. Remove the lock file and the `node_modules` directory
> 
> ```
> rm -rfv package-lock.json node_modules
> ```
> 
> 1. get the latest version of `firebase`
> 
> ```
> npm install --save-exact --save firebase@latest
> ```
> 
> at the time of writing this, the latest version of `firebase` was `7.10.0`
> 
> 1. check for vulnerabilities
> 
> ```
> npm audit fix
> ```
> 
> 1. then run install
> 
> ```
> npm install
> ```
> 
> It worked for me with this combination:
> 
> ```
> node version: v13.7.0
> npm version: 6.13.6
> ```
> 
> hth anyone who is still struggling...

Thanks @YogPanjarale. Works for me 
npm -v 6.14.11
node -v v14.16.0

**Comment by sarbh20** [comment]
> > First off, please do not upgrade/ downgrade your global environment libraries simply because a single library refuses to play nicely, save that as a super-last resort...
> > Try this:
> > 
> > 1. Remove the lock file and the `node_modules` directory
> > 
> > ```
> > rm -rfv package-lock.json node_modules
> > ```
> > 
> > 
> > 
> > 1. get the latest version of `firebase`
> > 
> > ```
> > npm install --save-exact --save firebase@latest
> > ```
> > 
> > 
> > at the time of writing this, the latest version of `firebase` was `7.10.0`
> > 
> > 1. check for vulnerabilities
> > 
> > ```
> > npm audit fix
> > ```
> > 
> > 
> > 
> > 1. then run install
> > 
> > ```
> > npm install
> > ```
> > 
> > 
> > It worked for me with this combination:
> > ```
> > node version: v13.7.0
> > npm version: 6.13.6
> > ```
> > 
> > 
> > hth anyone who is still struggling...
> 
> It worked for me

You are god sent. I spent 2hrs installing, uninstalling python, msvc, firebase, npm .

**Comment by maayaankk** [comment]
1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*

This should help

**Comment by EAvila34** [comment]
> 
> 
> > First off, please do not upgrade/ downgrade your global environment libraries simply because a single library refuses to play nicely, save that as a super-last resort...
> > Try this:
> > 
> > 1. Remove the lock file and the `node_modules` directory
> > 
> > ```
> > rm -rfv package-lock.json node_modules
> > ```
> > 
> > 
> > 
> > 1. get the latest version of `firebase`
> > 
> > ```
> > npm install --save-exact --save firebase@latest
> > ```
> > 
> > 
> > at the time of writing this, the latest version of `firebase` was `7.10.0`
> > 
> > 1. check for vulnerabilities
> > 
> > ```
> > npm audit fix
> > ```
> > 
> > 
> > 
> > 1. then run install
> > 
> > ```
> > npm install
> > ```
> > 
> > 
> > It worked for me with this combination:
> > ```
> > node version: v13.7.0
> > npm version: 6.13.6
> > ```
> > 
> > 
> > hth anyone who is still struggling...
> 
> Good work around

It's working on SO Windows 10, Ionic 3 node 14

**Comment by Jeluchez** [comment]
> was having trouble with Firebase cuz firebase needs grpc, so I went to package.json and updated firebase version to the current latest version "7.7.0".
> Yarn install and I don't see this error anymore

This worked for me.

**Comment by primeloop** [comment]
> > I found that the problem was that the package `request` was missing.
> > Installing it before installing grpc fixed my issues.
> > If you have a package depending on `grpc`, install `request` first.
> > `yarn add request`
> > `yarn add grpc`
> > A colleague mentioned that the package "spike" is used if request is not available and that doesn't play nice with the company proxy. Dunno if that's actually the problem, but adding `request` did fix the issue.
> 
I was trying to deploy cloud functions (or say run npm install for firebase cloud functions folder) this solution worked in my case

**Comment by menemelkatan** [comment]
> 
> 
> was having trouble with Firebase cuz firebase needs grpc, so I went to package.json and updated firebase version to the current latest version "7.7.0".
> Yarn install and I don't see this error anymore

Thanks a lot it worked with me
