### ISSUE TITLE
Compile time error "Critical dependency: the request of a dependency is an expression"

### ISSUE THREAD

**Issue by hlb8122** [grpc/grpc-node#1185]
Interaction with quasar causes a compile time error.
https://github.com/quasarframework/quasar/issues/5605

**Describe the bug**
The grpc library gives the following error at compile time:
```
WARNING  Compiled with 3 warnings                                                                                                                                 12:45:49 AM

 warning  in ./node_modules/grpc/src/grpc_extension.js

Critical dependency: the request of a dependency is an expression

 warning  in ./node_modules/grpc/node_modules/node-pre-gyp/lib/pre-binding.js

Critical dependency: the request of a dependency is an expression

 warning  in ./node_modules/grpc/node_modules/node-pre-gyp/lib/util/versioning.js

Critical dependency: the request of a dependency is an expression
```

Once the app has booted the following error is raised:
```
[Vue warn]: Error in mounted hook: "Error: Cannot find module '/home/harry/projects/minimal/node_modules/grpc/package.json'"

found in

---> <App> at src/App.vue
       <Root>
```

```
Error: Cannot find module '/home/harry/projects/minimal/node_modules/grpc/package.json'
    at webpackEmptyContext (eval at ./node_modules/grpc/node_modules/node-pre-gyp/lib sync recursive (app.js:3003), <anonymous>:2:10)
    at Object.exports.find (webpack-internal:///./node_modules/grpc/node_modules/node-pre-gyp/lib/pre-binding.js:20)
    at Object.eval (webpack-internal:///./node_modules/grpc/src/grpc_extension.js:29)
    at eval (webpack-internal:///./node_modules/grpc/src/grpc_extension.js:64)
    at Object../node_modules/grpc/src/grpc_extension.js (app.js:3467)
    at __webpack_require__ (app.js:770)
    at fn (app.js:130)
    at eval (webpack-internal:///./node_modules/grpc/src/client_interceptors.js:144)
    at Object../node_modules/grpc/src/client_interceptors.js (app.js:3420)
    at __webpack_require__ (app.js:770)
```

https://github.com/hlb8122/minimal-failure-example

**To Reproduce**
1. Initialize a new project with quasar/cli
2. npm i grpc
3. Import and use grpc

**Expected behavior**
Ability to use the library

**Platform:**
OS: Ubuntu 19.04
Node: 10, 11, 12, 13
NPM: 6
Yarn: 1
Browsers: Firefox
Electron: 5

**Additional context**
Tried various permutations of the gRPC library all with no luck. The minimal example linked has only gRPC.

**Comment by murgatroid99** [comment]
This appears to be the result of a `require` call with a non-constant string, specifically here: https://github.com/grpc/grpc-node/blob/master/packages/grpc-native-core/src/grpc_extension.js#L32. That is necessary for the library to function, so as long as this quasar framework doesn't support that, `grpc` isn't going to work with quasar.

You may want to instead try the `@grpc/grpc-js` library. It has almost exactly the same API and supports all of the same basic functionality as `grpc`, and I don't believe it will have that issue.

**Comment by hlb8122** [comment]
@murgatroid99 I originally started playing with grpc-js but performance is important here so was drawn to grpc-node library.
