### ISSUE TITLE
Regression with writable streams and grpc v1.24.2

### ISSUE THREAD

**Issue by fbiville** [grpc/grpc-node#1190]
### Problem description
Calling [`end`](https://nodejs.org/api/stream.html#stream_writable_end_chunk_encoding_callback) on a writable stream does not seem to trigger the [`'finish'`](https://nodejs.org/api/stream.html#stream_event_finish) event.

While this does not seem related to gRPC at first, we have a few failing tests after a gRPC upgrade.

### Reproduction steps

1. git clone https://github.com/projectriff/node-function-invoker
2. change `grpc` version from `1.24.1` to `1.24.2` in `package.json`
3. run `npm ci && npm test`
4. for more detailed errors, pick any failing test, replace `const logger = require('util').debuglog('riff');` with `const logger = console.dir;` in `lib/streaming-pipeline.js` and you'll see that the `finish` event handler in the failing test is not called, despite [the call to end](https://github.com/projectriff/node-function-invoker/blob/30a0a48ec40a412946e3d2393bf26c0a3399d00e/lib/streaming-pipeline.js#L58)

### Environment
 - Mac OS 10.14.6, x86_64
 - Node version: 13.1.0
 - Node installation method [e.g. nvm]: homebrew
 - If applicable, compiler version [e.g. clang 3.8.0-2ubuntu4]
 - Package name and version [e.g. gRPC@1.12.0]: grpc@1.24.2

**Comment by murgatroid99** [comment]
Can you please include a simple code snippet that reproduces this problem?

**Comment by fbiville** [comment]
My local installation seems bogus. I'll reopen if I manage to reproduce the issue on another machine.
