### ISSUE TITLE
node-pre-gyp fails with grpc v1.24.1 and compilation from sources fail

### ISSUE THREAD

**Issue by fbiville** [grpc/grpc-node#1191]
### Problem description
node-pre-gyp fails with grpc v1.24.1:
```
node-pre-gyp WARN Using needle for node-pre-gyp https download
node-pre-gyp WARN Tried to download(404): https://node-precompiled-binaries.grpc.io/grpc/v1.24.1/node-v79-darwin-x64-unknown.tar.gz
node-pre-gyp WARN Pre-built binaries not found for grpc@1.24.1 and node@13.1.0 (node-v79 ABI, unknown) (falling back to source compile with node-gyp)
```
and subsequent compilation from sources spits a big numbers of compilation warnings before failing.

### Reproduction steps
1. git clone https://github.com/projectriff/node-function-invoker
2. git checkout 30a0a48ec40a412946e3d2393bf26c0a3399d00e (that's `master` at the time of writing)
3. npm ci

### Environment
 - Mac OS 10.14.6, x86_64
 - Node version: 13.1.0
 - Node installation method [e.g. nvm]: homebrew
 - If applicable, compiler version [e.g. clang 3.8.0-2ubuntu4]
 - Package name and version [e.g. gRPC@1.12.0]: grpc@1.24.1

**Comment by fbiville** [comment]
For some reason, I can reproduce this only on my laptop.
Even `npm cache clean --force` does not change the result.

**Comment by murgatroid99** [comment]
Support for Node 13 was added in grpc 1.24.2. That includes fixing a compilation error when compiling the library for use on Node 13.
