### ISSUE TITLE
json_name not working, forcing to camelCase

### ISSUE THREAD

**Issue by agustinkassis** [grpc/grpc-node#1192]
### Problem description
Responses messages not using the json_name provided on proto file

### Reproduction steps
Example on this API.
https://api.lightning.community/#grpc-request-getinforequest
With the proto file: https://github.com/lightningnetwork/lnd/blob/master/lnrpc/rpc.proto
The response should respect the json_name provided but it doesnt, all the variables are camelCase, I even tried with:
```js
const packageDefinition = protoLoader.loadSync('rpc.proto', {
  keepCase: false
});
```

### Environment
 - OS name, version and architecture: MacOS
 - Node version: v12.12.0
 - Node installation method: nvm
 - Package name and version: v1.25.0-pre1

### Additional context
Not sure if its a problem on proto-loader or grpc itself.

**Comment by murgatroid99** [comment]
The way the `proto-loader` and `grpc` libraries generate objects is not intended to be the JSON encoding of the object, so the `json_name` option should not be used.
