### ISSUE TITLE
The precompiled binaries server is unreliable at serving files

### ISSUE THREAD

**Issue by AaronFriel** [grpc/grpc-node#1214]
### Problem description

The server that hosts GRPC binaries sporadically fails to serve requests and/or closes open sockets during build. (I haven't done a packet capture, but it looks like either the HTTPS server is down or it has a low socket timeout configured.)

### Reproduction steps

We have a build server running in AWS us-west-2, the build jobs run in a Docker container which we build and host ourselves in Elastic Container Registry. When our build job does an `npm install`, it sometimes logs out this:

**Successful build**:
```log
34 > node-pre-gyp install --fallback-to-build --library=static_library
35 node-pre-gyp info it worked if it ends with ok
36 node-pre-gyp info using node-pre-gyp@0.13.0
37 node-pre-gyp info using node@10.16.3 | linux | x64
38 node-pre-gyp WARN Using needle for node-pre-gyp https download 
39 node-pre-gyp info check checked for "/builds/monorepo/pulumi/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node" (not found)
40 node-pre-gyp http GET https://node-precompiled-binaries.grpc.io/grpc/v1.21.1/node-v64-linux-x64-glibc.tar.gz
41 node-pre-gyp http 200 https://node-precompiled-binaries.grpc.io/grpc/v1.21.1/node-v64-linux-x64-glibc.tar.gz
42 node-pre-gyp info install unpacking node-v64-linux-x64-glibc/grpc_node.node
43 node-pre-gyp info tarball done parsing tarball
```

And it sometimes logs out this:

```log
> node-pre-gyp install --fallback-to-build --library=static_library
30 node-pre-gyp info it worked if it ends with ok
31 node-pre-gyp info using node-pre-gyp@0.13.0
32 node-pre-gyp info using node@10.16.3 | linux | x64
33 node-pre-gyp WARN Using needle for node-pre-gyp https download 
34 node-pre-gyp info check checked for "/builds/twochairs/monorepo/pulumi/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node" (not found)
35 node-pre-gyp http GET https://node-precompiled-binaries.grpc.io/grpc/v1.21.1/node-v64-linux-x64-glibc.tar.gz
36 node-pre-gyp WARN Pre-built binaries not installable for grpc@1.21.1 and node@10.16.3 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 
37 node-pre-gyp WARN Hit error socket hang up 
```

The latter fails because we don't have `make` in our Docker image.

### Environment
 - Docker image is `debian:10-slim`
 - Node version is `10.16.3`
 - Node installed by copying from static files
 - n/a
 - grpc version is `1.21.1`

### Additional context

This error seems to persist for several minutes, as several consecutive builds will fail, then several will succeed in a row.

Builds that fail always fail for the same reason: "WARN Hit error socket hang up".

**Comment by nicolasnoble** [comment]
That's peculiar. The hosting environment is Google Compute Storage itself, with a cloudflare front in order to provide a proxy for people in countries where Google is censored, like China.

Your report means that there's an issue with CloudFlare and/or Google Compute Storage.

**Comment by AaronFriel** [comment]
Is your build process touching/replacing files periodically?

**Comment by murgatroid99** [comment]
We never touch or replace those files after the initial upload.

**Comment by AaronFriel** [comment]
Very frustrating. We don't have any other issues pulling packages, doing `npm install`, etc. I have no idea what could cause the socket to be dropped for just this URL.

**Comment by nicolasnoble** [comment]
Having a bit more logs about what's going on could potentially help a bit, but this isn't just a server sitting underneath someone's desk, this is CloudFlare and Google Storage we're talking about here, so this might require quite some more heavyweight troubleshooting than usual.

That being said, the list of binaries we're publishing is fairly easy to grab: https://node-precompiled-binaries.grpc.io/ which means that a nearer mirror could be created. The npm installation flags has a way to handle alternative mirrors, using `--grpc_binary_host_mirror=https://some.other.url/`

**Comment by AaronFriel** [comment]
Yeah, I see the Cloudflare and GCP headers when I make the request myself, so it's definitely mysterious as we aren't using any proxies right now. I will close, this will require a bit of investigation to figure out if there's something misbehaving with our build bots.
