### ISSUE TITLE
grpc.lb_policy_name is not working

### ISSUE THREAD

**Issue by tracy-liucui** [grpc/grpc-node#1215]
### Problem description
I have the grpc client config like following, but the load balancer doesn't work

```javascript
import grpc from 'grpc';
import { PodRequest } from '../../gen/proto/mock_pb';
import { EchoClient } from '../../gen/proto/mock_grpc_pb';

export const echoClient = new EchoClient(
  'dns:///main.namespace:5000',
  grpc.credentials.createInsecure(),
  {
    'grpc.lb_policy_name': 'round_robin',
    'grpc.dns_min_time_between_resolutions_ms': 500,
    'grpc.keepalive_timeout_ms': 1000,
    'grpc.dns_enable_srv_queries': 1,
  }
);
```
I saw the`Load Balancing` is supported by grpc package, but didn't find any document about how to make it work. Not sure if I am doing something wrong?

### Reproduction steps
1. compile the proto file with `grpc_tools_node_protoc`
2. have the grpc server running in k8s with 3 pods
3. create the  stub like above
4. the load balancer doesn't work(always hit the same pod)

### Environment
 - OS name, version and architecture: [e.g. MacOS 10.14.6]
 - Node version [e.g. 10.16.3]
 - Node installation method [e.g. nvm]
 - Package name and version [e.g. gRPC@1.24.2]

**Comment by murgatroid99** [comment]
Can you try setting the environment variable `GRPC_DNS_RESOLVER=ares`? It looks like only the ares resolver handles the `grpc.dns_enable_srv_queries` option, and that resolver has not yet been made the default for the Node grpc library.

**Comment by tracy-liucui** [comment]
@murgatroid99 Thanks!

The issue is because our server was not headless, now it is working properly!
