### ISSUE TITLE
Implement client retries in grpc-js

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc-node#1221]
We have had some reports that some customers are being adversely impacted by the missing retry behavior in grpc-js. In particular, apparently some auth errors encountered in the wild are transient, so when those failures do occur, a client with retries enabled will retry the call and eventually successfully authenticate, but a client without retries will immediately report an error to the user.

**Comment by lokoArt** [comment]
Any progress on this one? Or maybe a guide how to handle errors in this client implementation? At which errors we should retry and at which we should create a new client?

**Comment by khacminh** [comment]
still waiting for this feature

**Comment by Veath** [comment]
@murgatroid99

**Comment by murgatroid99** [comment]
Client retries are now implemented in version 1.8.x, as specified [here](https://github.com/grpc/proposal/blob/master/A6-client-retries.md).
