### ISSUE TITLE
14 UNAVAILABLE: failed to connect to all addresses

### ISSUE THREAD

**Issue by SeanDez** [grpc/grpc-node#1240]
### Problem description

When running `jest --watch` on a test suite that uses google cloud firestore/testing, I get the following error:

```
14 UNAVAILABLE: failed to connect to all addresses

      at Object.<anonymous>.exports.createStatusError (node_modules/grpc/src/common.js:91:15)
      at Object.onReceiveStatus (node_modules/grpc/src/client_interceptors.js:1209:28)
      at InterceptingListener.Object.<anonymous>.InterceptingListener._callNext (node_modules/grpc/src/client_interceptors.js:568:42)
      at InterceptingListener.Object.<anonymous>.InterceptingListener.onReceiveStatus (node_modules/grpc/src/client_interceptors.js:618:8)
      at callback (node_modules/grpc/src/client_interceptors.js:847:24)
```

### Reproduction steps
Give very precise steps you've discovered to reproduce your problem. If possible and applicable, provide us with a repository we can clone that contains a reproduction case. Also if possible and applicable, please include a Dockerfile that exhibits the problem if it's specific to a certain environment. Bug reports with no reproduction steps will be closed.

1. Initial setup: install through npm: jest, firebase/testing, firebase-admin, firestore. I believe grpc will install as a dependency
2. Write the code given below
3. Run `jest --watch` and the error will show in terminal.

```
const createTestDatabase = (credentials): any => {
  return firebaseTesting
    .initializeTestApp({
      projectId: 'testProject',
      auth: credentials
    })
    .firestore();
};

const nullAllApps = firebaseTesting
  .apps().map(app => app.delete());

// --------------- One Time,

// acts as unAuth user
const noAuthTestDatabase = createTestDatabase(null);
setDatabase(noAuthTestDatabase);
const db = new FirestoreConnection('testShopDomain', noAuthTestDatabase);


// --------------- Before / After

beforeEach(() => {
});


afterEach(async () => {
  await Promise.all(nullAllApps);
  await firebaseTesting.clearFirestoreData({
    projectId : "testProject"
  })
});


test("creates new record", () => {
  const addedDocument = db
    .createNew(RecordTypes.globalRule, {
      storeId : "dummyStoreId"
      , globalPercent : 40
    });
  
  expect(addedDocument).toEqual({
    storeId : "dummyStoreId"
    , globalPercent : 40
    , badProp : 0
  });
});
```

### Environment
 - OS name, version and architecture: Lubuntu 18.04
 - Node version 12.4.0
 - Node installation method: NVM
 - If applicable, compiler version [e.g. clang 3.8.0-2ubuntu4]
 - Package name and version. I typed grpc --version but `command not found`, how can I find this?

### Additional context
Add any other context about the problem here. If possible, attach full logs. Do not try to omit anything for brevity, but instead include absolutely everything. Please try and set your operating system's locale to English, so that logs contain error messages in the English language.

```
test("creates new record", () => { // line 53 where the error is given
  const addedDocument = db
    .createNew(RecordTypes.globalRule, {
      storeId : "dummyStoreId"
      , globalPercent : 40
    });
  
  expect(addedDocument).toEqual({
    storeId : "dummyStoreId"
    , globalPercent : 40
    , badProp : 0
  });
});
```

Full terminal:

```
  Warning, FIREBASE_CONFIG and GCLOUD_PROJECT environment variables are missing. Initializing firebase-admin will fail

 FAIL  functions/src/classes/__tests__/FirestoreConnection.test.ts (18.488s)
  ✕ creates new record (308ms)

  ● creates new record

    expect(received).toEqual(expected) // deep equality

    - Expected
    + Received

    - Object {
    -   "badProp": 0,
    -   "globalPercent": 40,
    -   "storeId": "dummyStoreId",
    - }
    + Promise {}

      58 |     });
      59 |   
    > 60 |   expect(addedDocument).toEqual({
         |                         ^
      61 |     storeId : "dummyStoreId"
      62 |     , globalPercent : 40
      63 |     , badProp : 0

      at Object.<anonymous> (functions/src/classes/__tests__/FirestoreConnection.test.ts:60:25)

  ● creates new record

    14 UNAVAILABLE: failed to connect to all addresses

      at Object.<anonymous>.exports.createStatusError (node_modules/grpc/src/common.js:91:15)
      at Object.onReceiveStatus (node_modules/grpc/src/client_interceptors.js:1209:28)
      at InterceptingListener.Object.<anonymous>.InterceptingListener._callNext (node_modules/grpc/src/client_interceptors.js:568:42)
      at InterceptingListener.Object.<anonymous>.InterceptingListener.onReceiveStatus (node_modules/grpc/src/client_interceptors.js:618:8)
      at callback (node_modules/grpc/src/client_interceptors.js:847:24)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        33.765s
Ran all test suites related to changed files.
```

I do not believe passing credentials to firebase-admin is needed during testing. The docs for `firebase/testing` state the database should receive unauth writes in the case of no given credentials.

**Comment by murgatroid99** [comment]
Your full terminal log says "Warning, FIREBASE_CONFIG and GCLOUD_PROJECT environment variables are missing. Initializing firebase-admin will fail". Maybe that's the problem.

**Comment by SeanDez** [comment]
@murgatroid99 I have removed the `firebase-admin` import since `@firebase/testing` didn't need it. This also cleared the error you mention.

I've also found that the initial error may have been caused because the server/emulator was not found by gRPC, I ran `firebase serve --only functions,firestore`. Terminal showed emulators running on different ports for both services. Rerunning `jest --watch` now produces a slightly different error:

```
 2 UNKNOWN:

      at Object.<anonymous>.exports.createStatusError (node_modules/grpc/src/common.js:91:15)
      at Object.onReceiveStatus (node_modules/grpc/src/client_interceptors.js:1209:28)
      at InterceptingListener.Object.<anonymous>.InterceptingListener._callNext (node_modules/grpc/src/client_interceptors.js:568:42)
      at InterceptingListener.Object.<anonymous>.InterceptingListener.onReceiveStatus (node_modules/grpc/src/client_interceptors.js:618:8)
      at callback (node_modules/grpc/src/client_interceptors.js:847:24)

```

**Comment by HofmannZ** [comment]
We’re getting the same error on our dev cluster running Kubernetes on GKE.

**Comment by SeanDez** [comment]
Ok, found the issue: I was giving `projectId` in firebaseTesting.initializeTestApp() a bad value (needs to be all lowercase). After clearing that issue the error resolved.
