### ISSUE TITLE
Can't install grpc 1.24.2

### ISSUE THREAD

**Issue by JPCMarques** [grpc/grpc-node#1241]
### Problem description
Installing grpc fails when attempting to install firebase. Also fails with same error when attempting to install grpc before firebase.

### Reproduction steps

npm i firebase, npm i grpc

### Environment
 - Windows 10 64-bits
 - 13.6.0 (also attempted with 12.14.1, getting the same error)
 - nvm
 - gRPC 1.24.2 

### Additional context

> grpc@1.24.2 install path\to\my\project\node_modules\grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: Unsupported target version: .\build\ActivateCustomer.js
node-pre-gyp ERR! stack     at get_runtime_abi (path\to\my\project\node_modules\grpc\node_modules\node-pre-gyp\lib\util\versioning.js:173:23)
node-pre-gyp ERR! stack     at Object.module.exports.evaluate (path\to\my\project\node_modules\grpc\node_modules\node-pre-gyp\lib\util\versioning.js:295:19)
node-pre-gyp ERR! stack     at install (path\to\my\project\node_modules\grpc\node_modules\node-pre-gyp\lib\install.js:241:31)
node-pre-gyp ERR! stack     at Object.self.commands.<computed> [as install] (path\to\my\project\node_modules\grpc\node_modules\node-pre-gyp\lib\node-pre-gyp.js:52:37)
node-pre-gyp ERR! stack     at run (path\to\my\project\node_modules\grpc\node_modules\node-pre-gyp\bin\node-pre-gyp:82:30)
node-pre-gyp ERR! stack     at Object.<anonymous> (path\to\my\project\node_modules\grpc\node_modules\node-pre-gyp\bin\node-pre-gyp:134:1)
node-pre-gyp ERR! stack     at Module._compile (internal/modules/cjs/loader.js:1144:30)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)
node-pre-gyp ERR! stack     at Module.load (internal/modules/cjs/loader.js:993:32)
node-pre-gyp ERR! stack     at Function.Module._load (internal/modules/cjs/loader.js:892:14)
node-pre-gyp ERR! System Windows_NT 10.0.18362
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "path\\to\\my\\project\\node_modules\\grpc\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd path\to\my\project\node_modules\grpc
node-pre-gyp ERR! node -v v13.6.0
node-pre-gyp ERR! node-pre-gyp -v v0.14.0
node-pre-gyp ERR! not ok
Unsupported target version: .\build\ActivateCustomer.js
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.24.2 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grpc@1.24.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by murgatroid99** [comment]
Do you have a line in your `package.json` that says `"target": ".\build\ActivateCustomer.js"`? The grpc library uses node-pre-gyp to install the native addon, and node-pre-gyp uses the `target` npm config option to set what Node version to install the addon for.

**Comment by JPCMarques** [comment]
> Do you have a line in your `package.json` that says `"target": ".\build\ActivateCustomer.js"`? The grpc library uses node-pre-gyp to install the native addon, and node-pre-gyp uses the `target` npm config option to set what Node version to install the addon for.

My package.json has no line that; in fact, there isn't even a `target` property on it.

**Comment by murgatroid99** [comment]
Does `npm config get target` output anything?

**Comment by JPCMarques** [comment]
@murgatroid99 indeed it did, it outputted the `.\build\ActivateCustomer.js`. 

I deleted this config from npm (`npm config delete target`) and it seems to have worked. Thank you!

**Comment by leogetzit** [comment]
Hi,
I had same problem.
I did not have any target as in the case above.
I upgraded Node from 12.14.0 to 12.15.0 and then it worked like a charm.
Hope this solution helps someone.
Cheers

**Comment by robc88Farm** [comment]
I am seeing this issue with node v12.16.0.

**Comment by itzzmeakhi** [comment]
Hi, I am facing this issue with node 10.16.0.

In my case, I don't find target variable in the package.json, and also when i tried to output the target using npm config get target, It was getting as undefined.

**Comment by max10rogerio** [comment]
@robc88Farm 
> I am seeing this issue with node v12.16.0.

Downgrade to node v12.15.0.... Worked for me!

**Comment by Martinnilsen99** [comment]
I get the same error. It did not work either downgrading to node v.12.15.0, nor trying to install an earlier version of grpc. Someone who has another possible solution for fixing this?

**Comment by Martinnilsen99** [comment]
> Hi, I am facing this issue with node 10.16.0.
> 
> In my case, I don't find target variable in the package.json, and also when i tried to output the target using npm config get target, It was getting as undefined.

Hi! I got it working now, and wanted to tell you how so you can try it out yourself. I had to set my node version to v12.15.0, and run "npm install -g node-pre-gyp" as grpc needs the node-pre-gyp globally (I read somewhere). Then I had to run "npm install --save firebase" and it worked! Try it out and let me know

**Comment by TAMDUC1** [comment]
> @robc88Farm
> 
> > I am seeing this issue with node v12.16.0.
> 
> Downgrade to node v12.15.0.... Worked for me!

same here

**Comment by jaequery** [comment]
cmon guys, these aren't even real solutions, just work around. how is this ticket even closed in this state?

**Comment by murgatroid99** [comment]
The original problem was a problem with the person's npm configuration and it was fixed. Other people have been chiming in with somewhat similar problems, but if it's not fixed by the original solution, it's not the same problem.

**Comment by angusturner** [comment]
Having this same issue. Fixed by downgrading to v12.15

**Comment by JPSantistebanQ** [comment]
Fixed downgrade to Node LTS last version 12.18.2
