### ISSUE TITLE
binding_path error when grpc is hoisted dependency in yarn workspace

### ISSUE THREAD

**Issue by jtsui** [grpc/grpc-node#1242]
### Problem description
binding_path resolves to incorrect folder in [`packages/grpc-native-core/src/grpc_extension.js`](https://github.com/grpc/grpc-node/blob/master/packages/grpc-native-core/src/grpc_extension.js#L28) causing Cannot find module `/incorrect_path/package.json` error.
 
### Reproduction steps
I have a yarn workspace monorepo where all dependencies are hoisted, following the standard format:
```
/monorepo
  /packages
    /packageA
    /packageB
 ```
packageA is a Node service that has a indirect dependency on grpc. Specifically packageA depends on a Util package that depends on grpc.

When I start my node service, I see the cannot find module error above.

When I specify add Util/** to packageA's nohoist, things work properly. This leads me to believe there is an issue with running grpc in a yarn workspace.

### Environment
 - Node version 10.17.0
 - gRPC@1.23.0

**Comment by murgatroid99** [comment]
The referenced line of code tries to load `grpc`'s own `package.json`. The expected directory structure is that `grpc` contains both its `package.json` and a `src` directory that contains the `grpc_extension.js` file. If this yarn workspace is breaking that somehow, that is a pretty serious violation of the basic assumption that installing a package does not rearrange its contents.

If you share more details we might be able to figure out what exactly is happening. What is the path to the `grpc_extension.js` file it is trying to load, what is the incorrect path to the `package.json` file it is trying to load, and what is the correct path to `grpc/package.json`? Also, are any parts of those paths symlinks and if so where do they point?
