### ISSUE TITLE
How to distinguish errors from the Writable and Readable sides of the gRPC duplex Stream

### ISSUE THREAD

**Issue by fbiville** [grpc/grpc-node#1256]
### Problem description

The current implementation of bidirectional streaming RPCs relies on Node Duplex stream.
I have a pipeline which roughly corresponds to this:
```
                   |->[unmarshaller stream 1]--| |--->[marshaller stream 1]-|
[gRPC bidi stream]--->[unmarshaller stream 2]-[...]-->[marshaller stream 2]--->[gRPC bidi stream]
                   |->[unmarshaller stream n]--| |--->[marshaller stream m]-|
```
The leftmost stream is the Readable part of the Duplex stream, let's call it `source`.
The rightmost stream is the Writable part of the Duplex stream, let's call it `dest`.

I have the following constraints:

1. if `source` emits en `error`, that `error` should be propagated to all unmarshaller streams
2. if any of the marshaller streams emit an `error`, that `error` should be propagated to `dest`

The problem occurs when a marshaller emits an `error` (point (2)). 
The propagation is done like this:
```js
marshallers.forEach(marshaller => {
   marshaller.on('error', (err) => {
      dest.emit('error', err);
   }
});
```
Because of point (1), I also set up this:
```js
source.on('error', (err) => {
   unmarshallers.forEach(unmarshaller => {
       unmarshaller.emit('error', err);
   });
});
```
Because I did not find a way to differentiate errors from the Readable (1) and the Writable (2) side of the bidi stream, the marshaller error ends up being propagated to all unmarshallers!

Are there e.g. pseudo-events fired by the grpc stream to avoid this situation (like `readable_error` and `writable_error`)?

### Environment
 - OS name, version and architecture: macOS Catalina 10.15.2
 - Node version 12.14.1
 - Node installation method nvm
 - Package name and version gRPC@1.24.2

**Comment by murgatroid99** [comment]
What you're looking for doesn't exist. In general, stream errors emitted by gRPC requests are not specific to the Readable side or the Writable side, and any error that is emitted closes both sides anyway, so it usually doesn't matter.

**Comment by fbiville** [comment]
Thanks for your quick reply!
I will try to filter on the error so that it doesn't get propagated too far, then.
