### ISSUE TITLE
Is there a proto-loader for gRPC-web?

### ISSUE THREAD

**Issue by lee-dave** [grpc/grpc-node#1264]
### Is your feature request related to a problem? Please describe.
I am running into a hard time auto-generating protobuf files. (helloworld_grpc_web_pb.js, helloworld_pb.js) Would like to replace the protoc generated utility step with how the way proto-loader does it for gRPC.

### Describe the solution you'd like
Similar to how gRPC uses the proto-loader to load .proto files but for gRPC-web

**Comment by murgatroid99** [comment]
Questions about grpc-web should be directed to the [grpc-web repository](https://github.com/grpc/grpc-web).
