### ISSUE TITLE
util.promisify() fails in Jest test context

### ISSUE THREAD

**Issue by imankovskyi** [grpc/grpc-node#1268]
### Problem description
When trying to wrap any client call with [util.promisify](https://nodejs.org/dist/latest-v8.x/docs/api/util.html), callback is lost in logic and is not returned to test context.
This results in timeout:
```
Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Error
```
Specifically [client_interceptors.js:1338](https://github.com/grpc/grpc-node/blob/35efc06146995445d416893b817d8fb1a1318009/packages/grpc-native-core/src/client_interceptors.js#L1338) check fails, because Function is not instanceof Function (sic!) in Jest context.

### Reproduction steps
Given simple Jest test and a client, any wrapped call results in Timeout
```
const {FormsClient} = require('generated/FormsService_grpc_pb');
const {promisify} = require('util');
const client = new FormsClient('0.0.0.0:9090', grpc.credentials.createInsecure());
getFormPromise = promisify(client.getForm).bind(client);

test('get redwood form',  async () => {
  const response = await getFormPromise(req);
  console.log(response);
});
```
Assuming generated code is in place, save test to ./test/simple.test.js , invoke with `jest ./test/simple.test.js`

### Environment
 - OS name, version and architecture:  macOS 10.14.6 (18G2022)  Kernel Version: Darwin 18.7.0
 - Node version v12.14.1
 - Node installation method: brew
    "grpc-tools": "^1.8.0",
    "grpc_tools_node_protoc_ts": "^2.5.9",
    "protoc-gen-grpc-web": "^1.0.5"

**Comment by murgatroid99** [comment]
It looks like the bug you are encountering is facebook/jest#2549, also reported more specifically as facebook/jest#6329.
