### ISSUE TITLE
how to use cmake.js ？

### ISSUE THREAD

**Issue by zuohuadong** [grpc/grpc-node#1274]
### Is your feature request related to a problem? Please describe.

node-gypis prone to problems.

### Describe the solution you'd like

use cmake.js

### Describe alternatives you've considered
cmake.js

### Additional context

node-gyp is ugly.

**Comment by nicolasnoble** [comment]
Until cmake.js gets prebuilt binaries downloads as a feature, we won't consider switching to it.
