### ISSUE TITLE
Unable to Load Imports/Nested Proto Files

### ISSUE THREAD

**Issue by jaysonesmith** [grpc/grpc-node#1278]
### Problem description

When working with a project that a number of imported proto files, I'm struggling to get all files loaded by what I'd imagine to be the "right way". One solution I've come up with was to specify all files to be loaded in the first argument to protoLoader.loadSync, but that's a bit troublesome when there are imports in various locations.

I'd imagine the standard method of loading should be somewhat easier and allow for the loader to follow import paths, but I'm really struggling to do so. I've attempted to add relative and absolute paths to the options' includeDir element and provided the base proto name to no avail, too.

Any help would be greatly appreciated, thanks!

### Reproduction steps

[I've created a repo here that demonstrates the loading issue](https://github.com/jaysonesmith/proto-demo)

### Environment
 - macOS 10.14.6
 - v10.16.3
 - brew
 ```
{
  "name": "proto-demo",
  "scripts": {
    "service": "npx babel-node index.js"
  },
  "dependencies": {
    "@babel/core": "^7.8.4",
    "@grpc/proto-loader": "^0.5.3"
  },
  "devDependencies": {
    "@babel/cli": "^7.8.4",
    "@babel/node": "^7.8.4",
    "@babel/preset-env": "^7.8.4",
    "babel-plugin-transform-es2015-modules-commonjs": "^6.26.2"
  }
}
```

**Comment by murgatroid99** [comment]
I notice that in your index.js, you are setting the include path to the absolute path to `proto/demo_services`, but in your `.proto` files you are importing e.g. `demo_services/foo/foo_service/create_foo.proto`. Include paths and import paths are concatenated together, so this will result in trying to load `proto/`**`demo_services/demo_services`**`/foo/foo_service/create_foo.proto`, which does not exist. You should be able to fix that by removing `demo_services` from either the include path or the import statements in your `.proto` files.

**Comment by jaysonesmith** [comment]
I'll give that a shot, thank you!

**Comment by jaysonesmith** [comment]
@murgatroid99 Thanks again for the info! I've made some changes and I'm able to get the bar service to load, but not foo. Foo has a file at /proto/demo_services/foo/foo_service/shared/line_item.proto that tries to import a shared file from /proto/demo_services/shared but is unable to. 

Have any other tips by chance?

**Comment by murgatroid99** [comment]
The include dirs should be absolute paths. I didn't expect you to change that so I didn't mention it.

**Comment by jaysonesmith** [comment]
Ah, gotcha! I've fixed that and put it back, this time without the demo_services section. Foo still fails being unable to load the root level shared proto. `Error: no such type: foo_service.Purchase`

**Comment by murgatroid99** [comment]
I think it's a package problem. The `LineItem` definition is in the `demo_services.foo_service` package, and the `Currency` definition is in the `demo_services` package. I think you can fix the reference by referring to `demo_services.Currency` in the `LineItem`definition (or maybe `.demo_services.Currency`).

**Comment by jaysonesmith** [comment]
Currency actually works without, there were a couple of things around Purchase that I munged up and now I'm able to get things working in the demo project. Thanks for the heads up around includeDirs! Going to try things out on my actual project and see how it goes. 

Thank you again! I really appreciate your time on this. :)

**Comment by jaysonesmith** [comment]
Early results seem positive. Thanks again!
