### ISSUE TITLE
server will shutdown, when the client shutdown.

### ISSUE THREAD

**Issue by saikoux12** [grpc/grpc-node#1279]
i use nodejs v12 and @grpc/grpc-js 0.6.18
it's a very simple demo.

this is server.js
```
var PROTO_PATH = __dirname + '/../protos/helloworld.proto';

var grpc = require('@grpc/grpc-js');
var protoLoader = require('@grpc/proto-loader');
var packageDefinition = protoLoader.loadSync(
  PROTO_PATH,
  {
    keepCase: true,
    longs: String,
    enums: String,
    defaults: true,
    oneofs: true
  });
var hello_proto = grpc.loadPackageDefinition(packageDefinition).helloworld;

function sayHello(call, callback) {
  // callback(null, {message: 12345});
}

function main() {
  var server = new grpc.Server();
  server.addService(hello_proto.Greeter.service, { sayHello: sayHello });
  server.bindAsync('0.0.0.0:50051', grpc.ServerCredentials.createInsecure(), (err, port) => {
    if (err) {
      console.log(err)
    }
    console.log(port)
    server.start();
  });
}

main();

```
this is client.js
```
var PROTO_PATH = __dirname + '/../protos/helloworld.proto';

var grpc = require('@grpc/grpc-js');
var protoLoader = require('@grpc/proto-loader');
var packageDefinition = protoLoader.loadSync(
  PROTO_PATH,
  {
    keepCase: true,
    longs: String,
    enums: String,
    defaults: true,
    oneofs: true
  });
var hello_proto = grpc.loadPackageDefinition(packageDefinition).helloworld;

function main() {
  var client = new hello_proto.Greeter('localhost:50051',
    grpc.credentials.createInsecure());
  var user;
  if (process.argv.length >= 3) {
    user = process.argv[2];
  } else {
    user = 'world';
  }
  client.sayHello({ name: user }, function (err, response) {
    console.log('Greeting:', response.message);
  });
}

main();

```
i run server.js first, then run client.js, of course it dosen't have response, because the sayHello function is not callback. Now stop the client.js, the server will shutdown and have error.

internal/http2/core.js:2516
      throw new ERR_HTTP2_INVALID_STREAM();
      ^

Error [ERR_HTTP2_INVALID_STREAM]: The stream has been destroyed
    at ServerHttp2Stream.respond (internal/http2/core.js:2516:13)
    at Http2ServerCallStream.sendMetadata (D:\grpc\node_modules\@grpc\grpc-js\build\src\server-call.js:213:21)
    at Http2ServerCallStream.sendStatus (D:\grpc\node_modules\@grpc\grpc-js\build\src\server-call.js:305:18)
    at Http2ServerCallStream.sendError (D:\grpc\node_modules\@grpc\grpc-js\build\src\server-call.js:325:14)
    at ServerHttp2Stream.<anonymous> (D:\grpc\node_modules\@grpc\grpc-js\build\src\server-call.js:193:18)
    at Object.onceWrapper (events.js:418:26)
    at ServerHttp2Stream.emit (events.js:311:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'ERR_HTTP2_INVALID_STREAM'
}

### Environment
 - windows 10 
 - Node version  v12.16.1
 - @grpc/grpc-js@0.6.18

**Comment by saikoux12** [comment]
@murgatroid99 could you reproduce the problem?

**Comment by murgatroid99** [comment]
I have not been able to reproduce that error, but I will look into adding some error handling to try to avoid those kinds of errors.

**Comment by murgatroid99** [comment]
In fact, the existing code has an explicit check for `stream.destroyed` at the beginning of the `sendMetadata` method (the second line in that stack trace), so I don't know how it could reach the point of calling `stream.respond` and getting an error that says "The stream has been destroyed".

**Comment by saikoux12** [comment]
```
        this.stream.once('error', (err) => {
            console.log(err);
            /**
             * Error: read ECONNRESET
             * at TCP.onStreamRead (internal/stream_base_commons.js:205:27) {
             * errno: 'ECONNRESET',
             * code: 'ECONNRESET',
             * syscall: 'read'
             * }
             */
            this.metadataSent = true;// i add this one, and solve the problem
            err.code = constants_1.Status.INTERNAL;
            this.sendError(err);
        });
```
I'm not sure if there's anything else wrong with that, but i add this.metadataSent = true; will solve the problem. I think once the client has some problem and disconnect, the server should not send the respond to client anymore, isn't it?

**Comment by saikoux12** [comment]
@murgatroid99 what do you think ? i really need the help T-T

**Comment by murgatroid99** [comment]
I've opened PR #1284 to try to fix this. You can test it out just by making the `'error'` event handler do nothing.

**Comment by saikoux12** [comment]
yeah,it will solve my problem
