### ISSUE TITLE
problem downloading grpc packages

### ISSUE THREAD

**Issue by juanklagos** [grpc/grpc-node#1280]
It is a rare thing, but for the Internet service provider CLARO HOGAR COLOMBIA, it does not allow downloading the grpc packages, the page does not even open, it happens in any connection with this provider, with another provider it works correctly, talk to an advisor of the company CLEAR HOME COLOMBIA but they did not solve, so I access from a vpn on my pc, there is no solution on your part, since in my meetup cucuta dev which I address many present this problem with that provider, thanks in advance

![image](https://user-images.githubusercontent.com/8006187/75514053-7f27d380-59c4-11ea-81f4-9c56bbacbd3c.png)

**Comment by murgatroid99** [comment]
One thing that might work is `npm install --grpc_node_binary_host_mirror=https://storage.googleapis.com/node-precompiled-binaries.grpc.io/`. This will try to download from the Google Cloud Storage bucket directly instead of going through CloudFlare.
