### ISSUE TITLE
proto-loader.loadSync silently stops resolving imports after failing to resolve one.

### ISSUE THREAD

**Issue by erwinvaneyk** [grpc/grpc-node#1298]
### Problem description
When trying to dynamically load a protobuf file, that has an import that can not be found on the local machine, `proto-loader.loadSync` does not fail with a helpful error message. Instead it does not report any error and seems to stop resolving the import statements. It consequently errors somewhere else, erroring on non-imported definitions. 

Although this is a user error, the error generated by loadSync is not specific to the problem and is difficult to debug.

### Reproduction steps
Using the following setup in NodeJS:
```javascript
const grpc = require('grpc');
const protoLoader = require('@grpc/proto-loader');
const protoFiles = require('google-proto-files');

const packageDefinition = protoLoader.loadSync(
    './api.proto',
    {
        keepCase: true,
        longs: String,
        enums: String,
        defaults: true,
        oneofs: true,
        includeDirs: [
            protoFiles.getProtoPath('..'),
        ]
    }
);
const helloworld_proto = grpc.loadPackageDefinition(packageDefinition).helloworld;
console.log(helloworld_proto);
```

The following protobuf definition is loaded successfully (likely because the non-resolved import is last in the order)
```protobuf
syntax = "proto3";

package helloworld;

import "google/protobuf/timestamp.proto";
import "github.com/gogo/protobuf/gogoproto/gogo.proto";

message HelloWorld {
    google.protobuf.Timestamp created_at = 5 [(gogoproto.stdtime) = true];
}
```

However, changing the order of the imports, running the node script will fail:
```protobuf
syntax = "proto3";

package helloworld;

import "github.com/gogo/protobuf/gogoproto/gogo.proto";
import "google/protobuf/timestamp.proto";

message HelloWorld {
    google.protobuf.Timestamp created_at = 5 [(gogoproto.stdtime) = true];
}
```
Resulting in the following error:
```
Error: no such Type or Enum 'google.protobuf.Timestamp' in Type .helloworld.HelloWorld
```

Based on this behaviour, it seems that instead of directly failing, `loadSync` simply stops resolving imports after encountering one that it cannot find.

### Environment
 - OS name, version and architecture: Darwin Kernel Version 19.3.0 x86_64
 - Node version: v13.10.1
 - Node installation method: brew
 - Package name and version [e.g. gRPC@1.12.0]: 1.24.2

**Comment by murgatroid99** [comment]
The bulk of the implementation of `@grpc/proto-loader` is the Protobuf.js library, and that is where you can find the decision to not error on failed imports. The include paths thing is an addition in proto-loader, but it just falls back to the Protobuf.js default behavior if it doesn't find the file. I could add a warning when a file can't be found in any of the include paths.

**Comment by erwinvaneyk** [comment]
Hey @murgatroid99, thanks for the quick follow up. I agree that even a warning would be enough to make the issue clear to the user.

**Comment by murgatroid99** [comment]
Version 0.5.4 has that warning.
