### ISSUE TITLE
grpc-js: deadline timeouts are no longer cleared

### ISSUE THREAD

**Issue by MiLk** [grpc/grpc-node#1300]
### Problem description
Since #1184, the deadline timeouts are no longer cleared.
`Call` no longer acts as an event emitter, and can no longer propagate the status to the `DeadlineFilter`.
For long running processes using the same client, even after having receiving the response, the call end up being cancelled due to the deadline.

### Reproduction steps
Query a gRPC service, and don't close the client.
There will be a deadline error even if the response has been received.

### Environment
 -  node: v12.16.1
 - grpc-js: 0.7.0, 0.7.1 and master

### Workaround
Checking the value of `this.statusOutput` in `cancelWithStatus` allows to prevent cancelling if the status has already been sent. But we still keep timeouts around for each call.

**Comment by murgatroid99** [comment]
I'm not sure I understand. Are you saying that your code was explicitly emitting a `'status'` event on the `Call` object to stop the deadline timer from triggering?

**Comment by MiLk** [comment]
I'm talking about this change: https://github.com/grpc/grpc-node/pull/1184/files#diff-94528be51385f17b41d967ec6d72fafaL69

It seems that since this changed, the timeout is never cleared, and the `Deadline exceeded` keeps showing up, even after completing the request.

**Comment by MiLk** [comment]
It might actually not be an issue. I will continue to investigate on my side, and close if there is no problem.

**Comment by murgatroid99** [comment]
The `cancelWithStatus` method should only do anything if the call has not already ended with some other status.

**Comment by MiLk** [comment]
Yes, I went into the wrong direction.
We have an important number of cancelled and timeout errors, but it looks like it's related to the infrastructure.
Sorry for the noise.
