### ISSUE TITLE
lodash.clone required as an explicit dependency, for 1.24.2

### ISSUE THREAD

**Issue by heatherlp** [grpc/grpc-node#1301]
### Problem description
When using 1.24.2, the following is seen:

```
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'lodash.clone'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
```
Workaround is adding lodash.clone as a dependency at the same level as grpc:

```
  "dependencies": {
    "grpc": "1.24.2",
    "lodash.clone": "4.5.0",...
```

### Reproduction steps
- Update grpc dependency version from 1.23.3 to 1.24.2
- Attempt to run file that imports grpc

### Environment
 - ubuntu-18.04
 - Recreatable across both; **node 10.19.0 x64** and **node 12.16.1 x64**
 - npm
 - package name: grpc@1.24.2

### Additional context
Could be an issue with npm? but: 
- Didn't see this with v1.23.2
- Cannot recreate it on macOS

Offending build log: https://dev.azure.com/Hyperledger/Fabric-SDK-Node/_build/results?buildId=9762&view=logs&j=da18d031-6b67-55f8-19f1-868c1b4eb10a

Commit with workaround and passing tests: https://github.com/hyperledger/fabric-sdk-node/commit/a4ee5d4b194c4ec41ba6503c7897c9acac58d53e

**Comment by murgatroid99** [comment]
I don't know what's happening here, but that version of `grpc` definitely has a dependency on `lodash.clone`. That version of `grpc` has been out for over 4 months and you're the first person who has reported this problem, so I think it's very likely that this is caused by some issue with your setup.
