### ISSUE TITLE
How can a client send a list of IP addresses for load balancing?

### ISSUE THREAD

**Issue by 07pia05** [grpc/grpc-node#1307]
```javascript
const grpcJs = require('@grpc/grpc-js');
const protoLoader = require('@grpc/proto-loader');
const proto = protoLoader.loadSync('books.proto', {
    keepCase: true,
    longs: String,
    enums: String,
    defaults: true,
    oneofs: true
  });
const packageGrpcJs = grpcJs.loadPackageDefinition(proto);
const clientGrpcJs = new packageGrpcJs.books.BookService(
    ['127.0.0.1:50051', '127.0.0.1:50052'], 
    grpcJs.credentials.createInsecure()
);
```
I get the following error
```
/home/js/grpc/node_modules/@grpc/grpc-js/build/src/resolver.js:51
        if (target.startsWith(prefix)) {
                   ^

TypeError: target.startsWith is not a function
```

**Comment by murgatroid99** [comment]
grpc-js does not currently have a mechanism to do exactly what you're trying to do. The existing name resolution+load balancing functionality can load balance across multiple addresses, when DNS records or hosts file records have multiple entries, but they always use the same port, and there isn't currently a way to load balance to multiple ports on the same address.

**Comment by murgatroid99** [comment]
By default, grpc-js only uses one address, so to enable true load balancing you will need to set a default service config ([documented here](https://github.com/grpc/grpc/blob/master/doc/service_config.md)). You can do this by passing the client construction argument `'grpc.service_config'` with a value that is a JSON string representation of a service config object. I haven't checked recently, but I think the simplest service config object that enables load balancing is

```js
const serviceConfig = {
  'loadBalancingConfig': [
    { round_robin: {} }
  ]
}
```

Then you can construct your client like this to enable round robin load balancing:

```js
const client = new Client(address, credentials, { 'grpc.service_config': JSON.stringify(serviceConfig) });
```

**Comment by yunnysunny** [comment]
@murgatroid99 Is the parameter of `address` is a DNS server's name?

**Comment by murgatroid99** [comment]
No, it's the DNS name of the gRPC server.

**Comment by yunnysunny** [comment]
I have read the code of `grpc-node`, and found that we can set the parameter of `address` to `dns://domain-name` to find the hosts from DNS server. But it‘s not mentioned on the document.
And the module of `resolver`(in the code of `packages/grpc-js/src/resolve.ts`) is not exported to developer, if we wanna implement an instance of custom resolver to resolve the problem of load balancing with different port，we have none method except write the load balancing code myself. Other grpc drivers , such as golang, has ability of passing custom resolver parameter to the driver's API, so I think it may be good for node too.

**Comment by murgatroid99** [comment]
The `dns:` scheme specifies that the target should be interpreted as a DNS name. This is also the default behavior: if you do not use any scheme, it will use DNS by default. So a target of `dns:///example.com` will behave the same as `example.com`.

**Comment by yunnysunny** [comment]
Will you consider exporting the `packages/grpc-js/src/resolve.ts` to developer?

**Comment by murgatroid99** [comment]
That API is not currently designed to be part of the public API. It would need to go through an API design process and probably some revisions before we export it like that.

**Comment by yunnysunny** [comment]
I'm glade to hear that. Expecting you complete it.

**Comment by RebornTong** [comment]
const client = new Client(address, credentials, { 'grpc.service_config': JSON.stringify(serviceConfig) });

then, how address can be multi server ip, or how Client can be iniciated with a list of ip addreses?

**Comment by murgatroid99** [comment]
Yes, grpc-js now supports the `ipv4:` and `ipv6:` schemes in [the naming documentation](https://github.com/grpc/grpc/blob/master/doc/naming.md). Those can be used to pass in multiple addresses for the client to load balance over.

**Comment by RebornTong** [comment]
thanks, it works!
