### ISSUE TITLE
Nodejs, gRPCserver, connection docker refuse

### ISSUE THREAD

**Issue by btbensoft** [grpc/grpc-node#1321]
### Problem description

I created a gRPC server with Nodejs, I built a Docker image, and run it.

But when I try to access it, I get an error from my client (.NET application) connection refuse. 
When I test without docker everything works perfectly 

**Docker file**
```
FROM node:13

WORKDIR /usr/src/app
COPY package.json ./
RUN yarn

COPY . .

EXPOSE 50051
CMD ["node", "index.js"]
```

**Server index.js**
```
const protoLoader = require('@grpc/proto-loader')
    const packageDefinition = protoLoader.loadSync('./PdfGeneratorService.proto');
    const notesProto = grpc.loadPackageDefinition(packageDefinition).PdfGeneratorPackage;

    const server = new grpc.Server()
    server.addService(notesProto.PdfGeneratorService.service, {
        GetPdf: (_, callback) => {
            console.log('Enter in the grpc GetPdf method');
        },
    })
    server.bind('0.0.0.0:50051', grpc.ServerCredentials.createInsecure())
    console.log('Server running')
    server.start()
```

### Client side (C# app)
I have tried several things. To connect :

http://localhost:50051
http://127.0.0.1:50051
http://172.17.0.3:50051 (Docker IP)

Nothing work, have you some tips to help me?

Note : without docker all works perfectly ==> http://localhost:50051

Thanks

Ben

**Comment by murgatroid99** [comment]
From the [Docker documentation](https://docs.docker.com/engine/reference/builder/#expose):

> The `EXPOSE` instruction does not actually publish the port. It functions as a type of documentation between the person who builds the image and the person who runs the container, about which ports are intended to be published. To actually publish the port when running the container, use the `-p` flag on docker run to publish and map one or more ports, or the `-P` flag to publish all exposed ports and map them to high-order ports.

**Comment by btbensoft** [comment]
When i change 

```
FROM node:13
......
```

to 

```
FROM node:12.16.1
.....
```

it's works
