### ISSUE TITLE
Broadcasting to several clients

### ISSUE THREAD

**Issue by lgmkr** [grpc/grpc-node#1327]
I’m breaking my head around how to make broadcasting from one server to several clients.
In my task I need to send message from one client to server but response should recive every connected client.
I’ve faced similar issues on stackoverflow but no luck.
One think that I understood that gRPC have no built-in ability to send message to several clients, only for client that send request.
And I should store every client in some data structure and send manually to every stored client.
For now I have sample project with bidirectional streaming communication between server and client.
It’s possible to get client identifier using  
```   
 /**
     * Get the endpoint this call/stream is connected to.
     * @return The URI of the endpoint
     */
    getPeer(): string 
```
But how to send meessage to the peer manualy ?

**Comment by murgatroid99** [comment]
gRPC is a protocol for clients to send requests to servers and for those servers to handle those requests. There is no notion of a server sending a message to a client outside of the context of a request started by a client.

To do something like this using gRPC, you should define a bidi or server streaming method with a response message type that describes what you want the server to send, then have the server send whatever you want it to broadcast to each active stream.

**Comment by lgmkr** [comment]
@murgatroid99 thanks for you answer, could you send me a code snippet of this `then have the server send whatever you want it to broadcast to each active stream.`
It would helpe me a lot!

**Comment by murgatroid99** [comment]
I don't really have anything specific for that. Just track open requests in some data structure and iterate over them when you want the server to send messages to them.

**Comment by lgmkr** [comment]
@murgatroid99 
I've looked for the way where and when can I save a "connected client" to a list of clients but there are no "connect" event or such an interceptor on server side. 

```js
export class SomeHandler implements ISomeServer {
  someMethod(call: grpc.ServerDuplexStream<SomeRequest, SomeResponse>) {
      call.on("connect", () => ....)                            <------------- event never fired 
      call.on("data", (request: SomeRequest) => { ... }); 
  }
```
Could you explain where I can retrive connected clients on the server?

**Comment by murgatroid99** [comment]
What I'm saying is that you save the `call` objects, and when you want to broadcast a message, you write it on each of them. You probably want to listen for both the `end` and `cancelled` event on each to know when the client has finished with them and you should remove them from your list.

**Comment by lgmkr** [comment]
It looks like I need to implement some default call on the same beginning of communication when client connects to the server. And it looks like workaround. Anyway thank you for your help. I'm very appriciated.
