### ISSUE TITLE
Getting metadata from plugin failed with error message

### ISSUE THREAD

**Issue by RezaRahmati** [grpc/grpc-node#1330]
### Problem description
A clear and concise description of what the problem is.

### Reproduction steps
Give very precise steps you've discovered to reproduce your problem. If possible and applicable, provide us with a repository we can clone that contains a reproduction case. Also if possible and applicable, please include a Dockerfile that exhibits the problem if it's specific to a certain environment. Bug reports with no reproduction steps will be closed.

I am developing firebase, firestore app, when I serve firebase locally I get below error

```
2 UNKNOWN: Getting metadata from plugin failed with error: error:0909006C:PEM routines:get_name:no start line +878ms
>  Error: 2 UNKNOWN: Getting metadata from plugin failed with error: error:0909006C:PEM routines:get_name:no start line
>      at Object.callErrorFromStatus (C:\projects\xy\xybot-newadmin\backend\functions\node_modules\dialogflow\node_modules\@grpc\grpc-js\build\src\call.js:30:26)
>      at Http2CallStream.call.on (C:\projects\xy\xybot-newadmin\backend\functions\node_modules\dialogflow\node_modules\@grpc\grpc-js\build\src\client.js:96:33)
>      at Http2CallStream.emit (events.js:203:15)
>      at process.nextTick (C:\projects\xy\xybot-newadmin\backend\functions\node_modules\dialogflow\node_modules\@grpc\grpc-js\build\src\call-stream.js:100:22)
>      at process._tickCallback (internal/process/next_tick.js:61:11)
```

### Environment
 - OS name, version and architecture: [e.g. Linux Ubuntu 18.04 amd64] Windows 10
 - Node version [e.g. 8.10.0] v10.16.0
 - Node installation method [e.g. nvm] npm@6.13.0
 - If applicable, compiler version [e.g. clang 3.8.0-2ubuntu4]
 - Package name and version [e.g. gRPC@1.12.0] "@grpc/grpc-js": "^0.7.4",

### Additional context
Add any other context about the problem here. If possible, attach full logs. Do not try to omit anything for brevity, but instead include absolutely everything. Please try and set your operating system's locale to English, so that logs contain error messages in the English language.

**Comment by murgatroid99** [comment]
You said you experienced this issue while using firebase. Have you filed an issue against that library?
