### ISSUE TITLE
Long polling stream response causes RSS always increase until OOM

### ISSUE THREAD

**Issue by kevinprotoss** [grpc/grpc-node#1332]
### Problem description
We have to use subscription scenario so that the web app keeps listening on the server push. That means, the h2 stream request will only be closed or canceled by means of client action or failed network connection. 
In this case, the server sends continuously response data back without stream end. The push pace is about 10 message data (Buffer) / milliseconds.
Since starting push, server increase the memory consumption steadly higher, especially the RSS part. After about 1 hours, server aborts because of OOM Exception. 
I had also tried: let the client side stop subscription ( trigger `call.end` on server side ) and restart subscription by a new request after an interval. The RSS still doesn't go down. Server does not free up any RSS memory. 
I had also seen some similar issues in this repo. Was this issue be tested or already known?
How could we fix such Problem or should we using another implementation scenario to ensure memory consumption?

### Reproduction steps
Use grpc stream service to send protobuf stream back continuously(without complete). 
I have tried the following pace: 
```javascript
// about 4 data per milliseconds
call.write({ data: binary / pb object });
// no call.end() before client side cancel
```
Use grpc-node implementing a simple client to subscribe the data source (keep alive).

### Environment
 - OS version: Windows 10 WSL: Ubuntu x64
 - Node version: v12.14.1
 - Node installation method: nvm
 - Package name and version: grpc@1.24.2 or @grpc/grpc-js@0.7.3

### Additional context
Both grpc native and grpc-js were tested, their problems are the same.
Tested also on different environments:  in addition to the one above, also on a linux server, x64, CentOS.

**Comment by murgatroid99** [comment]
The following paragraph can be found in the [`write` method documentation](https://nodejs.org/api/stream.html#stream_writable_write_chunk_encoding_callback):

> The return value is `true` if the internal buffer is less than the `highWaterMark` configured when the stream was created after admitting chunk. If `false` is returned, further attempts to write data to the stream should stop until the `'drain'` event is emitted.

When doing relatively few writes you can often safely ignore this, but you seem to be saying that you are doing thousands of writes per second, so you should do that. If you do that, does it change anything?

**Comment by kevinprotoss** [comment]
Hi,
thanks for your explanation. That means, I should handle this situation by myself. 
1. check the returned value
2. if false returned, I must manually pause the writing until drain event is emitted, such as the backpressure solution using Reactive Observable.

I'll make a try. I guess it should be an improvment. 
Best regards

**Comment by kevinprotoss** [comment]
Hi, 

Update new result from my futhre survey. 
The OOM happens because the grpc server impl hasn't awared that the client has already closed connection. The server listens on the 'cancelled' event of call so that the call could be ended immediately. However, it's not enough. I found it's so often that the event handler won't be triggered even client was already quit. This situation makes server side holds the cache of Buffer always. In the end, OOM occurs. 
Now my solution is, I check the `call.call.stream.closed` everytime before the server writing stream. If the value is true, server ends the stream connection manually. 
After this kind of fix, server runs steady. RSS consumption goes not very high and it will go down after clients close connections. Server continuous running for several days without downtime and sends hugh amount of data every seconds. It matches our current demand at least. 

Thanks again. Hopefully my inspect could help someone else.

Best regards,
Junxiang

**Comment by murgatroid99** [comment]
The `'cancelled'` event is emitted when a call finishes abnormally, such as when the client cancels a call, or when the client disconnects. To know when a client has finished writing normally, you should listen for the `'end'` event.
