### ISSUE TITLE
[proto-loader]: Identifying intentional default values

### ISSUE THREAD

**Issue by ollieayre-oc** [grpc/grpc-node#1337]
Hi

Is there a way to identify if a value was intentionally encoded with a default value? (e.g. int32 encoded with a 0).

Protobuf.js adds the defaults to the prototype so that the user can check if a value was present on the wire by calling hasOwnProperty on the message however proto-loader converts all messages straight to objects meaning that that information is lost. 

I appreciate that proto-loader aims to specifically hide the Protobuf.js API but i can't seem to find any alternative way to get access to this information before proto-loader removes it.

Thanks

**Comment by murgatroid99** [comment]
In Protobuf 3, default values are encoded as omitted, so you can't actually tell whether the remote end intentionally omitted the field, or set it to a default value.

**Comment by ollieayre-oc** [comment]
Ok thanks, i wasn't aware that that was an intentionally part of the design.
