### ISSUE TITLE
grpc-js: waitForReady called multiple times

### ISSUE THREAD

**Issue by badsyntax** [grpc/grpc-node#1352]
### Problem description
When using `client.waitForReady`, the ready callback is called multiple times (3 times in this case). Is this is the expected behaviour? I expected it to be called only once. Perhaps I'm misunderstanding the API.

### Reproduction steps
 I'm constructing the gRPC client (which extends from [Client.ts](https://github.com/grpc/grpc-node/blob/master/packages/grpc-js/src/client.ts)).

```ts
import * as grpc from '@grpc/grpc-js';
import { GradleTasksClient as GrpcClient } from './java-gradle-tasks-grpc/src/main/proto/gradle_tasks_grpc_pb';

const grpcClient = new GrpcClient(
  'localhost:8887',
  grpc.credentials.createInsecure()
);
const deadline = new Date();
deadline.setSeconds(deadline.getSeconds() + 1);
grpcClient.waitForReady(deadline, (err: Error | undefined) => {
  console.log('is ready');
});
```

### Environment
 - OS name, version and architecture: macos Catalina 10.15.3 x86_64
 - Node version: v12.16.1
 - Node installation method: nvm
 - Package name and version: `@grpc/grpc-js@0.7.9`

### Screencast

![grpc-js-waitforready](https://user-images.githubusercontent.com/102141/79078186-69fdce80-7cfe-11ea-9546-5c403444005a.gif)

**Comment by murgatroid99** [comment]
That does look like a bug, but I don't know what could be causing that to happen.

**Comment by murgatroid99** [comment]
In your screencast, you are running that code in a function `connectToServer`. Are you sure you're not just calling that function multiple times?

**Comment by badsyntax** [comment]
Hi. Yes i've checked, that method is called only once, and the ready callback is called 3 times. 

I'm using a pretty standard gRPC Java server on the backend. 

I've done some digging and it looks like there's some recursion happening which results in multiple watcherObjects being queued which results in the waitForReady callback being called multiple times.

It starts here: (note the callback (`checkState`) will re-run this code when the state changes - this is the recursion):

within `client.waitForReady`:

https://github.com/grpc/grpc-node/blob/03fdeedc78cab7671e8e5e939fafd74125658dd3/packages/grpc-js/src/client.ts#L179-L183

`watchConnectivityState` will queue the first watcher:

https://github.com/grpc/grpc-node/blob/03fdeedc78cab7671e8e5e939fafd74125658dd3/packages/grpc-js/src/channel.ts#L451-L461

Now when `channel.updateState` is called, the watcher callback method is called, see: 

https://github.com/grpc/grpc-node/blob/03fdeedc78cab7671e8e5e939fafd74125658dd3/packages/grpc-js/src/channel.ts#L404-L410

`watcherObject.callback` is the original `checkState` callback defined in `client.waitForReady`, so now we're back to the beginning, and another watcher object is queued.

So I think the fix is to remove the watcher _before_ calling the callback. 

So change this code: 

https://github.com/grpc/grpc-node/blob/03fdeedc78cab7671e8e5e939fafd74125658dd3/packages/grpc-js/src/channel.ts#L406-L408

To this:

```
        clearTimeout(watcherObject.timer);
        this.removeConnectivityStateWatcher(watcherObject);
```

**Comment by murgatroid99** [comment]
I think I do see a situation that could cause what you're seeing: if the state transition that triggers the `updateState` call is a transition to the IDLE state, the `getConnectivity` state in the callback will synchronously kick the channel out of the idle state, calling `updateState` to be called again, so the `watcherObject`'s callback will be called again before it is removed, increasing the number of eventual `watchConnectivityState` callbacks.

I'd be happy to make the change you described, or to accept a PR that makes that change.

**Comment by badsyntax** [comment]
Cool yes I think that makes sense. Am happy to make a PR for this, but will only get to doing it sometime tomorrow (BST).

**Comment by badsyntax** [comment]
I've added a PR with https://github.com/grpc/grpc-node/pull/1368 but it doesn't look like the builds are running. Should I close the PR and re-open?
