### ISSUE TITLE
http proxy not used when set at runtime

### ISSUE THREAD

**Issue by mrfelton** [grpc/grpc-node#1354]
### Problem description
http proxy is ignored if you set the `grpc_proxy` env var at runtime.

### Reproduction steps
Try enabling grpc proxy dynamically at run time by setting `process.env.grpc_proxy`

```js
process.env.grpc_proxy = 'http://...`
...
```

### Environment
 - OS name, version and architecture: mac
 - Node version v12.13.0
 - Node installation method: nvm
 - Package name and version: grpc-js 0.7.9

### Additional context

The problem is that `getProxyInfo` is only called once when the module first loads:

https://github.com/grpc/grpc-node/blob/7eca188ae1f047631d5c629cc9ee5411e41d2794/packages/grpc-js/src/http_proxy.ts#L87

As a result, changes to the proxy env var made at run time are ignored.

**Comment by murgatroid99** [comment]
This was fixed by #1356.
