### ISSUE TITLE
Segfault with IPV6 6rd enabled

### ISSUE THREAD

**Issue by stephenplusplus** [grpc/grpc-node#137]
_From @kuzyn on December 26, 2017 15:27_

This is a strange problem; apologies that the step to reproduces aren't super straightforward:

It appears that if I'm behind a router (Cisco EA3500) and leave the Internet Settings / IPV6 / IPV6 6rd to "Automatic", all request to the datastore will result in a segfault

![image](https://user-images.githubusercontent.com/1139068/34359277-91e61782-ea24-11e7-8418-8a0b0b1addec.png)

![image](https://user-images.githubusercontent.com/1139068/34359452-26402b60-ea26-11e7-9dfe-eb799cc2c0b4.png)

The `sensor.model:createOne` method (hangs at ds.save/datastore.save):
```javascript
 createOne: o => {
    return sensorEntity.new(o).then(e => ds.save(e))
  },
```

The `sensor.model:createOne` test:
```javascript
  test('sensor.model:createOne', t => {
    return sensorModel.createOne(entityPayload)
      .then(d => {
        const id = extract(d, 'id')
        t.equal(id.length, 16, 'id has 16 digits')
        t.equal(typeof parseInt(id), 'number', 'id parse to number')
        entitiesIds.push(id)
      })
      .then(() => t.end())
  })
```

I'm trying to understand why there is no error displayed and why it only seems to affect the datastore (so far). Maybe someone has an idea on how to replicate this environment in a Docker image or something?

#### Environment details

  - OS: 4.14.4-1-ARCH
  - Node.js version: v8.9.1
  - npm version: 5.5.1
  - yarn version: 1.3.2
  - @google-cloud/datastore version:

#### Steps to reproduce

  1. Enable 6RD on a router
  2. Try to perform a datastore operation

_Copied from original issue: googleapis/nodejs-datastore#36_

**Comment by stephenplusplus** [comment]
I'm taking a guess that this is a gRPC-related issue, which is why I moved it here. It would be good to note the version of `@google-cloud/datastore` and gRPC that is being loaded.

**Comment by kuzyn** [comment]
Oops! Of course:

`gRPC` = 1.6.0
`google-datastore` = 1.1.0

**Comment by murgatroid99** [comment]
Sorry for the slow response. Can you run the program with the environment variables `GRPC_TRACE=all` and `GRPC_VERBOSITY=DEBUG`, and share the output?

**Comment by kuzyn** [comment]
No worries. But unfortunately, I do not have access to this environment
anymore. Should we try to find someone with a similar config to test, try
to reproduce in a virtual env or close this?

**Comment by nicolasnoble** [comment]
It's sad, but we don't have any way to reproduce it. Please open a new issue if this changes.
