### ISSUE TITLE
Release precompiled build for node 13

### ISSUE THREAD

**Issue by pandres95** [grpc/grpc-node#1402]
### Problem description
C-based library ([grpc](https://npm.im/grpc)) Is taking way too long to be installed on Linux (amd64) on node v13.x. This happens just because the library seems not to have a precompiled binary for this platform-architecture.

### Reproduction steps
1. Run `npm install` under the `node:13` Docker image.

### Environment
 - _OS name, version and architecture:_ Linux Debian 9.12 amd64
 - _Node version:_ 13.14.0
 - _Node installation method:_ Docker 
 - _Package name and version:_ `gRPC@1.24.2`

**Comment by unludo** [comment]
Hi, 
I have the same question for node 12.16.3. Should I open another issue?
Thank you.

**Comment by unludo** [comment]
Hi,
no news about this:

WARN Pre-built binaries not installable for grpc@1.24.2 and node@12.16.3 (node-v72 ABI, glibc) (falling back to source compile with node-gyp)

This is annoying.

thanks

**Comment by murgatroid99** [comment]
Support for Node 13 and 14 is available in grpc 1.24.4.
