### ISSUE TITLE
Bind Async

### ISSUE THREAD

**Issue by tweenietomatoes** [grpc/grpc-node#1404]
After i changed server.bind to bindAsync
i am getting  TypeError: callback must be a function

As a result i passed a function as a third parameter then i am getting 
Error: server must be bound in order to start

How can i convert grpc to grpc-js :(

**Comment by murgatroid99** [comment]
`server.bindAsync` is an async function, so the callback function indicates that the operation is complete. So, you should call `server.start` in the callback.

**Comment by tweenietomatoes** [comment]
yes i discovered that thanks.

**Comment by murgatroid99** [comment]
An error can be passed to the callback if binding fails. You should add `error` as the first argument to the callback and check if it is set. If it is, its message will have more information about why it failed.

**Comment by charliemoweng** [comment]
@sudiptosarkar did you manage to resolve this issue? I'm facing the same problem.

**Comment by sudiptosarkar** [comment]
> @sudiptosarkar did you manage to resolve this issue? I'm facing the same problem. Edit: managed to resolve it by changing the port number. Links that I found useful: https://medium.com/@yuanchaodu/run-grpc-server-failed-289172dbe6e https://nanxiao.me/en/the-grpc-server-program-will-crash-when-cant-bind-successfully/

Hey @charliemoweng. I was able to resolve the issue. First, I had to bind it to all interfaces (`0.0.0.0:port`), and had to add the necessary arguments in the callback like @murgatroid99 said:

```
server.bindAsync('0.0.0.0'.concat(':').concat(myPort), grpc.ServerCredentials.createInsecure(), (err, result) => (err, _result) => !err ? server.start() : logger.error(err));
```
