### ISSUE TITLE
Documentation for using grpc-js with protoc

### ISSUE THREAD

**Issue by steven-supersolid** [grpc/grpc-node#1408]
### Problem description
The documentation for migrating from grpc to grpc-js recommends using the grpc-tools option --generate_package_definitions when generating packages to import. We are currently using protoc to generate packages and would like to know what the equivalent command is.

### Reproduction steps
Adding the grpc_out option `generate_package_definition`  results in the error message `--grpc_out: sdk.proto: Unknown parameter: generate_package_definition`

I have tried the singular and plural option.

```
protoc \
  -I /go/src/agones.dev/agones/proto/googleapis \
  -I /go/src/agones.dev/agones/proto/sdk \
  --grpc_out=generate_package_definition:minimum_node_version=12:./sdks/nodejs/lib \
  --plugin=protoc-gen-grpc=/usr/local/bin/grpc_node_plugin sdk.proto
```

### Environment
 - grpc v1.20.1
 - libprotoc 3.7.0

**Comment by murgatroid99** [comment]
If you are using `protoc` directly, where did you get the gRPC Node plugin?

**Comment by steven-supersolid** [comment]
`protoc` and `grpc` are installed on the build image as follows

https://github.com/googleforgames/agones/blob/master/build/build-sdk-images/tool/base/Dockerfile

```
ARG GRPC_RELEASE_TAG
# install protobuf first, then grpc
RUN git clone -b $GRPC_RELEASE_TAG --depth=5 https://github.com/grpc/grpc /var/local/git/grpc && \
		cd /var/local/git/grpc && \
    git submodule update --init && \
    echo "--- installing protobuf ---" && \
    cd third_party/protobuf && \
    ./autogen.sh && ./configure --enable-shared && \
    make -j$(nproc) && make install && make clean && ldconfig && \
    echo "--- installing grpc ---" && \
    cd /var/local/git/grpc && \
    make -j$(nproc) && make install && make clean && ldconfig
```

**Comment by murgatroid99** [comment]
The plugin in that repository is out of date. The current version is in this repository's `packages/grpc-tools` directory, and is distributed in the `grpc-tools` package.

**Comment by moloch--** [comment]
How do we use the `package/grpc-tools` version? Do we need to manually clone it from Github? It doesn't seem to be installed with `@grpc/grpc-js`, is there any documentation on how to use `@grpc/grpc-js`? The [reference documentation](https://grpc.github.io/grpc/node/) on the website is only for `grpc-node`.

**Comment by murgatroid99** [comment]
`grpc-tools` is an npm package that provides a `grpc_tools_node_protoc`, which invokes `protoc` and automatically uses the plugin (so you don't need the `--plugin` argument). `@grpc/grpc-js` has the same API as `grpc`, with only a few differences. There is a section in the [`@grpc/grpc-js` README](https://www.npmjs.com/package/@grpc/grpc-js) about migrating from `grpc`, including a point about using `grpc-tools`. In particular, you should use the `generate_package_definitions` option that this issue is originally about to generate an object that can be loaded into either library.

**Comment by steven-supersolid** [comment]
Thanks! I got it working with `grpc-tools`
