### ISSUE TITLE
Download grpc-node got 403

### ISSUE THREAD

**Issue by tdungnguyen** [grpc/grpc-node#141]
Short description: 
npm info lifecycle grpc@1.7.3~install: grpc@1.7.3

> grpc@1.7.3 install /usr/src/app/node_modules/google-gax/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.39
node-pre-gyp info using node@6.12.3 | linux | x64
node-pre-gyp info check checked for "/usr/src/app/node_modules/google-gax/node_modules/grpc/src/node/extension_binary/node-v48-linux-x64-musl/grpc_node.node" (not found)
node-pre-gyp http GET https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.7.3/node-v48-linux-x64-musl.tar.gz
node-pre-gyp http 403 https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.7.3/node-v48-linux-x64-musl.tar.gz
node-pre-gyp ERR! Tried to download(403): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.7.3/node-v48-linux-x64-musl.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.7.3 and node@6.12.3 (node-v48 ABI, musl) (falling back to source compile with node-gyp)
node-pre-gyp http 403 status code downloading tarball https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.7.3/node-v48-linux-x64-musl.tar.gz
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@6.12.3 | linux | x64
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@6.12.3 | linux | x64
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:449:14)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:353:11
gyp ERR! stack     at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:69:16)
gyp ERR! stack     at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:81:29)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:90:16
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Linux 3.13.0-37-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--library=static_library" "--module=/usr/src/app/node_modules/google-gax/node_modules/grpc/src/node/extension_binary/node-v48-linux-x64-musl/grpc_node.node" "--module_name=grpc_node" "--module_path=/usr/src/app/node_modules/google-gax/node_modules/grpc/src/node/extension_binary/node-v48-linux-x64-musl"
gyp ERR! cwd /usr/src/app/node_modules/google-gax/node_modules/grpc
gyp ERR! node -v v6.12.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --library=static_library --module=/usr/src/app/node_modules/google-gax/node_modules/grpc/src/node/extension_binary/node-v48-linux-x64-musl/grpc_node.node --module_name=grpc_node --module_path=/usr/src/app/node_modules/google-gax/node_modules/grpc/src/node/extension_binary/node-v48-linux-x64-musl' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/src/app/node_modules/google-gax/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:920:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
node-pre-gyp ERR! System Linux 3.13.0-37-generic
node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/src/app/node_modules/google-gax/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd /usr/src/app/node_modules/google-gax/node_modules/grpc
node-pre-gyp ERR! node -v v6.12.3
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --library=static_library --module=/usr/src/app/node_modules/google-gax/node_modules/grpc/src/node/extension_binary/node-v48-linux-x64-musl/grpc_node.node --module_name=grpc_node --module_path=/usr/src/app/node_modules/google-gax/node_modules/grpc/src/node/extension_binary/node-v48-linux-x64-musl' (1)
npm info lifecycle grpc@1.7.3~install: Failed to exec install script

**Comment by murgatroid99** [comment]
The problem here is that that specific version differentiates between binaries for glibc vs musl libc (Alpine), but we did not actually publish binaries for Alpine. It's a bit hard to see in that error log, but it actually tried to fall back to building the library from source, but it failed because python was not available. If you want to try to build from source, you will need to install the `python` and `build-base` Alpine packages.

**Comment by murgatroid99** [comment]
I would like to note that for 1.8.x, we do distribute precompiled binaries for Alpine, so if you use that version you will not encounter this problem.

**Comment by nikhilag** [comment]
I am facing the same issue with setting up electron 2.0 with create-react-app. How do I get the build-base package? I already have Python setup on my machine.

**Comment by henrik242** [comment]
I did an `apt-get install build-essential` to get rid of the download problem.

**Comment by jhagroshan** [comment]
"scripts": {
    "postinstall": "npm rebuild grpc --target=6.1.0 --target_arch=x64 --target_platform=linux --target_libc=glibc"
  },

running the above fixes it but would prefer a cleaner solution

**Comment by nikhilag** [comment]
@henrik242 Any idea what the corresponding fix will be for mac? I am repeatedly seeing the following error:-

> Error: /usr/local/bin/node exited with code 1
Error output:
node-pre-gyp ERR! Tried to download(403): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.9.1/electron-v1.8-darwin-x64-unknown.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.9.1 and electron@1.8.2 (electron-v1.8 ABI, unknown) (falling back to source compile with node-gyp) 
Traceback (most recent call last):
  File "./gyp-mac-tool", line 611, in <module>
    sys.exit(main(sys.argv[1:]))
  File "./gyp-mac-tool", line 28, in main
    exit_code = executor.Dispatch(args)
  File "./gyp-mac-tool", line 43, in Dispatch
    return getattr(self, method)(*args[1:])
  File "./gyp-mac-tool", line 246, in ExecFilterLibtool
    if not libtool_re.match(line) and not libtool_re5.match(line):
TypeError: cannot use a string pattern on a bytes-like object
make: *** [Release/libgrpc.a] Error 1
gyp ERR! build error

**Comment by nikhilag** [comment]
@murgatroid99 What is build-base Alpine package and how do I install it on mac?

**Comment by nicolasnoble** [comment]
The original issue which was about Alpine Linux specifically has been long fixed. Any and all other issues in this thread aren't related to it.

@nikhilag: Alpine Linux is, well, a Linux distribution. Has nothing to do with MacOS.

If you are still experiencing unrelated issues with your Mac, please open a separate issue.

**Comment by razorMureithi** [comment]
i have the save the same problem.
npm install -g grpc@1.10.1

> grpc@1.10.1 install /usr/lib/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp ERR! Tried to download(403): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.10.1/node-v64-linux-x64-glibc.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.10.1 and node@10.1.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp)

**Comment by nicolasnoble** [comment]
@razorMureithi this is working as intended. You are trying to install an obsolete version of gRPC for a version of nodejs that didn't exist at the time of publication. You can 1) upgrade to the latest version of gRPC or 2) downgrade to nodejs 8 or 9 that were then supported by grpc 1.10 or 3) have a compiler on your system to properly fallback on compiling from sources.

**Comment by patrice4github** [comment]
#3 Didn't work for me.
#1 I did a brew install grpc hoping to get the latest version, which I did. But still have the same error. If I have the grpc_node_plugin locally, shouldn't my npm install try to use that instead of downloading an old version?

**Comment by nicolasnoble** [comment]
Please open a new issue following our template, filing all required fields, so we can help you.

**Comment by Coehill** [comment]
Getting the same issue on Manjaro Linux, any fixes for this?

**Comment by nicolasnoble** [comment]
Please open new issues following our template instead of updating old resolved bugs with "me too".
