### ISSUE TITLE
grpc-js: string in metadata be split with comma

### ISSUE THREAD

**Issue by LeonsChun** [grpc/grpc-node#1412]
### Problem description
Set a string "1,2" in metedata and put in request. In server, the string in metadata is not "1,2" but ["1", "2"].

### Reproduction steps
![image](https://user-images.githubusercontent.com/3643627/81390107-7f271b00-914d-11ea-8f2a-604fbc6f42fd.png)

**Comment by murgatroid99** [comment]
This is intentional. The [gRPC protocol definition](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md) says this:

> Custom-Metadata header order is not guaranteed to be preserved except for values with duplicate header names. **Duplicate header names may have their values joined with "," as the delimiter and be considered semantically equivalent.** Implementations must split Binary-Headers on "," before decoding the Base64-encoded values.

**Comment by LeonsChun** [comment]
The string is not splitted in grpc-node. It's a bug?

![image](https://user-images.githubusercontent.com/3643627/81431278-7bb68280-9193-11ea-97d9-999ea3d45cb6.png)

**Comment by murgatroid99** [comment]
It turns out that I misunderstood the spec. That is a bug in grpc-js. There's a fix pending in #1414, and I can probably have that out next week.

**Comment by lwmxiaobei** [comment]
> It turns out that I misunderstood the spec. That is a bug in grpc-js. There's a fix pending in #1414, and I can probably have that out next week.

hi, Have you fixed this ?

**Comment by murgatroid99** [comment]
I published the fix for this in grpc-js version 1.0.4.
