### ISSUE TITLE
Bug when calling server.tryShutdown

### ISSUE THREAD

**Issue by franciscocpg** [grpc/grpc-node#142]
**OS Version**
Linux 4.14.11-1-ARCH #1 SMP PREEMPT Wed Jan 3 07:02:42 UTC 2018 x86_64 GNU/Linux

**Node**
v9.3.0

**grpc-node**
1.8.0

When calling `server.tryShutdown()` without a callback I'm getting this error:
```
#
# Fatal error in ../deps/v8/src/objects.cc, line 3574
# Check failed: receiver->IsJSFunction().
#
```

Isn't this (no callback) supposed to be handled by the library?

**Comment by murgatroid99** [comment]
The callback is not optional. But we should be checking and throwing a more helpful error instead of crashing.

**Comment by murgatroid99** [comment]
In 1.8.4 this now throws an exception indicating that a callback argument is required.

**Comment by franciscocpg** [comment]
:+1:
