### ISSUE TITLE
https://github.com/google/voice-builder

### ISSUE THREAD

**Issue by hack3r3d** [grpc/grpc-node#1428]
### Problem description
I'm working my through the installation instructions for Google Voice Builder (https://github.com/google/voice-builder).

I'm on this step, running this command

./deploy.sh cloud_functions

The command fails though with the following grpc error "command failed."

error /private/var/folders/_c/8_qmmzq12wbb0lzjhqyf9b2c0000gn/T/tmp.duYBCYG1/functions/node_modules/grpc: Command failed.
Exit code: 1

### Reproduction steps
I'm literally just going through these instructions.
https://github.com/google/voice-builder

Clone this project to your current directory by:

1. git clone https://github.com/google/voice-builder.git && cd voice-builder

If you haven't logged in to your account via gcloud yet, please log in by:

2. gcloud auth login
Also, if you haven't logged in to your account via firebase, please log in by:

3. firebase login --no-localhost

4. Open deploy.sh and edit the following variables:

PROJECT_NAME: your created GCP project's name from Prerequisite 1) e.g. vb-test-project
PROJECT_ID: your created GCP project's id from Prerequisite 1) e.g. vb-test-project
GCP_SERVICE_ACCOUNT_EMAIL: Use Compute Engine service account (you can find one by clicking on top left menu under "IAM & admin > Service accounts") e.g. 123456778911-compute@developer.gserviceaccount.com
Create GCS buckets for Voice Builder to store each job data

5. ./deploy.sh initial_setup
Deploy cloud functions component

6. ./deploy.sh cloud_functions

### Environment
 - Mac 10.15.4
 - Node version 13.10.1
 - Node installation method [NVM]

### Additional context
error /private/var/folders/_c/8_qmmzq12wbb0lzjhqyf9b2c0000gn/T/tmp.duYBCYG1/functions/node_modules/grpc: Command failed.
Exit code: 1
Command: ./node_modules/.bin/node-pre-gyp install --fallback-to-build --library=static_library
Arguments: 
Directory: /private/var/folders/_c/8_qmmzq12wbb0lzjhqyf9b2c0000gn/T/tmp.duYBCYG1/functions/node_modules/grpc
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.10.3
node-pre-gyp info using node@13.10.1 | darwin | x64
node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp info check checked for "/private/var/folders/_c/8_qmmzq12wbb0lzjhqyf9b2c0000gn/T/tmp.duYBCYG1/functions/node_modules/grpc/src/node/extension_binary/node-v79-darwin-x64-unknown/grpc_node.node" (not found)
node-pre-gyp http GET https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.13.0/node-v79-darwin-x64-unknown.tar.gz
node-pre-gyp http 403 https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.13.0/node-v79-darwin-x64-unknown.tar.gz
node-pre-gyp WARN Tried to download(403): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.13.0/node-v79-darwin-x64-unknown.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for grpc@1.13.0 and node@13.10.1 (node-v79 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp http 403 status code downloading tarball https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.13.0/node-v79-darwin-x64-unknown.tar.gz 
node-pre-gyp WARN Pre-built binaries not installable for grpc@1.13.0 and node@13.10.1 (node-v79 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error Connection closed while downloading tarball file 
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.7
gyp info using node@13.10.1 | darwin | x64
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.7
gyp info using node@13.10.1 | darwin | x64
gyp info ok 
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.7
gyp info using node@13.10.1 | darwin | x64
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.7
gyp info using node@13.10.1 | darwin | x64
gyp info find Python using Python version 2.7.16 found at "/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python"
gyp info find Python using Python version 2.7.16 found at "/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python"
gyp info spawn /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
gyp info spawn args [
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/private/var/folders/_c/8_qmmzq12wbb0lzjhqyf9b2c0000gn/T/tmp.duYBCYG1/functions/node_modules/grpc/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',

-- truncated --

**Comment by murgatroid99** [comment]
That package appears to depend on a weirdly old version of `grpc`, which is not compatible with the recent version of Node that you are using. You will have to downgrade your version of Node, version 8 should probably work. If not, you may need to use Node 6.

I have also filed google/voice-builder#36 to ask them to fix this on their side.
