### ISSUE TITLE
Add support for electron v8

### ISSUE THREAD

**Issue by ArcticTee** [grpc/grpc-node#1429]
### Problem description
I want to use grpc with electron v8.2.5 (stable).
But when I am running `"postinstall": "npm rebuild grpc --target=8.2.5 --runtime=electron"`

I get this error:

> Pre-built binaries not found for grpc@1.24.2 and electron@8.2.5 (electron-v8.2 ABI, unknown) (falling back to source compile with node-gyp) 

If do not rebuild I get the error mentioned in [#6138](https://github.com/grpc/grpc/issues/6138)

> [Error: .../node_modules/grpc/src/node/extension_binary/grpc_node.node: undefined symbol: GENERAL_NAME_free]

### Environment
 - OS name, version and architecture: macOS Catalina 10.15.3
 - Node version v12.13.0
 - Node installation method yarn / lerna
 - Package name and version grpc@1.24.2

### Additional context
related to 
 - #989 Electron v6 and gRPC error
 - #1235 Publish build for electron 7.1
 - [#6138](https://github.com/grpc/grpc/issues/6138) Error running gRPC greeter example with electron

Is there any workaround? Or is the release of v1.25.0 near?

**Comment by josiahruddell** [comment]
For real; if gRPC node isn't going to support electron any longer it would be informative to know. Electron v5 was the last version prebuilt with gRPC. Countless CI build hours wasted.

**Comment by murgatroid99** [comment]
I am working on this. I think I can get a new release out soon with the new binary files, including the ones for Electron.

**Comment by manu-st** [comment]
Hi @murgatroid99. Could we also do it for Electron v9 that was just released?

**Comment by murgatroid99** [comment]
Yes, the Electron binaries will go out at the same time.

**Comment by danst3in** [comment]
What is the most recent version of electron it is working with? When I was using gRPC previously I had success at Electron 7.0.1, but I am now trying to move to @grpc/grpc-js to convert the app to TypeScript. Would love to know before I get way down a rabbit hole. Thanks!

**Comment by murgatroid99** [comment]
I believe that the latest version of Electron that `grpc` works with is in fact 7.0.x. As far as I know, `@grpc/grpc-js` works with all recent versions of Electron.

**Comment by ConorEB** [comment]
Hello! We are very excited for the Electron 9 binaries. Do you have a general timeline on when you think they are expected to release?

**Comment by murgatroid99** [comment]
I'm hoping to get them out this week, but it might be next week.

**Comment by duhruh** [comment]
okay I found a very hack-y workaround, So it seems the current build is working, i just don't believe it's uploading correctly. So if you're like me and you don't mind doing a bit of hackery until this is fixed  for real you can just download the artifact directly from github actions

this  is the one i used for electron 8.3 windows 64:
https://github.com/grpc/grpc-node/suites/742611080/artifacts/7641115

once you download that then create the folder

```node_modules\grpc\src\node\extension_binary\electron-v8.3-win32-x64-unknown```

and place the `grpc_node.node` file you extracted from the artifact in there. 

This worked for me.

**Comment by keegan-lillo** [comment]
Looks like grpc@1.24.3 adds support for electron 9! Thanks for the hard work everyone. Looking forward to finally being able to update.

**Comment by murgatroid99** [comment]
As mentioned, grpc@1.24.3 has support for Electron 8 and 9.

@duhruh The binaries appear to have been uploaded successfully on my side. How is it failing for you?
