### ISSUE TITLE
Browser optimized build

### ISSUE THREAD

**Issue by skhavari** [grpc/grpc-node#1431]
### Is your feature request related to a problem? Please describe.
Need small module footprint for browser clients

### Describe the solution you'd like
A build optimized for the browser, client only

### Describe alternatives you've considered
Not considering any

### Additional context
Pretty easy to digest, just looking for smallest bundle footprint for a browser client talking with a grpc-web service.

**Comment by murgatroid99** [comment]
If you want to talk to a grpc-web service, I think you want to file this issue in the [grpc-web repository](https://github.com/grpc/grpc-web).
