### ISSUE TITLE
How to run awaits under async call

### ISSUE THREAD

**Issue by tweenietomatoes** [grpc/grpc-node#1437]
My server is like the following:

```
call.on('data', async (incoming) => {
const result = await something_database_related(incoming...);
call.write(result);
});
call.on('end', () => {
call.end();
});
```

But i couldn't get reply from stream as it's not writing to call. Am i completely wrong?

**Comment by murgatroid99** [comment]
What is the actual behavior that you are seeing when you run your client?

**Comment by tweenietomatoes** [comment]
i am not getting reply, nothing :D.

**Comment by tweenietomatoes** [comment]
When i drop await and just type 

const result = 'TEST'
call.write(result);

i am getting TEST...

**Comment by murgatroid99** [comment]
Are you saying that you never get the result from `something_database_related`?

**Comment by tweenietomatoes** [comment]
its very interesting :) i got bunch of sql queries , when i add them i can get the result from something database related but i can't write it to call. basically no reply.

**Comment by murgatroid99** [comment]
Can you get the result from them using `await` in an `async` function outside of the context of `grpc`?

**Comment by tweenietomatoes** [comment]
yes

**Comment by murgatroid99** [comment]
Can you get that result and then write it to a gRPC call in an `async` function outside of the context of a `data` event handler?

**Comment by tweenietomatoes** [comment]
```
console.log(database_related_result);
call.write({ message: database_related_result });
```

i can see database_related_result in console. but somehow write is not taking it or maybe my fault.

**Comment by murgatroid99** [comment]
Can you share the contents of your `.proto` file?

**Comment by tweenietomatoes** [comment]
```
syntax = "proto3";

package comm;

service Comm {
    rpc Status (stream Request) returns (stream Reply) {}
}

message Request {
    string message = 1;
}

message Reply {
    string message = 1;
}

```

**Comment by tweenietomatoes** [comment]
outside of call.on('data'

i can't get call.request.message 

:D undefined.

**Comment by murgatroid99** [comment]
There is no `call.request`. I'm guessing you mean that this is handler code on the server, in which case the requests are the objects you're getting in the `data` handler.

**Comment by tweenietomatoes** [comment]
its working now.  I dropped first Stream from Request in proto.
So i thought i am streaming request why? why?. sad.

**Comment by tweenietomatoes** [comment]
i also removed call.on('data'

**Comment by tweenietomatoes** [comment]
now i put it under call.on('data' and it's not working again.
stream is removed.

strange.
