### ISSUE TITLE
Don't know what to write here really.

### ISSUE THREAD

**Issue by tweenietomatoes** [grpc/grpc-node#1438]
Connection is closing before i write response to it.

First of all here is my GRPC-Java Client.

```
StreamObserver<Request> requestObserver = asyncStub.status(new StreamObserver<Reply>() {
...
Observer... on next on error on completed part here. }
...
try catches surrounded below in actuality.
requestObserver.onNext(newMessage(message));
requestObserver.onCompleted();
```

My GRPC-Node Server

```
call.on('data', () => { do_something(); console.log('Data'); call.write(something); })
call.on('end', () => { console.log('End'); call.end(); } )
```

**I put System.out.println("Completed") on requestObserver's onCompleted. So i get a message when it completes.**

**Then i put console.log() on node's each call.on just before call.write and call.end**

Problem is, connection is closing before the call.write(). I see End message first.

It seems like call.on('end', ())  is working before call.on('data', ()) 

:( I didn't understand anything.

**Comment by murgatroid99** [comment]
Is your `do_something` function asynchronous?

**Comment by tweenietomatoes** [comment]
yis.

**Comment by murgatroid99** [comment]
What's probably happening here is that the `data` event is triggered, then you call `do_something`, then the `end` event triggers and you see the `End` output, then `do_something` finishes and you see the `Data` output. You can test this by moving the `Data` output to before you call `do_something`.

I'm not sure, but I think you may be able to do that by calling [`call.pause()`](https://nodejs.org/api/stream.html#stream_readable_pause) before calling `do_something()`, and calling [`call.resume()`](https://nodejs.org/api/stream.html#stream_readable_resume) after writing the response. This will ensure that after you get each data event, you won't get another one until you have finished processing the previous one. You probably want to do that anyway, to ensure that you send responses in the same order that you get the requests.

If that doesn't help you will need to find another way to track which requests you have responded to, and only call `call.end()` when you have sent all of the responses.

**Comment by tweenietomatoes** [comment]
do i need to call.end if i return the last call.write() ?

for example:

```
call.write
call.write
return call.write();
```

**Comment by murgatroid99** [comment]
`return call.write()` doesn't do anything. `call.end` is how you say that you're done writing, so you need to call it.

**Comment by tweenietomatoes** [comment]
i put call.pause before async function and call.resume after async function.

now it's working ok.

i think it should be documented somehow as it's very normal to use async database thingies to process incoming data.

**Comment by murgatroid99** [comment]
Everything I said applies to built in Node streams in general, and how they interact with async functions. None of it is specific to gRPC.

**Comment by tweenietomatoes** [comment]
yes but documentation still would be helpful for those having brain inflamation like me.
