### ISSUE TITLE
Correct way to handle error w/client streaming to server?

### ISSUE THREAD

**Issue by filburt-turle** [grpc/grpc-node#1439]
Hi,

I'm trying to understand what's the best way to handle an error when the client is streaming data and the message they send has items that you don't want to except. I'm able to throw an error at the `call.on("data", () => {})` stage, but my grpc server goes down as well.

When I capture the error in a variable and hold it till the request is done, then send the error during the `call.on("end" () => {})` stage the server is fine and the client gets the error. The problem with this is I don't want to wait till the client is finished streaming, I want to kill the connection for the client when the error first occurs.

So my question is how to kill or terminate a connection with a client when you first notice an error on the server side without bringing down the server?

The reason why waiting is not ideal is that the client may be streaming indefinitely for my use case.

**Comment by murgatroid99** [comment]
If the server is sending a unary response, you can send the error by calling the callback with the error as the first argument. If the server is sending a streaming response, you can send an error by calling `call.emit('error', error)`.
