### ISSUE TITLE
Failed at the grpc@1.20.0 install script.

### ISSUE THREAD

**Issue by ReaperTech** [grpc/grpc-node#1440]
### Problem description
Cannot install firebase - (Angular app)

### Reproduction steps
Run npm install --save firebase

### Environment
 - W10
 - Node version v13.3.0
 - Node installation method - download from nodejs
 - Package name  gRPC@1.20.0

### Additional context
I've tried using powershell as admin + turning off defender, but get the same error.
The following issues don't help.
1) https://stackoverflow.com/questions/58935430/failed-at-the-grpc1-20-0-install-script-while-installing-react
2) https://github.com/grpc/grpc-node/issues/121
![image](https://user-images.githubusercontent.com/43549638/82839675-70bc5b80-9ed0-11ea-82f3-d73e5d164841.png)

**Comment by murgatroid99** [comment]
Currently no version of `grpc` supports Node 13. Node 12 should work, and Node 10 would definitely work.

**Comment by ReaperTech** [comment]
Thanks @murgatroid99. I can confirm running `npm install --save firebase` with Node 12.6.3 was successful.
