### ISSUE TITLE
Dependency on google-auth-library 6 breaks Node 8 support

### ISSUE THREAD

**Issue by samtstern** [grpc/grpc-node#1442]
### Problem description
grpc-js claims support for Node 8 or Node 10:
https://github.com/grpc/grpc-node/blob/master/packages/grpc-js/package.json#L9

However a recent commit added a new dependency on `google-auth-library@6`:
https://github.com/grpc/grpc-node/commit/010ef569f7f83007642f3f69e0ce13dee615d680

This release of google-auth-library requires Node 10+ in the engines field:
https://github.com/googleapis/google-auth-library-nodejs/releases/tag/v6.0.0

### Reproduction steps
This was reported to the Firebase CLI as a breaking issue on our side:
https://github.com/firebase/firebase-tools/issues/2284

### Environment
 - OS name, version and architecture: macOS
 - Node version: 8.x
 - Node installation method: nvm
 - If applicable, compiler version: N/A
 - Package name and version: grpc-js@1.0.4

### Additional context
None

**Comment by murgatroid99** [comment]
I did not realize that that would be a problem because grpc-js is not actually loading google-auth-library in any currently accessible code path. I have a fix in #1443.

**Comment by murgatroid99** [comment]
I have published grpc-js version 1.0.5 with the fix for this.

**Comment by samtstern** [comment]
@murgatroid99 thank you!
