### ISSUE TITLE
grpc for node in a firebase app

### ISSUE THREAD

**Issue by osso23** [grpc/grpc-node#1452]
I cloned a basic react firebase app :
 https://github.com/the-road-to-react-with-firebase/react-redux-firebase-authentication
When I try npm i I get the following error:
`> grpc@1.16.0 install C:\Users\hp\Desktop\react-redux-firebase-authentication-master\node_modules\grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://node-precompiled-binaries.grpc.io/grpc/v1.16.0/node-v83-win32-x64-unknown.tar.gz
node-pre-gyp WARN Pre-built binaries not found for grpc@1.16.0 and node@14.0.0 (node-v83 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Pre-built binaries not installable for grpc@1.16.0 and node@14.0.0 (node-v83 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error Connection closed while downloading tarball file
gyp ERR! find Python 
gyp ERR! find Python Python is not set from command line or npm configuration
gypgyp ERR! find Python  Python is not set from environment variable PYTHON
ERR!gyp  find PythonERR!
 gypfind Python  checking if "python" can be used
ERR!gyp  find PythonERR! Python is not set from command line or npm configuration
 find Pythongyp - "python" is not in PATH or produced an error
 gypERR!  ERR!find Python  Python is not set from environment variable PYTHON
gypfind Python  checking if "python2" can be used
gypERR!  ERR!find Python checking if "python" can be used
 gypfind Python  - "python2" is not in PATH or produced an error
gypERR!  ERR!find Python  - "python" is not in PATH or produced an error
find Pythongyp checking if "python3" can be used
 gypERR! find Python  checking if "python2" can be used
ERR!gyp  find PythonERR! - "python3" is not in PATH or produced an error
 gypfind Python  - "python2" is not in PATH or produced an error
ERR!gyp  find PythonERR! checking if the py launcher can be used to find Python 2
 gypfind Python  checking if "python3" can be used
gypERR!  find PythonERR! - "py.exe" is not in PATH or produced an error
gyp  ERR!find Python  - "python3" is not in PATH or produced an error
find Pythongyp checking if Python is C:\Python27\python.exe
gyp  ERR!ERR!  find Pythonfind Python checking if the py launcher can be used to find Python 2
 - "C:\Python27\python.exe" could not be run
gyp ERR! gypfind Python  checking if Python is C:\Python37\python.exe
gyp ERR! find Python - "C:\Python37\python.exe" could not be run
gyp ERR! find Python
gyp ERR! find Python **********************************************************
ERR!gyp  find PythonERR! - "py.exe" is not in PATH or produced an error
 gypfind Python  You need to install the latest version of Python.
ERR!gyp  find PythonERR! find Python checking if Python is C:\Python27\python.exe
gyp Node-gyp should be able to find and use Python. If not,
 gypERR!  ERR!find Python  - "C:\Python27\python.exe" could not be run
find Pythongyp you can try one of the following options:
 gypERR!  ERR!find Python find Python checking if Python is C:\Python37\python.exe
 - Use the switch --python="C:\Path\To\python.exe"
gypgyp  ERR!ERR! find Python  - "C:\Python37\python.exe" could not be run
find Pythongyp   (accepted by both node-gyp and npm)
gyp ERR! find Python - Set the environment variable PYTHON
gyp  ERR!ERR!  find Pythonfind Python - Set the npm configuration variable python:

gypgyp  ERR!ERR!  find Pythonfind Python **********************************************************
gyp   npm config set python "C:\Path\To\python.exe"
gyp ERR! find Python You need to install the latest version of Python.
gyp  ERR!ERR!  find Pythonfind Python For more information consult the documentation at:
 Node-gyp should be able to find and use Python. If not,
gypgyp  ERR!ERR!  find Pythonfind Python https://github.com/nodejs/node-gyp#installation
gyp ERR! find Python **********************************************************
gyp  you can try one of the following options:
gyp ERR! ERR!find Python  - Use the switch --python="C:\Path\To\python.exe"
gypfind Python
ERR! find Python   (accepted by both node-gyp and npm)
gypgyp  ERR!ERR! find Python - Set the environment variable PYTHON
gyp ERR! find Python - Set the npm configuration variable python:
 gypconfigure error
ERR! find Pythongyp   npm config set python "C:\Path\To\python.exe"
 gypERR!  ERR!stack  Error: Could not find any Python installation to use
gypfind Python For more information consult the documentation at:
gyp ERR!  ERR!find Python  https://github.com/nodejs/node-gyp#installation
gypstack      at PythonFinder.fail (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:307:47)
gyp ERR! stack     at PythonFinder.runChecks (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:136:21)
ERR!gyp  find PythonERR! **********************************************************
 gypstack      at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:225:16)
ERR!gyp  find PythonERR!
 stack     at PythonFinder.execFileCallback (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:271:16)
gyp ERR! stackgyp     at exithandler (child_process.js:310:5)
 gypERR!  configure errorERR!
 stack     at ChildProcess.errorhandler (child_process.js:322:5)
gypgyp  ERR!ERR!  stackstack Error: Could not find any Python installation to use
     at ChildProcess.emit (events.js:315:20)
gypgyp  ERR!ERR!  stackstack     at PythonFinder.fail (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:307:47)
     at Process.ChildProcess._handle.onexit (internal/child_process.js:274:12)
gypgyp  ERR!ERR!  stackstack     at PythonFinder.runChecks (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:136:21)       
     at onErrorNT (internal/child_process.js:468:16)
gypgyp  ERR!ERR!  stackstack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:225:16)     
     at processTicksAndRejections (internal/process/task_queues.js:84:21)
gyp ERR! gypstack      at PythonFinder.execFileCallback (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:271:16)
ERR! gypSystem  Windows_NT 10.0.18362
ERR! gypstack      at exithandler (child_process.js:310:5)
ERR!gyp  commandERR! "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--library=static_library" "--module=C:\\Users\\hp\\Desktop\\react-redux-firebase-authentication-master\\node_modules\\grpc\\src\\node\\extension_binary\\node-v83-win32-x64-unknown\\grpc_node.node" "--module_name=grpc_node" "--module_path=C:\\Users\\hp\\Desktop\\react-redux-firebase-authentication-master\\node_modules\\grpc\\src\\node\\extension_binary\\node-v83-win32-x64-unknown" "--napi_version=6" "--node_abi_napi=napi"
 gypstack      at ChildProcess.errorhandler (child_process.js:322:5)
ERR!gyp  cwdERR! C:\Users\hp\Desktop\react-redux-firebase-authentication-master\node_modules\grpc
 gypstack      at ChildProcess.emit (events.js:315:20)
ERR!gyp  node -v v14.0.0
ERR!gyp  stackERR!     at Process.ChildProcess._handle.onexit (internal/child_process.js:274:12)
gyp ERR!  node-gyp -vstack v5.1.0
     at onErrorNT (internal/child_process.js:468:16)
gypgyp  ERR! ERR!not ok
stack     at processTicksAndRejections (internal/process/task_queues.js:84:21)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" 
"--fallback-to-build" "--library=static_library" "--module=C:\\Users\\hp\\Desktop\\react-redux-firebase-authentication-master\\node_modules\\grpc\\src\\node\\extension_binary\\node-v83-win32-x64-unknown\\grpc_node.node" "--module_name=grpc_node" "--module_path=C:\\Users\\hp\\Desktop\\react-redux-firebase-authentication-master\\node_modules\\grpc\\src\\node\\extension_binary\\node-v83-win32-x64-unknown" "--napi_version=6" "--node_abi_napi=napi"
gyp ERR!node-pre-gyp ERR!  build errorcwd 
 C:\Users\hp\Desktop\react-redux-firebase-authentication-master\node_modules\grpc
gyp node-pre-gypERR!  ERR!node -v  v14.0.0
gypstack  Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --library=static_library --module=C:\Users\hp\Desktop\react-redux-firebase-authentication-master\node_modules\grpc\src\node\extension_binary\node-v83-win32-x64-unknown\grpc_node.node --module_name=grpc_node --module_path=C:\Users\hp\Desktop\react-redux-firebase-authentication-master\node_modules\grpc\src\node\extension_binary\node-v83-win32-x64-unknown --napi_version=6 --node_abi_napi=napi' (1)
ERR!node-pre-gyp  ERR!node-gyp -v  v5.1.0
stackgyp     at ChildProcess.<anonymous> (C:\Users\hp\Desktop\react-redux-firebase-authentication-master\node_modules\grpc\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
 node-pre-gypERR!  ERR!not ok
stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1051:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
node-pre-gyp ERR! System Windows_NT 10.0.18362
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\hp\\Desktop\\react-redux-firebase-authentication-master\\node_modules\\grpc\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd C:\Users\hp\Desktop\react-redux-firebase-authentication-master\node_modules\grpc
node-pre-gyp ERR! node -v v14.0.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --library=static_library --module=C:\Users\hp\Desktop\react-redux-firebase-authentication-master\node_modules\grpc\src\node\extension_binary\node-v83-win32-x64-unknown\grpc_node.node --module_name=grpc_node --module_path=C:\Users\hp\Desktop\react-redux-firebase-authentication-master\node_modules\grpc\src\node\extension_binary\node-v83-win32-x64-unknown --napi_version=6 --node_abi_napi=napi' (1)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.16.0 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grpc@1.16.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hp\AppData\Roaming\npm-cache\_logs\2020-06-01T15_06_09_124Z-debug.log`

I tried different ways like using yarn instead of npm but I still can't figure it out.

### Environment
 - Windows 10
 - Node 14.0.0
-gRPC@1.16.0

**Comment by murgatroid99** [comment]
> node-pre-gyp WARN Tried to download(404): https://node-precompiled-binaries.grpc.io/grpc/v1.16.0/node-v83-win32-x64-unknown.tar.gz
> node-pre-gyp WARN Pre-built binaries not found for grpc@1.16.0 and node@14.0.0 (node-v83 ABI, unknown) (falling back to source compile with node-gyp)
> node-pre-gyp WARN Pre-built binaries not installable for grpc@1.16.0 and node@14.0.0 (node-v83 ABI, unknown) (falling back to source compile with node-gyp)

These errors mean that the version of `grpc` you are getting is not compatible with the version of Node that you are using. If you are stuck with that version of `grpc`, you will need to use an older version of Node. Specifically, you will need to use Node 10 or earlier.

Alternatively, if you can upgrade the dependency that is pulling in `grpc`, you may be able to use a newer version of Node.

**Comment by osso23** [comment]
> > node-pre-gyp WARN Tried to download(404): https://node-precompiled-binaries.grpc.io/grpc/v1.16.0/node-v83-win32-x64-unknown.tar.gz
> > node-pre-gyp WARN Pre-built binaries not found for grpc@1.16.0 and node@14.0.0 (node-v83 ABI, unknown) (falling back to source compile with node-gyp)
> > node-pre-gyp WARN Pre-built binaries not installable for grpc@1.16.0 and node@14.0.0 (node-v83 ABI, unknown) (falling back to source compile with node-gyp)
> 
> These errors mean that the version of `grpc` you are getting is not compatible with the version of Node that you are using. If you are stuck with that version of `grpc`, you will need to use an older version of Node. Specifically, you will need to use Node 10 or earlier.
> 
> Alternatively, if you can upgrade the dependency that is pulling in `grpc`, you may be able to use a newer version of Node.

   I am a beginner and cannot figure out how to find "the dependency that pulls in grpc in my folder"
Please guide me through this process.
 Thank you

**Comment by murgatroid99** [comment]
The simplest way to determine that would be to run the installation successfully on an older version of Node, then run `npm ls grpc` to see what depends on it.

However, looking at the dependency list in that repository, it is almost definitely `firebase` itself.
