### ISSUE TITLE
grpc-js: disable http proxy with client options

### ISSUE THREAD

**Issue by badsyntax** [grpc/grpc-node#1453]
### Is your feature request related to a problem? Please describe.
When a system level http proxy is set (eg with `http_proxy`), and i attempt to connect to a grpc server running on **localhost**, the client never connects. I don't think it makes sense for requests to localhost to go through the http proxy.

### Describe the solution you'd like
I would like to disable http proxying in the client with a client option, eg `{ 'grpc.enable_http_proxy': 0 }`

### Describe alternatives you've considered
Using env vars work, eg: `no_grpc_proxy=localhost,127.0.0.0/8`, but i don't want to set global vars. I have built an application that attempts to connect to a localhost grpc server and I don't want to set global vars that _might_ have side effects with other applications that use grpc. 

I am more than happy to send a PR myself, but i'd like to get some feedback first. Thanks!

**Comment by murgatroid99** [comment]
I agree. This should be implemented using the option you listed.

Implementing this should be fairly simple. The channel options are already passed to [`mapProxyName`](https://github.com/grpc/grpc-node/blob/master/packages/grpc-js/src/http_proxy.ts#L120) for this purpose, they're just not used yet. The only other thing should be updating https://github.com/grpc/grpc-node/blob/master/packages/grpc-js/src/channel-options.ts to include that option, and updating the list in https://github.com/grpc/grpc-node/blob/master/PACKAGE-COMPARISON.md.

**Comment by badsyntax** [comment]
Awesome thanks! I'll send a PR

**Comment by badsyntax** [comment]
I've submitted a PR here: https://github.com/grpc/grpc-node/pull/1454

**Comment by murgatroid99** [comment]
I have published 1.0.5 with your change.

**Comment by badsyntax** [comment]
Thanks, have tested this change in my app it's working as expected 👍
