### ISSUE TITLE
@grpc/grpc-js: duplex streams of node.js doesn't fire data event

### ISSUE THREAD

**Issue by 117sparta** [grpc/grpc-node#1455]
### Problem description
I send data to the server by using the `write` method provided by duplex stream. And the proto code I use is generated by grpc-tools.  But i can't get the data event fired. And everything works fine if I use grpc package instead of @grpc/grpc-js.

### Reproduction steps
proto file is defined as below:
```
message Command {
  enum Type {
     PING = 0;
  }
  string id = 1;
  Type type = 2;
  bytes payload = 3; // payload is not required if type is 0
}

message CommandResponse {
   string reply_id = 1;
}

service Connect {
   rpc Connect(stream CommandV2) returns (stream CommandResponseV2) {}
}
```

I get ConnectClient after generating code by using grpc-tools. Then i create a connectClient instance.
```
  const connectClient = new ConnectClient(backendAddr, grpc.credentials.createSsl());
  const call = connectClient.connect(getGrpcMetaData()); // getGrpcMetaData is a function returns grpc.Metadata
  setInterval(() => {
    call.write({
        type: 0,
        id: '8888-899-0090'
    });
  }, 10000)
  call.on('data', (chunk) => {
    console.log(chunk); // this line of code will not be executed.
  });
```

### Environment
 - OS name, version and architecture: MacOS Catalina 10.15.4
 - Node version 14.3.0
 - Node installation method: yarn
 - If applicable, compiler version: vs code 1.45.0
 - Package name and version @grpc/grpc-js@1.0.4

### Additional context
The @grpc/grpc-js package is used in an electron project.

**Comment by 117sparta** [comment]
I chang the message sent to the instance of Command Message.  But it still doesn't work. And I change the interval to 30 seconds but data event still not fired.

**Comment by 117sparta** [comment]
By the way, the server can push the message to client but client can't push the message to server. And if I send a Unary request to ask server to push message to client, I can get the ping response with the unary response at the same time.

**Comment by 117sparta** [comment]
But everything works fine if I switch to use `grpc` package. But I guess it will be better to use `@grpc/grpc-js` in node and electron environment.

**Comment by murgatroid99** [comment]
What do you mean when you say "the server can push the message to client but client can't push the message to server"? The problem you described earlier looked like the opposite of that to me: you showed the client sending messages to the server, but the client did not receive any messages from the server.

Can you provide a complete code example that demonstrates the problem, including a client and a server? That way I can run it myself and figure out what the problem is.

**Comment by 117sparta** [comment]
Sorry for not replying for a long time. I guess I need to create a simple demo for you because the project i am developing is private.

**Comment by 117sparta** [comment]
@murgatroid99 Hello, I create a demo to demonstrate this problem. Could you take a look at [this](https://github.com/117sparta/duplex-react-demo)?  Thanks a lot.

**Comment by murgatroid99** [comment]
Thank you for putting together that demo. According to my tests with it so far, the problem is actually that the client only sends one or two messages, and the server only receives one. I can't yet tell why it is doing that.

**Comment by murgatroid99** [comment]
More specifically, the first message gets through to the server, then the client writes the next message to the HTTP2 stream, but the callback for that write operation is never called, and the server never sees that second message. Then all of the messages after that just pile up in the client's buffer.

In other words, the gRPC library is behaving as expected here, and Electron's version of the HTTP2 internals is not behaving as expected. So, this is an Electron bug.

I checked, and the code you have works just fine in the main process.

The simplest solution here is to not try to do this in the renderer. Electron's "main"/"renderer" split exists for a reason. You should do rendering operations in the renderer process, and other operations like network requests in the main process.

**Comment by 117sparta** [comment]
OK，I try the solution you provided and it works. Thank you for your help! I guess I can close this issue.
