### ISSUE TITLE
Improper typing with @grpc/grpc-js

### ISSUE THREAD

**Issue by greenboxal** [grpc/grpc-node#1456]
### Problem description
Although `@grpc/grpc-js` is written TypeScript, the exposed public API doesn't benefit from it.

(let me know if I should split this into multiple issues, but I believe they are all related)

#### credentials
The first issue is with the `credentials` object which is improperly typed as following:

```
/**** Client Credentials ****/
export declare const credentials: {
    [key: string]: Function;
};
```

This doesn't give visibility into which functions are available (like `createInsecure`) or their respective type signature. I believe this might is simple to fix and just a product of the `mixin` function being used in `index.ts`.

#### makeClientConstructor

A more complex issue is `makeClientConstructor` and other related functions. I understand the need for a generic implementation when loading service definitions in runtime, but it defeats the purpose of using TypeScript.

Users can cast the returned constructor to some user-defined interface, including generated types from `ts-protoc-gen`, but that's far from ideal.

I believe this library could provide  `makeClientConstructor<T>` and other similar types that would infer methods and types from the package definition using generics.

#### Package structure generated with `generate_package_definitions`

This is orthogonal to the `grpc_js` flag that was recently provided. Users wishing to provide typing definitions for generated package definitions will face trouble with Protobuf packages being used as exported names. Typescript and ES7 modules do not allow dots and other symbols on exported names.

```ts
export const ["my.package.name"] = <regular type definition>
```

The syntax above is invalid. A quick solution would be to expose the packages with some variation of the code below.

```js
module.exports.packages = {
  ["my.package.name"]: {
    ...
  },
}
```

That way it could be typed as follow:

```ts
export const packages: {
  ["my.package.name"]: <regular type definition here>
}
```

Unfortunately, this is a breaking change, so I'm not sure what to propose here.

---

I can submit a PR fixing the `credentials` issue, but I'm also interested in hearing about  `makeClientConstructor` and the package definitions.

Note that those issues I'm flagging are orthogonal to a feature request for `grpc-tools` generating type definitions.

### Environment
This is environment agnostic. Using the following packages:
* `"grpc-tools": "^1.9.0"`
* `"@grpc/grpc-js": "^1.0.4"`

**Comment by murgatroid99** [comment]
### Credentials

I did not realize that the `credentials` type looked like that. That is worth fixing.

### makeClientConstructor

Regarding `makeClientConstructor`, I do not believe that it is possible to infer the output type from the input, even if you declare a type where every string and boolean value has its literal value as the type, and you narrow the serialize and deserialize functions to handle the specific request and response types. TypeScript just doesn't provide a way to represent the correspondence.

It is unfortunate that that is the situation we have, but that function's API was designed well before TypeScript support was even a consideration. I think that the best can be done for now is generating the type of the output separately and using a single type assertion. I honestly think that is not that bad; you only miss out on validating the output of that specific function, then you get useful type information for all uses of it.

### generate_package_definitions

I think you can write something like this:

```
const packages: {
  ["my.package.name"]: <regular type definition here>
}
export = packages;
```

**Comment by greenboxal** [comment]
Regarding credentials, is that mixin really needed? I find it hard to type it properly without a very complicated type definition, and I also believe it might leak functions that weren't supposed to be exported.

Do you believe it will be fine to just list all available credentials manually? Will push a PR either way.

Regarding `makeClientConstructor`, that makes sense. I'll play with some typing definitions and see if I have any progress, but in any case it might be fine to just decide it's a wont-fix given it's mostly backward compatibility.

As for `generate_package_definitions`, will try it out and also suggest `protoc-gen-ts` libraries to do so.

Thanks!

**Comment by murgatroid99** [comment]
The type of `credentials`, or at least the part that's important, is pretty simple:

```ts
interface credentials {
  // from channel-credentials.ts
  createInsecure(): ChannelCredentials;
  createSsl(
    rootCerts?: Buffer | null,
    privateKey?: Buffer | null,
    certChain?: Buffer | null,
    verifyOptions?: VerifyOptions
  ): ChannelCredentials;
  // from call-credentials.ts
  createFromMetadataGenerator(metadataGenerator: CallMetadataGenerator);
  createFromGoogleCredential(googleCredentials: OAuth2Client): CallCredentials;
  createEmpty(): CallCredentials;
  // from index.ts
  combineChannelCredentials: (
    channelCredentials: ChannelCredentials,
    ...callCredentials: CallCredentials[]
  ): ChannelCredentials;
  combineCallCredentials: (
    first: CallCredentials,
    ...additional: CallCredentials[]
  ): CallCredentials;
}
```

`createEmpty` is used internally for dummy call credentials and isn't really useful to library users, but other than that I don't think anything else would be leaking. It would probably be fine to explicitly put those functions in a namespace or something instead of combining them with a mixin.

**Comment by murgatroid99** [comment]
This fix has been published.
