### ISSUE TITLE
@grpc/grpc-js: Missing propagate constants & types

### ISSUE THREAD

**Issue by vlucas** [grpc/grpc-node#1457]
### Problem description
The `@grpc/grpc-js` package is missing `propagate` types, and thus does not export them from the main package.

<img width="1153" alt="Screenshot 2020-06-03 17 02 42" src="https://user-images.githubusercontent.com/187/83693798-5f540d00-a5bc-11ea-8c7b-92a2f5551df4.png">

Their use is in the gRPC docs: https://grpc.github.io/grpc/node/grpc.html#.propagate__anchor 

These exist in the native gRPC package:
https://github.com/grpc/grpc-node/blob/grpc%401.24.x/packages/grpc-native-core/src/constants.js#L169

```
/**
 * Propagation flags: these can be bitwise or-ed to form the propagation option
 * for calls.
 *
 * Users are encouraged to write propagation masks as deltas from the default.
 * i.e. write `grpc.propagate.DEFAULTS & ~grpc.propagate.DEADLINE` to disable
 * deadline propagation.
 * @memberof grpc
 * @alias grpc.propagate
 * @enum {number}
 */
exports.propagate = {
  DEADLINE: 1,
  CENSUS_STATS_CONTEXT: 2,
  CENSUS_TRACING_CONTEXT: 4,
  CANCELLATION: 8,
  DEFAULTS: 65535
};
```

These do NOT exist in the pure JS package, and thus I ran into type errors when switching from the native package:
https://www.dropbox.com/s/yidakww7zzv2zhk/Screenshot%202020-06-03%2017.02.42.png?dl=0

### Reproduction steps
Give very precise steps you've discovered to reproduce your problem. If possible and applicable, provide us with a repository we can clone that contains a reproduction case. Also if possible and applicable, please include a Dockerfile that exhibits the problem if it's specific to a certain environment. Bug reports with no reproduction steps will be closed.

### Environment
 - OS name, version and architecture: MacOS 10.14.6
 - Node version: 12.13.1
 - Node installation method: homebrew
 - If applicable, compiler version: n/a
 - Package name and version: `@grpc/grpc-js` latest

### Additional context
Add any other context about the problem here. If possible, attach full logs. Do not try to omit anything for brevity, but instead include absolutely everything. Please try and set your operating system's locale to English, so that logs contain error messages in the English language.

**Comment by murgatroid99** [comment]
The fix for this is out in version 1.1.0.
