### ISSUE TITLE
GRPC Node Compression

### ISSUE THREAD

**Issue by badoet** [grpc/grpc-node#146]
Any idea on when compression is added to the grpc-node?
or if it is already supported, any example on how to set it in Server and Client?
thank you

**Comment by theogravity** [comment]
The flag is found here:

https://github.com/grpc/grpc/blob/master/include/grpc/impl/codegen/compression_types.h#L43

server:

```js
import { Server } from 'grpc'

const server = new Server({
  'grpc.default_compression_level': 2,
})
```

I've found that by default, the client will compress responses if the flag is enabled on the server.

You can verify this behavior by using a proxy between the client and server - see https://github.com/grpc/grpc-node/issues/465 for an example of this
