### ISSUE TITLE
Can't install GRPC on Node 14.3.0

### ISSUE THREAD

**Issue by iakanoe** [grpc/grpc-node#1461]
### Problem description
I need to install GRPC@1.23.3 as a high depth dependency for another npm package and I can't do it, I keep getting errors.

### Reproduction steps
```npm install grpc@1.23.3```
Actually I'm installing another package [(capacitor-pwa-firebase-msg)](https://github.com/CFT-Chris/capacitor-pwa-firebase-msg) but it is using grpc@1.23.3 as a dependency somewhere deep down.

### Environment
 - OS name, version and architecture: Windows 10 x64
 - Node version: 14.3.0 and now I'm trying 13.14.0
 - Node installation method: NVM for Windows
 - If applicable, compiler version [e.g. clang 3.8.0-2ubuntu4]
 - Package name and version: grpc@1.23.3

### Additional context
```
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Ianick\AppData\Roaming\nvm\v13.14.0\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Ianick\\AppData\\Roaming\\nvm\\v13.14.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=C:\\Users\\Ianick\\Proyectos\\AusentismoPWA\\node_modules\\grpc\\src\\node\\extension_binary\\node-v79-win32-x64-unknown\\grpc_node.node" "--module_name=grpc_node" "--module_path=C:\\Users\\Ianick\\Proyectos\\AusentismoPWA\\node_modules\\grpc\\src\\node\\extension_binary\\node-v79-win32-x64-unknown" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v79"
gyp ERR! cwd C:\Users\Ianick\Proyectos\AusentismoPWA\node_modules\grpc
gyp ERR! node -v v13.14.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\Ianick\AppData\Roaming\nvm\v13.14.0\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --library=static_library --module=C:\Users\Ianick\Proyectos\AusentismoPWA\node_modules\grpc\src\node\extension_binary\node-v79-win32-x64-unknown\grpc_node.node --module_name=grpc_node --module_path=C:\Users\Ianick\Proyectos\AusentismoPWA\node_modules\grpc\src\node\extension_binary\node-v79-win32-x64-unknown --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v79' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\Ianick\Proyectos\AusentismoPWA\node_modules\grpc\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1026:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
node-pre-gyp ERR! System Windows_NT 10.0.18362
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Ianick\\Proyectos\\AusentismoPWA\\node_modules\\grpc\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd C:\Users\Ianick\Proyectos\AusentismoPWA\node_modules\grpc
node-pre-gyp ERR! node -v v13.14.0
node-pre-gyp ERR! node-pre-gyp -v v0.13.0
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\Ianick\AppData\Roaming\nvm\v13.14.0\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --library=static_library --module=C:\Users\Ianick\Proyectos\AusentismoPWA\node_modules\grpc\src\node\extension_binary\node-v79-win32-x64-unknown\grpc_node.node --module_name=grpc_node --module_path=C:\Users\Ianick\Proyectos\AusentismoPWA\node_modules\grpc\src\node\extension_binary\node-v79-win32-x64-unknown --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v79' (1)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\@angular\compiler-cli\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\webpack-dev-server\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\watchpack-chokidar2\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\openvidu-browser\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.23.3 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grpc@1.23.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Ianick\AppData\Roaming\npm-cache\_logs\2020-06-04T18_10_53_274Z-debug.log
```

**Comment by murgatroid99** [comment]
I just published `grpc` version 1.24.3 with support for Node 14. If you can't upgrade to the new version of `grpc`, you will need to use an older version of Node.

**Comment by Mitdd9707** [comment]
****Problem description****

[4/4] Building fresh packages...
error .../node_modules/grpc: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build --library=static_library

****Reproduction steps****

yarn install

****Environment****

OS name: mac
Node version: 14.3.0 

**anyone can help I can't install?**

**Comment by andersbo87** [comment]
On FreeBSD 12:
In file included from ../deps/grpc/third_party/cares/cares/ares__close_sockets.c:17:
In file included from ../deps/grpc/third_party/cares/cares/ares_setup.h:214:
../deps/grpc/third_party/cares/cares/setup_once.h:113:8: error: redefinition of 'timeval'
struct timeval {
       ^
/usr/include/sys/_timeval.h:49:8: note: previous definition is here
struct timeval {
       ^
In file included from ../deps/grpc/third_party/cares/cares/ares__close_sockets.c:17:
In file included from ../deps/grpc/third_party/cares/cares/ares_setup.h:214:
../deps/grpc/third_party/cares/cares/setup_once.h:178:3: error: unknown type name 'Error'
  Error Missing_definition_of_macro_sread
  ^
../deps/grpc/third_party/cares/cares/setup_once.h:178:42: error: expected ';' after top level declarator
  Error Missing_definition_of_macro_sread
                                         ^
                                         ;
In file included from ../deps/grpc/third_party/cares/cares/ares__close_sockets.c:20:
In file included from ../deps/grpc/third_party/cares/cares/ares_private.h:95:
../deps/grpc/third_party/cares/cares/ares_ipv6.h:25:8: error: redefinition of 'sockaddr_in6'
struct sockaddr_in6
       ^
/usr/include/netinet6/in6.h:125:8: note: previous definition is here
struct sockaddr_in6 {
       ^
In file included from ../deps/grpc/third_party/cares/cares/ares__close_sockets.c:20:
In file included from ../deps/grpc/third_party/cares/cares/ares_private.h:117:
../deps/grpc/third_party/cares/cares/ares_writev.h:26:8: error: redefinition of 'iovec'
struct iovec
       ^
/usr/include/sys/_iovec.h:45:8: note: previous definition is here
struct iovec {
       ^
1 warning and 5 errors generated.
gmake: *** [ares.target.mk:218: Release/obj.target/ares/deps/grpc/third_party/cares/cares/ares__close_sockets.o] Error 1
gmake: Leaving directory '/home/a-bol/ownCloud/Web/Udemy-kurs/angular6/animations/node_modules/grpc/build'
gyp ERR! build error 
gyp ERR! stack Error: `gmake` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System FreeBSD 12.1-RELEASE-p8
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=/home/a-bol/ownCloud/Web/Udemy-kurs/angular6/animations/node_modules/grpc/src/node/extension_binary/node-v83-freebsd-x64-unknown/grpc_node.node" "--module_name=grpc_node" "--module_path=/home/a-bol/ownCloud/Web/Udemy-kurs/angular6/animations/node_modules/grpc/src/node/extension_binary/node-v83-freebsd-x64-unknown" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v83"
gyp ERR! cwd /home/a-bol/ownCloud/Web/Udemy-kurs/angular6/animations/node_modules/grpc
gyp ERR! node -v v14.8.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/home/a-bol/ownCloud/Web/Udemy-kurs/angular6/animations/node_modules/grpc/src/node/extension_binary/node-v83-freebsd-x64-unknown/grpc_node.node --module_name=grpc_node --module_path=/home/a-bol/ownCloud/Web/Udemy-kurs/angular6/animations/node_modules/grpc/src/node/extension_binary/node-v83-freebsd-x64-unknown --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/a-bol/ownCloud/Web/Udemy-kurs/angular6/animations/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1051:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
node-pre-gyp ERR! System FreeBSD 12.1-RELEASE-p8
node-pre-gyp ERR! command "/usr/local/bin/node" "/home/a-bol/ownCloud/Web/Udemy-kurs/angular6/animations/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd /home/a-bol/ownCloud/Web/Udemy-kurs/angular6/animations/node_modules/grpc
node-pre-gyp ERR! node -v v14.8.0
node-pre-gyp ERR! node-pre-gyp -v v0.15.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/home/a-bol/ownCloud/Web/Udemy-kurs/angular6/animations/node_modules/grpc/src/node/extension_binary/node-v83-freebsd-x64-unknown/grpc_node.node --module_name=grpc_node --module_path=/home/a-bol/ownCloud/Web/Udemy-kurs/angular6/animations/node_modules/grpc/src/node/extension_binary/node-v83-freebsd-x64-unknown --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
npm WARN codelyzer@5.2.2 requires a peer of @angular/compiler@>=2.3.1 <10.0.0 || >9.0.0-beta <10.0.0 || >9.1.0-beta <10.0.0 || >9.2.0-beta <10.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN codelyzer@5.2.2 requires a peer of @angular/core@>=2.3.1 <10.0.0 || >9.0.0-beta <10.0.0 || >9.1.0-beta <10.0.0 || >9.2.0-beta <10.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN karma-jasmine-html-reporter@1.5.4 requires a peer of jasmine-core@>=3.5 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.24.3 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the grpc@1.24.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Steps to reproduce**
npm install

**Environment**
OS name and version: FreeBSD 12
Node version: 14.8.

**Comment by MohammedMahmoudAbdelKarim** [comment]
**_THE PROBLEM_**

`npm ERR! grpc@1.24.3 install: node-pre-gyp install --fallback-to-build --library=static_library
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grpc@1.24.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`
-----------------------------------------------------------------------------------------------------
**_REASONS_**

NodeJs Version in not supported with grpc Version.
-------------------------------------------------------------------------------------------------------
**_SOLUTION_**

Try to edit your package.json's grpc version to 1.24.3

**Comment by yashika-sharma** [comment]
I was having the same issue as the OP. Had to downgrade my node version to 12.13.0 ://

**Comment by sureshwoua93** [comment]
i have issue in firebase install( "firebase": "^6.6.2") in node js

grpc@1.23.3 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grpc@1.23.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by murgatroid99** [comment]
The `grpc` package is now deprecated. We recommend using `@grpc/grpc-js` instead.
