### ISSUE TITLE
@grpc/grpc-js: Closing Stream After Unary Call Triggers Double Free

### ISSUE THREAD

**Issue by moloch--** [grpc/grpc-node#1464]
### Problem description
Attempting to close the client's connections to a server after making a single unary call triggers a panic in Node (this may actually be a bug in Node, it's not clear to me).

### Reproduction steps

I have a client class that manages a couple gRPC streams (`_events` and `_tunnelStream`) that are open for the lifetime of the client class. The client also makes unary calls. After making any number of unary calls (1 or more), and attempting to disconnect with the function below triggers a double free what appears to be the NodeJS HTTP/2 library:

```
  async disconnect(): Promise<void> {
    if (this._events !== null) {
      this._events.on('error', () => {})
      this._events.cancel()
    }
    if (this._tunnelStream !== null) {
      this._tunnelStream.on('error', () => {})
      this._tunnelStream.cancel()
    }
    this.rpc.close()
  }
```

### Environment
 - MacOS / Ubuntu 20.04
 - Node version 14
 - Package name and version `@grpc/grpc-js ^1.0.3`

### Screenshots

<img width="1050" alt="Screen Shot 2020-06-07 at 10 59 01 AM" src="https://user-images.githubusercontent.com/875022/83973800-55792500-a8ae-11ea-91ea-03535f883276.png">

<img width="1380" alt="Screen Shot 2020-06-07 at 8 18 13 AM" src="https://user-images.githubusercontent.com/875022/83973810-69248b80-a8ae-11ea-8588-ef0db7c481a7.png">

**Comment by murgatroid99** [comment]
That is definitely a bug in Node itself. You have more information about how you triggered the bug and your environment, so you should file an issue in that repository (https://github.com/nodejs/node), and link to it from here. I suggest that when you do, you share the error information in the form of text so that it's easier to interact with.

**Comment by sangaman** [comment]
Is there any update on this? I think I've encountered the same issue, still trying to figure out how to deal with it.

**Comment by LePremierHomme** [comment]
Wrapping the `.cancel()` call with `setTimeout`/`setImmediate` seems to mitigate the error.

**Comment by mdouglass** [comment]
@murgatroid99 built a small repro case for this issue and opened a ticket against https://github.com/nodejs/node as suggested.

**Comment by bl-ue** [comment]
https://github.com/nodejs/node/issues/38964.  I'll investigate it.

**Comment by murgatroid99** [comment]
`grpc-js` definitely doesn't use any C/C++ modules. Avoiding them was the main reason the library was created.

**Comment by bl-ue** [comment]
Great, okay, it like it's definitely a bug in node core.  Track https://github.com/nodejs/node/issues/38964 for updates :)

**Comment by bl-ue** [comment]
Linking for reference 🎉 https://github.com/nodejs/node/pull/39076 — thank you @mdouglass!!

**Comment by murgatroid99** [comment]
This is a Node bug and it appears to have been fixed in Node.
