### ISSUE TITLE
1 CANCELLED: Received RST_STREAM with error code 8

### ISSUE THREAD

**Issue by RobertDittmann** [grpc/grpc-node#1471]
### Problem description
On production we use grpc to communicate between microservices. Most of them are written in Nodejs and some in Java. Once a while for random Nodejs services we do see errors like:
`1 CANCELLED: Received RST_STREAM with error code 8`

Each service has queue with defined size and process requests one by one. Sometimes we do send cancelled from client when request deadline is exceeded, but this is handled.

### Reproduction steps
It is rare/random so do not have yet easy steps to reproduce than calling service. 

### Environment
 - OS name, version and architecture: [Docker with node:12.16.2-alpine]
 - Node version [12.16.2]
 - Node installation method [docker container FROM node:12.16.2-alpine]
 - Package name and version [grpc ^1.24.2]

### Additional context
If you know what could be the root cause to even try to reproduce I will be glad. 

Kind regards,
Robert Dittmann

**Comment by murgatroid99** [comment]
That error just means that the request was cancelled, probably by the server. It's hard to tell what specifically might cause that.

**Comment by RobertDittmann** [comment]
I will close it for now.
