### ISSUE TITLE
@grpc/grpc-js: Data loss on server-side streaming call (and a possible solution)

### ISSUE THREAD

**Issue by zeodtr** [grpc/grpc-node#1473]
### Problem description
(This bug applies to @grpc/grpc-js.  C-based npm grpc does not have this problem.)
If a server-side streaming call that produces a lot of messages is pipelined with a slow write stream (for example, file write stream), a few of last messages can be lost.

### Reproduction steps
1. Unzip attached `TestGrpc.zip`.
2. run `npm install`
3. run `node TestGrpcServer.js` on one command window.
4. run `node TestGrpcClient.js` on the other command window.
5. On the client command window, `Total written lines: 100000` should be shown. If the number is lower than 100000, it's the bug this issue describes.

And here is the location and the cause of the bug I found:

The source file that has the bug is call-stream.ts.  
The buggy functions are `maybeOutputStatus()` (line 268), `push()` (line 285) and `startRead()` (line 635).  
The problem is, when a `push()` waits on `process.nextTick()`, other `push()`s are additionally called and call `process.nextTick()`, thus build a 'push queue' on the Node.js event queue. And when one of the `push()`s causes `this.outputStatus()` while others are on the 'push queue', the other `push()`s are skipped since `this.statusOutput` is already set (by previous `push()`). Though `push()` has `this.canPush` guard, it is set to true by `startRead()` which calls `this.push()` when `this.unpushedReadMessages.length > 0`.

And here is a possible solution to fix the bug:

I modified `call-stream.js` to fix the bug. (Currently I have no npm development environment, so I just modified the JavaScript file instead of the TypeScript file. The modified `call-stream.js` file is included in the attached `TestGrpc.zip` file. Search for `IWFIX` string in the file. It's the locations I modified. Most importantly, I introduced a member property named `numNextTickPushes` to guard 'queued' pushes. I don't know whether it's the best fix since I don't know much of the source code. But anyway it seems to fix the bug.

### Environment
 - OS: Windows 10 x64 (real machine), Linux CentOS 7.7 x64 (VirtualBox)
 - Node version: 12.18.0 (Windows 10, CentOS), 10.21.0 (Windows 10)
 - Node installation method: nvm (Windows 10), download & tar xvfz (CentOS)
 - If applicable, compiler version: not applicable
 - Package name and version: @grpc/grpc-js 1.0.5

### Additional context
Attachment: [TestGrpc.zip](https://github.com/grpc/grpc-node/files/4769104/TestGrpc.zip)

**Comment by murgatroid99** [comment]
Thank you for digging into this. I think the root issue here is actually in a different place. The code you were looking at in `call-stream.js` is written with the assumption that there would only be one pending push at a time, or in other words that the next `startRead` would not be called until after `listener.onReceiveMessage` is called. If there are multiple pending `process.nextTick` events from `push`, that implies that that assumption was violated.

I think that assumption is being violated by the combination of [this line](https://github.com/grpc/grpc-node/blob/master/packages/grpc-js/src/call.ts#L116) and [this line](https://github.com/grpc/grpc-node/blob/master/packages/grpc-js/src/client.ts#L562). Whenever `listener.onReceiveMessage` is called, that ends up triggering both of those, so `startRead` is called twice. I think the second one is the one that should be removed.

**Comment by zeodtr** [comment]
@murgatroid99  I'm not sure about the code, but I suspect that both of the lines you mentioned are actually necessary.

About the first line: The `_read` function that calls the first `startRead` you mentioned is called by the Node.js streaming system when the 'downstream' stream has become able to receive more chunks again (after returning false from the previous push()). So, the gRPC stream must call `startRead` to begin push chunks again.

About the second line: The second `startRead` is necessary since the gRPC stream has paused itself (so I remember, maybe [this line (call-stream.ts line 318)](https://github.com/grpc/grpc-node/blob/f4cbe025f54330daf40e9b2c3cbab496627daa3c/packages/grpc-js/src/call-stream.ts#L318) before it pushed a chunk. But since the 'downstream' stream told that it can still receive more chunks by returning true from push(), the gRPC stream must resume itself to push more chunks - by calling `startRead`.

Maybe I'm wrong.

**Comment by zeodtr** [comment]
@murgatroid99 I've read the Node.js manual about the readable._read() function.

It says: 'Once the readable._read() method has been called, it will not be called again until more data is pushed through the readable.push() method'.

The above sentence can be interpreted that `readable._read()` can be called even when the downstream stream returns `true` from push() (really?). So, I think that 'the first line' you told is still necessary for the false returning case from push(), but a guard variable should be introduced to skip calling `startRead` when the downstream stream had returned true from push(), since in that case, 'the second line' has called `startRead` already.

That's just my thought.

**Comment by zeodtr** [comment]
@murgatroid99 If `readable._read()` is called 'everytime' by Node.js streaming system after `push()` is called, the second `startRead()` can be removed. But I think that the Node.js manual does not guarantee this. ([manual link](https://nodejs.org/api/stream.html#stream_readable_read_size_1))
 
So, I think it is safer (or, neccessary) to keep two `startRead()`s and introduce some guard logic to keep the assumption you told valid.

**Comment by murgatroid99** [comment]
I think you're right. The previous paragraph of the documentation says "_read() should continue reading from the resource and pushing data until readable.push() returns false". But then `_read` shouldn't be called again while one is still working. I will have to dig in more to understand what is actually happening here.

**Comment by murgatroid99** [comment]
It looks like the documentation is misleading at best. According to my tests, `_read` does get called after every `push`, no matter what `push` returns. Removing the `startRead` call in `onReceiveMessage` appears to fix the problem.

**Comment by zeodtr** [comment]
@murgatroid99 I'm somewhat worried, since the behavior (=  `_read` get called after every `push`) is not official (since the document does not guarantee it), the behavior can change without notice on the next Node.js version (or, on a different environment, or when piping to a different stream, etc.). Relying on the undocumented behavior can be dangerous.

**Comment by zeodtr** [comment]
@murgatroid99 I've read the counting stream example code on the Node.js stream document ([link](https://nodejs.org/dist/latest-v12.x/docs/api/stream.html#stream_an_example_counting_stream)).

It does assume that `_read` is get called after every `push`. So, now I think it's safe to assume that.

It seems that Node.js document suggests 2 strategies for a read stream implementation.
1. Stop when `push` returns false, resume when `_read` is called after that. ([SourceWrapper sample](https://nodejs.org/dist/latest-v12.x/docs/api/stream.html#stream_readable_push_chunk_encoding))
2. Call `push` on each `_read` while ignoring the return value of `push`. (the counting example above)

I think your correction will set the implementation of gRPC read stream to correctly follow the strategy 2. (But, is it more natural to follow the strategy 1 rather than repeatedly pausing and resuming the underlying read stream on each `_read`? But maybe this is an another topic.)

**Comment by murgatroid99** [comment]
It's useful for the `Http2CallStream` to have only one read pending at a time. So if I switch to strategy 1, it would be at a higher level, which means that we would still be pausing and resuming the underlying stream. The turnaround time wouldn't even be significantly better, because `push` calls `_read` in a `process.nextTick` call.

So, I think it's worth using the simple solution of "do one read when `_read` is called".

**Comment by murgatroid99** [comment]
That fix is out in version 1.1.0.
