### ISSUE TITLE
electron-rebuild grpc@1.24.3 failed with electron9.0.4

### ISSUE THREAD

**Issue by Randyshu2018** [grpc/grpc-node#1480]
### Problem description
electron-rebuild grpc@1.24.3 failed with electron9.0.4
### Environment
 - OS name, version and architecture: Darwin
 - Node version : v10.15.3
 - Node installation method :nvm
 - Package name and version grpc@1.24.3
### Additional context
![image](https://user-images.githubusercontent.com/19544447/84888823-791c4680-b0ca-11ea-87d0-1c58fc5ff6ec.png)

**Comment by murgatroid99** [comment]
We do not recommend using electron-rebuild with grpc. We do recommend using the precompiled binary files that we distribute. Once you have grpc installed, you can get the Electron 9 binary for your platform by running

```
npm rebuild grpc --target=9.0.0 --runtime=electron
```

**Comment by Randyshu2018** [comment]
> We do not recommend using electron-rebuild with grpc. We do recommend using the precompiled binary files that we distribute. Once you have grpc installed, you can get the Electron 9 binary for your platform by running
> 
> ```
> npm rebuild grpc --target=9.0.0 --runtime=electron
> ```

now everything is ok...
