### ISSUE TITLE
constants.methodTypes missing from @grpc/grpc-js

### ISSUE THREAD

**Issue by jncr** [grpc/grpc-node#1495]
### Problem description
[constants.methodTypes](https://github.com/grpc/grpc-node/blob/grpc%401.24.x/packages/grpc-native-core/src/constants.js#L246) is not available from typescript

### Reproduction steps
https://repl.it/repls/StarryExcitableTitle#index.ts:
```
import * as grpc from 'grpc'
console.log(grpc.methodTypes.UNARY)
>  Property 'methodTypes' does not exist on type 'typeof import("grpc")'
```
https://repl.it/repls/DangerousFruitfulEditor#index.js:
```
const grpc = require('grpc');
console.log(grpc.methodTypes.UNARY);
> 0
```

### Environment
 - Mac OS Catalina 10.15.5
 - Node version `12.18.0`
 - Node installation method [e.g. nvm]: `n`
 - If applicable, compiler version [e.g. clang 3.8.0-2ubuntu4] `tsc 3.9.6`
 - Package name and version [e.g. gRPC@1.12.0] grpc@1.24.3

### Additional context
the `methodTypes` enum is not in the enum section of grpc-native-core/index.d.ts, or in grpc-js/src/constants.js
can work around with `import * as constants from 'grpc/src/constants'` but that's fragile

**Comment by murgatroid99** [comment]
The fix for this has been published in version 1.24.4.
