### ISSUE TITLE
Logging/Intercepting Features in grpc-node?

### ISSUE THREAD

**Issue by Rchan0100** [grpc/grpc-node#1501]
I'm just curious whether or not there is a logging/intercepting feature in grpc-node? I'm trying to trace grpc proto requests with a grpc-node client and server. It seems like a lot of middleware logging features support grpc-go.

Hopefully there's one for node!!

**Comment by DmitrySergeyev** [comment]
Server side middleware implementation in `grpc-node` would be very useful, e.g. for logging or collect prometheus statistics.

**Comment by grissius** [comment]
@DmitrySergeyev  This feature is provided by higher-abstraction frameworks like [Mali](https://mali.js.org/) and [ProtoCat](https://grissius.github.io/protocat/).

**Comment by murgatroid99** [comment]
Server-side interceptors are now supported in `@grpc/grpc-js` version 1.10.x. [This proposal](https://github.com/grpc/proposal/blob/master/L112-node-server-interceptors.md) describes the feature in detail.
