### ISSUE TITLE
Sporadic cur != GRPC_CHANNEL_SHUTDOWN crashes the node process

### ISSUE THREAD

**Issue by felipegcampos** [grpc/grpc-node#1503]
### Problem description
The company I work in has multiple services and uses node grpc implementation to communicate amongst them. We are currently experiencing sporadically `E0714 23:39:13.907064150      18 connectivity_state.cc:154]  assertion failed: cur != GRPC_CHANNEL_SHUTDOWN` errors that shut down the service completely. The `GRPC_CHANNEL_SHUTDOWN` errors are usually preceded ( not always ) by other errors in the service such as Postgres statement timeouts and elastic search errors. However, these are not unhandled errors and it should definitely not shut down the service. It also looks to be happening with one of the services that usually handle more data compared to the others.

### Reproduction steps
You can use the code in the repo [here](https://github.com/felipegcampos/grpc_node_1503) to reproduce the problem. It also describes the steps to reproduce.

### Environment
 - OS name, version and architecture: Alpine Linux v3.11 docker running on Amazon Linux 2 x86_64
 - Node version: v12.16.0
 - Node installation method: docker
 - Package name and version: "grpc": "1.22.2" and "@grpc/grpc-js": "0.7.0"

### Additional context
* We are using Workers but the grpc server is created in the main thread.

* Server Options:
```
{
        'grpc.max_send_message_length': 104857600,
        'grpc.max_receive_message_length': 104857600,
        'grpc.max_connection_idle_ms': 15000,
        'grpc.max_connection_age_ms': 30000,
        'grpc.keepalive_time_ms': 5000,
        'grpc.keepalive_timeout_ms': 1000,
        'grpc.keepalive_permit_without_calls': 1,
        // Allow grpc pings from client without data. 
        // It must be 0 with Workers otherwise it throws RESOURCE_EXHAUSTED.
        'grpc.http2.min_ping_interval_without_data_ms': 0
    }
```

* Client Options:
```
{
        'grpc.max_send_message_length': 104857600,
        'grpc.max_receive_message_length': 104857600,
        'grpc.keepalive_time_ms': 5000,
        'grpc.keepalive_timeout_ms': 1000,
        'grpc.keepalive_permit_without_calls': 1
    }
```

* Error:
```
Jul 15 09:10:37 ca-cqoexb data-service-be460c54df5d E0715 13:10:37.418067384      17 connectivity_state.cc:154]  assertion failed: cur != GRPC_CHANNEL_SHUTDOWN
Jul 15 09:10:37 ca-cqoexb data-service-be460c54df5d Aborted
```

**[UPDATE]**

I found that grpc core removed the assertion from `connectivity_state.cc:154` that is causing the issue. However, it has been released in version 1.25. Here is the [link](https://github.com/grpc/grpc/pull/20255/files#diff-e2a14ef4a21894ba91da09db222ec5e1L154) to the PR that removed the line and the explanation of the changes. Is there any ETA to release version 1.25 of grpc-node and if not what is the best option for us supposing it will fix the problem?

**[UPDATE 2]**
I was able to reproduce and update the **Reproduction steps** section. Please, note that removing max-age will cause `RST_STREAM`s if working with NLB.

**Comment by murgatroid99** [comment]
The Node `grpc` library will not be picking up version 1.25 or later of the C core library because we are in the process of deprecating that Node library. I can try backporting the PR you linked to 1.24, but it looks fairly complex, so there's a possibility that it won't integrate cleanly.

This looks like it's the same issue as grpc/grpc#21327, so you can probably work around this problem by removing `grpc.max_connection_age_ms` from the options list.

You may want to start migrating to `@grpc/grpc-js` to get ahead of the planned deprecation `grpc`. `@grpc/grpc-js` will be the main supported implementation going forward. I will note that it does not yet implement all of the listed client and server options.

**Comment by felipegcampos** [comment]
Thank you for getting back @murgatroid99 .
What are the options currently unavailable in `@grpc/grpc-js` or where I can check the options available?
The problem of removing `grpc.max_connection_age_ms` is that we use NLB and we want to balance connections to different containers and instances.

**Comment by murgatroid99** [comment]
The list of supported options can be found here: https://github.com/grpc/grpc-node/blob/master/PACKAGE-COMPARISON.md.

**Comment by felipegcampos** [comment]
@murgatroid99 I was finally able to reproduce and updated the description. You might have some insights looking at the code. 🤞 

Note that removing max-age is causing RST_STREAMS if working with NLB.

**Comment by murgatroid99** [comment]
In general, retry safety depends less on the specific error code you're getting, and more on the semantics of the method that you are calling. For sporadic, connection-based error codes like this, there are no guarantees about what information the server has seen and processed.

Also, which `RST_STREAM` errors are you getting?

**Comment by felipegcampos** [comment]
> In general, retry safety depends less on the specific error code you're getting, and more on the semantics of the method that you are calling. For sporadic, connection-based error codes like this, there are no guarantees about what information the server has seen and processed.
> 
> Also, which `RST_STREAM` errors are you getting?

[error] message: 13 INTERNAL: Received RST_STREAM with code 2, stack: Error: 13 INTERNAL: Received RST_STREAM with code 2

**Comment by murgatroid99** [comment]
OK, code 2 just means "Internal server error", so you can't really infer anything from that one way or the other.

**Comment by felipegcampos** [comment]
Yes, so I assume retrying the requests is not ideal. Is there any progress on the backporting work? Do you think it's feasible? Is there anything I can do to help? We have this problem in production and I'm not sure how to fix it without having to remove pieces or moving to a job polling approach that would require some time. Unfortunately, we are running out of time right now. 😢

**Comment by murgatroid99** [comment]
See https://github.com/grpc/grpc/pull/23497 for the current state of the backport. I think it's going well.

Still, I want to emphasize again that development on the `grpc` library is limited, and fixes for other bugs may not be feasible to backport. I would encourage you to try out the `@grpc/grpc-js` library, and if you find that one of the unimplemented options is necessary for your system to work correctly, file a separate issue with that information to help us keep track of it.

**Comment by murgatroid99** [comment]
The `grpc` package is now deprecated, so this change will likely not happen. We recommend switching to `@grpc/grpc-js`.
