### ISSUE TITLE
Type signature of sendUnaryData is not precice enough

### ISSUE THREAD

**Issue by xylix** [grpc/grpc-node#1516]
### Problem description
The signature of sendUnaryData doesn't contain type info for the fact that in cases where error is set, it never returns. So our code base has patterns like this:

```
try {
    const value = functionThatMightError();
    return value;
    } catch (e) {
        callback(e, null);
    }
    // This is purely to appease Typescript compiler, code is never executed since the
    // `callback` breaks the execution.
    throw "Never executed";
```
### Suggested solution
Editing my local type definitions to look like this 
```
  /**
   * Callback function passed to server handlers that handle methods with
   * unary responses.
   */
  type sendUnaryData<ResponseType> = { 
    (error: null, value: ResponseType , trailer?: Metadata, flags?: number): void;
    (error: ServiceError, value: ResponseType | null, trailer?: Metadata, flags?: number): never;
  }
```
If this type signature is actually true, then I would suggest upstream would also update theirs to one that actually has the never in it.

I might also be misunderstanding how sending errors through the protocol works, and if that is the case please instruct me on how to use them correctly.

**Comment by murgatroid99** [comment]
How did you conclude that `sendUnaryData` would never return if you pass an error? That is not the intended behavior and I can't find anything that would cause that behavior.

**Comment by xylix** [comment]
I think we misinterpreted some behaviour. Thanks for the clarification and sorry for my slow response.
