### ISSUE TITLE
How can I can test the server is avalible or not?

### ISSUE THREAD

**Issue by Sunnykaby** [grpc/grpc-node#152]
Does Client have any methods to detect the rpc server is reachable or not? Before a invoke a rpc call.

**Comment by murgatroid99** [comment]
Strictly speaking, the gRPC library never considers a server to be unreachable. Either the client has connected to the server, or has not yet connected to the server. One thing you can check is whether the client can connect to a server within a specified period of time, using the `Client#waitForReady` method (see [documentation](https://grpc.io/grpc/node/grpc.Client.html)). If the client connects, you will get a callback without an error, and if it doesn't connect before the deadline passes, you will get a callback with an error.

**Comment by nicolasnoble** [comment]
I think we can consider this one answered. Closing.
