### ISSUE TITLE
Electron: Loading non-context-aware native module in renderer; This is deprecated...

### ISSUE THREAD

**Issue by pattrickrice** [grpc/grpc-node#1527]
### Is your feature request related to a problem? Please describe.

Current Electron release (v9) emits a deprecation warning. v11 will disable the ability to import without context-awareness
```
(node:86166) Electron: Loading non-context-aware native module in renderer: '<my-project>/node_modules/grpc/src/node/extension_binary/electron-v9.0-darwin-x64-unknown/grpc_node.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.
```

### Describe the solution you'd like
[Support for electron v9+](https://github.com/electron/electron/issues/18397)

### Describe alternatives you've considered
No alternatives, maybe not using grpc-node?

### Additional context
n/a

**Comment by murgatroid99** [comment]
I believe this is the same root issue as in #778. This is blocked by nodejs/nan#844, which I filed over a year ago. There has been no recent maintainer activity on that issue so I don't expect it to happen any time soon.

I suggest switching to `@grpc/grpc-js`, which is the primary gRPC implementation that we will be supporting going forward. That library does not use a native module, so it will not be impacted by this issue.

**Comment by murgatroid99** [comment]
At this point, the `grpc` module has been deprecated for a couple of years, with `@grpc/grpc-js` as the recommended replacement. We have no plans to update the `grpc` module to fix this problem.
