### ISSUE TITLE
Server pipes error to Client instead of printing it locally

### ISSUE THREAD

**Issue by dwjft** [grpc/grpc-node#153]
It is my understanding that when a gRPC server sends back an object, if there are extra fields not defined in the `.proto` file, they will get dropped on deserialization and ignored in the client.

Instead, the client throws an error:

```
#test is not a field: undefined

at ClientReadableStream._emitStatusIfDone (/node_modules/grpc/src/client.js:255:19)
at ClientReadableStream._receiveStatus (node_modules/grpc/src/client.js:233:8)
at node_modules/grpc/src/client.js:705:12
```

Example `.proto` file:

```
message Test {
  string id = 1;
}
```

Example server write:
```javascript
call.write({ id: 'test id', test: 'test field' });
```

If the client consumes the example `.proto` definition, it will throw the above error when the server attempts to write the `test` field.

It seems the server is sending the error to the client instead of erroring locally.

**Comment by murgatroid99** [comment]
I think what's actually happening here is that protobuf serialization on the server side is failing, which is causing the request to fail and sending the error to the client. So, you should be fine as long as the client and server each use the fields available in the local proto file.

**Comment by dwjft** [comment]
Wow, you are absolutely correct. Thank you.

It's odd that the server pipes the error to the client instead of logging it locally; definitely a red herring.

**Comment by nicolasnoble** [comment]
Closing this one.
