### ISSUE TITLE
@grpc/proto-loader & protobufjs JSON format

### ISSUE THREAD

**Issue by hugebdu** [grpc/grpc-node#1535]
### Is your feature request related to a problem? Please describe.
Any chance to export & make public the [`createPackageDefinition`](https://github.com/grpc/grpc-node/blob/master/packages/proto-loader/src/index.ts#L272)?
We have a use case where our build system crunches multiple protobuf APIs (as `*.proto` files) into a single JSON file using the [`protobufjs#toJSON`](https://github.com/protobufjs/protobuf.js/blob/master/index.d.ts#L195) and then at runtime we load it using the [`grpc#loadObject`](https://github.com/grpc/grpc-node/blob/grpc%401.25.x/packages/grpc-native-core/index.d.ts#L69).

**Comment by murgatroid99** [comment]
You can probably already load those JSON files using `load` or `loadSync` in the `@grpc/proto-loader` library. The arguments to those functions are passed directly to Protobuf.js, so they can load whatever Protobuf.js can load.

We are not going to make `createPackageDefinition` public. One of the goals of the `@grpc/proto-loader` library is to avoid directly exposing Protobuf.js types and APIs.

**Comment by hugebdu** [comment]
indeed, loading JSON instead of proto did work.

thanks!
