### ISSUE TITLE
@grpc/grpc-js & client call cancellation upon deadline

### ISSUE THREAD

**Issue by hugebdu** [grpc/grpc-node#1542]
### Problem description
Could that be grpc-js behaves differently from native grpc in terms of client side call cancellation upon deadline?

Looks like grpc-js's client does not cancel a call if the deadline has reached while the native client does.

See attached repo for reproduction.

Thanks

### Reproduction steps
https://github.com/hugebdu/grpc-js-client-cancellation

**Comment by murgatroid99** [comment]
The issue there is the `parent: call` option, which does deadline and cancellation propagation. That feature is not implemented in `@grpc/grpc-js`, but the option is there for type compatibility between the libraries.

**Comment by hugebdu** [comment]
@murgatroid99 thanks.
is it in your backlog or design decision is not to implement?

**Comment by murgatroid99** [comment]
We prioritized features that we knew people were using, and until you filed this issue, I was not aware that anyone was using that feature. Now we can plan to implement it.

**Comment by hugebdu** [comment]
IMO for SOA those propagations are more than nice to have :)

**Comment by murgatroid99** [comment]
This is now implemented in version 1.2.0

**Comment by hugebdu** [comment]
You're the best!

Thanks a lot
