### ISSUE TITLE
Mutation of Default Response Headers

### ISSUE THREAD

**Issue by richardpringle** [grpc/grpc-node#1549]
### Problem description
A clear and concise description of what the problem is.

The response headers global is being mutated on every request.

### Reproduction steps
It will be clear what the issue is when you see the code: https://github.com/grpc/grpc-node/pull/1548/files

### Environment
 - OS name, version and architecture: all
 - Node version all
 - Node installation method: N/A
 - If applicable, compiler version: N/A 
 - Package name and version: >= grpc-js 1.03 (possibly older versions too... this fix should definitely be back-ported)

### Additional context
This is definitely a possible attack vector

**Comment by murgatroid99** [comment]
The linked fix for this has been published in version 1.1.4 and above.
