### ISSUE TITLE
deprecate dns.lookup() or a way to add custom DNS Resolver?

### ISSUE THREAD

**Issue by civilizeddev** [grpc/grpc-node#1554]
### Is your feature request related to a problem? Please describe.

I'm using AWS Lambda, Route53(DNS), CloudMap(Service Discovery) for my service.

I want a grpc-js client in a lambda function to find a target grpc-js server by querying DNS, with A record or SRV.

But it is not working with `dns.lookup()`.

https://github.com/grpc/grpc-node/blob/2111c0ffa9d5aaef51b0d9a12a75e73bab5cbd93/packages/grpc-js/src/resolver-dns.ts#L48

And I found this article:

> dns.lookup() does not necessarily have anything to do with the DNS protocol. The implementation uses an operating system facility that can associate names with addresses, and vice versa. This implementation can have subtle but important consequences on the behavior of any Node.js program. Please take some time to consult [the Implementation considerations section](https://nodejs.org/api/dns.html#dns_implementation_considerations
) before using dns.lookup().

So I monkey-patched the target js file to use `dns.resolve4()` for A record resolution, instead of `dns.lookup()`

```diff
From 5c9e75ccf15a9806cdf75a157e4b7793ed77273d Mon Sep 17 00:00:00 2001
From: Hyeonsoo Lee <hyeonsoo.david.lee@gmail.com>
Date: Tue, 18 Aug 2020 16:18:19 +0900
Subject: [PATCH] =?UTF-8?q?chore(crane-distributor-api):=20grpc-js=20DNS?=
 =?UTF-8?q?=20Resolver=20=EB=AA=BD=ED=82=A4=ED=8C=A8=EC=B9=AD?=
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit

---
 packages/my-client/generated/index.js | 8 +++-----
 1 file changed, 3 insertions(+), 5 deletions(-)

diff --git a/packages/my-client/generated/index.js b/packages/my-client/generated/index.js
index 3b2b874..a1c9455 100644
--- a/packages/my-client/generated/index.js
+++ b/packages/my-client/generated/index.js
@@ -5937,7 +5937,7 @@ function trace(text) {
  */
 const DEFAULT_PORT = 443;
 const resolveTxtPromise = util.promisify(dns.resolveTxt);
-const dnsLookupPromise = util.promisify(dns.lookup);
+const dnsLookupPromise = util.promisify(dns.resolve4);
 /**
  * Merge any number of arrays into a single alternating array
  * @param arrays
@@ -6032,12 +6032,10 @@ class DnsResolver {
              * because when looking up a single family, dns.lookup outputs an error
              * if the name exists but there are no records for that family, and that
              * error is indistinguishable from other kinds of errors */
-            this.pendingLookupPromise = dnsLookupPromise(hostname, { all: true });
+            this.pendingLookupPromise = dnsLookupPromise(hostname);
             this.pendingLookupPromise.then((addressList) => {
                 this.pendingLookupPromise = null;
-                const ip4Addresses = addressList.filter((addr) => addr.family === 4);
-                const ip6Addresses = addressList.filter((addr) => addr.family === 6);
-                this.latestLookupResult = mergeArrays(ip6Addresses, ip4Addresses).map((addr) => ({ host: addr.address, port: +this.port }));
+                this.latestLookupResult = addressList.map((addr) => ({ host: addr, port: +this.port }));
                 const allAddressesString = '[' +
                     this.latestLookupResult
                         .map((addr) => addr.host + ':' + addr.port)
-- 
2.24.3 (Apple Git-128)
```

It's ugly, isn't it?

### Describe the solution you'd like

> I'm not sure what is the best.
> Maybe one of these:

1. replace `dns.lookup()` with `dns.resolve()`
1. provide a way to add custom `DnsResolver`
1. another solution?

### Describe alternatives you've considered

- More documentation
- Let me know what I could help with.

### Additional context

- Node.js: 14.8.0
- OS: macOS Catalina
- grpc-js: 1.1.5

**Comment by civilizeddev** [comment]
Some says `dns.lookup()` is harmful.

> https://github.com/LCMApps/dns-lookup-cache

**Comment by civilizeddev** [comment]
I found `dns.lookup()` failed with some domain name just like `abc.internal`, `abc.zz` (with unregistered TLDs).

It forces me to use registered TLD in domain name.

**Comment by civilizeddev** [comment]
`abc.zzz` works.

**Comment by murgatroid99** [comment]
It's not clear to me why `dns.lookup()` would have a problem with unregistered TLDs. Under the hood it's just calling `getaddrinfo`, and I can't find any information about that having problems with unregistered TLDs. As you quoted in your first comment, "The implementation uses an operating system facility that can associate names with addresses, and vice versa". The linked implementation considerations section goes on to say "For instance, `dns.lookup()` will almost always resolve a given name the same way as the `ping` command." Can you `ping` the target server?

In addition, your source for "`dns.lookup()` is harmful" does not say that it is harmful in any way that is relevant to this problem. They refer back to that same "implementation considerations" section, which talks about the potential problems with thread pool usage. grpc-js makes relatively infrequent lookups so I don't expect that to be a significant problem here.

**Comment by civilizeddev** [comment]
> https://en.wikipedia.org/wiki/Top-level_domain#Reserved_domains

> Any such reserved usage of those TLDs should not occur in production networks that utilize the global domain name system:

- localhost
- test
- example
- (maybe) internal
- zz

**Comment by civilizeddev** [comment]
And I also found that `dns.lookup()` doesn't work with dns name that contains `_`.

## Not working

```
service-a._tcp.internal
service-b._tcp.zzz
```

## Working

```
serviceb.tcp.zzz
```

**Comment by murgatroid99** [comment]
That Wikipedia article says that those TLDs should not be used. That is not helping to convince me that we should make a change to support the use of those TLDs.

The `resolve` functions have their own tradeoffs. Specifically, they do not read `hosts` files or other sources of hostname to IP address mappings.

And an underscore character is not a valid character in a hostname, so it is expected behavior that you would not be able to use one.

**Comment by civilizeddev** [comment]
- https://stackoverflow.com/questions/2180465/can-domain-name-subdomains-have-an-underscore-in-it
- https://tamas.dev/aws/ecs/haproxy/nginx/certbot/microservices/containers/route53/dns/srv/2019/10/18/run-your-ecs-cluster-with-service-discovery-and-haproxy-for-8-a-month.html

DNS record name that contains `_` is commonly used in service discovery using DNS.

(And what about CNAME, SRV records? Do you have plan to support them?)

Yes, it's okay to preserve the current behavior. (I changed my dns records all yesterday 😄)

Wouldn't it be better to provide a way to customize the dns resolver then?

**Comment by murgatroid99** [comment]
My understanding is that CNAME records should be automatically handled by the underlying DNS resolver, such as the ones used by `dns.lookup` and `dns.resolve*`. Regarding SRV records, as far as I know gRPC in general only officially uses SRV records to implement the [grpclb system](https://github.com/grpc/proposal/blob/master/A5-grpclb-in-dns.md), which we have chosen not to implement in grpc-js. There is nothing else there that we would officially support that I know of.

You are not the first person to ask about a custom resolver and I am sympathetic to that, but the current resolver API was not designed to be part of the public API and we would need to go through an API design and review process to change that.

**Comment by civilizeddev** [comment]
I'll be waiting.
