### ISSUE TITLE
Cross-OS build does not work with python 3 in system 

### ISSUE THREAD

**Issue by strowk** [grpc/grpc-node#1564]
### Problem description

I have Windows 10 and python 3 installed. Building for Windows and Darwin work fine, but I need to build grpc package for linux too (for electron runtime). 

So I'm running following command 
```
npm rebuild grpc --runtime=electron --target=7.3.3 --target_platform=linux
```

And it gives error ouput, where I see that:
```
gyp ERR! stack Error: Command failed: C:\Users\myuser\AppData\Local\Programs\Python\Python36\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
```

So the way I undertand this is that somehwere in build process it's assumed that python 2 is installed in system, but it is no longer supported as of this year, so this is a bug. 

### Reproduction steps

1. install python 3 in Windows 10, remove python 2 from system if was installed
2. install grpc package
3. try to build for linux: `npm rebuild grpc --runtime=electron --target=7.3.3 --target_platform=linux`
4. failed because build trying to use old python version

### Environment
 - OS name, version and architecture:  Windows 10 amd64
 - Node version: v11.10.1
 - Node installation method: msi
 - Package name and version: `"grpc": "^1.24.3"`

**Comment by murgatroid99** [comment]
I don't believe we ever explicitly invoke python. This is most likely coming from `node-gyp`, which is generally installed automatically along with `npm`. If you update to a newer version of `npm`, that may fix this.

Alternatively, if you follow [our instructions for installing `grpc` for Electron}(https://www.npmjs.com/package/grpc#about-electron), you should be able to bypass the python invocation entirely.

**Comment by andria21** [comment]
error C:\Users\andria\Desktop\graphql-lesson-master\node_modules\grpc: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build --library=static_library
Arguments:
Directory: C:\Users\andria\Desktop\graphql-lesson-master\node_modules\grpc
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.13.0
node-pre-gyp info using node@16.13.0 | win32 | x64
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp info check checked for "C:\Users\andria\Desktop\graphql-lesson-master\node_modules\grpc\src\node\extension_binary\node-v93-win32-x64-unknown\grpc_node.node" (not found)
node-pre-gyp http GET https://node-precompiled-binaries.grpc.io/grpc/v1.20.3/node-v93-win32-x64-unknown.tar.gz
node-pre-gyp http 404 https://node-precompiled-binaries.grpc.io/grpc/v1.20.3/node-v93-win32-x64-unknown.tar.gz
node-pre-gyp WARN Tried to download(404): https://node-precompiled-binaries.grpc.io/grpc/v1.20.3/node-v93-win32-x64-unknown.tar.gz      
node-pre-gyp WARN Pre-built binaries not found for grpc@1.20.3 and node@16.13.0 (node-v93 ABI, unknown) (falling back to source compile 
with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://node-precompiled-binaries.grpc.io/grpc/v1.20.3/node-v93-win32-x64-unknown.tar.gz
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@16.13.0 | win32 | x64
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@16.13.0 | win32 | x64
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Python310\python.exe -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gyp ERR! stack SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (node:child_process:397:12)
gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
gyp ERR! stack     at maybeClose (node:internal/child_process:1064:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\andria\\Desktop\\graphql-lesson-master\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--library=static_library" "--module=C:\\Users\\andria\\Desktop\\graphql-lesson-master\\node_modules\\grpc\\src\\node\\extension_binary\\node-v93-win32-x64-unknown\\grpc_node.node" "--module_name=grpc_node" "--module_path=C:\\Users\\andria\\Desktop\\graphql-lesson-master\\node_modules\\grpc\\src\\node\\extension_binary\\node-v93-win32-x64-unknown" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v93" "--python=C:\\Python310\\python.exe" "--msvs_version=2017"
gyp ERR! cwd C:\Users\andria\Desktop\graphql-lesson-master\node_modules\grpc
gyp ERR! node -v v16.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\andria\Desktop\graphql-lesson-master\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --library=static_library --module=C:\Users\andria\Desktop\graphql-lesson-master\node_modules\grpc\src\node\extension_binary\node-v93-win32-x64-unknown\grpc_node.node --module_name=grpc_node --module_path=C:\Users\andria\Desktop\graphql-lesson-master\node_modules\grpc\src\node\extension_binary\node-v93-win32-x64-unknown --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93 --python=C:\Python310\python.exe --msvs_version=2017' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\andria\Desktop\graphql-lesson-master\node_modules\grpc\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1064:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
node-pre-gyp ERR! System Windows_NT 10.0.19042
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\andria\\Desktop\\graphql-lesson-master\\node_modules\\grpc\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd C:\Users\andria\Desktop\graphql-lesson-master\node_modules\grpc
node-pre-gyp ERR! node -v v16.13.0
node-pre-gyp ERR! node-pre-gyp -v v0.13.0
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\andria\Desktop\graphql-lesson-master\node_modules\node-gyp\bin\node-gyp.js 
configure --fallback-to-build --library=static_library --module=C:\Users\andria\Desktop\graphql-lesson-master\node_modules\grpc\src\node\extension_binary\node-v93-win32-x64-unknown\grpc_node.node --module_name=grpc_node --module_path=C:\Users\andria\Desktop\graphql-lesson-master\node_modules\grpc\src\node\extension_binary\node-v93-win32-x64-unknown --napi_version=8 --node_abi_napi=napi --napi_build_versio

**Comment by murgatroid99** [comment]
You are using an old version of the `grpc` package, which does not have support for Node 16. The latest version is 1.24.11, and it does have support for Node 16. You should upgrade.

However, please note that the `grpc` package has been deprecated. We recommend switching to `@grpc/grpc-js`, which does not have these kinds of problems.

**Comment by andria21** [comment]
Hey, thank you so much for your reply. Could you tell me how to actually
achieve this? I mean, how to start using @grpc/grpc-js
