### ISSUE TITLE
GitHub Releases/Tags missing for grpc-js 1.1.3, 1.1.4 and 1.1.5

### ISSUE THREAD

**Issue by nairb774** [grpc/grpc-node#1565]
According to https://www.npmjs.com/package/@grpc/grpc-js there have been releases of 1.1.3, 1.1.4 and 1.1.5, but these releases don't look to be tagged in the repo. Could the correct tags be added/pushed to the repo?

It also is entirely possible I'm holding it wrong or GitHub is lying to me, but this is what I see:
![image](https://user-images.githubusercontent.com/128795/92336272-b7832b00-f053-11ea-85bd-ba06229a7c07.png)
![image](https://user-images.githubusercontent.com/128795/92336275-bd790c00-f053-11ea-829c-74dfe1eb63a3.png).

**Comment by murgatroid99** [comment]
Those tags are now there, along with corresponding release notes.
