### ISSUE TITLE
Sending gRPC status and message in initial metadata: headers instead of trailers

### ISSUE THREAD

**Issue by merlinnot** [grpc/grpc-node#1567]
### Is your feature request related to a problem? Please describe.

While for native gRPC there's no difference between sending `grpc-status` and `grpc-message` in headers vs trailers, compatibility with Envoy (gRPC-web and gRPC-JSON) suffers when this data is sent in trailers. Specifically, forwarding errors in Envoy (for gRPC-web) doesn't work with the following:

```ts
stream.emit('error', {
  code: error.code,
  message: error.message,
});
```

while it does work when `grpc-status` and `grpc-message` are sent in initial metadata:

```ts
const metadata = new Metadata();

metadata.set('grpc-status', error.code.toString());
metadata.set('grpc-message', error.message);

stream.sendMetadata(metadata);

stream.end();
```

### Describe the solution you'd like

I was wondering if it would be possible to always send this data in headers if no data was sent over the stream prior to emitting an `error` event.

### Describe alternatives you've considered

For the time being, I'm manually calling `sendMetadata` + `end`.

### Additional context

https://github.com/grpc/grpc-web/issues/901

**Comment by murgatroid99** [comment]
I don't know how you concluded that "for native gRPC there's no difference between sending `grpc-status` and `grpc-message` in headers vs trailers", but that doesn't sound right to me. The protocol specification says that the status is part of the trailers.

**Comment by merlinnot** [comment]
You're right, I should have phrased it differently, sorry for that: for native gRPC there's _potentially_ no difference between sending `grpc-status` and `grpc-message` in headers vs trailers, as both can be supported. For `grpc-web`, only headers can be supported, unless we make some changes to the `grpc-web` protocol.

The problem is that this currently doesn't work in `grpc-web` if it's sent in trailers. I'm looking for a solution to this problem and this seemed to be the easiest idea on my list.

**Comment by merlinnot** [comment]
Now that I think about it, maybe we should move the conversation to https://github.com/grpc/grpc or https://github.com/grpc/grpc-web?

**Comment by murgatroid99** [comment]
I don't know the details of the Envoy grpc-web plugin, but I was under the impression that it properly handled the status in the trailers. If it doesn't, that is probably a bug that should be filed on the grpc-web repository.

**Comment by murgatroid99** [comment]
Recent versions of grpc-js (>=1.8.x) support sending and receiving trailers-only responses, where the response only has one headers block, which is marked as ending the stream. Specifically, if a server application ends a call without explicitly sending any headers or messages, the response will be sent as a trailers-only response. I think that is the closest we will get to implementing the functionality described in this issue.
