### ISSUE TITLE
Client call with self signed certificates don't verify properly

### ISSUE THREAD

**Issue by ericabr** [grpc/grpc-node#157]
Hi all,
So, I'm trying to make a secure connection to a GRPC server written in GO.
The client connection is written with the node js GRPC module. Both services are running in Kubernetes. **NOTE, when using a go client this works using the SAME certificates.**

Here is how I am creating my certificates:
```
echo '{ "CN": "ca", "key": { "algo": "rsa", "size": 2048 }, "names": [ { "C": "US", "L": "NC", "ST": "Raleigh" } ] }' > ca-csr.json
# Generate the CA using the signing request we created above
cfssl gencert -initca ca-csr.json | cfssljson -bare ca -

echo '{ "signing": { "default": { "expiry": "168h" }, "profiles": { "server": { "expiry": "43800h", "usages": [ "signing", "key encipherment", "server auth" ] }, "client": { "expiry": "43800h", "usages": [ "signing", "key encipherment", "client auth" ] }, "peer": { "expiry": "43800h", "usages": [ "signing", "key encipherment", "server auth", "client auth" ] } } } }' > ca.json

echo '{ "CN": "server", "hosts": [ "localhost", "127.0.0.1", "server.kube-system", "server.kube-system.svc",  #master_hosts ], "key": { "algo": "rsa", "size": 2048 }, "names": [ { "C": "US", "L": "NC", "ST": "Raleigh" } ] }' > server.json
sed -i "s/#master_hosts/$master_hosts/g" server.json

echo '{"CN":"api","hosts":["api.kube-system", "api.kube-system.svc", "localhost", "127.0.0.1", #master_hosts],"key":{"algo":"rsa","size":2048}}' > api.json
sed -i "s/#master_hosts/$master_hosts/g" api.json

cfssl gencert -ca=ca.pem \
-ca-key=ca-key.pem \
-config=ca.json \
-profile=peer server.json | cfssljson \
-bare server

cfssl gencert -ca=ca.pem \
-ca-key=ca-key.pem \
-config=ca.json \
-profile=peer api.json | cfssljson \
-bare api
````

That creates: `ca.pem, ca-key.pem, api.pem, api-key.pem, server.pem, server-key.pem`

The client code:
```
const setupClientConn = (token) => {
    const meta = new grpc.Metadata();
    meta.add('Authorization', 'Bearer ' + token);

    try{
        //trapping the errors in case the certs are not available in the /etc/certs directory
        const cacert = readFileSync(resolve(certsDir ,'ca.crt')),
            cert = readFileSync(resolve(certsDir, 'tls.crt')),
            key = readFileSync(resolve(certsDir, 'tls.key')),
            creds = grpc.credentials.createSsl(cacert, key, cert);
        let client = new serverProto.hapi.services.ReleaseService(serverUrl, creds,
            { 'grpc.max_send_message_length': 8 * 1024 * 1024, 'grpc.max_receive_message_length': -1 });
        grpc.waitForClientReady(client, 0, () => logger.log('connected'));
        return { client, meta };
    }
    catch(err){
        //will connect without using the certs if an error happens
        let client = new serverProto.hapi.services.ReleaseService(serverUrl, grpc.credentials.createInsecure(),
            { 'grpc.max_send_message_length': 8 * 1024 * 1024, 'grpc.max_receive_message_length': -1 });
        grpc.waitForClientReady(client, 0, () => logger.log('insecure connected'));
        return { client, meta };
    }
    
};
```

- `tls.crt` -> `client.pem`
- `tls.key` -> `client-key.pem`
- `ca.crt` -> `ca.pem`
Here is the error I get on the client side:
```
E0117 16:24:53.016696285      17 ssl_transport_security.c:630] Invalid cert chain file.
E0117 16:24:53.016724882      17 security_connector.c:838]   Handshaker factory creation failed with TSI_INVALID_ARGUMENT.
E0117 16:24:53.016734214      17 secure_channel_create.c:127] Failed to create secure subchannel for secure name 'tiller-deploy.kube-system:44134'
E0117 16:24:53.016741557      17 secure_channel_create.c:158] Failed to create subchannel arguments during subchannel creation.

```

**Comment by murgatroid99** [comment]
I don't recognize this error. @jboeuf do you know what's happening here?

**Comment by jboeuf** [comment]
Looks like for some reason, `tsi_create_ssl_client_handshaker_factory` doesn't like the passed in `tls.crt`. @murgatroid99 or @jiangtaoli2016, can you try to repro the cert the creation and see what's wrong here?

**Comment by ericabr** [comment]
Here is the code I wrote for the go client that actually works:
I'm running this in the same **pod** and using the **same certificates** to make sure it's not a fluke with our certificate creation process.

```
func main() {
	// flag.Parse()
	var opts []grpc.DialOption
	certificate, err := tls.LoadX509KeyPair(crt, key)
	if err != nil {
		fmt.Printf("could not load client key pair: %s", err)
		return

	}

	// Create a certificate pool from the certificate authority
	certPool := x509.NewCertPool()
	ca, err := ioutil.ReadFile(ca)
	if err != nil {
		fmt.Printf("could not read ca certificate: %s", err)
		return

	}

	// Append the certificates from the CA
	if ok := certPool.AppendCertsFromPEM(ca); !ok {
		fmt.Printf("failed to append ca certs")
		return
	}

	creds := credentials.NewTLS(&tls.Config{
		ServerName:   addr, // NOTE: this is required!
		Certificates: []tls.Certificate{certificate},
		RootCAs:      certPool,
	})

	opts = append(opts, grpc.WithTransportCredentials(creds))
	ch := make(chan *rls.ListReleasesResponse, 1)
	conn, err := grpc.Dial(addr, opts...)
	if err != nil {
		log.Fatalf("fail to dial: %v", err)
		return
	}

	defer close(ch)
	defer conn.Close()
	errc := make(chan error, 1)
	client := rls.NewReleaseServiceClient(conn)
	ctx := metadata.NewOutgoingContext(context.TODO(), nil)
	req := &rls.ListReleasesRequest{Namespace: "default"}

	s, err := client.ListReleases(ctx, req)

	if err != nil {
		log.Fatalf("failed to get contents %v", err)
		return
	}

	for {
		msg, err := s.Recv()
		if err == io.EOF {
			log.Print("End of file")
			return
		}
		if err != nil {
			errc <- err
			log.Fatalf("error looping through contents %v", err)
			return
		}
		ch <- msg
		log.Printf("contents being returned are %v", ch)
	}

}
```

**Comment by jiangtaoli2016** [comment]
@ericabr Sorry for late response. I reproduced the certificates generated by your script and I embedded them on gRPC c++ client/server, it has no problem. So certificate creation is fine. 

I don't know how to run your client code. Could you paste the full client code so that I can repo your error? From the error log, it appears that the client has trouble loading the certificate files.

**Comment by embrown30** [comment]
So I'm using node JS not c++.

**Comment by jiangtaoli2016** [comment]
I understand your client code is running in JS. Can you paste your full JS code? 
Let me run a greeter example using SSL credential in JS and see whether it works.

**Comment by ericabr** [comment]
So, that was just the connection code. I'm attaching how I would use the connection below.

The function `setupClientConn` gets called by another function. Then the resulting connection is used to make the call to the services.
This should be able to be replicated with simple JS client connection to a GoLang server using those certificates, since that is my use case. I already verified it wasn't the certificate because it works if I use a golang client to connect to the golang server.

```
module.exports.listReleases = (token, callback) => {
    logger.log('About to call listReleases ');
    let releaseData = {releases: []};
    try{
        const result = setupClientConn(token);
        let call = result.client.listReleases({status_codes: [1, 4, 0]}, result.meta);
        call.on('data', function(release){
            if(release.count && release.count > 0){
                release.releases.forEach((item) =>{
                    logger.log('Release name ', item.name);
                    releaseData.releases.push(item);
                });
                return release;
            }
        //logger.log("Release found ", release);
        });
        call.on('end', function(){
            logger.log('Done with server sending');
            callback(releaseData);
        });
        call.on('status', function(status){
            logger.log('Whats the status ', status);
        });
        call.on('error', function(error){
            logger.log('Error getting connection ', error);
            callback(error);
        });
    }catch(err){
        logger.log('Problem calling RPC server ', err);
        callback(err);
    }

};
```

**Comment by jiangtaoli2016** [comment]
@ericabr thanks a lot for your patience. I could not reproduce the failure. I suspect your client code does not open the certificate/key files correctly.

I did manage to run a greeter client/server example in node.js using the certificate generation script you provide, where I set $master_hosts="jiangtao.test". The certificate is placed in /home/jiangtao/cert in my experiment.

My code is modified on grpc/example/node.

My greeter client code:

```
var messages = require('./helloworld_pb');
var services = require('./helloworld_grpc_pb');

var grpc = require('grpc');
var fs = require('fs');
var path = require('path');

function main() {
  const cacert = fs.readFileSync(path.resolve('/home/jiangtao/cert', 'ca.pem')),
        cert = fs.readFileSync(path.resolve('/home/jiangtao/cert', 'server.pem')),
        key = fs.readFileSync(path.resolve('/home/jiangtao/cert','server-key.pem')),
        creds = grpc.credentials.createSsl(cacert, key, cert);
  var client = new services.GreeterClient('localhost:50051',
                                          creds);
  var request = new messages.HelloRequest();
  var user;
  if (process.argv.length >= 3) {
    user = process.argv[2];
  } else {
    user = 'world';
  }
  request.setName(user);
  client.sayHello(request, function(err, response) {
    console.log('Greeting:', response.getMessage());
  });
}

main();
```

The server code is following:

```
var messages = require('./helloworld_pb');
var services = require('./helloworld_grpc_pb');

var grpc = require('grpc');
var fs = require('fs');
var path = require('path');

/**
 * Implements the SayHello RPC method.
 */
function sayHello(call, callback) {
  var reply = new messages.HelloReply();
  reply.setMessage('Hello ' + call.request.getName());
  callback(null, reply);
}

/**
 * Starts an RPC server that receives requests for the Greeter service at the
 * sample server port
 */
function main() {
  var server = new grpc.Server();
  server.addService(services.GreeterService, {sayHello: sayHello});
  const cacert = fs.readFileSync(path.resolve('/home/jiangtao/cert', 'ca.pem')),
        cert = fs.readFileSync(path.resolve('/home/jiangtao/cert', 'server.pem')),
        key = fs.readFileSync(path.resolve('/home/jiangtao/cert','server-key.pem')),
        creds = grpc.ServerCredentials.createSsl(cacert, [{private_key: key, cert_chain: cert}]);
  server.bind('0.0.0.0:50051', creds);
  server.start();
}

main();
```

My client and server can talk to each other using SSL. I hope it helps. 

My recommendation is that you put your credentials on the same folders as your .js code. Read from local directory, e.g., fs.readFileSync('ca.pem'), to make sure files are loaded correctly.

**Comment by ericabr** [comment]
@jiangtaoli2016 
Hi,
The gist is that if I write a **node js client** and connect to a **go based server**, using the certificates don't work. If I use the insecure client then the connection works just fine.
I  have already figured out the problem is not the certificates, but trying to verify the connection to the server from **node to golang.**
If I use the exact same certificates from a **golang client to a golang server**, the connection works.

Can you try **exactly** what I have done?
Start a **golang server** with certificates and use a **node js client** with the certificates to connect to the server securely.
It would be nice to get this fixed, but we will abandon the **grpc node js** client if this can't be resolved.

**Comment by jiangtaoli2016** [comment]
@ericabr If you can post your full client and server code (including proto), I can try to reproduce. 

As I said, the problem is mostly likely on reading certificates on the client node.js code. If you can try the following and place the certificate on the same folder as the source code. At least we can see where the problem is. 

```
        const cacert = fs.readFileSync('ca.pem'),
            cert = fs.readFileSync('server.pem'),
            key = fs.readFileSync('server-key.pem'),
            creds = grpc.credentials.createSsl(cacert, key, cert);
```

It does not matter whether client talks to Go server or node.js server. 

PS: did you use latest grpc code? Looking at the error code, it still uses ssl_transport_security.c. We already changed to .cc a while ago.

**Comment by xelawafs** [comment]
I have a similar issue trying to connect to a go based server. I've filled an issue with the project I'm using here: https://github.com/chemicstry/recksplorer/issues/18

Maybe the logs I have there might help figure this out.

**Comment by jiangtaoli2016** [comment]
@xelawafs Your error looks like a different error during SSL handshake(@ericabr error looks like trouble loading the SSL certificate chain). Could you give us details so that we can reproduce the error.

**Comment by nicolasnoble** [comment]
There was no real update from questions asked to the bug reporters since 3 months, this bug has become stale. Closing.
