### ISSUE TITLE
Failed to connect before the deadline on endorser (hyperledger fabric)

### ISSUE THREAD

**Issue by WJay-tec** [grpc/grpc-node#1573]
Hi i am currently trying to establish a gateway using the fabric network, but i faced the following errors listed at the picture below
![Capture](https://user-images.githubusercontent.com/64273338/93090399-48e74280-f6cf-11ea-9be3-17d3f629c341.JPG)

I am able to register and enroll users with the certificate authority through the application but it is unable to connect to the peers.

THINGS THAT I HAVE DONE IN ATTEMPT TO FIX THE ERROR : 
1) Double checking the TLScacerts to see if i have placed them wrongly or not ( the content of the pem certificate is used rather than providing the file path)
2) Making sure that the ports specified in the connection profile are up and running through checking the docker containers using "docker ps" command.                 
3) Changing the Discovery options asLocalhost to true in ConnectionOptions settings (this is because the environment that i am running in purely exists in the local network only)
4) Reinstalling and testing various versions of fabric-network , nodejs , grpc and etc.

**Common-connection profile**
![ccp](https://user-images.githubusercontent.com/64273338/93091701-07f02d80-f6d1-11ea-8f24-9428067a37e0.JPG)
**Connection Options**
![connection options](https://user-images.githubusercontent.com/64273338/93091707-09b9f100-f6d1-11ea-8e0d-15ef8bad63c8.JPG)
**docker container configuration**
![docker container](https://user-images.githubusercontent.com/64273338/93091711-0b83b480-f6d1-11ea-93cb-f6343b6b2971.JPG)
**docker ps for running containers**
![docker ps](https://user-images.githubusercontent.com/64273338/93091992-6d441e80-f6d1-11ea-9302-413fabbf5ff7.JPG)

Any help that can be provided will be greatly appreciated. Thank You!

**Comment by murgatroid99** [comment]
Why did you file this issue here, instead of in the Hyperledger Fabric project?

**Comment by WJay-tec** [comment]
Hi @murgatroid99 , sorry about that i am new to github. I posted it here because i suspect that grpc is causing the error which made me unable to connect with the peers.

**Comment by murgatroid99** [comment]
OK. I assume the configuration information you shared here is for Hyperledger Fabric. If so, you should ask them because they are the ones who will best understand what that configuration means and why there might be an error.
