### ISSUE TITLE
Keys that DON'T  end with "-bin" must be String value

### ISSUE THREAD

**Issue by andy-betin** [grpc/grpc-node#1578]
### Problem description
When i create request with multiple metadata keys, is have error:
"Error constructing the request
keys that don't end with '-bin' must have String values"

In other case with only one metadata (example {"remote-host":"192.168.1.1:9090"} ) - it is work;

### Reproduction steps
Body request such as:
{
  "sort": "asc",
  "order": "id",
  "limit": 20,
  "offset": 0
}

and meta data:
[
    {"remote-host":"192.168.1.1:9090"},
    {"Authorization":"Bearer  SOME_TOKEN"}
]

### Environment
 - Windows 10 64Bit
 - Node version 10.11.0
 - BloomRPC version 1.4.1

**Comment by murgatroid99** [comment]
The metadata you have here is not in the format that gRPC uses directly, so it is hard to tell what is triggering that error. I suggest filing an issue with BloomRPC.
