### ISSUE TITLE
Usage with React Native

### ISSUE THREAD

**Issue by dclipca** [grpc/grpc-node#1585]
I want to use grpc-js with React Native but it seems that there is no documentation. Can anyone provide an example of using grpc-js with React Native? Thank you in advance.

**Comment by murgatroid99** [comment]
grpc-js is a Node library, and if I understand correctly, React Native is its own separate runtime. So, I would not expect them to work together.

**Comment by virtumonde** [comment]
@murgatroid99 Most pure JS modules work with React Native.

**Comment by virtumonde** [comment]
@murgatroid99 can you point me to some sort of example of using this library?

**Comment by murgatroid99** [comment]
[Here is a client example](https://github.com/grpc/grpc/blob/master/examples/node/dynamic_codegen/greeter_client.js). Just replace `grpc` with `@grpc/grpc-js`.

**Comment by virtumonde** [comment]
@murgatroid99 can you point out how does ```var PROTO_PATH = __dirname + '/../../protos/helloworld.proto';``` work? Can you directly ```require``` the ```.proto``` file?

**Comment by murgatroid99** [comment]
A couple of lines after that, that string is passed to `protoLoader.loadSync`. That library is responsible for loading `.proto` files for use with the Node gRPC libraries.

**Comment by virtumonde** [comment]
@murgatroid99, what about Typescript? Does grpc-js support it?

**Comment by murgatroid99** [comment]
Yes. The type definition files are distributed with the library.

**Comment by virtumonde** [comment]
@murgatroid99 Thank you! I have another question. It is problematic for me to give the path to the ```.proto``` file because ```__dirname``` is not supported in React Native. I am looking for a way to directly import it using ```require``` and then feed it into the ```loader``` is something like this possible?

**Comment by murgatroid99** [comment]
No, that does not work. An alternative is to use code statically generated with the `grpc-tools` package. There is an example [here](https://github.com/grpc/grpc/tree/master/examples/node/static_codegen); the equivalent client code is in that directory's `greeter_client.js`. To generate code for use with `grpc-js`, you will need to set the `grpc_js` option in the `--grpc_out` argument in the code generation command, like this: `--grpc_out=grpc_js:<directory>`. You will also need to depend on the `google-protobuf` package to use that generated code.

**Comment by virtumonde** [comment]
@murgatroid99 Does this presume that I will be able to load the ```packageDefinition``` into grpc?

**Comment by virtumonde** [comment]
@murgatroid99 did I understand correctly that I make the stub with grpc-tools then it is a standalone solution and I would not have to use ```protoloader```?

**Comment by virtumonde** [comment]
Also, what about the go compiler like this ```protoc game.proto --grpc-web_out=import_style=typescript,mode=grpcweb:./ts```? As I understand grpcweb is not compatible with grpc-js. Am I correct?

**Comment by murgatroid99** [comment]
I'm not sure what you are asking regarding the `packageDefinition`. You are correct that the code generated with `grpc-tools` is a standalone solution and does not require the `@grpc/proto-loader` library. The `grpc-web` library is a separate thing that is not compatible with the Node gRPC libraries.

**Comment by virtumonde** [comment]
@murgatroid99 thank you! I am sorry I was too annoying. I am not very experienced with gRPC.

**Comment by virtumonde** [comment]
For other people reading this, I would advise using ```grpc-web``` instead of this as it works without any special magic spells. Here is an example: https://github.com/grpc/grpc-web/issues/90

**Comment by githorse** [comment]
@murgatroid99 I was unable to get the [given example](https://github.com/grpc/grpc/blob/master/examples/node/dynamic_codegen/greeter_client.js) working in React Native because a bunch of dependencies built into `node` are not there in the React Native / Metro runtime (`http2`, `path`, etc.). I installed some of them manually but finally ran into one (I think it was `fs`) I could not seem to fix and gave up. (I did not get [rn-nodeify](https://www.npmjs.com/package/rn-nodeify) working though it seems like a promising way to solve the issue.) @virtumonde I'm not sure if I'm missing something here about the right way to make this work? 

Looking into the `grpc-web` and `grpc-tools` ideas now.

**Comment by murgatroid99** [comment]
For future reference, the `@grpc/grpc-js` library is intended only for use in the Node.js runtime. React Native is not compatible with Node.js, so `@grpc/grpc-js` will not work with React Native.

For JS environments that are not compatible with Node.js, I recommend using [grpc-web](https://github.com/grpc/grpc-web) instead.
