### ISSUE TITLE
[grpc-js] server.bindAsync() and server.start() do not actually start a server

### ISSUE THREAD

**Issue by koresar** [grpc/grpc-node#1592]
### Problem description

This code does not start the server
```js
            await new Promise((resolve, reject) => {
               server.bindAsync(
                    `0.0.0.0:50051`,
                    grpc.ServerCredentials.createInsecure(),
                    (err, result) => (err ? reject(err) : resolve(result))
                );
            });

          server.start();

          console.log(server.started); // TRUE !!!
```

You have to add to actually wait from 500 to 1000 ms for the server to start accepting calls:

```js
await new Promise((r) => setTimeout(r, 1000));
```

Expected:
 - Either `bindAsync()` or `.start()` should not return until the server is actually capable of receiving calls.

### Environment
 - OS name, version and architecture: any
 - Node version: >10
 - Node installation method: any
 - Package name and version: 1.1.7

**Comment by murgatroid99** [comment]
I tried to reproduce this problem but it works for me. Here is the code I used:

```js
const PROTO_PATH = __dirname + '/helloworld.proto';

const grpc = require('@grpc/grpc-js');
const protoLoader = require('@grpc/proto-loader');
const packageDefinition = protoLoader.loadSync(
  PROTO_PATH,
  {keepCase: true,
    longs: String,
    enums: String,
    defaults: true,
    oneofs: true
  });
const hello_proto = grpc.loadPackageDefinition(packageDefinition).helloworld;

function sayHello(call, callback) {
  callback(null, {message: 'Hello ' + call.request.name});
}

async function main() {
  const server = new grpc.Server();

  server.addService(hello_proto.Greeter.service, {sayHello: sayHello});

  await new Promise((resolve, reject) => {
    server.bindAsync(
        `0.0.0.0:50051`,
        grpc.ServerCredentials.createInsecure(),
        (err, result) => (err ? reject(err) : resolve(result))
    );
  });

  server.start();

  console.log(server.started);

  const client = new hello_proto.Greeter('localhost:50051', grpc.credentials.createInsecure());

  client.sayHello({name: 'world'}, function(err, response) {
    console.log('Greeting:', response.message);
    server.tryShutdown(() => {});
  });
}

main();
```

You can see that I used exactly the code you provided for starting the server. The request succeeds pretty quickly for me.

---

The `helloworld.proto` file looks like this:

```proto
syntax = "proto3";

package helloworld;

// The greeting service definition.
service Greeter {
  // Sends a greeting
  rpc SayHello (HelloRequest) returns (HelloReply) {}
}

// The request message containing the user's name.
message HelloRequest {
  string name = 1;
}

// The response message containing the greetings
message HelloReply {
  string message = 1;
}
```

**Comment by koresar** [comment]
Apologies. Looks like my code example is not complete.

Could you please put these two lines right before the `server.start()`:

```js
await new Promise(r => client.waitForReady(Date.now() + 100, r);
await new Promise(r => client.sayHello({name:'world'}, r);
```

That's how I check if server is up. If it's down, I start it - and retry the call.

**Comment by murgatroid99** [comment]
If I add those right before `server.start()` (along with the client constructor call), nothing changes. The test still succeeds very quickly. If instead I move those lines before `server.bindAsync`, the last request fails with an UNAVAILABLE status. This is expected because as I mentioned in the other issue you filed, the client does exponential backoff when trying to connect, so it does not reconnect immediately after the server becomes available. Adding the `waitForReady` option to that last request as described in the other issue makes the test succeed again, with a small delay.

**Comment by koresar** [comment]
Indeed you are right, `waitForReady:true` did solve my issue.
I'm closing this issue as resolved.
That for all your help!
