### ISSUE TITLE
documentation: server and client side stream events

### ISSUE THREAD

**Issue by jon-whit** [grpc/grpc-node#1595]
Looking at the documentation, I don't see any details about the events that are emitted when certain server or client side events take place. For example, I know the `stream.on('end', callback)` is invoked server side when the client calls on `stream.end()`. But this behavior is not specified anywhere in the documentation? Is it just expected to read the source code at this point?

**Comment by murgatroid99** [comment]
The stream objects in the gRPC library are subclasses of the built in [`Readable`, `Writable`, and `Duplex` classes](https://nodejs.org/api/stream.html) in object mode. That documentation covers most of the methods and events that those classes have.
