### ISSUE TITLE
grpc_node.node: undefined symbol: OPENSSL_init_ssl

### ISSUE THREAD

**Issue by celesteking** [grpc/grpc-node#1598]
### Problem description
PANIC on scl NODE EL7.

### Reproduction steps
```
> new grpc.Client('localhost', grpc.credentials.createSsl(Buffer.alloc(1))).waitForReady(Date.now(), ()=>{}); 
undefined
> node: symbol lookup error: /xx/node_modules/grpc/src/node/extension_binary/node-v72-linux-x64-glibc/grpc_node.node: undefined symbol: OPENSSL_init_ssl
```

### Environment
grpc@1.24.3
```bash
$ node -v
v12.18.2
$ which node
/opt/rh/rh-nodejs12/root/usr/bin/node
$ rpm -qf /opt/rh/rh-nodejs12/root/usr/bin/node
rh-nodejs12-nodejs-12.18.2-1.el7.x86_64
$ rpm -qi rh-nodejs12-nodejs-12.18.2-1.el7.x86_64
Name        : rh-nodejs12-nodejs
Version     : 12.18.2
Release     : 1.el7
Architecture: x86_64
Install Date: Tue 25 Aug 2020 03:49:13 AM CDT
Group       : Development/Languages
Size        : 35528528
License     : MIT and ASL 2.0 and ISC and BSD
Signature   : RSA/SHA1, Mon 24 Aug 2020 10:16:17 AM CDT, Key ID 4eb84e71f2ee9d55
Source RPM  : rh-nodejs12-nodejs-12.18.2-1.el7.src.rpm
Build Date  : Mon 20 Jul 2020 08:42:40 AM CDT
Build Host  : c1bk.rdu2.centos.org
Relocations : (not relocatable)
Packager    : CBS <cbs@centos.org>
Vendor      : CentOS
URL         : http://nodejs.org/
Summary     : JavaScript runtime
Description :
Node.js is a platform built on Chrome's JavaScript runtime
for easily building fast, scalable network applications.
Node.js uses an event-driven, non-blocking I/O model that
makes it lightweight and efficient, perfect for data-intensive
real-time applications that run across distributed devices.
$ ldd /opt/rh/rh-nodejs12/root/usr/bin/node
        linux-vdso.so.1 =>  (0x00007ffd236ff000)
        libcrypto.so.10 => /lib64/libcrypto.so.10 (0x00007f73dfc4b000)
        libssl.so.10 => /lib64/libssl.so.10 (0x00007f73df9d9000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f73df7d5000)
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f73df4ce000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f73df1cc000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f73defb6000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f73ded9a000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f73de9cc000)
        libz.so.1 => /lib64/libz.so.1 (0x00007f73de7b6000)
        libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00007f73de569000)
        libkrb5.so.3 => /lib64/libkrb5.so.3 (0x00007f73de280000)
        libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00007f73de07c000)
        libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00007f73dde49000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f73e00ae000)
        libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x00007f73ddc39000)
        libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007f73dda35000)
        libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f73dd81b000)
        libselinux.so.1 => /lib64/libselinux.so.1 (0x00007f73dd5f4000)
        libpcre.so.1 => /lib64/libpcre.so.1 (0x00007f73dd392000)
```

To get SCL ver installed:
```
yum --enablerepo=extras install centos-release-scl-rh
yum install rh-nodejs12
```

### Additional context
This is happening both with bundled binary from June 4th and with extension that's been compiled from source on this machine. WTF guys this is extremely unexpected and is impeding deployment.

**Comment by celesteking** [comment]
Also, for whatever random reason, this:
```bash
$ npm install node-webcrypto-ossl             

> node-webcrypto-ossl@2.1.2 install /home/temp/node_modules/node-webcrypto-ossl
> node-gyp rebuild

make: Entering directory `/home/temp/node_modules/node-webcrypto-ossl/build'
  CXX(target) Release/obj.target/nodessl/src/main.o
  CXX(target) Release/obj.target/nodessl/src/core/key_exp.o
  CXX(target) Release/obj.target/nodessl/src/core/scoped_ssl.o
  CXX(target) Release/obj.target/nodessl/src/core/logger.o
  CXX(target) Release/obj.target/nodessl/src/core/excep.o
  CXX(target) Release/obj.target/nodessl/src/core/digest.o
  CXX(target) Release/obj.target/nodessl/src/core/bn.o
  CXX(target) Release/obj.target/nodessl/src/rsa/rsa_gen.o
  CXX(target) Release/obj.target/nodessl/src/rsa/rsa_jwk.o
  CXX(target) Release/obj.target/nodessl/src/rsa/rsa_pkcs1.o
  CXX(target) Release/obj.target/nodessl/src/rsa/rsa_oaep.o
  CXX(target) Release/obj.target/nodessl/src/rsa/rsa_pss.o
  CXX(target) Release/obj.target/nodessl/src/ec/ec_gen.o
  CXX(target) Release/obj.target/nodessl/src/ec/ec_dsa.o
  CXX(target) Release/obj.target/nodessl/src/ec/ec_dh.o
  CXX(target) Release/obj.target/nodessl/src/ec/ec_jwk.o
  CXX(target) Release/obj.target/nodessl/src/aes/aes_gen.o
  CXX(target) Release/obj.target/nodessl/src/aes/aes_ecb.o
  CXX(target) Release/obj.target/nodessl/src/aes/aes_cbc.o
  CXX(target) Release/obj.target/nodessl/src/aes/aes_gcm.o
  CXX(target) Release/obj.target/nodessl/src/aes/aes_ctr.o
  CXX(target) Release/obj.target/nodessl/src/hmac/hmac_gen.o
  CXX(target) Release/obj.target/nodessl/src/hmac/hmac_sign.o
  CXX(target) Release/obj.target/nodessl/src/pbkdf2/pbkdf2_derive.o
  CXX(target) Release/obj.target/nodessl/src/node/common.o
  CXX(target) Release/obj.target/nodessl/src/node/w_key.o
  CXX(target) Release/obj.target/nodessl/src/node/w_aes.o
  CXX(target) Release/obj.target/nodessl/src/node/w_hmac.o
  CXX(target) Release/obj.target/nodessl/src/node/w_pbkdf2.o
  CXX(target) Release/obj.target/nodessl/src/node/w_core.o
  CXX(target) Release/obj.target/nodessl/src/node/async_rsa.o
  CXX(target) Release/obj.target/nodessl/src/node/async_ec.o
  CXX(target) Release/obj.target/nodessl/src/node/async_aes.o
  CXX(target) Release/obj.target/nodessl/src/node/async_hmac.o
  CXX(target) Release/obj.target/nodessl/src/node/async_pbkdf2.o
  CXX(target) Release/obj.target/nodessl/src/node/async_core.o
  SOLINK_MODULE(target) Release/obj.target/nodessl.node
  COPY Release/nodessl.node
make: Leaving directory `/home/temp/node_modules/node-webcrypto-ossl/build'
npm WARN saveError ENOENT: no such file or directory, open '/home/temp/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/temp/package.json'
npm WARN temp No description
npm WARN temp No repository field.
npm WARN temp No README data
npm WARN temp No license field.

+ node-webcrypto-ossl@2.1.2
updated 1 package and audited 19 packages in 36.887s
found 0 vulnerabilities

$ node
Welcome to Node.js v12.18.2.
Type ".help" for more information.
> require('node-webcrypto-ossl')
node: symbol lookup error: /home/temp/node_modules/node-webcrypto-ossl/build/Release/nodessl.node: undefined symbol: OPENSSL_init_crypto
```

**Comment by murgatroid99** [comment]
According to [this documentation](https://www.openssl.org/docs/man1.1.0/man3/OPENSSL_init_ssl.html), "The `OPENSSL_init_ssl()` function was added in OpenSSL 1.1.0." The most likely cause of this error is that you have an earlier version of OpenSSL. I suggest upgrading.

Alternatively, you may want to use `@grpc/grpc-js` instead of `grpc`. We created that package to avoid these kinds of problems.

**Comment by celesteking** [comment]
Who is "you", Michael? This is an EL7 system, an Enterprise OS distribution provided by IBM and Oracle. 

$ openssl version
OpenSSL 1.0.2k-fips  26 Jan 2017

I haven't got an earlier version, I have got a system-supplied version, supplied by distro. I have got a nodejs that's linked against shared openssl OS supplied lib (which is the only proper way of doing stable software in enterprise world). It's impossible to upgrade openssl in EL systems, whole and entire distribution is compiled against and expects it to be a stable version. No openssl upgrade is possible.

Is there an option that I can pass so it just skips whatever assumptions it's making and just goes with shared openssl?

**Comment by murgatroid99** [comment]
1.0.2 comes before 1.1.0. That's why it doesn't have this function. The problem is not that the `grpc` library isn't using that OpenSSL library, but rather that that OpenSSL library doesn't provide the function `grpc` is calling.

**Comment by celesteking** [comment]
You talk gibberish. Are you trying to tell me that `grpc-node` requires `openssl` >= 1.1.0 in order to work? I don't believe you. There's a grpc library RPM that's linked against EL7's openssl and is working just fine -- http://rpm.pbone.net/index.php3/stat/4/idpl/69962143/dir/centos_7/com/grpc-1.20.1-1.el7.x86_64.rpm.html (see `Requires` list to confirm).

Unless there's *something* very special you do in node-grpc that others (C , Golang, PHP bindings) don't do and what requires exclusively >= 1.1.0.  Thanks for replying.

**Comment by celesteking** [comment]
Well, as expected, grpc native actually supports openssl < 1.1.0,  [as seen in code](https://github.com/grpc/grpc/blob/85e22ef28d55f27e8efb3d5e2e43ca6f59971065/src/core/tsi/ssl_transport_security.cc#L159-L162).  That's what happens when you talk to a horse.

So the question remains -- how do I tell the build script to actually use OS-bundled (aka shared) openssl lib instead of the one that is supplied by nodejs? (despite nodejs not  being built against it, but against the SHARED lib, I'm unsure why they supply those openssl include files, they like to mess with people probably). Thanks.

**Comment by celesteking** [comment]
I was able to work around the problem by doing: ` rm -rf  /usr/src/builder/.cache/node-gyp/12.18.2/include/node/openssl` and then  `make BUILDTYPE=Release -C build` inside the extension dir. For whatever random reason it would populate `build/./Release/.deps/Release/obj.target/grpc/deps/grpc/src/core/tsi/ssl_transport_security.o.d` with superfluous openssl header includes otherwise.

**Comment by murgatroid99** [comment]
I do not appreciate your tone in this issue. You are being unjustifiably hostile while I am just trying to help. I am not familiar with all parts of the core library so I made some inferences based on the information in the provided error message, and I came to a conclusion that was not entirely correct and I made a recommendation based on that conclusion.

Honestly, I'm still not exactly sure what is causing this failure. As far as I can tell, the OpenSSL headers set `OPENSSL_API_COMPAT` to `0` by default and the `grpc` build file `binding.gyp` doesn't explicitly set it, so I don't know why it would take that branch by default. I think you could probably change that behavior by explicitly setting `OPENSSL_API_COMPAT` to a lower number in the preprocessor flags.

Regarding the other languages, if this is a weird interaction with the headers provided by Node as your last comment appears to indicate, it would make sense why the C library is not impacted. The Go library is an entirely separate codebase, so it wouldn't have this problem. And it looks like the PHP library always builds BoringSSL and never uses the system OpenSSL, which would explain that too.

**Comment by celesteking** [comment]
Nobody is being hostile to anybody, relax. You're taking this bug too personally. I was able to use your workaround and make it compile & link properly.
```
$ grep -2 OPENSSL_API_COMPAT binding.gyp 
        'defines': [
            'NDEBUG',
            'OPENSSL_API_COMPAT=1'
        ],
      },
```
The only thing that remains is getting down to the source of this issue and pushing a fix so that it would work with node linked against shared openssl. Or possibly mentioning the suggested above workaround or putting a note that EL7 SCL nodejs is not supported and people should try grpc-js instead.

**Comment by murgatroid99** [comment]
I'm not talking about the bug overall. You said "You talk gibberish" and "That's what happens when you talk to a horse" directed at me personally. Comments like that are not appropriate for discussions in this repository.

**Comment by celesteking** [comment]
We've got lost in translation. You should be more on fresh air.
Have I not been so pushy, it would've stopped at comment [#3](https://github.com/grpc/grpc-node/issues/1598#issuecomment-704463225) and nothing would've been done regarding this bug. Closing as this has been taken care of by grpc upstream and will hopefully land back into this repo soon. Thanks.
