### ISSUE TITLE
Allow use enum string option for the grpc-tool (code generation)

### ISSUE THREAD

**Issue by AndreyUtka** [grpc/grpc-node#1599]
it would be great to add `enum: string` option for the grpc-tools in the same way as grpc loader has https://github.com/grpc/grpc-node/tree/master/packages/proto-loader#usage.

Currently it has only numeric implementation

**Comment by murgatroid99** [comment]
The `grpc-tools` package redistributes the `protoc` code generation tool, and `protoc` is responsible for generating the message classes and related APIs, including enum handling. That tool is maintained in [the protobuf repository](https://github.com/protocolbuffers/protobuf), so a feature request there is the most likely way for a change like this to be made.

**Comment by AndreyUtka** [comment]
got it thanks @murgatroid99
