### ISSUE TITLE
Replace ArgueJS because of unsafe call of eval()?

### ISSUE THREAD

**Issue by StabbarN** [grpc/grpc-node#161]
ArgueJS uses `eval()`, see https://github.com/zvictor/ArgueJS/blob/master/argue.js#L203

I'm trying to prevent any usage of eval for all dependencies in an app by setting:
```
window.eval = function() {
  throw new Error("Nope, eval not permitted");
};
```

Are you OK with replacing the usage of ArgueJS (last meaningful update was in May 2013) with something more modern and safe? For example Typescript, flow or manual type checking?
I can see that some files of yours are already converted to Typescript. 

ArgueJS is required here:
https://github.com/grpc/grpc-node/blob/master/packages/grpc-native-core/src/client.js

**Comment by murgatroid99** [comment]
gRPC no longer uses ArgueJS.
