### ISSUE TITLE
react native + arduino+ internet?

### ISSUE THREAD

**Issue by user321123** [grpc/grpc-node#1618]
Hallo world,

How I can create an arduino with a switch in react native over the internet? How would I do that? What do I need?

Thank you all

**Comment by murgatroid99** [comment]
This is the repository for the gRPC libraries for Node.js. What would you like to know specifically about those libraries?

**Comment by user321123** [comment]
How do I establish a connection to the server with node.js?

**Comment by murgatroid99** [comment]
I suggest starting with the [gRPC Node Quick start guide](https://grpc.io/docs/languages/node/quickstart/).
