### ISSUE TITLE
grpc-js channel connectivity states differ from grpc core

### ISSUE THREAD

**Issue by jon-whit** [grpc/grpc-node#1620]
### Problem description
The Channel connectivity state enums in the `grpc-js` package do no align with the same enum integer values in the `grpc` package.

https://github.com/grpc/grpc-node/blob/grpc%401.24.x/packages/grpc-native-core/src/constants.js#L260-L266
vs
https://github.com/grpc/grpc-node/blob/grpc%401.24.x/packages/grpc-js/src/channel.ts#L57-L63

`IDLE` and `SHUTDOWN` do not match as compared to the `grpc` alternative. Because of this it changes client side code for handling those cases. This wasn't called out as a client-side incompatibility in migrating from the `grpc` package.

**Comment by murgatroid99** [comment]
Thank you for bringing this to my attention. I will fix it. But I have to ask: why does your code care about the numeric values of the enums at all?

**Comment by jon-whit** [comment]
@murgatroid99 because currently `@grpc/grpc-js` does not support channel level auto-reconnects (or maybe it does but it doesn't work, in which case I'd be happy to submit and issue). So I've had to implement that client side using the connectivity state enums.

**Comment by murgatroid99** [comment]
grpc-js does support channel level auto-reconnects. Please file an issue describing the problem you are having with it.
