### ISSUE TITLE
base58 instead of base64 on bytes type?

### ISSUE THREAD

**Issue by christopheSeeka** [grpc/grpc-node#1624]
### Problem description
I would like to use base58 instead of base64 on bytes types when set types to String, is there a way to do this at the options level?

### Environment
 - Windows 10 64
 - Node version 12.15.0
 - Npm
 - @grpc/proto-loader": "^0.1.0",

**Comment by murgatroid99** [comment]
No, this is not currently an option. That behavior is controlled by the underlying library [Protubuf.js](https://github.com/protobufjs/protobuf.js), so the first step to having that feature would be making a change in that library, so I suggest filing a feature request there.

In the meantime, the simplest workaround for you would probably be to get the `bytes` fields as buffers and then do the base58 encoding/decoding yourself.

**Comment by christopheSeeka** [comment]
Thank you for the answer, i went for the simplest option, was just asking in case the base58 option exist. Will work like that thanks a lot.
