### ISSUE TITLE
connect ECONNREFUSED 142.250.74.202:443 - request to https://www.googleapis.com/oauth2/v4/token failed 

### ISSUE THREAD

**Issue by mohan570** [grpc/grpc-node#1626]
Hi Team,

In recently last two months only we are getting below error while using detectTextIntent method( const responses = await sessionClient.detectIntent(request); ) in detect.js file( https://github.com/googleapis/nodejs-dialogflow/blob/master/samples/detect.js ).

The Error,

ERROR: Error: Getting metadata from plugin failed with error: request to https://www.googleapis.com/oauth2/v4/token failed, reason: connect ECONNREFUSED 142.250.74.202:443
at Http2CallStream. (API\node_modules\dialogflow\node_modules@grpc\grpc-js\build\src\client.js:102:45)
at Http2CallStream.emit (events.js:322:22)
at Http2CallStream.endCall (API\node_modules\dialogflow\node_modules@grpc\grpc-js\build\src\call-stream.js:74:18)
at API\node_modules\dialogflow\node_modules@grpc\grpc-js\build\src\call-stream.js:355:18
at runMicrotasks ()
at processTicksAndRejections (internal/process/task_queues.js:97:5) {
code: 'ECONNREFUSED',
details: 'Getting metadata from plugin failed with error: request to https://www.googleapis.com/oauth2/v4/token failed, reason: connect ECONNREFUSED 142.250.74.202:443',
metadata: Metadata { internalRepr: Map {} }

Regards,
Mohan A

**Comment by murgatroid99** [comment]
This error is being reported by the gRPC library, but it is most likely coming from the google-auth-library. Since you're using the Diagflow library, I suggest filing an issue either in that repository, or in the [google-auth-library](https://github.com/googleapis/google-auth-library-nodejs) repository.
