### ISSUE TITLE
Reopen: Support parsing of file descriptor sets into package definitions

### ISSUE THREAD

**Issue by tatemz** [grpc/grpc-node#1627]
Thank you for furthering the gRPC and protobuf communities by providing all these great open source packages!

### Is your feature request related to a problem? Please describe.
I am resubmitting the feature request to export the `createPackageDefinition` function in the `@grpc/proto-loader` package.
This feature has been discussed many times across the following threads and beyond:

- https://github.com/grpc/grpc-node/issues/556
- https://github.com/protobufjs/protobuf.js/issues/1117

In fact, this issue is blocking cool features like https://github.com/Urigo/graphql-mesh/pull/1086 from using the canonical `@grpc/proto-loader` package.

I know this feature has already been rejected before, but I feel that it should not have been. If it does not pose a security risk, and the community would like this feature to enable it to build awesome gRPC tooling, then why not?

I've gone ahead and forked this repo and will be submitting a PR to close this issue. If rejected, I see no other way around the issue but to publish and maintain my new fork.

### Describe the solution you'd like
Export the `createPackageDefinition` function in the `@grpc/proto-loader` package.

### Describe alternatives you've considered
If there is a better way to build a package definition from a file descriptor proto set, then I am open to closing this issue in favor of that, provided the grpc team can produce a definitive example.
Otherwise, publishing and maintaining a new fork is the best route.

**Comment by murgatroid99** [comment]
As we have previously explained in #550, #807, and #1535, we will not export the `createPackageDefinition` function because doing so would violate one of the core design goals of the library: hiding the Protobuf.js APIs.

That being said, I have previously looked into an alternate solution to this problem, which is providing a function that can load from a binary-encoded `FileDescriptorSet` or similar and return the same kind of output as `load` and `loadSync`. However, I never got around to fully implementing that solution. One existing obstacle to doing that is protobufjs/protobuf.js#1149.

**Comment by tatemz** [comment]
Thanks for the explanation. If it's against the core design, then perhaps we can use this thread to provide the community with some use case examples as it seems this topic has been off-and-on discussed since 2018 and it'd be ideal to conclude it with some definitive sampless.

I suppose a PR to fix https://github.com/protobufjs/protobuf.js/issues/1149 along with some code samples in the extension README could resolve this issue fully. I'll take a pass at it in the meantime :sweat: 

Thanks again! :tada:

**Comment by tatemz** [comment]
I was working on this and came up with this solution inside of `proto-loader`. Unfortunately, I don't see a way around needing `(Protobuf.Root as Protobuf.RootConstructor)` to properly resolve the types.


```ts
declare module 'protobufjs' {
  interface RootConstructor {
    new (options?: Options): Root;
    fromDescriptor(descriptorSet: descriptor.IFileDescriptorSet | Protobuf.Reader | Uint8Array): Root;
    fromJSON(json: Protobuf.INamespace, root?: Root): Root;
  }
}

function loadFileDescriptorSet(
  filename: string,
  options: Protobuf.IParseOptions & Protobuf.IConversionOptions = {}
): Promise<PackageDefinition> {

  return new Promise((resolve, reject) => {
    fs.readFile(filename, (err, data) => {
      if (err) {
        return reject(err);
      }

      const root = (Protobuf.Root as Protobuf.RootConstructor).fromDescriptor(data);
      root.resolveAll();
      return resolve(createPackageDefinition(root, options!));
    });
  });
}
```

**Comment by tatemz** [comment]
@murgatroid99 can we get #1635 pushed into the NPM package registry?

Also for anyone coming to this issue from Google, please see the tests for examples loading binary-encoded, JSON, and plain JS object file descriptor sets https://github.com/grpc/grpc-node/blob/master/packages/proto-loader/test/descriptor_type_test.ts#L105-L109
