### ISSUE TITLE
Can't install grpc 1.8.4

### ISSUE THREAD

**Issue by koolkvd** [grpc/grpc-node#163]
I am trying to install Firebase-Admin which has a dependency of grpc 1.8.4

Whatever i try, it simply fails to install grpc with the following errors:

> grpc@1.8.4 install C:\Users\kusha\FirebaseWaitlistFunctions\functions\node_modules\grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp ERR! Tried to download(undefined): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.8.4/node-v59-win32-x64-unknown.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.8.4 and node@9.4.0 (node-v59 ABI, unknown) (falling back to source compile with node-gyp)
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Users\kusha\AppData\Local\Programs\Python\Python36", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\kusha\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\kusha\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Users\kusha\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:166:21)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\kusha\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--library=static_library" "--module=C:\\Users\\kusha\\FirebaseWaitlistFunctions\\functions\\node_modules\\grpc\\src\\node\\extension_binary\\node-v59-win32-x64-unknown\\grpc_node.node" "--module_name=grpc_node" "--module_path=C:\\Users\\kusha\\FirebaseWaitlistFunctions\\functions\\node_modules\\grpc\\src\\node\\extension_binary\\node-v59-win32-x64-unknown"
gyp ERR! cwd C:\Users\kusha\FirebaseWaitlistFunctions\functions\node_modules\grpc
gyp ERR! node -v v9.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\kusha\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --library=static_library --module=C:\Users\kusha\FirebaseWaitlistFunctions\functions\node_modules\grpc\src\node\extension_binary\node-v59-win32-x64-unknown\grpc_node.node --module_name=grpc_node --module_path=C:\Users\kusha\FirebaseWaitlistFunctions\functions\node_modules\grpc\src\node\extension_binary\node-v59-win32-x64-unknown' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\kusha\FirebaseWaitlistFunctions\functions\node_modules\grpc\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:160:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:943:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
node-pre-gyp ERR! System Windows_NT 10.0.15063
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\kusha\\FirebaseWaitlistFunctions\\functions\\node_modules\\grpc\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd C:\Users\kusha\FirebaseWaitlistFunctions\functions\node_modules\grpc
node-pre-gyp ERR! node -v v9.4.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\kusha\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --library=static_library --module=C:\Users\kusha\FirebaseWaitlistFunctions\functions\node_modules\grpc\src\node\extension_binary\node-v59-win32-x64-unknown\grpc_node.node --module_name=grpc_node --module_path=C:\Users\kusha\FirebaseWaitlistFunctions\functions\node_modules\grpc\src\node\extension_binary\node-v59-win32-x64-unknown' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.8.4 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grpc@1.8.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\kusha\AppData\Roaming\npm-cache\_logs\2018-01-31T18_13_58_440Z-debug.log

My OS is Windows 10.0.15063
Node version 9.4.0
npm version 5.6.0

looking at the error, i did install python 3.6.4, i set the PYTHON variable as it suggested but it still seems to not be able to detect it, i think its because of the python.EXE it's trying to find instead of a python.exe,
saw it in the logs while trying to install firebase-admin 5.8.2

Running python from cmd does get me into python console so the path is properly set.

i also tried, installing new node.js and got it up to the 9.4.0, updated npm with : npm install -g npm,
same error happens on trying to install firebase-tools, though this is an optional dependency there so it does install. Firebase-admin absolutely fails to get installed

I am not a Node.js developer and this is absolutely the first time i am even using npm or anything like it, please help me as i do need the firebase functions and stuff.

**Comment by koolkvd** [comment]
i also tried, installing new node.js and got it up to the 9.4.0, updated npm with : npm install -g npm,
same error happens on trying to install firebase-tools, though this is an optional dependency there so it does install. Firebase-admin absolutely fails to get installed

**Comment by nicolasnoble** [comment]
This exact package

```
node-pre-gyp ERR! Tried to download(undefined): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.8.4/node-v59-win32-x64-unknown.tar.gz
```

has been published since then:

```
$ wget 'https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.8.4/node-v59-win32-x64-unknown.tar.gz'
--2018-04-27 19:15:37--  https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.8.4/node-v59-win32-x64-unknown.tar.gz
Resolving storage.googleapis.com (storage.googleapis.com)... 216.58.205.16, 2a00:1450:4007:812::2010
Connecting to storage.googleapis.com (storage.googleapis.com)|216.58.205.16|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 957651 (935K) [application/x-tar]
Saving to: ‘node-v59-win32-x64-unknown.tar.gz’

node-v59-win32-x64-unknown.tar.gz    100%[=====================================================================>] 935.21K  --.-KB/s    in 0.02s

2018-04-27 19:15:38 (40.3 MB/s) - ‘node-v59-win32-x64-unknown.tar.gz’ saved [957651/957651]
```

**Comment by dev-assassin** [comment]
also, I got the same error.
How can I solve this problem?
please hint me any suggestions.
