### ISSUE TITLE
@grpc/grpc-js & deadline propagation

### ISSUE THREAD

**Issue by eyalpost** [grpc/grpc-node#1632]
### Problem description
When propagating deadlines, the minimal deadline should be used instead of taking parent deadline. 
Basically, [`getDeadline`](https://github.com/grpc/grpc-node/blob/ae2b64bd659a74adcca0c48d1cefc6aa252795cf/packages/grpc-js/src/call-stream.ts#L631) should be changed to take the min value between `this.options.deadline` and `this.options.parentCall.getDeadline()`

### Reproduction steps
https://github.com/eyalpost/grpc-js-min-deadline
Shows the difference between native grpc and grpc-js. Seems like native behavior is implemented [here](https://github.com/grpc/grpc/blob/27e1c1c/src/core/lib/surface/call.cc#L395)

**Comment by eyalpost** [comment]
@hugebdu FYI

**Comment by murgatroid99** [comment]
This is fixed in version 1.2.1.

**Comment by eyalpost** [comment]
Amazing! Thanks 🙏
