### ISSUE TITLE
Clarification on grpc-js vs grpc-web?

### ISSUE THREAD

**Issue by gavan1** [grpc/grpc-node#1637]
@murgatroid99 any basic examples with the release of grpc-js?

Thanks.

**Comment by murgatroid99** [comment]
`@grpc/grpc-js` is a reimplementation of the original Node `grpc` library purely in JavaScript, without the native addon that the original had. The [existing examples](https://github.com/grpc/grpc/tree/master/examples/node) have been modified to use grpc-js, though the README is a bit out of date.

grpc-web is a separate library that is intended to be used in browsers. It uses a different protocol that is compatible with browser JavaScript APIs. More information about it can be found in the [grpc-web repository](https://github.com/grpc/grpc-web).
