### ISSUE TITLE
HELP: How to establish new connection forcely when create more client with same params

### ISSUE THREAD

**Issue by zyf0330** [grpc/grpc-node#1642]
Need for client-side load balancing

**Comment by murgatroid99** [comment]
If you want a client to start connecting immediately without making a request, you can use the [`waitForReady`](https://grpc.github.io/grpc/node/grpc.Client.html#waitForReady__anchor) method. That will also notify you when a connection has been established.

I want to note that the gRPC library has its own built in client-side load balancing. What specifically are you trying to do? Maybe there's a simpler option.

**Comment by zyf0330** [comment]
I have aleady found that option `grpc.use_local_subchannel_pool`.
But what is gRPC own built in client-side load balancing that you said?

**Comment by murgatroid99** [comment]
If you have a DNS name that corresponds to multiple IP addresses, you can use the round robin load balancing policy (see https://github.com/grpc/grpc-node/issues/1307#issuecomment-601312421 for how to enable it). That will make the client connect to all of those addresses, and send requests to each of them in turn.

**Comment by zyf0330** [comment]
I use k8s service to export gRPC server, and real multiple backends are behind k8s service as k8s endpoint. So gRPC client can only resolve one backend address from k8s service name. So it seems that gRPC service config feature is not proper here
My strategy now is to establish new connection forcely whithin self implemented load balancing logic.
