### ISSUE TITLE
Customized Resolver does not working.

### ISSUE THREAD

**Issue by jc-lab** [grpc/grpc-node#1646]
### Problem description
I created and registered a resolver.
But I get the error "Error: 14 UNAVAILABLE: No connection established".

### Reproduction steps
```
class MyResolver implements Resolver {
  public constructor(private target: GrpcUri, private listener: ResolverListener, private channelOptions: ChannelOptions) {
    console.log(target);
    /*
OUTPUT : 
{
  scheme: 'myresolver',
  authority: undefined,
  path: 'custom.hostname:12345'
}
    */
  }

  public static getDefaultAuthority(target: GrpcUri): string {
    return target.path;
  }

  updateResolution(): void {
    this.listener.onSuccessfulResolution([{
      host: '127.1.2.3',
      port: 12345
    }], null, null, {});
  }
}

registerResolver('myresolver', MyResolver);


const client = new MyGrpcServiceClient('myresolver:custom.hostname:12345');
// ...
```

Error:
```
Error: 14 UNAVAILABLE: No connection established
    at Object.callErrorFromStatus (....\node_modules\@grpc\grpc-js\src\call.ts:81:24)
    at Object.onReceiveStatus (....\node_modules\@grpc\grpc-js\src\client.ts:334:36)
    at Object.onReceiveStatus (....\node_modules\@grpc\grpc-js\src\client-interceptors.ts:424:34)
    at Object.onReceiveStatus (....\node_modules\@grpc\grpc-js\src\client-interceptors.ts:387:48)
    at ....\node_modules\@grpc\grpc-js\src\call-stream.ts:243:24
    at processTicksAndRejections (internal/process/task_queues.js:75:11) {
  code: 14,
  details: 'No connection established',
  metadata: Metadata { internalRepr: Map {}, options: {} }
}
```

### Environment
 - OS name, version and architecture: Windows 10 amd64
 - Node version: v12.14.0.
 - Node installation method: msi installer
 - Package name and version: @grpc/grpc-js@1.2.2

**Comment by murgatroid99** [comment]
The first step to debugging this would be to run the client with the environment variables `GRPC_TRACE=all` and `GRPC_VERBOSITY=DEBUG`. That will tell us more specifically what is failing.

At first glance, the `127.1.2.3` address looks very weird. I think it is a valid loopback address, but it's very unusual to use a loopback address other than `127.0.0.1`. Why did you choose that address?

**Comment by jc-lab** [comment]
The reason was that `DNS Name` was not given as the Alt Name when creating the certificate.
It was my mistake. Thank you.
