### ISSUE TITLE
Export createPackageDefinition

### ISSUE THREAD

**Issue by entropitor** [grpc/grpc-node#1647]
### Is your feature request related to a problem? Please describe.
Right now the proto file is parsed at run time. This works okay in some scenario's but for e.g. bundling everything in one file, this approach doesn't work

### Describe the solution you'd like
https://github.com/protobufjs/protobuf.js/blob/master/README.md#pbjs-for-javascript PbJS supports compiling proto files into json objects, I thought it might be useful to export `createPackageDefinition` so we could load a json file (which can be inlined in the bundle as well) and then call createPackageDefinition on that.

### Describe alternatives you've considered
Support a compiler for the grpc-loader package as well but that would be more work

**Comment by murgatroid99** [comment]
You can load that JSON file using `load` or `loadSync`.

Please see #1627, #1535, #807, and #550 for explanations of why we will not export `createPackageDefinition`.

**Comment by tatemz** [comment]
@entropitor this comment may help: https://github.com/grpc/grpc-node/issues/1627#issuecomment-742131217

**Comment by entropitor** [comment]
I believe https://github.com/grpc/grpc-node/pull/1635 could indeed solve the issue but it's not yet releases as far as I can tell
