### ISSUE TITLE
Restart/resume on error

### ISSUE THREAD

**Issue by christopheSeeka** [grpc/grpc-node#1656]
Hello,

I was wondering if there is an option to resume/restart the gRPC stream on error?

Here a simplified example of my code in client.js:

```
const packageDefinition = protoLoader.loadSync(PROTO_PATH, options);
const waves_events = grpc.loadPackageDefinition(packageDefinition).waves.events.grpc; 
const gRPCclient = new waves_events.BlockchainUpdatesApi("grpc server host", grpc.credentials.createInsecure());

let initSync = async function(){
  let call = gRPCclient.Subscribe();
  call.on("data", async function(res){
   // id do stuff with data
  })
  call.on('error', (err) => {
    console.log('gRPC stream error')
    console.log(err)
    initSync()
  })
  call.on('end', (err) => {
    console.log('gRPC stream ended')
  })
}

initSync ()
```

I start it with "node client.js" and it works well and receive the flux of events but if i get an error, it stop and even if i call initSync() again from inside call.on("error"... it doesnt resume/restart the process. Guess i'm missing something, if someone can help me please.

**Comment by murgatroid99** [comment]
Which gRPC library are you using, and what version of Node are you running this code on?

**Comment by christopheSeeka** [comment]
Hello, 

Thank you for the reply, im using Node v12.15.0 and for gRPC lib:

```
const grpc = require('grpc');
const protoLoader = require('@grpc/proto-loader');
```

Should i use grpc-js instead? like:

 _const grpc = require('@grpc/grpc-js');_ instead of _const grpc = require('grpc');_

Pretty new to gRPC here :)

**Comment by murgatroid99** [comment]
Yes, I recommend using `@grpc/grpc-js` instead of `grpc`, and dropping the dependency on `grpc`. You should probably also get a more recent version of `@grpc/proto-loader`; the latest version is 0.5.x.

If you are still having this issue with grpc-js, I suggest running with the environment variables `GRPC_TRACE=all` and `GRPC_VERBOSITY=DEBUG`, and share the output of a run that encounters that issue.

**Comment by christopheSeeka** [comment]
Thank you very much for the answer, will test all that and come back if needed.

**Comment by christopheSeeka** [comment]
> Yes, I recommend using `@grpc/grpc-js` instead of `grpc`, and dropping the dependency on `grpc`. You should probably also get a more recent version of `@grpc/proto-loader`; the latest version is 0.5.x.
> 
> If you are still having this issue with grpc-js, I suggest running with the environment variables `GRPC_TRACE=all` and `GRPC_VERBOSITY=DEBUG`, and share the output of a run that encounters that issue.

I got the error again and my gRPC client ended:

` Error: 13 INTERNAL: Received RST_STREAM with code 2 (Internal server error)`

Is this a problem from gRPC server? How can i make my gRPC resume or reconnect when this happen instead of everyting stopping?

**Comment by christopheSeeka** [comment]
Hello, today the stream ended again with the following error:

 Error: 14 UNAVAILABLE: Connection dropped

What the best automatic way to relaunch it when this happen?

**Comment by murgatroid99** [comment]
Are you saying that the call to `initSync()` from within the error handler is still not working after you switched to grpc-js? If so, I suggest that you run the code with the environment variables `GRPC_TRACE=all` and `GRPC_VERBOSITY=DEBUG`, and share the output of a run that encounters that issue.

**Comment by christopheSeeka** [comment]
Yes for some reason it is not called after switching to grpc-js and i cant figure why.

GRPC_TRACE=all and GRPC_VERBOSITY=DEBUG arent for the gRPC server side? 
Because in my case i only develop the gRPC client that subscribe to a gRPC server to receive the stream but i don't have hand on the gRPC server.

If not, can i just put these:

GRPC_TRACE=all
GRPC_VERBOSITY=DEBUG

in the .env of my gRPC client and restart?

**Comment by christopheSeeka** [comment]
Is there a way i can simulate/trigger the end event? To do some testing locally

**Comment by christopheSeeka** [comment]
It seem to be ok now, i'll monitor and update if anything again, thanks a lot for your time :)
