### ISSUE TITLE
@grpc/proto-loader pre version has bad semver order

### ISSUE THREAD

**Issue by tdzl2003** [grpc/grpc-node#1657]
Semver "0.6.0-pre9" is higher then "0.6.0-pre17", which causing yarn using "0.6.0-pre9" instead of "0.6.0-pre17" when requesting `^0.6.0-pre17`

see also: https://semvercompare.azurewebsites.net/?version=0.6.0-pre17&version=0.6.0-pre9

in yarn.lock:

```
"@grpc/proto-loader@^0.6.0-pre17":
  version "0.6.0-pre9"
```

One way is using BUILDMETA to order multiple pre version: `0.6.0-pre.17` is higher than `0.6.0-pre.9`, but currently they are all lower than `0.6.0-pre9`……

Maybe skip the patch version `0.6.0` and use `0.6.1-pre.18` or use a higher prerelease name like `0.6.0-rc.18` is better?

**Comment by murgatroid99** [comment]
I think this issue is likely obsolete, now that we have reached version 0.7.9.
