### ISSUE TITLE
./node_modules/@grpc/grpc-js/build/src/server.js Module not found: Can't resolve 'http2' in 'C:\Users\admin\Desktop\stock.tao.ui\node_modules\@grpc\grpc-js\build\src'

### ISSUE THREAD

**Issue by zqxul** [grpc/grpc-node#1677]
http2 is declare at http2.d.ts , but it doesnt seems to work
![image](https://user-images.githubusercontent.com/25364252/106256473-4b999d00-6256-11eb-83a4-6fc20532f3e4.png)
![image](https://user-images.githubusercontent.com/25364252/106256534-5c4a1300-6256-11eb-8d95-e2917bf141d4.png)

**Comment by murgatroid99** [comment]
The `package.json` file declares which Node versions this library works with, specifically `^8.13.0 || >=10.10.0`. If you want to use this library, you need to use one of those versions of Node.

**Comment by zqxul** [comment]
Thanks you for your patiently reply ,but I
am now using protobufferjs + grpc-web🙂
发自我的iPhone

在 2021年1月30日，02:32，Michael Lumish <notifications@github.com> 写道：

﻿

The package.json file declares which Node versions this library works with, specifically ^8.13.0 || >=10.10.0. If you want to use this library, you need to use one of those versions of Node.
