### ISSUE TITLE
Issue with repeated float

### ISSUE THREAD

**Issue by konstantinblaesi** [grpc/grpc-node#1691]
### Problem description
Client fails to read the response when using repeated floats in a TypeScript/NodeJS gRPC project

### Reproduction steps

Reproducible using https://github.com/konstantinblaesi/grpc-issue

### Environment
 - Linux Fedora 33 amd64
 - node 14.15.4
 - dnf package manager
 - clang 11.0.0, gcc 10.2.1
 - @grpc/grpc-js@1.2.7

### Additional context
Using [1,2,3] as value for a repeated float field causes a client error
Using [] works but is obviously not useful
https://github.com/konstantinblaesi/grpc-issue/blob/master/src/server.ts#L14

```
> ts-node src/client.ts

Calling DemoClient.doDemo
Error: 13 INTERNAL: Response message parsing error: reader.isDelimited is not a function
    at Object.callErrorFromStatus (/home/konstantin/Documents/Projects/grpc-issue/node_modules/@grpc/grpc-js/src/call.ts:81:24)
    at Object.onReceiveStatus (/home/konstantin/Documents/Projects/grpc-issue/node_modules/@grpc/grpc-js/src/client.ts:334:36)
    at Object.onReceiveStatus (/home/konstantin/Documents/Projects/grpc-issue/node_modules/@grpc/grpc-js/src/client-interceptors.ts:426:34)
    at Object.onReceiveStatus (/home/konstantin/Documents/Projects/grpc-issue/node_modules/@grpc/grpc-js/src/client-interceptors.ts:387:48)
    at /home/konstantin/Documents/Projects/grpc-issue/node_modules/@grpc/grpc-js/src/call-stream.ts:249:24
    at processTicksAndRejections (internal/process/task_queues.js:75:11) {
  code: 13,
  details: 'Response message parsing error: reader.isDelimited is not a function',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} }
}
```

**Comment by murgatroid99** [comment]
That code doesn't seem to have a dependency on `google-protobuf`, but the generated code requires it. What happens if you add that?

**Comment by konstantinblaesi** [comment]
@murgatroid99 I added it and it's working now. But I have two versions installed now, previously I only had the one pulled in by grpc_tools_node_protoc_ts
```
$ npm ls google-protobuf
grpc-issue@1.0.0 /home/konstantin/Documents/Projects/grpc-issue
├── google-protobuf@3.15.0-rc.1 
└─┬ grpc_tools_node_protoc_ts@5.1.1
  └── google-protobuf@3.12.4 
```

**Comment by konstantinblaesi** [comment]
3.14.0 also works

```
$ npm ls google-protobuf
grpc-issue@1.0.0 /home/konstantin/Documents/Projects/grpc-issue
├── google-protobuf@3.14.0 
└─┬ grpc_tools_node_protoc_ts@5.1.1
  └── google-protobuf@3.12.4
```

**Comment by murgatroid99** [comment]
Multiple versions of a dependency is fine. It happens all the time with Node.

It looks like this problem is resolved so I'll close this issue.

**Comment by ccocheci** [comment]
If you get the error "Response message parsing error: reader.isDelimited is not a function" and you do have the google-protobuf dependency, just update the google-protobuf version to the latest.
