### ISSUE TITLE
grpc@1.24.1 missing

### ISSUE THREAD

**Issue by cauchyp** [grpc/grpc-node#1692]
I need a specific dependency on my projet, and I can't find the related package on version 1.24.1.
Is it normal ?

Thank you

**Comment by murgatroid99** [comment]
When you say that you can't find it, what do you mean exactly? It's definitely on npm, here: https://www.npmjs.com/package/grpc/v/1.24.1.

**Comment by cauchyp** [comment]
I mean not on github releases
https://github.com/grpc/grpc-node/releases/tag/grpc%401.24.1

**Comment by murgatroid99** [comment]
You're right. It's not there. You can still get it from npm.
