### ISSUE TITLE
Deserialize buffer

### ISSUE THREAD

**Issue by James2516** [grpc/grpc-node#1694]
I have a Kafka message containing a grpc message as a buffer.
How do I deserialize this buffer (byte array) into a JSON object?

I cannot find the `deserialize` method in this package: https://grpc.github.io/grpc/node/grpc.html#~deserialize__anchor

I have tried the following but it errored with "invalid wire type 7 at offset..."
```
const packageDef = grpc.loadPackageDefinition(...);
packageDef.namespace.Results.responseDeserialize(kafkaMessageBuffer);
```

Perhaps it's using string deserialization instead of byte array deserialization? How do I change that?

**Comment by murgatroid99** [comment]
gRPC is a network protocol, not a message format. I am guessing that when you say "grpc message", you are referring to a protobuf message. If you are just trying to deserialize a protobuf message, you should use a protobuf library directly. If you are trying to make or handle gRPC requests, can you provide more details about that?
