### ISSUE TITLE
Upgrade `grpc-js` `google-auth-library` version

### ISSUE THREAD

**Issue by bojeil-google** [grpc/grpc-node#1695]
`google-auth-library` version in `grpc-js` should be upgraded to `^7.0.2` to support workload identity federation.

Latest version of `google-gax` has the latest auth library:
https://github.com/googleapis/gax-nodejs/releases/tag/v2.10.3

but has a dependency on `@grpc/grpc-js`:

This means that 2 versions of the library will be pulled in.

**Comment by yinzara** [comment]
When this is updated, can we make the version range be:
>=7.0.2
instead of 
^7.0.2


That will prevent the duplicate versions of the library being pulled.

**Comment by murgatroid99** [comment]
As of version 1.3.0, `google-auth-library` is no longer a dependency of `@grpc/grpc-js`.
