### ISSUE TITLE
cant access map elements when using grpc/grpc-js

### ISSUE THREAD

**Issue by AmichaiGeler** [grpc/grpc-node#1700]
hi 
im using @grpc/grpc-js version 1.2.8 and @grpc/proto-loader version 0.5.6
node version 14.14.0
in my proto file i have this 
message DeviceInfo {
    string uuid = 1;               //device UUID
    string kernelVersion = 2;      // device kerenel firmware version
    string ubootVersion = 3;       // device FIT firmware version
    string busId= 4;               // busID of the device
    string driverVersion = 5;      // driver version
    string serialNumber = 6;       // serial number
    string pcb = 7;                // PCB version
    string pcbAssembly = 8;        // PCB assembly version
    uint32 pcieLinkGeneration = 9; // PCIe link generation
}
message HlmlDevicesInfoResponse{
    map<uint64,DeviceInfo> deviceToDeviceInfo = 1;
}
over client side to get the map im doing response.deviceToDeviceInfo 
and now i want to get the keys or values or access some element and im keep getting an error 
that those are not functions 
im using it like this  response.deviceToDeviceInfo.keys()
can you please help me ?

**Comment by murgatroid99** [comment]
The protobuf `map` type is represented as a plain object mapping strings to values, not a JavaScript `Map`.

**Comment by AmichaiGeler** [comment]
hi thx 
can you please write an example for how can i iterate such object?

**Comment by murgatroid99** [comment]
```js
for (const key of Object.keys(response.deviceToDeviceInfo) {
  const value = response.deviceToDeviceInfo[key];
  // Further processing
}
```

**Comment by AmichaiGeler** [comment]
thx!!
