### ISSUE TITLE
move @types to devDependencies

### ISSUE THREAD

**Issue by zivni** [grpc/grpc-node#1711]
package.json in grpc-js has @types/node in the dependencies section but I think it should be in the devDependencies section, as this is used for compile of the typescipt to js.

I installed in my project a library (newrelic) that uses this library and I got typescript errors as the typing doesn't match the version I use.

**Comment by murgatroid99** [comment]
The `.d.ts` files have types that depend on types in `@types/node`, so it needs to be a regular dependency. Which library are you using? We recently changed the dependency in `@grpc/grpc-js` to have a broader range to avoid conflicts like that.
