### ISSUE TITLE
@grpc/grpc-js cannot get receivedMessage when gzip is enabled in nginx

### ISSUE THREAD

**Issue by bbi8** [grpc/grpc-node#1719]
### Problem description
When nginx enables gzip, grpc response receivedMessage is always null
When nginx closes gzip, grpc response receivedMessage is normal 

### Reproduction steps
nginx.conf:
...
    gzip on;
    gzip_vary on;
    gzip_types *;
    gzip_proxied  expired no-cache no-store private no_last_modified no_etag auth;
...

src/client-interceptors.ts
... line 423
  if (!receivedMessage) {
      listener?.onReceiveMessage?.(null);
  }
...

### Environment
 - windows 10
 - Node version v14.x
 - Node installation method [e.g. nvm]
 - If applicable, compiler version [e.g. clang 3.8.0-2ubuntu4]
 - @grpc/grpc-js@1.2.11

**Comment by murgatroid99** [comment]
If nginx's gzip compression does not work with gRPC, I recommend disabling nginx's gzip compression with gRPC. gRPC uses the content type `application/grpc`, if that helps configure it more specifically.

**Comment by bbi8** [comment]
> If nginx's gzip compression does not work with gRPC, I recommend disabling nginx's gzip compression with gRPC. gRPC uses the content type `application/grpc`, if that helps configure it more specifically.

I just switched from grpc@1.24.6 to @grpc/grpc-js. grpc@1.24.6 can work in nginx with gzip enabled, but grpc@1.24.6 does not support TLSv1.3. Hope to fix @grpc/grpc-js nginx gzip support

**Comment by murgatroid99** [comment]
I just published a patch in `@grpc/grpc-js` version 1.2.12 that should fix the interaction with servers (and proxies) that support gzip. Can you try it out?

**Comment by bbi8** [comment]
> I just published a patch in `@grpc/grpc-js` version 1.2.12 that should fix the interaction with servers (and proxies) that support gzip. Can you try it out?

Now @grpc/grpc-js@1.2.12 can work normally in nginx with gzip enabled, thanks
