### ISSUE TITLE
Error: Request had invalid authentication credentials

### ISSUE THREAD

**Issue by nabulaer** [grpc/grpc-node#172]
nodejs 6.10.3
on GKE (kubernetes)
got few random exceptions and then stopped.

unhandledRejection { Error: Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
    at /usr/src/app/node_modules/google-gax/node_modules/grpc/src/client.js:554:15

**Comment by murgatroid99** [comment]
That error is being sent by the server. Did you follow the link and do what it says?

**Comment by nabulaer** [comment]
The link is about adding the google sign in to a web site for a user to use his google account to sign in. This is not my case. I use nodejs google logging to add logs to stackdriver. The google logging is dependent on this package for the requests. When running on a GKE or on a local gcloude authenticated it works. But on the GKE there this exceptions not all the time,but some few times out of all the logs that get written. If it was a real authentication problem no logs would have been written...
The nodejs server is an api server so there is no client html interface for performing a user login.

**Comment by murgatroid99** [comment]
This is not a gRPC issue. This is between the client application and the server application.
