### ISSUE TITLE
Error on GCF: Could not refresh access token

### ISSUE THREAD

**Issue by schmidt-sebastian** [grpc/grpc-node#173]
Last Wednesday (Jan 31), we pushed a new release of google-gax that pulled in 1.8.x GRPC for the first time. We eventually reverted back to GRPC 1.7.x.

Over the course of the day, we got multiple customer reports about Firestore errors on GCF as such:

Error: 16 UNAUTHENTICATED: Getting metadata from plugin failed with error: Could not refresh access token. 
at createStatusError (/user_code/node_modules/firebase-admin/node_modules/grpc/src/client.js:65:15) 
at ClientReadableStream._emitStatusIfDone (/user_code/node_modules/firebase-admin/node_modules/grpc/src/client.js:271:19) 
at ClientReadableStream._receiveStatus (/user_code/node_modules/firebase-admin/node_modules/grpc/src/client.js:249:8) 
at /user_code/node_modules/firebase-admin/node_modules/grpc/src/client.js:715:12

https://stackoverflow.com/questions/48550151/after-deploy-cloud-functions-error-could-not-refresh-access-token

https://github.com/firebase/firebase-functions/issues/121 

Note: We are still investigating other possible root causes, such as the release of https://github.com/google/google-auth-library-nodejs/releases that happened at the same time. We believe that we did not include the affected versions we are pegged at 0.x via common-grpc.

**Comment by murgatroid99** [comment]
This may actually be fixed (in a sense) in version 1.9. We made a change to auth errors so that they are now reported as `UNAVAILABLE` instead of `UNAUTHENTICATED`. Since `UNAVAILABLE` errors are retried, that may fix that problem.

**Comment by nicolasnoble** [comment]
Was this one solved in 1.9 ?

**Comment by schmidt-sebastian** [comment]
We haven't seen any reports since the upgrade.
