### ISSUE TITLE
Cannot bind/bindAsync to `::` or `::1`

### ISSUE THREAD

**Issue by CMCDragonkai** [grpc/grpc-node#1736]
In grpc-js, the server cannot be bound to `::` nor `::1` nor any of the long form `0:0:0:0:0:0:0:1`.

It says that the `Name resolution failed for target dns:0:0:0:0:0:0:0:1:55557`. 

I thought at least it would be possible to bind specifically to an ipv6 address.

**Comment by CMCDragonkai** [comment]
Found out that you have to use `[::]` or `[::1`] because of the address format.

**Comment by murgatroid99** [comment]
Yes, when using colons to separate both components of the address and to separate the address from the port, the square brackets are needed to indicate which is which. If you want to bind to the default port (443), you can provide the IPv6 address without brackets.
