### ISSUE TITLE
when run "build " got an error,  'fs' is a internal module ,why ?

### ISSUE THREAD

**Issue by RobinYang11** [grpc/grpc-node#1743]
ModuleNotFoundError: Module not found: Error: Can't resolve 'fs' in 'F:\workdir\panzi-material-web\node_modules\@grpc\proto-loader\build\src'

**Comment by nicolasnoble** [comment]
Please make a proper bug report: https://github.com/grpc/grpc-node/blob/master/.github/ISSUE_TEMPLATE/bug_report.md
