### ISSUE TITLE
Internal grpc status codes cause a log statement

### ISSUE THREAD

**Issue by jon-whit** [grpc/grpc-node#1748]
Right now the `grpc` package logs an error if the error code is equal to a status code 13 (grpc status INTERNAL).
https://github.com/grpc/grpc-node/blob/grpc%401.24.x/packages/grpc-native-core/src/server.js#L59

If the server is intentionally returning a status code 13 back to the client (e.g. if the database backing the server is temporarily experiencing downtime), I'd like it to be the responsibility of the server to log those errors. Getting a status code 13 error printed out of this library is non-ideal. Errors logged out of this library should be specific to the grpc transport and the protocol implementation as bytes go out over the wire. It should have nothing to do with the server invoked callback.

In general I'd like to see the error logs reworked to only log protocol specific errors coming out of the library. But at minimum I'd hope we can remove the line linked above. It took me longer than I would have liked to find out that the library was logging application specific errors..

**Comment by murgatroid99** [comment]
This has been fixed in version 1.24.7.
