### ISSUE TITLE
@grpc/proto-loader permissive vs restrictive behavior is unclear

### ISSUE THREAD

**Issue by JrSchild** [grpc/grpc-node#1758]
### Problem description
It is unclear to me what the behavior of permissive and restrictive should represent. Currently two interfaces per message are generated, one with a clear name and one post-fixed with `__Output`. Personally I am not very interested in a type that adds `'string'` for numbers.

Ideally it would be nice to see the rationale behind this documented, why and when should you use which. Any clarification would be greatly appreciated!

```typescript
export interface Test {
  'value'?: (number | string);
}

export interface Test__Output {
  'value'?: (number);
}
```

**Comment by murgatroid99** [comment]
The permissive interface describes the type of objects that can be passed in to gRPC (specifically, in to the protobuf serializer) to be sent as messages. The restrictive interface describes the type of objects that will be output by gRPC (specifically, by the protobuf deserializer) to represent received messages. The various generated types for services demonstrate this convention.

**Comment by JrSchild** [comment]
Okay that makes sense. The naming got a little confusing to me. If I define a message as a request and I have to add `__Output` to it to get the strict form.
Thanks for clarifying.
