### ISSUE TITLE
Can't build on Windows, node 16

### ISSUE THREAD

**Issue by ElDavoo** [grpc/grpc-node#1762]
Hi, I can't install this package on Windows with node 16. Please advice. Thanks

[2021-04-25T16_45_28_456Z-debug.log](https://github.com/grpc/grpc-node/files/6372467/2021-04-25T16_45_28_456Z-debug.log)

**Comment by aladdin-add** [comment]
same issue on macOS Big Sur.

**Comment by murgatroid99** [comment]
Node 16 support is in progress in #1760,

**Comment by murgatroid99** [comment]
Node 16 support is available in version 1.24.9.
