### ISSUE TITLE
Version 1.24.8 of grpc and updated node-pre-gyp name

### ISSUE THREAD

**Issue by wesleytodd** [grpc/grpc-node#1773]
### Problem description

```Cannot find module 'node-pre-gyp/lib/pre-binding'```

The commit [here](https://github.com/grpc/grpc-node/commit/c6525d2ab0f7962638d539ea59523f13d6502a63) updates the [installed dep to `@mapbox/node-pre-gyp`](https://github.com/grpc/grpc-node/blob/c6525d2ab0f7962638d539ea59523f13d6502a63/packages/grpc-native-core/package.json#L29) but forgot to update the `require` statement [here](https://github.com/grpc/grpc-node/blob/c6525d2ab0f7962638d539ea59523f13d6502a63/packages/grpc-native-core/src/grpc_extension.js#L26).  

### Reproduction steps

n/a

### Environment

n/a

**Comment by HendrikFreund85** [comment]
Yes for me too. Failing after installing Version 1.24.8 and
`const grpc = require("grpc") `
results in
Cannot find module 'node-pre-gyp/lib/pre-binding'

**Comment by blayet** [comment]
Same problem here!

**Comment by murgatroid99** [comment]
The fix for this is in #1775. I'll try to publish a new version today.

**Comment by murgatroid99** [comment]
The fix for this is now out in version 1.24.9.
