### ISSUE TITLE
Usage Docs Not Clear

### ISSUE THREAD

**Issue by hashweather** [grpc/grpc-node#1774]
I am studying the examples under the static code gen for node and it's not really clear how the Service Code was generated.

I noticed that inside the `helloworld_grpc_pb.js` file we have the following lines of code

```

// The greeting service definition.
var GreeterService = exports.GreeterService = {
  // Sends a greeting
sayHello: {
    path: '/helloworld.Greeter/SayHello',
    requestStream: false,
    responseStream: false,
    requestType: helloworld_pb.HelloRequest,
    responseType: helloworld_pb.HelloReply,
    requestSerialize: serialize_helloworld_HelloRequest,
    requestDeserialize: deserialize_helloworld_HelloRequest,
    responseSerialize: serialize_helloworld_HelloReply,
    responseDeserialize: deserialize_helloworld_HelloReply,
  },
};

exports.GreeterClient = grpc.makeGenericClientConstructor(GreeterService);
```
 Was the above line of code also generated by the grpc tool or hard coded.

If Generated by the `grpc_tool`, how was it done coz my generated codes don't appear like the above, only the messages are getting generated.

Here is the command I used
`grpc_tools_node_protoc --js_out=import_style=commonjs,binary:libs --grpc_out=grpc_js: protos/location.proto`

Where `protos/location.proto` is where my proto file is and `libs` is the folder I want the generated service and message codes to be stored in

Any help would be really appreciated as I've exceeded some time limits coz of this issue. Thanks in advance.

**Comment by murgatroid99** [comment]
Your `--grpc_out` argument is incomplete. You need to provide a path after the colon to say where the service files should be output. In this case you probably want `libs` to put it in the same place as the generated message files.

**Comment by hashweather** [comment]
Your recommendation isn't helpful at all. Can you give an example command, please?

**Comment by hashweather** [comment]
> Your `--grpc_out` argument is incomplete. You need to provide a path after the colon to say where the service files should be output. In this case you probably want `libs` to put it in the same place as the generated message files.

Does that mean I need to remove the libs after the binary line, can you give an example?

**Comment by murgatroid99** [comment]
Your command should look like this:

```
grpc_tools_node_protoc --js_out=import_style=commonjs,binary:libs --grpc_out=grpc_js:libs protos/location.proto
```

I added `libs` after the colon in the `--grpc_out` argument.

**Comment by hashweather** [comment]
Wow! You are the Boss! That worked like a Charm!! Thanks alot.

**Comment by hashweather** [comment]
But, It's creating different files for different messages. The examples weren't like that though.

How can I force all the messages to be compiled to a single file just like in the example

I am currently having over four different message files. That's weird.

**Comment by hashweather** [comment]
Look at this:

```
syntax = "proto3";

package location;

enum LocationTarget{
    CUSTOMER = 0;
    RIDER = 1;
}

message LocationUpdateRequest{
    AuthParams authParams = 1;
    LocationTarget locationUpdateTarget = 2;
    Location location = 3;
}

message LocationQueryRequest{
    AuthParams authParams = 1;
    LocationTarget locationQueryTarget = 2;
    string targetId = 3;
}

message LocationDataResponse{
    int32 statusCode = 1;
    Location location = 2;
}

message Location{
     double longitude = 3;
     double latitude = 4;
}

message AuthParams{
    string apiKey = 1;
}

service LocationManager{
    rpc updateLocation(LocationUpdateRequest) returns (LocationDataResponse);
    rpc queryLocation(LocationQueryRequest) returns (stream LocationDataResponse);
}
```

When I compiled the above with the command I was expecting just two files. One is the Server Code and the Other should be the Messages Compiled file. But instead I am getting 6 files plus the Server Code.

How can I prevent that? 

The example docs weren't like that.
