### ISSUE TITLE
Working with Multiple Services located in different Files

### ISSUE THREAD

**Issue by hashweather** [grpc/grpc-node#1777]
I am currently looking at the dynamic code gen samples for node and certain things are not quite clear.

Imagine I have two services sitting in two different proto files how do I connect to those services?

The samples only showed one Service which is the greeter service and connected to it as below:

```
var client = new hello_proto.Greeter(target,
    grpc.credentials.createInsecure());
  var user;
  if (argv._.length > 0) {
    user = argv._[0];
  } else {
    user = 'world';
  }
  client.sayHello({ name: user }, function (err, response) {
    console.log('Greeting:', response.message);
  });
  client.sayHelloAgain({ name: 'you' }, function (err, response) {
    console.log('Greeting: ', response.message);
  });
```

Now Imagine, there is another service do I still create another client like below?

```
var client2 = new hello_proto.AnotherGreeter(target,
    grpc.credentials.createInsecure());
  var user;
  if (argv._.length > 0) {
    user = argv._[0];
  } else {
    user = 'world';
  }
  client2 .sayHello({ name: user }, function (err, response) {
    console.log('Greeting:', response.message);
  });
  client2 .sayHelloAgain({ name: 'you' }, function (err, response) {
    console.log('Greeting: ', response.message);
  });
```

Is the above realistic? If not, what is the recommended way to work with multiple services sitting on different proto files.

Thanks.

**Comment by nicolasnoble** [comment]
Yes ? Aside from your first line that'd need to be the other filename containing your other service, but that's the gist. I'm not sure I see the problem. The example is for 1, but easily extends for n.

**Comment by hashweather** [comment]
Alright.Thanks
