### ISSUE TITLE
Static Code Generation Unclarity

### ISSUE THREAD

**Issue by hashweather** [grpc/grpc-node#1779]
I really want to use gRPC but the static code generation technique isn't clear.

How were the `helloworld_pb` and `helloworld_grpc_pb` files generated and called as below

```
var messages = require('./helloworld_pb');
var services = require('./helloworld_grpc_pb');
```

The command isn't clear. When I used the command, I am getting only the messages generated and the service files aren't no where to be found.

Can someone help me with a straight forward command to generate this client libraries, please?

Imagine I have the following IDL

```
syntax = "proto3";

package location;

enum LocationTarget{
    CUSTOMER = 0;
    RIDER = 1;
}

message LocationUpdateRequest{
    AuthParams authParams = 1;
    LocationTarget locationUpdateTarget = 2;
    Location location = 3;
}

message LocationQueryRequest{
    AuthParams authParams = 1;
    LocationTarget locationQueryTarget = 2;
    string targetId = 3;
}

message LocationDataResponse{
    int32 statusCode = 1;
    Location location = 2;
}

message Location{
     double longitude = 3;
     double latitude = 4;
}

message AuthParams{
    string apiKey = 1;
}

service LocationManager{
    rpc updateLocation(LocationUpdateRequest) returns (LocationDataResponse);
    rpc queryLocation(LocationQueryRequest) returns (stream LocationDataResponse);
}
```
How can I generate the gRPC Server and Client Libraries for NodeJS 
I will really appreciate.

**Comment by murgatroid99** [comment]
Did you make the changes suggested in your other issue (#1774)?

**Comment by hashweather** [comment]
Yea, I did it didn't work. Can you elaborate with the command for that?
