### ISSUE TITLE
Calls in GRPC fail when passed options is undefined

### ISSUE THREAD

**Issue by connor4312** [grpc/grpc-node#178]
Changes introduced in https://github.com/grpc/grpc-node/pull/162 cause calls to fail if the call options are undefined, such as in [this call](https://github.com/mixer/etcd3/blob/master/src/connection-pool.ts#L40).  This resulted in [significant regressions](https://github.com/mixer/etcd3/issues/59) in many scenarios.

**Comment by murgatroid99** [comment]
Sorry about that. I didn't realize that `undefined` was accepted before. We'll publish a bug fix soon.

**Comment by murgatroid99** [comment]
I have published version 1.9.1, which includes a fix for this issue.

**Comment by connor4312** [comment]
Thank you!
