### ISSUE TITLE
@grpc/grpc-js doesn't support yarn2 pnp

### ISSUE THREAD

**Issue by Wetinee** [grpc/grpc-node#1798]
### Problem description
when using yarn2, set `nodeLinker: pnp` in `.yarnrc.yml`.
Then run the script, it will raise  error : 

`Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@grpc/grpc-js' imported from xxxx`
`Did you mean to import @grpc-grpc-js-npm-1.3.2-0e02c36ae3-39cab06165.zip/node_modules/@grpc/grpc-js/build/src/index.js?`

### Reproduction steps
As long as it is set to be `nodeLinker: pnp` in `.yarnrc.yml`, the problem exists.

### Environment
 - MacOS 11.3.1
 - Node.js v16.1.0.
 - @grpc/grpc-js@1.3.2

### Additional context
when  setting it to be : `nodeLinker: node_modules`, the error no longer raises.

**Comment by murgatroid99** [comment]
I suggest filing a bug with yarn with this information. They should at least have a better idea of how to interpret that error message.

**Comment by merceyz** [comment]
That looks like an error Node throws when you're using ESM and Yarn PnP, in which case I'll point you to https://github.com/yarnpkg/berry/issues/638

**Comment by Wetinee** [comment]
Thx! I’ll go see it there.
