### ISSUE TITLE
grpc-node: @grpc/js-core example needed

### ISSUE THREAD

**Issue by neogeno** [grpc/grpc-node#180]
@murgatroid99 Please help provide the correct way to call a GRPC service using the native Javascript library with :
- macaroon authentication
- ssl connections. 
- reading .proto file in current directory

My current code doesn't work.

 `var grpc = require('@grpc/js-core');
var fs = require("fs");
var protobuf = require('protocol-buffers');
var proto = require('grpc');

//Load Certificate and Auth macaroon
var lndCert = fs.readFileSync("/Users/xxx/Library/Application Support/Lnd/tls.cert");
var macfile = fs.readFileSync("/Users/xxx/Library/Application Support/Lnd/admin.macaroon");
var macaroon = macfile.toString('hex');
let metadata = new grpc.Metadata();
metadata.add('macaroon', macaroon);
let macaroonCreds = grpc.CallCredentials.createFromMetadataGenerator((params, callback) =>
    callback(null, metadata)
);
var sslCreds = grpc.ChannelCredentials.createSsl(lndCert);
var allCreds = sslCreds.compose(macaroonCreds);
var lnrpcDescriptor = grpc.load("rpc.proto");
var lnrpc = lnrpcDescriptor.lnrpc;
var lightning = new grpc.Client('https://10.100.0.212:10001', allCreds);
lnrpc.getInfo({}, function(err, response) {
    console.log('GetInfo:', response);
});

 
`

**Comment by murgatroid99** [comment]
Work on that library is still ongoing, and what you found on NPM is an earlier version that was published for our own testing. In addition, it is intended to be an internal implementation package, and it should not be used directly.

**Comment by nicolasnoble** [comment]
This is irrelevant - package is only internal, and is superseded by `@grpc/grpc-js` anyway. Closing this one.
