### ISSUE TITLE
Client streaming emit error to the server

### ISSUE THREAD

**Issue by CMCDragonkai** [grpc/grpc-node#1800]
I found that I can do `stream.emit('error', status)` from the server and the client will catch it.

However if I try to do the `stream.emit('error', status);` from the client side, the server never receives the error event from the client. In fact the client side just hangs, it never completes the `emit` procedure.

Instead it later says `Unhandled error` on the client side.

How should client streams emit errors to the server?

Does it even make sense to send errors from client to server?

**Comment by murgatroid99** [comment]
There is no mechanism within gRPC for sending complex errors from the client to the server. You can cancel a request, which sends a cancellation message to the server, but that doesn't have any details. If you need to send more error information than that from the client, you should make it part of the message that the client sends, and then have the server application code handle it.
