### ISSUE TITLE
Several tests timeout consistently under emulated aarch64 linux test suite 

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc-node#1801]
Several tests (it seems it's almost always the same tests) report "Timeout of 2000ms exceeded". The problem could simply be that under emulator, the tests run more slowly which makes time timeout.

The tests:
`js client -> js server Interop-adjacent tests max message size with a server with message size limits and a client without limits.should get an error when sending a large message`
and 
`js client -> js server Interop-adjacent tests max message size with a server with message size limits and a client without limits.should get an error when sending a large message` 

There are also a few `"after all" hook` failures, not sure if they are related.

Example results:
https://source.cloud.google.com/results/invocations/91618033-4b5d-47f0-9d49-d7d42c61a414/targets/github%2Fgrpc-node%2Freports%2Fnode12/tests
https://source.cloud.google.com/results/invocations/fd64d2ec-62ac-4aad-ae79-1b4d414dce4b/targets/github%2Fgrpc-node%2Freports%2Fnode12/tests
https://source.cloud.google.com/results/invocations/ad72ca8e-c844-4047-bf99-0e3ee04d0c20/targets/github%2Fgrpc-node%2Freports%2Fnode12/tests
https://source.cloud.google.com/results/invocations/65a7687d-bb07-4fa1-8a5a-3aaea9aabc84/targets/github%2Fgrpc-node%2Freports%2Fnode12/tests

**Comment by jtattermusch** [comment]
https://github.com/grpc/grpc-node/blob/21652b8793ee8e0a23df67090826fb553a75713d/test/api/interop_extra_test.js#L55

**Comment by jtattermusch** [comment]
CC @murgatroid99  does this seem like a real problem or should we just increase the timeout of the test mentioned above?

**Comment by murgatroid99** [comment]
I think we should just increase the timeouts. If they end up failing even with a generous timeout, then we can look for other issues. The errors in the hooks are probably nothing; sometimes asynchronous test errors get associated with the hook instead of with the test itself.

**Comment by jtattermusch** [comment]
Fixed by #1803 (and its followups).
