### ISSUE TITLE
request failure using the pure js server code

### ISSUE THREAD

**Issue by travisghansen** [grpc/grpc-node#1815]
### Problem description
I'm seeing silent failures when using the pure js implementation but the `grpc` package works fine.

### Reproduction steps
I'm writing an authentication plugin to work with envoy (https://www.envoyproxy.io/docs/envoy/latest/api-v3/service/auth/v3/external_auth.proto). I have a local client I used to invoke the service locally (using the pure js code) and that works just fine. However when the service is invoked by envoy itself I get silent failures (callback is never invoked, connection is showing as reset on the envoy side). After scratching my head for far too long I decided to try the the c-based package and immediately it worked successfully.

### Environment
 - OS name, version and architecture: arch
 - Node version 12
 - Node installation method pacman
 - Package name and version [e.g. gRPC@1.12.0]

```
    "@grpc/grpc-js": "^1.3.2",
    "grpc": "^1.24.10",
```

### Additional context
`tcpdump` appeared to show the pure js package responding at least to a `HEAD` request coming from envoy (something my local client doesn't do) but for some reason I'm not getting much more than that.

Thanks!

**Comment by murgatroid99** [comment]
Can you run the client and server with the environment variables `GRPC_TRACE=all` and `GRPC_VERBOSITY=DEBUG` and share the output when using envoy? That should give us a better idea of what's happening.

**Comment by travisghansen** [comment]
OK, I'm not entirely sure what you mean by the client as `envoy` is the client in the failure scenario. I have added the env vars to both `envoy` and the auth server though and unfortunately I'm getting *nothing* on the server logs at all during the failed request. Here are the envoy logs..

```
[2021-06-18 06:19:46.215][16][debug][router] [source/common/router/router.cc:425] [C0][S17070522059472688576] cluster 'extension/projectcontour-auth/eas' match for URL '/envoy.service.auth.v3.Authorization/Check'
[2021-06-18 06:19:46.215][16][debug][router] [source/common/router/router.cc:582] [C0][S17070522059472688576] router decoding headers:
':method', 'POST'
':path', '/envoy.service.auth.v3.Authorization/Check'
':authority', 'extension/projectcontour-auth/eas'
':scheme', 'http'
'te', 'trailers'
'grpc-timeout', '5000m'
'content-type', 'application/grpc'
'x-envoy-internal', 'true'
'x-forwarded-for', ''
'x-envoy-expected-rq-timeout-ms', '5000'

[2021-06-18 06:19:46.215][16][debug][pool] [source/common/http/conn_pool_base.cc:79] queueing stream due to no available connections
[2021-06-18 06:19:46.215][16][debug][pool] [source/common/conn_pool/conn_pool_base.cc:106] creating a new connection
[2021-06-18 06:19:46.215][16][debug][client] [source/common/http/codec_client.cc:41] [C36] connecting
[2021-06-18 06:19:46.215][16][debug][connection] [source/common/network/connection_impl.cc:864] [C36] connecting to 10.42.0.40:9002
[2021-06-18 06:19:46.215][16][debug][connection] [source/common/network/connection_impl.cc:880] [C36] connection in progress
[2021-06-18 06:19:46.216][16][debug][http2] [source/common/http/http2/codec_impl.cc:1190] [C36] updating connection-level initial window size to 268435456
[2021-06-18 06:19:46.216][16][debug][connection] [source/common/network/connection_impl.cc:670] [C36] connected
[2021-06-18 06:19:46.216][16][debug][client] [source/common/http/codec_client.cc:80] [C36] connected
[2021-06-18 06:19:46.216][16][debug][pool] [source/common/conn_pool/conn_pool_base.cc:225] [C36] attaching to next stream
[2021-06-18 06:19:46.216][16][debug][pool] [source/common/conn_pool/conn_pool_base.cc:130] [C36] creating stream
[2021-06-18 06:19:46.216][16][debug][router] [source/common/router/upstream_request.cc:359] [C0][S17070522059472688576] pool ready
[2021-06-18 06:19:46.478][16][debug][http2] [source/common/http/http2/codec_impl.cc:970] [C36] stream closed: 1
[2021-06-18 06:19:46.478][16][debug][client] [source/common/http/codec_client.cc:125] [C36] request reset
[2021-06-18 06:19:46.478][16][debug][pool] [source/common/conn_pool/conn_pool_base.cc:159] [C36] destroying stream: 0 remaining
[2021-06-18 06:19:46.478][16][debug][router] [source/common/router/router.cc:1026] [C0][S17070522059472688576] upstream reset: reset reason: remote reset, transport failure reason: 
[2021-06-18 06:19:46.478][16][debug][http] [source/common/http/async_client_impl.cc:101] async http request response headers (end_stream=true):
':status', '200'
'content-type', 'application/grpc'
'grpc-status', '14'
'grpc-message', 'upstream connect error or disconnect/reset before headers. reset reason: remote reset'
```

With my auth server code I literally toggle these 2 lines and go from fully functioning to nothing (at least with envoy as the client):

```
const grpc = require("@grpc/grpc-js");
const grpc = require("grpc");
```

Any other ways I can get lower level tcp connection debug stats from node or something to see what's going on with the connection? I do see packets floating around so I know `envoy` is trying to connect.

**Comment by murgatroid99** [comment]
Are you saying that you are seeing logs, but not during the failed request, or that you aren't seeing any logs at all because the logging functionality is not working for you?

If it's the first one, that indicates that the request is getting rejected by Node before grpc-js even sees it. If that is the case, you may be able to get more information by adding the environment variable `NODE_DEBUG=http2`.

**Comment by travisghansen** [comment]
Sorry that wasn't clear. I know the extra env vars are taking effect because I see a little extra output during server startup (see below). I have just added the `NODE_DEBUG` env var and still nothing gets logged at all when a request is made by envoy (my local client still works just fine however. I will note that the debug output from the js lib seems quite minimal.

```
# extra logs show by adding the env vars when using the js lib
2021-06-18T15:35:40.744Z | dns_resolver | Resolver constructed for target dns:0.0.0.0:9002
2021-06-18T15:35:40.745Z | dns_resolver | Resolution update requested for target dns:0.0.0.0:9002
2021-06-18T15:35:40.745Z | dns_resolver | Returning IP address for target dns:0.0.0.0:9002
2021-06-18T15:35:40.748Z | server | Attempting to bind 0.0.0.0:9002
2021-06-18T15:35:40.748Z | server | Successfully bound 0.0.0.0:9002
2021-06-18T15:37:22.055Z | server | Received call to method /envoy.service.auth.v3.Authorization/Check at address 0.0.0.0:9002
```

**Comment by travisghansen** [comment]
OK, scratch the failure of the `NODE_DEBUG` comment above, I had something else overwriting the ENV var but I've got it enabled now.

Sequence when request is initiated by `envoy`:

```
NET 778668: onconnection
STREAM 778668: read 0
STREAM 778668: need readable false
STREAM 778668: length less than watermark true
STREAM 778668: do read
NET 778668: _read
NET 778668: Socket._handle.readStart
HTTP2 778668: Http2Session server: received a connection
HTTP2 778668: Http2Session server: setting up session handle
HTTP2 778668: Http2Session server: sending settings
HTTP2 778668: Http2Session server: submitting settings
HTTP2 778668: Http2Session server: created
(node:778668) Warning: Setting the NODE_DEBUG environment variable to 'http2' can expose sensitive data (such as passwords, tokens and authentication headers) in the resulting log.
HTTP2 778668: Http2Session server: settings received
# at this point output stops, the connection has seemingly been dropped, and nothing more happens until another request is initiated
```

Sequence when request is initiated by local client (using the pure js lib as a client):

```
NET 778668: onconnection
STREAM 778668: read 0
STREAM 778668: need readable false
STREAM 778668: length less than watermark true
STREAM 778668: do read
NET 778668: _read
NET 778668: Socket._handle.readStart
HTTP2 778668: Http2Session server: received a connection
HTTP2 778668: Http2Session server: setting up session handle
HTTP2 778668: Http2Session server: sending settings
HTTP2 778668: Http2Session server: submitting settings
HTTP2 778668: Http2Session server: created
HTTP2 778668: Http2Stream 1 [Http2Session server]: headers received
2021-06-18T15:51:27.725Z | server | Received call to method /envoy.service.auth.v3.Authorization/Check at address 0.0.0.0:9002
...
```

I find it particularly odd that the warning and `settings received` message never appear when using my local client.

**Comment by murgatroid99** [comment]
grpc-js debug logs are minimal because they are mostly added as we need them. Right now, I can't think of any other information that grpc-js has access to that would help us solve this, but if there was something, I would add the log and then it would be there in the future too.

These `NODE_DEBUG` logs do seem to pretty clearly show that the problem is that the Node http2 module isn't handling the request at all. The "settings received" is the most interesting discrepancy here. It would be nice to see the contents of that. If you're willing to edit some code, you could modify [this event handler](https://github.com/grpc/grpc-node/blob/master/packages/grpc-js/src/server.ts#L635-L646) to add a `session.on('remoteSettings', console.log)` or something like that to get more details. Alternatively, Wireshark could probably show you the contents. Wireshark might be a good idea anyway to see exactly what's happening at a network level.

**Comment by travisghansen** [comment]
Thanks for the continued help! Something with `enablePush`?

```
# envoy
NET 787717: onconnection
STREAM 787717: read 0
STREAM 787717: need readable false
STREAM 787717: length less than watermark true
STREAM 787717: do read
NET 787717: _read
NET 787717: Socket._handle.readStart
HTTP2 787717: Http2Session server: received a connection
HTTP2 787717: Http2Session server: setting up session handle
HTTP2 787717: Http2Session server: sending settings
HTTP2 787717: Http2Session server: submitting settings
HTTP2 787717: Http2Session server: created
on session fired
HTTP2 787717: Http2Session server: new settings received
{
  headerTableSize: 4096,
  enablePush: false,
  initialWindowSize: 268435456,
  maxFrameSize: 16384,
  maxConcurrentStreams: 2147483647,
  maxHeaderListSize: 4294967295,
  maxHeaderSize: 4294967295,
  enableConnectProtocol: false
}
HTTP2 787717: Http2Session server: settings received


# js client
NET 787717: onconnection
STREAM 787717: read 0
STREAM 787717: need readable false
STREAM 787717: length less than watermark true
STREAM 787717: do read
NET 787717: _read
NET 787717: Socket._handle.readStart
HTTP2 787717: Http2Session server: received a connection
HTTP2 787717: Http2Session server: setting up session handle
HTTP2 787717: Http2Session server: sending settings
HTTP2 787717: Http2Session server: submitting settings
HTTP2 787717: Http2Session server: created
on session fired
HTTP2 787717: Http2Session server: new settings received
{
  headerTableSize: 4096,
  enablePush: true,
  initialWindowSize: 65535,
  maxFrameSize: 16384,
  maxConcurrentStreams: 4294967295,
  maxHeaderListSize: 4294967295,
  maxHeaderSize: 4294967295,
  enableConnectProtocol: false
}
HTTP2 787717: Http2Stream 1 [Http2Session server]: headers received

```

**Comment by murgatroid99** [comment]
Those do look like the main differences, but I don't know why those would cause the problems you are seeing. It's still not really clear to me what is happening, though. The best next step I can think of is to examine the traffic between Envoy and the gRPC with a tool like Wireshark.

**Comment by travisghansen** [comment]
Got a good example tcpdump command for observing grpc traffic? tcpdump is not my forte :)

I’ll also try to force my local client to use those specific settings as well and see what happens (if you have an example of setting them client side send it over).

**Comment by murgatroid99** [comment]
gRPC traffic is just TCP traffic. It's really just the analyzer that needs to understand gRPC, or at least HTTP/2. [This page](https://www.wireshark.org/docs/wsug_html_chunked/AppToolstcpdump.html) shows how to dump a file for analysis by Wireshark.

I'm not sure how to send settings from that client. This is the function: https://nodejs.org/api/http2.html#http2_http2session_settings_settings_callback, but it's async so it might have some weird timing issues. If you did want to add it it would probably go [in here](https://github.com/grpc/grpc-node/blob/master/packages/grpc-js/src/subchannel.ts#L541-L551)

**Comment by travisghansen** [comment]
I tried messing around with the session settings (and think I got it working) but it didn't seem to make much difference. I have some captures now but I'd prefer to not through them on gh for privacy reasons. Mind if I email them or some other channel?

Analyzing them seems to indicate that indeed the request is arriving from `envoy` in both scenarios but the packets after the request have arrived diverge. I'm not versed enough at this level (tcp/ip) to be of much help on my own at this point :(

**Comment by murgatroid99** [comment]
OK, you can send them to me at mlumish at google dot com

**Comment by travisghansen** [comment]
Great, I'll do that shortly. We've also got a test instance of contour up and running where I can point it at a local development endpoint if you have some way to run the server (npm i on the project) and punch a hole and NAT some traffic down to your dev machine.

**Comment by travisghansen** [comment]
OK, email sent. Thanks for the help!

**Comment by murgatroid99** [comment]
Those TCP dumps show that when envoy makes the request to the pure JS server, the response is an RST_STREAM with error code 1 (PROTOCOL_ERROR). This implies that there is at least one bug in envoy: when it receives such a response, it should either report that the request has ended with an error, or it should retry the request with modifications to avoid the protocol error. I think this means there is also another bug in either envoy or Node: either envoy is committing an actual protocol error, or Node is incorrectly interpreting a valid HTTP/2 frame as having an error. It's hard to tell which it is from the 

Before we try to go any further, can you just verify that you see the same problem when running the server on the latest version of Node, so that we can eliminate the possibility that it's a Node bug that has already been fixed?

**Comment by travisghansen** [comment]
Yeah I'm fairly certain I did do that, but I'll run through the process again to confirm and report back.

**Comment by travisghansen** [comment]
To be clear, envoy is detecting the failure and moving on with life

```
':status', '200'
'content-type', 'application/grpc'
'grpc-status', '14'
'grpc-message', 'upstream connect error or disconnect/reset before headers. reset reason: remote reset'
```

**Comment by murgatroid99** [comment]
In the original post you said "when the service is invoked by envoy itself I get silent failures (callback is never invoked, connection is showing as reset on the envoy side)". Did I misunderstand that? I assumed that "silent" meant that the client was not seeing any errors.

**Comment by travisghansen** [comment]
Yeah sorry that was unclear. I meant silent from the perspective of the node server (doesn’t log anything or throw any errors etc that I as an app developer can ‘handle’)…as mentioned envoy is showing the connection reset.

**Comment by travisghansen** [comment]
Yeah, same behavior confirmed with `v16.3.0`

```
node --version
v16.3.0
```

**Comment by murgatroid99** [comment]
OK, I have posted nodejs/help#3422. Hopefully we can get some information from there to help understand this bug better.

**Comment by travisghansen** [comment]
The node grpc version being deprecated while this issue still exists is disheartening. Are there other avenues/channels we should be looking to get a fix?

I have 2 projects using grpc and neither of them can be fully migrated unfortunately still:

- integration with `envoy` due to this issue
- `csi` driver for k8s/Nomad/etc because of unix socket bind issues and/or screwy authentication issues (the later more the problem of bad clients, but nonetheless)

**Comment by murgatroid99** [comment]
From my point of view, this has no relationship to the deprecation of the other library. We have no intention of guaranteeing that Node.js itself is bug-free as a condition of continuing with that deprecation, and I do believe that this is a bug in Node, not in grpc-js.

I think any information about the cause of this error exists inside of Node, and without any responses on that issue I posted, I don't know how to make progress.

**Comment by travisghansen** [comment]
I understand the sentiment but effectively (even if not under your control) it leaves users without an upgrade path and/or security updates. That’s kinda a tough position to be in as a consumer of the lib :(

I only wish to convey the predicament and explore options, not complain about the project or the team and effort!

Is it possible to communicate via other channels with the core team to work on the issue? Are there other potential avenues that can be explored?

**Comment by murgatroid99** [comment]
The `grpc` package still gets security updates. We have published about 4 new versions of the library since we officially deprecated it.

I have tried back channel communication to try to get responses from the Node team, and it didn't get me a useful response. It seems like they just don't have many (or any?) people working on HTTP/2. This is frustrating for me too, but at this point, it's out of my hands.

**Comment by travisghansen** [comment]
Yeah that is super frustrating :( Thanks for clarifying the security updates, I was unaware those were intended to continue. UDS support never made it into that package right?

**Comment by murgatroid99** [comment]
You're right, that package does not have UDS support.

**Comment by hugebdu** [comment]
same here with node 14 :(

**Comment by travisghansen** [comment]
Since comments are closed on the upstream issue, putting notes here. `NODE_DEBUG_NATIVE=http2` provided no additional output in my setup.

**Comment by murgatroid99** [comment]
I want to comment on something you mentioned in the Node issue:

> `@grpc/grpc-js` should probably default to adding `unix://` to the server/client when the path looks like a uds (or does not look like a `host:port`). maybe this should be left to higher-level code?

We intentionally do not do this. We don't have any complex heuristics at all when handling target addresses. We just default to DNS, which is the behavior specified in [this document](https://github.com/grpc/grpc/blob/master/doc/naming.md):

> The URI scheme indicates what resolver plugin to use. If no scheme prefix is specified or the scheme is unknown, the `dns` scheme is used by default.

**Comment by travisghansen** [comment]
Sounds sane. Does the go library do the same? Perhaps all the k8s bits handle this at a higher-level.

**Comment by travisghansen** [comment]
This can be closed now. If anyone lands here I created this to overcome the issue: https://github.com/democratic-csi/csi-grpc-proxy
