### ISSUE TITLE
Reserved keyword in Enum doesnt get compile

### ISSUE THREAD

**Issue by vsr7** [grpc/grpc-node#183]
Grpc version : 1.9.0
When reserved field in Enums is given in the proto file, the compiler throws error:

Error : Parse error at line 42: illegal '18', '=' expected.

May be latest version of protobufjs has this fix.

**Comment by nicolasnoble** [comment]
We have released new versions of the `grpc` package, which can now be used with `@grpc/proto-loader`, which allows you to use protobufjs 6 instead.

Could you check if this helps your case ?

**Comment by nicolasnoble** [comment]
Closing, since it got no response for 40 days.
