### ISSUE TITLE
grpc-js - 'error' argument in provided callback for Server.tryShutdown() will never be used.

### ISSUE THREAD

**Issue by ddorando** [grpc/grpc-node#1846]
### Problem description
The argument you can provide for the 'callback' in Server.tryShutdown() is never used/provided, thus, it's not possible to provide an error to said callback.
I'm not sure if anything inside tryShutdown() can throw an error; though right now it's a bit confusing to say the least.

### Reproduction steps
n/a - Doesn't apply to running code.

### Environment
Package name and version: '@grpc/grpc-js' - at least v1.2.12 up to current master branch

**Comment by murgatroid99** [comment]
`tryShutdown` does call the callback when the server has finished shutting down, which happens after all outstanding requests have finished processing. It's true that currently no code paths currently provide an error to the callback, but that could change.
