### ISSUE TITLE
Static code generation error

### ISSUE THREAD

**Issue by mano233** [grpc/grpc-node#1847]
### Problem description
same issue as https://github.com/grpc/grpc-node/issues/1774#issuecomment-832654907, 

This error seems to happen only in windows environment, I use the same command in macos and linux without this problem

### Environment
 - windows10 2004
 - node v14.16.1
 - nvm
 -  "@grpc/grpc-js": "^1.3.5",
    "@grpc/proto-loader": "^0.6.4",
    "google-protobuf": "^3.17.3",
    "grpc-tools": "^1.11.2",

**Comment by murgatroid99** [comment]
`grpc-tools` uses `protoc` to generate those files. I suggest asking in the repository responsible for that tool (https://github.com/protocolbuffers/protobuf). They probably have a better idea of what could cause that.

**Comment by mano233** [comment]
> `grpc-tools` uses `protoc` to generate those files. I suggest asking in the repository responsible for that tool (https://github.com/protocolbuffers/protobuf). They probably have a better idea of what could cause that.


Thanks for the advice, but I didn't find a solution there, but after my attempts, I finally succeeded~
 A powershell script.
```
#!/usr/bin/env bash
$PROTOC_GEN_TS_PATH = "$HOME/AppData/Roaming/npm/protoc-gen-ts.cmd"
$GRPC_TOOLS_NODE_PROTOC_PLUGIN = "$HOME/AppData/Roaming/npm/grpc_tools_node_protoc_plugin.cmd"
& protoc `
--plugin=protoc-gen-grpc=$GRPC_TOOLS_NODE_PROTOC_PLUGIN `
--plugin=protoc-gen-ts=$PROTOC_GEN_TS_PATH `
--js_out=import_style=commonjs,binary:./ `
--ts_out=service=grpc-node,mode=grpc-js:./ `
--grpc_out=grpc_js:./ `
out/hello.proto
```

This only worked for me if I installed grpc-tools and grpc_tools_node_protoc_ts globally with npm install -g grpc-tools grpc_tools_node_protoc_ts
