### ISSUE TITLE
Support nodejs cluster module 

### ISSUE THREAD

**Issue by CatsMiaow** [grpc/grpc-node#1848]
Related issues
- https://github.com/grpc/grpc/issues/6976
- https://github.com/grpc/grpc/issues/10417
- https://github.com/grpc/grpc/issues/11004

https://nodejs.org/api/cluster.html
Are there any methods or tricks I can implement in the latest Node.js(v16)?

**Comment by murgatroid99** [comment]
Those all refer to the old deprecated package `grpc`. The newer supported package `@grpc/grpc-js` should just work with cluster out of the box. If you encounter any issues trying to use it that way, please file another issue with the details of the problem.

**Comment by CatsMiaow** [comment]
I wrote a sample code and tested it in node.js cluster and pm2 cluster environment, and confirmed that the connection in the new instance is connected to other processes on the server by round-robin. Thank you.
