### ISSUE TITLE
Client-side C++ exception in ClientContext destructor

### ISSUE THREAD

**Issue by fronneburg** [grpc/grpc-node#186]
If the ClientContext object's "recv_initial_metadata_" member has entries in its "map_", the ClientContext destructor crashes when trying to free the pair of string_ref's in the map.

**Comment by murgatroid99** [comment]
Are you using the Node implementation or the C++ implementation? If you are using the C++ implementation, you should file this issue in the main repository: https://github.com/grpc/grpc.

**Comment by fronneburg** [comment]
Yes, I did that wrong. This should be C++.
