### ISSUE TITLE
Tag for @grpc/grpc-js v1.3.6 looks to be missing.

### ISSUE THREAD

**Issue by nairb774** [grpc/grpc-node#1863]
### Problem description

It would be nice to see the releases tagged in the repo.

### Reproduction steps

I was looking for releases notes for the 1.3.6 release, and it seems to be missing. The underlying tag also seems to be missing.

### Additional context

https://www.npmjs.com/package/@grpc/grpc-js claims there is a 1.3.6, but the tag looks to be missing in the repo.

**Comment by murgatroid99** [comment]
Done
