### ISSUE TITLE
Add release notes or changelog

### ISSUE THREAD

**Issue by jdforsythe** [grpc/grpc-node#1876]
### Is your feature request related to a problem? Please describe.
@grpc/grpc-js was recently bumped from 1.3.6 to 1.3.7. There doesn't appear to be a release in the releases section and there's no changelog in the directory to indicate what changes were made. I don't see any commits indicating when versions change, so it's difficult to tell what has changed and whether we should upgrade.

### Describe the solution you'd like
The best solution would be separate repos so that automated tools like GitHub's Dependabot show the release notes in the automated upgrade PRs, but without that the next best solution would be a changelog file or to at least ensure that a new release is created on GitHub any time a new npm release is made so there's always a place to find out what the changes were between versions.

### Additional context
Add any other context about the feature request here.

**Comment by murgatroid99** [comment]
I have added the release [here](https://github.com/grpc/grpc-node/releases/tag/%40grpc%2Fgrpc-js%401.3.7)
