### ISSUE TITLE
grpc install fails: "node-pre-gyp: Permission denied" but for global install only?

### ISSUE THREAD

**Issue by stephenplusplus** [grpc/grpc-node#188]
###### Copied from original issue: https://github.com/googleapis/nodejs-speech/issues/29

<a href="/talkingnews"><img src="https://avatars2.githubusercontent.com/u/1552808?s=88&v=4" height=44 width=44 align=left></a>@talkingnews<br>February 19, 2018 4:36 PM

#### Environment details

  - OS: Ubuntu 17.10 4.13.0-32-generic #35-Ubuntu SMP Thu Jan 25 09:13:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
  - Node.js version: 8.9.4
  - npm version: 5.6.0
  - @google-cloud/speech version: 1.1.0

#### Steps to reproduce

  1. `npm install -g @google-cloud/speech`

Results below - this looks like the same issue as these:
https://github.com/grpc/grpc/issues/13928
https://github.com/googleapis/gax-nodejs/issues/173

Strangely, installing it locally (without -g) works, but with -g, I get the following:

```
> grpc@1.7.3 install /root/.nvm/versions/node/v8.9.4/lib/node_modules/@google-cloud/speech/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

sh: 1: node-pre-gyp: Permission denied
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! grpc@1.7.3 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the grpc@1.7.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-02-19T16_16_46_264Z-debug.log
```
[2018-02-19T16_16_46_264Z-debug.log](https://github.com/googleapis/nodejs-speech/files/1737519/2018-02-19T16_16_46_264Z-debug.log)

**Comment by murgatroid99** [comment]
This looks like a file system permission problem. I don't know if there's anything we can change in the package to fix that.

**Comment by murgatroid99** [comment]
@talkingnews I have figured out how to reproduce this failure: it only happens if I run the command as root. If that is what you are seeing, then you should be able to fix it either by running as a different user, or by running with the `--unsafe-perm` option.

**Comment by talkingnews** [comment]
Tada! Success - thank you!
