### ISSUE TITLE
Call metadata missing on server side.

### ISSUE THREAD

**Issue by tegefaulkes** [grpc/grpc-node#1881]
### Problem description
I have a program node program that we import as a library called js-polykey. This library handles communication between a client and an agent. This communication needs to make use of Metadata to start and maintain sessions. 

The problem arises when importing js-polykey, separately importing `@grpc/grpc-js` and trying to send a message with `grpc.Metadata()` to the agent. On the agent side the metadata is missing.

I can fix the problem by creating a `grpc.Metadata()` object through the js-polykey library. either by re-exporting it or using a utility function to create the Metadata object.

### Reproduction steps
Here are the simplified steps to re-create the problem. I will link to a branch that cleanly displays the problem once I've created it.

To test the problem I send an echo message containing the metadata. Here I'm sending two message to demonstrate the problem and the 2nd one that shows a working solution.
```ts
    const echoMessage = new clientPB.EchoMessage();
    echoMessage.setChallenge('Hello!');

    console.log('First metadata');
    const meta = new grpc.Metadata();
    meta.add('First', 'Test');
    await grpcClient.echo(echoMessage, meta);

    //with other metadata.
    console.log('Second metadata')
    const meta2 = createMetadata();
    meta2.add('Second', 'Test');
    await grpcClient.echo(echoMessage, meta2);
```
Where `createMetadata()` is defined inside the js-polykey as;
```ts
function createMetadata(): grpc.Metadata {
  return new grpc.Metadata();
}
```

On the agent side where we are logging the received Metadata we get;
```
First metadata
Echo meta:  Metadata {
  internalRepr: Map(1) { 'user-agent' => [ 'grpc-node-js/1.3.6' ] },
  options: {}
}

Second metadata
Echo meta:  Metadata {
  internalRepr: Map(2) {
    'second' => [ 'Test' ],
    'user-agent' => [ 'grpc-node-js/1.3.6' ]
  },
  options: {}
}
```

As you can see the first message is missing the it's metadata.
We expect to see `'First' => [ 'Test' ],` here.

### Environment
 - NixOS
 - Node version: v14.17.1
 - "@grpc/grpc-js": "^1.2.5",

### Additional context
Relates to issue https://github.com/MatrixAI/js-polykey/issues/221

**Comment by murgatroid99** [comment]
Where does `grpcClient` come from in this example?

Also, what is the output of `npm ls @grpc/grpc-js`?

**Comment by tegefaulkes** [comment]
Here is the full test file.
```ts
import { PolykeyAgent, PolykeyClient } from '@matrixai/polykey/src';
import { clientPB } from '@matrixai/polykey/src/client';
import { Metadata as Metadata2 } from '@matrixai/polykey/src/client/utils';
import Logger from '@matrixai/logger';
import { Metadata } from '@grpc/grpc-js';

const nodePath = 'tmp/keynode';

async function main() {
  const logger = new Logger();
  const agent = new PolykeyAgent({
    nodePath,
    logger
  });
  await agent.start({ password: 'password' });
  const client = new PolykeyClient({
    nodePath
  });
  await client.start({});
  try {
    const grpcClient = client.grpcClient;

    const echoMessage = new clientPB.EchoMessage();
    echoMessage.setChallenge('Hello!');
    console.log('First metadata');
    const meta = new Metadata();
    meta.add('First', 'Test');
    await grpcClient.echo(echoMessage, meta);

    //with other metadata.
    console.log('Second metadata')
    const meta2 = new Metadata2();
    meta2.add('Second', 'Test');
    await grpcClient.echo(echoMessage, meta2);

  } catch (e) {
    console.error(e);
  } finally {
    await client.stop();
    await agent.stop();
  }
}

main();
```
Its part of the js-polykey library that handles calls through the GRPC from the client side.

As for your second question.

```
[nix-shell:~/matrixworkspace/polykeyCode/pkgTesting/lib-grpc-test]$ npm ls @grpc/grpc-js
@matrixai/typescript-demo-lib@1.0.0 /home/brian/matrixworkspace/polykeyCode/pkgTesting/lib-grpc-test
├── @grpc/grpc-js@1.3.7 
└─┬ @matrixai/polykey@0.0.41 -> /home/brian/matrixworkspace/polykeyCode/js-polykey
  └── @grpc/grpc-js@1.3.6 

```

I'll post instructions for using the repo for testing in a sec.

**Comment by murgatroid99** [comment]
OK, that `npm ls` output shows the problem. There's an `instanceof Metadata` check when making a request in grpc-js, so when you have two different versions, the classes won't match up and it will get interpreted incorrectly.

**Comment by tegefaulkes** [comment]
I figured it was something like that. Is there a proper way of importing it to avoid this issue?
Or is the solution basically what i'm doing by re-exporting it through the js-polykey library?

**Comment by tegefaulkes** [comment]
If you want to test it with the code, you can clone the two repository with
```
In a clean directory
git clone --single-branch --branch GRPC_issue_example https://github.com/MatrixAI/js-polykey.git 
git clone --single-branch --branch simpleGRPC https://github.com/MatrixAI/TypeScript-Demo-Lib.git 
```

**Comment by murgatroid99** [comment]
If you expect your users to have their own dependency on grpc-js, and interact with it directly, you might want to use a peer dependency to ensure that both the user and the library are using the same instance of grpc-js. If it's not particularly useful for your users to do that, you should ensure that all of the grpc-js functionality they need can be accomplished using your library, either by wrapping it like you did or by providing a more substantial abstraction layer.

My guess for why the versions are different is that you installed them at different times, and your package-lock.json froze the dependencies at whatever version you installed at the time. Or maybe you simply never updated the library's dependencies after the new version was published. Either way, the conclusion here is that you can't count on npm's dependency resolution to ensure that those two dependencies point to the same library, because that's not something it tries to guarantee.

**Comment by tegefaulkes** [comment]
Thank you, I think that covers everything.
I'm closing this issue now.
