### ISSUE TITLE
proto-loader-gen-types shall generate an extra method definition for services which accepts arg: A and returns Observable<R>  

### ISSUE THREAD

**Issue by nikotili** [grpc/grpc-node#1883]
I'm using NestJS to create a gRPC microservice and `proto-loader-gen-types` to generate types from the `.proto` file. However, generated interfaces only have methods which return `SurfaceCall` types like `ClientUnaryCall` and have a `callback` param like `callback: (err, res: R) => void`.

I'm suggesting a feature for `proto-loader-gen-types` to generate an extra method definition which looks like `FindOne(arg: A, metadata?: Metadata): Observable<T>` for the services.

I have considered using <a href="https://www.npmjs.com/package/nestjs-proto-gen-ts">nestjs-proto-gen-ts</a> which does exactly what I'm suggesting, but it lacks the generated methods from `proto-loader-gen-types`

**Comment by murgatroid99** [comment]
The purpose of the type generator in the `@grpc/proto-loader` library is to generate types for objects output by the proto-loader library. Generating types for other libraries is out of scope for that type generator.
