### ISSUE TITLE
Getting Failed to load gRPC binary error (with either node v12 or v14)

### ISSUE THREAD

**Issue by diogolessa** [grpc/grpc-node#1885]
Hi,

I'm working on an application that runs fine locally, but when running through docker I constantly get this error.

```bash
web_1  | Error: Failed to load gRPC binary module because it was not installed for the current system
web_1  | Expected directory: node-v72-linux-x64-glibc
web_1  | Found: [node-v48-linux-x64-glibc]
web_1  | This problem can often be fixed by running "npm rebuild" on the current system
web_1  | Original error: Cannot find module '/usr/app/node_modules/grpc/src/node/extension_binary/node-v72-linux-x64-glibc/grpc_node.node'
web_1  | Require stack:
web_1  | - /usr/app/node_modules/grpc/src/grpc_extension.js
web_1  | - /usr/app/node_modules/grpc/src/client_interceptors.js
web_1  | - /usr/app/node_modules/grpc/src/client.js
web_1  | - /usr/app/node_modules/grpc/index.js
web_1  | - /usr/app/node_modules/google-gax/lib/grpc.js
web_1  | - /usr/app/node_modules/google-gax/index.js
web_1  | - /usr/app/node_modules/@google-cloud/datastore/src/index.js
```
Node version: 12.13.0 (I've also tried 14.17.5 LTS, same happens but with node-v83-linux-x64-glibc instead)
I'm currently using yarn `1.22.10` but tried to use npm `6.12.0` too and the same happens.
Also tried to go with npm only, ran `npm rebuild --unsafe-perm` inside the dockerfile, but didn't work.

Appreciate any ideas on how to proceed in order to fix this.

Thanks in advance,

**Comment by murgatroid99** [comment]
You are installing the package on/for Node 6 and then trying to run it on Node 12 (or 14). There are different binaries for different versions of Node, so they have to match. `npm rebuild` in the dockerfile would usually work, maybe it's using a different version of Node at that time than when you actually run the code. You can resolve this by adding the argument `--target=12.0.0` (or whatever version of Node you are using) when running the original `npm` or `yarn` install command.

In addition, this library has been deprecated. We recommend using `@grpc/grpc-js` instead.

**Comment by diogolessa** [comment]
@murgatroid99 I build the image the first time using node 6 indeed.
I was able to fix it by actually removing the image and building it again.
Thanks for the suggestion 👍🏻
