### ISSUE TITLE
Unused message properties are being defaulted

### ISSUE THREAD

**Issue by respinha-ribeiro** [grpc/grpc-node#189]
Hello.

If I send a message via gRPC which doesn't have all of its properties set, they are being defaulted to a null/empty value. I've modified the officially provided [example](https://github.com/grpc/grpc/tree/master/examples/node) to simulate this issue. 
I included some more properties in the `HelloReply` message

```
message HelloReply {
  string message = 1;
  double number_property = 2;
  string string_property = 3;
  repeated string array_property = 4;
  message NestedMsg {
  	string property = 1;
  }
  NestedMsg nested_property = 5;
}
```

and I just added a small print statement to `dynamic_codegen/greeter_client.js`

```
console.log('Total message:', JSON.stringify(response));
```

and it prints:

```
Total message: {"message":"Hello world","number_property":0,"string_property":"","array_property":[],"nested_property":null}
```

So, all properties are being defaulted to 0/""/[]/null. Is this the expected behaviour? I thought it could also be a protobuf.js-specific issue.
In my case, this behaviour is not desirable as in some cases I override existing data in my system with data from protobuf messages and if those properties are defaulted I might even override valid data with a null or empty value. 

If this is the expected workflow for gRPC messages, can it be turned off?

**Comment by murgatroid99** [comment]
This is the expected behavior of protobuf, as documented [here](https://developers.google.com/protocol-buffers/docs/proto3#default). Currently, gRPC does not provide a way to change that, but I am working on a new package (proposed [here](https://github.com/grpc/proposal/blob/master/L23-node-protobufjs-library.md)) that will provide that option among other things.

**Comment by respinha-ribeiro** [comment]
I didn't notice it in the documentation, thanks, @murgatroid99. I'll wait for the new package then.

**Comment by nicolasnoble** [comment]
The new `@grpc/proto-loader` package has been published. Could you tell us if this helps with your problem ?

**Comment by respinha-ribeiro** [comment]
Hey, @nicolasnoble, thanks for the notice.

However, when I try to apply the package definition as in the [example](https://www.npmjs.com/package/@grpc/proto-loader) within Typescript code, I get a type definition error: 
```
error TS2339: Property 'loadPackageDefinition' does not exist on type 'typeof "grpc"'.
```

**Comment by murgatroid99** [comment]
We've published version 1.11.1 which includes those definitions in the TypeScript types file.

**Comment by respinha-ribeiro** [comment]
Hmm, I updated to version `1.11.1` and when I run `tsc -d` I get
```
node_modules/grpc/index.d.ts(1307,61): error TS2304: Cannot find name 'function'.
node_modules/grpc/index.d.ts(1309,54): error TS2304: Cannot find name 'function'.
node_modules/grpc/index.d.ts(1311,61): error TS2304: Cannot find name 'function'.
node_modules/grpc/index.d.ts(1349,82): error TS2304: Cannot find name 'function'.
node_modules/grpc/index.d.ts(1351,55): error TS2304: Cannot find name 'function'.
node_modules/grpc/index.d.ts(1353,39): error TS2304: Cannot find name 'function'.
node_modules/grpc/index.d.ts(1355,40): error TS2304: Cannot find name 'function'.
node_modules/grpc/index.d.ts(1357,41): error TS2304: Cannot find name 'function'.
```

**Comment by Crevil** [comment]
This is fixed with #307 but not released yet

**Comment by respinha-ribeiro** [comment]
I fixed the typings locally in order to perform tests.
It seems to work as expected!

**Comment by nicolasnoble** [comment]
@respinha-ribeiro there's an issue with node 10 (nodejs/node#20258) that prevents us from running tests with node 10 at the moment, so we can't legitimately recommend using node 10 with gRPC just yet. This will require a new release of node 10.

**Comment by respinha-ribeiro** [comment]
Thank you for the notice. We are using Node 9 anyway and it all seems fine.
