### ISSUE TITLE
grpc@grpc-js connections pool documents

### ISSUE THREAD

**Issue by lwmxiaobei** [grpc/grpc-node#1899]
hi, I want to know how many connections grpc@grpc-js will open by default, whether there is a concept of connection pool, or where there are related documents to read

**Comment by murgatroid99** [comment]
gRPC does not use connection pools, as the term is commonly used. gRPC establishes a single connection to each backend, and sends all requests along that single connection. Some names may resolve to more than one backend (e.g. a DNS name may have both A and AAAA records, or multiple records of either kind), which may result in connections being established either to only one of those backends or to all of them, depending on the load balancing policy in use.

Open connections are reused if a different client connects to the same server, which is connection pooling in a different sense.

**Comment by lwmxiaobei** [comment]
Thanks!

**Comment by matthiasgeihs** [comment]
@murgatroid99 How does your comment go in line with the following?

> Each gRPC channel uses 0 or more HTTP/2 connections

https://grpc.io/docs/guides/performance/

Are you saying actually it is more like between 0 and 1 HTTP/2 connections?

**Comment by murgatroid99** [comment]
I said

> Some names may resolve to more than one backend (e.g. a DNS name may have both A and AAAA records, or multiple records of either kind), which may result in connections being established either to only one of those backends or to all of them, depending on the load balancing policy in use.

If the client establishes connections to more than one backend, then it will use more than one connection.
