### ISSUE TITLE
Why  module `build/src/resolver` is not exported ?

### ISSUE THREAD

**Issue by Tseian** [grpc/grpc-node#1904]
In my project, I have used resolver for round-robin strategy，but  it is not exported yet.  Are there other ways that I do not know yet to use round-robin strategy ?

**Comment by murgatroid99** [comment]
That file contains internal APIs for defining resolver classes. It is not relevant for using any resolver. And round robin is not a resolver at all in this library, it is a load balancing policy, which is handled by different internals.

Instructions for using the round robin load balancing policy can be found here: https://github.com/grpc/grpc-node/issues/1307#issuecomment-601312421.
