### ISSUE TITLE
Problem migrating to `@grpc/grpc-js`

### ISSUE THREAD

**Issue by gabrielcora20** [grpc/grpc-node#1906]
Hi, I'm new here and would like to ask a question. I have the following error when migrating to the new lib: `Incorrect arguments passed`, the error is happening in the `sendMessage` method, if I change the require to the old lib it works again.

Do I need to make any changes when passing the parameters?

**Comment by nicolasnoble** [comment]
No code change should be needed. If you get this error, it means there's a silent bug in your code originally, and the new version has tighter requirements, but without the actual code, we can't really help you much further.
