### ISSUE TITLE
Not able to wrap static compiled ts files in a npm package

### ISSUE THREAD

**Issue by mr-bjerre** [grpc/grpc-node#1912]
### Problem description

I'm afraid I've come along a bug. I'm using the following npm packages `grpc-tools` and `ts-protoc-gen` to compile `.proto` into `.js` and `.d.ts` files. I then create a local npm package that wraps and exports the generated files. This package can then be installed locally in other node projects using `yarn add link:/path/to/package`.

The issue arises during runtime here

```typescript
import * as grpc from "@grpc/grpc-js";
import { GreeterClient } from "wrapper/hello_grpc_pb";

new GreeterClient("abc", grpc.credentials.createInsecure());
```
The error is

```typescript
$ ts-node index.ts
/home/nixd/Projects/Playground/yarn-packages/grpc/wrapper/node_modules/@grpc/grpc-js/src/channel.ts:174
      throw new TypeError(
            ^
TypeError: Channel credentials must be a ChannelCredentials object
    at new ChannelImplementation (/home/nixd/Projects/Playground/yarn-packages/grpc/wrapper/node_modules/@grpc/grpc-js/src/channel.ts:174:13)
    at new Client (/home/nixd/Projects/Playground/yarn-packages/grpc/wrapper/node_modules/@grpc/grpc-js/src/client.ts:150:30)
    at new ServiceClientImpl (/home/nixd/Projects/Playground/yarn-packages/grpc/wrapper/node_modules/@grpc/grpc-js/src/make-client.ts:128:3)
    at Object.<anonymous> (/home/nixd/Projects/Playground/yarn-packages/grpc/client/index.ts:4:1)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Module.m._compile (/home/nixd/Projects/Playground/yarn-packages/grpc/client/node_modules/ts-node/src/index.ts:1310:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Object.require.extensions.<computed> [as .ts] (/home/nixd/Projects/Playground/yarn-packages/grpc/client/node_modules/ts-node/src/index.ts:1313:12)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

It seems to be caused by different `@grpc/grpc-js` in the two different `node_modules`.

### Reproduction steps

I've made a small GitHub project with two folders `client` and `wrapper`. I've already generated files from `hello.proto` in the `wrapper` folder.

1. clone https://github.com/mr-bjerre/NodeGRPCWrapper
2. cd wrapper
3. yarn install
4. cd ../client
5. yarn install
6. yarn run ts-node index.ts

I've noticed that if you don't install dependencies in `wrapper` folder then you get a different error (dependencies not really needed in wrapper since I've already compiled the proto files)

### Environment
 - OS name, version and architecture: Ubuntu 20.04
 - Node version: v15.14.0
 - Node installation method [e.g. nvm]
 - If applicable, compiler version [e.g. clang 3.8.0-2ubuntu4]
 - Package name and version [e.g. gRPC@1.12.0]

Let me know if you need additional information

**Comment by mr-bjerre** [comment]
The following workaround seems to work but it ain't pretty

1. cd wrapper
2. rm -rf node_modules
3. cd ../client
4. yarn remove wrapper
5. yarn add ../wrapper (instead of link:../wrapper)
6. yarn run ts-node index.ts

So there are definitely some issue with the different node_modules

**Comment by murgatroid99** [comment]
If the wrapper package is expected to be used by code that is also using `@grpc/grpc-js` directly, it should have a peer dependency on `@grpc/grpc-js`, not a regular dependency.

**Comment by mr-bjerre** [comment]
Thanks for your reply @murgatroid99 

I've tried adding `@grpc/grpc-js` as peerDependency instead. Unfortunately that leaves me with `Error: Cannot find module '@grpc/grpc-js'`.


```javascript
+ yarn run ts-node index.ts
yarn run v1.22.10
$ /Users/nixd/Documents/NodeGRPCWrapper/client/node_modules/.bin/ts-node index.ts
Error: Cannot find module '@grpc/grpc-js'
Require stack:
- /Users/nixd/Documents/NodeGRPCWrapper/wrapper/generated/hello_grpc_pb.js
- /Users/nixd/Documents/NodeGRPCWrapper/client/index.ts
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/nixd/Documents/NodeGRPCWrapper/wrapper/generated/hello_grpc_pb.js:19:12)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/nixd/Documents/NodeGRPCWrapper/wrapper/generated/hello_grpc_pb.js',
    '/Users/nixd/Documents/NodeGRPCWrapper/client/index.ts'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I've updated my reproducible example https://github.com/mr-bjerre/NodeGRPCWrapper so you simply have to run `./run` in the root dir.


I can only make it work if I have `yarn add ../wrapper` instead of `yarn add link:../wrapper` but then I don't get "live" updates

**Comment by murgatroid99** [comment]
OK, the specific behavior you're seeing is related to how linking packages impacts Node's `require` search algorithm. Node searches `node_modules` in parent directories, but not in sibling directories. `yarn add` will actually copy the package, so the `client`'s `node_modules` will be in the parent directory, but `yarn link` uses the package in its original directory, so it won't work like that.

The conclusion is that you can't have all three of

 - `wrapper` uses the same instance of `@grpc/grpc-js` as `client`
 - `client` directly depends on `@grpc/grpc-js`
 - `wrapper` is not installed in `client`'s `node_modules` (i.e. it is linked instead)

The resolution of this problem depends on how much this directory structure that you have there reflects your final use case. If you publish these packages to `npm`, users of those packages won't experience these problems. If you only intend to use them locally, you can easily resolve the problem by having the generated code live in `client`, instead of in a separate package.

**Comment by mr-bjerre** [comment]
Thanks for the insights here!

I guess I'll go with the solution of not linking. My use case is only local but multiple packages uses the wrapper.

**Comment by mr-bjerre** [comment]
Sorry for returning to this @murgatroid99 but I think I have a very related issue.

I'm using nodemon and want to attach a debugger so I do `nodemon --inspect=0.0.0.0:9229` and then I receive the same error. Is it not possible to run a debug session with `@grpc-js`?
