### ISSUE TITLE
Cannot handle hot-plugged CPUs | cpu_linux.cc:75

### ISSUE THREAD

**Issue by Mreddi1** [grpc/grpc-node#1914]
### Problem description
`E0923 20:39:14.921011514   12272 cpu_linux.cc:75            Cannot handle hot-plugged CPUs`

### Reproduction steps
I don't know how to reproduce this problem. But I suppose it happened because my hosting provider changed count of CPUs. I found the place to call the logging function https://github1s.com/grpc/grpc/blob/master/src/core/lib/gpr/cpu_linux.cc#L75-L76

And this error appears endlessly:
```
E0923 20:39:14.969403791   12272 cpu_linux.cc:75            Cannot handle hot-plugged CPUs
E0923 20:39:14.993540098   12272 cpu_linux.cc:75            Cannot handle hot-plugged CPUs
E0923 20:39:14.993592906   12272 cpu_linux.cc:75            Cannot handle hot-plugged CPUs
E0923 20:39:15.000811017   12272 cpu_linux.cc:75            Cannot handle hot-plugged CPUs
E0923 20:39:15.055667511   12272 cpu_linux.cc:75            Cannot handle hot-plugged CPUs
E0923 20:39:15.057504479   12272 cpu_linux.cc:75            Cannot handle hot-plugged CPUs
```

### Environment
OS:
  - Icon name: computer-container
  - Chassis: container
  - Virtualization: openvz
  - Operating System: CentOS Linux 7 (Core)
  - CentOS Linux release 7.6.1810 (Core)
  - CPE OS Name: cpe:/o:centos:centos:7
  - Kernel: Linux 3.10.0
  - Architecture: x86-64

CPU:
  - Architecture:          x86_64
  - CPU(s):                2
  - On-line CPU(s) list:   0,1
  - Thread(s) per core:    1
  - CPU family:            6
  - Model:                 44
  - Model name:            Intel(R) Xeon(R) CPU           X5680  @ 3.33GHz
  - Virtualization:        VT-x
  - Hypervisor vendor:     Parallels
  - Virtualization type:   container

Node.js:
  - Node.js v13.9.0
  - NVM v0.35.3
  - NPM v6.13.7
  - grpc v^1.24.10
  - typescript v^4.2.4
  - protobufjs v^6.10.2

### Additional context
- none

**Comment by murgatroid99** [comment]
The `grpc` package has been deprecated for a few months. As a result, we will not be making modifications to fix bugs like this. I recommend switching to `@grpc/grpc-js`.
