### ISSUE TITLE
1.4.0 produces typescript error

### ISSUE THREAD

**Issue by tomfriedhof** [grpc/grpc-node#1936]
```
#11 11.92 node_modules/@grpc/grpc-js/build/src/channelz.d.ts(3,30): error TS2307: Cannot find module './generated/grpc/channelz/v1/ChannelTrace' or its corresponding type declarations.
#11 11.92 node_modules/@grpc/grpc-js/build/src/channelz.d.ts(5,54): error TS2307: Cannot find module './generated/grpc/channelz/v1/Channelz' or its corresponding type declarations.
```

I had to lock my version of the client to `1.3.8` for my typescript to compile.

**Comment by komalali** [comment]
Thanks for pointing that out @murgatroid99 yeah I think we'll have to upgrade typescript [on our end](https://github.com/pulumi/pulumi/blob/a92a005d6897506d3ea40307dfd37788c51a4dcf/sdk/nodejs/package.json#L25) if we want to update to the new version. For the time being we'll pin to 1.3.8. Thanks!
