### ISSUE TITLE
channelz support might have introduced memory leak

### ISSUE THREAD

**Issue by Xiaosha61** [grpc/grpc-node#1958]
### Problem description

Upgrading @grpc-js from 1.3.8 to 1.4.1 introduces memory leak. 

The image shows the heap space size used (old space)
- green line is using @grpc-js@1.3.8; 
- yellow one is @grpc-js@1.4.1.

![image](https://user-images.githubusercontent.com/10236330/140039859-f1419afc-5102-4984-a440-70bc3af62232.png)

### Reproduction steps
- Set up the most common grpc transport following the guide of nestjs/microservices/grpc (https://docs.nestjs.com/microservices/grpc#call-stream-handler)
- Observe the Used Heap Space Size (Old space) for a few hours (in my case it's leaking ~15M/day)

### Environment
 - OS name, version and architecture:  [docker container x86_64 GNU/Linux Ubuntu 20.04.3 LTS]
 - Node version  [v16.12.0]
 - Package name and version: @grpc-js@1.4.1, consumed by @nestjs/microservice@8.0.11 (same case for 8.1.2)

### Additional context

This is the screenshot of the snapshot diff with 15 hours gap in between.
As the object stack indicates, the `timestamp` pushed into `events` array each time `addTrace` is called, it keeps adding new trace but is never garbage collected somehow. 

According to the grpc version diff, the problem might be introduced by this commit: [grpc-js: Add channelz support](https://github.com/grpc/grpc-node/commit/d4574a28fbaba840454bd62914a5d980661b0f31), when introducing the new object `ChannelzTrace` in [server.ts](https://github.com/grpc/grpc-node/blob/master/packages/grpc-js/src/server.ts#L153) after release of [1.4.0](https://github.com/grpc/grpc-node/releases/tag/%40grpc%2Fgrpc-js%401.4.0).

![snapshot-diff](https://user-images.githubusercontent.com/10236330/140052489-92ef137c-4b27-4c11-95c7-a9cfeb20102d.png)

Is it something now should be disabled explicitly if not needed?

**Comment by murgatroid99** [comment]
Thank you for the report. This was also reported in #1941, and as a result, I published grpc-js version 1.4.2 with hard limits on the number of retained channelz trace events per channel/subchannel/server, and support for the channel/server option `grpc.enable_channelz`, which can be set to 0 to disable channelz entirely. Please try it out to see if it solves your problem.

**Comment by Xiaosha61** [comment]
looks better. Thanks for the fast fix :)
