### ISSUE TITLE
Method type generated by proto-loader-gen-types has improper callback signature

### ISSUE THREAD

**Issue by LunaTK** [grpc/grpc-node#1966]
### Problem description
RPC method generated by `proto-loader-gen-types` uses different callback type against `requestCallback` from `@grpc/grpc-js`.

- proto-loader-gen-types : `(error?: grpc.ServiceError, result?: Res) => void`
- grpc-js : `(err: ServiceError | null, value?: ResponseType) => void`

When `strict` is on in `compilerOptions` from `tsconfig.json`, these two types are incompatible. Using conditional types on the RPC method with grpc.requestCallback fails because of the inconsistency.

As all the other parameters are represented with `grpc-js` provided types (e.g., `grpc.Metadata`, `grpc.CallOptions`), it seems logical that `callback` parameter of the RPC method should also be represented with `requestCallback` type provided by `grpc-js`.

- current
```typescript
type ProtoLoaderGrpcMethod<Req, Res> = {
  (argument: Req, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (error?: grpc.ServiceError, result?: Res) => void): grpc.ClientUnaryCall;
  (argument: Req, metadata: grpc.Metadata, callback: (error?: grpc.ServiceError, result?: Res) => void): grpc.ClientUnaryCall;
  (argument: Req, options: grpc.CallOptions, callback: (error?: grpc.ServiceError, result?: Res) => void): grpc.ClientUnaryCall;
  (argument: Req, callback: (error?: grpc.ServiceError, result?: Res) => void): grpc.ClientUnaryCall;
}
```
- suggested
```typescript
type GrpcJsGrpcMethod<Req, Res> = {
  (argument: Req, metadata: grpc.Metadata, options: grpc.CallOptions, callback: grpc.requestCallback<Res>): grpc.ClientUnaryCall;
  (argument: Req, metadata: grpc.Metadata, callback: grpc.requestCallback<Res>): grpc.ClientUnaryCall;
  (argument: Req, options: grpc.CallOptions, callback: grpc.requestCallback<Res>): grpc.ClientUnaryCall;
  (argument: Req, callback: grpc.requestCallback<Res>): grpc.ClientUnaryCall;
}
```

### Reproduction steps
- I made a reproduction repository: https://github.com/LunaTK/proto-loader-gen-types-typing/blob/main/index.ts#L11-L16
- I expect type inference of conditional type to be working when leveraging `grpc.requestCallback` for the callback parameter

### Environment
- `TypeScript` : 4.2.4
- `@grpc/grpc-js` : 1.4.4
- `@grpc/proto-loader` : 0.6.6

**Comment by murgatroid99** [comment]
This has been changed in `@grpc/proto-loader` version 0.6.7
