### ISSUE TITLE
I want to make 10k generative art with hashlips.

### ISSUE THREAD

**Issue by somematon** [grpc/grpc-node#1971]
I'm using a Mac.

This video (https://youtu.be/qmpuvGdI0w4) is shown at 4:09

I could not run yarn add all. I would like to know the solution.

＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿
　　　　　　　　　　Air generative-art-opensource % npm install yarn

added 64 packages, and audited 65 packages in 17s

5 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
　　　　　　　　　　Air generative-art-opensource % yarn add all
zsh: command not found: yarn
＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿

Translated with www.DeepL.com/Translator (free version)

**Comment by murgatroid99** [comment]
This does not seem to be about gRPC. If this is about gRPC, please explain how.
