### ISSUE TITLE
Default value of grpc.max_concurrent_streams?

### ISSUE THREAD

**Issue by pigLoveRabbit520** [grpc/grpc-node#1973]
### Problem description
```
const server = new grpc.Server({
    'grpc.max_concurrent_streams': ****,
  });
```
Maybe low value of `grpc.max_concurrent_streams` leads to [slow response](https://github.com/grpc/grpc-node/issues/1889)?

### Environment
 - OS name [Ubuntu 20.04 amd64]
 - Node version [v14.17.1]
 - Package name and version ["@grpc/grpc-js": "^1.4.3"]

**Comment by murgatroid99** [comment]
That option just gets passed through to Node's http2 server creation, which specifies that there is no limit by default.
