### ISSUE TITLE
Support PFX format in credentials.createSsl

### ISSUE THREAD

**Issue by JoshuaWise** [grpc/grpc-node#1977]
### Is your feature request related to a problem? Please describe.
At Postman, we're trying to use `@grpc/grpc-js`, but we need to load TLS credentials from PFX files. Currently, the `credentials.createSsl()` function only accepts `private_key` and `cert_chain` separately,  but the underlying `tls.createSecureContext()` function supports a `pfx` option which allows you to pass both of them together in PFX format.

### Describe the solution you'd like
I'd like `credentials.createSsl()` to accept a `pfx` option, which gets passed to `tls.createSecureContext()`. Also, to support password-protected PFX files, `credentials.createSsl()` should accept a `passphrase` option, which also gets passed directly to `tls.createSecureContext()`.

### Describe alternatives you've considered
We considered trying to split the PFX files into `cert` and `key` files, but that requires `openssl` to be installed, which we can't rely on. Also, it seems silly to try such heavy-handed workarounds when `tls.createSecureContext()` already supports this exact feature.

### Additional context
`tls.createSecureContext()`: https://nodejs.org/api/tls.html#tlscreatesecurecontextoptions
`credentials.createSsl()`: https://grpc.github.io/grpc/node/grpc.credentials.html#.createSsl__anchor

**Comment by murgatroid99** [comment]
My proposal to resolve this is grpc/proposal#282, which would add a new credentials creation API that directly takes a `SecureContext`. Our procedures for API change proposals require that I wait two weeks before finalizing that proposal, so this will probably happen in the new year.

**Comment by JoshuaWise** [comment]
That would be perfect. Thank you for creating this proposal.

**Comment by murgatroid99** [comment]
The implementation of that proposal has been released in version 1.6.0.
