### ISSUE TITLE
grpc.lb_policy_name option no longer works in grpc-js

### ISSUE THREAD

**Issue by josephharrington** [grpc/grpc-node#1982]
### Problem description
Setting the client load balancer to `round_robin` via the `'grpc.lb_policy_name'` option works in `grpc`, but seems to have no effect in `@grpc/grpc-js`.

However, setting the client load balancer via the `'grpc.service_config'` option works in both libraries, so this is not a blocker. Depending on the intention for `'grpc.lb_policy_name'`, maybe this is a bug or maybe this only needs to be documented as a breaking change to watch out for when switching over to grpc-js.

### Reproduction steps
```node
// const grpc = require('grpc'); // works (uses round_robin)
const grpc = require('@grpc/grpc-js'); // broken (uses pick_first)

// <get stub constructor via protoLoader.loadSync and grpc.loadPackageDefinition>

const options = {
    'grpc.ssl_target_name_override': ...,
    'grpc.lb_policy_name': 'round_robin', // <--- has no effect in grpc-js
    // 'grpc.service_config': 
    //     JSON.stringify({loadBalancingConfig: [{round_robin: {}}]}),  // <--- but this still works
};

const client = new MyService(
    'myservice.netflix.com:8980',
    grpc.credentials.createSsl(...),
    options
);

// <make a call with the client>
```

Setting env vars `GRPC_VERBOSITY=debug` and `GRPC_TRACE=round_robin,pick_first`, I can see that when running under `grpc` the round_robin LB is successfully activated, but under `@grpc/grpc-js` it still uses pick_first.

### Environment
 - OS name, version and architecture: Linux and macOS 
 - Node version: 12.22
 - Node installation method: NA
 - Package name and version: `grpc@v1.24.11` and `@grpc/grpc-js@v1.4.4`

**Comment by murgatroid99** [comment]
There are a lot of channel arguments that are supported in `grpc` but not `@grpc/grpc-js`. That is simply one of them. The list of channel arguments that are supported in `@grpc/grpc-js` can be found in [this document](https://github.com/grpc/grpc-node/blob/master/PACKAGE-COMPARISON.md).

I don't know what its deprecation status is of that specific channel argument, but I think it is unlikely that it will be implemented when the service config option is available and more general.

**Comment by josephharrington** [comment]
Thanks for linking the package comparison document. Now that I see it again, I think I'd run across that in the past but had forgotten about it. Would you support updating the readme to add a link to this doc, and maybe also mention that not all channel args are supported in grpc-js? I think it would fit well in the ["Migrating from grpc" section](https://github.com/grpc/grpc-node/tree/master/packages/grpc-js#migrating-from-grpc), and would then also show up on the npm page for grpc-js.

**Comment by murgatroid99** [comment]
A very similar issue came up in #1983, so I think it would be best to continue that discussion there.
