### ISSUE TITLE
Snyk.io vulnerable package ansi-regex

### ISSUE THREAD

**Issue by kanxoramesh** [grpc/grpc-node#1995]
Introduced through:  `newrelic@8.6.0 › @grpc/grpc-js@1.4.5 › @grpc/proto-loader@0.6.7 › yargs@16.2.0 › string-width@4.2.2 › strip-ansi@6.0.0 › ansi-regex@5.0.0`

please update your package `@grpc/grpc-js` to use latest version of `yargs`

**Comment by murgatroid99** [comment]
This is good to know and I will fix it, but `@grpc/grpc-js` never invokes any code path in `@grpc/proto-loader` that uses `yargs`, so this is not an actual vulnerability in `@grpc/grpc-js`. I will fix this in the new year after the holidays.

**Comment by murgatroid99** [comment]
I have published `@grpc/proto-loader` version 0.6.8. If you pick up new versions of your dependencies it should resolve this issue.
