### ISSUE TITLE
[Bug]: 'Long' can only be imported by using a default import.

### ISSUE THREAD

**Issue by rustamsmax** [grpc/grpc-node#2009]
node_modules/@grpc/proto-loader/build/src/index.d.ts(22,10): error TS2595: 'Long' can only be imported by using a default import.

**Comment by murgatroid99** [comment]
I haven't seen this error in my own tests. Can you share some code that triggered it?

**Comment by rustamsmax** [comment]
I'm not using this library. I've a project where I user @firebase-admin which uses @grpc modules


├─┬ firebase-admin@9.12.0
│ ├─┬ @firebase/database-compat@0.1.4
│ │ ├─┬ @firebase/app-compat@0.1.12
│ │ │ ├─┬ @firebase/app@0.7.11
│ │ │ │ ├── @firebase/component@0.5.9 deduped
│ │ │ │ ├── @firebase/logger@0.3.2 deduped
│ │ │ │ ├── @firebase/util@1.4.2 deduped
│ │ │ │ └── tslib@2.3.1 deduped
│ │ │ ├── @firebase/component@0.5.9 deduped
│ │ │ ├── @firebase/logger@0.3.2 deduped
│ │ │ ├── @firebase/util@1.4.2 deduped
│ │ │ └── tslib@2.3.1 deduped
│ │ ├─┬ @firebase/component@0.5.9
│ │ │ ├── @firebase/util@1.4.2 deduped
│ │ │ └── tslib@2.3.1 deduped
│ │ ├─┬ @firebase/database-types@0.9.3
│ │ │ ├── @firebase/app-types@0.7.0
│ │ │ └── @firebase/util@1.4.2 deduped
│ │ ├─┬ @firebase/database@0.12.4
│ │ │ ├─┬ @firebase/auth-interop-types@0.1.6
│ │ │ │ ├── @firebase/app-types@0.7.0 deduped
│ │ │ │ └── @firebase/util@1.4.2 deduped
│ │ │ ├── @firebase/component@0.5.9 deduped
│ │ │ ├── @firebase/logger@0.3.2 deduped
│ │ │ ├── @firebase/util@1.4.2 deduped
│ │ │ ├─┬ faye-websocket@0.11.4
│ │ │ │ └─┬ websocket-driver@0.7.4
│ │ │ │   ├── http-parser-js@0.5.5
│ │ │ │   ├── safe-buffer@5.1.2 deduped
│ │ │ │   └── websocket-extensions@0.1.4
│ │ │ └── tslib@2.3.1 deduped
│ │ ├─┬ @firebase/logger@0.3.2
│ │ │ └── tslib@2.3.1 deduped
│ │ ├─┬ @firebase/util@1.4.2
│ │ │ └── tslib@2.3.1 deduped
│ │ └── tslib@2.3.1
│ ├─┬ @firebase/database-types@0.7.3
│ │ └── @firebase/app-types@0.6.3
│ ├─┬ @google-cloud/firestore@4.15.1
│ │ ├── fast-deep-equal@3.1.3 deduped
│ │ ├── functional-red-black-tree@1.0.1 deduped
│ │ ├─┬ google-gax@2.28.1
│ │ │ ├─┬ @grpc/grpc-js@1.4.6
│ │ │ │ ├── @grpc/proto-loader@0.6.8 deduped
│ │ │ │ └── @types/node@15.14.9 deduped
│ │ │ ├─┬ @grpc/proto-loader@0.6.8
│ │ │ │ ├── @types/long@4.0.1 deduped
│ │ │ │ ├── lodash.camelcase@4.3.0
│ │ │ │ ├── long@4.0.0
│ │ │ │ ├── protobufjs@6.11.2 deduped
│ │ │ │ └─┬ yargs@17.3.1
│ │ │ │   ├─┬ cliui@7.0.4
│ │ │ │   │ ├─┬ string-width@4.2.3
│ │ │ │   │ │ ├── emoji-regex@8.0.0 deduped
│ │ │ │   │ │ ├── is-fullwidth-code-point@3.0.0
│ │ │ │   │ │ └── strip-ansi@6.0.1 deduped
│ │ │ │   │ ├── strip-ansi@6.0.1 deduped
│ │ │ │   │ └── wrap-ansi@7.0.0 deduped
│ │ │ │   ├── escalade@3.1.1 deduped
│ │ │ │   ├── get-caller-file@2.0.5
│ │ │ │   ├── require-directory@2.1.1
│ │ │ │   ├─┬ string-width@4.2.3
│ │ │ │   │ ├── emoji-regex@8.0.0 deduped
│ │ │ │   │ ├── is-fullwidth-code-point@3.0.0
│ │ │ │   │ └── strip-ansi@6.0.1 deduped
│ │ │ │   ├── y18n@5.0.8
│ │ │ │   └── yargs-parser@21.0.0
│ │ │ ├── @types/long@4.0.1 deduped
│ │ │ ├─┬ abort-controller@3.0.0
│ │ │ │ └── event-target-shim@5.0.1
│ │ │ ├── duplexify@4.1.2 deduped
│ │ │ ├── fast-text-encoding@1.0.3
│ │ │ ├─┬ google-auth-library@7.11.0
│ │ │ │ ├── arrify@2.0.1 deduped
│ │ │ │ ├── base64-js@1.5.1 deduped
│ │ │ │ ├── ecdsa-sig-formatter@1.0.11 deduped
│ │ │ │ ├── fast-text-encoding@1.0.3 deduped
│ │ │ │ ├── gaxios@4.3.2 deduped
│ │ │ │ ├─┬ gcp-metadata@4.3.1
│ │ │ │ │ ├── gaxios@4.3.2 deduped
│ │ │ │ │ └─┬ json-bigint@1.0.0
│ │ │ │ │   └── bignumber.js@9.0.2
│ │ │ │ ├─┬ gtoken@5.3.1
│ │ │ │ │ ├── gaxios@4.3.2 deduped
│ │ │ │ │ ├─┬ google-p12-pem@3.1.2
│ │ │ │ │ │ └── node-forge@0.10.0 deduped
│ │ │ │ │ └── jws@4.0.0 deduped
│ │ │ │ ├─┬ jws@4.0.0
│ │ │ │ │ ├─┬ jwa@2.0.0
│ │ │ │ │ │ ├── buffer-equal-constant-time@1.0.1 deduped
│ │ │ │ │ │ ├── ecdsa-sig-formatter@1.0.11 deduped
│ │ │ │ │ │ └── safe-buffer@5.1.2 deduped
│ │ │ │ │ └── safe-buffer@5.1.2 deduped
│ │ │ │ └── lru-cache@6.0.0 deduped
│ │ │ ├── is-stream-ended@0.1.4
│ │ │ ├─┬ node-fetch@2.6.6
│ │ │ │ └─┬ whatwg-url@5.0.0
│ │ │ │   ├── tr46@0.0.3
│ │ │ │   └── webidl-conversions@3.0.1
│ │ │ ├── object-hash@2.2.0
│ │ │ ├─┬ proto3-json-serializer@0.1.6
│ │ │ │ └── protobufjs@6.11.2 deduped
│ │ │ ├── protobufjs@6.11.2 deduped
│ │ │ └─┬ retry-request@4.2.2
│ │ │   ├── debug@4.3.3 deduped
│ │ │   └── extend@3.0.2 deduped
│ │ └─┬ protobufjs@6.11.2
│ │   ├── @protobufjs/aspromise@1.1.2
│ │   ├── @protobufjs/base64@1.1.2
│ │   ├── @protobufjs/codegen@2.0.4
│ │   ├── @protobufjs/eventemitter@1.1.0
│ │   ├─┬ @protobufjs/fetch@1.1.0
│ │   │ ├── @protobufjs/aspromise@1.1.2 deduped
│ │   │ └── @protobufjs/inquire@1.1.0 deduped
│ │   ├── @protobufjs/float@1.0.2
│ │   ├── @protobufjs/inquire@1.1.0
│ │   ├── @protobufjs/path@1.1.2
│ │   ├── @protobufjs/pool@1.1.0
│ │   ├── @protobufjs/utf8@1.1.0
│ │   ├── @types/long@4.0.1 deduped
│ │   ├── @types/node@15.14.9 deduped
│ │   └── long@4.0.0
│ ├─┬ @google-cloud/storage@5.16.1
│ │ ├─┬ @google-cloud/common@3.8.1
│ │ │ ├── @google-cloud/projectify@2.1.1
│ │ │ ├── @google-cloud/promisify@2.0.4 deduped
│ │ │ ├── arrify@2.0.1 deduped
│ │ │ ├── duplexify@4.1.2 deduped
│ │ │ ├── ent@2.2.0
│ │ │ ├── extend@3.0.2 deduped
│ │ │ ├── google-auth-library@7.11.0 deduped
│ │ │ ├── retry-request@4.2.2 deduped
│ │ │ └─┬ teeny-request@7.1.3
│ │ │   ├─┬ http-proxy-agent@5.0.0
│ │ │   │ ├── @tootallnate/once@2.0.0
│ │ │   │ ├─┬ agent-base@6.0.2
│ │ │   │ │ └── debug@4.3.3 deduped
│ │ │   │ └── debug@4.3.3 deduped
│ │ │   ├─┬ https-proxy-agent@5.0.0
│ │ │   │ ├── agent-base@6.0.2 deduped
│ │ │   │ └── debug@4.3.3 deduped
│ │ │   ├── node-fetch@2.6.6 deduped
│ │ │   ├── stream-events@1.0.5 deduped
│ │ │   └── uuid@8.3.2 deduped
│ │ ├─┬ @google-cloud/paginator@3.0.6
│ │ │ ├── arrify@2.0.1 deduped
│ │ │ └── extend@3.0.2 deduped
│ │ ├── @google-cloud/promisify@2.0.4
│ │ ├── arrify@2.0.1
│ │ ├─┬ async-retry@1.3.3
│ │ │ └── retry@0.13.1
│ │ ├── compressible@2.0.18 deduped
│ │ ├── date-and-time@2.0.1
│ │ ├─┬ duplexify@4.1.2
│ │ │ ├─┬ end-of-stream@1.4.4
│ │ │ │ └── once@1.4.0 deduped
│ │ │ ├── inherits@2.0.4 deduped
│ │ │ ├── readable-stream@3.6.0 deduped
│ │ │ └── stream-shift@1.0.1
│ │ ├── extend@3.0.2
│ │ ├─┬ gcs-resumable-upload@3.6.0
│ │ │ ├── abort-controller@3.0.0 deduped
│ │ │ ├── async-retry@1.3.3 deduped
│ │ │ ├── configstore@5.0.1 deduped
│ │ │ ├── extend@3.0.2 deduped
│ │ │ ├─┬ gaxios@4.3.2
│ │ │ │ ├── abort-controller@3.0.0 deduped
│ │ │ │ ├── extend@3.0.2 deduped
│ │ │ │ ├── https-proxy-agent@5.0.0 deduped
│ │ │ │ ├── is-stream@2.0.1
│ │ │ │ └── node-fetch@2.6.6 deduped
│ │ │ ├── google-auth-library@7.11.0 deduped
│ │ │ ├── pumpify@2.0.1 deduped
│ │ │ └── stream-events@1.0.5 deduped
│ │ ├── get-stream@6.0.1
│ │ ├── hash-stream-validation@0.2.4
│ │ ├── mime-types@2.1.34 deduped
│ │ ├── mime@3.0.0
│ │ ├─┬ p-limit@3.1.0
│ │ │ └── yocto-queue@0.1.0
│ │ ├─┬ pumpify@2.0.1
│ │ │ ├── duplexify@4.1.2 deduped
│ │ │ ├── inherits@2.0.4 deduped
│ │ │ └── pump@3.0.0 deduped
│ │ ├── snakeize@0.1.0
│ │ ├─┬ stream-events@1.0.5
│ │ │ └── stubs@3.0.0
│ │ └── xdg-basedir@4.0.0
│ ├── @types/node@15.14.9 deduped
│ ├─┬ dicer@0.3.1
│ │ └── streamsearch@1.1.0 deduped
│ ├── jsonwebtoken@8.5.1 deduped
│ ├─┬ jwks-rsa@2.0.5
│ │ ├─┬ @types/express-jwt@0.0.42
│ │ │ ├─┬ @types/express-unless@0.5.2
│ │ │ │ └── @types/express@4.17.13 deduped
│ │ │ └── @types/express@4.17.13 deduped
│ │ ├── debug@4.3.3 deduped
│ │ ├─┬ jose@2.0.5
│ │ │ └── @panva/asn1.js@1.0.0
│ │ ├── limiter@1.1.5
│ │ └─┬ lru-memoizer@2.1.4
│ │   ├── lodash.clonedeep@4.5.0
│ │   └─┬ lru-cache@4.0.2
│ │     ├── pseudomap@1.0.2
│ │     └── yallist@2.1.2
│ └── node-forge@0.10.0

**Comment by murgatroid99** [comment]
OK, that looks like a TypeScript compilation error. Can you share the contents of your `tsconfig.json` file?

**Comment by rustamsmax** [comment]
{
  "compilerOptions": {
    "experimentalDecorators": true,
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "noEmit": true,
    "strict": false,
    "target": "esnext",
  },
  "typeRoots": [
    "node_modules/@types",
    "src/typings",
    "./@types"
  ]
}

**Comment by rustamsmax** [comment]
I think the issue it originating from not explicitly importing @mongodb Long type

**Comment by murgatroid99** [comment]
No, Protobuf.js and `@grpc/proto-loader` use the `long` library, which has no relationship to mongodb as far as I know.

What typescript compiler version are you using?

**Comment by mr-tech** [comment]
Just want to leave here that changing https://github.com/grpc/grpc-node/blob/c1d68a00aceb552a49ffab1bba502896fc9d1b46/packages/proto-loader/src/index.ts#L25 to
`export { default as Long } from 'long';` I believe fixes the problem. I believe it has something to do with another package importing a newer version of Long that is packaged with its own typings making typescript apply different rules to how this package is using Long. I've moved on from the problem, but perhaps this information will help you.

**Comment by nikolaymatrosov** [comment]
I was getting the error when I had `long: 5.2.0` installed in my node_modules. The error was gone when I pinned down the `long` version to `4.0.0`.

**Comment by alexstojda** [comment]
Pinning to version 4 of `long` resolved the issue for me as well, but it would be great to see @mr-tech's [suggestion](https://github.com/grpc/grpc-node/issues/2009#issuecomment-1059634486) implemented!

**Comment by murgatroid99** [comment]
I have published version 0.6.10 with a change that should fix this. Please try it out.

**Comment by mr-tech** [comment]
> I have published version 0.6.10 with a change that should fix this. Please try it out.

The error does appear to have been resolved for me. Thank you!
