### ISSUE TITLE
unable to close etcd3 watch client

### ISSUE THREAD

**Issue by borisovg** [grpc/grpc-node#201]
I am loading etcd3 proto files via grpc to create a Node client. The Watch API involves creating a stream. For some reason that I don't understand I seem to be unable to close the client (or maybe the stream) and the test hangs. I have connectivity to the server as I send / receive messages before I try and close.

I tried `wtfnode` but it doesn't show anything that might be keeping the app running and unfortunately I don't have much clue as to what goes on under the hood in grpc module. :(

Test app I am using: https://github.com/borisovg/node-etcd3-rpc/blob/master/examples/watch-client.js (`npm install etcd3-rpc`). I get the 'Cancelled:' log messages so that function definitely fires, but app keeps running.

grpc: 1.2.0
node: 8.9.4
os: Debian Sid

**Comment by murgatroid99** [comment]
You appear to be trying to start closing everything by sending this "cancel_request" message. What exactly is the effect of that message supposed to be? Is it supposed to cancel the stream itself, or some other operation on the server? Also, that second "data" handler that you add is a race condition. There is no guarantee that the next message you receive after sending that "cancel_request" message was triggered by that message.

In any case, the gRPC client considers a call to have completed when you receive a call status. This will trigger a "status" event on the stream, and also an "error" event if the status is anything but "OK". When you call `stream.end()`, you are indicating that you have finished writing from the client. The server may take that as a signal to stop on its end and send the status, but it is not required to do so. If you want to force the stream to end, you can use the `stream.cancel()` method. This will quickly end the call with a CANCELLED status, and also signal to the server that the call has been cancelled.

**Comment by borisovg** [comment]
@murgatroid99 the "cancel_request" message is to remove the watcher inside of etcd (a single stream can have multiple watchers getting updates through it). The process is to send a "create_request" first, after which there may be many messages from the server with updates (not present in example I provided) and finally a "cancel_request" which cancels the watcher.

I don't think there is any race condition: `stream.removeAllListeners('data');` before takes care of that. And the request response code works fine, just the connection closing.

What I am seeing is that the app continues to run even through I have called `stream.end()` and `client.close()` which is strange coming from what I am used to in Node world. Are you saying this is an issue with etcd server that is not reacting to my close request? Should this ticket be raised with them instead?

I originally found this issue via Mocha tests for a more sophisticated version of the client (the new Mocha doesn't exit process by default if something is still holding open, to catch issues just like this one).

The `stream.cancel()` does work - the error event is not very elegant, but I can live with that if that's my only option.

**Comment by borisovg** [comment]
Also, I just checked tcpdump:

if I call `stream.end()` client sends some PSH packets to server (no idea how to parse the binary format in the payload) but if I call `stream.cancel()` then it sends FIN which obviously works.

What sort of data is being sent as a result of stream.end() and how is server supposed to respond to it?

**Comment by murgatroid99** [comment]
You don't call `stream.removeAllListeners` before adding the "data" listener inside of the `setTimeout` callback. And the race condition I was pointing out wasn't with having multiple event handlers at the same time. The problem is that you have no guarantee that the first message you receive after sending your "cancel_request" message will be a response to that message, instead of a regular data message that was already on its way.

If etcd says that the server is supposed to close the stream when you send a "cancel_request" message, or when you do a `stream.end()`, and it's not doing that, then that definitely sounds like a bug in their server handler.

Also, just to be sure of what's happening here, I would suggest adding a "status" event handler. If that handler does fire, then that means that the stream is closing, and something else is going on.

As for the tcpdump, I would strongly suggest not looking at lower-level network protocol information until it's the last option. In the gRPC protocol, `stream.end()` send a client-side half close that communicates that it has finished writing. At the HTTP/2 protocol level, this is denoted by a DATA frame with the END_STREAM flag set. We don't specify how a server should respond to that; that's up to the service handler.

**Comment by borisovg** [comment]
There can only be one type of message according to the proto file - the only thing that indicates this is a response is that the "cancel" parameter is set to true, and I can see that it is in the console log of the data response. None of this matters, as it is just a simple little example - in the real client there is of course more sophisticated checks for the value - but I have added some asserts just to be clear.

I have also added a 'status' listener and it does not fire if I call 'stream.end()'.

```/*jshint node:true, esversion:6*/
'use strict';

const assert = require('assert');
const grpc = require('grpc');
const etcd = require('etcd3-rpc');

const client = new etcd.Watch('localhost:2379', grpc.credentials.createInsecure());
const stream = client.watch();

stream.on('data', function (data) {
    const id = data.watch_id;

    assert(data.created === true);
    console.log('Created:', data);
    stream.removeAllListeners('data');

    stream.on('data', function (data) {
        assert(data.canceled === true);
        console.log('Canceled:', data);

        setTimeout(function () {
            console.log('End');
            stream.end();
            client.close();
        }, 3000);
    });

    stream.write({ cancel_request: { watch_id: id } });
});

stream.on('error', function (err) {
    console.log('Error:', err);
});

stream.on('status', function () {
    console.log('Status:', arguments);
});

stream.write({ create_request: { key: new Buffer('\0'), range_end: new Buffer('\0') } });
```

Output:

```
Created: { header: 
   { cluster_id: '9465767127905902590',
     member_id: '6398922322381134955',
     revision: '2',
     raft_term: '2' },
  watch_id: '0',
  created: true,
  canceled: false,
  compact_revision: '0',
  cancel_reason: '',
  events: [] }
Canceled: { header: 
   { cluster_id: '9465767127905902590',
     member_id: '6398922322381134955',
     revision: '2',
     raft_term: '2' },
  watch_id: '0',
  created: false,
  canceled: true,
  compact_revision: '0',
  cancel_reason: '',
  events: [] }
End
```

**Comment by murgatroid99** [comment]
OK, that confirms that the stream is not ending. I would recommend checking etcd's documentation to verify that the stream is supposed to be closed there, and filing a bug with them if it is not behaving as expected.

**Comment by borisovg** [comment]
Will do, thanks.
