### ISSUE TITLE
Tag for @grpc/proto-loader v0.6.9 missing

### ISSUE THREAD

**Issue by nairb774** [grpc/grpc-node#2016]
### Problem description

NPM has a version [v0.6.9](https://www.npmjs.com/package/@grpc/proto-loader/v/0.6.9) but information isn't available for that release in this repository.

### Reproduction steps
Give very precise steps you've discovered to reproduce your problem. If possible and applicable, provide us with a repository we can clone that contains a reproduction case. Also if possible and applicable, please include a Dockerfile that exhibits the problem if it's specific to a certain environment. Bug reports with no reproduction steps will be closed.

![image](https://user-images.githubusercontent.com/128795/148598266-a882e5fc-7c00-46e3-9b31-91f3288524f1.png)

### Environment
 - Package name and version: @grpc/proto-loader v0.6.9

### Additional context
Publishing tags and release notes to the repository helps to validate that the release is intentional and not the result of malicious activities. Having this information available is an important cross-check to prevent bad actors.

**Comment by murgatroid99** [comment]
Fixed
