### ISSUE TITLE
How return an error in duplex streams

### ISSUE THREAD

**Issue by plitex** [grpc/grpc-node#2028]
I'm using `@gprc/grpc-js` to implement a gRPC server. Is there a way to return an error like in unary calls (callback)? I didn't find a way to intercept the call on the server to handle this authentication in a better way.

Here is a basic example of what I'm doing:

```js
import {
  ServerDuplexStream
} from "@grpc/grpc-js";
import { SubscribeRequest, SubscribeResponse } from "./proto/my_service_grpc_pb";

class MyClass implements IMyServiceService {
  
  subscribe(call: ServerDuplexStream<SubscribeRequest, SubscribeResponse>) {
    const token = call.metadata.get("authorization")[0];
    if (token && !authenticate(token.toString())) {

      // How to return status and message?
      //
      // callback({
      //   code: status.UNAUTHENTICATED,
      //   message: "Unauthenticated",
      // });

      call.destroy(new Error("Unauthenticated")); // ???
      return;
    }

    call.on("data", (req: SubscribeRequest) => {
      // Do stuff
    });
  }
}
```

Thank you all!

**Comment by murgatroid99** [comment]
Use `call.emit('error', errorObject)` with the same kind of error object you would pass to the callback in a unary call.

**Comment by plitex** [comment]
Thank you!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
