### ISSUE TITLE
How to use proxy url with @grpc/grpc-js?

### ISSUE THREAD

**Issue by dougg0k** [grpc/grpc-node#2032]
Hi, is there a way to use in the Client part?

Like you see in packages like `got` https://github.com/sindresorhus/got/blob/main/documentation/tips.md#proxying

**Comment by murgatroid99** [comment]
You can do this by setting the `grpc_proxy` environment variable to `http://<proxy server url>`.

**Comment by dougg0k** [comment]
I was asking about doing it dynamically per request, directly in the code, is that possible? Like using a different one each request.

**Comment by murgatroid99** [comment]
There is an open feature request to add per-client proxy configuration: #1294.

> why read from env and not have a option in the client?

Because the most common use case is traversing a single static proxy that is the same for an entire process, such as a corporate proxy. So, that is what we focused on addressing.

**Comment by dougg0k** [comment]
I understand, alright then, thanks for the answers.
