### ISSUE TITLE
Client writable streams callbacks never contain an error.

### ISSUE THREAD

**Issue by Connor-Wallace** [grpc/grpc-node#2035]
### Problem description
When writing to a client writable stream with `stream.write` the callback never receives an error if one occurs.
```
stream.write(requestThatWillCauseError, (error) => {
// error is undefined
})
```
### Reproduction steps
Open a client writable stream. Write data to the stream that causes an error on the server with a callback.

### Environment
 - OS name, version and architecture: Linux Ubuntu 18.04
 - Node version: 16
 - Node installation method: nvm
 - Package name and version @grpc/grpc-js@1.15.3

**Comment by murgatroid99** [comment]
Pretty much any error that can be triggered there will be routed to the overall error handler for the stream, which in this case is the callback for the overall request.

**Comment by Connor-Wallace** [comment]
Doesn't that cause a loss of context for the error? In some cases it is beneficial to know which write caused the error.

**Comment by murgatroid99** [comment]
I wouldn't expect it to come up that much. The only kind of error that is associated with a particular outgoing message is a serialization error, and that's pretty much always a programming error which should be corrected and then never come up again.
