### ISSUE TITLE
Could not generate typescript type with @grpc/proto-loader

### ISSUE THREAD

**Issue by dongnguyenltqb** [grpc/grpc-node#2057]
### Problem description
I can not generate typescript type with proto-loader-gen-types CLI.
Show warning and error when run build:proto command.

### Reproduction steps
Dependency version
 @grpc/grpc-js": "^1.5.7", 
@grpc/proto-loader": "^0.6.9"

Project struct
Current Dir: **/Users/dong/Desktop/protobuf** 
Project Dir:
- **message**
     - user.proto
- **rpc**
    - user.proto
- **proto-gen**
- package.json

The **message** folder contain package **message** define all the message type
The **rpc** folder contain package **rpc** define all the rpc function, the *.proto file in **rpc** folder will import message type from **message** forder

For example:
The content of **message/user.proto**
```
syntax  = "proto3";

package message;

message AccessToken{
    string access_token = 1;
}

message Credentials{
    string username = 1;
    string password = 2;
}

message LoginResult{
    bool ok = 1;
    string error = 2;
    AccessToken data = 3;
}
```
The content of. `rpc/user.proto`
```
syntax = "proto3";

package rpc;

import "message/user.proto";

service User{
    rpc UserLogin(message.Credentials) returns (message.LoginResult){};
}
```

Purpose: I use grpc/proto-loader to load protobuf definition and build grpc server. I want to generate type to code with typescript.
I will generate type definition to forder *proto-gen*
The command in **package.json** i am using is
```
 "scripts": {
    "start": "nodemon index.js",
    "build:proto": "$(npm bin)/proto-loader-gen-types --longs=String --enums=String --defaults --oneofs --grpcLib=@grpc/grpc-js  --includeDirs=[\"/Users/dong/Desktop/code/share-proto/protobuf\"] --outDir=proto-gen/ message/*.proto rpc/*.proto"
  },

```

After i run npm run build:proto command i got this error
```
❯ npm run build:proto

> learngrpcjs@1.0.0 build:proto
> $(npm bin)/proto-loader-gen-types --longs=String --enums=String --defaults --oneofs --grpcLib=@grpc/grpc-js  --includeDirs=["/Users/dong/Desktop/code/share-proto/protobuf"] --outDir=proto-gen/ message/*.proto rpc/*.proto

(node:13143) Warning: message/user.proto not found in any of the include paths [/Users/dong/Desktop/code/share-proto/protobuf]
(Use `node --trace-warnings ...` to show where the warning was created)
(node:13143) Warning: rpc/user.proto not found in any of the include paths [/Users/dong/Desktop/code/share-proto/protobuf]
(node:13143) Warning: message/user.proto not found in any of the include paths [/Users/dong/Desktop/code/share-proto/protobuf]
[Error: ENOENT: no such file or directory, open 'rpc/message/user.proto'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'rpc/message/user.proto'
}
```
**Question: How can i build typescript type definition with this folder struct ?.

### Environment
 - OS name, version and architecture: MacOS 12.3 beta
 - Node version: v16.14
 - Node installation method : install from PKG file, download from nodejs.org
 - Package name and version :   "@grpc/grpc-js": "^1.5.7", "@grpc/proto-loader": "^0.6.9"

**Comment by dongnguyenltqb** [comment]
Thank guy, i solved by list exactly all the protobuf file which need to be compiled instead of using *.proto

**Comment by murgatroid99** [comment]
The error message that you got indicates that it is trying to load specific proto files, which would imply that the `*` expansion did work. The problem is that the `includeDirs` argument is not formatted correctly. You should just write `--includeDirs=<directory> <directory> ...`. So your command should just be

```
$(npm bin)/proto-loader-gen-types --longs=String --enums=String --defaults --oneofs --grpcLib=@grpc/grpc-js  --includeDirs=/Users/dong/Desktop/code/share-proto/protobuf --outDir=proto-gen/ message/*.proto rpc/*.proto
```
