### ISSUE TITLE
ResolvingLoadBalancer does not properly update the DNS resolution

### ISSUE THREAD

**Issue by rintaun** [grpc/grpc-node#2094]
### Problem description
`this.currentState` is never `IDLE` in `ResolvingLoadBalancer.exitIdle()`. This causes DNS re-resolution to not happen. The reason it is never `IDLE` is that `this.childLoadBalancer.exitIdle()` itself causes an update to `ResolvingLoadBalancer`'s `currentState`, so by the time it returns, `this.currentState` has already become `CONNECTING`.

### Reproduction steps
1. Enable trace logging and create a channel with a hostname target
2. Call `channel.getConnectivityState(true)`.
3. See that "Looking up DNS hostname" is present in the trace.
4. Wait the minimum configured re-resolution time or until the connectivity state returns to `IDLE`, whichever is longer.
5. Call `channel.getConnectivityState(true)`.
6. See that "Looking up DNS hostname" is not repeated in the logs. This demonstrates that even `updateResolution()` was not called, because `currentState` was not `IDLE`.

This can all also be accomplished with debugging and breakpoints and such, of course.

### Environment
 - Ubuntu 18.04 amd64
 - Node 16.13.2
 - Node installation method: nvm
 - Package name and version: @grpc/grpc-js@1.6.4

### Additional context
We originally encountered this problem while using an AWS ALB in front of our gRPC server. A day or so after starting the client, the client would suddenly be unable to connect to the gRPC server anymore, until the client was restarted. This appears to be because AWS is rotating out the IP addresses associated with the ALB (i.e. the DNS is changing). Trace logging revealed that the DNS lookup was only ever being performed once when we first connected to the gRPC server and never again. After a sufficiently long period of time (again, about a day), all of the IP addresses from the original DNS lookup would be rotated out and no longer apply to the gRPC server, making the client unable to connect.

### Suggested fix
A simple fix would be to have `ResolvingLoadBalancer.exitIdle()` only call `this.childLoadBalancer.exitIdle()` _after_ the `if` statement.

https://github.com/grpc/grpc-node/blob/a6f3df70aee0280119868787ae64729b1696eceb/packages/grpc-js/src/resolving-load-balancer.ts#L300-L310

i.e.

```typescript
 exitIdle() { 
   if (this.currentState === ConnectivityState.IDLE) { 
     if (this.backoffTimeout.isRunning()) { 
       this.continueResolving = true; 
     } else { 
       this.updateResolution(); 
     } 
     this.updateState(ConnectivityState.CONNECTING, new QueuePicker(this)); 
   } 
   this.childLoadBalancer.exitIdle(); 
 } 
```

I have confirmed via local testing that this works as expected (at least, how I expected it to).

**Comment by murgatroid99** [comment]
Thank you for reporting this. In theory, this was supposed to be handled by the `childLoadBalancer` calling `requestReresolution` when it fails to connect to its address list, but it looks like that code path in the `pick_first` load balancer may have become unreachable at some point.

**Comment by murgatroid99** [comment]
OK, I published that change in version 1.6.5. Please try it out.

**Comment by sirctseb** [comment]
thanks for the quick response @murgatroid99. we've deployed our services and are seeing logs for re-resolution when coming out of idle. i'll post back again after we have it running for a day or so (the time it took for the connection failure symptom to kick in in our deployed environment)

**Comment by sirctseb** [comment]
We are seeing that the library successfully resolves new ip addresses for our service as they change over the course of several days. Thanks @murgatroid99
