### ISSUE TITLE
Generated client method calls sometimes return null with no error.

### ISSUE THREAD

**Issue by ademuk** [grpc/grpc-node#2101]
## Problem description
Generated client method calls sometimes return `null` with no error.

```
const client = new GeneratedClient(
  'grpc-server-hostname',
  grpc.credentials.createInsecure()
);

client.listObjects(
  new ListObjectsRequest(),
  new Metadata(),
  { deadline: new Date(Date.now() + 10 * 1000) },
  (err, response) => {
    if (err) {
      return console.error(err);
    }

    return console.log(response.getObjectsList());
  },
)
```
### Notes
* ~50% of the time `response` will be `null` resulting in error `TypeError: Cannot read properties of null (reading 'getObjectsList')`. The other times it works fine and return all items.
* Only occurs with larger payload sizes. i.e. thousands of objects. Does not happen with smaller/single object requests.

### Debugging notes
* When it fails, the debugger never gets here https://github.com/grpc/grpc-node/blob/master/packages/grpc-js/src/stream-decoder.ts#L85 (would suggest not all bytes are received)
* But the stream is closed/ended here: https://github.com/grpc/grpc-node/blob/master/packages/grpc-js/src/call-stream.ts#L588

## Environment
macOS Big Sur 11.6 intel
Node version v12.16.1 v16.14.2
@grpc/grpc-js v1.6.6

**Comment by murgatroid99** [comment]
This is very similar to the problem that was reported in #2065. In that case, it was caused by a problem with their security software.

The requests should still end with an error when this happens, and I will fix that.

**Comment by ademuk** [comment]
@murgatroid99 thanks for you quick reply.
I saw that ticket which seemed very similar. The only thing is, I cannot reproduce this using `grpcurl`, with that the request returns correctly consistently.

**Comment by murgatroid99** [comment]
Can you put together a self-contained program that reproduces this consistently, or at least frequently? Our own tests with large messages don't do this, as far as I know.

**Comment by murgatroid99** [comment]
An update on this: as of version 1.6.7 of grpc-js, when a request ends with no message received, it will fail with an error instead of apparently succeeding with a `null` message.
