### ISSUE TITLE
1.6.6/master compile error with typescript 4.x

### ISSUE THREAD

**Issue by jimmypresto** [grpc/grpc-node#2107]
Compilation errors when using the typescript 4.x toolchain.

### Reproduction steps
1. cd packages/grpc-js
2. npm install
3. npm install typescript@4.6.3
4. npm run build

### Environment
 - OS name, version and architecture: MacOS 12.3.1 Intel architecture
 - Node version: 16.13.1
 - Node installation method: nvm
 - If applicable, compiler version
 - Package name and version gRPC@1.6.6 or gRPC master

### Additional context
Couple typescript files failing to transpile with typescript 4.x. Typescript 4.x enforces object's default type to be 'unknown', instead of 'any' and no implicit the argument value for the resolve call.

For examples using typescript 4.6.3, the transpilation errors are:
a. Object is of type 'unknown'
b. Argument of type 'unknown' is not assignable to parameter of type XYZ
c. Expected 1 arguments, but got 0. Did you forget to include 'void' in your type argument to 'Promise'?

**Comment by vladgorbachev** [comment]
@jimmypresto, the step to reproduce is the expected behavior while upgrading the version. Why upgrade it?
In the app project, package installed from npm. Typescript shouldn't check the version in node_modules. Or ignoring node_modules can be configured in tsconfig

**Comment by jimmypresto** [comment]
The use scenario is to consume libgrpc-js in nodejs apps with typescript 4.x. The steps are just to demo what the transpilation errors may look like.

**Comment by murgatroid99** [comment]
Consuming the library `@grpc/grpc-js` in an app that uses TypeScript 4.x can be more accurately simulated with something like this:

```
npm install @grpc/grpc-js typescript@4.x
echo 'import * as grpc from "@grpc/grpc-js";' > test.ts
./node_modules/.bin/tsc test.ts
```

This works without any errors, so I do not believe that there is any actual problem with that uses case.

**Comment by belivo** [comment]
Hi, this has been fixed here: https://github.com/grpc/grpc-node/issues/2113

**Comment by murgatroid99** [comment]
We now build the library using TypeScript 5, so this is now resolved.
