### ISSUE TITLE
Grpc-JS client attempts to Connect over IPv6 when no IPv6 Interfaces are present

### ISSUE THREAD

**Issue by rrichardson** [grpc/grpc-node#2118]
### Problem description
In a k8s pod with *no* IPv6 support, and only a single IPv4 Interface,  the grpc-js client will attempt to connect to IPv6 addresses when it resolves hosts that have both v4 and v6 addresses. 

I'm not entirely sure it's the fault grpc-js,  however, this just started happening today, and we just upgraded to grpc-js 1.6.7.
Our Node version hasn't changed.  We're running Node 16.13, and have been for many months. 

Our DNS resolver returns hosts in both A and AAAA.  But until very recently, our grpc-js client would only attempt to connect to IPv4 addresses, at least when running in a K8s pod which only has a single IPv4 interface. (plus ipv4 loopback)  

After enabling GRPC_TRACE=all and GRPC_VERBOSITY=debug  I notice that it seems to exclusively attempt to connect to IPv6 addresses. 

### Reproduction steps
Run in an environment with only IPv4 Interfaces. 
Resolve a DNS name that has both A and AAAA records. 
Client will attempt to connect to AAAA record. 

### Environment
 - K8s 1.18 in a node:16.13-alpine Docker container
 - Node 16.13
 - Docker / Alpine3
 - @grpc/grpc-js 1.6.7

### Additional context
```
D 2022-05-14T03:58:49.109Z | resolving_load_balancer | dns:myhost.co:2379 READY -> READY
D 2022-05-14T03:58:49.109Z | connectivity_state | (3) dns:myhost.co:2379 READY -> READY
D 2022-05-14T03:58:49.245Z | subchannel | (4) 2600:1f16:568:f701:6c41:6609:a9b3:f0a9:2379 TRANSIENT_FAILURE -> CONNECTING
D 2022-05-14T03:58:49.245Z | subchannel | (4) 2600:1f16:568:f701:6c41:6609:a9b3:f0a9:2379 creating HTTP/2 session
D 2022-05-14T03:58:49.246Z | subchannel | (4) 2600:1f16:568:f701:6c41:6609:a9b3:f0a9:2379 connection closed with error connect EADDRNOTAVAIL 2600:1f16:568:f701:6c41:6609:a9b3:f0a9:2379 - Local (:::0)
```

 I know node (17 I think?)  has recently switched to favor IPv6 addresses when found, but we are definitely not running 17.

**Comment by rrichardson** [comment]
Upon running a bit more,  I notice that it is not exclusively choosing IPv6 addresses.. It seems to be 50/50  (which would make sense, I think) 
When connecting to the IPv4 addresses, it succeeds. 

Is there a way to specify ipv4 only as a connection option?

**Comment by murgatroid99** [comment]
Whenever grpc-js tries and fails to connect to an IPv6 address, it should fall back to the IPv4 address after about a quarter of a second. Does this match what you are seeing? The first couple of lines of the log you shared show that the overall channel has a connection, which indicates that it did successfully fall back.

**Comment by rrichardson** [comment]
It does eventually succeed in connecting to an ipv4 address.  Is there a way to skip that step that is guaranteed to fail?

**Comment by murgatroid99** [comment]
I don't see any way to detect in Node that IPv6 is not available. So I think the best automatic option is to do what we're doing: attempt to connect to the address, and fall back if it doesn't work.

One alternative for you would be to use the round robin load balancing policy. That will force it to connect to all addresses immediately, but the downside is that it will keep trying to connect to the IPv6 address (with an exponential backoff). You can find an example of enabling round robin here: https://github.com/grpc/grpc-node/issues/1307#issuecomment-601312421.

Also, regarding your comment

> until very recently, our grpc-js client would only attempt to connect to IPv4 addresses

I do not know why this would be the case. grpc-js has preferentially connected to IPv6 address since at least as far back as version 1.0.

**Comment by murgatroid99** [comment]
I have to ask: this issue amounts to essentially a temporary extra socket and an added quarter-second delay on establishing the initial connection (over which many requests can then be made). Practically speaking, how much impact does that have on your usage?
