### ISSUE TITLE
Error: Not implemented. Use bindAsync() instead

### ISSUE THREAD

**Issue by tomasalles** [grpc/grpc-node#2133]
### Problem description
Code throws error: Error: Not implemented. Use bindAsync() instead at:
`server.bind(`127.0.0.1:${PORT}`, ServerCredentials.createInsecure())`

throw new Error('Not implemented. Use bindAsync() instead');
              ^

Error: Not implemented. Use bindAsync() instead
    at Server.bind (/home/sales/MEGAsync/projects/pc-command-grpc/server/node_modules/.pnpm/@grpc+grpc-js@1.6.7/node_modules/@grpc/grpc-js/build/src/server.js:200:15)
    at main (/home/sales/MEGAsync/projects/pc-command-grpc/server/dist/main.js:30:12)
    at Object.<anonymous> (/home/sales/MEGAsync/projects/pc-command-grpc/server/dist/main.js:34:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47

### Reproduction steps
main.ts code:

```
`import { loadPackageDefinition, Server, ServerCredentials } from "@grpc/grpc-js"
import { loadSync, Options } from "@grpc/proto-loader"
import "dotenv/config"
import { join } from "path"
import { ProtoGrpcType as CommandGrpcType } from "./proto/command"
import { CommandServiceHandlers } from "./proto/command/CommandService"

if (!process.env.PORT) {
  throw new Error("PORT not set!")
}
if (!process.env.PC_MAC_ADDRESS) {
  throw new Error("PC_MAC_ADDRESS not set!")
}

const { PORT } = process.env

const commandProtoPath = join(__dirname, "..", "proto", "command.proto")

const loaderOptions: Options = {
  keepCase: true,
  longs: String,
  enums: String,
  defaults: true,
  oneofs: true
}

const commandProtoDefinition = loadSync(commandProtoPath, loaderOptions)

const commandPackageDefinition = loadPackageDefinition(
  commandProtoDefinition
) as unknown as CommandGrpcType

const commandServiceHandlers: CommandServiceHandlers = {
  TurnOn() {}
}

async function main() {
  const server = new Server()
  server.addService(
    commandPackageDefinition.command.CommandService.service,
    commandServiceHandlers
  )

  server.bind(`127.0.0.1:${PORT}`, ServerCredentials.createInsecure())
  server.start()

  console.log(`listening on port ${PORT}...`)
}
main()`
```

### Environment
Linux Ubuntu 22.04 amd64
Node v16.15.0
Node installation method - nvm
@grpc/grpc-js@1.6.7

**Comment by tomasalles** [comment]
Can you please reopen?
Issue is not fixed.
I tried it, obviously, and it then throws:
Error: server must be bound in order to start

replaced the bind line to:

```
server.bindAsync(
    `127.0.0.1:${PORT}`,
    ServerCredentials.createInsecure(),
    (err, port) => {
      if (err) {
        console.log(err)
      }
      console.log(`listening on port ${port}`)
    }
  )
```

**Comment by nicolasnoble** [comment]
As with any async code, your subsequent `start()` call needs to be within the async callback, not sequentially.

**Comment by tomasalles** [comment]
Nice, it now works!
Hmmm, I think this is a documentation problem then...
I was refering to https://grpc.github.io/grpc/node/grpc.Server.html 
and it clearly states: 
```
var server = new grpc.Server();
server.addProtoService(protobuf_service_descriptor, service_implementation);
server.bind('address:port', server_credential);
server.start();
```

**Comment by nicolasnoble** [comment]
Right, this documentation is outdated. This is for the previous, C-based module. We need to update it, for sure.

**Comment by tomasalles** [comment]
OK, anywhere I can reference the new package (@grpc/grpc-js) docs?
TYVM for your help, it now works.
