### ISSUE TITLE
Update healthcheck to use `@grpc/grpc.js` instead of deprecated `grpc`

### ISSUE THREAD

**Issue by mic-max** [grpc/grpc-node#2142]
### Problem description
The healthcheck module currently depends on the npm package grpc - ref: [package.json](https://github.com/grpc/grpc-node/blob/master/packages/grpc-health-check/package.json#L19)

The [grpc package on npm](https://www.npmjs.com/package/grpc) states that it is deprecated and to use [@grpc/grpc-js](https://www.npmjs.com/package/@grpc/grpc-js) instead.

### Additional context
I noticed this warning when running `npm ci` on a project of mine that depended on `grpc-health-check`. Which brings up the fact that after making this change a new release for that package should be performed.

I'm willing to attempt to fix this (hoping it's a drop in replacement) if nobody objects to the idea 😄

**Comment by TrumanRu** [comment]
#[926]

**Comment by mic-max** [comment]
Duplicate.
