### ISSUE TITLE
'UntypedHandleCall' is not defined

### ISSUE THREAD

**Issue by eliw00d** [grpc/grpc-node#2178]
### Problem description
For some reason, I am getting eslint errors for adding `[name: string]: grpc.UntypedHandleCall` to my implementation of an interface that extends `grpc.UntypedServiceImplementation`:

![image](https://user-images.githubusercontent.com/1801127/182623145-ca210741-5fd4-4886-81dc-8c3c4153c5e9.png)

### Reproduction steps
```typescript
import * as grpc from '@grpc/grpc-js'

interface ISomeServer extends grpc.UntypedServiceImplementation {}

class SomeServer implements ISomeServer {
  [name: string]: grpc.UntypedHandleCall
}
```

### Environment
 - OS name, version and architecture: `macOS Monterey 12.4 x86`
 - Node version `v16.13.0`
 - Node installation method `nvm`
 - If applicable, compiler version [e.g. clang 3.8.0-2ubuntu4]
 - Package name and version `"@grpc/grpc-js": "^1.4.2"`

### Additional context
This only seems to happen in the class that implements the interface. If I define something outside of the class, like:
```typescript
type UntypedHandleCall = grpc.UntypedHandleCall
```
it does not have the error.

**Comment by murgatroid99** [comment]
That reproduction code doesn't reproduce the error for me with the latest version of grpc-js. I compiled it with the typescript compiler and loaded it in VSCode, both without errors.
