### ISSUE TITLE
is it possible to let multiple service share one client?

### ISSUE THREAD

**Issue by yunfan** [grpc/grpc-node#2214]
hi, i had checked the example showing how to call a rpc function located at one single service, it will need to create a service specific client, the problem is if i had a grpc server which hold multiple services, can i create a one client connection to this server, and then use it to call different rpc functions of different services?

i had saw people use  addService to register service at server side, which could accept multiple service of course. so how does the client side ?

**Comment by murgatroid99** [comment]
If you create multiple client objects pointing to the same server with the same connection options, they will share connections by default. Alternatively, if you want to share connections explicitly, you can construct a single `Channel` object, and then pass it as the `channelOverride` option when constructing each client.

**Comment by yunfan** [comment]
> If you create multiple client objects pointing to the same server with the same connection options, they will share connections by default. Alternatively, if you want to share connections explicitly, you can construct a single `Channel` object, and then pass it as the `channelOverride` option when constructing each client.

thanks, but i think i havnt expressed my meaning. what i need is for each server, i only create one client, and use this client to invoke the sub service belong to it

like 
```
const client = createSingleConnection(host)
client.invokeServiceA.xxxx
client.invokeServiceB.yyyy
```

**Comment by murgatroid99** [comment]
A single client object is associated with a single service by design. That is not going to change. If your goal is just to access multiple services using the same underlying connection(s), the options I already described are the ones available to accomplish that. The difference between what I described and what you described is really just syntactic sugar, and you can make up that difference by creating a simple wrapper object and a simple wrapper function. It would be something like this:

```ts
function createSingleConnection(host) {
  const channel = new grpc.Channel(host, credentials);
  const clientA = new ServiceAClient(host, credentials, {channelOverride: channel});
  const clientB = new ServiceBClient(host, credentials, {channelOverride: channel});
  return {
    invokeServiceA: clientA,
    invokeServiceB: clientB
  };
}
```

**Comment by yunfan** [comment]
ok

**Comment by yunfan** [comment]
i had use the latter pattern, but that is meaningless to me. if i still need to gave the host and credentials params when using a channelOverride . unfortunately i cant omit these two params

**Comment by yunfan** [comment]
@murgatroid99

**Comment by murgatroid99** [comment]
It doesn't matter. Just use the same values you used to construct the Channel.
