### ISSUE TITLE
Reconnect not working as expected

### ISSUE THREAD

**Issue by arrin00** [grpc/grpc-node#2218]
### Problem description
When destination servers stopped,  Client tries only once or twice, then stop retrying.

I expected it to keep retrying with exponential backoff until the server restarted and a connectivity state is READY. The actual behavior is that after 1 or 2 retries, it goes into IDLE state and does not retry.

### Reproduction steps
a) try only once
1. stop a destination server
2. create client
3. client.getChannel().getConnectivityState(true)

b) try only twice
1. create client
2. client.getChannel().getConnectivityState(true)
3. stop a destination server
4. client.getChannel().getConnectivityState(true) // in step.3 state goes to IDLE, therefore necessary to connect explicitly

### Environment
 - CentOS 7.9
 - Node version 14.16.1
 - Node installation method nodenv
 - Package name and version @grpc/grpc-js 1.6.10

**Comment by arrin00** [comment]
SubChannel.continueConnecting initiate by false and is set to false when connecting state goes into CONNECTING. therefore connecting state goes to IDLE when backoff timer timed out.
Is this the intended behavior?

**Comment by murgatroid99** [comment]
The client attempts to connect to the server as long as the client has a pending request. The `getConnectivityState(true)` makes the channel behave as though a new request was started, but only once. It doesn't actually create a pending request, so the channel goes back to IDLE after a single connection attempt.

Instead of calling `getConnectivityState(true)`, you should just make the request you want to make. That will get the behavior you want.

**Comment by arrin00** [comment]
thank you, [murgatroid99](https://github.com/murgatroid99).

I'm developing a REST service that sends requests to a backend grpc service.

For high availability, my service connects to several grpc servers. So I thought I'd use client-side LB of grpc-js.
But the grpc servers each have a different name and tls ca certificate, so the LB feature seems inapplicable to my service.
So I implemented a simple LB that creates a grpc client for each grpc server and only uses clients in the READY state.

I understand that to keep these clients in the READY state, I need to implement reconnecting the clients in the IDLE state and retrying with backoff, explicitly.

Please let me know if I misunderstand or if there is a better way.

**Comment by murgatroid99** [comment]
You don't need to implement the backoff yourself. grpc-js only resets its backoff timer when the subchannel is READY, so you just need to keep calling `getConnectivityState(true)` and grpc-js will do the rest. A simple way to do that is using the `watchConnectivityState` method, which would look something like this for each channel:

```ts
const kickChannel = () => {
  const state = channel.getConnectivityState(true);
  channel.watchConnectivityState(state, Infinity, kickChannel);
}
kickChannel();
```

**Comment by arrin00** [comment]
Thank you for giving me good advice.
I have solved my issue with the code you gave me.
