### ISSUE TITLE
Missing node-precompiled-binaries 

### ISSUE THREAD

**Issue by zibra** [grpc/grpc-node#2229]
### Problem description
My project started to fail few days ago because of missing protoc prebuild packages:
<img width="1358" alt="obraz" src="https://user-images.githubusercontent.com/4493100/191023560-a413559f-c65a-46af-a8e5-ab78e928d4e4.png">

Probelatic link in my case: https://node-precompiled-binaries.grpc.io/grpc-tools/v1.11.2/linux-arm64.tar.gz

Looks like: https://node-precompiled-binaries.grpc.io/ contains only version from 0.14 to 1.6 now.

**Comment by murgatroid99** [comment]
That package does not have ARM binaries. See issue #1405 for more discussion of this topic.
