### ISSUE TITLE
Performance loss since @grpc/grpc-js version 1.6.8

### ISSUE THREAD

**Issue by antonstefer** [grpc/grpc-node#2231]
### Problem description
I use @google-cloud/bigtable which depends on @grpc/grpc-js through grpc-gcp and google-gax (maybe in more ways). When updating from 1.6.7 to 1.6.8 or any version above that, bigtable calls (especially ReadRows queries) get significantly slower (about 100% on average).

### Reproduction steps
Use bigtable with both of the above versions and perform ReadRows queries on tables.

### Environment
 - Google Cloud, Kubernetes Cluster, Container-Optimized OS from Google 
 - node:16-alpine docker image
 - @grpc/grpc-js@1.6.8 or above
 - google managed bigtable instance

### Additional context
As this is only a performance issue we do not see any error logs. We have created trace analysis reports using the google cloud platform which show the difference in execution time.

before:
<img width="935" alt="before" src="https://user-images.githubusercontent.com/59652072/191322163-bc8878e9-3394-4684-9f83-4f8defe78b81.png">

after:
<img width="935" alt="after" src="https://user-images.githubusercontent.com/59652072/191322159-2759f75a-b68f-4a46-9b60-9be2b75f74cf.png">

**Comment by murgatroid99** [comment]
I published grpc-js version 1.7.1 with a change that will hopefully improve this situation. Please try it out.

**Comment by antonstefer** [comment]
It works, thank you so much!
