### ISSUE TITLE
Cancelling a client stream throws CANCELLED: Cancelled on client

### ISSUE THREAD

**Issue by Ganitzsh** [grpc/grpc-node#2233]
### Problem description

Calling the `cancel` method of a ClientReadableStream causes a `CANCELLED: Cancelled on client` error on the client to be thrown.

I cannot find a clean way to close a ClientStreams that never ends. The only way I found to do this in a "clean" way is to expect the error before cancelling and suppressing it doing `stream.removeAllListeners().once('error', () => suppress the error here)`

### Reproduction steps

Given the current rpc: `  rpc WatchPerson(WatchPersonRequest) returns (stream WatchPersonResponse);` that indefinitely sends updates on a `Person` resource

I tell the server that the client will stop listening to the chunks the server is streaming. I couldn't find anything else than the `cancel` method of the `ClientReadableStream`

### Environment
 - OS name, version and architecture: consistent on any docker image or os I've tried
 - Node version 16.17.0
 - Node installation method nvm
 - Package name and version:
 ```
"dependencies": {
    "@grpc/grpc-js": "^1.7.0",
    "@grpc/proto-loader": "^0.7.2"
  }
```

### Additional context

Just the stack trace:

```
Error: 1 CANCELLED: Cancelled on client
    at Object.callErrorFromStatus (/.../node_modules/@grpc/grpc-js/src/call.ts:81:17)
    at Object.onReceiveStatus (/.../node_modules/@grpc/grpc-js/src/client.ts:596:32)
    at Object.onReceiveStatus (/.../node_modules/@grpc/grpc-js/src/client-interceptors.ts:424:48)
    at //node_modules/@grpc/grpc-js/src/call-stream.ts:330:24
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
for call at
    at ServiceClientImpl.makeServerStreamRequest (/node_modules/@grpc/grpc-js/src/client.ts:580:26)
    at ServiceClientImpl.<anonymous> (/node_modules/@grpc/grpc-js/src/make-client.ts:189:15)
    at callServer (/src/client.ts:32:12)
    at Object.<anonymous> (/src/client.ts:44:1)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Module.m._compile (/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Object.require.extensions.<computed> [as .ts] (/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12) {
  code: 1,
  details: 'Cancelled on client',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} }
}
```
Also, if I just kill the client, the server keeps sending data to the stream and doesn't even know that there's no one on the other side.

**Comment by murgatroid99** [comment]
The point of a call that streams from the server is that the server decides how much data to send and when to stop sending. If you want the client to have a way to indicate that the server should stop streaming after it starts, you probably want to use a duplex stream.

Also, the server should be able to listen for a `cancelled` event (or some equivalent if it's in another language) to know if it needs to stop sending. This should work both for explicit cancellations and if the client disconnects.

Finally, you should always have an `error` listener on a call, to handle any errors that may occur. There's no reason to remove the other listeners when you add it.

**Comment by Ganitzsh** [comment]
Yes, I figured it was the point of client streams, the issue is that in case the client somehow has an issue the server cannot know if something happened and keeps sending data without getting any errors.

Even though the client was disconnected, the streams never end and keep using memory over time.

I am just wondering why calling `cancel` throws an error. The `removeAllListeners` is used just before calling cancel like this:
```
stream
  .removeAllListeners()
  .once('error', () => suppress the error here)
  .cancel();
```
So that I know it's not a "real" error.

**Comment by murgatroid99** [comment]
Cancelling a call causes it to end with an unsuccessful status because it didn't end with a successful status. It only throws an error because you don't have an `error` handler, and you should always have an `error` handler. You shouldn't install a separate `error` handler to cancel a call, you should just properly handle the `CANCELLED` status code in your regular error handler.

Closing a client performs a kind of graceful shutdown. It informs all currently connected servers that no further requests will be sent and it stops creating new connections, so that once all existing streams finish, the connections will automatically be discarded.

**Comment by Ganitzsh** [comment]
Okay, thanks for the clarification, it makes much more sense now. Closing this one
