### ISSUE TITLE
Missing darwin-x64 node binary for grpc-tools 1.11.3

### ISSUE THREAD

**Issue by josephharrington** [grpc/grpc-node#2238]
### Problem description
The new release of `grpc-tools@1.11.3` seems to be missing darwin-x64 precompiled binary.

The darwin-x64 binary for `1.11.2` is available. And `1.11.3` does have the darwin-arm64 binary (🎉), but seems to be missing the darwin-x64.

### Reproduction steps
```
curl -Of https://node-precompiled-binaries.grpc.io/grpc-tools/v1.11.3/darwin-x64.tar.gz
curl: (22) The requested URL returned error: 404
```

### Environment
 - OS name, version and architecture: Mac OS / x86_64
 - Node version: 12.x
 - Node installation method: nvm
 - If applicable, compiler version: NA
 - Package name and version: grpc-tools@1.11.3

**Comment by murgatroid99** [comment]
This should work now. That file existed, but it looks like there was a name error in the build script and it ended up at the wrong URL. I've fixed this one manually, and I'll fix the build script before the next release.

**Comment by josephharrington** [comment]
Works now! Thank you!!
