### ISSUE TITLE
gRPC client requests fail with "Deadline exceeded" after update client Node version from 16 to 18

### ISSUE THREAD

**Issue by dandan3o3** [grpc/grpc-node#2257]
### Problem description
gRPC client requests fail with "Deadline exceeded" after updating the client Node version from 16 to 18.

### Reproduction steps
The server side is a Java service and the client side is a nodeJS app. After a recent upgrade to Node 18, all gRPC requests are failing with errors `{"code":4,"details":"Deadline exceeded","metadata":{}}}}`

### Environment
 - OS name: ubuntu 22.04 x64
 - Node version: 18
 - @grpc/grpc-js: 1.6.9

### Additional context
There is a commit in the repo that disables testing against Node 18. Is there any known issue? 
Commit "Don't test on Node18 yet": https://github.com/grpc/grpc-node/commit/223bf8f4b04bdb412b55bc14146f86c228a682f7

**Comment by murgatroid99** [comment]
That change you linked was about some build errors. It didn't get to the point of testing for the kind of problems you are reporting.

I just ran the library's tests manually with Node 18 and they don't experience this bug with deadlines. Can you provide some code that reproduces the problem, ideally using just Node?

**Comment by dandan3o3** [comment]
Hi @murgatroid99, 
We pin down the issue to another change on the Client side, which has nothing to do with the usage of the grpc-js library but would lead to this error since it spans the channel with lots of requests. 

Thanks for looking into this, good to know Node 18 is compatible. :D

**Comment by dandan3o3** [comment]
not an issue.
