### ISSUE TITLE
[QUESTION] Change :path: from headers

### ISSUE THREAD

**Issue by osyduck** [grpc/grpc-node#2264]
does anyone know how to change or set :path: , :authority: , & :method: from grpc-node?

**Comment by murgatroid99** [comment]
The `:path` header is determined by the method definition object that corresponds to the method you are calling in the service definition used to construct the client object. The only way to change it is to change that definition.

The `:authority` header can be changed for an entire client/channel by setting the channel option `grpc.default_authority`, or it can be changed for an individual request by setting the `host` option.

The `:method` header is required to have the value `POST` by the gRPC protocol specification. That cannot be changed.
