### ISSUE TITLE
Feature Request: Force grpc client to resolve DNS

### ISSUE THREAD

**Issue by CristianBB** [grpc/grpc-node#2265]
### Is your feature request related to a problem?
When using round_robin load balancing on GRPC client on a kubernetes cluster with autoscaling rules, clients never pick new replicas if current channels are always available, so autoscaling has no real effectivity here.

### Describe the solution you'd like
There is two different possible alternatives:

- Based on GRPC specs, make params `grpc.max_connection_age_ms`  and `grpc.max_connection_age_grace_ms` available in `@grpc/grpc-js` server config. In that way clients will receive the GOAWAY signal and will be forced to resolve again DNS addresses.
- Not defined into GRPC specs but I think would be better and easier to implement an interval on clients to force them to resolve DNS. In that way there is no need to force channels to be disconnected (that could affect in multiple ways to processes) and we have the possibility to define the interval when DNS will be resolved again

**Comment by murgatroid99** [comment]
You are correct that the recommended way to trigger resolution updates is to use the `grpc.max_connection_age_ms` setting, and also that that feature is not currently implemented in the `@grpc/grpc-js` library. I will treat this issue as a feature request to implement that feature.

**Comment by CristianBB** [comment]
Thank you @murgatroid99 ! In that case I've updated the issue title and description to have it properly tracked.

I really think that second choice would be better and easier to implement, but as it's not defined on GRPC specs I'm not sure if would be possible

**Comment by murgatroid99** [comment]
The `grpc.max_connection_age_ms` and `grpc.max_connection_age_grace_ms` options are now supported in the v1.8.0 release, so I am considering this issue resolved. If you still want a different behavior that is not currently specified, please file a separate feature request.
