### ISSUE TITLE
Content-type header not sent on trailers-only response

### ISSUE THREAD

**Issue by nadavwe** [grpc/grpc-node#2300]
### Problem description
when a server returns with an error, a trailers-only response is generated back to the client.
this response does not include the needed content-type header as directed by [grpc protocol](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md#responses).
 
### Reproduction steps
see full example in https://github.com/hugebdu/grpc-js_1_8.

this is found in 1.8.0 and is a regression from 1.7.3.

@hugebdu

**Comment by travisghansen** [comment]
Indeed this makes all my ci tests blow up: https://github.com/democratic-csi/democratic-csi/actions/runs/3746781480/jobs/6362393102

Seems to likely be the same issue. `  unexpected error: OK: HTTP status code 200; transport: missing content-type field`

**Comment by murgatroid99** [comment]
I have published a fix for this in version 1.8.1.
