### ISSUE TITLE
[question] How to make the client deserialize responses into "full" objects?

### ISSUE THREAD

**Issue by adi-code** [grpc/grpc-node#2324]
Hello,

Is it possible to make `grpc.Client` return always "full" response objects instead of `{}`? For example:

```protobuf
syntax = "proto3";

package com.iot.devices;

message DeviceIdentifier {
  int64 tenantId = 1;
  string deviceId = 2;
}

message Device {
  DeviceIdentifier deviceId = 1;
  string name;
}

message DeviceRequest {
  repeated string deviceIds = 1;
}

message DeviceResponse {
  repeated Device devices = 1;
  int64 total = 2;
}

service DeviceApi {
  rpc GetDevices (DeviceRequest) returns (DeviceResponse);
}
```

Request (devices with those ids don't exist):
```json
{
    "deviceIds": ["1", "2", "3"]
}
```

Expected response (no such devices):
```json
{
    "devices": [],
    "total": 0
}
```

Actual response:
`{}` (empty object)

I see some grpc clients return the full object (e.g. Insomnia), some return just `{}`.

I'm using a client generated by:
`proto-loader-gen-types --longs=String --enums=String --defaults --oneofs --grpcLib=@grpc/grpc-js --outDir=src/generated com/iot/devices/api.proto --includeDirs=src/lib/proto`

```typescript
const packageDefinition = protoLoader.loadSync(
    'com/iot/devices/api.proto',
    { includeDirs: [__dirname + '/../proto/'] },
);
const proto = loadPackageDefinition(packageDefinition) as unknown as ProtoGrpcType;
const client = new proto.com.iot.devices.DeviceApi(
    grpcUrl,
    credentials.createSsl(),
    {
        callInvocationTransformer: (callProperties) => ({
            ...callProperties,
            callOptions: { ...callProperties.callOptions, deadline: Date.now() + (timeoutMillis ?? 10000) },
        }),
    },
);
```

Can I make generated client always return full objects?

Thanks,
Adrian

P.S. Sorry if it's documented somewhere, I was looking for such information but haven't found anything.

**Comment by murgatroid99** [comment]
Your `protoLoader.loadSync` options don't match your `proto-loader-gen-types` options. If you fix that it will include the `defaults` option which does exactly what you want.

**Comment by adi-code** [comment]
Hi @murgatroid99,

After changing `protoLoader.loadSync` to:
```typescript
const packageDefinition = protoLoader.loadSync(
    'com/iot/devices/api.proto',
    {
        includeDirs: [__dirname + '/../proto/'],
        longs: String,
        enums: String,
        defaults: true,
        oneofs: true,
    },
);
```

to match options provided to `proto-loader-gen-types --longs=String --enums=String --defaults --oneofs --grpcLib=@grpc/grpc-js --outDir=src/generated com/iot/devices/api.proto --includeDirs=src/lib/proto`, it works as expected.

Thank your very much!
