### ISSUE TITLE
retry maxAttempts limited to 5

### ISSUE THREAD

**Issue by kaedwen** [grpc/grpc-node#2326]
### Problem description
We need to configure a retry maxAttempts limit of 10 in our scenario. Why is there a max limit of 5 hardcoded 2 months ago? If the client is configured with `maxAttempts: 100` and there are resource issues then this is up to the user to handle this.

https://github.com/grpc/grpc-node/commit/fa21e13ef38dd7cbc44fd1156fd97169c876025e

### Additional context
Maybe I do not understand the root cause and if you have a good explanation why it would help a lot.

**Comment by murgatroid99** [comment]
The limit of 5 is in the spec, explained [here](https://github.com/grpc/proposal/blob/master/A6-client-retries.md#limits-on-retries-and-hedges). The spec does say that the limit can be configured on the client, but this library's implementation is based on the C core implementation, which does not have those configuration options.

I'll treat this as a feature request to add those options.

**Comment by kaedwen** [comment]
Ok there is a proposal which says that there is a client side max of 5. But it can be adjusted in the channel settings. Where do I have to provide these settings?

The C core impl is the underdaying client core right? If I patch out the max restriction in your js impl the core is retrying more than 5 times. So I do not understand why to restrict than in js.

If the C core would be implemented correctly and could be configured via channel arguments to support more than 5 times, then I would accept the highlevel restriction. But how should this be possible when the js impl would stop after max 5 attempts but the C core is configured to do more. It won't get any further requests then?

**Comment by murgatroid99** [comment]
What I'm saying here is that the channel argument to adjust the client side maximum number of retries is not implemented, and that I will treat this issue as a feature request to add that functionality.

The JS library is not based on the core in the sense that it uses the core, but in the sense that the design and implementation are derived from earlier work in the core library.

**Comment by Oliver-Piorun** [comment]
Thanks for creating this issue @kaedwen. This change broke our app which is trying to reconnect an infinite number of times. I would be glad if the decision would be reconsidered.

Greetings!

**Comment by murgatroid99** [comment]
Version 1.11.0 now has an option `grpc-node.retry_max_attempts_limit` to configure this option.
