### ISSUE TITLE
Add JSDoc comment to mark fields as deprecated in output interfaces

### ISSUE THREAD

**Issue by danielronnkvist** [grpc/grpc-node#2348]
### Is your feature request related to a problem? Please describe.
It would be useful to get JSDoc comments when marking a field as deprecated like this:
```proto
uint32 count = 1 [deprecated = true];
```

### Describe the solution you'd like
The output interface would get the `@deprecated` comment added to the field.
```ts
/** @deprecated */
count: number;
```

### Describe alternatives you've considered
It could be an option when generating if these comments should be included or not.

**Comment by murgatroid99** [comment]
This seems like a reasonable idea, and it looks like the `deprecated` option also exists on other things such as message definitions. So, I think it would make the most sense to add this annotation to everything that can have that option.

I don't know when I'm going to have time to prioritize making this change, but we're happy to accept contributions if you (or anyone) would like to make the change yourself.
