### ISSUE TITLE
TypeError : Cannot destructure property 'HTTP2_HEADER_STATUS' of 'http2.constants' as it is undefined.

### ISSUE THREAD

**Issue by kody435** [grpc/grpc-node#2364]
<img width="957" alt="Screenshot 2023-02-15 at 5 43 35 PM" src="https://user-images.githubusercontent.com/50862704/219024434-453d76ad-e210-4471-adda-8e89660b7692.png">
I am using it in Next.js project and it's throwing error as the photo above

<img width="162" alt="Screenshot 2023-02-15 at 5 45 12 PM" src="https://user-images.githubusercontent.com/50862704/219024780-c3a8f59b-99fc-4c0f-b698-7756ef1ed110.png">
This is the photo of package.json, I tried adding these to make it work, as they were keep the throwing error.

**Comment by murgatroid99** [comment]
The `@grpc/grpc-js` library only works on Node.js and runtimes built on it such as Electron. That error indicates that you are trying to run it on an unsupported platform.

**Comment by kody435** [comment]
> The `@grpc/grpc-js` library only works on Node.js and runtimes built on it such as Electron. That error indicates that you are trying to run it on an unsupported platform.

I am using it on Next.js, then it should be working fine, right?

**Comment by apoorva-saxena** [comment]
Sorry, but what was the resolution on this? I am getting the same error on next js project

**Comment by murgatroid99** [comment]
If you are getting this error, that means that you are trying to use this library on an unsupported platform. If you are trying to use gRPC in a browser, this library will not work for that, and you should instead use [grpc-web](https://github.com/grpc/grpc-web).
