### ISSUE TITLE
typescript mode

### ISSUE THREAD

**Issue by gitsupi** [grpc/grpc-node#2366]
it is very hard to auto complete and resuse protobuff service and rpc(s)
we can not add proto service to grpc server and using it in stub....

there is no suggetion in vscode coding 
for example adding a new service is not possible east
```

server.addService(hello_proto.Xapi.service, {
        CreateAccount: createAccount
    })

```

![image](https://user-images.githubusercontent.com/65791341/219324643-3747c2f7-2d08-461d-9ee3-a72d08295ebc.png)

**Comment by gitsupi** [comment]
we can not find proto's service , rpc 
there is no finding methods and structure

**Comment by murgatroid99** [comment]
It looks like you are using the `@grpc/proto-loader` library. If so, you can generate TypeScript information for the loaded protobuf objects. See the **Generating TypeScript types** section of [that library's documentation](https://www.npmjs.com/package/@grpc/proto-loader) for more information.
