### ISSUE TITLE
Adding mirrors for our binaries.

### ISSUE THREAD

**Issue by hrdwdmrbl** [grpc/grpc-node#238]
During the install process, an attempt is made to access

https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.8.4/node-v57-darwin-x64-unknown.tar.gz

Unfortunately as you likely know, all Google APIs are blocked from China. Would it be possible to fall back to compiling those binaries? Or else to host the files in a non-Google domain?

**Comment by hrdwdmrbl** [comment]
Actually, it does fall back to compiling. I will close this issue. I might still ask that it fall back faster, as I was able to file this issue before it began the fallback :)

**Comment by nicolasnoble** [comment]
We might still want to add mirrors in locations that aren't blocked...

**Comment by poppinlp** [comment]
Hi. How's it going? That's really a pain for install grpc on node right now. :)

**Comment by nicolasnoble** [comment]
We've just added a mirror actually, and 1.14.0-pre1 is using it. Could you please give it a try and tell us if it works better for you?

**Comment by murgatroid99** [comment]
In addition, the previous versions are also on the mirror, so you should be able to use it with the existing packages with `npm install --grpc_node_binary_host_mirror=https://node-precompiled-binaries.grpc.io/`.

**Comment by poppinlp** [comment]
@nicolasnoble  @murgatroid99 
Hi. I have tried that mirror and it works for me. That's really help. Thanks.

**Comment by poppinlp** [comment]
BTW maybe you could add some description of your mirror source in [README](https://github.com/grpc/grpc-node/tree/master/packages/grpc-native-core)? :)

**Comment by nicolasnoble** [comment]
Good. This is going to be the main download location for the binaries from now on.
