### ISSUE TITLE
Server waits for all RPCs to be handled before sending back responses

### ISSUE THREAD

**Issue by goelayu** [grpc/grpc-node#2384]
### Problem description
When a server receives multiple RPCs from a client, instead of sending back responses as it processes the requests, it seems to send back responses only after completing all the requests. This seems extremely strange to me, and I'm wondering if there is something wrong with my configuration. 

### Reproduction steps
I have an extremely minimal deployment. Following are relevant code snippets

proto file:
```
service Rewriter {
  rpc Test(TestRequest) returns (TestResponse) {} // both arg and response contain a single string field
}
```

server.js registers a single RPC method
```
var _test = function () {
 // multi second CPU computation
  return { content: "test" };
};

var test = function (call, callback) {
  callback(null, _test());
};

var server = new grpc.Server();
server.addService(rewriter.Rewriter.service, {
    test: test,
  });
server.bindAsync(
  `0.0.0.0:1234`,
  grpc.ServerCredentials.createInsecure(),
  () => {
    server.start();
  }
```
client.js
```
var client = new rewriter.Rewriter(
  "localhost:1234",
  grpc.credentials.createInsecure()
);
client.test() // called 10 times
```
The 10 callback for 10 `client.test()` calls get fired only after server has processed all the 10 requests. I would expected each callback to be fired sequentially, as the server iteratively processes each request. 

### Environment
 - OS name, version and architecture: [e.g. Linux Ubuntu 18.04 amd64] Linux Ubuntu 18.04
 - Node version [e.g. 8.10.0] Node16
 - Package name and version [e.g. gRPC@1.12.0] gRPC@1.16

**Comment by goelayu** [comment]
To help debug this better, here is a trimmed copy of the trace logs
```
Listening on port 1234...
D 2023-03-07T16:05:01.296Z | server | (1) Received call to method /rewriter.Rewriter/Test at address null
D 2023-03-07T16:05:01.302Z | server | (1) Received call to method /rewriter.Rewriter/Test at address null
D 2023-03-07T16:08:40.194Z | server_call | Request to method /rewriter.Rewriter/Test ended with status code: OK details: OK
D 2023-03-07T16:10:13.809Z | server_call | Request to method /rewriter.Rewriter/Test ended with status code: OK details: OK
D 2023-03-07T16:11:15.697Z | server_call | Request to method /rewriter.Rewriter/Test stream closed with rstCode 0
D 2023-03-07T16:27:48.956Z | server_call | Request to method /rewriter.Rewriter/Test stream closed with rstCode 0
```
So the server processes the two requests, and then closes both the streams at the end. Only when it closes the stream, is when the client receives the messages. Ideally the client should receive the message, the moment the server was done with the request?

**Comment by murgatroid99** [comment]
This small log isn't really enough to determine anything specific. It would be a lot more helpful if I could see the complete client and server logs with all tracers enabled and/or your complete test code.

**Comment by goelayu** [comment]
@murgatroid99 Thanks for the response. Let me get my conceptual understanding right, and then I can proceed to share more information about the code. 
(1) Given the grpc server is implemented in node, it can at best execute a single RPC request. When a client sends two request at the same time, the server will receive both these requests, push them in an event loop, and continue waiting for other incoming requests. 
The server then iterates over the requests in the event loop --> takes  a request, invokes the appropriate handler, and issues the callback, or in other words sends back the response. Then it moves to the next request in the queue. 

(2) What I am observing is that only after it clears out the queue, i.e., processes all the requests, it starts issuing the responses. 

Is my understanding (1) correct, and if so, should I be observing (2)?

**Comment by goelayu** [comment]
My client and server test code:
server.js
```
const grpc = require("@grpc/grpc-js");
const protoLoader = require("@grpc/proto-loader");
const packageDefinition = protoLoader.loadSync("./rewriter.proto", {
  keepCase: true,
  longs: String,
  enums: String,
  defaults: true,
  oneofs: true,
});

var rewriter = grpc.loadPackageDefinition(packageDefinition).rewriter;

var _test = function () {
// expensive computation -- takes around 1s
  for (var i = 1; i < 1000000000; i++) {
    var x = i * i;
  }
  return { content: "test" };
};

var test = function (call, callback) {
  callback(null, _test());
};

var getServer = function () {
  var server = new grpc.Server();
  server.addService(rewriter.Rewriter.service, {
    rewrite: rewrite,
    test: test,
  });
  return server;
};

var rewriterServer = getServer();
rewriterServer.bindAsync(
  `0.0.0.0:${program.port}`,
  grpc.ServerCredentials.createInsecure(),
  () => {
    console.log(`Listening on port ${program.port}...`);
    rewriterServer.start();
  }
);
```
test-client.js
```
const grpc = require("@grpc/grpc-js");
const protoLoader = require("@grpc/proto-loader");
const packageDefinition = protoLoader.loadSync("./rewriter.proto", {
  keepCase: true,
  longs: String,
  enums: String,
  defaults: true,
  oneofs: true,
});

var rewriter = grpc.loadPackageDefinition(packageDefinition).rewriter;

var client = new rewriter.Rewriter(
  "localhost:1234",
  grpc.credentials.createInsecure()
);

var starttimes = [];

for (var i = 1; i <= 5; i++) {
  starttimes.push(Date.now());
  let iter = i;
  console.log(`sending request ${iter}...`);
  client.test({ content: "test" }, function (err, response) {
    if (err) {
      console.log(err);
    } else {
      console.log(
        `end time of ${iter}: ${Date.now() - starttimes[iter - 1]} ms`
      );
    }
  });
}
```
rewriter.proto
```
syntax = "proto3";


package rewriter;

service Rewriter {
  rpc Test(TestRequest) returns (stream TestResponse) {}
}

message TestRequest {
  string content = 1;
}

message TestResponse {
  string content = 1;
}
```

server.js logs 
```
D 2023-03-07T18:09:44.293Z | server | (1) Server constructed
D 2023-03-07T18:09:44.294Z | dns_resolver | Resolver constructed for target dns:0.0.0.0:1234
D 2023-03-07T18:09:44.295Z | dns_resolver | Returning IP address for target dns:0.0.0.0:1234
D 2023-03-07T18:09:44.297Z | server | (1) Attempting to bind 0.0.0.0:1234
D 2023-03-07T18:09:44.299Z | server | (1) Successfully bound 0.0.0.0:1234
Listening on port 1234...

D 2023-03-07T18:09:46.042Z | server | (1) Received call to method /rewriter.Rewriter/Test at address null
D 2023-03-07T18:09:46.044Z | server_call | Request to /rewriter.Rewriter/Test received headers {"grpc-accept-encoding":["identity,deflate,gzip"],"accept-encoding":["identity"],"user-agent":["grpc-node-js/1.8.7"],"content-type":["application/grpc"],"te":["trailers"]}
D 2023-03-07T18:09:46.045Z | server | (1) Received call to method /rewriter.Rewriter/Test at address null
D 2023-03-07T18:09:46.045Z | server_call | Request to /rewriter.Rewriter/Test received headers {"grpc-accept-encoding":["identity,deflate,gzip"],"accept-encoding":["identity"],"user-agent":["grpc-node-js/1.8.7"],"content-type":["application/grpc"],"te":["trailers"]}
D 2023-03-07T18:09:46.046Z | server | (1) Received call to method /rewriter.Rewriter/Test at address null
D 2023-03-07T18:09:46.046Z | server_call | Request to /rewriter.Rewriter/Test received headers {"grpc-accept-encoding":["identity,deflate,gzip"],"accept-encoding":["identity"],"user-agent":["grpc-node-js/1.8.7"],"content-type":["application/grpc"],"te":["trailers"]}
D 2023-03-07T18:09:46.046Z | server | (1) Received call to method /rewriter.Rewriter/Test at address null
D 2023-03-07T18:09:46.047Z | server_call | Request to /rewriter.Rewriter/Test received headers {"grpc-accept-encoding":["identity,deflate,gzip"],"accept-encoding":["identity"],"user-agent":["grpc-node-js/1.8.7"],"content-type":["application/grpc"],"te":["trailers"]}
D 2023-03-07T18:09:46.047Z | server | (1) Received call to method /rewriter.Rewriter/Test at address null
D 2023-03-07T18:09:46.047Z | server_call | Request to /rewriter.Rewriter/Test received headers {"grpc-accept-encoding":["identity,deflate,gzip"],"accept-encoding":["identity"],"user-agent":["grpc-node-js/1.8.7"],"content-type":["application/grpc"],"te":["trailers"]}
received test
done
D 2023-03-07T18:09:46.688Z | server_call | Request to method /rewriter.Rewriter/Test ended with status code: OK details: OK
received test
done
D 2023-03-07T18:09:47.278Z | server_call | Request to method /rewriter.Rewriter/Test ended with status code: OK details: OK
received test
done
D 2023-03-07T18:09:47.614Z | server_call | Request to method /rewriter.Rewriter/Test ended with status code: OK details: OK
received test
done
D 2023-03-07T18:09:47.949Z | server_call | Request to method /rewriter.Rewriter/Test ended with status code: OK details: OK
received test
done
D 2023-03-07T18:09:48.284Z | server_call | Request to method /rewriter.Rewriter/Test ended with status code: OK details: OK
D 2023-03-07T18:09:48.287Z | server_call | Request to method /rewriter.Rewriter/Test stream closed with rstCode 0
D 2023-03-07T18:09:48.287Z | server_call | Request to method /rewriter.Rewriter/Test stream closed with rstCode 0
D 2023-03-07T18:09:48.287Z | server_call | Request to method /rewriter.Rewriter/Test stream closed with rstCode 0
D 2023-03-07T18:09:48.287Z | server_call | Request to method /rewriter.Rewriter/Test stream closed with rstCode 0
D 2023-03-07T18:09:48.287Z | server_call | Request to method /rewriter.Rewriter/Test stream closed with rstCode 0
```
Output logs from test-client.js
```
sending request 1...
sending request 2...
sending request 3...
sending request 4...
sending request 5...
end time of 1: 2308 ms
end time of 2: 2298 ms
end time of 3: 2299 ms
end time of 4: 2298 ms
end time of 5: 2299 ms
```
As you can see, each request is finishing around ~2s mark, i.e., all the callbacks are invoked only when the server is finished with ALL the requests.

**Comment by murgatroid99** [comment]
The part where your understanding is a little off is that handling a single request can involve multiple asynchronous operations in sequence. In particular, sending the status code happens asynchronously after sending the last message. Since your "expensive computation" is synchronous, it locks up the event loop, and I think that results in a sequence like this:

 - The client sends all 5 requests in quick succession.
 - The server queues events to handle each of the 5 requests.
 - 5 times, the server processes the first event on the queue, performing the expensive operation, sending the response message, and signaling that it is ready to send trailers.
 - Once the queue empties, Node processes network events, and queues 5 events for processing trailers.
 - As the server processes each of those events, it sends the trailers.

If you replaced your expensive computation with an asynchronous operation that took about a second, the client would get each result in its own time.

**Comment by goelayu** [comment]
Thanks for the clarification. 
So are you implying that if I were to move the expensive computation part in an async method, clients would get results on their own time? 
Rewriting the test method like this work didn't work
```
var test = function (call, callback) {
  setTimeout(() => {
    _test();
    callback(null, { content: "test" });
  }, 0);
};
```
What would be the best way to execute `test` such that each client request receives the response the moment the server has finished the corresponding processing? In other words, if each `test` RPC results in 500ms of synchronous computation, and the clients each 4 requests in parallel, it receives the responses at 500,1000,1500,2000ms respectively, instead of receiving all 4 at 2000ms.

**Comment by murgatroid99** [comment]
Your `_test` method is performing an inherently synchronous operation. Calling it "asynchronously" doesn't change that. Your rewritten `test` function doesn't change the visible outcome because the only change it makes to the event sequence I described is delaying the second bullet point by one event loop cycle. When I talked about "an asynchronous operation", I meant something genuinely asynchronous like a network request.

The root cause of what you are observing here is that you have one client sending all of the requests essentially together. This will almost always force the server to process all of them sequentially within a single event loop cycle.

Fundamentally, "responsive server" and "expensive synchronous computations" do not go well together in Node.

**Comment by goelayu** [comment]
Thanks again for clarification. I guess I'm still a little confused. As I mentioned in the above comment, assuming the "Test" RPC does some computation for 500ms, and the server receives 4 requests at the same time (either all from one client, or 1 each from 4 different client, tho I believe this shouldn't matter), the server should be able to respond back at roughly 500ms, 1000ms, 1500ms and 2000ms mark, respectively, correct?
How should the "Test" RPC above be implemented do achieve this, as currently, it only responds after 2000ms for all 4 requests.

**Comment by murgatroid99** [comment]
OK, to simplify a little, the event loop is essentially a queue of operations. When you make a request, the server enqueues an operation to handle the request. Once that operation executes, it sends the response message and also enqueues an operation to send trailers, which is what actually finishes the response. The issue you're seeing here is that if other operations are also on the queue at that time, such as the other requests, they will run before the one that sends trailers. You can't avoid this as long as your response handling code has a long synchronous operation.

**Comment by goelayu** [comment]
I see. I guess there is nothing that can be done about this, since there is only event loop, unless the trailers were sent right away once the request finishes, instead of pushing them to the event loop. 

> I expect that you will see this outcome whenever the time between incoming requests is significantly less than the time it takes to process one request.
I would be curious about what kind of workloads use grpc-node, as I would imagine the above property to be true for most workloads, i.e., per request processing latency >>> inter-request delay. 

Anyway, thanks for clarifying. I will close this issue now.

**Comment by murgatroid99** [comment]
To clarify the statement you quoted, this is all in the context of your server application code that processes requests with a block of synchronous code, so when I said "the time it takes to process one request", I was referring to the time the server spends processing the request in a single block of synchronous code. Most server application workloads will not have this problem because they do asynchronous operations such as

 1. Making gRPC requests to other servers
 2. Making REST requests
 3. Querying a database
 4. Loading a file
 5. Waiting for events from other clients
