### ISSUE TITLE
Grpc error handling fails when receiving a non-grpc error with a code property (like assert's AssertionError)

### ISSUE THREAD

**Issue by adematte** [grpc/grpc-node#239]
Just stumbled on a weird issue when using asserts with grpc services.
Assert statements throw errors of type AssertionError when an assertion fails, the AssertionError objects contain a **code** property which grpc unfortunately uses internally for its error handling mechanism in **handleError**. Grpc then tries to wrap the error for internal use and fails.

We pinpointed the issue to being here: https://github.com/grpc/grpc-node/blob/896f07cc086d25d8014eb373f6b68422d31f1540/packages/grpc-native-core/src/server.js#L55-L60

error.code at this point contains ('ASSERTION_ERROR') and not an integer as expected by grpc status code.
It ends up calling startBatch with a wrong status code at https://github.com/grpc/grpc-node/blob/896f07cc086d25d8014eb373f6b68422d31f1540/packages/grpc-native-core/src/server.js#L71 which fails with error: **TypeError: Incorrectly typed arguments to startBatch**. 

What are your thoughts on this issue? One fix could be to change the check and ensure the value passed is indeed an integer within grpc error code status ranges but I am not sure it's the most viable approach.

Steps to reproduce: create a grpc server and use ```assert(false)``` before returning any value on a unary call. This occurs with GRPC NPM package version 1.10.0 (didn't test other versions).

**Comment by ksmithut** [comment]
Just to add to this, in Node 10, all builtin errors have a `.code` property that will be a string for most, if not all built in errors.

**Comment by nicolasnoble** [comment]
Very likely similar, if not the same, as #369.

**Comment by ksmithut** [comment]
That's the exact error that I get

**Comment by hugohernani** [comment]
I am also getting this issue. I am using nestjs framework and wrapping the error into **RpcException** instance.

```
if(exception.message.error == 'Bad Request'){
  rpcException = new RpcException({
    code: GrpcStatus.INVALID_ARGUMENT,
    message: exception.message.error
  })
}
```

**Comment by guyisra** [comment]
any updates on this issue?
