### ISSUE TITLE
InternalChannel is being recreated over time - possible memory leak

### ISSUE THREAD

**Issue by voslartomas** [grpc/grpc-node#2402]
### Problem description

We are seeing increasing memory in our application which is using grpc-node. The thing is that we are creating new client for each request (not sure if this can be a problem?) and trying to close all the created clients (we have tens of different grpc clients per request - micro services) with `client.close()`, but even though we close client we can see multiple objects retained in memory as shown on screenshot (showing just InternalChannel, but there are more if needed).

### Environment
 - Linux Ubuntu 18.04, amd64 (can reproduce even on arm64, macos)
 - Tested on multiple versions from 14 to 18
 - System
 - Tested multiple versions - now on 1.8.13

### Additional context

<img width="741" alt="Screenshot 2023-03-29 at 11 04 52" src="https://user-images.githubusercontent.com/1945040/228485426-972ec1de-bf95-4dfc-ba7f-98abad8d541e.png">

**Comment by murgatroid99** [comment]
I will try to fix this, but please note that this is the opposite of how we recommend using the API. You should create one client per service and then use that client for every request to that service.

**Comment by voslartomas** [comment]
Noted, it might be little bit difficult for us to switch easily to one client per service as it is quite big service with lot of different clients, but I will try to push it this way.

It would be great if you will be able to fix it though, thank you very much. Let me know if you need more details.

**Comment by murgatroid99** [comment]
I'm not sure if I was clear. It's hard to be precise without knowing your setup, but in short, if you are creating and closing identical client objects with the same options, you should instead reuse the same client object.

**Comment by murgatroid99** [comment]
Also, can you expand one of the `InternalChannel` entries from the earlier screenshot and share a screenshot of that?

**Comment by voslartomas** [comment]
Sure here it is
<img width="1167" alt="Screenshot 2023-03-29 at 21 15 06" src="https://user-images.githubusercontent.com/1945040/228644206-8aad43c7-f38b-4ca1-9db2-06e88a13cbb7.png">

Also I've just tried to do quick fix to have single client per app and it seems that it is still creating internalChannel for some reason, I mean lot of them

**Comment by voslartomas** [comment]
I can also upload somewhere whole memory dump if it will be helpful

**Comment by murgatroid99** [comment]
> Also I've just tried to do quick fix to have single client per app and it seems that it is still creating internalChannel for some reason, I mean lot of them

I think your code may be creating grpc-js client or channel objects somewhere that you didn't change, and those aren't getting closed. That is my best explanation for what you're seeing.

> I can also upload somewhere whole memory dump if it will be helpful

I think that would help get an idea of what's going on.

**Comment by murgatroid99** [comment]
I checked several of the `InternalChannel` objects in that heap dump. In every case, the information was consistent with a channel/client being discarded without calling the `close` method.

It might help you to run your code with the environment variables `GRPC_TRACE=channel_stacktrace` and `GRPC_VERBOSITY=DEBUG`. That will log a stacktrace every time a channel is constructed.

**Comment by voslartomas** [comment]
All right, probably it was just that some of the clients were not properly closed, I will try to investigate this situation, thank you.

**Comment by voslartomas** [comment]
It's really strange, but I am pretty sure that I am closing everything now and I can still see leaks of `InternalChannel` and other objects from grpc. But when I tried to do simple hack to create just single client per app it was fine, so I guess we should anyway go this way and fix it properly.

**Comment by voslartomas** [comment]
Just FYI, after all we refactored our app so it creates just one instance per application and memory leak is gone.
