### ISSUE TITLE
[Question] How to configure channel options for grpc server ?

### ISSUE THREAD

**Issue by tirth0** [grpc/grpc-node#2430]
### Background
We have been intermittently encountering `1 CANCELLED: CALL Cancelled` from our grpc clients.
We have configured channel options for our clients after following these threads:

1. https://github.com/grpc/grpc-node/issues/2340
2. https://github.com/grpc/grpc-node/issues/154#issuecomment-357358178
3. https://github.com/grpc/grpc/blob/2d4f3c56001cd1e1f85734b2f7c5ce5f2797c38a/doc/keepalive.md

However we are unable to understand how to do the same for our servers. We are looking for some documentation regarding the same. Any help would be appreciated.

### Environment
 - OS name, version and architecture: [e.g. Linux Debian 10 buster]
 - Node version [e.g. LTS 19.9.0 (alpine image)]
 - Container Orchestrator: Docker Swarm

### Additional context
Currently we are testing with insecureConnections:

Server Setup: 

### Proto Loader file Snippet
```javascript
const grpc = require("@grpc/grpc-js");
const protoLoader = require("@grpc/proto-loader");
const options = require("../utils/protoOptions");

const services = require("../services/hubspot");

const PROTO_FILE = "proto-name.proto";

const pkgDef = protoLoader.loadSync(PROTO_FILE, options);
const proto = grpc.loadPackageDefinition(pkgDef);

global.grpcServer.addService(proto.Service.service, services);

```

### Server File Snippet
```javascript
const grpc = require("@grpc/grpc-js");

global.grpcServer = new grpc.Server();

grpcServer.bindAsync(
  `${process.env.GRPC_ADDRESS}:${GRPC_PORT}`,
  grpc.ServerCredentials.createInsecure(),
  (error, port) => {
    if (error) logger.error(`Error for grpc:${error}`);
    else logger.info(`GRPC listening on port ${GRPC_PORT}`);
    grpcServer.start();
  }
);
```

**Comment by murgatroid99** [comment]
Since `@grpc/grpc-js` 1.8.0, keepalive pings are implemented on the server, and they can be configured with the channel arguments `grpc.keepalive_time_ms` and `grpc.keepalive_timeout_ms`.
