### ISSUE TITLE
gRPC module throwing error with Electron.js

### ISSUE THREAD

**Issue by vamsideepak** [grpc/grpc-node#2443]
I am trying to work with gRPC in my electron application but grpc module is not working after building the electron application. Initially I tried with grpc node module but it is deprecated recently. So I tried with @grpc/grpc.js module and it is not working as expected. Below are the steps what I have done so far

npm install @grpc/grpc.js @grpc/grpc-protoloader.
imported both grpc modules
added grpc related code in my electron app.
added .proto file
after all the setup I tried to launch my electron application and getting the below error.
**ERROR Error: Uncaught (in promise): Error: Invalid package C:\Users\some-user\Desktop\MockServer\Trilogy_Client_Installer\node_modules\electron\dist\resources\electron.asar**

### Environment
 - windows 11
 - Node version 16.14.2
 - Electron version 20.1.3
 - gRPC version 1.8.14

**Comment by murgatroid99** [comment]
That invalid package error doesn't say anything about gRPC. I don't think it's related.

**Comment by vamsideepak** [comment]
> That invalid package error doesn't say anything about gRPC. I don't think it's related.
After removing thr grpc my electron application working as usual. The problem is with grpc module after building the application

**Comment by vamsideepak** [comment]
@murgatroid99  When I import in the main process it is working but I want to use it in the renderer process too.

**Comment by murgatroid99** [comment]
The error is about a file in the `electron` package. I think this is more likely to be an electron bug than a gRPC bug. I suggest filing an issue in the Electron repository.

**Comment by vamsideepak** [comment]
@murgatroid99  thanks for the info . It was a problem with nodejs __dirname that i have used to get path . Issue has been resolved.
