### ISSUE TITLE
[Question] How to make the grpc client to get the new backend service pods when k8s cluster scaling up?

### ISSUE THREAD

**Issue by icewindq** [grpc/grpc-node#2455]
We use round_robin load balancing on GRPC client to call some backend pods on a k8s cluster with autoscaling rules. The k8s will some new backend service pods if the traffic load is increasing. 

**How to make the grpc client to get the new backend service pods when k8s cluster scaling up?**
**Is there any way to refresh DNS every X seconds in GRPC client?** Now it will refresh DNS when the connection was idle. it's about 2 minutes sometime. 

What's the best practice when using load balancing for GRPC client on k8s?

**Comment by emilsivervik** [comment]
This might be what you're looking for @icewindq: https://github.com/grpc/grpc-node/issues/2023#issuecomment-1086214633

**Comment by icewindq** [comment]
@emilsivervik  thanks for your help. 
but the option `grpc.dns_min_time_between_resolutions_ms` means the minimum time between two DNS resolutions. normally it's bigger than this option (default: 30 seconds). it seems the DNS resolution is triggered only when the connection is idle.

**Comment by icewindq** [comment]
find a solution: watch the pods change and get pods address via k8s client api.  
https://github.com/zcong1993/grpc-resolver-k8s.

Not sure it's the best practice for using load balancing for GRPC client on k8s. But it works.

**Comment by wang-xiaowu** [comment]
> find a solution: implement a custom resolver, watch the pods change and get pods address via k8s client api. https://github.com/zcong1993/grpc-resolver-k8s.
> 
> Not sure it's the best practice for using load balancing for GRPC client on k8s. But it works.

actually this repository has not updated since 3years ago, i think we need this issue reopen and take a solution to handle this problem in k8s, like [kuberesolver](https://github.com/sercand/kuberesolver) in golang

**Comment by wang-xiaowu** [comment]
and as a supplement for the anwer, i think you can reduce `max_connect_age` to ease this situation, like
```js
const server = new grpc.Server(
  {
    'grpc.max_connection_age_ms': 1000 * 60, // 1 minute
    interceptors: [logger_interceptor],
  }
);
```
