### ISSUE TITLE
grpc-js is incredibly difficult to lint/prettify/fix

### ISSUE THREAD

**Issue by dancrumb** [grpc/grpc-node#2464]
### Problem description
As a would-be contributor, I'd like to comply with the lining and formatting rules, but it's incredibly difficult to do so.

The current `master` HEAD does not currently pass the `lint` script and the `fix` script fails.

It's also worth noting that this project uses `tslint` which has been deprecated for over 4 years.

In short, it's hard to know where to start with the lining and formatting rules since the repo doesn't appear to be in compliance with its own rules.

### Reproduction steps

1. Clone repo
2. Run `npm install` from the repo root
3. `cd packages/grpc-js/`
4. `npm install`
5. `npm run lint`
     First, you get this warning:
```
version: 18
=============

WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <4.5.0

YOUR TYPESCRIPT VERSION: 4.9.5

Please only submit bug reports when using the officially supported version.

============= 
```
    then you get this result:
```
✖ 58 problems (56 errors, 2 warnings)
  56 errors and 0 warnings potentially fixable with the `--fix` option.
```
 6. So, run `npm run fix`
 Same warning
 The command fails with `✖ 15 problems (5 errors, 10 warnings)`

### Environment
 - Darwin danpersallaptop.lan 21.6.0 Darwin Kernel Version 21.6.0: Mon Apr 24 21:10:53 PDT 2023; root:xnu-8020.240.18.701.5~1/RELEASE_X86_64 x86_64
 - v18.15.0
 - nvm
 - n/a
 - @grpc/grpc-js@1.8.14

### Additional context

This isn't just a nitpick. I'd like to assist with making this package Deno-ready and part of this would include adding lint rules to prevent the direct use of Timer functions so that they can be properly shimmed to support Node and Deno environments.

I'd be happy to put in the work to migrate this repo from `gts` and `tslint` to `eslint/prettier`.
This would make life a lot easier for VSCode users, as well as bring the repo up to date with industry norms (see https://npmtrends.com/eslint-vs-gts-vs-prettier-vs-tslint).

To be clear: I'm not trying to impugn your choice with GTS... it shows/showed a lot of promise, but it seems to have stagnated or, at least, isn't a priority. They created a `4.0.1` version in January, but didn't actually publish it until March and it's still tagged as `next` rather than `latest` tag.

**Comment by dancrumb** [comment]
FWIW - I tried updating GTS to version 4, but the same problems persist

**Comment by murgatroid99** [comment]
I would support updating or switching the linter. It looks like some actual code changes will also be needed to fix some lint errors.
