### ISSUE TITLE
Update protobufjs in proto-loader to fix  vulverability

### ISSUE THREAD

**Issue by getellez** [grpc/grpc-node#2497]
![image](https://github.com/grpc/grpc-node/assets/85968117/2fd0f01f-9b74-408c-b179-68a4a481fa6a)

Hey guys there is a vulnerability with `protobufjs`. So, could you please update the `protobufjs` version to the >=7.2.4 version used in `@grcp/proto-loader?`

**Comment by murgatroid99** [comment]
Duplicate of #2495.
