### ISSUE TITLE
grcpjs - Update to latest proto-loader version to fix vulnerability

### ISSUE THREAD

**Issue by getellez** [grpc/grpc-node#2499]
![image](https://github.com/grpc/grpc-node/assets/85968117/73e1e45f-2518-49ab-ac9f-748600fe7ab0)

Hey guys! Could you please update `@grpc/grpc-js` to use the latest version of `@grpc/proto-loader`? so that a proto-loader vulnerability is fixed

**Comment by murgatroid99** [comment]
Please do not create duplicate issues. This is the same as issue #2497, which you created earlier today.
