### ISSUE TITLE
proto-loader-gen-types throwing warnings that file not found in the include path

### ISSUE THREAD

**Issue by anthony-dandrea** [grpc/grpc-node#2510]
### Problem description

I am attempting to generated typescript types from proto files using `proto-loader-gen-types`. It seems to succeed and gives me a `✨  Done` at the end. But before it does that, I receive many warnings that I'm not sure how to resolve or silence.

The command I am running (I've tried quite a few variations of this as well):
```
proto-loader-gen-types --longs=String --enums=String --grpcLib=@grpc/grpc-js --includeDirs=./protos --outDir=protosTypes/types/ protos/**/*.proto
```

The warnings that it throws:
```
(node:61840) Warning: protos/test/messages.proto not found in any of the include paths protos
```

My directory structure:
```
protos
├── test
│   ├── message.proto
protosTypes
└── types
    ├── test
    │   ├── Test.ts
```
Note: there are many different directories and proto files in that protos directory. The tree above is just a simplified example.

The `protos/test/messages.proto` is nested inside of the `protos/` directory. And the generated typed files seem to work. So it's unclear to me what exactly is the warning for. 

### Environment
 - OS name, version and architecture: macOS 13.4.1
 - Node version: v16.20.1
 - Node installation method: nvm 0.39.3
 - If applicable, compiler version: Not sure
 - Package name and version: @grpc/grpc-js 1.8.18, @grpc/proto-loader 0.5.6

**Comment by murgatroid99** [comment]
The file paths you provide should be relative to the include directories. In your example, the only include directory is `./protos` and the only file path is `protos/test/message.proto`. This means that it will look for `./protos/protos/test/message.proto`, which does not exist. You should either use an include directory of `./` or a file path of `test/message.proto`.

**Comment by anthony-dandrea** [comment]
Adding `./` worked like a charm, thank you 🙏 Final command I ended up with for reference:
```
proto-loader-gen-types --keepCase --longs=String --enums=String --defaults --oneofs --grpcLib=@grpc/grpc-js --includeDirs=./protos ./ --outDir=protosTypes/types/ protos/**/*.proto
```
