### ISSUE TITLE
How to use .pfx certificate in grpc-js client 

### ISSUE THREAD

**Issue by vamsideepak** [grpc/grpc-node#2529]
As per documents i did not see how to use the .pfx certificates in grpc-js client  . Is there any example of it or grpc will not be support pfx ?

**Comment by murgatroid99** [comment]
You can create a Node secure context using .pfx certificates with [`tls.createSecureContext`](https://nodejs.org/api/tls.html#tlscreatesecurecontextoptions), and then pass the result to `grpc.credentials.createFromSecureContext`.

**Comment by vamsideepak** [comment]
@murgatroid99  I have ran my .exe successfully and as you mentioned I have implemented the below code. The path is correct and exe is running and on https I am able to run listen the streaming events (localhost:5003) but unfortunatly on https(tried https://localhost:5003,grpc:localhost:5003, https://0.0.0.0:5003, https://127.0.0.1:5003) it is failing and saying that 

`Error: 14 UNAVAILABLE: Name resolution failed for target dns:https://localhost:5003 at callErrorFromStatus (C:\Users\xxx\Desktop\MockServer\Trilogy_Client_Installer\node_modules\@grpc\grpc-js\build\src\call.js:31:19) at Object.onReceiveStatus (C:\Users\xxx\Desktop\MockServer\Trilogy_Client_Installer\node_modules\@grpc\grpc-js\build\src\client.js:351:73) at Object.onReceiveStatus (C:\Users\xxx\Desktop\MockServer\Trilogy_Client_Installer\node_modules\@grpc\grpc-js\build\src\client-interceptors.js:323:181) at C:\Users\xxx\Desktop\MockServer\Trilogy_Client_Installer\node_modules\@grpc\grpc-js\build\src\resolving-call.js:94:78 at process.processTicksAndRejections (node:internal/process/task_queues:77:11) for call at at ServiceClientImpl.makeServerStreamRequest (C:\Users\xxx\Desktop\MockServer\Trilogy_Client_Installer\node_modules\@grpc\grpc-js\build\src\client.js:334:34) at ServiceClientImpl.<anonymous> (C:\Users\xxx\Desktop\MockServer\Trilogy_Client_Installer\node_modules\@grpc\grpc-js\build\src\make-client.js:105:19) at t.clientGrpcPmTrans (http://localhost:4200/main.js:1:418211) at http://localhost:4200/main.js:1:415464 at Generator.next (<anonymous>) at vI (http://localhost:4200/main.js:1:330898) at c (http://localhost:4200/main.js:1:331101) at B.invoke (http://localhost:4200/polyfills.js:1:7225) at T.run (http://localhost:4200/polyfills.js:1:2577) at http://localhost:4200/polyfills.js:1:17585 at B.invokeTask (http://localhost:4200/polyfills.js:1:7845) at T.runTask (http://localhost:4200/polyfills.js:1:3210) at G (http://localhost:4200/polyfills.js:1:9893) at invokeTask (http://localhost:4200/polyfills.js:1:8929) at invoke (http://localhost:4200/polyfills.js:1:8800) at U.z.args.<computed> (http://localhost:4200/polyfills.js:1:29047)`


 

`const tls = require('tls');
const pfxFilePath = process.resourcesPath +  '/kiosk-screens/peripheralManager/Certificates/wildcard_everikiosk_app.pfx';
const pfxPassphrase = 'Everi@123'; // If the .pfx file is password-protected
console.log('pfxFilePath', pfxFilePath);
const pfxData = this.electronService.fs.readFileSync(pfxFilePath);
const formSecureSSL = tls.createSecureContext({
  pfx: pfxData,
  passphrase: pfxPassphrase,
}).context;
const sslCreds = this.electronService.grpc.credentials.createFromSecureContext(formSecureSSL);`

My exe is running by using nodejs child-process and it is running in my task manager.

**Comment by murgatroid99** [comment]
The address you are using is not valid for gRPC. You should just use `localhost:5003`.

The `http` vs `https` distinction communicates whether the communication should be plaintext or encrypted. In gRPC that is communicated using the credentials object instead of the URL scheme.

**Comment by vamsideepak** [comment]
@murgatroid99  Tried by removing https but still facing same issue. Actually I am using streaming where it is always failing and throwing error but the same code is working when I make insecure calls. my grpc-js version is 1.8.14 
are there any changes in the latest versions for streaming with certification related things ?

**Comment by murgatroid99** [comment]
Please post the full text of the error that you get after changing the address string.

**Comment by murgatroid99** [comment]
That is a different error. It says "No connection established" while the first one said "Name resolution failed for target dns:https://localhost:5003".

If you run the process with the environment variables `GRPC_TRACE=all` and `GRPC_VERBOSITY=DEBUG`, you will get more information about what is happening. However, the most likely issue here comes from the fact that most TLS certificates do not have a target name of "localhost". As a result, those certificates will be rejected by default when connecting to `localhost`. You can get the client to accept the server certificate by setting the channel arguments `grpc.ssl_target_name_override` and `grpc.default_authority` both to the value of the server's certificate's target name. In addition to that, you are using a certificate in the client credentials, which is used to authenticate the client with the server. There is currently no support for similar override options on the server, so you cannot do the same for that part. And the server also does not have an equivalent of `createFromSecureContext`, so you cannot currently use .pfx certificates on the server.

**Comment by vamsideepak** [comment]
@murgatroid99  If that is the case how server will know that client is making secure connection calls or how client know that it is connected to secure server ? is there any other option to make it success ? is it possible if I use .pem ? 

and after removing client reading .pfx code and made calls to secure server, getting the below error . Server cancelling the streaming and throwing below error. I don't set timeouts for streaming.

`Error: 1 CANCELLED: Call cancelled at callErrorFromStatus (C:\Users\xxxx\Desktop\MockServer\Trilogy_Client_Installer\node_modules\@grpc\grpc-js\build\src\call.js:31:19) at Object.onReceiveStatus (C:\Users\xxxx\Desktop\MockServer\Trilogy_Client_Installer\node_modules\@grpc\grpc-js\build\src\client.js:357:73) at Object.onReceiveStatus (C:\Users\xxxx\Desktop\MockServer\Trilogy_Client_Installer\node_modules\@grpc\grpc-js\build\src\client-interceptors.js:323:181) at C:\Users\xxxx\Desktop\MockServer\Trilogy_Client_Installer\node_modules\@grpc\grpc-js\build\src\resolving-call.js:94:78 at process.processTicksAndRejections (node:internal/process/task_queues:77:11) for call at at ServiceClientImpl.makeServerStreamRequest (C:\Users\xxxx\Desktop\MockServer\Trilogy_Client_Installer\node_modules\@grpc\grpc-js\build\src\client.js:340:32) at ServiceClientImpl.<anonymous> (C:\Users\xxxx\Desktop\MockServer\Trilogy_Client_Installer\node_modules\@grpc\grpc-js\build\src\make-client.js:105:19) at t.clientGrpcPmTrans (http://localhost:4200/main.js:1:417965) at http://localhost:4200/main.js:1:415189 at Generator.next (<anonymous>) at vI (http://localhost:4200/main.js:1:330898) at c (http://localhost:4200/main.js:1:331101) at B.invoke (http://localhost:4200/polyfills.js:1:7225) at T.run (http://localhost:4200/polyfills.js:1:2577) at http://localhost:4200/polyfills.js:1:17585 at B.invokeTask (http://localhost:4200/polyfills.js:1:7845) at T.runTask (http://localhost:4200/polyfills.js:1:3210) at G (http://localhost:4200/polyfills.js:1:9893) at invokeTask (http://localhost:4200/polyfills.js:1:8929) at invoke (http://localhost:4200/polyfills.js:1:8800) at U.z.args.<computed> (http://localhost:4200/polyfills.js:1:29047)
`

**Comment by vamsideepak** [comment]
@murgatroid99  Now I am trying with pem files and getting below error 

`in.js:1 ERROR Error: Uncaught (in promise): Error: Private key must be given with accompanying certificate chain
Error: Private key must be given with accompanying certificate chain
    at Object.createSsl (C:`
    
 Grpc code is below 
 
 `   const certPath = process.resourcesPath + '/kiosk-screens/peripheralManager/Certificates/certificate.pem';
    const privateKeyPath = process.resourcesPath + '/kiosk-screens/peripheralManager/Certificates/privatekey.key';
    const caCert = process.resourcesPath + '/kiosk-screens/peripheralManager/Certificates/ca.pem';
    const sslCreds = this.electronService.grpc.credentials.createSsl(
      this.electronService.fs.readFileSync(certPath),
      this.electronService.fs.readFileSync(privateKeyPath),

    );`

**Comment by murgatroid99** [comment]
> If that is the case how server will know that client is making secure connection calls or how client know that it is connected to secure server ?

If you create a credentials object using `credentials.createInsecure`, it will make plaintext connections. Otherwise, it will make TLS connections as specified in the credentials.

If your certificate has a password, you can only provide it by using `credentials.createFromSecureContext`. I will note that you can omit the private key and cert chain arguments in `credentials.createSsl` if you don't need the server to authenticate the client over TLS. You can even omit the certificate authority list if you want to use the default certificate authorities.

**Comment by vamsideepak** [comment]
@murgatroid99  as you said I have used **createFromSecureContext** Still facing the below issue. I could not find exactly what happening . server exe is running and createFromSecureContext is proper still not able to connect to the server. Anything wrong in my code.? or is it problem with certificate ? but from postman with same certs we are able to connect to the server. The below error , I am getting in the stream listeners.  do I have to run client server as well ??? 
`    ```
const defaultAuthority = 'localhost';
const clientOptions = {
  'grpc.ssl_target_name_override': 'localhost',
  'grpc.default_authority': defaultAuthority,
};
    const tls = require('tls');
    const certPath = process.resourcesPath + '/kiosk-screens/peripheralManager/Certificates/certificate.pem';
    const privateKeyPath = process.resourcesPath + '/kiosk-screens/peripheralManager/Certificates/privatekey.pem';
    const caCertPath = process.resourcesPath + '/kiosk-screens/peripheralManager/Certificates/certificate.pem';

    const certificate = this.electronService.fs.readFileSync(certPath);
    const privateKey = this.electronService.fs.readFileSync(privateKeyPath);
    const caCert = this.electronService.fs.readFileSync(caCertPath);
    console.log('cert details', certificate, 'private', privateKey, 'cacert', caCert)
    const secureContext = tls.createSecureContext({
      cert: certificate,
      key: privateKey,
      passphrase: 'test@123',
    });

    const certChain = Buffer.concat([certificate, caCert]);
    try {
      var sslCreds = this.electronService.grpc.credentials.createFromSecureContext(
        secureContext);
    } catch (error) {
      console.log('sslcred error', error);
    }
this.cardPrinterClient = new this.cardPrinterPackage.GrpcPmCardPrinterService(localhost:5003, sslCreds,clientOptions);

````

```
Error: 14 UNAVAILABLE: No connection established at callErrorFromStatus (C:\Users\some.user\Desktop\MockServer\Trilogy_Client_Installer\node_modules\@grpc\grpc-js\build\src\call.js:31:19) at Object.onReceiveStatus (C:\Users\some.user\Desktop\MockServer\Trilogy_Client_Installer\node_modules\@grpc\grpc-js\build\src\client.js:357:73) at Object.onReceiveStatus (C:\Users\some.user\Desktop\MockServer\Trilogy_Client_Installer\node_modules\@grpc\grpc-js\build\src\client-interceptors.js:323:181) at C:\Users\some.user\Desktop\MockServer\Trilogy_Client_Installer\node_modules\@grpc\grpc-js\build\src\resolving-call.js:94:78 at process.processTicksAndRejections (node:internal/process/task_queues:77:11) for call at at ServiceClientImpl.makeServerStreamRequest (C:\Users\some.user\Desktop\MockServer\Trilogy_Client_Installer\node_modules\@grpc\grpc-js\build\src\client.js:340:32) at ServiceClientImpl.<anonymous> (C:\Users\some.user\Desktop\MockServer\Trilogy_Client_Installer\node_modules\@grpc\grpc-js\build\src\make-client.js:105:19) at t.clientGrpcPmTrans (http://localhost:4200/main.js:1:418316) at http://localhost:4200/main.js:1:415534 at ge.<computed> (http://localhost:4200/polyfills.js:1:29345) at B.invokeTask (http://localhost:4200/polyfills.js:1:7845) at T.runTask (http://localhost:4200/polyfills.js:1:3210) at invokeTask (http://localhost:4200/polyfills.js:1:8899) at invoke (http://localhost:4200/polyfills.js:1:8800) at U.z.args.<computed> (http://localhost:4200/polyfills.js:1:29047)
```

**Comment by vamsideepak** [comment]
@murgatroid99  First of all thank you for instant response. As I am using self signed certificate unable to CA cert. I have extracted the private key and certicate from .pfx file and using them **createFromSecureContext**. That is the reason I have pointed to certificate.pem as cacert. I am new to Grpc and certification handling. I've modified code like below
May I know what are the exact thing I am missings to accomplish this.?
openssl commands to extract the .pfx

```openssl pkcs12 -in yourfile.pfx -clcerts -nokeys -out certificate.pem 
openssl pkcs12 -in yourfile.pfx -nocerts -out privatekey.pem            
openssl pkcs12 -in your-file.pfx -cacerts -nokeys -out ca.crt
```   
but for ca.crt I am getting empty data in file

Trail 1:
```    const certPath = process.resourcesPath + '/kiosk-screens/peripheralManager/Certificates/certificate.pem';
    const privateKeyPath = process.resourcesPath + '/kiosk-screens/peripheralManager/Certificates/privatekey.pem';
    const caCertPath = process.resourcesPath + '/kiosk-screens/peripheralManager/Certificates/certificate.pem';

    const certificate = this.electronService.fs.readFileSync(certPath);
    const privateKey = this.electronService.fs.readFileSync(privateKeyPath);
    const caCert = this.electronService.fs.readFileSync(caCertPath);
    console.log('cert details', certificate, 'private', privateKey, 'cacert', caCert)
    const secureContext = tls.createSecureContext({
      ca : [caCert],
      cert: certificate,
      key: privateKey,
      passphrase: 'test@123',
    });
    try {
      var sslCreds = this.electronService.grpc.credentials.createFromSecureContext(
        secureContext);
    } catch (error) {
      console.log('sslcred error', error);
    }
    this.cardPrinterClient = new this.cardPrinterPackage.GrpcPmCardPrinterService(localhost:5003, sslCreds);

    ```
   
 Trail 2:
    
    ```const tls = require('tls');
    const pfxFilePath = process.resourcesPath + '/kiosk-screens/peripheralManager/Certificates/wildcard_everikiosk_app.pfx';
    const pfxPassphrase = "test@123"; // If the .pfx file is password-protected
    console.log('pfxFilePath', pfxFilePath);
    const pfxData = this.electronService.fs.readFileSync(pfxFilePath);
    console.log('pfxData', pfxData)
    const formSecureSSL = tls.createSecureContext({
      pfx: pfxData,
      passphrase: pfxPassphrase,
    }).context;
    console.log('formSecureSSL', formSecureSSL);
     const sslCreds = this.electronService.grpc.credentials.createFromSecureContext(formSecureSSL);
     ```
But still the error is persist:

```Error: 14 UNAVAILABLE: No connection established
    at callErrorFromStatus (C:\Users\deepak\Desktop\MockServer\Trilogy_Client_Installer\node_modules\@grpc\grpc-js\build\src\call.js:31:19)
    at Object.onReceiveStatus (C:\Users\deepak\Desktop\MockServer\Trilogy_Client_Installer\node_modules\@grpc\grpc-js\build\src\client.js:351:73)
    at Object.onReceiveStatus (C:\Users\deepak\Desktop\MockServer\Trilogy_Client_Installer\node_modules\@grpc\grpc-js\build\src\client-interceptors.js:323:181)
    at C:\Users\deepak\Desktop\MockServer\Trilogy_Client_Installer\node_modules\@grpc\grpc-js\build\src\resolving-call.js:94:78
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
for call at
    at ServiceClientImpl.makeServerStreamRequest (C:\Users\vamsi.deepak\Desktop\MockServer\Trilogy_Client_Installer\node_modules\@grpc\grpc-js\build\src\client.js:334:34)
    at ServiceClientImpl.<anonymous> 
    ```

**Comment by murgatroid99** [comment]
If you are using a self-signed certificate on the server, you **need** to provide the CA certs file on the client. I don't know enough about the `openssl` CLI tool to help you with creating that file, so you will need to look for help with that elsewhere. In your "Trail 1", you are providing a CA certs file, but you stopped providing options to the client. You still need to provide the options I specified. In your "Trail 2", you are not providing the CA certs file, which is why it is not working.

**Comment by murgatroid99** [comment]
I also want to note: the purpose of providing a key/cert pair (including in PFX format) is for TLS mutual authentication, where the client sends the certificate to the server and the server authenticates it. If that is not what you are trying to do, then you should not be providing those at all when constructing the credentials object.

**Comment by vamsideepak** [comment]
@murgatroid99  Yes server is also using same .pfx certificate and we are reading and sending these certificates to authenticate and checking the secure connections . I will try more. I am suspecting my certificate only because it is not providing the ca.pem file . Thanks a lot for your help and guidance . Must appreciate it 😊.
