### ISSUE TITLE
Repeated Option Names with Array syntax not permitted

### ISSUE THREAD

**Issue by marsh73** [grpc/grpc-node#2532]
### Problem description
According to the protobuf spec the array structure is acceptable for multiple option names. 

https://protobuf.com/docs/language-spec#resolving-option-names

<img width="932" alt="Screenshot 2023-08-01 at 3 56 54 PM" src="https://github.com/grpc/grpc-node/assets/645730/357ba9db-c786-467b-8714-9e783ac0fada">

But the second example breaks giving me the error `Error loading proto file: Error: illegal value '['`. 

### Reproduction steps
Following the example above change one of the option properties to be an array.

### Environment
 - OS name, version and architecture: [e.g. Linux Ubuntu 18.04 amd64] Mac
 - Node version [e.g. 8.10.0] Node version 16.13
 - Node installation method [e.g. nvm] nvm
 - If applicable, compiler version [e.g. clang 3.8.0-2ubuntu4]
 - Package name and version [e.g. gRPC@1.12.0]
     "@grpc/grpc-js": "^1.8.17",
    "@grpc/proto-loader": "0.6.4",

**Comment by murgatroid99** [comment]
`@grpc/proto-loader` just delegates to `protobufjs` to parse `.proto` files, so any parsing problem would need to be corrected there. I think this is the existing issue protobufjs/protobuf.js#1369.
