### ISSUE TITLE
Questions about DNS Lookup Caching and TLS Handshake

### ISSUE THREAD

**Issue by pratik151192** [grpc/grpc-node#2548]
Hello team!

I'm reaching out with a few questions regarding DNS lookups and its caching behavior in the gRPC Node.js runtime. Here's a bit of context:

**Background**: We have a gRPC-backed service, with SDKs in multiple languages to support our customers.

**Environment**: We're observing varied DNS lookup times ranging from 20ms-80ms in an AWS Lambda environment when using our Node.js SDK. This is especially pronounced during the initial requests (expectedly).

**Traces**: We've been relying on the `dns_resolver` and `resolving_load_balancer` gRPC traces for these observations. However, we couldn't pinpoint a specific trace for the TLS handshake time in Node.js. Also, it wasn't clear from the trace itself as to how much time was spent in the DNS resolution itself vs connecting to the server (IDLE -> READY) that might involve multiple components. Our external measurements showed that the handshake time is around 8-15ms, leading us to believe the delta might be from DNS resolutions.

Given this context, we had the following questions:

- Are DNS lookups cached within grpc-js? If they are, could you explain the caching behavior in a bit more detail?

- In a use case where we expect users to exceed the max concurrent streams for a connection, and we therefore proactively create multiple connections, is there a way we can avoid the cost of the DNS lookup being incurred on every connection?

- Are there other trace flags or environment variables, perhaps not mentioned in the [documentation](https://github.com/grpc/grpc-node/blob/master/doc/environment_variables.md), which might help us distinguish the time spent on DNS resolutions versus the TLS handshake?

- Does the trace ```resolving_load_balancer``` include the TLS handshake since it shows the transition steps from ```IDLE``` TO ```READY```?

Thanks in advance for your time and assistance!

**Comment by pratik151192** [comment]
> I assume you're doing this by making multiple separate channels. There isn't a good way to avoid making a separate DNS lookup for each.

Yes it's through separate channels. Some libraries allow you to provide a custom DNS lookup function, is that something that could be added to `grpc-js`?

Reference: https://httptoolkit.com/blog/configuring-nodejs-dns/

> The rest of the time between that and the resolving_load_balancer transitioning to READY is connection establishment, but that might include multiple successive connection attempts

A few times  I see the trace `resolving_load_balancer` in between the two `Looking up` and `Resolved addresses` trace for `dns_resolver`. It always logs the state as `IDLE -> CONNECTING` so I am assuming until the DNS resolution completes, this particular trace for `resolving_load_balancer` just indicates it's waiting for the DNS lookup to complete first?

**Comment by murgatroid99** [comment]
> Yes it's through separate channels. Some libraries allow you to provide a custom DNS lookup function, is that something that could be added to `grpc-js`?

There are APIs in the `experimental` namespace that allow you create your own resolver, specifically `experimental.registerResolver`, but it's more heavy-weight than just defining an override for the `lookup` function. **Note that these experimental APIs are unstable, and can change in any minor version.**

You could register the resolver with whatever scheme you want, and then use that scheme instead of the default `dns` to use that resolver.

> A few times I see the trace `resolving_load_balancer` in between the two `Looking up` and `Resolved addresses` trace for `dns_resolver`. It always logs the state as `IDLE -> CONNECTING` so I am assuming until the DNS resolution completes, this particular trace for `resolving_load_balancer` just indicates it's waiting for the DNS lookup to complete first?

When the resolving load balancer exits the IDLE state, it tells the resolver to start resolving, and then immediately transitions to the CONNECTING state. So, you will see those trace logs in that order, but they happen at essentially the same time. The `IDLE -> CONNECTING` transition happens when it starts doing any work that could eventually result in a connection, and the `CONNECTING -> READY` transition happens when a connection is established.

**Comment by pratik151192** [comment]
Thanks for your answers and those pointers @murgatroid99. I am closing the issue for now as that answers my questions!
