### ISSUE TITLE
How can I disable the Load Reporting Service in the xds client?

### ISSUE THREAD

**Issue by darren-west** [grpc/grpc-node#2556]
### Description
I have a use case for disabling lrs in the xds client because the endpoint I am using does not support it, is there a way to disable it? As I currently get unimplemented errors every-time I make a request.

**Comment by murgatroid99** [comment]
In the `Cluster` resource, the `lrs_server` field is optional, and if it is unset then the client won't start an LRS stream. So, if the xDS server does not support the LRS service, it should not set that field in the `Cluster` resource.
