### ISSUE TITLE
CPU occasionally spike after bumping to grpc-js 1.9.0

### ISSUE THREAD

**Issue by schen22-9527** [grpc/grpc-node#2560]
### Problem description
We have enabled o11y to our service. After bumping to grpc-js 1.9.0, CPU occasionally spikes.

### Reproduction steps
Ref https://github.com/open-telemetry/opentelemetry-js/issues/4082

### Environment
 - Node version: v14.21.3
 - Package name and version: @grpc/grpc-js 1.9.0

**Comment by murgatroid99** [comment]
There are two things that would likely help determine the cause of this:

 1. A CPU profile for a time period that includes a spike. See [this documentation](https://nodejs.org/en/docs/guides/simple-profiling) for how to get one.
 2. A full gRPC trace log for a time period that includes a spike. The process will output this to stderr if you set the environment variables `GRPC_TRACE=all` and `GRPC_VERBOSITY=DEBUG`.

**Comment by murgatroid99** [comment]
These logs are for a 5 millisecond time span. Does that correspond to a CPU usage spike?

**Comment by murgatroid99** [comment]
That fix is out in version 1.9.2. Please try it out.

**Comment by schen22-9527** [comment]
confirmed the issue fixed. Thanks @murgatroid99 !
