### ISSUE TITLE
Client hangs after create child called 

### ISSUE THREAD

**Issue by supermeng** [grpc/grpc-node#2574]
### Problem description
We have an api which will do a grpc call to another server, when I do some performance test to this api with go-wkr, some of the request will be hang, and will return code=1 details=\"Call cancelled\"\n after we restart the server.
go-wrk params: 
connections=100
duration=60s
timeout=60s

### Reproduction steps
1. deployed our server
2. run `go-wrk -c 100 \
    -d 60 \
    -T 60000 \
    https://host:port/api/v1/communities/search/list`

### Environment
 - OS name, version and architecture: Linux 3.10.0-1160.76.1.el7.x86_64 SMP Wed Aug 10 16:21:17 UTC 2022 x86_64 Linux
 - Node version: v14.17.6
 - Node installation method: docker image 14-alpine3.14
 - If applicable, compiler version [e.g. clang 3.8.0-2ubuntu4]
 - Package name and version: gRPC@1.8.21

### Additional context
sample log:
```
{"log":"D 2023-09-14T11:51:09.687Z | channel | (25) dns:js-design-staging-java-search-svc:50061 createResolvingCall [10612] method=\"/searchV1.Search/communityResource\", deadline=Infinity\n","stream":"stderr","time":"2023-09-14T11:51:09.687600621Z"}
{"log":"D 2023-09-14T11:51:09.687Z | resolving_call | [10612] Created\n","stream":"stderr","time":"2023-09-14T11:51:09.687607355Z"}
{"log":"D 2023-09-14T11:51:09.687Z | resolving_call | [10612] Deadline: Infinity\n","stream":"stderr","time":"2023-09-14T11:51:09.687613459Z"}
{"log":"D 2023-09-14T11:51:09.687Z | resolving_call | [10612] start called\n","stream":"stderr","time":"2023-09-14T11:51:09.687634256Z"}
{"log":"D 2023-09-14T11:51:09.687Z | resolving_call | [10612] startRead called\n","stream":"stderr","time":"2023-09-14T11:51:09.68764045Z"}
{"log":"D 2023-09-14T11:51:09.687Z | resolving_call | [10612] write() called with message of length 144\n","stream":"stderr","time":"2023-09-14T11:51:09.687664302Z"}
{"log":"D 2023-09-14T11:51:09.687Z | resolving_call | [10612] halfClose called\n","stream":"stderr","time":"2023-09-14T11:51:09.687670427Z"}
{"log":"D 2023-09-14T11:51:09.687Z | resolving_call | [10612] Created child [10613]\n","stream":"stderr","time":"2023-09-14T11:51:09.687761044Z"}
{"log":"D 2023-09-14T12:53:16.135Z | resolving_call | [10612] Received status\n","stream":"stderr","time":"2023-09-14T12:53:16.135807083Z"}
{"log":"D 2023-09-14T12:53:16.135Z | resolving_call | [10612] ended with status: code=1 details=\"Call cancelled\"\n","stream":"stderr","time":"2023-09-14T12:53:16.135813933Z"}
```

**Comment by murgatroid99** [comment]
There are logs missing here. In particular, there should be another  `channel` log that says either `createRetryingCall` or `createLoadBalancingCall` before the `Created child` log. Please get a complete log and share it.

**Comment by supermeng** [comment]
I filtered log with number 10612 and 10613:
```{"log":"D 2023-09-14T11:51:09.687Z | channel | (25) dns:js-design-staging-java-search-svc:50061 createResolvingCall [10612] method=\"/searchV1.Search/communityResource\", deadline=Infinity\n","stream":"stderr","time":"2023-09-14T11:51:09.687600621Z"}
{"log":"D 2023-09-14T11:51:09.687Z | resolving_call | [10612] Created\n","stream":"stderr","time":"2023-09-14T11:51:09.687607355Z"}
{"log":"D 2023-09-14T11:51:09.687Z | resolving_call | [10612] Deadline: Infinity\n","stream":"stderr","time":"2023-09-14T11:51:09.687613459Z"}
{"log":"D 2023-09-14T11:51:09.687Z | resolving_call | [10612] start called\n","stream":"stderr","time":"2023-09-14T11:51:09.687634256Z"}
{"log":"D 2023-09-14T11:51:09.687Z | resolving_call | [10612] startRead called\n","stream":"stderr","time":"2023-09-14T11:51:09.68764045Z"}
{"log":"D 2023-09-14T11:51:09.687Z | resolving_call | [10612] write() called with message of length 144\n","stream":"stderr","time":"2023-09-14T11:51:09.687664302Z"}
{"log":"D 2023-09-14T11:51:09.687Z | resolving_call | [10612] halfClose called\n","stream":"stderr","time":"2023-09-14T11:51:09.687670427Z"}
{"log":"D 2023-09-14T11:51:09.687Z | channel | (25) dns:js-design-staging-java-search-svc:50061 createRetryingCall [10613] method=\"/searchV1.Search/communityResource\"\n","stream":"stderr","time":"2023-09-14T11:51:09.687747853Z"}
{"log":"D 2023-09-14T11:51:09.687Z | resolving_call | [10612] Created child [10613]\n","stream":"stderr","time":"2023-09-14T11:51:09.687761044Z"}
{"log":"D 2023-09-14T11:51:09.687Z | retrying_call | [10613] start called\n","stream":"stderr","time":"2023-09-14T11:51:09.687774847Z"}
{"log":"D 2023-09-14T11:51:09.687Z | retrying_call | [10613] Created child call [10614] for attempt 1\n","stream":"stderr","time":"2023-09-14T11:51:09.687800208Z"}
{"log":"D 2023-09-14T11:51:09.687Z | retrying_call | [10613] startRead called\n","stream":"stderr","time":"2023-09-14T11:51:09.687847958Z"}
{"log":"D 2023-09-14T11:51:09.688Z | retrying_call | [10613] write() called with message of length 149\n","stream":"stderr","time":"2023-09-14T11:51:09.688115002Z"}
{"log":"D 2023-09-14T11:51:09.688Z | retrying_call | [10613] halfClose called\n","stream":"stderr","time":"2023-09-14T11:51:09.68817388Z"}
{"log":"D 2023-09-14T12:53:16.109Z | retrying_call | [10613] Received status from child [10614]\n","stream":"stderr","time":"2023-09-14T12:53:16.109525683Z"}
{"log":"D 2023-09-14T12:53:16.109Z | retrying_call | [10613] state=TRANSPARENT_ONLY handling status with progress PROCESSED from child [10614] in state ACTIVE\n","stream":"stderr","time":"2023-09-14T12:53:16.109532881Z"}
{"log":"D 2023-09-14T12:53:16.109Z | retrying_call | [10613] ended with status: code=1 details=\"Call cancelled\"\n","stream":"stderr","time":"2023-09-14T12:53:16.109573294Z"}
{"log":"D 2023-09-14T12:53:16.135Z | resolving_call | [10612] Received status\n","stream":"stderr","time":"2023-09-14T12:53:16.135807083Z"}
{"log":"D 2023-09-14T12:53:16.135Z | resolving_call | [10612] ended with status: code=1 details=\"Call cancelled\"\n","stream":"stderr","time":"2023-09-14T12:53:16.135813933Z"}```

and the full log is in this [url](https://staging.img.js.design/assets/docs/grpc_hang.log)

**Comment by murgatroid99** [comment]
My reading of that log is that the server simply didn't respond to some of the requests. We know that the connection to the server was working, both because some of the requests made on that same connection succeeded, and because the client consistently received keepalive ping responses. I don't see any difference in client-side behavior between this request that failed, and other requests that succeeded.

I think your server is dropping requests when overloaded, but it isn't communicating those drops to the client, so the client just waits forever for the response.

**Comment by supermeng** [comment]
Thanks so much for your reply, we will do some test to the grpc directly. 
One more thing, I do not know much about the create child logic, and I saw much create child call after number 10612, just like 10613, 10614 and 10615, but every things got stuck after 10615 halfClose called:
`{"log":"D 2023-09-14T11:51:09.688Z | load_balancing_call | [10614] Created child call [10615]\n","stream":"stderr","time":"2023-09-14T11:51:09.688066791Z"}
{"log":"D 2023-09-14T11:51:09.688Z | subchannel_call | [10615] write() called with message of length 149\n","stream":"stderr","time":"2023-09-14T11:51:09.688138615Z"}
{"log":"D 2023-09-14T11:51:09.688Z | subchannel_call | [10615] sending data chunk of length 149\n","stream":"stderr","time":"2023-09-14T11:51:09.688144187Z"}
{"log":"D 2023-09-14T11:51:09.695Z | subchannel_call | [10615] end() called\n","stream":"stderr","time":"2023-09-14T11:51:09.69608686Z"}
{"log":"D 2023-09-14T11:51:09.695Z | subchannel_call | [10615] calling end() on HTTP/2 stream\n","stream":"stderr","time":"2023-09-14T11:51:09.696092841Z"}
{"log":"D 2023-09-14T12:53:16.095Z | subchannel_call | [10615] HTTP/2 stream closed with code 8\n","stream":"stderr","time":"2023-09-14T12:53:16.09577347Z"}
{"log":"D 2023-09-14T12:53:16.095Z | subchannel_call | [10615] ended with status: code=1 details=\"Call cancelled\"\n","stream":"stderr","time":"2023-09-14T12:53:16.09577824Z"}`
Could u please be so kind to tell me how the create child works and why the [10615] got stuck after halfClose(calling end()) called?  Thanks so much :D

**Comment by murgatroid99** [comment]
It's not "stuck", it's just waiting for a response that it never gets.

In grpc-js, a "call" is represented by multiple objects that are responsible for different parts of making the request. The "Created child" logs are just each object creating the next object in the chain. The subchannel call is the lowest level object, interacting directly with HTTP/2 streams.

**Comment by supermeng** [comment]
Oh, got it. After some pressure test to our grpc server, we have replayed the dropped request Scenes in our grpc server and fixed it. Thanks so much.
