### ISSUE TITLE
HowTo: include a types.proto file with the service definition

### ISSUE THREAD

**Issue by kstatz12** [grpc/grpc-node#2577]
Im using the runtime/dynamic generation for a proto client. We have our services.proto and types.proto broken out into two files and I cant figure out how to support that path. I think im just being dense though

```
var typesDefinition = protoLoader.loadSync(
  typesPath,
  {
    keepCase: true,
    longs: String,
    enums: String,
    defaults: true,
    oneofs: true
  }
);



var commandsDefinition = protoLoader.loadSync(
  commandsPath,
  {
    keepCase: true,
    longs: String,
    enums: String,
    defaults: true,
    oneofs: true
  }
);




var packageDefinition = protoLoader.loadSync(
  servicePath,
  {
    keepCase: true,
    longs: String,
    enums: String,
    defaults: true,
    oneofs: true
  }
);



```

results in

```
Error: no such type: users.commands.CreateUser
```

**Comment by murgatroid99** [comment]
I suggest following the usage instructions in [the README](https://www.npmjs.com/package/@grpc/proto-loader). If you have further questions, please show how you followed those instructions and what problem you are still having.
