### ISSUE TITLE
gRPC xds client stops working after a period of inactivity. 

### ISSUE THREAD

**Issue by darren-west** [grpc/grpc-node#2579]
### Problem description
When upgrading beyond `1.8.2` (e.g. 1.9) we have been facing an issue where a gRPC client using xds is no longer able to make request and hangs indefinitely, it can be resolved by rotating the process running the client. The logs I see upon making a request are as below:

```
2023-09-21T08:17:01.920Z | resolving_load_balancer | xds:///api.test:5000 IDLE -> CONNECTING
2023-09-21T08:17:02.173Z | resolving_load_balancer | xds:///api.test:5000 CONNECTING -> IDLE
2023-09-21T08:17:02.174Z | resolving_load_balancer | xds:///api.test:5000 IDLE -> CONNECTING
```

I have tried setting keepalives in both server and client. When the client gets in this state it no longer logs endpoint updates, which makes me think its not receiving them. 

The issue does not exist in 1.8.2.

### Reproduction steps
Unsure how to show reproduction, our client tends to stop working after about 2 hours of inactivity. 

### Environment
 - Linux Alpine  3:16 x86_64
 - 18
 - nvm
 - gRPC 1.9

**Comment by murgatroid99** [comment]
I reproduced this problem. It is a bug in how channel idleness (which was added in version 1.9.0) is handled in the xDS stack. I'll try to get a fix out for this soon.

**Comment by murgatroid99** [comment]
I published a change in version 1.9.1 that fixes this problem, according to my local testing. Please try it out.

**Comment by darren-west** [comment]
Thanks I will try this out shortly and let you know

**Comment by darren-west** [comment]
Hi @murgatroid99 I updated to the latest packages and have some other issues
```
no such Type or Enum 'data.accesslog.v3.AccessLogType' in Type .envoy.config.accesslog.v3.LogTypeFilter
```

Versions
```
"@grpc/grpc-js": "^1.9.3",
"@grpc/grpc-js-xds": "^1.9.1",
```

**Comment by murgatroid99** [comment]
Fixed in version 1.9.2.

**Comment by murgatroid99** [comment]
@darren-west Can you confirm whether the newest version of `@grpc/grpc-js-xds` resolves your problem?

**Comment by darren-west** [comment]
@murgatroid99 yes it did thanks
