### ISSUE TITLE
A deadlock case

### ISSUE THREAD

**Issue by tomatoFQ** [grpc/grpc-node#2588]
### Problem description
My service CPU usage has reached 100%, after upgrading grpc to 1.9.1.
I found that the deadlock was caused by grpc continuously performing the doPick operation in load-balancing-call.ts, when subchannel.getConnectivityState() equals ConnectivityState.IDLE

### Reproduction steps
I don't know how to reproduct it. I just make client calls, 

### Environment
 - OS name, version and architecture: [Linux CentOS 7.2.1511 x86_64]
 - Node version [16.18.0]
 - Node installation method [nvm]
 - Package name and version [@grpc/grpc-js@1.9.1]

### Additional context
This log is a cpuprofile, you can open it in Chrome Dev Tools -> Performance
[100cpu.log](https://github.com/grpc/grpc-node/files/12737549/100cpu.log)

**Comment by murgatroid99** [comment]
Fortunately, that bug was fixed in grpc-js version 1.9.2. I suggest updating your dependencies.

**Comment by tomatoFQ** [comment]
> Fortunately, that bug was fixed in grpc-js version 1.9.2. I suggest updating your dependencies.

Thanks
