### ISSUE TITLE
proto-loader-gen-types strict types

### ISSUE THREAD

**Issue by alyahmedaly** [grpc/grpc-node#2601]
### Problem description

when trying to generate types from a proto file for example

```proto
syntax = "proto3";

package echo.service;


service EchoService {
  rpc echo (Hello) returns (Replay) {}
}

message Hello {
  string name = 1;
}

message Replay {
    string message = 1;
}
```

it generates an optional type for the request but not for the handler

```typescript
export interface Hello {
  name?: string;
}

export interface Hello__Output {
  name: string;
}
```

I would expect a strict type for both types since `optional` modifier is not used in the proto file

**Comment by murgatroid99** [comment]
Omitting any field is valid when providing an object to be serialized using `@grpc/proto-loader`, so that optional modifier is correct.

**Comment by alyahmedaly** [comment]
@murgatroid99 I understand now why this is the default behavior https://protobuf.dev/programming-guides/proto3/#default 

but do you think having a strict mode will improve the experience for the consumers for example if I got only access to the lib that is generated from proto files how I know if a field is required or not,
Please note I'm totally new to GRPC so maybe this is the wrong perspective

**Comment by murgatroid99** [comment]
There are no required fields in proto3. These generated type definitions just describe what objects will be accepted by the implementation. The field is specified as optional in the generated code because the implementation will accept an object with that field unset.
