### ISSUE TITLE
Unable to capture thrown errors when service unavailable

### ISSUE THREAD

**Issue by jambudipa** [grpc/grpc-node#2603]
The following code is throwing an error:
```
const client = new ChatServiceClient('localhost:8080', grpc.credentials.createInsecure());
const question = new Question(input);
const responseStream = client.AskQuestion(question, meta);
```
Now this service is unavailable, but wrapping this code block in try / catch seemingly has no effect. Why might that be?

I cannot see any way to handle this connection error and my node app just stops...
>Error: 14 UNAVAILABLE: No connection established. Last error: connect ECONNREFUSED 127.0.0.1:8080 (2023-10-19T20:59:35.951Z)

**Comment by murgatroid99** [comment]
Please check the [error handling example](https://github.com/grpc/grpc-node/tree/master/examples/error_handling) for more information about how to handle errors from requests in this library. Specifically, you need to set an `error` event handler by calling `responseStream.on('error', errorHandler)`, and if you do not, errors will be thrown as you see there.

**Comment by mark-norgate-ons** [comment]
Ok thanks, I'll do that.

**Comment by jillesme** [comment]
We had something similar. When providing the wrong credentials class (I accidentally used `createSsl` instead of `createInsecure`) the callback is never called and the error is nowhere to be found. Happy to put in a PR if this is an actual issue (it was for me).

**Comment by murgatroid99** [comment]
I just tested a client with SSL credentials talking to a server with insecure credentials, and I did get an error. Please provide example code that demonstrates the problem you are experiencing.

**Comment by jambudipa** [comment]
Oh, I did as suggested and put in an error handler, and that’s fixed my issue. Sorry I neglected to report back.Sent from my iPhoneOn 3 Nov 2023, at 20:43, Michael Lumish ***@***.***> wrote:﻿
I just tested a client with SSL credentials talking to a server with insecure credentials, and I did get an error. Please provide example code that demonstrates the problem you are experiencing.
