### ISSUE TITLE
package.json for grpc-tools missing license field

### ISSUE THREAD

**Issue by krisselden** [grpc/grpc-node#2607]
### Problem description
The published package for grpc-tools missing license field and package is missing LICENSE file from repo

### Reproduction steps
View package on https://www.npmjs.com/package/grpc-tools

It is missing https://github.com/grpc/grpc-node/blob/master/packages/grpc-tools/LICENSE
and https://github.com/grpc/grpc-node/blob/master/packages/grpc-tools/README.md

Looks like it should include it
https://github.com/grpc/grpc-node/blob/master/packages/grpc-tools/package.json#L41

Likely issue is it staged into a temp dir and packaged up from that.

**Comment by murgatroid99** [comment]
If I `npm install grpc-tools`, I see the `LICENSE` and `README.md` files in `node_modules/grpc-tools` and they both contain the expected content. The `grpc-tools` page on the npm website contains the text of the `README.md` file, and the code explorer there shows `LICENSE` in the list of files.

Cannot reproduce.

**Comment by krisselden** [comment]
@murgatroid99 the package.json in the tarball that is published to NPM does not have it. I know it is in the repo, I linked to it.

**Comment by krisselden** [comment]
If you look at the page in NPM, it says license: none

**Comment by krisselden** [comment]
https://docs.npmjs.com/cli/v10/configuring-npm/package-json#license

To clarify, because companies validate license field for compliant open source license and I had to get this library manually verified.

**Comment by murgatroid99** [comment]
The original issue said that the LICENSE and README.md files are not present in the tarball. They are in fact present, which is why I closed the issue. The problem you described after that is a different one: that the published package.json file does not have a "license" field. That is a separate thing from including the LICENSE file in the "files" list.
