### ISSUE TITLE
Are the 1.9.8 and 1.9.9 releases legitimate?

### ISSUE THREAD

**Issue by mdouglass** [grpc/grpc-node#2615]
### Problem description
Sorry to bother, but neither the 1.9.8 nor the 1.9.9 release are listed in this repository via releases or even tags so I wanted to confirm they were intentional releases of the project? If they are, is it possible to add tags so we can tell which changes from  were included in them?

### Additional context
https://www.npmjs.com/package/@grpc/grpc-js/v/1.9.9
https://www.npmjs.com/package/@grpc/grpc-js/v/1.9.8

compare with 1.9.7 which has both a release and a tag
https://github.com/grpc/grpc-node/releases/tag/%40grpc%2Fgrpc-js%401.9.7

**Comment by murgatroid99** [comment]
Yes, those are legitimate. Release notes are available for those versions.

**Comment by mdouglass** [comment]
Excellent, thank you :)
