### ISSUE TITLE
Infinite Looping Calls via grpc

### ISSUE THREAD

**Issue by Treterten** [grpc/grpc-node#2621]
### Problem description
During operation, we are seeing that `grpc-js` is making multiple calls to one of our services and causing multiple restarts and/or  crashes. This is when running in a kubernetes pod and making calls to a service within the same cloud provider region. 

### Environment
 - OS name, version and architecture: Debian GNU/Linux 11 (bullseye)
 - Node version: 18.18.0
 - Node installation method: Installed into container image
 - If applicable, compiler version **N/A**
 - Package name and version: `@grpc/grpc-js >= 1.9.6`

### Additional context
[Logs](https://github.com/grpc/grpc-node/files/13432671/errorlogs.txt)

**Comment by murgatroid99** [comment]
Can you update to the latest version (1.9.11) and verify whether you experience the same problem?

**Comment by murgatroid99** [comment]
Actually, I just published a change in version 1.9.12 that might fix this. Please try that out.

**Comment by pmalouin** [comment]
Version 1.9.12 fixed the issue for us. Thanks a lot on the quick fix 🙇‍♂️
