### ISSUE TITLE
ObjectWritable.write(chunk, cb) issue with node >18

### ISSUE THREAD

**Issue by Toffels** [grpc/grpc-node#2627]
### Problem description
Can't write messages with `grpc.ClientDuplexStream.write` in node >19, while it's working with node 18.17.
When using `grpc.ClientDuplexStream.write` in node 19.9 (or 21.3), it will return false.
Additionally the callback will be called with arguments beeing: `[null]`

### Reproduction steps
```ts
import * as grpc from "@grpc/grpc-js";
import * as services from "<xxx>/proto"; // Some proto code.
const grpc = new services.MessageExchangeClient(
   url,
   credentials,
   {
        "grpc.enable_retries": 10000,
        "grpc.initial_reconnect_backoff_ms": 1000,
        "grpc.max_reconnect_backoff_ms": 30000,
        "grpc.min_reconnect_backoff_ms": 5000,
        "grpc.keepalive_time_ms": 45000,
        "grpc.keepalive_timeout_ms": 120000,
        "grpc.http2.min_time_between_pings_ms": 30000,
        "grpc.http2.min_ping_interval_without_data_ms": 30000,
        "grpc.keepalive_permit_without_calls": 1,
        "grpc.http2.max_pings_without_data": 0,
   }
);

const grpcStream = grpc.subscribe();
   // some listeners
   
new Promise<void>((resolve, reject) => {
  const messageSend = grpcStream.write(data, (...args: unknown[]) => {
          if (args.length > 0) {
            reject(`Write error: args.length > 0 [${args}]`);
            //                                                          ^ this will be an array of [ null ]
            // Which is pretty inconvenient to figure out what is actually going on.
          } else {
            resolve();
          }
     });
     
   if(messageSend) console.log("success");
   else console.log("failure");
   //      ^ this will be the result.
});
```

### Environment
 - Linux Ubuntu 18.04 x86_64
 - Node version: Issue: `19 - 21.3`, Works in: `<19 (e.g. 18.17)`
 - Node installation method: n (https://www.npmjs.com/package/n)
 - Package name and version: `"@grpc/grpc-js": "^1.9.12"`

### Additional context
I'm sorry, can't afford the time right now to setup proper reproduction!
All I'm hoping for is, to understand if this is a known/common issue, or if I messed up the code 2 years ago already.
It's not too big of a deal, but it prevents from upgrading node version above 18.17 for now.

Either I'm unable to search properly or I'm the only one with this issue :man_shrugging: :disappointed:

**Comment by murgatroid99** [comment]
Nothing is failing here. The [`Writable#write` documentation](https://nodejs.org/api/stream.html#writablewritechunk-encoding-callback) says this:

> The return value is `true` if the internal buffer is less than the `highWaterMark` configured when the stream was created after admitting `chunk`. If `false` is returned, further attempts to write data to the stream should stop until the [`'drain'`](https://nodejs.org/api/stream.html#event-drain) event is emitted.

In addition, it is not specific about the arguments to the callback, but `null` usually indicates the absence of an error in these callbacks.

So, you should be checking the return value from `write`, to decide whether to keep writing or to wait for the `'drain'` event. You probably don't need to pass a callback to `write`, because any write error will result in the call ending with a non-OK status, which you should be watching for anyway.

**Comment by Toffels** [comment]
@murgatroid99 thanks a lot for pointing that out and give an initial explanation!
I read and will re-read the docs.
