### ISSUE TITLE
@grpc/grpc-js Memory leak with latest version

### ISSUE THREAD

**Issue by ArtemAdamenko** [grpc/grpc-node#2629]
### Problem description
Memory leak on each request

### Reproduction steps
I send from my bash script 120 grpc requests to one grpc method. Between each request 1 second sleep. After requests I see ~ 120 objects and their references in heap and GC don't sweep them.

### Environment
 - MacOS SOnoma 14.1.2 arm64/ Linux Ubuntu 20.04 amd64
 - Node version 14.1.3
 - nvm/native
 - grpc/grpc-js 1.9.12
<img width="1218" alt="Screenshot 2023-12-13 at 18 26 24" src="https://github.com/grpc/grpc-node/assets/2178516/2954c5e9-f91c-45f9-be06-c424cf799e28">
<img width="1434" alt="Screenshot 2023-12-13 at 18 27 49" src="https://github.com/grpc/grpc-node/assets/2178516/773ceaf8-e443-4555-bff8-f7b02fc3d8bf">
<img width="1218" alt="Screenshot 2023-12-13 at 18 28 32" src="https://github.com/grpc/grpc-node/assets/2178516/78f6b62b-f135-4245-8375-7e5bafb06be2">
<img width="1436" alt="Screenshot 2023-12-13 at 18 28 17" src="https://github.com/grpc/grpc-node/assets/2178516/a229f302-162f-4ecd-9a62-f76eb6307a6f">
<img width="1391" alt="Screenshot 2023-12-13 at 18 28 09" src="https://github.com/grpc/grpc-node/assets/2178516/b7aa9597-7d73-4539-88bd-66d665128dc5">
<img width="1440" alt="Screenshot 2023-12-13 at 18 28 01" src="https://github.com/grpc/grpc-node/assets/2178516/99daaf66-0547-4d67-ad4a-126f39a61b9a">

**Comment by murgatroid99** [comment]
This shows that you are constructing a new Client/Channel for each request you make. We recommend that you do not do that, and instead make all of the requests using the same Client. If you do use a separate Client for each one, you need to call `.close` on them when you are done, or they will be retained.

**Comment by ArtemAdamenko** [comment]
Can I close channel through client.getChannel().close() ?

**Comment by murgatroid99** [comment]
You can just call `client.close()`. `client.getChannel().close()` will do the same thing.

**Comment by ArtemAdamenko** [comment]
client.close() and client.getChannel().close() doesn't any effect
<img width="1341" alt="Screenshot 2023-12-14 at 17 37 03" src="https://github.com/grpc/grpc-node/assets/2178516/a6068a17-b70d-46af-9896-515d54dea0b2">

**Comment by ArtemAdamenko** [comment]
I do call method with client context
`            new Promise((resolve, reject) => {
                clientMethod.call(client, ...args, (err, data) => {
                    if (err) {
                        reject(err);
                    }
                    client.close();
                    resolve(data);
                });
            })
                .then((data) => {`
                
                and nothing

**Comment by murgatroid99** [comment]
Please share your complete test code. The new heap dump is showing 10 instances of each object where the original one showed 120, so clearly something is different.

**Comment by ArtemAdamenko** [comment]
I did 10 requests there

**Comment by murgatroid99** [comment]
Please share your complete test code

**Comment by ArtemAdamenko** [comment]
`
export interface Additional {
    service: string;
    microServiceName: string;
    microServicePort: string;
    microServiceIp: string;
}

type AClient = Client & Additional;

private unaryCallHandler(
        client: AClient,
        method: string,
        endpoint: ServiceEndPoint | undefined,
        clientMethod: Function,
        args: any[],
    ): any {
        return (endpoint ? of(endpoint) : this.discoveryService.getServiceEndPoint(client.microServiceName)).pipe(
            tap(({ port, ip }) => {
                client.microServicePort = port;
                client.microServiceIp = ip;
            }),
            switchMap(
                () =>
                    new Observable((observer) => {
                        // Set current correlationId to Metadata to use id inside next micro-service
                        let meta = args[1] as Metadata;
                        if (!meta) {
                            // Set new metadata if no is passed
                            meta = args[1] = new Metadata();
                        }

                        this.requestContextService.setCorrelationIdToMeta(this.requestContextService.getCorrelationId(), meta);
                        this.requestContextService.setCallsDepthInMeta(this.requestContextService.getCallsDepth() + 1, meta);

                        new Promise((resolve, reject) => {
                            clientMethod.bind(client, ...args, (err: unknown, data: unknown) => {
                                if (err) {
                                    reject(err);
                                }
                                client.close();
                                resolve(data);
                            });
                        })
                            .then((data) => {
                                client.close();
                                observer.next(data);
                                observer.complete();
                            })
                            .catch((err) => {
                                observer.error(err);
                            });
                    }),
            ),
            catchError((err: unknown) => {
                ...
            }),
        );
    }`

**Comment by murgatroid99** [comment]
1. You probably shouldn't be closing the client in this section of code, because you are not creating it in this section of code. If you modify whatever part of your code manages the client object(s) to reuse a single client, closing it here will break other requests.
2. You don't close the client at all in the error codepath.
3. You don't show the code that creates the client object. It may be retaining that object in some other way.
4. You do not explicitly invoke the garbage collector, so you don't know that the garbage collector actually runs. If the garbage collector doesn't run, then none of this indicates anything about a memory leak. See [this post](https://stackoverflow.com/a/30654451/159388) for information on explicitly calling the garbage collector.

**Comment by ArtemAdamenko** [comment]
https://gist.github.com/ArtemAdamenko/d12d6b6b41a458cccfd943448ad22a63
https://gist.github.com/ArtemAdamenko/3aa37205a9ad0a57684e84a3920932a8

**Comment by murgatroid99** [comment]
In `callTransformer` you are constructing a new `Channel`, and you never close that. That accounts for all of the retained memory you saw.

We really do not recommend using a `callInvocationTransformer` at all, and I don't see any reason to do so here. You can just construct the client with the options you are using to construct that channel.

**Comment by ArtemAdamenko** [comment]
Where I can replace these options in my code ?

**Comment by murgatroid99** [comment]
In the call to `new serviceConstructor`, just pass those options, instead of the `callInvocationTransformer` option.

**Comment by ArtemAdamenko** [comment]
But without creating new channel in callTransformer I need create channel in other place ?

**Comment by murgatroid99** [comment]
A client object, which is what is created by `serviceConstructor`, already has its own channel that it uses to make requests. You don't need to explicitly create another one at all.

**Comment by ArtemAdamenko** [comment]
Can I set ip and port ? Because I setted that in transformer, where I was creating new channel

**Comment by murgatroid99** [comment]
Just pass the `IP:port` string where you are currently passing the `microServiceName`.

**Comment by ArtemAdamenko** [comment]
Best thanks!
