### ISSUE TITLE
proto-loader-gen-types Warning: **/*.proto not found in any of the include paths ../protos

### ISSUE THREAD

**Issue by init-center** [grpc/grpc-node#2657]
### Problem description
The command I wrote in the scripts of `package.json`：
```sh
proto-loader-gen-types --keepCase --longs=String --enums=String --defaults --oneofs --grpcLib=@grpc/grpc-js --includeDirs=../protos --outDir=pb/types **/*.proto
```
My file tree：
```
.
├── client_js
│   ├── package.json
│   ├── pb
│   │   └── types
│   ├── src
│   │   └── main.ts
│   └── tsconfig.json
├── protos
│   └── test.proto
```
got the following warning.：
```sh
(node:40025) Warning: **/*.proto not found in any of the include paths ../protos
(Use `node --trace-warnings ...` to show where the warning was created)
[Error: ENOENT: no such file or directory, open '**/*.proto'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '**/*.proto'
}
```
But it's no problem for me to change the wildcard to a specific file，like this：
```
proto-loader-gen-types --keepCase --longs=String --enums=String --defaults --oneofs --grpcLib=@grpc/grpc-js --includeDirs=../protos --outDir=pb/types test.proto
```
But if there are many files in the future, it will be very troublesome to use this method. How can I solve this problem? Thank you.

### Environment
 - OS name, version and architecture: Mac OS 14.0
 - Node version v18.17.0
 - Node installation method  nvm
 - Package name and version @grpc/grpc-js 1.9.14，@grpc/proto-loader 0.7.10

**Comment by murgatroid99** [comment]
File name patterns like that are handled by the shell that your code is running in. Generally, if there are no files matching a pattern, the shell will instead pass through the pattern string unmodified, which is what seems to be happening there. The `**` pattern in particular is not a standard pattern, but an extension. If you are using Bash, I suggest checking out the "globstar" setting. You may need to enable it to get that to work. If you are using some other shell, it may have a similar setting.

**Comment by init-center** [comment]
> File name patterns like that are handled by the shell that your code is running in. Generally, if there are no files matching a pattern, the shell will instead pass through the pattern string unmodified, which is what seems to be happening there. The `**` pattern in particular is not a standard pattern, but an extension. If you are using Bash, I suggest checking out the "globstar" setting. You may need to enable it to get that to work. If you are using some other shell, it may have a similar setting.

Thank you for your reply. After your reminder, I have found the reason. npm uses `/bin/sh` to execute the script by default, and it does not support `globstar`.

My problem was solved by setting `script-shell=/bin/zsh` in `.npmrc`.
