### ISSUE TITLE
gRPC client xDS failing to reconnect after MaxConnectionIdle

### ISSUE THREAD

**Issue by darren-west** [grpc/grpc-node#2666]
### Problem description
When using the gRPC node client with xDS we have experienced an issue where the client fails to handle the server ending an idle connection.  This seems to have become a problem from after v1.8

We are using a Go gRPC server with MaxConnectionIdle and after the server ends the connection I can see the client logs `CONNECTING -> IDLE` repeatedly and calls hang until the client times out. 

### Reproduction steps
To reproduce connect a client gRPC using xDS to a server with MaxConnectionIdle and leave the connection idle for longer than the timeout, then try to make a request. 

### Environment
 - OS [Alpine]
 - Node version [20.3.1]
 - Package name and version ["@grpc/grpc-js": "^1.10.0", "@grpc/grpc-js-xds": "^1.10.0"]

### Additional context
I have seen this a few times across a variety of Docker images, so Im not sure it is related to a single OS.

**Comment by murgatroid99** [comment]
I think I have reproduced this. I'll try to get a fix out soon.

**Comment by murgatroid99** [comment]
I have published a patch to fix this in grpc-js version 1.10.1. Please try it out.
