### ISSUE TITLE
I checked there is recent release on server interceptors , can you please add documentation how this can be configured

### ISSUE THREAD

**Issue by kirankumarkn** [grpc/grpc-node#2682]
### Problem description
A clear and concise description of what the problem is.

### Reproduction steps
Give very precise steps you've discovered to reproduce your problem. If possible and applicable, provide us with a repository we can clone that contains a reproduction case. Also if possible and applicable, please include a Dockerfile that exhibits the problem if it's specific to a certain environment. Bug reports with no reproduction steps will be closed.

### Environment
 - OS name, version and architecture: [e.g. Linux Ubuntu 18.04 amd64]
 - Node version [e.g. 8.10.0]
 - Node installation method [e.g. nvm]
 - If applicable, compiler version [e.g. clang 3.8.0-2ubuntu4]
 - Package name and version [e.g. gRPC@1.12.0]

### Additional context
Add any other context about the problem here. If possible, attach full logs. Do not try to omit anything for brevity, but instead include absolutely everything. Please try and set your operating system's locale to English, so that logs contain error messages in the English language.

**Comment by murgatroid99** [comment]
As stated in the release notes, detailed information about that feature can be found in [gRFC L112](https://github.com/grpc/proposal/blob/master/L112-node-server-interceptors.md). All of the information you need can be found there. If you have specific questions feel free to follow up.

**Comment by kirankumarkn** [comment]
Is there any document, I can referrer for configuring in Js , not typescript, please let me know Thanks

**Comment by kirankumarkn** [comment]
I have followed adding a server interceptor in the below code. But when you call service from client , console log in server interceptor it is not logged. Is there any thing I have missed 

// Server code
const packageDefinition = protoLoader.loadSync(LINKPROTO, {
  keepCase: true,
  longs: String,
  enums: String,
  arrays: true,
  includeDirs: ['node_modules/google-proto-files', 'proto']
})

const linksProto = grpc.loadPackageDefinition(packageDefinition)
const serverAddress = `${process.env.SERVER_IP_ADDRESS}:${process.env.SERVER_PORT}`

const interceptors = [(methodDescriptor, call) => {
  console.log('called interceptors', call)
   return new grpc.ServerInterceptingCall(call);
 }]


const server = new grpc.Server(interceptors)

server.addService(linksProto.LinkService.service, {
  ListLinks: listLinks
})

server.bindAsync(
  serverAddress,
  grpc.ServerCredentials.createInsecure(), () => {
    console.log(`Server running at ${serverAddress}`)
  })



// Client code 

function main() {
    let metadata = new grpc.Metadata();
    metadata.add('authorization', 'test Data')
    
    let client = new LinkService("localhost:30043", grpc.credentials.createInsecure());
    client.ListLinks({"parent":"partners/partner-1"},metadata,(err,data) => {
      if(!err){
        console.log('data', JSON.stringify(data));
      }
      else{
        console.log('error', err);
      }
    });
}

**Comment by kirankumarkn** [comment]
I think need a document on how to configure serverListener. Please check above server code and client code, when I call service interceptors are not called. Please let me know if any suggestions

**Comment by murgatroid99** [comment]
Your server constructor call should be

```js
const server = new grpc.Server({interceptors: [interceptors]});
```

**Comment by kirankumarkn** [comment]
> Your server constructor call should be
> 
> ```js
> const server = new grpc.Server({interceptors: [interceptors]});
> ```

Thank you for pointing out the issue, I  am able to configure interceptors and log metadata and message in listener.

I have one query regarding handling metadata, usually metadata is handled for validating tokens, if the token is invalid. how do you handle , I don't see the call back function to throw an error. if I throw an error inside as below code. server is getting aborted here. please let me know how to handle the scenarios to stop further and throw back error to client

ex : withOnReceiveMetadata(function (metadata, next) {
    console.log('meta data Received', metadata);
    if(!token){
    throw new Error('Invalid token authentication failed')
      }
    next(metadata);
  })

**Comment by murgatroid99** [comment]
To do that, you would need to interact with the call passed in to the interceptor function, and call `call.sendStatus`. [Here is an example in the tests](https://github.com/grpc/grpc-node/blob/master/packages/grpc-js/test/test-server-interceptors.ts#L29-L47).

**Comment by kirankumarkn** [comment]
Thank you @murgatroid99.
