### ISSUE TITLE
Missing 1.10.6 @grpc/grpc-js tag/release

### ISSUE THREAD

**Issue by MattIPv4** [grpc/grpc-node#2721]
👋 https://www.npmjs.com/package/@grpc/grpc-js/v/1.10.6 exists on NPM, but https://github.com/grpc/grpc-node/releases/tag/%40grpc%2Fgrpc-js%401.10.6 & https://github.com/grpc/grpc-node/tree/%40grpc/grpc-js%401.10.6 don't exist, making it hard to determine what changes were included in the release, and if it is legitimate.

**Comment by MattIPv4** [comment]
Looking at https://npmdiff.dev/@grpc%2fgrpc-js/1.10.5/1.10.6, the change does seem to be non-malicious.

**Comment by murgatroid99** [comment]
The tag and release notes are up now. Thank you for bringing this to our attention.
