### ISSUE TITLE
Grpc Unary calls not giving any response after client is in idle for some time(30mins)

### ISSUE THREAD

**Issue by vamsideepak** [grpc/grpc-node#2748]
### Problem description
Client is in idle mode for almost 30 mins and after that If I made any calls I am able to see the response in streaming calls but for Unary calls it is not giving any response. So I thought it is problem with idle timers/deadlines for calls but how streaming is working when compare to the Unary calls. I tried below Keep alive options but still no luck. Is there any other way ?

Note : my client communication is happening via Named Pipes

### Code

```
const sslCreds = this.electronService.grpc.credentials.createInsecure();
    const keepAliveOptions = {
      'grpc.idle_timeout_ms': 31536000000, // One year in milliseconds
      'grpc.keepalive_time_ms':31536000000,
      'grpc.keepalive_timeout_ms': 31536000000,
      'grpc.keepalive_permit_without_calls':1,
    }
  
    this.scannerClient = new this.LittlePackage.GrpcService(this.periPheralPort, sslCreds,keepAliveOptions);

clientGetScanData(data) {
    console.log('this.scannerClient', this.scannerClient);
    this.scannerClient.GetScanData({
      pmSessionId: data.sessionId,
      transactionID: data.transactionId
    }, this.metadata, async (err, res) => {

      if (res) {
       console.log('res', res);
      }
    
    })
  }

````

### Environment
 - OS name - windows 11
 - Node version - 16.14.0
 - Node installation - exe manual installation
 - Package name and version-  gRPC@1.10.6

### Additional context
Observed the below option when I console the scannerClient

**Comment by murgatroid99** [comment]
The channel argument to change the client idle timeout is `grpc.client_idle_timeout_ms`, not `grpc.idle_timeout_ms`. That's why it uses the default value in this tests.

This is a bug caused specifically by the `unix:` URL scheme, which is why we didn't catch it before. The fix for that bug is in #2750, and I will publish that soon.

**Comment by vamsideepak** [comment]
@murgatroid99  I have done the below options 

```
const keepAliveOptions = {
      'grpc.client_idle_timeout_ms': 31536000000, // One year in milliseconds
      'grpc.keepalive_time_ms':31536000000,
      'grpc.keepalive_timeout_ms': 31536000000,
      'grpc.keepalive_permit_without_calls':1,
      
    }
```

Now unary calls are working fine but streaming is not working until I refresh the my application.

**Comment by murgatroid99** [comment]
What do you mean "streaming is not working"? What actual problem are you experiencing?

Also, the bug has been fixed, so you should upgrade to `@grpc/grpc-js@1.10.8` and revert the `grpc.client_idle_timeout_ms` setting. I also recommend setting more useful keepalive settings, now that we know that keepalives are not the cause of the problem. 1 minute is a reasonable value for the keepalive time, and 20 seconds is the default value for the keepalive timeout.

**Comment by vamsideepak** [comment]
@murgatroid99  Just now upgrade to @grpc/grpc-js@1.10.8 and checking on it .

Initial problem:
My client is idle for sometime like almost 1 hour and after that if I make Grpc call to the server then it is not happening , and to make it work I need to restart my client then only it is working again.  

After some Changes:
I have added the below configurations for keep alive and after this if client is idle for 1 hour then I am not able to receive any streaming calls data.
```
const keepAliveOptions = {
      'grpc.client_idle_timeout_ms': 31536000000, // One year in milliseconds
      'grpc.keepalive_time_ms':31536000000,
      'grpc.keepalive_timeout_ms': 31536000000,
      'grpc.keepalive_permit_without_calls':1,
      
    }
```
Note: I am using the named Pipe communication.

**Comment by murgatroid99** [comment]
I suggest that you try the following configuration

```
const keepaliveOptions = {
  'grpc.keepalive_time_ms': 60000
}
```

with all of the other options unset.

**Comment by vamsideepak** [comment]
@murgatroid99  Thanks for your inputs . I will close this once everything is working fine on my end after testing with recent upgrade of grpc.

**Comment by murgatroid99** [comment]
I think we need more information to determine what is causing this problem. Can you run your client and server with the environment variables `GRPC_TRACE=all` and `GRPC_VERBOSITY=DEBUG`, perform the test that results in this problem, and share the output?

**Comment by vamsideepak** [comment]
@murgatroid99  sure will do that and update here.

**Comment by vamsideepak** [comment]
_@murgatroid99  This has been tested and working fine . Thanks for all the quick response. Happy coding._
