### ISSUE TITLE
can we provide a detailed tutorial of grpc-js-xds?

### ISSUE THREAD

**Issue by wang-xiaowu** [grpc/grpc-node#2749]
### Is your feature request related to a problem? Please describe.
i am confusing of xds bootstrap use in istio

### Describe the solution you'd like
a clear code example of using grpc-js-xds

**Comment by murgatroid99** [comment]
There is a [blog post](https://istio.io/v1.13/blog/2021/proxyless-grpc/) about using Istio with gRPC proxyless service mesh (including `@grpc/grpc-js-xds`). As the blog post says, support for this in Istio is experimental and incomplete, so keep that in mind when you use it.

Regarding bootstap files in particular, that blog post says

> For gRPC servers, your Pod should also be annotated with `proxy.istio.io/config: '{"holdApplicationUntilProxyStarts": true}'` to make sure the in-agent xDS proxy and bootstrap file are ready before your gRPC server is initialized.

I also want to note that that blog post says that it supports mutual TLS, but that functionality is not yet supported in `@grpc/grpc-js-xds`.
