### ISSUE TITLE
`@grpc/grpc-js@latest` is pointing to an old version

### ISSUE THREAD

**Issue by mhassan1** [grpc/grpc-node#2774]
### Problem description
In NPM, the `latest` tag is pointing to `1.8.22`, instead of `1.10.9` (which is later). I'm assuming this is caused by a backport.

### Reproduction steps
```sh
npm install @grpc/grpc-js
node -p "require('@grpc/grpc-js/package.json').version"
-> 1.8.22
```

### Environment
 - OS name, version and architecture: OS X
 - Node version: 20
 - Node installation method: nvm
 - If applicable, compiler version: N/A
 - Package name and version: `@grpc/grpc-js@latest`

### Additional context
N/A

**Comment by murgatroid99** [comment]
This is fixed now.
