### ISSUE TITLE
Implement authority overrides in the DNS resolver

### ISSUE THREAD

**Issue by atollena** [grpc/grpc-node#2775]
### Is your feature request related to a problem? Please describe.

We have use cases where we would like to use the DNS resolver with a DNS server that is not the system's DNS server.

### Describe the solution you'd like

Implement DNS server authority parsing as described in https://github.com/grpc/grpc/blob/master/doc/naming.md:

> `authority` indicates the DNS server to use, although this is only supported by some implementations. (In C-core, the default DNS resolver does not support this, but the c-ares based resolver supports specifying this in the form "IP:port".).

- [Golang implementation](https://github.com/grpc/grpc-go/blob/c04b085930ce33ee83cc3f92dbe7632031e127a9/internal/resolver/dns/dns_resolver.go#L91-L107)
- [C-core implementation (only when using `GRPC_DNS_RESOLVER=ares`)](https://github.com/grpc/grpc/blob/master/src/core/resolver/dns/c_ares/dns_resolver_ares.cc)
- [Java: not implemented as customizing DNS server is a bit of a moving target](https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/internal/DnsNameResolver.java#L165-L166)

### Describe alternatives you've considered

Do more customisation to the DNS configuration, not involving gRPC directly.

### Additional context

We have workloads in javascript that run browser tests and use public DNS for most resolutions, and a custom DNS server for our internal service discovery system to report results to our internal systems.

**Comment by atollena** [comment]
We are likely willing to provide a patch for this, if that helps.

**Comment by murgatroid99** [comment]
I don't see how you would do that. The only way I can see to make requests to a different DNS server is with `dns.setServers`, but that is a global setting, as opposed to affecting a single request, so it is inappropriate to use in a library.

**Comment by gkampitakis** [comment]
Something like this where you create a new resolver https://github.com/gkampitakis/grpc-node/pull/1?

**Comment by murgatroid99** [comment]
I see. I didn't realize that the Resolver class had its own `setServers` method. That should do it.

**Comment by gkampitakis** [comment]
I have created the pr with the above changes 👍

**Comment by atollena** [comment]
Fixed in https://github.com/grpc/grpc-node/pull/2776.
