### ISSUE TITLE
Message.toObject() does not respect chosen field name.

### ISSUE THREAD

**Issue by majelbstoat** [grpc/grpc-node#279]
Given a definition with a repeated field:

```protobuf
message History {
  repeated string paths = 1;
}
```

and the following code:

```js
const history = new History()
history.setPathsList(['/', '/var'])
console.log(history.toObject())
```

I expect the output to be:

```js
{ paths: ["/", "/var"] }
```

Instead, it is:

```js
{ pathsList: ["/", "/var"] }
```

Failure to honour the specified name creates a lot of work mapping the fields back to what they are supposed to be.

(It's hard to tell if the issue is with grpc-node or google-protobuf.)

**Comment by murgatroid99** [comment]
If that code is using a file generated by google-protobuf, it never touches any gRPC code. You'll want to bring this up with that repo (https://github.com/google/protobuf).
