### ISSUE TITLE
Should I worry about dynamic codegen mismatch with my other modules written in C++

### ISSUE THREAD

**Issue by Mukul-Sharma** [grpc/grpc-node#281]
I have a Proto file which is being used in a NodeJs and C++.

C++ is using protoc compiler whereas NodeJS is using dynamic codegen, My worry is that if the C++ uses a different compiler version than my NodeJS dynamic codegen, could it be an issue for us?

If yes, What do you guys recommend to resolve this? Should I use static codegen? What are the advantages and disadvantages for both If anyone can help me understand, Thanks

**Comment by mukul-bittmax** [comment]
That resolves it for me. Thanks @nicolasnoble
