### ISSUE TITLE
Retry mechanism

### ISSUE THREAD

**Issue by lucavallin** [grpc/grpc-node#284]
Is there a way to retry RPC calls when they fail? I think in the Go package this is available. I couldn't find anything about this in the docs. If not, what approach would you suggest instead?

**Comment by nicolasnoble** [comment]
The retry mechanism hasn't been implemented yet in [native core](https://github.com/grpc/grpc).

**Comment by drobertduke** [comment]
Retries can be implemented using the interceptor framework, see https://github.com/grpc/grpc-node/blob/master/packages/grpc-native-core/src/client_interceptors.js and https://github.com/grpc/proposal/pull/14/files#diff-c1aee0ddae63a3e9a9ba050796cd4b58R325

The Node interceptor framework will be released with 1.11.0

**Comment by dannypaz** [comment]
As an aside, if you are using Node 8 (LTS), you do not have access to use client interceptors (gRPC is only supported up to 1.10)

**Comment by TLadd** [comment]
@drobertduke @nicolasnoble I tried using the retry interceptor from [here](https://github.com/grpc/proposal/pull/14/files#diff-c1aee0ddae63a3e9a9ba050796cd4b58R325), but it didn't work for me as is. After some debugging, it looks like the retry function gets called the first time, and it calls [newCall.start here](https://github.com/grpc/proposal/pull/14/files#diff-c1aee0ddae63a3e9a9ba050796cd4b58R349), but the onReceiveMessage and onReceiveStatus listener functions never get triggered; the message isn't sent again.

[Looking at the way unary requests are made](https://github.com/grpc/grpc-node/blob/master/packages/grpc-native-core/src/client.js#L497), it looks like you have to also call sendMessage and halfClose after calling start. I added these calls to the interceptor so it looks like this:

```javascript
var maxRetries = 3;
var interceptor = function(options, nextCall) {
    var savedMetadata;
    var savedSendMessage;
    var savedReceiveMessage;
    var savedMessageNext;
    var requester = {
        start: function(metadata, listener, next) {
            savedMetadata = metadata;
            var newListener = {
                onReceiveMessage: function(message, next) {
                    savedReceiveMessage = message;
                    savedMessageNext = next;
                },
                onReceiveStatus: function(status, next) {
                    var retries = 0;
                    var retry = function(message, metadata) {
                        retries++;
                        var newCall = nextCall(options);
                        var retryListener = {
                            onReceiveMessage: function(message) {
                                savedReceiveMessage = message;
                            },
                            onReceiveStatus: function(status) {
                                if (status.code !== grpc.status.OK) {
                                    if (retries <= maxRetries) {
                                        retry(message, metadata);
                                    } else {
                                        savedMessageNext(savedReceiveMessage);
                                        next(status);
                                    }
                                } else {
                                    savedMessageNext(savedReceiveMessage);
                                    next({code: grpc.status.OK});
                                }
                            }
                        }
                        newCall.start(metadata, retryListener)
                        newCall.sendMessage(savedSendMessage);  // Added Call
                        newCall.halfClose();  // Added Call
                    };
                    if (status.code !== grpc.status.OK) {
                        retry(savedSendMessage, savedMetadata);
                    } else {
                        savedMessageNext(savedReceiveMessage);
                        next(status);
                    }
                }
            };
            next(metadata, newListener);
        },
        sendMessage: function(message, next) {
            savedSendMessage = message;
            next(message);
        }
    };
    return new InterceptingCall(nextCall(options), requester);
};
```

And it seems to be working as expected now. Any insight into whether this is correct or not?

**Comment by drobertduke** [comment]
You are correct, this was an oversight in my original proposal. There is a working version of the retry interceptor in [client_interceptors_test.js](https://github.com/grpc/grpc-node/blob/master/packages/grpc-native-core/test/client_interceptors_test.js#L465) which includes the calls you've added

@murgatroid99 Should I make a PR to fix up the proposal code?

**Comment by murgatroid99** [comment]
Yes, I think we should keep the proposal correct. And since it is just a correction, it doesn't need the whole review process.

**Comment by Narretz** [comment]
The retry interceptor example can now be found here: https://github.com/grpc/grpc-node/blob/grpc%401.24.x/packages/grpc-native-core/test/client_interceptors_test.js#L460

Was this ever provided officially in grpc-js or as a separate package?

**Comment by murgatroid99** [comment]
That code is not provided in any package. It is just shown as an example of how to use the interceptor API.

**Comment by happy15** [comment]
the example in proposal still miss the calls added as mentioned above:

https://github.com/grpc/proposal/blob/master/L5-node-client-interceptors.md

**Comment by mpx2m** [comment]
@murgatroid99 Is the built-in retry implementation [sepc](https://github.com/grpc/proposal/blob/master/A6-client-retries.md) the drop-in replacement for the code below and the grpc client has the retry policy with default `grpc.enable_retries` set to true and have some numbers of retrying regardless a policy set by the service owner?

Or the `grpc.enable_retries` always adapted to a policy set by the service owner and to obtain the determinative number of retries the interceptor code below is recommended to be added?

> @drobertduke @nicolasnoble I tried using the retry interceptor from [here](https://github.com/grpc/proposal/pull/14/files#diff-c1aee0ddae63a3e9a9ba050796cd4b58R325), but it didn't work for me as is. After some debugging, it looks like the retry function gets called the first time, and it calls [newCall.start here](https://github.com/grpc/proposal/pull/14/files#diff-c1aee0ddae63a3e9a9ba050796cd4b58R349), but the onReceiveMessage and onReceiveStatus listener functions never get triggered; the message isn't sent again.
> 
> [Looking at the way unary requests are made](https://github.com/grpc/grpc-node/blob/master/packages/grpc-native-core/src/client.js#L497), it looks like you have to also call sendMessage and halfClose after calling start. I added these calls to the interceptor so it looks like this:
> 
> ```js
> var maxRetries = 3;
> var interceptor = function(options, nextCall) {
>     var savedMetadata;
>     var savedSendMessage;
>     var savedReceiveMessage;
>     var savedMessageNext;
>     var requester = {
>         start: function(metadata, listener, next) {
>             savedMetadata = metadata;
>             var newListener = {
>                 onReceiveMessage: function(message, next) {
>                     savedReceiveMessage = message;
>                     savedMessageNext = next;
>                 },
>                 onReceiveStatus: function(status, next) {
>                     var retries = 0;
>                     var retry = function(message, metadata) {
>                         retries++;
>                         var newCall = nextCall(options);
>                         var retryListener = {
>                             onReceiveMessage: function(message) {
>                                 savedReceiveMessage = message;
>                             },
>                             onReceiveStatus: function(status) {
>                                 if (status.code !== grpc.status.OK) {
>                                     if (retries <= maxRetries) {
>                                         retry(message, metadata);
>                                     } else {
>                                         savedMessageNext(savedReceiveMessage);
>                                         next(status);
>                                     }
>                                 } else {
>                                     savedMessageNext(savedReceiveMessage);
>                                     next({code: grpc.status.OK});
>                                 }
>                             }
>                         }
>                         newCall.start(metadata, retryListener)
>                         newCall.sendMessage(savedSendMessage);  // Added Call
>                         newCall.halfClose();  // Added Call
>                     };
>                     if (status.code !== grpc.status.OK) {
>                         retry(savedSendMessage, savedMetadata);
>                     } else {
>                         savedMessageNext(savedReceiveMessage);
>                         next(status);
>                     }
>                 }
>             };
>             next(metadata, newListener);
>         },
>         sendMessage: function(message, next) {
>             savedSendMessage = message;
>             next(message);
>         }
>     };
>     return new InterceptingCall(nextCall(options), requester);
> };
> ```
> 
> And it seems to be working as expected now. Any insight into whether this is correct or not?

**Comment by murgatroid99** [comment]
The built in retries are different from the interceptor in some ways:

 - The interceptor will retry any failure, while the built in retries will only retry requests if there is a high degree of confidence that the server has not started processing the request, and only if the status code is in the configured list.
 - The interceptor only handles unary requests and unary responses. The built in retries can handle any kind of streaming.
 - In addition to basic retries, the built in version also supports transparent retries, which are enabled by default and retry a narrower set of errors only once, and hedging, which sends the same request multiple times, and accepts the first successful response it gets.

Retries are configured using the service config, which can be provided by the service owner through the name resolution mechanism, but it can also be provided by the user, in the `grpc.service_config` channel argument. There is no interaction between the built in retries and the interceptor, and I would not recommend configuring both.
