### ISSUE TITLE
Support reverse gRPC for browser

### ISSUE THREAD

**Issue by powellnorma** [grpc/grpc-node#2841]
### Is your feature request related to a problem? Please describe.

It would be really useful (in certain scenarios) if we could define an RPC server for the client in the web browser.
I am writing a web extension, that listens for instructions through a pre-established WebSocket connection. It would be awesome if one could use gRPC for such cases.

### Describe the solution you'd like

The transport-logic would need to get abstracted, such that one can (e.g.) "bind" to an already existing WebSocket object.

If we are at it, it would be great if the user could define his own custom transport implementation, so that e.g. bi-directional streams from https://github.com/improbable-eng/grpc-web could also be used as underlying transport.

### Describe alternatives you've considered

I have looked around but the closest I have found was https://github.com/bigstepinc/jsonrpc-bidirectional - However I'd like to make use of protobuf stub generation.

**Comment by murgatroid99** [comment]
Practically speaking, it wouldn't make sense to implement a browser gRPC server in this repository. This repository is focused on the Node.js gRPC implementation, and I think it is unlikely that much of the server implementation here could be adapted to the browser. A lot of it depends on Node's built in HTTP/2 server implementation, which in turn uses nghttp2, so it would not be easy to polyfill it.

[The grpc-web repository](https://github.com/grpc/grpc-web) is focused on the gRPC implementation in the browser, but this would be pretty unrelated to any of their existing or planned features.

**Comment by powellnorma** [comment]
Thank you for the explanation, even if unfortunate. I found a way that works well for me - I use ts-proto to convert the .proto Messages, and then use a custom .proto parser (written in python) that generates RPC Interfaces. For the communication, I use socket.io - which does stuff like relating the response (acknowledgement) back to the query, and some other stuff. Every event is interpreted as method invocation. So no gRPC anymore, but still typed RPC stub generation
