### ISSUE TITLE
Can't use refer to status enum in typescript

### ISSUE THREAD

**Issue by majelbstoat** [grpc/grpc-node#289]
It does not currently appear to be possible to refer to status codes in Typescript. For example: 

```
import {status} from 'grpc' // Not a typescript compile error.

console.log(status.NOT_FOUND)
```

Expected result: `5` is printed.

Actual result:

```
Error: Cannot read property 'NOT_FOUND' of undefined.
```

Although Typescript docs seem to imply that "enums are real objects that exist at runtime", it does not appear to be the case here. This could perhaps be solved by updating `index.d.ts` to export a `const enum status` instead of a regular `enum status`. With that definition, usage sites would be rewritten to the underlying integer.

Typescript: 2.8.1
GRPC Node: 1.10.1

**Comment by murgatroid99** [comment]
The `grpc` package is deprecated, so this probably won't change. But the `@grpc/grpc-js` package, its replacement, has this implemented properly.
