### ISSUE TITLE
Prebuilt binaries for s390x

### ISSUE THREAD

**Issue by mastersingh24** [grpc/grpc-node#296]
Are binaries for s390x built?   If not, if we were willing to do so, how would we go about getting integrated into the build cycle?

**Comment by nicolasnoble** [comment]
Binaries for s390x aren't built, no. The only acceptable method for us to provide pre-compiled packages would be through cross compilation, the same way the [arm cross compilation scripts](https://github.com/grpc/grpc-node/blob/master/packages/grpc-native-core/tools/run_tests/artifacts/build_artifact_node_arm.sh) work. I guess [this s390x cross compiler](https://packages.debian.org/stretch/g%2B%2B-6-s390x-linux-gnu) might work.

Note that we have absolutely no way of testing that architecture whatsoever, and packages provided would be with no guarantee, and very restricted support.

**Comment by nicolasnoble** [comment]
We can discuss, yes :-) In the immediate future, I'd be happy to take a PR from you to add s390x cross compilation support if this is something that is possible, and make this architecture a "tier3" support - aka, we acknowledge support from the community for this.

In order to basically say s390x is "tier2", we would need to have access to some s390x machines somehow in order to say we can react to bug report ourselves, and not rely on the community to fix these.

For "tier1", this would mean continuous integration testing. As of right now we're using [Google's modification of Jenkins](https://www.cloudbees.com/sites/default/files/2016-jenkins-world-jenkins_inside_google.pdf) for all our gRPC build and testing. In the near future, this platform will accept external hardware connections to support nodes that are otherwise not supported internally at Google.


So right now, I can see a "tier3" support very quickly, if you are willing to provide the expertise. For tier2 or even 1, I think we should have a conf call or something to see what we could do exactly here.

**Comment by mastersingh24** [comment]
Sounds good.  We'll take a look at the cross compilation option as an initial step.

**Comment by ptippett** [comment]
@mastersingh24 I'm starting to chase this down.

**Comment by ptippett** [comment]
@nicolasnoble I've just started to work on this at IBM to find some capacity and get it set up.  I'm told google is building golang binaries on s390x, so maybe talking to them to see if they have capacity would be another option?

**Comment by nicolasnoble** [comment]
That's a good question. I can try to track down the team doing this to see how they do it exactly.

**Comment by nicolasnoble** [comment]
Apparently, the s390x resources for building and testing golang natively are provided by another IBM employee, @mundaym.

**Comment by ptippett** [comment]
OK thanks..I'll talk to him.

**Comment by vmorris** [comment]
Hi @nicolasnoble  -- I'm chasing this issue down and have an s390x build machine ready for use.
I attempted to get a test build done, but my experience in building grpc is severely limited now.

**Comment by vmorris** [comment]
@nicolasnoble can we get a conference call scheduled for this? We have the build system ready and I would like to know what the next steps are to get "tier 1" support in place.

As for "tier 2", I'm happy to hand over the credentials to you, if you would please contact me via email: vmorris@us.ibm.com

Thanks.

**Comment by nicolasnoble** [comment]
I'll send you an e-mail directly to schedule a conf call and everything.

**Comment by vmorris** [comment]
Hi @nicolasnoble -- I did receive your email and it looked like you were setting up a meeting, but I never got any follow up. Can you tell me what's going on there? Thanks.

**Comment by vmorris** [comment]
Hi @nicolasnoble -- Can you report any status on how the s390x system is working out? Have you had any difficulties or successes you can share?

**Comment by vmorris** [comment]
@nicolasnoble Any update you can share regarding this issue?

**Comment by sanjeevgour** [comment]
@mastersingh24 @vmorris -- Hello Guys, I am also trying to make the grpc server work on IBM zLinux (s390x) system, I haven't made a lot progress yet. While trying to compile grpc, it ended up asking about protobuf 3.5.0+ for which I didn't find readily available binaries supported for s390x, so I halted my work there. Looking around for help, I came across this post. 
Were you guys successful in compiling grpc on s390x. Any pointers in this direction would be helpful.

Thanks.

**Comment by vmorris** [comment]
You'll want to talk to @nicolasnoble I think... last I checked we left it in his hands.

**Comment by sanjeevgour** [comment]
@vmorris - Sure, thanks.
@nicolasnoble - Do you have anything latest on that can help us make progress?

**Comment by ptippett** [comment]
Hi Guys.

@nicolasnoble  Someone asked me about this today.  Did this get dropped?  Can we get it moving again?

**Comment by shahidhs-ibm** [comment]
Not sure if this is right place but as per Protobuf issue [comment](https://github.com/protocolbuffers/protobuf/issues/6625#issuecomment-570045871), it looks like grpc and Protobuf share a common CI. Also as this issue talks about building and publishing binaries on s390x, I am adding my comment for discussion here.

As we have completed the PR#[1230](https://github.com/grpc/grpc-node/pull/1230), I am curious to know if similar shell script changes would be required for Protobuf to build correct s390x binaries? It seems like protobuf [PR#6558](https://github.com/protocolbuffers/protobuf/pull/6558) has no effects in the Kokoro CI grpc project which builds binaries for Protobuf.

Any help or pointers is highly appreciated.

**Comment by murgatroid99** [comment]
I suggest bringing that up in the Protobuf repository. We share CI infrastructure but they still have their own CI scripts.

**Comment by shahidhs-ibm** [comment]
@murgatroid99 Thank you for reply. We'll check with Protobuf for more insight on CI.

**Comment by shahidhs-ibm** [comment]
The latest grpc version 1.24.3 got released today have s390x binary support. Thank you @murgatroid99 for excellent support :)
This issue can be closed.

**Comment by Erick-shi** [comment]
> The latest grpc version 1.24.3 got released today have s390x binary support. Thank you @murgatroid99 for excellent support :)
> This issue can be closed.

could you please send the protoc binary to me ?

**Comment by shahidhs-ibm** [comment]
> could you please send the protoc binary to me ?

Here we are talking about grpc binary which can be installed using `npm i grpc` command. The issue of wrong protoc binary getting published for s390x still exists and we are in discussion with community for same.
