### ISSUE TITLE
Suboptimal implementation, am I missing something?

### ISSUE THREAD

**Issue by pfreixes** [grpc/grpc-node#303]
I was just digging a bit on how the asynchronously was being reached within the `grpc-node` library. Having an open discussion of how the Python Asyncio might be implemented [1], for me sounded pretty weird that nobody took care of the concidences. Taking into account that both worlds are based on the same pattern, the reactor one.

So I've decided to take a look at the current implementation and I realized that instead of having the proper glue to register the file descriptors that might trigger network events from Grcp core to Node.js/libuv the whole implementation is based on the following pattern:

1) Make usage of the prepare handler [2] statement provided by libuv, that is executed at each loop iteration.
2) If there is any completion queue pending to be polled we make usage of 1.

Worth mentioning that - correct me if I'm wrong - completion queues are used by whatever, perhaps they are used when we register a new handler that might be called at whenever moment. This might be seen as the typical server behaviour of a Grpc service.

So, what is wrong?

The main disadvantage of this implementation can be summarized as, when there is at least one completion queue waiting for events - remember that in case of a  Grpc server it will always happen- the Libuv timeout used will be 0 while the timeout used to fetch the event by Grpc will be `INT64_MIN`.  This scenario is perfect to end up having a high CPU usage, even for that scenarios that there are NO Grpc messages to be consumed.

Am I missing something?

[1] https://github.com/grpc/grpc/issues/14876
[2] http://docs.libuv.org/en/v1.x/prepare.html

**Comment by murgatroid99** [comment]
> the Libuv timeout used will be 0

The documentation you linked says that the prepare handle runs before polling for I/O, but it does not say that it affects the timeout used when polling for I/O. And our observations are consistent with the event loop polling with a longer timeout when the prepare handle is active.

**Comment by nicolasnoble** [comment]
Also, quoted from http://docs.libuv.org/en/v1.x/idle.html,

> Idle handles will run the given callback once per loop iteration, right before the uv_prepare_t handles.

> Note The notable difference with prepare handles is that when there are active idle handles, the loop will perform a zero timeout poll instead of blocking for i/o.

Did this answer your concerns ?

**Comment by pfreixes** [comment]
Yes, right I read this code in the wrong way [1]. Anyway, I'm still thinking that the current implementation is suboptimal.

Why? Because having the Libuv timeout will mean that the handler that lives in the Node.js side will be delayed for a while - the total time delayed might come either for the timeout used by libuv or the time needed to receive a networking event in the Node.js side. So, we will have never a real-time reaction because of a Grpc event.

What am I missing?

[1] https://github.com/libuv/libuv/blob/v1.x/src/unix/core.c#L320

**Comment by murgatroid99** [comment]
I suspect that what you are missing is that gRPC hooks into the libuv event loop at a low level, and uses it to wait for network events and handle gRPC timers. This means that any network event or timeout that gRPC cares about will wake up the libuv event loop and trigger the prepare handle within a very short time.

**Comment by pfreixes** [comment]
Hi @murgatroid99 thanks for your response, abd patience. Maybe my rationale is wrong and I might be missing something, correct me if Im wrong.

Node.js and Grpc with the current design are completely decoupled regarding how IO is handled,  the network events related to the TCP conections that belong to the Grpc environment will never wake up the poll that is done by libuv. Is not that right?

**Comment by murgatroid99** [comment]
No, that's the opposite of what I'm saying. Under Node, gRPC uses the libuv event loop to handle IO, so when Node polls for IO events that includes IO events that gRPC cares about.

**Comment by pfreixes** [comment]
Um, so they are using the same loop instance? Do you have a link to the source code that allows this cooperation? I didn't manage to find it.

**Comment by murgatroid99** [comment]
The libuv specific network code is in this file: https://github.com/grpc/grpc/blob/master/src/core/lib/iomgr/tcp_uv.cc

**Comment by pfreixes** [comment]
You are right, now I can see that Grpc with libuv always uses the `uv_default_loop()` method to retrieve an initialized loop and never calls directly the `uv_loop_init`. So, the same loop instance is shared across Node.js and Grpc world.

Thanks for the clarification.
