### ISSUE TITLE
Add a sanity test to check if packages contains all the files they should.

### ISSUE THREAD

**Issue by nicolasnoble** [grpc/grpc-node#305]

**Comment by nicolasnoble** [comment]
The issue was more with the native module where we can't necessarily tell if we managed to capture all of the necessary C++ files during packing, since this list is elsewhere. But I might just have thought of a way actually...

**Comment by murgatroid99** [comment]
Now that we are changing the native package very little we probably don't need this for that package anymore, but in @2021 I implemented a very simple version of this for grpc-js, grpc-js-xds, and proto-loader.
