### ISSUE TITLE
How to use oneof's with @grpc/proto-loader?

### ISSUE THREAD

**Issue by respinha-ribeiro** [grpc/grpc-node#318]
I am using @grpc/proto-loader to load all protobuf definitions while preventing any unused field to default to null. However, since I started doing so I'm having issues with oneof values. A good example is [`google.protobuf.Struct`](https://github.com/google/protobuf/blob/master/src/google/protobuf/struct.proto), where `Value` has a oneof named `kind`. In this case, if I provide the following input structure while using only `grpc.load()`:
```
{
   "fields":{
      "value":{
         "struct_value":{
            "fields":{
               "some_nested_value":{
                  "number_value":10
               }
            }
         }
      }
   }
}
```

I get the following message on server-side: 
```
{
   "fields":{
      "value":{
         "kind":"struct_value",
         "null_value":"NULL_VALUE",
         "number_value":0,
         "string_value":"",
         "bool_value":false,
         "struct_value":{
            "fields":{
               "some_nested_value":{
                  "kind":"number_value",
                  "null_value":"NULL_VALUE",
                  "number_value":10,
                  "string_value":"",
                  "bool_value":false,
                  "struct_value":null,
                  "list_value":null
               }
            }
         },
         "list_value":null
      }
   }
}
```

When using @grpc/proto-loader with the exact same input I get on server-side: 
```
{
   "fields":{
      "value":{
      }
   }
}
```

How I am applying package definitions: 
```js
const packageDefinition = protoLoader.loadSync(
   defaults: false,
   arrays: false,
   keepCase: 
});
protoDef = grpc.loadPackageDefinition(packageDefinition);
```

**Comment by nicolasnoble** [comment]
I'm not sure I'm able to properly see what's wrong here. Do you think you could provide a fully working reproduction case ?

**Comment by respinha-ribeiro** [comment]
The problem does not occur specifically when using oneof's, I've opened another issue with the details on #326

**Comment by nicolasnoble** [comment]
Per #326, closing this one too.
