### ISSUE TITLE
@grpc/proto-loader: issue when importing proto files if file directory is `google/protobuf/<file>`

### ISSUE THREAD

**Issue by respinha-ribeiro** [grpc/grpc-node#326]
I use a set of protobuf interfaces defined by Google such as [google.protobuf.Struct](https://github.com/google/protobuf/blob/master/src/google/protobuf/struct.proto). I have these files under the directory `google/protobuf/`. 
Since I moved to @grpc/proto-loader I started having issues using message structures from these files in other protobuf interfaces. The content from fields using messages from these files is always empty. After several tests I discovered that this does not happen if the path is not `google/protobuf`. If I change it to `google_1/protobuf` or `google/protobuf_1` it works!
I was not experiencing this issue when loading protos the "old way" - `grpc.load({ protoRoot, filePath})`. Could this be some reserved keyword conflict while loading the files?

My grpc loader options:
```js
const packageDef = protoLoader.loadSync(filepath, {
     arrays:false,
     defaults: false,
     keepCase: true,
     includeDirs: [protoRoot]
});
```

The protos are defined [here](https://github.com/restorecommerce/protos).
`grpc` version: 1.11.3
`@grpc/proto-loader` version:  0.1.0

**Comment by nicolasnoble** [comment]
Protobufjs 6 introduced built-in support for the Google well-known protos. Maybe this is the problem?

**Comment by respinha-ribeiro** [comment]
@nicolasnoble but previously I was using the latest gRPC version, which supported protobuf.js 6, right?

**Comment by respinha-ribeiro** [comment]
Oh, from what I see in [`index.js`](https://github.com/grpc/grpc-node/blob/master/packages/grpc-native-core/index.js#L123), `load()` uses protobuf.js 5 by default, so only version 6 is actually only used on `@grpc/proto-loader`.

**Comment by respinha-ribeiro** [comment]
Tested locally with plain `protobuf.js` and same problem occurs. I will post an issue there.

**Comment by nicolasnoble** [comment]
You are correct. The only reason `@grpc/proto-loader` exists is for exactly the kind of situation you see yourself in right now. If you've determined that the issue is in fact in protobufjs, and opening an issue there, I will then close these two here.

For cross-reference, you have opened issue https://github.com/dcodeIO/protobuf.js/issues/1042.
