### ISSUE TITLE
update lodash version

### ISSUE THREAD

**Issue by wyardley** [grpc/grpc-node#330]
Can you bump the required lodash version? NSP is warning about vendored dependencies on this and google-gax for https://nodesecurity.io/advisories/577 e.g.,
`@google-cloud/pubsub@0.18.0 > google-gax@0.16.1 > grpc@1.8.4 > lodash@4.17.4`

**Comment by nicolasnoble** [comment]
That's not a bad one to change, yes. Feel free to submit a PR to update, and we'll accept it immediately.

**Comment by zixia** [comment]
I have one question: as we are using the TypeScript and ES6, what's the reason that we still need to use `lodash` to do those jobs?

**Comment by zixia** [comment]
@nicolasnoble You are absolutely right. Sorry for my misunderstanding and thanks for correcting me.
