### ISSUE TITLE
Received RST_STREAM with error code 7

### ISSUE THREAD

**Issue by justin0218** [grpc/grpc-node#346]
{ Error: 14 UNAVAILABLE: Received RST_STREAM with error code 7
    at new createStatusError (/Users/justin/Desktop/work/abctime-socket-grpc/node_modules/grpc/src/client.js:64:15)
    at /Users/justin/Desktop/work/abctime-socket-grpc/node_modules/grpc/src/client.js:573:15
  code: 14,
  metadata: Metadata { _internal_repr: {} },
  details: 'Received RST_STREAM with error code 7' }

why concurrent greater 128 error(为什么并发超过128次就出现这个错误)?

**Comment by nicolasnoble** [comment]
This is working as intended.

Something on your network route decided to close your network connection, and your grpc calls got canceled. The UNAVAILABLE error usually means that the connection got interrupted. You need to listen to the error event, and in the UNAVAILABLE case, retry your call.
