### ISSUE TITLE
Server middleware/interceptors?

### ISSUE THREAD

**Issue by theogravity** [grpc/grpc-node#350]
I noticed that the client now has support for interceptors - is there anything like that for the server side?

**Comment by murgatroid99** [comment]
We do not have that on the server side. You are free to submit a design proposal for that functionality to https://github.com/grpc/proposal, as is anyone else.

**Comment by theogravity** [comment]
Update - found a project that implements a custom interceptor via proxying

https://github.com/echo-health/node-grpc-interceptors
