### ISSUE TITLE
The protobuf.Timestamp should turn to Date when call toObject ?

### ISSUE THREAD

**Issue by lawrsp** [grpc/grpc-node#357]
### Is your feature request related to a problem? Please describe.
I'm always frustrated when I use node as a interface gateway,  it call the backend with grpc, and  reply to the client with json,
call message.toObject() always get the { seconds: XXX, nanos: XXXX} object with timestamp.
A standard json timestamp should be like "2017-05-04 T00:20:30Z", which is a javascript Date Object turned to be.
 
### Describe the solution you'd like
we should change the protobuf.Timestamp.toObject() function to some like the toDate() function

**Comment by murgatroid99** [comment]
If you are using `grpc.load` or otherwise explicitly using the `protobufjs` package, you should file this issue with https://github.com/dcodeIO/protobuf.js. If you are using the `google-protobuf` package, you should file this issue with https://github.com/google/protobuf.
