### ISSUE TITLE
protobufjs security issue

### ISSUE THREAD

**Issue by jschirrmacher** [grpc/grpc-node#360]
### Problem description
`npm audit` reports a possible vulnerability to a denial of service attack.
See https://nodesecurity.io/advisories/605

Is there any objection to require at least protobufjs 6.8.6?

**Comment by nicolasnoble** [comment]
First, which package exactly are you talking about.

Also, yes, requiring protobufjs 6.8.6 would be an API breaking change for the grpc package. And https://nodesecurity.io/advisories/605 is outdated, and isn't showing the fact that 5.0.3 is fixed also.

Closing because duplicate of #277.
