### ISSUE TITLE
grpc 1.12.1 fails to install with `npm ci`

### ISSUE THREAD

**Issue by mdouglass** [grpc/grpc-node#365]
### Problem description
grpc 1.12.1 fails to install with `npm ci`

### Reproduction steps
I've attached two empty projects that differ only in their dependency on grpc -- one uses 1.11.3, the other 1.12.1.
[repro-grpc.zip](https://github.com/grpc/grpc-node/files/2033207/repro-grpc.zip)

If you run `npm ci` with repro-grpc-1.11.3 it succeeds.
If you run `npm ci` with repro-grpc-1.12.1 it fails with `sh: ./node_modules/.bin/node-pre-gyp: No such file or directory`
 
### Environment
 - macOS 10.13.4
 - node.js v10.1.0 installed via brew
 - npm v6.0.1

#### Successful install
```
bigbird:repro-grpc-1.11.3 mdouglass$ npm ci
npm WARN prepare removing existing node_modules/ before installation

> grpc@1.11.3 install /Users/mdouglass/kixeye/repros/repro-grpc-1.11.3/node_modules/grpc
> ./node_modules/.bin/node-pre-gyp install --fallback-to-build --library=static_library

[grpc] Success: "/Users/mdouglass/kixeye/repros/repro-grpc-1.11.3/node_modules/grpc/src/node/extension_binary/node-v64-darwin-x64-unknown/grpc_node.node" is installed via remote
added 36 packages in 4.435s
bigbird:repro-grpc-1.11.3 mdouglass$ 
```

#### Failed install:
```
bigbird:repro-grpc-1.12.1 mdouglass$ npm ci
npm WARN prepare removing existing node_modules/ before installation

> grpc@1.12.1 install /Users/mdouglass/kixeye/repros/repro-grpc-1.12.1/node_modules/grpc
> ./node_modules/.bin/node-pre-gyp install --fallback-to-build --library=static_library

sh: ./node_modules/.bin/node-pre-gyp: No such file or directory
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! grpc@1.12.1 install: `./node_modules/.bin/node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the grpc@1.12.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     [/Users/mdouglass/.npm/_logs/2018-05-23T23_27_00_544Z-debug.log]
````

npm debug log from that run:
[2018-05-23T23_27_00_544Z-debug.log](https://github.com/grpc/grpc-node/files/2033209/2018-05-23T23_27_00_544Z-debug.log)

**Comment by ellismg** [comment]
Likely related, when I install this version via `yarn install` I get this warning:

```
warning "grpc@1.12.1" is missing a bundled dependency "node-pre-gyp". This should be reported to the package maintainer.
```

**Comment by nicolasnoble** [comment]
For the last part, yarn can't be used to install grpc.

**Comment by nicolasnoble** [comment]
Right, and 1.12.1 doesn't contain node-pre-gyp as a bundled dependency, which causes that.

**Comment by nicolasnoble** [comment]
Published 1.12.2 to fix this. Sorry about the trouble.

**Comment by nicolasnoble** [comment]
I just confirmed `npm ci` works again with grpc@1.12.2

**Comment by mdouglass** [comment]
Thanks for the quick turnaround!
