### ISSUE TITLE
heap out of memory

### ISSUE THREAD

**Issue by zyf0330** [grpc/grpc-node#368]
### Problem description
I use pm2 to run node app in docker on CentOS. VSZ keeps increasing day and day. And this morning, one of node instance restarts. PM2 show error.
This app has both grpc client and server.
I doubt that there is a memory leak problem, not ensure.

### Reproduction steps
I just don't know what should I give.

### Environment
 - OS name, version and architecture: CentOS Linux release 7.4.1708
 - Node version: 8.9.3
 - Node installation method: tar.gz package
 - If applicable, compiler version [e.g. clang 3.8.0-2ubuntu4]
 - Package name and version
grpc v1.9.1

### Additional context
pm2 logs 
```
[101:0x560f0f0d2360] 765331583 ms: Mark-sweep 1400.6 (1515.1) -> 1400.6 (1516.1) MB, 2186.4 / 0.0 ms  allocation failure GC in old 
space requested
[101:0x560f0f0d2360] 765333597 ms: Mark-sweep 1400.6 (1516.1) -> 1400.5 (1502.1) MB, 2014.2 / 0.0 ms  last resort GC in old space r
equested
[101:0x560f0f0d2360] 765335597 ms: Mark-sweep 1400.5 (1502.1) -> 1400.5 (1495.1) MB, 1998.7 / 0.0 ms  last resort GC in old space r
equested


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x39640c6a5ee1 <JSObject>
    1: fn(aka writeStringBuffer) [/app/node_modules/tinder-edge-nodejs/node_modules/protobufjs/src/writer_buffer.js:~57] [pc=0x1077
a4a41a8f](this=0x1210931668d1 <Op map = 0x9eaaf81c039>,val=0x121093162141 <Very long string[402744]>,buf=0x121093167bb1 <Uint8Array
 map = 0x37c9c3bb4c91>,pos=6)
    3: finish [/app/node_modules/tinder-edge-nodejs/node_modules/protobufjs/src/writer.js:449] [bytecode=0...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
```

**Comment by murgatroid99** [comment]
Can you provide some code that triggers this problem?

**Comment by nicolasnoble** [comment]
@zyf0330: there's nothing for us in your report to investigate anything. We can't help you without any better context, which is why we request reproduction cases now.

See #369 as an example of what we want: a small piece of code that demonstrates the problem. We need you to share with us a small application we can run ourselves that will show us the problem.

**Comment by zyf0330** [comment]
I cannot give you whole code. I have watched memory leak and will analyze heap. After finding something, will report.

**Comment by zyf0330** [comment]
find nothing
