### ISSUE TITLE
roots.pem error

### ISSUE THREAD

**Issue by ThibautJ** [grpc/grpc-node#379]
### Problem description
I am using Google Cloud Datastore.
When trying to start my application, this error is printed:
`  console.error node_modules/grpc/src/common.js:63
    Auth error:Error: error:0906D066:PEM routines:PEM_read_bio:bad end line
`
It seems there is a problem with the certificates...

### Reproduction steps
I'm using this dependency in my Node.js app : `"@google-cloud/datastore": "^1.4.0"`.
It installed grpc and generated this error.

### Environment
 - OS name, version and architecture: [Linux Ubuntu]
 - Node version [6.11.1]
 - Node installation method [npm]
 - Package name and version [gRPC@1.12.0]

**Comment by nicolasnoble** [comment]
We can't really see what's going on here. This isn't something we're seeing on our side. Could you give a quick datastore example that would trigger this on your Ubuntu machine ? Also, which version of Ubuntu is it so we can try and reproduce exactly using a Dockerfile or something. A dump of your /etc/issue file would be enough.

**Comment by ThibautJ** [comment]
Thank you for the quick answer ! But I just found the problem.

It was just my google private key which was not correctly defined locally ! 


Sorry for the disagrement 

![bitmoji](https://render.bitstrips.com/v2/cpanel/27c34645-4e03-42a5-bb21-c48c76fcacfe-7c472774-08e7-4d52-a361-d5edc9fe658b-v1.png?transparent=1&palette=1&width=246)
