### ISSUE TITLE
Ask for a build guide for node module

### ISSUE THREAD

**Issue by Sunnykaby** [grpc/grpc-node#380]
I want to disable the alpn for my project, And I just change the code in the grpc module.
change the "grpc_alpn" to false. 
But It doesn't work.
So I want to know how can I change the source code, and rebuild the module for my project.

**Comment by nicolasnoble** [comment]
I believe this answers the question.

**Comment by Sunnykaby** [comment]
our project use a nginx with old version, and it not support alpn. And I try to close the alpn when the npm install the grpc. But it not work for me. The server also return a null for the alpn check. and the code of grpc (c++):
`const tsi_peer_property* p =

tsi_peer_get_property_by_name(peer, TSI_SSL_ALPN_SELECTED_PROTOCOL);

if (p == nullptr) {

return GRPC_ERROR_CREATE_FROM_STATIC_STRING(

"Cannot check peer: missing selected ALPN property.");

}`
in the security_connector.cc file. 
The p is null, and the error occur.

**Comment by Sunnykaby** [comment]
@murgatroid99
