### ISSUE TITLE
Can't install firebase-admin on ubuntu 16.04

### ISSUE THREAD

**Issue by cmr624** [grpc/grpc-node#383]
### Problem description

Hi, I receive this error message when I try to npm install firebase-admin. I cleaned out the error message bc of personal info with "{PATH}"

> grpc@1.12.2 install {PATH}/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp ERR! UNCAUGHT EXCEPTION 
node-pre-gyp ERR! stack TypeError: this is not a typed array.
node-pre-gyp ERR! stack     at Function.from (native)
node-pre-gyp ERR! stack     at Object.<anonymous> (/{PATH}/node_modules/grpc/node_modules/tar/lib/parse.js:33:27)
node-pre-gyp ERR! stack     at Module._compile (module.js:410:26)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (module.js:417:10)
node-pre-gyp ERR! stack     at Module.load (module.js:344:32)
node-pre-gyp ERR! stack     at Function.Module._load (module.js:301:12)
node-pre-gyp ERR! stack     at Module.require (module.js:354:17)
node-pre-gyp ERR! stack     at require (internal/module.js:12:17)
node-pre-gyp ERR! stack     at Object.<anonymous> ({PATH}/node_modules/grpc/node_modules/tar/lib/list.js:10:16)
node-pre-gyp ERR! stack     at Module._compile (module.js:410:26)
node-pre-gyp ERR! System Linux 4.13.0-43-generic
node-pre-gyp ERR! command "/usr/bin/nodejs" "{PATH}/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd {PATH}/node_modules/grpc
node-pre-gyp ERR! node -v v4.2.6
node-pre-gyp ERR! node-pre-gyp -v v0.10.0
node-pre-gyp ERR! This is a bug in `node-pre-gyp`.
node-pre-gyp ERR! Try to update node-pre-gyp and file an issue if it does not help:
node-pre-gyp ERR!     <https://github.com/mapbox/node-pre-gyp/issues>
{foldername}@0.0.0 {PATH}
└── (empty)

npm ERR! Linux 4.13.0-43-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "firebase-admin"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! grpc@1.12.2 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 7
npm ERR! 
npm ERR! Failed at the grpc@1.12.2 install script 'node-pre-gyp install --fallback-to-build --library=static_library'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the grpc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build --library=static_library
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs grpc
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls grpc
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!    {PATH}/npm-debug.log
npm ERR! code 1

### Reproduction steps
Two commands
npm install --save firebase-admin
sudo npm install -g firebase-admin
any combination of the above two, with different flags etc.

### Environment
 - OS name, version and architecture: Linux, Ubuntu 16.04 LTS
 - Node version: v4.2.6
 - Node installation method: npm

### Additional context
Junior / Intermediate developer (still learning!). Very new to filing github issues. Sorry if this has been posted before! Please be patient :)

**Comment by cmr624** [comment]
As my friendly roommate developer pointed out, I did not include the "npm-debug.log" because I couldn't find it!

**Comment by murgatroid99** [comment]
This problem appears to be related to your Node version. Node 4 is old and is no longer maintained, and 4.2.6 is a relatively old version of Node 4. The installation appears to work with the newest version of Node 4, which is 4.9.1, but I would recommend upgrading to a much newer version like Node 10, or at least Node 8, which is the newest LTS version.

**Comment by cmr624** [comment]
Thank you sir! Updated and worked. :)
