### ISSUE TITLE
Compatibility with node-pre-gyp v0.10.0?

### ISSUE THREAD

**Issue by gyang274** [grpc/grpc-node#388]
Tried to install grpc-tools, and experienced error below:

```
 $ sudo npm install -g grpc-tools
/usr/local/bin/grpc_tools_node_protoc_plugin -> /usr/local/lib/node_modules/grpc-tools/bin/protoc_plugin.js
/usr/local/bin/grpc_tools_node_protoc -> /usr/local/lib/node_modules/grpc-tools/bin/protoc.js

> grpc-tools@1.6.6 install /usr/local/lib/node_modules/grpc-tools
> node-pre-gyp install

node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: EPERM: operation not permitted, utime '/usr/local/lib/node_modules/grpc-tools/bin'
node-pre-gyp ERR! System Linux 4.4.0-127-generic
node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/grpc-tools/node_modules/.bin/node-pre-gyp" "install"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/grpc-tools
node-pre-gyp ERR! node -v v8.0.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.38
node-pre-gyp ERR! not ok
EPERM: operation not permitted, utime '/usr/local/lib/node_modules/grpc-tools/bin'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc-tools@1.6.6 install: `node-pre-gyp install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the grpc-tools@1.6.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Steps tried to fix but failed:

```
$ sudo npm install -g node-pre-gyp
```
Above installation complete ok, but install node-pre-gyp v0.10.0.

And, re-run `sudo npm install -g grpc-tools` gives the same error message.

OS: Ubuntu 16.04, Node v8.0.0, NPM v6.5.1.

Don't know node installation method, node installed at `/usr/local/bin/node`.

Thank you.

**Comment by nicolasnoble** [comment]
This isn't a grpc issue, nor a node-pre-gyp issue. All it really means is that you don't have permissions to install any global package at all. What this says is that you shouldn't be able to install, say, npm itself. Try `npm install -g npm` to get you convinced of what I am saying. Also the fact you don't know how you got your node runtime, and its location (/usr/local/bin) tells me you've either built nodejs from source, or that someone else did it for you.

Either run npm as root, or install node in your local account using [nvm](https://github.com/creationix/nvm).

**Comment by murgatroid99** [comment]
If anything, I think it actually is a node-pre-gyp problem. That is where the error message is coming from, and it is an unusual installation step that grpc has and most packages don't. But it's almost definitely not grpc-specific. The grpc module uses node-pre-gyp in a very standard way.
