### ISSUE TITLE
Enums changed to uppercase in generated files

### ISSUE THREAD

**Issue by TLadd** [grpc/grpc-node#404]
### Problem description
Lowercase enums defined in proto files are capitalized in generated files when using grpc_tools_node_protoc

### Reproduction steps
When using grpc_tools_node_protoc, lower-case enums become uppercase. I believe the casing should be preserved? I created an example repo here: https://github.com/TLadd/example-grpc-enum.

In the [proto file](https://github.com/TLadd/example-grpc-enum/blob/master/helloworld.proto#L32), the enum is specified as
```
enum Value {
    hello = 0;
    hi = 1;
  }
```

After running 
```
grpc_tools_node_protoc --js_out=import_style=commonjs,binary:./ --grpc_out=./ --plugin=protoc-gen-grpc=`which grpc_tools_node_protoc_plugin` helloworld.proto
```

the [generated output](https://github.com/TLadd/example-grpc-enum/blob/master/helloworld_pb.js#L160) is capitalized

```
/**
 * @enum {number}
 */
proto.helloworld.HelloRequest.Value = {
  HELLO: 0,
  HI: 1
};
```

### Environment
 - Mac OS X
 - Node v9.8.0
 - NVM
 - grpc-tools@1.6.6

**Comment by nicolasnoble** [comment]
I know this may be confusing given the package's name, but this isn't something we actually have any control over. We are merely shipping a binary package containing protoc from protobuf with a few additional things, and this output isn't from what we add. So this issue actually belongs in the protobuf repository, here: https://github.com/google/protobuf

Sorry for the confusion.
