### ISSUE TITLE
grpc-js support for passphrase-protected private keys on mutual TLS connections

### ISSUE THREAD

**Issue by marzolfb** [grpc/grpc-node#413]
The [`createSSL` method](https://github.com/grpc/grpc-node/blob/f952778ed75b3a000adc6abc787d266af88c9a82/packages/grpc-js-core/src/channel-credentials.ts#L53) assumes that the private key you are providing in a mutual TLS scenario is not protected with a passphrase. 

If you are using a private key protected with a passphrase, you will get an error like this: 
```
Error: error:0906A068:PEM routines:PEM_do_header:bad password read
```

It is interesting to note that while it is possible to address this issue in `grpc-js-core` simply by passing an additional `passphrase` option on the [`createSecureContext` call](https://github.com/grpc/grpc-node/blob/f952778ed75b3a000adc6abc787d266af88c9a82/packages/grpc-js-core/src/channel-credentials.ts#L67), it does not appear to be possible to address this in `grpc-native-core` based on the current lack of support in the underlying library based on [this issue](https://github.com/grpc/grpc/issues/14216).

**Comment by murgatroid99** [comment]
The `grpc-js` library now has the function `credentials.createFromSecureContext`, which can accept any output of `createSecureContext`. The `grpc` library is deprecated, so we have no plans to update it with a compatible change.
