### ISSUE TITLE
Poor performance

### ISSUE THREAD

**Issue by sathibault** [grpc/grpc-node#417]
### Problem description
I've porting a C++ gRPC client to grpc-node and am experiencing high CPU usage and overall bad performance.  It seems like calling `grpc_completion_queue_next(queue,gpr_inf_past(GPR_CLOCK_MONOTONIC),NULL);` from a UV prepare handle is going to essentially create a busy loop.  Is there a better way to integrate gRPC with libuv?

### Environment
 - Ubuntu 14.04.3 LTS x86_64
 - Node v8.9.3
 - Node npm n module
 - clang 3.4-1ubuntu3
 - gRPC@1.8.0

**Comment by murgatroid99** [comment]
Can you provide some more details about this busy loop you think is happening? The prepare handle is only called before Node polls for I/O, and `grpc_completion_queue_next` should only be called more than once if it returns an event, which should happen infrequently, and the I/O poll should last until something stops it, like a timeout or a network event. So, with those facts put together, there should not be a busy loop.

If you can provide some code that you are seeing performance problems with, it might help us understand what is going on there.

Also, one final thing: 1.8.0 is a somewhat old version of the library. I don't know if anything relevant has changed in the intervening time, but I would suggest trying out the latest version 1.12.4 to see if it behaves differently.

**Comment by nicolasnoble** [comment]
Seems similar to the discussion that happened there: https://github.com/grpc/grpc-node/issues/303

**Comment by sathibault** [comment]
Yes, thank you;  I had the same misconception that the active prepare handle would result in a zero timeout poll in the libuv run loop.

My only other idea is that the high CPU is due to pure-JS protobuf layer.  I wonder if I implemented a v8 wrapper over my C++ stub and integrated it with grpc in the same way this module is, I would get similar performance to the pure C++ client?

**Comment by nicolasnoble** [comment]
Well, if you would give us some ways of benchmarking what you're doing ourselves, it'd help a lot. It'd be useful to try and profile what's going on with your code, such as using a flamegraph for example.

**Comment by nicolasnoble** [comment]
Closing this one, as it went for more than a month with no updates.

**Comment by sathibault** [comment]
Oh, I wrote some feedback here a while back and never clicked the comment button!  Anyway ...

I think I have confirmed that the performance overhead is due to using pure JS for protobuf.  I have implemented a v8 module wrapper to my protobuf generated C++ stub for BigTable access and integrated the gRPC library into the main loop with prepare handles as you have done.  It is way faster than using the BigTable Node module.

**Comment by murgatroid99** [comment]
Are you talking about using the entire C++ gRPC library in Node? Or do you have some way of using the C++ protobuf library? Which JavaScript protobuf library are you comparing this with?

**Comment by sathibault** [comment]
I have not used grpc-node directly, but created a Node module that builds the gRPC library in the same way (with `GRPC_UV`) together a C++ protobuf stub generated for BigTable.

I'm comparing that to the performance of the standard `@google-cloud/bigtable` module.

**Comment by murgatroid99** [comment]
OK, I think I understand now. If your test is mainly showing that the Node gRPC library is slower than the C/C++ library, then that is broadly in agreement with our own benchmarks.

However, I think there may be some confounding factors here when trying to determine exactly what part of the libraries are slower. If you are not using the Node gRPC library at all, then you must be doing your own integration of the completion queue with the Node event loop. Plus there is a significant amount of other JavaScript code in the Node gRPC library that may impact performance.
