### ISSUE TITLE
RESTful Interop

### ISSUE THREAD

**Issue by travistrue2008** [grpc/grpc-node#420]
### Is your feature request related to a problem? Please describe.
We're using gRPC with Node for our microservices, but our load balancers can only be configured  make RESTful calls to the servers they manage to check if they're alive.

### Describe the solution you'd like
I'd like the ability to use the built-in `http` package as my web server to listen for incoming connections, check for incoming headers to see if the request is gRPC, and defer the gRPC payload to the `grpc` module for parsing, processing, it'd defer to my own handlers. If not, then handling

### Describe alternatives you've considered
I've looked at `grpc-dynamic-gateway` package, but it appears to just map gRPC requests to REST for everything. I don't need to map RPCs to REST endpoints, and it incurs overhead which defeats the purpose of gRPC. I just need to see if a single endpoint is hit, and send a 200 response, otherwise pass the request along to `grpc` to handle.

### Additional context
Our current solution is to have listen on a separate port using the `http` server for incoming REST requests, and use it to invoke gRPC's `IsAlive` RPC to make sure that connection's alive. This is messy because now each microservice we write needs 2 ports, and my HTTP server needs to import our client just to call the gRPC server.

**Comment by nicolasnoble** [comment]
That's not going to happen any time soon.

**Comment by travistrue2008** [comment]
Just wondering: how come `grpc` uses its own natively-compiled web server instead of using `http`? Is it meant to improve performance, or some functionality that `http` doesn't have, etc?

**Comment by murgatroid99** [comment]
gRPC is a protocol that is built on top of the HTTP/2 protocol, and the library is an implementation of that protocol. It is simply performing a different function than the `http` module does.

**Comment by nicolasnoble** [comment]
Or said differently, the `http` nodejs module doesn't have the necessary capabilities to handle [gRPC's wire protocol](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md).
