### ISSUE TITLE
error details of the  chinese will be will be truncated, a chinese charactor is three bytes

### ISSUE THREAD

**Issue by bysir-zl** [grpc/grpc-node#426]
### Problem description
error details of the  chinese will be will be truncated

### Reproduction steps
in service.js
```
function sayHello(call, callback) {
    callback({
        code: grpc.status.NOT_FOUND,
        details: '你好啊世界'
    });
}
```
client.js
```
  client.sayHello({name: user}, function (err, response) {
    if (err) {
      console.log(err.details);
    } else {
      console.log('Greeting:', response.message);
    }
  });
```
this client.js will print : 
```
$ node greeter_client.js
(node:15552) DeprecationWarning: grpc.load: Use the @grpc/proto-loader module wi
th grpc.loadPackageDefinition instead
你�

```

### Environment
- node v8.9.1
- grpc@1.13.0

### Additional context
a chinese charactor is three bytes

**Comment by nicolasnoble** [comment]
Full reproduction case attached. This one's interesting.

[string-issue.zip](https://github.com/grpc/grpc-node/files/2177154/string-issue.zip)

**Comment by nicolasnoble** [comment]
Full reproduction case attached. This one's interesting.

[string-issue.zip](https://github.com/grpc/grpc-node/files/2177165/string-issue.zip)
