### ISSUE TITLE
The options parameter needs to documented as required.

### ISSUE THREAD

**Issue by shobhitchittora** [grpc/grpc-node#427]
### Problem description
The use of the options object in `@grpc/proto-loader` package is not clear. It mentions that - 
`The options parameter is an object that can have the following optional properties`. 

There's nothing mentioned specifically whether the options parameter itself is required or not. And apparently it's required because the following code fails - 

``` js

loader.load('test').then((package) => {
  console.log(package);
});

```

stating - 

```
TypeError: Cannot read property 'includeDirs' of undefined
```

### Environment
 - OS name, version and architecture: OSX Sierra 10.12.6
 - Node version: 8.0.0
 - Node installation method: nvm
 - Package name and version:   @grpc/proto-loader: ^0.1.0

### Additional context
A doc update would be great. Up for creating a PR if triaged. 😇

**Comment by nicolasnoble** [comment]
This rather sounds like a bug in the library. This really should be optional.

**Comment by shobhitchittora** [comment]
@nicolasnoble +1.
I'm up for pushing a PR if this is indeed what everyone wants. I can see that this might be a breaking change. Please do let me know. 😇

**Comment by nicolasnoble** [comment]
I wouldn't consider this a breaking change, no. Your PR to fix this would be welcome.

**Comment by murgatroid99** [comment]
I went ahead and opened the PR with that change myself.

**Comment by shobhitchittora** [comment]
@murgatroid99 🎉🎉🎉
