### ISSUE TITLE
[Doc] Would be great if it was easy to access docs for older versions

### ISSUE THREAD

**Issue by richardpringle** [grpc/grpc-node#431]
### Is your feature request related to a problem? Please describe.
The api changed between 1.10 and 1.13... but now I can't find the api reference for 1.10. I've been looking through the code, but it's taking me way longer to find what I'm looking for than it should.

### Describe the solution you'd like
Each minor release should have a separate doc build

### Describe alternatives you've considered
I've just been digging through the code

### Additional context
Could use some better examples around ssl with Node.js... but I think that's a much bigger ask than just keeping the old minor releases of the api docs. It could also just be that I don't know where to find them.

**Comment by nicolasnoble** [comment]
What API change are you referring to ? There shouldn't have been any breaking change.

**Comment by nicolasnoble** [comment]
Also, since we're not supposed to do breaking changes, always having the latest document per major version ought to be enough.

**Comment by richardpringle** [comment]
@nicolasnoble, there's a deprecation warning on `grpc.load` that wasn't there before, but you're right, that isn't breaking.

I think that a quick blurb in the README about how to build the docs yourself would be nice...

However, I realized that I was following an older tutorial for authentication where the API was different:
https://jsherz.com/grpc/node/nodejs/mutual/authentication/ssl/2017/10/27/grpc-node-with-mutual-auth.html

There they gave the following example:
```
server.bind('0.0.0.0:50051', grpc.ServerCredentials.createSsl({
      rootCerts: fs.readFileSync(path.join(process.cwd, "server-certs", "Snazzy_Microservices.crt")),
      keyCertPairs: {
            privateKey: fs.readFileSync(path.join(process.cwd, "server-certs", "login.services.widgets.inc.key")),
            certChain: fs.readFileSync(path.join(process.cwd, "server-certs", "login.services.widgets.inc.crt"))
      },
      checkClientCertificate: true
}));
```

It would have been nice for me to look back at previous versions and see when the api matched that tutorial, just to make sure that there were no other major changes (and if the tutorial was still valid).

Just to re-iterate, having multiple builds of the docs just like the [Node.js docs](https://nodejs.org/docs/) would be great, otherwise, an addition to the readme that instructs on how to run the build tool myself.

**Comment by murgatroid99** [comment]
Our API has never matched that code sample.

In a broader scope, we published version 1.0 in late 2016, and we have not made any breaking changes since then, or in the few versions before that. I don't even know if we had generated documentation that long ago.

So there is really nothing to find by looking at previous versions of the documentation. You would basically just see incomplete documentation of the current library.

**Comment by richardpringle** [comment]
Ha! Fair enough. Thanks for the insight.

**Comment by richardpringle** [comment]
@nicolasnoble @murgatroid99 
in 1.10, the `privateKey` and `certChain` are actually snake cased... so there has been a breaking change.

**Comment by murgatroid99** [comment]
That was actually not a code change. It was just a documentation error that was fixed in #171.

**Comment by richardpringle** [comment]
Then the docs need to be updated then: https://grpc.io/grpc/node/grpc.ServerCredentials.html

**Comment by murgatroid99** [comment]
The new documentation has now been published.
