### ISSUE TITLE
Passing additional CallOptions for client interceptors

### ISSUE THREAD

**Issue by TLadd** [grpc/grpc-node#433]
I need to pass some additional data per-call for a client interceptor to use. It seems like passing the data through the [CallOptions](https://github.com/grpc/grpc-node/blob/master/packages/grpc-native-core/index.d.ts#L999) argument works, but I was curious if that was an alright approach, or if there were any pitfalls. The typescript definition does not indicate that custom options are allowed (https://github.com/grpc/grpc-node/blob/master/packages/grpc-native-core/index.d.ts#L1094)

I found [this similar issue in grpc-java](https://github.com/grpc/grpc-java/issues/1800), where the eventual conclusion did seem to be passing extra data through CallOptions.

**Comment by murgatroid99** [comment]
I would say that it is correct to pass options to interceptors through the call options. And I think it is reasonable to modify that type definition to allow for arbitrary additional options. That type definition simply predates the client interceptor API and doesn't take that use case into account.

**Comment by TLadd** [comment]
Awesome, thank you for the clarity. I can put a PR up to update the type.
