### ISSUE TITLE
@grpc/proto-loader Empty Arrays Are 'undefined'

### ISSUE THREAD

**Issue by travistrue2008** [grpc/grpc-node#434]
### Problem description
When we pass our database results to our gRPC server's RPC handler, the property assigned to the empty array is omitted ever since we've switched over to using `@grpc/proto-loader` in our NodeJS project.

### Reproduction steps
Here's a stripped-down version of our RPC handler:
```
export function passSomeData (_call, callback) {
  callback(null, {
    id: 'asdf',
    name: 'Travis',
    results: [],
  })
}
```

Here's what our client looks like:
```
// we promisify our client RPCs
const res = await client.passSomeData(args)
console.log('res:', res) /* res: {
  id: 'asdf',
  name: 'Travis',
} */
```
The `results` property isn't even defined.

### Environment
 - OS name, version and architecture: `macOS 10.13.5`
 - Node version `8.10`
 - Node installation method: `nvm`
 - Package name and version [e.g. gRPC@1.12.0]

**Comment by nicolasnoble** [comment]
Per the documentation of https://www.npmjs.com/package/@grpc/proto-loader, please add the `arrays=true` in the options.

**Comment by travistrue2008** [comment]
Jeez, I should have checked the documentation *facepalm* I've even used these options before, dangit. In my defense, I've been up for about ~28 hours though...

Thanks, guys. Looks like an easy fix from here.

**Comment by nicolasnoble** [comment]
Please report back and close if appropriate :-)

**Comment by travistrue2008** [comment]
Hey @nicolasnoble! Sorry, I didn't close right away. I'm new to GitHub issues, and I didn't see your response asking me to close this issue. I thought the authors closed issues that seemed irrelevant.

Your advice did resolve the issues we were running into. Thanks again for `proto-loader`. It's been great to work with!
