### ISSUE TITLE
Upgrade to protobufjs 6?

### ISSUE THREAD

**Issue by theogravity** [grpc/grpc-node#436]
### Is your feature request related to a problem? Please describe.

grpc-node seems to be using protobufjs 5 based on this:

```
$ npm ls protobufjs
...
└─┬ grpc@1.13.0
  └── protobufjs@5.0.3 
```

### Describe the solution you'd like

Can the project use protobufjs 6? It has been out for two years already.

It'd address issues like https://github.com/dcodeIO/protobuf.js/issues/476

**Comment by theogravity** [comment]
Oh, it seems it's more tied to the loader being used.

Looks like I need to start using https://www.npmjs.com/package/@grpc/proto-loader for loading the files.

**Comment by nicolasnoble** [comment]
Exactly. The direct dependency is legacy code that is deprecated. Updating it would be a breaking change. The loader is the way to go now.
