### ISSUE TITLE
Parameterized download location of precompiled-binaries

### ISSUE THREAD

**Issue by tomasAlabes** [grpc/grpc-node#441]
### Is your feature request related to a problem? Please describe.
A request is done to https://storage.googleapis.com/ to download the precompiled binaries, and I need to download that binary from my Artifactory, not from Google.

### Describe the solution you'd like
Have a way to pass the location of the binary as a parameter or environment variable to the downloader.

### Describe alternatives you've considered
Compiling it is more cumbersome as it depends on the platform and other tools. I'd like to take advantage of the already compiled binaries. And using a proxy is what I can't do.

### Additional context
* I have to download if from Artifactory
* I can't use the proxy

**Comment by murgatroid99** [comment]
Please see #117 for information about how to do that.
