### ISSUE TITLE
No easy way to detect or fail when starting a gRPC server on a taken port 

### ISSUE THREAD

**Issue by bojand** [grpc/grpc-node#443]
### Problem description

Not sure if this is a bug or expected behaviour, but using `grpc@1.13.0` it seems `server.bind()` or `server.start()` do not clearly error or throw when bound to a port that's already taken. In such scenario an error is logged but the application otherwise continues. It seems `server.bind()` returns `0` (normally it returns the port) which isn't very helpful way of determining the erroneous condition.

### Reproduction steps
Use [helloworld.proto](https://github.com/grpc/grpc/blob/master/examples/protos/helloworld.proto)

```sh
$ npm i grpc @grpc/proto-loader
```

server.js
```js
const path = require('path')

const protoLoader = require('@grpc/proto-loader')
const grpc = require('grpc')

const PROTO_PATH = path.resolve(__dirname, './protos/helloworld.proto')

const pd = protoLoader.loadSync(PROTO_PATH)
const hp = grpc.loadPackageDefinition(pd).helloworld

function sayHello (call, fn) {
  fn(null, { message: 'Hello ' + call.request.name })
}

function main () {
  const port = 50051
  const server = new grpc.Server()

  server.addService(hp.Greeter.service, { sayHello: sayHello })
  server.bind(`0.0.0.0:${port}`, grpc.ServerCredentials.createInsecure())
  server.start()
  console.log(`gRPC server started on port: ${port}`)
}

main()

```
start server:
```sh
$ node server.js
```
in another terminal session try the same:
```sh
$ node server.js
E0719 09:28:43.579062000 140735852622720 server_chttp2.cc:40]          {"created":"@1532003323.579028000","description":"No address added out of total 1 resolved","file":"../deps/grpc/src/core/ext/transport/chttp2/server/chttp2_server.cc","file_line":307,"referenced_errors":[{"created":"@1532003323.579025000","description":"Failed to add port to server","file":"../deps/grpc/src/core/lib/iomgr/tcp_server_custom.cc","file_line":402,"referenced_errors":[{"created":"@1532003323.579010000","description":"Failed to listen to port","file":"../deps/grpc/src/core/lib/iomgr/tcp_uv.cc","file_line":73,"grpc_status":14,"os_error":"address already in use"}]}]}
gRPC server started on port: 50051
```

### Environment
 - OS name, version and architecture:  `macOS High Sierra 0.13.6`
 - Node version: Tested with Node.js `8.11.3`, `10.6.0`, and `10.7.0`
 - Node installation method: stock installer for `10.7.0` and nvm for others.
 - If applicable, compiler version: N/A
 - Package name and version: `grpc@1.13.0`, `@grpc/proto-loader@0.3.0`

**Comment by murgatroid99** [comment]
The supported way to detect this is to check the return value of `server.bind` and handle the value of `0` as a failure.
