### ISSUE TITLE
gRPC Protobuf Loader when there is not gRPC service

### ISSUE THREAD

**Issue by Olshansk** [grpc/grpc-node#444]
I'm looking for an equivalent to `protobufjs.loadSync(fileName)` that also supports `includeDirs` when there is no gRPC service, but simply a set of protobufs importing other protobufs from different directories.

Is there a way to do this?

**Comment by murgatroid99** [comment]
I would suggest looking at the `@grpc/proto-loader` code in this repository .The support for `includeDirs` is really just a small modification to how Protobuf.js resolves file names. You could probably just use that same function in your own code if you want the same functionality.

**Comment by Olshansk** [comment]
Thanks for the suggestion @murgatroid99.

I wanted to share my solution (based on the code from `@grpc/proto-loader`) for completeness.

The closest equivalent to something like:

```
return protobufjs.loadSync(fileName, {includePaths: includePaths})`
```

is:

```
  addIncludePathToRoot(root, includePaths) {
    root.resolvePath =  function(origin, target) {
      for (const directory of includePaths) {
        const fullPath = path.join(directory, target);
        try {
          fs.accessSync(fullPath, fs.constants.R_OK);
          return fullPath;
        } catch (err) {
          continue;
        }
      }
      return null;
    };
  }

const root = new protobufjs.Root();
addIncludePathToRoot(root, includePaths)
const loadedRoot = root.loadSync(proto);
loadedRoot.resolveAll();
return root;
```
