### ISSUE TITLE
grpc-node-core documentation is out of date

### ISSUE THREAD

**Issue by mvaldesdeleon** [grpc/grpc-node#449]
### Problem description
The documentation available at https://grpc.io/grpc/node/grpc.html is not up to date with the current codebase.

### Reproduction steps
You can see that the attached link is missing the `loadPackageDefinition` method (https://github.com/grpc/grpc-node/blob/master/packages/grpc-native-core/index.js#L160).

### Environment
 - N/A

### Additional context
Since it looks like the documentation itself is automatically generated, it would be nice if it could track the current codebase and not require manual intervention.

According to the footer ("Documentation generated by JSDoc 3.5.5 on 2018-01-16T12:05:13-05:00 using the DocStrap template."), it appears to be lagging by several months, given that the latest release was a few weeks ago.

**Comment by murgatroid99** [comment]
Thank you for pointing this out. That documentation is now up to date with the latest release, version 1.14.
