### ISSUE TITLE
compiling error when building from source on ubuntu 18.04

### ISSUE THREAD

**Issue by xgdgsc** [grpc/grpc-node#452]
### Problem description
Hi. I' m using the nodejs 8 deb package from official site (not the ubuntu repo version) . When I do npm rebuild for grpc with one of my electron project.

### Reproduction steps
npm install --build-from-source=grpc 

### Environment
 - OS name, version and architecture: [e.g. Linux Ubuntu 18.04 amd64]
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04 LTS"

 - Node version [e.g. 8.10.0]
$ node -v
v8.11.3

 - Node installation method [e.g. nvm]
deb package from https://deb.nodesource.com/node_8.x
 
 - Package name and version [e.g. gRPC@1.12.0]
 grpc@1.13.0

### Additional context
 I get following compiling errors:
```
CXX(target) Release/obj.target/grpc_node/ext/call.o
In file included from ../ext/call.cc:26:0:
../ext/call.h:106:8: error: ‘AsyncResource’ in namespace ‘Nan’ does not name a type
   Nan::AsyncResource *async_resource;
        ^~~~~~~~~~~~~
In file included from ../ext/call.cc:27:0:
../ext/call_credentials.h:82:8: error: ‘AsyncResource’ in namespace ‘Nan’ does not name a type
   Nan::AsyncResource *async_resource;
        ^~~~~~~~~~~~~
../ext/call_credentials.h: In constructor ‘grpc::node::plugin_callback_data::plugin_callback_data(const char*, grpc_credentials_plugin_metadata_cb, void*)’:
../ext/call_credentials.h:71:9: error: class ‘grpc::node::plugin_callback_data’ does not have any field named ‘async_resource’
         async_resource(NULL) {
         ^~~~~~~~~~~~~~
../ext/call_credentials.h:73:5: error: ‘async_resource’ was not declared in this scope
     async_resource = new Nan::AsyncResource("grpc:plugin_callback_data");
     ^~~~~~~~~~~~~~
../ext/call_credentials.h:73:26: error: expected type-specifier
     async_resource = new Nan::AsyncResource("grpc:plugin_callback_data");
                          ^~~
../ext/call_credentials.h: In destructor ‘grpc::node::plugin_callback_data::~plugin_callback_data()’:
../ext/call_credentials.h:76:12: error: ‘async_resource’ was not declared in this scope
     delete async_resource;
            ^~~~~~~~~~~~~~
../ext/call.cc: In constructor ‘grpc::node::tag::tag(Nan::Callback*, grpc::node::OpVec*, grpc::node::Call*, v8::Local<v8::Value>)’:
../ext/call.cc:450:7: error: class ‘grpc::node::tag’ does not have any field named ‘async_resource’
       async_resource(NULL),
       ^~~~~~~~~~~~~~
../ext/call.cc:454:3: error: ‘async_resource’ was not declared in this scope
   async_resource = new Nan::AsyncResource("grpc:tag");  // Needs handle scope.
   ^~~~~~~~~~~~~~
../ext/call.cc:454:24: error: expected type-specifier
   async_resource = new Nan::AsyncResource("grpc:tag");  // Needs handle scope.
                        ^~~
../ext/call.cc: In destructor ‘grpc::node::tag::~tag()’:
../ext/call.cc:460:10: error: ‘async_resource’ was not declared in this scope
   delete async_resource;
          ^~~~~~~~~~~~~~
../ext/call.cc: In function ‘void grpc::node::CompleteTag(void*, const char*)’:
../ext/call.cc:476:41: error: ‘struct grpc::node::tag’ has no member named ‘async_resource’
     callback->Call(2, argv, tag_struct->async_resource);
                                         ^~~~~~~~~~~~~~
../ext/call.cc:479:41: error: ‘struct grpc::node::tag’ has no member named ‘async_resource’
     callback->Call(1, argv, tag_struct->async_resource);
                                         ^~~~~~~~~~~~~~

```

**Comment by nicolasnoble** [comment]
Thanks for moving this to a new issue, and for providing the additional details.

**Comment by nicolasnoble** [comment]
I fail to reproduce following the steps you are describing, which means there's something odd with your reproduction steps. Here's a working Dockerfile that demonstrates what I am attempting on my end:

```
FROM ubuntu:18.04

RUN apt-get update
RUN apt-get install -y curl gnupg
RUN curl -sL https://deb.nodesource.com/setup_8.x | bash -
RUN apt-get install -y g++ make nodejs
RUN JOBS=8 npm install --build-from-source grpc@1.13.0
```

**Comment by nicolasnoble** [comment]
Few things that are catching my attention in your bug report however. You are mentioning Electron, yet you aren't running anything Electron-related. This is odd.

We've recently added some notes about using Electron in our [readme file](https://github.com/grpc/grpc-node/tree/master/packages/grpc-native-core). Please refer to them for some explanations on how this is supposed to work.

Also, why would you really want to build from source ? We're shipping working Electron binaries, and it's okay to use them - unless you don't want to trust us, but in this case, please follow the guidelines on how to properly use `npm rebuild`.

Last but not least, I am realizing that the error you are listing is a common one when there's a mismatch between Electron and NodeJS' headers. Unfortunately, `node-gyp` is caching them, and has bad Electron support, so they will stay mismatched forever, even after you enter the proper command line arguments. Please try nuking your `node-gyp` cache before trying again:

```
rm -rf ~/.node-gyp
```

**Comment by xgdgsc** [comment]
Thanks. I get 504 error on url `https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.13.0/node-v57-linux-x64-glibc.tar.gz ` when running `npm i --target=2.0.5 --runtime=electron --dist-url=https://atom.io/download/electron grpc`  even with a proxy. I manually downloaded the file and put it to the location. Hope those files could be hosted somewhere more friendly for Chinese users, though.

**Comment by nicolasnoble** [comment]
Ah ! Could you tell me if https://packages.grpc.io works from China?

**Comment by xgdgsc** [comment]
grpc.io works well. I tried deleting ~/.node-gyp and still cannot compile.

**Comment by nicolasnoble** [comment]
We'll start publishing binaries there soon, we'll see if it makes things better for you.
