### ISSUE TITLE
node-grpc server does not compresses streaming responses inspite of the presence of accept-encoding gzip header.

### ISSUE THREAD

**Issue by darkryder** [grpc/grpc-node#465]
### Problem description
Node-grpc server does not compress streaming responses, even when requested on a channel with compression defaults.

### Reproduction steps
I'm using the server and client from the [GRPC examples folder](https://github.com/grpc/grpc/tree/master/examples). The example I'm using is the route service.
GRPC client: `examples/python/route_guide/route_guide_client.py`
GRPC server: `/examples/node/dynamic_codegen/route_guide/route_guide_server.js`

I'm using socat to intercept the traffic between the server and client and check for compression. `socat -v TCP-LISTEN:50052,fork TCP:localhost:50051`

### Environment
 - OS name, version and architecture:  Ubuntu 16.04.4 LTS x86_64
 - Node version: v8.11.3
 - Node installation method: apt - [https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions](official installation page)
 - If applicable, compiler version [e.g. clang 3.8.0-2ubuntu4]
 - Package name and version:  grpc@1.13.0

### Additional context

1. Modify the client to go to 50052, so we can see packets intercepted by socat. 
` [Python client] <=> <socat> <=> [nodejs sever]`. Modified the `route_guide_client.py` file to send compression defaults.
``` python
+def run2():
+       with grpc.insecure_channel('localhost:50052', options=[('grpc.default_compression_algorithm', 1)]) as channel:
+               stub = route_guide_pb2_grpc.RouteGuideStub(channel)
+               guide_list_features(stub)

 if __name__ == '__main__':
-    run()
+    run2()
(
```

Calling `python route_guide_client.py` will show that the client had sent the `grpc-accept-encoding: identity, deflate, gzip` header, but the response is uncompressed.

```
> 2018/07/27 16:05:54.259897  length=488 from=0 to=487
PRI * HTTP/2.0\r
\r
SM\r
\r
..$.....................@.....@...... .........;......@\a:scheme.http@\a:method.POST@
:authority.localhost:50052@.:path#/routeguide.RouteGuide/ListFeatures@.te\btrailers@\fcontent-type.application/grpc@
user-agent=grpc-python/1.13.0 grpc-c/6.0.0 (manylinux; chttp2; gloriosa)@\rgrpc-encoding\adeflate@.grpc-accept-encoding.identity,deflate,gzip@.accept-encoding\ridentity,gzip...\b...........+..........&
.\b..................\b...................\b......?....\b..............< 2018/07/27 16:05:54.266914  length=250 from=0 to=249
............@.....@...... ..........\b......?....\b................\b..........................\b........+.........@\a:status.200@\fcontent-type.application/grpc@\rgrpc-encoding.gzip@.grpc-accept-encoding.identity,deflate,gzip@.accept-encoding\ridentity,gzip> 2018/07/27 16:05:54.270985  length=26 from=488 to=513
..\b.......................< 2018/07/27 16:05:54.275528  length=72 from=250 to=321
..?..........:
%Patriots Path, Mendham, NJ 07945, USA..\b................< 2018/07/27 16:05:54.278925  length=1620 from=322 to=1941
..D..........?
*101 New Jersey 10, Whippany, NJ 07981, USA..\b..................8..........3
.U.S. 6, Shohola, PA 18458, USA..\b..................A..........<
'5 Conners Road, Kingston, NY 12401, USA..\b..................S..........N
9Mid Hudson Psychiatric Center, New Hampton, NY 10958, USA..\b..................N..........I
4287 Flugertown Road, Livingston Manor, NY 12758, USA..\b..................H..........C
...
...
*261 Van Sickle Road, Goshen, NY 10924, USA..\b..................<..........7
"3 Hasta Way, Newton, NJ 07860, USA..\b.................. ......@\vgrpc-status.0@\fgrpc-message.OK
```

It's similar to #464, but I have been unable to find any magic header which makes the server compress the response. I've tried adding the `grpc-internal-encoding-request` header in the trailing metadata as well.

The tests specified [here](https://github.com/grpc/grpc/blob/063d5de052af0280b415526e06287190ba909ed2/test/core/compression/compression_test.cc#L82) seem to point that gzip/deflate should be given priority.

**How do I get the nodejs grpc server to compress streaming responses?**

**Comment by murgatroid99** [comment]
I want to note first that the `grpc.default_compression_algorithm` argument changes what compression algorithm the client uses for sending messages. So you shouldn't expect that to directly affect the response encoding. Also, the value of 1 corresponds to deflate, not gzip, in case that matters. You can see [this header](https://github.com/grpc/grpc/blob/master/include/grpc/impl/codegen/compression_types.h) for all of the details.

The compression algorithm that the client can handle in response messages is determined by the `rpc.compression_enabled_algorithms_bitset` argument, but the documentation says that they are all enabled by default, so that shouldn't be the problem. There is also the `grpc.default_compression_level` argument on the server, which approximately determines which compression algorithms the server can use when sending. It might help to set that to 1, 2, or 3 on the server.

**Comment by darkryder** [comment]
> the grpc.default_compression_algorithm argument changes what compression algorithm the client uses
I understand, though I used this to show that the server has the libraries to decompress the data.

> Also, the value of 1 corresponds to deflate
Ah, that was a mistake. I was more concerned right now about making any kind of compression work. Thanks for pointing it out.

> There is also the grpc.default_compression_level argument on the server
This ended up solving it for me, though the compression kicked in after some length of the message.
Thanks for pointing this out!

I couldn't find this mentioned anywhere in the nodejs grpc documentation. Thanks!

**Comment by darkryder** [comment]
I still wonder why didn't the server automatically prefer to compress the response since the client accepted it. Is the default value of grpc.default_compression_level set to 0 (Identity) ?

**Comment by darkryder** [comment]
Setting `grpc.default_compression_level` worked for me, though the question for default value still remains. Thanks!
