### ISSUE TITLE
NPM module includes very large, unnecessary file

### ISSUE THREAD

**Issue by 24601** [grpc/grpc-node#471]
### Problem description
The gRPC node module is 36.3MB or so. That appears largely, in part due to a single 20.2MB file from the BoringSSL dep that seems to be a totally unnecessary test data source file.  

### Reproduction steps
Install the node module

### Environment
Mac OS X. NPM 5.5.1. Node 8.9.1

### Additional context
The file in question is "deps/grpc/src/boringssl/crypto_test_data.cc". 

Is this something I should open up against BoringSSL? Since it's the gRPC lib that is packaging it I figured this might be the place, but let me know if I'm barking up the wrong tree.

**Comment by nicolasnoble** [comment]
The rootcause is due to [this line](https://github.com/grpc/grpc-node/blob/master/packages/grpc-native-core/templates/package.json.template#L71) that's being overly generous.

**Comment by murgatroid99** [comment]
I cannot find that file on GitHub, so I have no idea why it would be showing up in our package.

**Comment by nicolasnoble** [comment]
Oh. I missed the path. It's being generated during buildgen.sh

**Comment by nicolasnoble** [comment]
And it's definitely present on github. https://github.com/grpc/grpc/blob/master/src/boringssl/crypto_test_data.cc

**Comment by murgatroid99** [comment]
Oh, I was looking at grpc/third_party/boringssl

**Comment by cjihrig** [comment]
Can this be closed since #501 landed?
