### ISSUE TITLE
I am facing gyp error while installing grpc package

### ISSUE THREAD

**Issue by garimak29** [grpc/grpc-node#472]
### Problem description
While installing grpc package, I am receiving following error:

```
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (d:\Profiles\garkumar\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Users\\garkumar\\Node\\node.exe" "d:\\Profiles\\garkumar\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=d:\\Profiles\\garkumar\\AppData\\Roaming\\npm\\node_modules\\grpc\\src\\node\\extension_binary\\node-v57-win32-x64-unknown\\grpc_node.node" "--module_name=grpc_node" "--module_path=d:\\Profiles\\garkumar\\AppData\\Roaming\\npm\\node_modules\\grpc\\src\\node\\extension_binary\\node-v57-win32-x64-unknown" "--napi_version=1" "--node_abi_napi=napi"
gyp ERR! cwd d:\Profiles\garkumar\AppData\Roaming\npm\node_modules\grpc
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Users\garkumar\Node\node.exe d:\Profiles\garkumar\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --library=static_library --module=d:\Profiles\garkumar\AppData\Roaming\npm\node_modules\grpc\src\node\extension_binary\node-v57-win32-x64-unknown\grpc_node.node --module_name=grpc_node --module_path=d:\Profiles\garkumar\AppData\Roaming\npm\node_modules\grpc\src\node\extension_binary\node-v57-win32-x64-unknown --napi_version=1 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (d:\Profiles\garkumar\AppData\Roaming\npm\node_modules\grpc\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Windows_NT 10.0.15063
node-pre-gyp ERR! command "C:\\Users\\garkumar\\Node\\node.exe" "d:\\Profiles\\garkumar\\AppData\\Roaming\\npm\\node_modules\\grpc\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd d:\Profiles\garkumar\AppData\Roaming\npm\node_modules\grpc
node-pre-gyp ERR! node -v v8.9.4
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok
Failed to execute 'C:\Users\garkumar\Node\node.exe d:\Profiles\garkumar\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --library=static_library --module=d:\Profiles\garkumar\AppData\Roaming\npm\node_modules\grpc\src\node\extension_binary\node-v57-win32-x64-unknown\grpc_node.node --module_name=grpc_node --module_path=d:\Profiles\garkumar\AppData\Roaming\npm\node_modules\grpc\src\node\extension_binary\node-v57-win32-x64-unknown --napi_version=1 --node_abi_napi=napi' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.14.0-pre2 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grpc@1.14.0-pre2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

###Steps

Following command was used for installation:
npm install -g grpc

### Environment
Windows 10

**Comment by nicolasnoble** [comment]
You haven't shared the whole log with us. Please do so.

**Comment by chameleonbr** [comment]
I facing the same problem with node 8 and 10 when I install GRPC 1.13 and 1.14 module.

As I see, the script can not download the binary and try to compile the grpc module and crash.
Node 10
`CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/filters/client_channel/resolver/sockaddr/sockaddr_resolver.o
make: *** No rule to make target 'Release/obj.target/grpc/deps/grpc/src/cpp/ext/filters/census/grpc_context.o', needed by 'Release/obj.target/libgrpc.a'.  Pare.
make: Leaving directory '/home/user/projects/cargas/node_modules/grpc/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
gyp ERR! System Linux 4.13.0-36-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=/home/user/projects/cargas/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node" "--module_name=grpc_node" "--module_path=/home/user/projects/cargas/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc" "--napi_version=3" "--node_abi_napi=napi"
gyp ERR! cwd /home/user/projects/cargas/node_modules/grpc
gyp ERR! node -v v10.8.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/home/user/projects/cargas/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node--module_name=grpc_node --module_path=/home/user/projects/cargas/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc --napi_version=3 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/user/projects/cargas/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:249:5)
node-pre-gyp ERR! System Linux 4.13.0-36-generic
node-pre-gyp ERR! command "/usr/bin/node" "/home/user/projects/cargas/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd /home/user/projects/cargas/node_modules/grpc
node-pre-gyp ERR! node -v v10.8.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/home/user/projects/cargas/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/home/user/projects/cargas/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc --napi_version=3 --node_abi_napi=napi' (1)`

**Comment by murgatroid99** [comment]
Can you please share your full error output?

**Comment by nicolasnoble** [comment]
Please avoid assuming that issues are similar. Most of the time, they are not. Please open a new issue for yours, including the whole log, especially the part that describes the download failures.

**Comment by chameleonbr** [comment]
How I can share full error report?

**Comment by murgatroid99** [comment]
I think I know what the problem is with the second error: that missing file is in `deps/grpc/src/cpp`, which of course we are not distributing because core has never before depended on `src/cpp`.

**Comment by murgatroid99** [comment]
Regarding the original error: trying to build gRPC from source on Windows is pretty much guaranteed to fail. It's just an unfortunate fact of how things outside of our control are set up. Problems like that are the reason that we distribute precompiled binaries. You are more likely to be able to fix the problem of failing to install the binary than the problem of failing to build from source, but without the full error log, we can't tell why you failed to install the binary.

**Comment by garimak29** [comment]
It was a proxy issue. I was able to install the binary successfully after fixing it.
