### ISSUE TITLE
Vulnerability : protobufjs

### ISSUE THREAD

**Issue by DoodahProductions** [grpc/grpc-node#479]
Latest version of this module has an open source vulnerability on : 

- protobufjs-5.0.3.tgz
- name : WS-2018-0083
- description : Versions of protobufjs before 6.8.6 are vulnerable to denial of service when parsing crafted invalid *.proto files.

Could you release a fix on this ?
Thanks.

**Comment by murgatroid99** [comment]
If you're referring to [this ReDoS vulnerability](https://snyk.io/vuln/npm:protobufjs:20180305), it was fixed in Protobuf.js 5.0.3. If not, I don't know what you're referring to.

**Comment by nicolasnoble** [comment]
Also please provide the origin of this report.

**Comment by DoodahProductions** [comment]
Hello,

Thanks for you fast response.
This reports comes form the WhiteSource security scanner. 

Based on description, it seems to be the ReDos vulnerability @murgatroid99 linked. I guess this is an issue with Whitesource tagging the version 5.0.3 as vulnerable when it's not.

I'll talk with the whitesource team to see if it's a false positive.
Thanks.

**Comment by nicolasnoble** [comment]
Snyk and nodesecurity have the correct information about this vulnerability, and both show that 5.0.3 is fixed. So, yes, if whitesource is flagging it, this is incorrect.

See the following:

https://snyk.io/vuln/npm:protobufjs:20180305
https://www.npmjs.com/advisories/605

**Comment by nicolasnoble** [comment]
I'll close this one as this is a false positive, really. Let us know if you need help with whitesource.
