### ISSUE TITLE
Export Request/Response Classes

### ISSUE THREAD

**Issue by jonahbron** [grpc/grpc-node#485]
### Is your feature request related to a problem? Please describe.
I'd like to submit type definitions to DefinitelyTyped for the grpc NPM package.  This would make it easier to write server service handlers in TypeScript.  In order to make those type definitions available, it's necessary that the classes themselves are exported and made available to applications.  Classes like ServerUnaryCall, etc.

### Describe the solution you'd like
I would like to submit a PR that makes the following classes are exported:

* ServerUnaryCall
* ServerWritableStream
* ServerReadableStream
* ServerDuplexStream
* ClientUnaryCall
* ClientWritableStream
* ClientReadableStream
* ClientDuplexStream

This would have no backwards-compatibility effects, and would also be useful for unit testing as well.  I can contribute this change if it is welcome.

### Describe alternatives you've considered
The only alternative solution I'm aware of is to declare the types entirely separately and import them outside the context of the GRPC library.

**Comment by murgatroid99** [comment]
All eight of those types are exported by the typescript type definition files that are distributed with the gRPC library. Is that what you need?

**Comment by jonahbron** [comment]
@murgatroid99 Oh, somehow I didn't even realize there were type definitions included. Those work, thank you!
