### ISSUE TITLE
Next Release?

### ISSUE THREAD

**Issue by wikiwong** [grpc/grpc-node#499]
Hey, thanks for the great library!  I'm looking to grab the latest of `grpc-tool`, as it contains a change to increase the `maxBuffer` size of the childProcess during code gen: https://github.com/grpc/grpc-node/blob/master/packages/grpc-tools/bin/protoc_plugin.js#L35

When do you think this change will be published to NPM?  More generally, is this project on a release cycle?

(sorry if this is not the appropriate medium to be asking these questions)

**Comment by nicolasnoble** [comment]
Yes, we definitely need to do a grpc-tools release, we just haven't managed to get around to it yet. Sorry.

**Comment by wikiwong** [comment]
No worries, will keep an eye on it then.

**Comment by sangaman** [comment]
A new release would definitely be appreciated. The `grpc-tools` version in npm is a year old, and it has a dependency on an older version of `node-pre-gyp`, which in turn has a dependency on an old version of `hawk`, which in turn has a dependency on an old version of `cryptiles` which has a security vulnerability.

**Comment by TLadd** [comment]
Ran into an issue where I'm not able to generate from protos using reserved values because it was introduced in protoc 3.5.0 https://github.com/protocolbuffers/protobuf/issues/4010

**Comment by sangaman** [comment]
@nicolasnoble Still looking forward to a new release on npm, it would help us out a lot particularly with some of the older dependencies that are in the outdated/published version. Let me know if there's anything I can do to help move it along.

**Comment by murgatroid99** [comment]
Thank you for your patience with this issue. We have published a new version of `grpc-tools` with that change.

**Comment by sangaman** [comment]
@murgatroid99 I am unable to update `grpc-tools` to 1.7 on windows through npm, I always receive this error:

`404 status code downloading tarball https://node-precompiled-binaries.grpc.io/grpc-tools/v1.7.0/win32-x64.tar.gz`

Any ideas off the top of your head? Should I open a separate issue?

**Comment by murgatroid99** [comment]
I know what the issue is there. That was an error in the build script. I think I fixed the issue for 1.7; can you try again?

**Comment by sangaman** [comment]
Looks like it works now, oddly `npm update grpc-tools` was giving me no output at all (I'm guessing that may be some cache issue with npm) but `npm remove grpc-tools` and `npm install grpc-tools` worked fine, thank you!
