### ISSUE TITLE
Typescript typings have partially incorrect definition for `CallCredentials`

### ISSUE THREAD

**Issue by SimonSchick** [grpc/grpc-node#502]
### Problem description
See title.

### Reproduction steps
Try to use any of the `make*Request` calls with `options`.

### Environment
gRPC@1.14 and earlier
Everything else is not applicable

### Additional context

Relatively basic, the `CallOptions` interface exported from the properties:

```
propagate_flags: number;
credentials: CallCredentials;
```

see https://github.com/grpc/grpc-node/blob/master/packages/grpc-native-core/index.d.ts#L1140

set as mandatory, this seems incorrect given the code around it and other typing files.

**Comment by jonahbron** [comment]
I've run into other type-related issues here as well.  It seems that ChannelCredentials does not have the getCallCredentials() or getSecureContext() functions.

**Comment by murgatroid99** [comment]
Those methods are internal and only exist in the grpc-js library. It is an error that they are visible in the public interface.

**Comment by paambaati** [comment]
@murgatroid99 I'm trying to use it like this —

1. Generatic static `_pb` files.
2. Take (optional) credentials and start server.

	```
	import { Client, credentials, ChannelCredentials } from 'grpc';
	const connection = new Client('address:1234', credentials.createInsecure());
	```
3. Now I want to set a deadline for a particular call. This is where TS throws —

	```
	connection.someRPCMethod(someRPCRequest, { deadline: 123 } , (err, res) => {})
	```

Because `propagate_flags` and `credentials` are mandatory, I cannot set deadline alone.

**Comment by murgatroid99** [comment]
OK, it looks like there is an error in the TypeScript definition of `CallOptions`. All of the fields in that interface should be optional.

**Comment by paambaati** [comment]
@murgatroid99 Can I send a PR to fix this?

**Comment by murgatroid99** [comment]
Yes, that would be very helpful.

**Comment by paambaati** [comment]
@murgatroid99 https://github.com/grpc/grpc-node/pull/1030 ready for review.
