### ISSUE TITLE
[QUESTION] How to set the stream chunk size?

### ISSUE THREAD

**Issue by poppinlp** [grpc/grpc-node#509]
Hi. I try to set the stream chunk size between grpc connection. I find this [grpc arg keys](https://grpc.io/grpc/cpp/group__grpc__arg__keys.html) and tried some args but failed.
Could anyone help me or give me some clues? Really thanks.

**Comment by nicolasnoble** [comment]
That's not a knob we're offering, I'm afraid.

**Comment by poppinlp** [comment]
@nicolasnoble  OK. Thanks.
I asked this question because i always get all data in one `data` event from a stream gRPC response and i wanna test my code for multiple chunk case.
Could you please give me any guide? Thanks.

**Comment by poppinlp** [comment]
@nicolasnoble OK, thanks.
And one more question please. If i write a message to a stream response, will i always get it in one `data` event no matter the size of that message?

**Comment by nicolasnoble** [comment]
Yes, we will always reconstruct whole messages for you.

**Comment by poppinlp** [comment]
OK. Thanks a lot. :)
