### ISSUE TITLE
Question: How does the client make the TCP request under the hood in code?

### ISSUE THREAD

**Issue by hvent90** [grpc/grpc-node#521]
Hi all,

To fulfill a curiosity of mine, I'd like to read the source code on how the client actually makes the TCP request. I am wondering what kind of native functions (JS? C++? If C++, how does C++ make itself available to JS?) are eventually used, because all I have ever used are AJAX requests on the client or Node's HTTP requests on the server. From my understanding, gRCP does not make requests over HTTP.

Can someone point me to the code where the TCP requests are made? I've done a bit of looking but haven't made sense of it.

Cheers,
Henry

**Comment by murgatroid99** [comment]
There are several layers in between the surface API that you see and the actual TCP requests. The Node surface API is defined primarily in the [src directory](https://github.com/grpc/grpc-node/tree/master/packages/grpc-native-core/src). That code interfaces with a C++ library defined in the [ext directory](https://github.com/grpc/grpc-node/tree/master/packages/grpc-native-core/ext). The primary parts of that library that are involved with the network are the `Call`, `Channel`, and `Server` classes.

That C++ library is for the most part a thin wrapper around the [gRPC core library](https://github.com/grpc/grpc), which has an interface defined in [these header files](https://github.com/grpc/grpc/tree/master/include/grpc). Broadly speaking, the core translates call, channel, and server related API calls to HTTP/2 messages, which are then sent over TCP by some platform-specific code. The Node library uses [this TCP code](https://github.com/grpc/grpc/blob/master/src/core/lib/iomgr/tcp_uv.cc), which uses [libuv](http://docs.libuv.org/en/v1.x/api.html) to use Node's own event loop for network operations.
