### ISSUE TITLE
Does the nodejs client have load balancing function?

### ISSUE THREAD

**Issue by fuguohong** [grpc/grpc-node#526]
i did not see any  docs or examples about nodejs lb.
I am a grpc novice, please help me, thanks

**Comment by xizhibei** [comment]
It seems that it has not been implemented yet: https://groups.google.com/forum/#!topic/grpc-io/Uaq3K3TDDjU , and you can take a look at my blog (in Chinese) for detail: https://github.com/xizhibei/blog/issues/84

**Comment by k359792067** [comment]
Is there any way to resolve it now?

**Comment by murgatroid99** [comment]
The `@grpc/grpc-js` package supports the "pick first" and "round robin" load balancing policies. In addition, the `@grpc/grpc-js-xds` package adds support for retrieving service mesh configuration including load balancing from an xDS-based service mesh orchestrator.
