### ISSUE TITLE
grpc node doesn't allow more than 4 meta data headers

### ISSUE THREAD

**Issue by chandradeepak** [grpc/grpc-node#539]
### Problem description

When we are sending metadata headers we can't send more than 4 meta data headers. We get this exception. Any suggestion what we should do to fix it ? 

`E0909
 23:32:31.360357000 140736659739584 client_auth_filter.cc:105]    assertion failed: calld->md_array.size <= MAX_CREDENTIALS_METADATA_COUNT
Abort trap: 6
`

### Reproduction steps

1) create a client 
2) add 5 metadata headers while opening a stream. 
3) it fails with above exception. 

### Environment
 - OS name, version and architecture: [e.g. Linux Ubuntu 18.04 amd64]
MAC, amd64
 - Node version [e.g. 8.10.0]
v10.5.0

**Comment by nicolasnoble** [comment]
The failure you're describing is about metadata credentials... which shouldn't be impact with typical metadata. What are you trying to do exactly?

**Comment by chandradeepak** [comment]
@nicolasnoble , 
Thanks for looking in to it.

we had a streaming service written. we tried sending multiple headers when trying to open a stream.  It fails with above error when this happens.

When send 
1) a tenant id 
2) oauth token
3) and few other meta data headers before opening the stream with required options so that we can configure the service appropriately. 
Our service is working . since we are able to open stream with more than 4 meta data headers using java and go. While using node we are getting this error. Not sure how we can get past that.

**Comment by murgatroid99** [comment]
The error seems to indicate that you are trying to send all of your headers using the credentials interface, specifically `grpc.credentials.createFromMetadataGenerator`. This is not an intended use of that API. For most metadata, you should just pass it directly when starting a request, and you should only use the credentials API for auth metadata. The recommended usage of the credentials API is for things like credentials refresh clients, that you can set up once and then send the most current credentials metadata with each request.

**Comment by nicolasnoble** [comment]
Please share some actual code that exhibits the problem.

**Comment by chandradeepak** [comment]
@nicolasnoble , yeah what you said is true. we are trying to send meta data headers in grpc.credentials.createFromMetadataGenerator and that is where this error happened. 

we are creating stream after this and using getStream. what ever we pass in here we are not receiving any thing on the server side. Is there any another place or a different way to pass metadata headers in node. Sorry i am new to node so still trying to figure things out. 

` /**
     * Create a subscription and get the raw stream.
     * @return {ReadableStream} the raw stream of events.
     */
    get stream() {
        // Create a new subscription and return the raw stream
        const metadata = new grpc.Metadata();
        console.log('this.name :: ', this.name);
        metadata.add('metadata1', "true");
        metadata.add('metadata2', "true")
        metadata.add('metadata3', this.name);
        metadata.add('metadata4', "true");
        metadata.add("metadata5", "30s")
        metadata.add("metadata6", "3")
        const creds = getCreds(this.uaaUrl, this.clientId, this.clientSecret, this.zoneIdProp, this.zoneId, this.name);
        const client = new eventhub_proto.Subscriber(this.uri, creds);       
        const s = client.receiveWithAcks({
            zone_id: this.zoneId,
            subscriber: this.name,
            instance_id: this.instance
        }, metadata);
        s.on('close', () => {
            console.log('Subscribe stream closed');
            clearInterval(hc);
        });
        s.on('end', () => {
            console.log('Subscribe stream ended');
            clearInterval(hc);
        });
        return s;
    }`

**Comment by nicolasnoble** [comment]
I'm a bit dumbfounded, as the first code snippet is supposed to work. I don't know why you'd get metadata on the second block and not the first one.

**Comment by chandradeepak** [comment]
Yeah, but if u see in the first block i am calling getCreds which is getting the oauth token and fill some metadata. what ever metadata i pass from there works. 

then when we call 

` const s = client.receiveWithAcks({
            zone_id: this.zoneId,
            subscriber: this.name,
            instance_id: this.instance
        }, metadata);`

I expected it would send the next meta data in the call. But it didn't . None of this reached server at all . So though we are doing some thing wrong. So we added additional metadata in createUaaBearerTokenCredentials which is  metadata.add("metadata5", "300s") and as soon as i put that it immediately fails with the exception i pasted first.

So not sure what we are doing wrong?

**Comment by nicolasnoble** [comment]
As we've said multiple times, please do not use the credentials generator, that's not how this works. You need to attach metadata to the call itself without this trick.

Here's a complete example: [metadata-example.zip](https://github.com/grpc/grpc-node/files/2369340/metadata-example.zip)

Its output should be what you'd expect, really:

![image](https://user-images.githubusercontent.com/7281574/45338841-20f30080-b544-11e8-86e3-b404562ad1f4.png)


Please try it out, and if it doesn't work, give us a complete reproduction case.

**Comment by chandradeepak** [comment]
@nicolasnoble , Thanks very much nicolas for being patient and taking time to write a sample. I will try it out and let you know.  I will close the issue now. If it still fails i will make a working sample to reproduce and post it here.

**Comment by Saad9768** [comment]
@nicolasnoble 
Please find this error which I am also facing.
E0911 11:32:08.086000000 10280 client_auth_filter.cc:105] assertion failed: calld->md_array.size <= MAX_CREDENTIALS_METADATA_COUNT
I have tried your code as well, but still unlucky 
![image](https://user-images.githubusercontent.com/15965748/45341137-16be1a00-b5b7-11e8-96c4-350deafea043.png)

**Comment by nicolasnoble** [comment]
This comment doesn't make sense. The generator is a call credential. It'll be invoked to generate auth metadata on every call made on this channel.

Moreover, metadata are always sent on every call. That's how the protocol works.

**Comment by Saad9768** [comment]
Basically this field should go at the time of connection

**Comment by nicolasnoble** [comment]
That's not a thing with grpc.

**Comment by chandradeepak** [comment]
@nicolasnoble 
I found the issue in our code. The problem is we are using a bi-directional stream. In that since we don't have a request or a response but every thing is sent in streams. 

So the solution is  ( send metadata as first arugment). 

`   Create a subscription and get the raw stream.
      @return {ReadableStream} the raw stream of events.
   
    get stream() {
        // Create a new subscription and return the raw stream
        const metadata = new grpc.Metadata();
        console.log('this.name :: ', this.name);
        metadata.add('metadata1', "true");
        metadata.add('metadata2', "true")
        metadata.add('metadata3', this.name);
        metadata.add('metadata4', "true");
        metadata.add("metadata5", "30s")
        metadata.add("metadata6", "3")
        const creds = getCreds(this.uaaUrl, this.clientId, this.clientSecret, this.zoneIdProp, this.zoneId, this.name);
        const client = new eventhub_proto.Subscriber(this.uri, creds);     

  
       //  use metadata as first argument . this works
         const s = client.receiveWithAcks(metadata);

       //  this doesn't work
      //   const s = client.receiveWithAcks({
      //     zone_id: this.zoneId,
      //         subscriber: this.name,
      //        instance_id: this.instance
     //   }, metadata);
       s.on('close', () => {
            console.log('Subscribe stream closed');
            clearInterval(hc);
        });
        s.on('end', () => {
            console.log('Subscribe stream ended');
            clearInterval(hc);
        });
        return s;
    }`

Otherwise it gets replaced in the first code block where is overrides it. 

`Client.prototype.makeBidiStreamRequest = function(path, serialize,
                                                  deserialize, metadata,
                                                  options) {
  if (!(metadata instanceof Metadata)) {
    options = metadata;
    metadata = new Metadata();
  }
`

**Comment by nicolasnoble** [comment]
@chandradeepak good to hear :-) yes, bi-directional streams's call signatures doesn't have the same sort of arguments. Maybe we could harden this a bit more... although typescript here would help.

**Comment by chandradeepak** [comment]
@nicolasnoble  what is a typescript and how it would help here.

**Comment by nicolasnoble** [comment]
Typescript is a variation of javascript made by Microsoft. Basically, it's javascript with types. We don't support it fully yet, so in this specific instance, it wouldn't have helped, but if your "client.receiveWithAcks" method call was properly typed, you'd have gotten an error when trying to use it with the wrong set of parameters.
