### ISSUE TITLE
node-grpc throwing exception when loading extension

### ISSUE THREAD

**Issue by DanielBaulig** [grpc/grpc-node#544]
### Problem description
I am trying to install and run assistant-relay a Node application which uses grpc-node. I compiled grpc from source as part of installing the npm module. When the application tries to load the grpc extension, it apparently throws an exception. Here's a paste with the error:
https://pastebin.com/G57EY984

Here's the compiled grpc_node.node:
https://filebin.net/y7jt6ywj31wft21o

### Reproduction steps
Download assistant-relay and extract
Run CC=gcc npm install
Run npm run start

Note: the failure is likely related to my environment.

### Environment
 - Synology NAS armv7l GNU/Linux synology_armada38x_rs816
 - Node v8.9.4
 - Node installation method: Synology Package Manager
 - gcc (OpenWrt GCC 6.3.0) 6.3.0 (installed through Entware for armv7)

**Comment by nicolasnoble** [comment]
When you said you compiled from source, does it mean you did an `npm install --build-from-source` ? You put into your reproduction steps you simply did an npm install, so I'm not sure about what you've done exactly.

**Comment by DanielBaulig** [comment]
No, I didn’t explicitly provide the flag, but it ends up compiling from source because it fails to find a prebuilt extension. The HTTP request fails with a 403 and it falls back to building from source.

I can provide a full build output tonight. 
I can also try to explicitly build from source using the flag to see if that changes anything.

**Comment by nicolasnoble** [comment]
I'm surprised it didn't manage to install from our prebuilt binaries, I'd be interested in seeing what's going on here, yes. Also, without being able to reproduce the environment ourselves, troubleshooting why the compiled version didn't work will be difficult. The "internal error" thing is unfortunately fairly unhelpful from node.

We might be able to troubleshoot a bit together however. But I'd first like to see why you didn't manage to get the prebuilt package we have downloaded.

Also I realized you didn't mention which version of grpc you were trying to install. Was it latest ? (aka, 1.15.0)

**Comment by nicolasnoble** [comment]
Going down a bit further, I realized you're talking about "assistant-relay", but I don't find this anywhere on npmjs.

**Comment by DanielBaulig** [comment]
assistant-relay isn't in npm, I was installing it from source using `npm install`. You can get it here: 
https://github.com/greghesp/assistant-relay

I'll make sure to get the full build/install output and any additional information to you asap.

**Comment by nicolasnoble** [comment]
Thanks for that. So digging a bit, the problem is has several layers. This assistant-relay package is depending on google-assistant^0.2.0, which means you're picking up google-assistant@0.2.2. This version has a hard dependency on grpc@1.8.0, no caret or anything. The latest versions of google-assistant (0.5.x) now depends on grpc^1.12.1, which means that you'd get 1.15.0 by installing it, but right now, that's not the case.

We can't really help with such an old version of grpc (1.8.0), unfortunately. Unless assistant-relay updates to google-assistant 0.5.x, there's not much we can do on our end.

**Comment by DanielBaulig** [comment]
So, I tried increasing the version of google-assistant in the package json to 0.5.x to see how much if anything at all would break. But if I run `npm install` the compilation of grpc now fails with an error.

This is the output of `CC=gcc npm install`:
https://pastebin.com/73n4MuJt

I reran the install while also installing nan (`CC=gcc npm install nan`) and that seemed to have fixed the compilation error. This may be an actual bug in the grpc package, which should probably bring in `nan` when building from source.

The download of the grpc binary failed with a 404, I assume because the constructed URL is not matching a known platform.

    https://node-precompiled-binaries.grpc.io/grpc/v1.15.1/node-v57-linux-arm-unknown.tar.gz

 The `unknown` string at the end of the URL is suspicious to me. Not sure what information should be encoded there and if just fixing and downloading an ARM build of grpc would work for me.

However, even with the freshly built grpc (version 5.6.0), I still get the internal error, when trying to run assistant-relay:

https://pastebin.com/4z2VWPFy

:(

**Comment by murgatroid99** [comment]
I want to add that the grpc library does have a dependency on nan, and you are not getting an error indicating that the header could not be loaded. Rather, it seems likely that there is some incompatibility between the nan headers that we depend on and the Node development headers that you have.

**Comment by murgatroid99** [comment]
The `grpc` package is now deprecated. I don't expect that we will make any changes to address this problem. We recommend switching to `@grpc/grpc-js`.
