### ISSUE TITLE
Version mismatch error when loading gRPC in Electron

### ISSUE THREAD

**Issue by nikolovp** [grpc/grpc-node#565]
### Problem description
I am new to gRPC and I am trying to load the node binding in an Electron process but all I get is this error:

```
Error: Failed to load gRPC binary module because it was not installed for the current system
Expected directory: node-v64-win32-x64-unknown
Found: [electron-v3.0-win32-x64-unknown]
This problem can often be fixed by running "npm rebuild" on the current system
Original error: Cannot find module '<app>\node_modules\grpc\src\node\extension_binary\node-v64-win32-x64-unknown\grpc_node.node'
    at Object.<anonymous> (<app>\node_modules\grpc\src\grpc_extension.js:53:17)
    at Object.<anonymous> (<app>\node_modules\grpc\src\grpc_extension.js:63:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (<app>\node_modules\grpc\src\client_interceptors.js:145:12)
```

### Environment
 - Windows 10 - x64
 - Node v8.12.0 - regular installation from .msi
 - npm v6.4.1
 - yarn v1.7.0
 - Electron v3.0.2
 - gRPC@1.15.1

### Additional context
As the additional information hints, I am trying to run gRPC v1.15.1 in Electron v.3.0.2.

Instead of rebuilding all native module after installation I am using build target configuration in a .npmrc file:
```
runtime=electron
target=3.0.2
target_arch=x64
disturl=https://atom.io/download/electron
```
I am usually using `yarn` instead of `npm` but in that case I tried with both and the result was the same.
I am not passing any arguments since all I need is already defined in the .npmrc file.

I also tried to run `npm rebuild grpc` but I get the same error when I load the binding. The output from `npm rebuild` is:
```
> grpc@1.14.2 install<app>\node_modules\grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp WARN Using request for node-pre-gyp https download
[grpc] Success: "<app>\node_modules\grpc\src\node\extension_binary\electron-v3.0-win32-x64-unknown\grpc_node.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile
grpc@1.14.2 <app>\node_modules\grpc
```

I get exactly the same output and error if I manually pass all runtime & target arguments to `npm rebuild.
`npm rebuild gprc --runtime=electron --target=3.0.2 --target_arch=x64 --dist-url=https://atom.io/download/electron`

The content of `grpc\src\node\extension_binary\` is:
 - electron-v3.0-win32-x64-unknown
   - grpc_node.node

The .npmrc configuration should be fine since I am also using few other native modules (some them with pre-built binaries) and they all download/build without errors.

I didn't try to build from source because the initial README says this is quite complex task.

**Comment by nikolovp** [comment]
I just tried to build the binding from source but I got the same error.

`npm rebuild grpc --build-from-source --runtime=electron --target=3.0.2 --target_arch=x64 --dist-url=https://atom.io/download/electron`

Build output: https://gist.github.com/nikolovp/1949641f663d5465626151238eedd4b3

**Comment by nicolasnoble** [comment]
Something doesn't add up in your report. The error says you have the electron grpc module installed, but you are trying to run your project from node 8.

**Comment by murgatroid99** [comment]
Module version 64 is actually Node 10, which interestingly is the version of Node included in Electron 3, not the version of Node installed on their system. I think there is a possibility here that node-pre-gyp is loading modules differently on Electron 3.

**Comment by nikolovp** [comment]
@nicolasnoble is right, I forgot to mention a detail which is most probably causing the issue. The code runs in an electron app for sure but... in a fork of the main Electron process. I didn't debug the process because I didn't manage to spawn it so I have no idea in what environment exactly my code is running.

> Module version 64 is actually Node 10, which interestingly is the version of Node included in Electron 3

I guess forking the electron's main process spawns a node process instead of an electron process. This behaviour is not very well documented in the Electon's doc page.

I cannot debug it at the moment. I will post additional info as soon as I can.

**Comment by nicolasnoble** [comment]
That's still kind of weird. Please definitely share code that exhibits the problem.

**Comment by nicolasnoble** [comment]
Actually, see https://github.com/electron/electron/issues/8727

**Comment by nicolasnoble** [comment]
So the rootcause is https://github.com/mapbox/node-pre-gyp/pull/278 and the fix is pending at https://github.com/mapbox/node-pre-gyp/pull/279

**Comment by murgatroid99** [comment]
It should be possible to fix this without waiting on node-pre-gyp by doing another rebuild to get the binary you need for the fork. I think something like `npm rebuild grpc --target=10` should work.

**Comment by nikolovp** [comment]
@nicolasnoble  Thanks for digging into the issue and for the links. The discussed topics look just like the issue I have.

@murgatroid99 I want to use grpc from a forked process as server and from an electron render process as client and I want to use a single build of grpc on boat sides.

Thank you both for the help. I am closing the issue since it is not really related to the grpc binding.
I will dig further about the possible workarounds and I will write back if I find anything useful.

**Comment by nicolasnoble** [comment]
Well, if you are not trying to fork for CPU reasons, there's no reasons the main electron process can't be a server. The Electron event loop is more than capable of handling this.

**Comment by nikolovp** [comment]
This is the exact reason why I want to run the server on a separate process. I want to run some long-running heavy tasks with an API on top.

I guess I could workaround the issue if I fork the process with disabled ELECTRON_RUN_AS_NODE env var (enabled by default if I understand correctly). In this case I believe I should get a child electron process instead of a node process. There will be most probably some overhead but it should be still better than creating a hidden BrowserWindow.

Hidden BrowserWindow would be my last option. I don't need the electron for this process so I prefer to limit the overhead as much as possible.

I write back when I have a working "solution".
