### ISSUE TITLE
[grpc-health-check] Documentation & problem with published package

### ISSUE THREAD

**Issue by mousavian** [grpc/grpc-node#569]
### Problem description
There is no documentation around how `grpc-health-check` library should be used.
I have tried to use it based on existing test cases, but there is major issue with latest published version `1.6.6`:
The "main" file defined in `package.json` file is `src/node/index.js` [[here](https://github.com/grpc/grpc-node/blob/990f082f0094f32cc9e1d8f272886955e98afc9c/packages/grpc-health-check/package.json#L30)] while there is no such file.
Hence, we can't have `require('grpc-health-check')` because it will throw `Cannot find module 'grpc-health-check'` error. 
It should be used like `require('grpc-health-check/health')`. 

But it can be resolved easily by fixing that line to point to `health.js` and publish it as `1.6.7` or something.

### Reproduction steps
```bash
mkdir /tmp/test && cd /tmp/test
npm init
npm i grpc-health-check@1.6.6
node -e "require('grpc-health-check')"
```
### Environment
 - Any node version / but i've tested on 8.8.1
clang 3.8.0-2ubuntu4]
 - grpc-health-check@1.6.6

### Additional context
I'd be happy to raise PRs to fix that and also add documentation if this is not deprecated or sth.
Also wondering why link to repository in npmjs.com is pointing to https://github.com/grpc/grpc/ 🤔

**Comment by cjihrig** [comment]
@mousavian, I'm not sure how actively maintained `grpc-health-check` is, but fixing the`package.json` `main` entry seems like a simple but worthwhile PR to submit.

**Comment by alexandervain** [comment]
@cjihrig Some of the describe issues seems to be fixed on master (for a while actually - by this commit - https://github.com/grpc/grpc-node/commit/16ad6e14aaacce88145db0a31ad182799d2ba6c8).
Any chance for releasing a new version of `grpc-health-check` containing those changes?

**Comment by cjihrig** [comment]
@alexandervain I don't have any permissions on any grpc repos. You'd have to ask @murgatroid99 and company.

**Comment by iangeckeler** [comment]
@murgatroid99 has this issue been resolved?

**Comment by murgatroid99** [comment]
It looks like this fell off our radar. We have now published a new version of `grpc-health-check`, version 1.7.0.

**Comment by cymarechal** [comment]
@murgatroid99 Great news! Do you know if there is any documentation or examples available?

**Comment by nareddyt** [comment]
I made a PR with the documentation. Would appreciate any feedback :)
