### ISSUE TITLE
Cannot compile TypeScript hello world client/server

### ISSUE THREAD

**Issue by DominicKramer** [grpc/grpc-node#572]
I was following the [quickstart document](https://grpc.io/docs/quickstart/node.html) to implement the hello world client server example in TypeScript.

I can compile and run the code fine if I have `noImplicitAny` set to `false` in `tsconfig.json`.  However, if I have it set to `true`, I get the following error when running `tsc -p .`:
```
node_modules/grpc/index.d.ts:2:55 - error TS7016: Could not find a declaration file for module 'protobufjs'. '.../grpc-example/node_modules/protobufjs/dist/protobuf.js' implicitly has an 'any' type.
  Try `npm install @types/protobufjs` if it exists or add a new declaration (.d.ts) file containing `declare module 'protobufjs';`

2   import { Message, Service as ProtobufService } from "protobufjs";
                                                        ~~~~~~~~~~~~
```
Also, running `npm install @types/protobufjs` does not resolve the issue.

### Environment
 - OS name, version and architecture: OS X Mojave
 - Node version: 8.9.1
 - Node installation method: nvm
 - Package name and version: @grpc/proto-loader@0.3.0, grpc@1.15.1

**Comment by kjin** [comment]
Try: `npm install @types/protobufjs@5.0.31`

**Comment by DominicKramer** [comment]
After using `npm install @types/protobufjs@5.0.31`, compilation reports the following errors:
```
> tsc -p .

node_modules/@grpc/proto-loader/build/src/index.d.ts:42:40 - error TS2694: Namespace 'ProtoBuf' has no exported member 'IParseOptions'.

42 export declare type Options = Protobuf.IParseOptions & Protobuf.IConversionOptions & {
                                          ~~~~~~~~~~~~~


node_modules/@grpc/proto-loader/build/src/index.d.ts:42:65 - error TS2694: Namespace 'ProtoBuf' has no exported member 'IConversionOptions'.

42 export declare type Options = Protobuf.IParseOptions & Protobuf.IConversionOptions & {
                                                                   ~~~~~~~~~~~~~~~~~~


node_modules/@types/protobufjs/index.d.ts:275:16 - error TS2304: Cannot find name 'XMLHttpRequest'.

275         XHR(): XMLHttpRequest;
                   ~~~~~~~~~~~~~~


src/client.ts:19:33 - error TS2339: Property 'Greeter' does not exist on type 'Message | GrpcObject | typeof Client'.
  Property 'Greeter' does not exist on type 'Message'.

19   const client = new helloProto.Greeter('localhost:50051',
                                   ~~~~~~~


src/server.ts:26:32 - error TS2339: Property 'Greeter' does not exist on type 'Message | GrpcObject | typeof Client'.
  Property 'Greeter' does not exist on type 'Message'.

26   server.addService(helloProto.Greeter.service, {
                                  ~~~~~~~
```

**Comment by DominicKramer** [comment]
Based on in person feedback from @kjin, I installed `protobufjs`.  This solved the issue since `protobufjs` includes type definitions.

**Comment by murgatroid99** [comment]
You shouldn't need to have an explicit dependency on protobufjs, and I don't understand why it helps here. The initial error indicates that the protobufjs package is present, but TypeScript is for some reason looking at a `.js` file instead of the `.d.ts` file.

**Comment by tingwai-to** [comment]
@DominicKramer were you able to solve the compile error? The only solution I could come up with was casting `helloProto` to `any`, but then I lose my type checking

**Comment by tatemz** [comment]
Same, I'd love to know the solution for this. I've been stuck in an loop of Google searches. This is the closest setup I have been able to mimic: https://medium.com/attest-engineering/fully-typed-typescript-api-consuming-grpc-and-graphql-5d5ae6b33bf1

**Comment by aconchillo** [comment]
I was also having the same errors so I ended up using the static module approach:

```
$ pbjs -t static-module -w commonjs -o compiled.js file1.proto file2.proto
$ pbts -o compiled.d.ts compiled.js
```

And the simply import `compiled.js`:

```
import { xxx } from 'compiled';
```

where `xxx` is the name of your service.

**Comment by aconchillo** [comment]
Not TypeScript... but I ended up generating static code:

https://github.com/grpc/grpc/tree/master/examples/node/static_codegen

**Comment by jdforsythe** [comment]
@murgatroid99 it appears the typescript definitions aren't available in the 5.x release of protobufjs, which this depends on. The typescript definitions are available in the 6.x releases.

The `proto-loader` package is set to a newer version already:

https://github.com/grpc/grpc-node/blob/073dc563858a2d74bd114e5cc50d02203123078f/packages/proto-loader/package.json#L41-L44

But the `grpc-native-core` is still pegged to an old version:

https://github.com/grpc/grpc-node/blob/10a0472f1e205833a86104a79405d4722ad6af35/packages/grpc-native-core/package.json#L31-L37

Oddly, this comment and object lead me to believe the module was already developed with v6 but that `package.json` just wasn't updated:

https://github.com/grpc/grpc-node/blob/04395a0bc88a64aa67f1c299ad6d1504b6af32bc/packages/grpc-native-core/index.d.ts#L31-L74

**Comment by murgatroid99** [comment]
I did not realize Protobuf.js did not include type definitions. The correct course of action here is probably to include a dependency on `@types/protobufjs@5.x`.

The dependency on Protobuf.js version 5 is deliberate. Bumping the dependency to version 6 would cause breaking changes in gRPC itself. This is part of why `@grpc/proto-loader` exists: to make that upgrade without breaking anything.

**Comment by jdforsythe** [comment]
@murgatroid99 like this? https://github.com/grpc/grpc-node/pull/828

**Comment by murgatroid99** [comment]
Yes. I don't know if that will solve the whole problem, but I think that's probably a good idea.

**Comment by jdforsythe** [comment]
It seems to fix the above issue in my local test, but there are other issues.

Since `@grpc/proto-loader` is on v6 of `protobufjs`, the types aren't aligned and there are type errors related to that (e.g. `Type 'Message' is not generic` and `Namespace ... has no exported member 'IParseOptions'`).

Unfortunately the native package will probably have to be updated or we'll have to stick to old versions to use it with Typescript.

**Comment by murgatroid99** [comment]
That's going to be tricky to reconcile. There is an inherent ambiguity in importing `protobufjs` and wanting to get the actual type information from one version of the `@types/protobufjs` package instead of a different version of the `protobufjs` package. And the fact is that we can't change either of those versions.

**Comment by pelhage** [comment]
Any progress here? Seems like most developers who would be using gRPC are also highly likely to be using Typescript as well

**Comment by murgatroid99** [comment]
I have a possible fix in #1008

**Comment by murgatroid99** [comment]
I have published version 1.23.3 with that fix. Please try it and see if it helps.

**Comment by simegeorge** [comment]
This fix in 1.23.3 works for me but has been undone in 1.23.4 it seems ?

**Comment by murgatroid99** [comment]
I don't see that dependency in 1.23.4.

**Comment by simegeorge** [comment]
Sorry my mistake, I meant 1.24.0 - the fix is only in 1.23.3 and 1.23.4 and using 1.24.0 results in the error posted originally

**Comment by murgatroid99** [comment]
I don't see that dependency on 1.24.0 either.

**Comment by simegeorge** [comment]
Strange, I see the `import {...} from "protobufjs"` (that causes the error) back in 1.24.0 as shown by

`wget -qO - $(npm view grpc@1.24.0 dist.tarball) | tar xzO package/index.d.ts | grep import`

whereas in 1.23.4 (and 1.23.3) it is not there

`wget -qO - $(npm view grpc@1.23.4 dist.tarball) | tar xzO package/index.d.ts | grep import`

Am I missing something ?  Thanks :)

**Comment by murgatroid99** [comment]
No, you're right. I was looking for the wrong thing. I guess that fix didn't make it into the 1.24 branch. I'll get a fix for that out soon.

**Comment by simegeorge** [comment]
Great, thanks :)

**Comment by murgatroid99** [comment]
Version 1.24.1 is out with that fix.

**Comment by simegeorge** [comment]
Ok, many thanks !

**Comment by rodoufu** [comment]
> Version 1.24.1 is out with that fix.

I'm still facing that with the following dependencies:
```js
"dependencies": {
    "@grpc/proto-loader": "^0.5.5",
    "@types/express": "^4.17.9",
    "@types/protobufjs": "^6.0.0",
    "google-protobuf": "^3.14.0",
    "grpc": "^1.24.4"
  }
```

**Comment by murgatroid99** [comment]
You explicitly added a dependency on `@types/protobuf.js` version 6.x. Since `grpc` depends on `protobufjs` version 5.x as mentioned previously in this issue, that is probably creating a compatibility problem.

**Comment by rodoufu** [comment]
> You explicitly added a dependency on `@types/protobuf.js` version 6.x. Since `grpc` depends on `protobufjs` version 5.x as mentioned previously in this issue, that is probably creating a compatibility problem.

Thanks

**Comment by Choongkyu** [comment]
hello. I'm able to compile the server but not the hello world client as I'm getting this error:
```
Property 'Greeter' does not exist on type 'ProtobufTypeDefinition | GrpcObject | ServiceClientConstructor'.
  Property 'Greeter' does not exist on type 'ProtobufTypeDefinition'.ts(2339)
```

**Comment by rafaelargenta-quanto** [comment]
Same problem here.

**Comment by swaastick-nestaway** [comment]
Guys any fix for what @Choongkyu said

**Comment by collinspeight** [comment]
I know this thread is pretty stale, but just to add my solution for @Choongkyu's issue: try using the `any` keyword like so:  
```TypeScript
const hello_proto: any = grpc.loadPackageDefinition(packageDefinition).helloworld;
```  
The type of the object returned from loadPackageDefinition isn't known until runtime when using `proto-loader`, so I had to use `any` to make TypeScript happy. Creating a service object and beyond should work as it does in the example after this change.
