### ISSUE TITLE
proto-loader incompatible with proto annotations

### ISSUE THREAD

**Issue by alephnan** [grpc/grpc-node#583]
index.js

```
var grpc = require("grpc"), protoLoader = require("@grpc/proto-loader");

var packageDefinition = protoLoader.loadSync("service.proto", {});
console.log('Service: ' + grpc.loadPackageDefinition(packageDefinition).foo.Service);
```

service.proto
```
syntax = "proto3"; package foo; import "response.proto";

message Request{}
service Service {
  rpc Get(Request) returns (Response) {}
}
```

resource.proto
```
syntax = "proto3"; package foo;

message Response {
  // If the following declaration is un-commented
  // @grpc/proto-loader will complain about 'type Person not found'.
  // string name = 1 [
  //   (common.Field.annotation) = {
  //     filterable: true;
  //   }
  // ];
}
```
This is the stacktrace when running `node index.js` with the `name` field in Response message uncommented:
```
../node_modules/protobufjs/src/namespace.js:382
        throw Error("no such type: " + path);
        ^

Error: no such type: Response
    at Service.lookupType (.../node_modules/protobufjs/src/namespace.js:382:15)
    at Method.resolve (.../node_modules/protobufjs/src/method.js:148:45)
    at Service.resolveAll (../node_modules/protobufjs/src/service.js:111:20)
    at Namespace.resolveAll(../node_modules/protobufjs/src/namespace.js:307:25)
    at Root.resolveAll (../node_modules/protobufjs/src/namespace.js:307:25)
    at Root.resolveAll (../node_modules/protobufjs/src/root.js:246:43)
    at Object.loadSync (../node_modules/@grpc/proto-loader/build/src/index.js:153:16)
    at Object.<anonymous> (spec/tmp/index.js:7:39)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
````

Some more characteristics of the issue:
- when importing / depending on a proto file containing annotations, the complaint will be "type X not found", where X is the type in the imported proto file
- if the annotation is in the resident proto file, ie: if the Response message was defined in service.proto, we get a more helpful error "illegal name ';'" pointing to the line number of the annotation
- the parser is happy when removing the ";" inside the annotation. Unfortunately, this workaround is not feasible when we have multiple configurations inside our annotation.

Workaround:
```
message Response {
   string name = 1 [
     (common.Field.annotation) = {
       filterable: true // removed semi colon
     }
  ];
}
```
I'm unsure if the workaround is feasible for the case with multiple configurations for the annotation
```
message Response {
   string name = 1 [
     (common.Field.annotation) = {
       filterable: true
       sortable: true
    }
  ];
}
```

**Comment by murgatroid99** [comment]
This part of the proto-loader functionality is handled by the Protobuf.js library (https://github.com/dcodeIO/protobuf.js). I suggest filing an issue there.

**Comment by ChrisFichman** [comment]
Quick note - its not valid syntax to have empty curly or square braces. There needs to be something, or the whole class has to be commented.
