### ISSUE TITLE
Execute tests on Node.js 11 in CI

### ISSUE THREAD

**Issue by kibertoad** [grpc/grpc-node#585]
Currently it is unclear whether grpc-node actually supports Node.js 11; tests in CI would clarify that.

**Comment by sangaman** [comment]
I'm unable to install grpc-node in travis builds using Node 11, so it would be good to know whether it's supported  or whether there's something wrong with the build.

**Comment by nicolasnoble** [comment]
grpc depends on node-pre-gyp for its binary releases and builds, and node 11 support depends on node-pre-gyp node 11 support. Follow #593 for node 11 integration, which is blocked on node-pre-gyp.

**Comment by julien-c** [comment]
If this is happening at every node release (which it is, in my experience), maybe a good idea would be to test upcoming releases in advance?

**Comment by nicolasnoble** [comment]
This isn't about us being proactive. This is about our dependency having to update their code so we can even do testing.

**Comment by julien-c** [comment]
Got it (did not mean to sound abrasive too)
