### ISSUE TITLE
Unable to catch client streaming errors during parsing until the stream ends.

### ISSUE THREAD

**Issue by michael-donat** [grpc/grpc-node#595]
### Problem description

During development we've introduced some Proto incompatibility resulting in the go-lang server running a newer, incompatible service definition comparing to our node client.

The call in questions is a client streaming call.

When receiving a message from the server, the deserialisation fails with `Failed to parse server response` but the error is never emitted on the error handler.

I tracked it down to the following code:

```
/**
 * If we have both processed all incoming messages and received the status from
 * the server, emit the status. Otherwise, do nothing.
 * @private
 */
function _emitStatusIfDone() {

  /* jshint validthis: true */
  var status;
  if (this.read_status && this.received_status) {
    if (this.read_status.code !== constants.status.OK) {
      status = this.read_status;
    } else {
      status = this.received_status;
    }
    if (status.code === constants.status.OK) {
      this.push(null);
    } else {
      var error = common.createStatusError(status);
      this.emit('error', error);
    }
    this.emit('status', status);
  }
}
```

The problem is that the `  if (this.read_status && this.received_status) {` never passes, as far as the server side is concerned, the stream is alive so `this.received_status` is never set.

Once the stream is ended/cancelled the error is emitted correctly, but before this happens we end up with a stream in limbo, unable to report error and unable to receive further messages.

Dumping the stream after the invalid message results in following:

```
   next_call: InterceptingCall { next_call: null, requester: [Object] },
     requester: undefined },
  finished: true,
  reading: true,
  read_status: { code: 13, details: 'Failed to parse server response' },
  received_status: null }
```

It is `finished`, but it's still `reading`, `read_status` is set but not `received_status`.

Am I missing something here? Is there any way to check for read status externally (I realise I could just monitor the prop in a sub routine).

**Comment by murgatroid99** [comment]
Thank you for giving so much detail here. The call is definitely supposed to end when it does that.

The trick is that when `read_status` is set, we also call `cancelWithStatus`, which should result in `received_status` getting set and `_emitStatusIfDone` getting called again. I don't know why that's not happening here. That `InterceptingCall` with `next_call: null` looks possibly wrong to me. Are you doing anything with call interceptors?

**Comment by michael-donat** [comment]
@murgatroid99 no interceptors our side, it’s a pretty straight setup.

I tried providing a minimal repro example but it’s more difficult than I though to trigger the parsing error ;)
