### ISSUE TITLE
Update @grpc/proto-loader to require protobufjs ^6.8.7 

### ISSUE THREAD

**Issue by mhoeger** [grpc/grpc-node#600]
### Problem description
There is still a TypeScript compilation error when using the latest `grpc` and `@grpc/proto-loader` pacakges (`error TS2314: Generic type 'Message<T>' requires 1 type argument(s)`). The solution proposed in https://github.com/grpc/grpc-node/issues/425 was to make Message<T> have a default type param in protobuf.js. However, this was released in 6.8.7 and `@grpc/proto-loader` requires "^6.8.6" ([here](https://github.com/grpc/grpc-node/blob/master/packages/grpc-protobufjs/package.json)). It would be nice to update the minimum required protobufjs to avoid this issue altogether.

**Comment by murgatroid99** [comment]
That original error did not actually involve `@grpc/proto-loader` at all. Instead, that user was directly using Protobuf.js with gRPC using `grpc.loadObject`.

Are you experiencing a similar error using `@grpc/proto-loader` and `grpc`? If so, can you share a reproduction case? That may be a symptom of a different problem.

**Comment by mhoeger** [comment]
Hi @murgatroid99 - thanks for the reply! My project is currently using Protobuf.js directly with gRPC (using `grpc.loadObject`).

This might be a misunderstanding on my part, but I was playing around with moving towards `@grpc/proto-loader` and ran into the infamous `Message<T>` error. That's when I noticed that the dependency that `@grpc/proto-loader` takes on `protobufjs` is `^6.8.6`.

It's by no means a blocker and maybe not even a valid scenario, but when protobufjs 6.8.6 was installed along with `@grpc/proto-loader`, per default minimum dependency requirement, I saw that error again. Opened this issue wondering if the minimum dependency taken should be 6.8.7.

**Comment by murgatroid99** [comment]
OK, I see. I generally wouldn't put a high priority on dependency changes like that because `^6.8.6` will currently resolve to `6.8.7` anyway, though I do understand that in some cases it can still help. In addition, in this particular case that type issue shouldn't happen with `@grpc/proto-loader` itself, unless there is some other bug. That is why I would like to see how exactly you started encountering this error after you added the dependency on `@grpc/proto-loader`.

**Comment by murgatroid99** [comment]
The latest version of `@grpc/proto-loader` depends on `protobufjs` version `^7.2.4`.
