### ISSUE TITLE
When a client cannot connect to a gRPC service it first gets UNAVAILABLE, but subsequent calls timeout with a DEADLINE_EXCEEDED

### ISSUE THREAD

**Issue by wdittmer** [grpc/grpc-node#601]
### Problem description
NodeJS client A needs to call NodeJS service B via gRPC. If we do not start service B, client A will report 'UNAVAILABLE' for the first call quite fast ~2 ms.. The next calls result in a DEADLINE_EXCEEDED after the configured deadline (e.g. 5 seconds). I would expect that UNAVAILABLE kept being returned. The DEADLINE_EXCEEDED makes it seem that the service is up, but taking more time than the deadline.

### Reproduction steps
I imagine this is very easily reproduce-able (e.g. the hello-world client should also show this). If not, I will make the effort to create a grpcClient to demonstrate this.

### Environment
 - Darwin 18.0.0 Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT 2018; root:xnu-4903.201.2~1/RELEASE_X86_64 x86_64
 - Node version: v8.12.0
 - Node installation method: npm
 - Package name and version:     "grpc": "^1.14.1"

### Additional context
Client A tries every minute to reach out to Service B.
At first Service B is not started and we see first UNAVAILABLE, then DEADLINE_EXCEEDED.
Then after a while service B is started and a connection is made (but a business error is returned)
Then the service B is stopped again and we see first UNAVAILABLE and then DEADLINE_EXCEEDED.
Our deadline is set to 5 seconds.

Logging:

> > cbo-recording-scheduler-service@1.2.0-SNAPSHOT start-local /Users/wilfreddittmer/cbo-recording-scheduler-service
> > REDIS_USE_LOCAL=true DYNAMODB_USE_LOCAL=true node app.js
> 
> (node:14764) DeprecationWarning: grpc.load: Use the @grpc/proto-loader module with grpc.loadPackageDefinition instead
> {"@timestamp":"2018-10-30T14:10:17.869Z","app_version":"1.2.0-SNAPSHOT","app_name":"cbo-recording-scheduler-service","level":"info","message":"Prometheus endpoint registered on /prometheus"}
> {"@timestamp":"2018-10-30T14:10:17.869Z","app_version":"1.2.0-SNAPSHOT","app_name":"cbo-recording-scheduler-service","level":"info","message":"Health endpoint registered on /health"}
> {"@timestamp":"2018-10-30T14:10:17.870Z","app_version":"1.2.0-SNAPSHOT","app_name":"cbo-recording-scheduler-service","level":"info","message":"HTTP Recording Scheduler Service started on port 8201"}
> {"@timestamp":"2018-10-30T14:11:17.864Z","app_version":"1.2.0-SNAPSHOT","app_name":"cbo-recording-scheduler-service","level":"info","message":"There are '1' events to record"}
> {"@timestamp":"2018-10-30T14:11:17.876Z","app_version":"1.2.0-SNAPSHOT","app_name":"cbo-recording-scheduler-service","level":"warn","message":"Error in Archive Service archiveEvent: 14 UNAVAILABLE: Connect Failed"}
> {"@timestamp":"2018-10-30T14:11:17.876Z","app_version":"1.2.0-SNAPSHOT","app_name":"cbo-recording-scheduler-service","level":"warn","message":"Unable to archive to be recorded event 'event2', retrying next time"}
> {"@timestamp":"2018-10-30T14:11:17.877Z","app_version":"1.2.0-SNAPSHOT","app_name":"cbo-recording-scheduler-service","level":"debug","message":"All to be recorded events processed"}
> {"@timestamp":"2018-10-30T14:12:17.879Z","app_version":"1.2.0-SNAPSHOT","app_name":"cbo-recording-scheduler-service","level":"info","message":"There are '1' events to record"}
> {"@timestamp":"2018-10-30T14:12:22.884Z","app_version":"1.2.0-SNAPSHOT","app_name":"cbo-recording-scheduler-service","level":"warn","message":"Error in Archive Service archiveEvent: 4 DEADLINE_EXCEEDED: Deadline Exceeded"}
> {"@timestamp":"2018-10-30T14:12:22.885Z","app_version":"1.2.0-SNAPSHOT","app_name":"cbo-recording-scheduler-service","level":"warn","message":"Unable to archive to be recorded event 'event2', retrying next time"}
> {"@timestamp":"2018-10-30T14:12:22.885Z","app_version":"1.2.0-SNAPSHOT","app_name":"cbo-recording-scheduler-service","level":"debug","message":"All to be recorded events processed"}
> {"@timestamp":"2018-10-30T14:13:17.862Z","app_version":"1.2.0-SNAPSHOT","app_name":"cbo-recording-scheduler-service","level":"info","message":"There are '1' events to record"}
> {"@timestamp":"2018-10-30T14:13:22.871Z","app_version":"1.2.0-SNAPSHOT","app_name":"cbo-recording-scheduler-service","level":"warn","message":"Error in Archive Service archiveEvent: 4 DEADLINE_EXCEEDED: Deadline Exceeded"}
> {"@timestamp":"2018-10-30T14:13:22.872Z","app_version":"1.2.0-SNAPSHOT","app_name":"cbo-recording-scheduler-service","level":"warn","message":"Unable to archive to be recorded event 'event2', retrying next time"}
> {"@timestamp":"2018-10-30T14:13:22.872Z","app_version":"1.2.0-SNAPSHOT","app_name":"cbo-recording-scheduler-service","level":"debug","message":"All to be recorded events processed"}
> {"@timestamp":"2018-10-30T14:14:17.863Z","app_version":"1.2.0-SNAPSHOT","app_name":"cbo-recording-scheduler-service","level":"info","message":"There are '1' events to record"}
> {"@timestamp":"2018-10-30T14:14:22.868Z","app_version":"1.2.0-SNAPSHOT","app_name":"cbo-recording-scheduler-service","level":"warn","message":"Error in Archive Service archiveEvent: 4 DEADLINE_EXCEEDED: Deadline Exceeded"}
> {"@timestamp":"2018-10-30T14:14:22.868Z","app_version":"1.2.0-SNAPSHOT","app_name":"cbo-recording-scheduler-service","level":"warn","message":"Unable to archive to be recorded event 'event2', retrying next time"}
> {"@timestamp":"2018-10-30T14:14:22.869Z","app_version":"1.2.0-SNAPSHOT","app_name":"cbo-recording-scheduler-service","level":"debug","message":"All to be recorded events processed"}
> {"@timestamp":"2018-10-30T14:15:17.870Z","app_version":"1.2.0-SNAPSHOT","app_name":"cbo-recording-scheduler-service","level":"info","message":"There are '1' events to record"}
> {"@timestamp":"2018-10-30T14:15:22.876Z","app_version":"1.2.0-SNAPSHOT","app_name":"cbo-recording-scheduler-service","level":"warn","message":"Error in Archive Service archiveEvent: 4 DEADLINE_EXCEEDED: Deadline Exceeded"}
> {"@timestamp":"2018-10-30T14:15:22.876Z","app_version":"1.2.0-SNAPSHOT","app_name":"cbo-recording-scheduler-service","level":"warn","message":"Unable to archive to be recorded event 'event2', retrying next time"}
> {"@timestamp":"2018-10-30T14:15:22.877Z","app_version":"1.2.0-SNAPSHOT","app_name":"cbo-recording-scheduler-service","level":"debug","message":"All to be recorded events processed"}
> {"@timestamp":"2018-10-30T14:25:17.888Z","app_version":"1.2.0-SNAPSHOT","app_name":"cbo-recording-scheduler-service","level":"info","message":"There are '1' events to record"}
> {"@timestamp":"2018-10-30T14:25:22.895Z","app_version":"1.2.0-SNAPSHOT","app_name":"cbo-recording-scheduler-service","level":"warn","message":"Error in Archive Service archiveEvent: 4 DEADLINE_EXCEEDED: Deadline Exceeded"}
> {"@timestamp":"2018-10-30T14:25:22.895Z","app_version":"1.2.0-SNAPSHOT","app_name":"cbo-recording-scheduler-service","level":"warn","message":"Unable to archive to be recorded event 'event2', retrying next time"}
> {"@timestamp":"2018-10-30T14:25:22.895Z","app_version":"1.2.0-SNAPSHOT","app_name":"cbo-recording-scheduler-service","level":"debug","message":"All to be recorded events processed"}
> 
> --> start the service
> 
> {"@timestamp":"2018-10-30T14:26:17.892Z","app_version":"1.2.0-SNAPSHOT","app_name":"cbo-recording-scheduler-service","level":"info","message":"There are '1' events to record"}
> {"@timestamp":"2018-10-30T14:26:17.906Z","app_version":"1.2.0-SNAPSHOT","app_name":"cbo-recording-scheduler-service","level":"warn","message":"Error received from archive service, state = 'CHANNEL_NOT_FOUND'"}
> {"@timestamp":"2018-10-30T14:26:17.906Z","app_version":"1.2.0-SNAPSHOT","app_name":"cbo-recording-scheduler-service","level":"warn","message":"Unable to archive to be recorded event 'event2', retrying next time"}
> {"@timestamp":"2018-10-30T14:26:17.906Z","app_version":"1.2.0-SNAPSHOT","app_name":"cbo-recording-scheduler-service","level":"debug","message":"All to be recorded events processed"}
> 
> --> stop the service 
> 
> {"@timestamp":"2018-10-30T14:27:17.893Z","app_version":"1.2.0-SNAPSHOT","app_name":"cbo-recording-scheduler-service","level":"info","message":"There are '1' events to record"}
> {"@timestamp":"2018-10-30T14:27:17.895Z","app_version":"1.2.0-SNAPSHOT","app_name":"cbo-recording-scheduler-service","level":"warn","message":"Error in Archive Service archiveEvent: 14 UNAVAILABLE: Connect Failed"}
> {"@timestamp":"2018-10-30T14:27:17.895Z","app_version":"1.2.0-SNAPSHOT","app_name":"cbo-recording-scheduler-service","level":"warn","message":"Unable to archive to be recorded event 'event2', retrying next time"}
> {"@timestamp":"2018-10-30T14:27:17.896Z","app_version":"1.2.0-SNAPSHOT","app_name":"cbo-recording-scheduler-service","level":"debug","message":"All to be recorded events processed"}
> {"@timestamp":"2018-10-30T14:28:17.894Z","app_version":"1.2.0-SNAPSHOT","app_name":"cbo-recording-scheduler-service","level":"info","message":"There are '1' events to record"}
> {"@timestamp":"2018-10-30T14:28:22.900Z","app_version":"1.2.0-SNAPSHOT","app_name":"cbo-recording-scheduler-service","level":"warn","message":"Error in Archive Service archiveEvent: 4 DEADLINE_EXCEEDED: Deadline Exceeded"}
> {"@timestamp":"2018-10-30T14:28:22.901Z","app_version":"1.2.0-SNAPSHOT","app_name":"cbo-recording-scheduler-service","level":"warn","message":"Unable to archive to be recorded event 'event2', retrying next time"}
> {"@timestamp":"2018-10-30T14:28:22.901Z","app_version":"1.2.0-SNAPSHOT","app_name":"cbo-recording-scheduler-service","level":"debug","message":"All to be recorded events processed"}
> {"@timestamp":"2018-10-30T14:29:17.897Z","app_version":"1.2.0-SNAPSHOT","app_name":"cbo-recording-scheduler-service","level":"info","message":"There are '1' events to record"}
> {"@timestamp":"2018-10-30T14:29:18.163Z","app_version":"1.2.0-SNAPSHOT","app_name":"cbo-recording-scheduler-service","level":"warn","message":"Error in Archive Service archiveEvent: 14 UNAVAILABLE: Connect Failed"}
> {"@timestamp":"2018-10-30T14:29:18.163Z","app_version":"1.2.0-SNAPSHOT","app_name":"cbo-recording-scheduler-service","level":"warn","message":"Unable to archive to be recorded event 'event2', retrying next time"}
> {"@timestamp":"2018-10-30T14:29:18.163Z","app_version":"1.2.0-SNAPSHOT","app_name":"cbo-recording-scheduler-service","level":"debug","message":"All to be recorded events processed"}
> {"@timestamp":"2018-10-30T14:30:17.898Z","app_version":"1.2.0-SNAPSHOT","app_name":"cbo-recording-scheduler-service","level":"info","message":"There are '1' events to record"}
> {"@timestamp":"2018-10-30T14:30:22.904Z","app_version":"1.2.0-SNAPSHOT","app_name":"cbo-recording-scheduler-service","level":"warn","message":"Error in Archive Service archiveEvent: 4 DEADLINE_EXCEEDED: Deadline Exceeded"}
> {"@timestamp":"2018-10-30T14:30:22.904Z","app_version":"1.2.0-SNAPSHOT","app_name":"cbo-recording-scheduler-service","level":"warn","message":"Unable to archive to be recorded event 'event2', retrying next time"}
> {"@timestamp":"2018-10-30T14:30:22.905Z","app_version":"1.2.0-SNAPSHOT","app_name":"cbo-recording-scheduler-service","level":"debug","message":"All to be recorded events processed"}
> {"@timestamp":"2018-10-30T14:31:17.901Z","app_version":"1.2.0-SNAPSHOT","app_name":"cbo-recording-scheduler-service","level":"info","message":"There are '1' events to record"}
> {"@timestamp":"2018-10-30T14:31:22.908Z","app_version":"1.2.0-SNAPSHOT","app_name":"cbo-recording-scheduler-service","level":"warn","message":"Error in Archive Service archiveEvent: 4 DEADLINE_EXCEEDED: Deadline Exceeded"}
> {"@timestamp":"2018-10-30T14:31:22.908Z","app_version":"1.2.0-SNAPSHOT","app_name":"cbo-recording-scheduler-service","level":"warn","message":"Unable to archive to be recorded event 'event2', retrying next time"}
> {"@timestamp":"2018-10-30T14:31:22.908Z","app_version":"1.2.0-SNAPSHOT","app_name":"cbo-recording-scheduler-service","level":"debug","message":"All to be recorded events processed"}
> 

The piece of code calling the service:
```javascript
const archiveServiceProtoPath = './proto/archive/archiveservice.proto';
const archiveServiceProto = grpc.load(archiveServiceProtoPath).archiveservice;

const archiveService = new archiveServiceProto.ArchiveService(archiveServiceHost + ':' + archiveServiceGrpcPort, grpc.credentials.createInsecure());
const client = Promise.promisifyAll(archiveService);

async function archiveEvent (eventId) {
    try {
        const grpcArchiveEventResponse = await client.archiveEventAsync({id: eventId},
            {
                deadline: moment.utc().add(grpcDeadlineTimeoutInSeconds, 'seconds').valueOf()
            });
        if (grpcArchiveEventResponse.state !== 'OK') {
            log.warn(`Error received from archive service, state = '${grpcArchiveEventResponse.state}'`);
            return grpcArchiveMapper.convertToArchiveState(grpcArchiveEventResponse.state);
        }
        return grpcArchiveMapper.convertToArchiveState(grpcArchiveEventResponse.state);
    } catch (err) {
        if (err.code) {
            grpcMetricHelper.logFailedRequest('archive_event', err.code);
        }
        log.warn(`Error in Archive Service archiveEvent: ${err.message}`);
        return archiveStateEnum.GENERAL_ERROR;
    }
}
```

**Comment by wdittmer** [comment]
I upgraded to 1.15.1 seeing fixes made in 1.15.0:
- Check connectivity state before watching in pick-first load balancing policy (grpc/grpc#16306)
- Fix re-resolution in pick-first load balancing policy (grpc/grpc#16076)

But the behaviour is still the same. We can workaround it by making a new client when an error occurs, but it is not really nice.

**Comment by AspirinSJL** [comment]
This reminds me of https://github.com/grpc/grpc/issues/16239#issuecomment-410406858, which is a slightly different issue of round robin. 

I will try to debug it a little later.

**Comment by AspirinSJL** [comment]
Oh, actually https://github.com/grpc/grpc/pull/17010 has fixed it but hasn't been included into any release version. Please try patching it. @wdittmer

**Comment by nicolasnoble** [comment]
Additionally, we just released 1.16.0. Maybe the behavior would be slightly different there? #17010 would need to be released in 1.17.0...

**Comment by wdittmer** [comment]
@nicolasnoble Thanks, I upgraded to 1.16.0, but the same pattern is still there.
@AspirinSJL I will try the patch and build it with  grpc/grpc#17010

**Comment by wdittmer** [comment]
To test the master branch I did the following:
clone grpc/grpc
clone grpc/grpc-node
copy the core files from grpc/grpc to grpc-node/node_modules/grpc/deps/src
and then ran`npm install grpc --build-from-source`
The resulting node-modules/grpc I copied to my project.

With this I see the following:
First UNAVAILABLE is returned, then DEADLINE_EXCEEDED, then UNAVAILABLE and then only DEADLINE_EXCEEDEDs.

Logging:
> {"@timestamp":"2018-11-01T13:13:13.663Z","level":"info","message":"Prometheus endpoint registered on /prometheus"}
> {"@timestamp":"2018-11-01T13:13:13.664Z","level":"info","message":"Health endpoint registered on /health"}
> {"@timestamp":"2018-11-01T13:13:13.665Z","level":"info","message":"HTTP Recording Scheduler Service started on port 8201"}
> {"@timestamp":"2018-11-01T13:14:13.659Z","level":"info","message":"There are '2' events to record"}
> {"@timestamp":"2018-11-01T13:14:13.674Z","level":"warn","message":"Error in Archive Service archiveEvent: 14 UNAVAILABLE: Connect Failed"}
> {"@timestamp":"2018-11-01T13:14:13.675Z","level":"warn","message":"Error in Archive Service archiveEvent: 14 UNAVAILABLE: Connect Failed"}
> {"@timestamp":"2018-11-01T13:14:13.675Z","level":"warn","message":"Unable to archive to be recorded event 'event1', retrying next time"}
> {"@timestamp":"2018-11-01T13:14:13.675Z","level":"warn","message":"Unable to archive to be recorded event 'event2', retrying next time"}
> {"@timestamp":"2018-11-01T13:14:13.675Z","level":"debug","message":"All to be recorded events processed"}
> {"@timestamp":"2018-11-01T13:15:13.661Z","level":"info","message":"There are '2' events to record"}
> {"@timestamp":"2018-11-01T13:15:18.665Z","level":"warn","message":"Error in Archive Service archiveEvent: 4 DEADLINE_EXCEEDED: Deadline Exceeded"}
> {"@timestamp":"2018-11-01T13:15:18.665Z","level":"warn","message":"Error in Archive Service archiveEvent: 4 DEADLINE_EXCEEDED: Deadline Exceeded"}
> {"@timestamp":"2018-11-01T13:15:18.665Z","level":"warn","message":"Unable to archive to be recorded event 'event2', retrying next time"}
> {"@timestamp":"2018-11-01T13:15:18.665Z","level":"warn","message":"Unable to archive to be recorded event 'event1', retrying next time"}
> {"@timestamp":"2018-11-01T13:15:18.666Z","level":"debug","message":"All to be recorded events processed"}
> {"@timestamp":"2018-11-01T13:16:13.660Z","level":"info","message":"There are '2' events to record"}
> {"@timestamp":"2018-11-01T13:16:14.417Z","level":"warn","message":"Error in Archive Service archiveEvent: 14 UNAVAILABLE: Connect Failed"}
> {"@timestamp":"2018-11-01T13:16:14.417Z","level":"warn","message":"Error in Archive Service archiveEvent: 14 UNAVAILABLE: Connect Failed"}
> {"@timestamp":"2018-11-01T13:16:14.417Z","level":"warn","message":"Unable to archive to be recorded event 'event1', retrying next time"}
> {"@timestamp":"2018-11-01T13:16:14.417Z","level":"warn","message":"Unable to archive to be recorded event 'event2', retrying next time"}
> {"@timestamp":"2018-11-01T13:16:14.417Z","level":"debug","message":"All to be recorded events processed"}
> {"@timestamp":"2018-11-01T13:17:13.662Z","level":"info","message":"There are '2' events to record"}
> {"@timestamp":"2018-11-01T13:17:18.664Z","level":"warn","message":"Error in Archive Service archiveEvent: 4 DEADLINE_EXCEEDED: Deadline Exceeded"}
> {"@timestamp":"2018-11-01T13:17:18.664Z","level":"warn","message":"Error in Archive Service archiveEvent: 4 DEADLINE_EXCEEDED: Deadline Exceeded"}
> {"@timestamp":"2018-11-01T13:17:18.664Z","level":"warn","message":"Unable to archive to be recorded event 'event2', retrying next time"}
> {"@timestamp":"2018-11-01T13:17:18.664Z","level":"warn","message":"Unable to archive to be recorded event 'event1', retrying next time"}
> {"@timestamp":"2018-11-01T13:17:18.664Z","level":"debug","message":"All to be recorded events processed"}
> {"@timestamp":"2018-11-01T13:18:13.663Z","level":"info","message":"There are '2' events to record"}
> {"@timestamp":"2018-11-01T13:18:18.669Z","level":"warn","message":"Error in Archive Service archiveEvent: 4 DEADLINE_EXCEEDED: Deadline Exceeded"}
> {"@timestamp":"2018-11-01T13:18:18.669Z","level":"warn","message":"Error in Archive Service archiveEvent: 4 DEADLINE_EXCEEDED: Deadline Exceeded"}
> {"@timestamp":"2018-11-01T13:18:18.669Z","level":"warn","message":"Unable to archive to be recorded event 'event1', retrying next time"}
> {"@timestamp":"2018-11-01T13:18:18.669Z","level":"warn","message":"Unable to archive to be recorded event 'event2', retrying next time"}
> {"@timestamp":"2018-11-01T13:18:18.669Z","level":"debug","message":"All to be recorded events processed"}
> {"@timestamp":"2018-11-01T13:19:13.663Z","level":"info","message":"There are '2' events to record"}
> {"@timestamp":"2018-11-01T13:19:18.669Z","level":"warn","message":"Error in Archive Service archiveEvent: 4 DEADLINE_EXCEEDED: Deadline Exceeded"}
> {"@timestamp":"2018-11-01T13:19:18.669Z","level":"warn","message":"Error in Archive Service archiveEvent: 4 DEADLINE_EXCEEDED: Deadline Exceeded"}
> {"@timestamp":"2018-11-01T13:19:18.669Z","level":"warn","message":"Unable to archive to be recorded event 'event1', retrying next time"}
> {"@timestamp":"2018-11-01T13:19:18.669Z","level":"warn","message":"Unable to archive to be recorded event 'event2', retrying next time"}
> {"@timestamp":"2018-11-01T13:19:18.669Z","level":"debug","message":"All to be recorded events processed"}

**Comment by wdittmer** [comment]
When I build it (and disable WIFI) it says:

> #grpc-node: npm install grpc --build-from-source
> npm WARN registry Using stale data from https://registry.npmjs.org/ because the host is inaccessible -- are you offline?
> npm WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
> 
> > grpc@1.16.0 install /Users/wilfreddittmer/Work/grpc-node/node_modules/grpc
> > node-pre-gyp install --fallback-to-build --library=static_library
> 
> node-pre-gyp WARN Using request for node-pre-gyp https download 
>   CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o
>   CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/avl/avl.o
>   CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/backoff/backoff.o
> ....<snipped>
>   SOLINK_MODULE(target) Release/grpc_node.node
>   COPY /Users/wilfreddittmer/Work/grpc-node/node_modules/grpc/src/node/extension_binary/node-v57-darwin-x64-unknown/grpc_node.node
>   TOUCH Release/obj.target/action_after_build.stamp
> + grpc@1.16.0
> updated 1 package in 82.811s
> 

If I compare grpc_node.node binary I created like this with a normal install , then node_modules/grpc/src/node/extension_binary/node-v57-darwin-x64-unknown/grpc_node.node differ
The assumption being that the build would generate the exact same binary of course if the grpc code was not modified.

Also I did see a change in behaviour, namely that it now does UNAVAILABLE, DEADLINE, UNAVAILABLE and then DEADLINE only. Before I got one UNAVAILABLE and then only DEADLINES.

If there is a better/easier/deterministic way to patch the grpc-node, I welcome suggestions.

**Comment by murgatroid99** [comment]
At this point, the `grpc` module has been deprecated for a couple of years, with `@grpc/grpc-js` as the recommended replacement. We have no plans to make any further updates to the `grpc` module to fix this problem.
