### ISSUE TITLE
Rename directories in `packages` directory

### ISSUE THREAD

**Issue by cjihrig** [grpc/grpc-node#602]
### Is your feature request related to a problem? Please describe.
It would be nice if the directories inside of `packages` in this repo had the same names as their corresponding npm packages.

### Describe the solution you'd like
In an ideal world, I'd get rid of the monorepo completely. You could also rename the directories. I'm happy to do the work, but I suspect it would break internal tooling such as CI.

### Describe alternatives you've considered
n/a

### Additional context
n/a

**Comment by nicolasnoble** [comment]
Yes, we wanted to do this for a while :-) Priorities...

**Comment by cjihrig** [comment]
> Priorities...

Is this something the community can help with, or will it break a bunch of internal things?

**Comment by murgatroid99** [comment]
Doing that shouldn't break anything internal, as long as any references within the repo are fixed. My main concern is that it might break external links into the repo.
