### ISSUE TITLE
Is node version 8.6.0 supported?

### ISSUE THREAD

**Issue by xeoshow** [grpc/grpc-node#611]
### Is your feature request related to a problem? Please describe.
I am using node-mobile, which used the node 8.6.0, is this version supported?

### Describe the solution you'd like
Hope 8.6.0 could be supported.

### Describe alternatives you've considered
None.

### Additional context
None.

**Comment by nicolasnoble** [comment]
This version of nodejs is supported by the native grpc module, but the biggest question is whether or not your runtime properly supports native modules.

8.6.0 isn't supported by the pure javascript version since this runtime didn't have http2 support yet.

**Comment by nicolasnoble** [comment]
A native module is a module that contains code native to the platform, so not in JavaScript. So basically the opposite of what you were thinning. Other examples of native modules are sqlite3 or mongodb's native driver. We provide precompiled binaries for a variety of platforms and runtimes, but in case you are on a runtime not in our support matrix, the installation will fallback to using your system's compiler.

Making native modules work isn't necessarily easy, and the pure javascript version of grpc helps with the difficulty here.

**Comment by xeoshow** [comment]
Got it, so is the grpc native module supported on android platform? thanks again!

**Comment by nicolasnoble** [comment]
Not officially, no. I managed to get it to work with some effort on my Android tablet using the nodejs runtime provided by termux, but there's no real way for us to support it properly and officially.

**Comment by xeoshow** [comment]
@nicolasnoble Really thank you v much for your kind and professional help. So, besides the so good grpc-node project, considering my special need, is there any other usable pure js grpc module which could be recommended? :-D
Thanks a lot!

Best regards, Jason

**Comment by xeoshow** [comment]
Hello @nicolasnoble ,

Just checked from below link, seems 8.6.0 support http2 already, if so, grpc-web should can work on 8.6.0? Thanks! 
https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V8.md#8.9.3

**Comment by nicolasnoble** [comment]
Unfortunately, we need some of the corrections that were done in 8.11.2. See https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V8.md#8.11.2 for the list of changes in 8.11.2 affecting the http2 module.

**Comment by nicolasnoble** [comment]
Also, no, we don't really have any other pure javascript implementation, since it would really rely on this http2 module from node 8.11.2, unfortunately.
