### ISSUE TITLE
Failed at the grpc@1.13.1 install script still occuring

### ISSUE THREAD

**Issue by spencerfontein** [grpc/grpc-node#652]
### Problem description
Failed at the grpc@1.13.1 install script

### Reproduction steps
npm install (inside the project)

### Environment
$npm -v
6.4.1

$nodejs -v
v8.12.0

OS: Ubuntu 16.04

### Additional context
grpc@1.13.1 install /root/nginx/ngdesk-webapp-project/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

sh: 1: node-pre-gyp: Permission denied
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! grpc@1.13.1 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the grpc@1.13.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-11-20T19_03_49_986Z-debug.log

**Comment by nicolasnoble** [comment]
You're installing as root. Please run with `--unsafe-perm`.
