### ISSUE TITLE
proto-loader map<int64, string> error

### ISSUE THREAD

**Issue by p2world** [grpc/grpc-node#658]
i have:
message pingReply {
    map<int64, string> mint64string = 1;
}
callback(null, {
mint64string: { "1": "a", "2": "b" }
});

but got 

mint64string:
   { '\u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000': 'a',
     '\u0002\u0000\u0000\u0000\u0000\u0000\u0000\u0000': 'b' },

**Comment by nicolasnoble** [comment]
Your report doesn't contain nearly enough information for us to help you. As mentioned in [our issue template](https://github.com/grpc/grpc-node/blob/master/.github/ISSUE_TEMPLATE/bug_report.md), issues without reproduction will be closed. Please create a new issue with the full details of what you're doing, including a minimal reproduction case we can run ourselves.
