### ISSUE TITLE
protobufjs@5.0.3 is vulnerable to ReDOS Attack

### ISSUE THREAD

**Issue by lbphillipvose** [grpc/grpc-node#659]
### Problem description
https://hackerone.com/reports/319576

### Reproduction steps
Install [retireJS](https://retirejs.github.io/retire.js/) and run against any project including `grpc`.

### Environment
 - gRPC@1.12.0

### Additional context
When running [retireJS](https://retirejs.github.io/retire.js/) against our repo, we get the following error message:
```
node_modules/grpc/node_modules/protobufjs/package.json
↳ protobufjs 5.0.3
protobufjs 5.0.3 has known vulnerabilities: severity: medium; summary: Denial of Service; https://hackerone.com/reports/319576
```

After a bit of investigation, most of the dependencies are up to date, but within `grpc-native-core`, the version of `protobufjs` is currently sat at 5.0.3 and needs updating.

* https://github.com/grpc/grpc-node/blob/abbc9aa1363839a1eef7c1144de281bf83d19a82/packages/grpc-native-core/package.json
* https://github.com/grpc/grpc-node/blob/abbc9aa1363839a1eef7c1144de281bf83d19a82/packages/grpc-native-core/templates/package.json.template

<img width="442" alt="screen shot 2018-11-27 at 14 50 28" src="https://user-images.githubusercontent.com/43742888/49089698-03385c00-f254-11e8-90ba-a960d06e6c57.png">

**Comment by nicolasnoble** [comment]
This report is incorrect. Protobufjs 5.0.3 has been fixed. Please contact your security provider so they update their databases.
