### ISSUE TITLE
Sending request to a server that isn't responding causes the node process hang

### ISSUE THREAD

**Issue by Cyperwu** [grpc/grpc-node#666]
### Problem description
I have a C++ server that is not very stable runing on windows, it sometimes stop responding (maybe due to Windows's own problems).
When the Windows server hangs and I start streaming data to it, my server hangs, too.

The situation could be reproduced in a Linux(Ubuntu 18.04) server and a client in the same machine too, but in my case the Windows server hangs more often(but grpc is not the one to be blamed).

In general, I tried a Linux server with Linux/Mac client and a Windows server with Linux/Mac client. In both cases the client  will hang when the server is not responding.

I think it's a SERIOUS situation that the client shouldn't hang up though the server side hangs.
I used ` node-inspector` to debug the client and the most I could go is `call.startBatch` which refers
[here](https://github.com/grpc/grpc-node/blob/master/packages/grpc-native-core/src/client_interceptors.js#L954) and [here](https://github.com/grpc/grpc-node/blob/master/packages/grpc-native-core/ext/call.cc#L597)

I'll try going more deeper.

### Reproduction steps
1. Start a server and make it not responding (In my case some server-side crash or some windows mechanism will do the job.)
2. make a client side streaming call, send any data (even the type of the input does not match the description of the .proto file)

### Environment
 - OS: Linux Ubuntu 18.04, MacOS High Sierra 10.13.6
 - Node version:  8.11.2, 11.3.0
 - Node installation method: n
 - Package name and version grpc@1.16.1, grpc@1.15.1

*** EDIT ***
To reproduce the server-side hang, just let the Windows machine turn into Sleep Mode.

**Comment by nicolasnoble** [comment]
From what you're describing, I could only say that this is "working as intended". If you're starting a single request of anything without any other timer or timeout or parallel request happening, then, sure, the client will just not do anything.

Have you tried adding a deadline to your call? Have other nodejs tasks been started in your process that aren't completing and got frozen?

**Comment by Cyperwu** [comment]
@nicolasnoble Deadline didn't work, the whole node process is not responding. The client side service is a RESTful API server, which accepts requests from the web front end. In my test environment, I can  confirm that there is only one request sent to the server, and it went through middlewares in an asynchronous way, right to the grpc call. And after a few seconds from the call, it did not respond to any call at all.

Also i've found that the grpc-1.17-pre package seems resolved this bug.

**Comment by nicolasnoble** [comment]
This is peculiar... but at the same time, if 1.17 fixes it, then...

**Comment by Cyperwu** [comment]
Yeah, I should upgrade my grpc package to 1.17
