### ISSUE TITLE
Electron and Firestore

### ISSUE THREAD

**Issue by higuitadiaz** [grpc/grpc-node#677]
### Problem description
The system is displaying: the following error: 

> Error: Failed to load gRPC binary module because it was not installed for the current system
> Expected directory: electron-v3.0-linux-x64-glibc
> Found: [node-v51-linux-x64-glibc, node-v57-linux-x64-glibc]

I am just using a Electron quick starter oficial (https://github.com/electron/electron-quick-start) and Firebase npm version 5.7.0
.

### Reproduction steps
```
1. $ git clone https://github.com/electron/electron-quick-start
2. $ npm install && npm install firebase --save
3. $ npm start
```

### Environment
 - OS name, version and architecture:  Linux Ubuntu 18.04 amd64
 - Node version 8.14.0
 - Node installation method : npm
 - Package name and version: 1.17.0

### Additional context

>  App threw an error during load
> Error: Failed to load gRPC binary module because it was not installed for the current system
> Expected directory: electron-v3.0-linux-x64-glibc
> Found: [node-v51-linux-x64-glibc, node-v57-linux-x64-glibc]
> This problem can often be fixed by running "npm rebuild" on the current system
> Original error: Cannot find module '/home/adrian/workspace/electron_projects/euruspro-desktop/node_modules/@firebase/firestore/node_modules/grpc/src/node/extension_binary/electron-v3.0-linux-x64-glibc/grpc_node.node'

**Comment by nicolasnoble** [comment]
Please check out our Electron section in our readme.

https://www.npmjs.com/package/grpc#about-electron
