### ISSUE TITLE
How to get the simple object by google_protobuf_struct_pb.Struct.toObject?

### ISSUE THREAD

**Issue by wzkun** [grpc/grpc-node#680]
### Is your feature request related to a problem? Please describe.
In .proto file ,I use 'google.protobuf.Struct' as response data type, but in nodejs,after response.toObject(),the response is like :
{ fieldsMap:
   [ [ 'createTime',
       { nullValue: 0,
         numberValue: 0,
         stringValue: '2018-12-12T17:38:09.085+08:00',
         boolValue: false,
         structValue: undefined,
         listValue: undefined } ]
}.
But I want get the response like :{'createTime': '2018-12-12T17:38:09.085+08:00'}.
### Describe the solution you'd like
I just want to use response.toObject(), and get the simple object.

**Comment by wzkun** [comment]
@murgatroid99

**Comment by CatsMiaow** [comment]
https://github.com/grpc/grpc-node/issues/375#issuecomment-400092208

**Comment by wzkun** [comment]
I have tried that way ， but it does not works.

**Comment by CatsMiaow** [comment]
This is an example that I have solved.
https://github.com/CatsMiaow/node-grpc-typescript
Client: https://github.com/CatsMiaow/node-grpc-typescript/blob/master/src/client.ts#L33
Server: https://github.com/CatsMiaow/node-grpc-typescript/blob/master/src/package/helloworld/Greeter.ts#L38

**Comment by murgatroid99** [comment]
If I understand right, you are using compiled .proto files using protoc, possibly using the `grpc-tools` package. If that is correct I suggest filing an issue on [the official protobuf repository](https://github.com/protocolbuffers/protobuf) because they are responsible for that API.
