### ISSUE TITLE
Fail to get the meaning of the status code

### ISSUE THREAD

**Issue by WandyLau** [grpc/grpc-node#687]
### Problem description
A clear and concise description of what the problem is.
We had an application which failed to communicate with server. 
We only get the error:  **Error: 1 CANCELLED: Received http2 header with status: 404**

### Environment
 - OS name, version and architecture: [e.g. Linux Ubuntu 18.04 amd64]
    ubuntu 16.04
 - Node version [e.g. 8.10.0]
   node v8.11.3 npm 5.6.0
 - Node installation method [e.g. nvm]
 - If applicable, compiler version [e.g. clang 3.8.0-2ubuntu4]
 - Package name and version [e.g. gRPC@1.12.0]
 grpc 1.10.1

### Additional context
In the debug log, we have found some interesting things as follow:

I1221 10:50:35.064140645   16826 completion_queue.cc:853]    grpc_completion_queue_next(cq=0x22fb350, deadline=gpr_timespec { tv_sec: -9223372036854775808, tv_nsec: 0, clock_type: 0 }, reserved=(nil))
I1221 10:50:35.064152555   16826 completion_queue.cc:953]    RETURN_EVENT[0x22fb350]: QUEUE_TIMEOUT
I1221 10:50:35.064171928   16826 completion_queue.cc:853]    grpc_completion_queue_next(cq=0x22fb350, deadline=gpr_timespec { tv_sec: -9223372036854775808, tv_nsec: 0, clock_type: 0 }, reserved=(nil))
I1221 10:50:35.064186800   16826 completion_queue.cc:953]    RETURN_EVENT[0x22fb350]: QUEUE_TIMEOUT

CANCEL:{"created":"@1545407435.167005801","description":"Received http2 :status header with non-200 OK status","file":"../deps/grpc/src/core/ext/filters/http/client/http_client_filter.cc","file_line":87,"grpc_message":"Received http2 header with status: 404","grpc_status":1,"value":"404"}

But we can not figure out what exactly has happened.

**Comment by nicolasnoble** [comment]
Well, you got a 404, meaning you tried to issue a call to an unknown method of the server.

**Comment by WandyLau** [comment]
@nicolasnoble So you mean that the connection has been established but the function is not available in server end. Is that what you mean? I ask this because I doubt the connection failed. And we did not find any log in server side. So I am not sure what does this error means exactly.

**Comment by nicolasnoble** [comment]
Yes, the correction succeeded, but the call failed.

**Comment by WandyLau** [comment]
I afraid the communication between client and server is not good enough. I did not find any clue from server end. Or it just failed to communicate with server with grpcs protocol. I will investigate it more.
In other test, I can call the function in server side. I doubt some element may be filtered when to communicate with server.
