### ISSUE TITLE
How to test keepalive options?

### ISSUE THREAD

**Issue by zyf0330** [grpc/grpc-node#706]
I use keepalive options like `grpc.keepalive_time_ms, grpc.keepalive_timeout_ms`, but don't know how to test if it works.
I have test set options at client and server, but both is useless.
My way to test is disconnecting network and checking tcp connection status between client and server with `ss -tpn`. Connections status keeps being `ESTABLISED` after disconnecting network. I think client or server should close tcp connection and status becomes like `FIN-WAIT`.

**Comment by alexvy86** [comment]
@murgatroid99 does that mean that if I have a client application that just starts, but doesn't make any requests to a GRPC server until it receives requests itself, there's no way to keep the connection between them active (with keepalive packets) unless I make a "fake" call to the server during the client init? The keepalive won't start as soon as the connection is established, before the first request is sent?

**Comment by murgatroid99** [comment]
As indicated by the bullet point following the one you quoted, if there are no active calls, a keepalive ping will not be sent unless the channel argument `GRPC_ARG_KEEPALIVE_PERMIT_WITHOUT_CALLS` is set (the string key is `"grpc.keepalive_permit_without_calls"`, and the value should be `1` to enable it).

Also, a caveat that is not mentioned in that document is that a transport connecting is not the same as creating a client/channel. Generally gRPC channels start with no transports, and do not establish a transport until a call is started. It is possible to force a client to connect using the [`Client#waitForReady`](https://grpc.io/grpc/node/grpc.Client.html#waitForReady__anchor) method.
