### ISSUE TITLE
node grpc client is writing data to non-existent grpc server which running on AWS.

### ISSUE THREAD

**Issue by ghost** [grpc/grpc-node#71]
We have our grpc servers running on AWS and maintained by AWS ELB. After every deployments, all the old instances will take down and new ones will come up.

I am using node grpc client to consume grpc. What is surprising is, after deployment, node client is still able to write data to instances which are already terminated. they are removed from AWS. 

This is happening consistently and able to get logs.

*Before deploying new instances, it is connect `99.126.18.38`*

```D1027 00:02:32.641236796      20 tcp_uv.c:165]               read: error="No Error"
D1027 00:02:32.641248526      20 tcp_uv.c:170]               READ 0x2ca2440 (peer=ipv4:99.126.18.38:50051): 00 00 00 04 01 00 00 00 00 '.........'
D1027 00:02:32.641256175      20 tcp_uv.c:205]               Initiating read on 0x2ca2440: error="No Error"
D1027 00:02:56.319402144      20 tcp_uv.c:165]               read: error="No Error"
D1027 00:02:56.319445970      20 tcp_uv.c:170]               READ 0x2ca2440 (peer=ipv4:99.126.18.38:50051): ......'
D1027 00:02:56.319465809      20 tcp_uv.c:205]               Initiating read on 0x2ca2440: error="No Error"
workflow-j994qpll-log-14 PENDING deploy Processing by xxxxx...
D1027 00:02:59.687340345      20 tcp_uv.c:165]               read: error="No Error"
D1027 00:02:59.687392673      20 tcp_uv.c:170]               READ 0x2ca2440 (peer=ipv4:99.126.18.38:50051): .'
D1027 00:02:59.687433036      20 tcp_uv.c:205]               Initiating read on 0x2ca2440: error="No Error"
D1027 00:02:59.687475521      20 tcp_uv.c:248]               WRITE 0x2ca2440 (peer=ipv4:99.126.18.38:50051): .......'
D1027 00:02:59.687538793      20 tcp_uv.c:223]               write complete on 0x2ca2440: error="No Error"
D1027 00:02:59.690488603      20 tcp_uv.c:165]               read: error="No Error"
D1027 00:02:59.690499049      20 tcp_uv.c:170]               READ 0x2ca2440 (peer=ipv4:99.126.18.38:50051): 00 00 00 04 01 00 00 00 00 '.........'
D1027 00:02:59.690505852      20 tcp_uv.c:205]               Initiating read on 0x2ca2440: error="No Error"
commit call status :  { code: 0,
  details: '',
  metadata: Metadata { _internal_repr: {} } }
```
*After deployment, new instances came up with new IPs.*

```
D1027 02:08:03.254455899      20 tcp_uv.c:248]               WRITE 0x2ca2440 (peer=ipv4:99.126.18.38:50051): ..........'
D1027 02:08:03.254477131      20 tcp_uv.c:248]               WRITE 0x2ca2440 (peer=ipv4:99.126.18.38:50051): ':path'
D1027 02:08:03.254482534      20 tcp_uv.c:248]               WRITE 0x2ca2440 (peer=ipv4:99.126.18.38:50051): '*'
D1027 02:08:03.254488566      20 tcp_uv.c:248]               WRITE 0x2ca2440 (peer=ipv4:99.126.18.38:50051): '
D1027 02:08:03.254494090      20 tcp_uv.c:248]               WRITE 0x2ca2440 (peer=ipv4:99.126.18.38:50051): .......'
D1027 02:08:03.254498968      20 tcp_uv.c:248]               WRITE 0x2ca2440 (peer=ipv4:99.126.18.38:50051):  'grpc-timeout'
D1027 02:08:03.254504662      20 tcp_uv.c:248]               WRITE 0x2ca2440 (peer=ipv4:99.126.18.38:50051):  '.630S..........'
D1027 02:08:03.254509486      20 tcp_uv.c:248]               WRITE 0x2ca2440 (peer=ipv4:99.126.18.38:50051): '....'
D1027 02:08:03.254517491      20 tcp_uv.c:248]               WRITE 0x2ca2440 (peer=ipv4:99.126.18.38:50051): '
D1027 02:08:03.254847362      20 tcp_uv.c:223]               write complete on 0x2ca2440: error="No Error"
```
There is almost 120 mins between two calls. 

Also I have tried to ping or curl to make sure that the IP not recycled. 

Why is still writing to non-existent IP ? any hints will help me debug this issue. thanks !!

**Comment by murgatroid99** [comment]
Does the request after the IP change end? If so, what status does it end with?

**Comment by krundrufanatics** [comment]
@murgatroid99 yes it is because I have set 10mins as deadline from client site. the reason we have 10 mins is, it is a ClientReadableStream and usually server will take anywhere between 3-10 mins to process the request. 

After this deadline-exceeded, next requests are send to new servers.

**Comment by murgatroid99** [comment]
That is very strange. If the next requests are going to the new servers, then clearly gRPC does notice at some point that the old servers are down and that it has to re-query DNS. But when that happens, the network disconnection should bubble up to any active requests as an UNAVAILABLE status. The call shouldn't wait for the deadline.

**Comment by krundrufanatics** [comment]
Actually I was wrong. it is able to reconnect following calls b/c we have a retry logic which catches the `Connect Fail` errors then it will connect channel (`grpc.closeClient(client)` and reopen new one. 

I think when re-connecting, it able to get new IPs. 
Good thing here is, after `Deadline-Exceeded` error, next calls are failing with `Connect Failed` errors.

**Comment by nicolasnoble** [comment]
Is this still an issue then ?

**Comment by nicolasnoble** [comment]
Closing, since it got no response for 40 days.
