### ISSUE TITLE
404 Not Found: grpc@1.12.0

### ISSUE THREAD

**Issue by lukepighetti** [grpc/grpc-node#710]
Given deps

```
  "dependencies": {
    "axios": "^0.18.0",
    "bitcoind-rpc": "^0.7.1",
    "firebase-admin": "^5.12.1"
  }
```

These all fail with 

> npm ERR! code E404
> npm ERR! 404 Not Found: grpc@1.12.0

```
FROM node:10-alpine
RUN npm install --production --build-from-source
```

```
FROM node:10-alpine
RUN npm install --production
```

```
FROM node:8-alpine
RUN npm install --production --build-from-source
```

```
FROM node:8-alpine
RUN npm install --production
```

This is the only one that succeeds

```
FROM node:6-alpine
RUN npm install --production
```

**Comment by murgatroid99** [comment]
I don't know why your dependencies are specifically resolving to grpc@1.12.0, but that version was unpublished soon after it was published 8 months ago. Versions 1.12.1 through 1.12.3 do exist, so even relatively restrictive version ranges should pick those up. The newest version of the grpc library is 1.18.0, so it would be good to upgrade anyway.

**Comment by lukepighetti** [comment]
Upgraded and problem is resolved!
