### ISSUE TITLE
Getting GOAWAY in callback error of call

### ISSUE THREAD

**Issue by zyf0330** [grpc/grpc-node#717]
Request to server receives an error from callback, don't know why. If it is caused by too many `PING`, it should be another kind info within `ENHANCE_YOUR_CALM`, I think.
This is error info
```
{"error":{"code":13,"name":"Error","details":"GOAWAY received","message":"13 INTERNAL: GOAWAY received","stack":"Error: 13 INTERNAL: GOAWAY received\n    at Object.exports.createStatusError (/app/node_modules/grpc/src/common.js:87:15)\n    at Object.onReceiveStatus (/app/node_modules/grpc/src/client_interceptors.js:1188:28)\n    at InterceptingListener._callNext (/app/node_modules/grpc/src/client_interceptors.js:564:42)\n    at InterceptingListener.onReceiveStatus (/app/node_modules/grpc/src/client_interceptors.js:614:8)\n    at callback (/app/node_modules/grpc/src/client_interceptors.js:841:24)","metadata":{"_internal_repr":{}}}}
```

### another
I just add some keepalive options to grpc client and server, not sure if it is related to this error.

#### client option
```
        // reconnect
        'grpc.initial_reconnect_backoff_ms': 3000,
        'grpc.min_reconnect_backoff_ms': 1000,
        'grpc.max_reconnect_backoff_ms': 10000,
        // keepalive
        'grpc.http2.min_time_between_pings_ms': 5 * 60000, // grpc default
        'grpc.http2.max_pings_without_data': 0,
        'grpc.keepalive_time_ms': 10 * 60000,
        'grpc.keepalive_timeout_ms': 10000,
        'grpc.keepalive_permit_without_calls': 1,
```
#### server option
```
      // keepalive
      'grpc.http2.min_ping_interval_without_data_ms': 5 * 60000, // grpc default
      'grpc.keepalive_permit_without_calls': 1,
      // connection survival
      'grpc.max_connection_idle_ms': 30 * 60000,
      'grpc.max_connection_age_ms': 2 * 60 * 60000,
```

**Comment by zyf0330** [comment]
I cannot reproduce it at local.
I believe it is related to this issue https://github.com/googleapis/nodejs-spanner/issues/492, they should have same reason.

**Comment by zyf0330** [comment]
@murgatroid99 Do you think this problem is related to https://github.com/grpc/grpc/issues/14088?

**Comment by bcronje** [comment]
This is probably related to https://github.com/grpc/grpc-go/issues/2202 and https://github.com/grpc/grpc/issues/16210

**Comment by zyf0330** [comment]
I think I have found the reason.
It is `grpc.max_connection_age_ms` which causes rpc call returns GOAWAY error, because server closes connection forcely when connection's life exceeds `grpc.max_connection_age_ms`.

**Comment by zyf0330** [comment]
@murgatroid99 Due to some reason about Load Balancing I must use **max age** option to close long-alive connection now, but I think the current related logic is not proper, this `GOAWAY` error can be avoided. I hope more transparent connection switch.
The following logic is what I think proper. When server prepares to close connection due to `max_connection_age_ms`, it can half close connection, and keep handling current request. When client receives connection close event, it won't send more requests in old connection, but create new connection and send new requests on it.
I don't know the real logic implemented in grpc C core, could you give me some suggestions?

**Comment by murgatroid99** [comment]
The problem there is that there is a race: if the server sends a GOAWAY because the max connection age is reached, the client may start a new request before receiving the GOAWAY, but the server will not accept the request so it fails. You will probably just need to retry those requests when they fail that way.

**Comment by zyf0330** [comment]
Can you confirm that in this situation, the possible error is only GOAWAY?

Michael Lumish <notifications@github.com> 于2020年11月17日周二 上午1:17写道：

**Comment by murgatroid99** [comment]
grpc-js 1.8.x+ has improved handling of errors like this: they are now transparently retried if possible.
