### ISSUE TITLE
Resolver plug-ins?

### ISSUE THREAD

**Issue by djmarcin** [grpc/grpc-node#719]
Can custom resolvers be used with the node client? I didn’t see an API for this in the JavaScript. Would I need to fork, add it to the C library, and build from source?

**Comment by nicolasnoble** [comment]
There is currently no API in the C library for custom resolvers. See https://github.com/grpc/grpc/pull/16617

**Comment by murgatroid99** [comment]
The `grpc` package has been deprecated, so even if the C library does get an API for custom resolvers, it will not be picked up by that library. However, the `@grpc/grpc-js` library, which we recommend using, now has an experimental API for defining and registering custom resolvers. We do not guarantee that that API will be stable across different minor versions of that library, so use it at your own risk.
