### ISSUE TITLE
Endpoint read failed error in server

### ISSUE THREAD

**Issue by rush-kamath** [grpc/grpc-node#727]
### Problem description
The greeter_server.js in the node example (https://github.com/grpc/grpc/tree/master/examples/node/dynamic_codegen) always logs "Endpoint read failed" error after executing the sayHello method.

### Reproduction steps
I am running the greeter_server.js from the node/examples  with the GRPC_VERBOSITY = DEBUG and GRPC_TRACE = tcp. 
In another window, I execute the greeter_client.js 
The client ends normally, but the server always logs the following error after processing the request

`I0206 16:30:56.859028000 4364977600 tcp_custom.cc:132]                 read: error={"created":"@1549470656.858973000","description":"EOF","file":"../deps/grpc/src/core/lib/iomgr/tcp_uv.cc","file_line":107}`

`I0206 16:30:56.859058000 4364977600 tcp_custom.cc:286]                 TCP 0x102315480 shutdown why={"created":"@1549470656.859042000","description":"Endpoint read failed","file":"../deps/grpc/src/core/ext/transport/chttp2/transport/chttp2_transport.cc","file_line":2491,"grpc_status":14,"occurred_during_write":0,"referenced_errors":[{"created":"@1549470656.858973000","description":"EOF","file":"../deps/grpc/src/core/lib/iomgr/tcp_uv.cc","file_line":107}]}`

### Environment
 - Running this locally on my MacOS
 - Node version: 8.7.0
 - Node installation method: nvm
 - Package name and version: I see this error in both 1.11.0 and 1.16.0

**Comment by murgatroid99** [comment]
There is probably not a problem here. These lines are simply logging that the client has disconnected, so all of the server state for that connection is getting shut down. 

In general, you should not run with the tracers enabled unless you are looking for something specific or debugging an failure. Many things are hidden by the gRPC abstraction layers, and errors that are not surfaced to the user are not meant to be acted on by the user.

**Comment by nicolasnoble** [comment]
This isn't an issue. Closing.
