### ISSUE TITLE
[Question] How to get client ipv4 from server end?

### ISSUE THREAD

**Issue by Jeff-Tian** [grpc/grpc-node#738]
Is there any way to get the client's ip from server side when a grpc request was made?

**Comment by Jeff-Tian** [comment]
Seems I can get client ipv6 by `ServerUnaryCall.getPeer()` method which gives these output:
'ipv6:[::1]:60099'

But how to get the ipv4 address?

**Comment by nicolasnoble** [comment]
The client is only connected once, so there's only one peer address. In your case, your client connected in ipv6, so that's the only information available to you.

**Comment by Jeff-Tian** [comment]
@nicolasnoble thanks.
