### ISSUE TITLE
Fails to build from source on nodejs 10 + gcc 8.2.1 (Fedora 29)

### ISSUE THREAD

**Issue by gcampax** [grpc/grpc-node#739]
### Problem description
Building from source (with "build_from_source true" in .npmrc or .yarnrc) fails with the following error:
>   CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/transport/chttp2/transport/chttp2_transport.o
> ../deps/grpc/src/core/ext/transport/chttp2/transport/chttp2_transport.cc: In function ‘grpc_error* try_http_parsing(grpc_chttp2_transport*)’:
> ../deps/grpc/src/core/ext/transport/chttp2/transport/chttp2_transport.cc:2457:40: error: ‘void* memset(void*, int, size_t)’ clearing an object of non-trivial type ‘grpc_http_response’ {aka ‘struct grpc_http_response’}; use assignment or value-initialization instead [-Werror=class-memaccess]
>   memset(&response, 0, sizeof(response));
>                                        ^
> In file included from ../deps/grpc/src/core/ext/transport/chttp2/transport/chttp2_transport.cc:44:
../deps/grpc/src/core/lib/http/parser.h:71:16: note: ‘grpc_http_response’ {aka ‘struct grpc_http_response’} declared here
 typedef struct grpc_http_response {
>                ^~~~~~~~~~~~~~~~~~
> cc1plus: all warnings being treated as errors
> make: *** [grpc.target.mk:474: Release/obj.target/grpc/deps/grpc/src/core/ext/transport/chttp2/transport/chttp2_transport.o] Error 1

### Reproduction steps
1. Set your npm to build all dependencies from source.
2. Attempt to install the library

### Environment
 - Linux Fedora 29
 - Node 10.15.0 (installed from distro packages)
 - Compiler: gcc-8.2.1-6.fc29.x86_64
 - grpc 1.18.0

### Additional context
It seems that the new gcc introduced a new warning that is enough to make the build fail, due to `-Werror`. At the same time, it seems that grpc is exposing undefined behavior, due to declaring a class with member initializers and then using memset on it without ever calling a constructor (this is not allowed in C++). Looking at affected header, it seems grpc is mixing C (`typedef struct`) and C++ (member initializers, `nullptr`).

**Comment by murgatroid99** [comment]
Thank you for reporting this. The code in question actually lives in https://github.com/grpc/grpc, so if you could file an issue there that would be more helpful with fixing this.

**Comment by mastersingh24** [comment]
We've been using 
`export CXXFLAGS -Wno-error` 
for platforms where we have to build from source

**Comment by murgatroid99** [comment]
I believe that specific error has been fixed, and the most recent versions of the grpc library no longer set the `-Werror` flag, so this should no longer be a problem.

**Comment by mastersingh24** [comment]
great news!
