### ISSUE TITLE
Update grpc-native-core submodule to make interop tests against Grpc.AspNetCore.Server to pass

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc-node#740]
Can we update grpc-native-core at least to a version that includes this fix: https://github.com/grpc/grpc/pull/17950 ?

Context:
https://github.com/grpc/grpc-dotnet/issues/101#issuecomment-464682286
(interop tests between grpc-node native and ASP.NET core rely the above fix to work).

https://github.com/grpc/grpc/pull/18070

**Comment by jtattermusch** [comment]
I could create the PR to update the submodule myself, but it seems other files need to be updated too (I checked https://github.com/grpc/grpc-node/pull/718/files) and I'm not sure what the process is.

**Comment by nicolasnoble** [comment]
It's the same process as the other repository: calling `generate_projects.sh`

**Comment by jtattermusch** [comment]
Superseded by https://github.com/grpc/grpc-node/pull/737/files.
