### ISSUE TITLE
Missing bundled dependency "node-pre-gyp"

### ISSUE THREAD

**Issue by kritzware** [grpc/grpc-node#748]
### Problem description
When running `yarn` or `yarn install` in a project that has `grpc-tools` installed, I get the following error:
```$ yarn
yarn install v1.12.3
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
warning "grpc-tools@1.7.0" is missing a bundled dependency "node-pre-gyp". This should be reported to the package maintainer.
[5/5] 📃  Building fresh packages...
⠁
⠁
⠁
error /Users/louis/programming/project/node_modules/grpc-tools: Command failed.
Exit code: 127
Command: ./node_modules/.bin/node-pre-gyp install
Arguments:
Directory: /Users/louis/programming/project/node_modules/grpc-tools
Output:


```

### Reproduction steps
This also happens when I create a fresh project, following the steps below:
1. `mkdir temp/ && cd temp/`
2. `yarn add grpc-tools`
3. `rm -rf node_modules`
4. `yarn`

This then leads to the following output:

```$ yarn
yarn install v1.12.3
warning package.json: No license field
warning No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "grpc-tools@1.7.0" is missing a bundled dependency "node-pre-gyp". This should be reported to the package maintainer.
[4/4] 📃  Building fresh packages...
error /Users/louis/programming/temp/node_modules/grpc-tools: Command failed.
Exit code: 127
Command: ./node_modules/.bin/node-pre-gyp install
Arguments:
Directory: /Users/louis/programming/temp/node_modules/grpc-tools
Output:
/bin/sh: ./node_modules/.bin/node-pre-gyp: No such file or directory
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

### Environment
 - OS name, version and architecture: `macOS Mojave 10.14.3`
 - Node version: `v10.13.0`
 - Node installation method: Installer from nodejs.org
 - Package name and version: `grpc-tools@1.7.0`

**Comment by murgatroid99** [comment]
This should be fixed in 1.7.1

**Comment by kritzware** [comment]
All good now, thanks! 👍

**Comment by ilari-makimattila** [comment]
This still happens if you do a full reinstall with yarn.lock in place:

 1. `yarn init`
 2. `yarn add grpc-tools`
 3. `rm -rf node_modules`
 4. `yarn`

**Comment by nicolasnoble** [comment]
You mean, a yarn.lock pinning the grpc package version to 1.7.0...?

**Comment by ilari-makimattila** [comment]
No. `yarn add grpc-tools` writes `"grpc-tools": "^1.7.1"` into `package.json` and `yarn.lock` contains
```
grpc-tools@^1.7.1:
  version "1.7.1"
  resolved "https://registry.yarnpkg.com/grpc-tools/-/grpc-tools-1.7.1.tgz#f353812fd21df057d09cf94d06134c19834ad67c"
  integrity sha512-mK2AvaWhr6nfthLs2igXxo8c3jjOkr5fra+ifJ6LGgIT+iyJTb4AZOA09s86wDVyBpodqF9XCT1HsXVV6OJIAg==
```
I'm using yarn v1.13.0.

**Comment by nicolasnoble** [comment]
And is the problem solved by removing the yarn.lock file?

**Comment by ilari-makimattila** [comment]
Yes. So it's an issue in yarn. Thanks.

**Comment by nicolasnoble** [comment]
Thanks, that makes a lot more sense to me now, I was just very confused.

We're going to file an issue with yarn.

**Comment by murgatroid99** [comment]
I have filed an issue with yarn: yarnpkg/yarn#7063.

**Comment by foisonocean** [comment]
We have the same problem in our CI build, is there any solutions for fix this?

**Comment by nicolasnoble** [comment]
#774 worked this around, but I don't think we've republished any new package yet.

**Comment by foisonocean** [comment]
@nicolasnoble 

Is there any plans to publish a version? This really blocks my works, thanks.
