### ISSUE TITLE
Cannot encode BytesValue

### ISSUE THREAD

**Issue by alephnan** [grpc/grpc-node#756]
I am attempting to specify a field `foo` of type [google.protobuf.BytesValue](https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/wrappers.proto#L120).
```
message Bar {
  google.protobuf.BytesValue foo = 1;
}
```

For context, `foo` encodes an PNG image. A Java based gRPC client successfully transmitted the data with this code:
```
RandomAccessFile f = new RandomAccessFile(imageName, "r");
byte[] bytes = new byte[(int) f.length()];
f.read(bytes);
f.close();
ByteString byteString = ByteString.copyFrom(bytes);
Bar creative = Bar.newBuilder()
    .setFoo(BytesValue.of(byteString)))
    .build();
```

I've not been able to construct similar code with Node.JS gRPC. Either the client complains with "Invalid encoding" or the server receives no value for `foo`. From my understanding, `foo` should be base 64 encoded in JavaScript. For a similar type, google.protobuf.StringValue, ["The JSON representation for `StringValue` is JSON string."](https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/wrappers.proto#L111).
```
message Baz {
  google.protobuf.StringValue qux = 1;
}
```

JavaScript:
```
{
   qux: "Hello" 
}
```

Adjacent to google.protobuf.StringValue's definition is a comment ["The JSON representation for `BytesValue` is JSON string."](https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/wrappers.proto#L119). How do we encode such a JSON string for Node.JS gRPC? This did not work:

```
const input = fs.readFileSync(path.join(__dirname, "../image.png"));
const base64 = Buffer.from(input).toString("base64");
const message = {
   foo: base64
};
```

I've also tried to take the bytes array from my Java code that's been proven to work, and created buffer from that...

```
const uint8 = [123, 143, ... , 111];
const base64 = Buffer.from(uint8).toString("base64");
const message = {
   foo: base64
};
```

**Comment by murgatroid99** [comment]
The protobuf handlers currently available for gRPC Node have no special handling for `google.protobuf.*` message types. You have to use the actual message structures, not the stated JSON representation. In this case, your message should look like this:

 ```js
const message = {
  foo: {
    value: base64
  }
}
```

It looks to me like this actually matches the structure of the Java code you are comparing it to. The part `setFoo(BytesValue.of(byteString)))`  sets the field `foo` to a `BytesValue` message constructed with the `byteString`.

**Comment by alephnan** [comment]
So I tried:

```
const message = {
 foo: {
   value: base64
 }
}
```

But it's still not working. I used various PNG to base64 converters online. Do you have an example of converting an image to a encoding gRPC NodeJS will transmit?

**Comment by murgatroid99** [comment]
Oh, I missed something the first time I read your issue. This is a `BytesValue` message, so `value` has the type `bytes`. That type is represented by a `Buffer`, so you should just pass your `Buffer` directly as the value.
