### ISSUE TITLE
"npm rebuild" sometimes freeze forever at node-pre-gyp installation

### ISSUE THREAD

**Issue by xiaozhongliu** [grpc/grpc-node#759]
### Problem description
"npm rebuild" sometimes freeze forever at node-pre-gyp install, the entire log is like:
```
[root@iZbp186nbf9djv4xm08ajpZ ~]# kubectl logs k8s-demo-grpc-744bd69c88-74wzf -c k8s-demo-grpc

> protobufjs@6.8.8 postinstall /app/node_modules/protobufjs
> node scripts/postinstall


> grpc@1.18.0 install /app/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp WARN Using needle for node-pre-gyp https download
```

### Reproduction steps
Install npm packages for our app and build docker image on **centos**, then rebuild via "npm rebuild" before running our app within our **alpine** container.

### Environment
 - OS name, version and architecture:
    build env: CentOS Linux 7 (Core)
    running env: Alpine Linux v3.8
 - Node version v10.15.0
 - Package name and version grpc@1.18.0

**Comment by murgatroid99** [comment]
Does the environment it's running in allow outgoing HTTP requests? When you run `npm rebuild` grpc makes an http request to download the binary file for the current environment. If the environment does not allow that that may be one possible reason for this failure.

**Comment by nicolasnoble** [comment]
One way to avoid HTTP requests completely would be to add the `--build-from-source` option to your `npm rebuild` command. Maybe try that?

**Comment by xiaozhongliu** [comment]
> Does the environment it's running in allow outgoing HTTP requests? When you run `npm rebuild` grpc makes an http request to download the binary file for the current environment. If the environment does not allow that that may be one possible reason for this failure.

@murgatroid99 Yes definitely there is network access from within the container. The issue only occurs occasionally. Whenever the issue occurs, kill the container, a new created one will run normally.


> One way to avoid HTTP requests completely would be to add the `--build-from-source` option to your `npm rebuild` command. Maybe try that?

@nicolasnoble Thanks for ur suggestion, this may bypass the problem but it's not applicable for us...
The final docker image won't allow compile time packages like python, make, etc. that occupies a lot of disk space.

**Comment by nicolasnoble** [comment]
Unfortunately, this really isn't a grpc issue, it seems to be a node-pre-gyp one. The move to needle instead of request seems to be a rootcause however. I might try to revert this in node-pre-gyp.

**Comment by xiaozhongliu** [comment]
@nicolasnoble Do you mean you may create one issue in node-pre-gyp repo? We've used "npm rebuild" for more than two months, this issue started to occur several days ago.

**Comment by nicolasnoble** [comment]
node-pre-gyp made a change not so long ago to reduce their dependencies by replacing the HTTP downloader from `request` to `needle`.

**Comment by xiaozhongliu** [comment]
@nicolasnoble I see this was done 1 year ago: [commit](https://github.com/mapbox/node-pre-gyp/commit/9a9089b529413d5bdf30f548b217f87fa3c79010#diff-b9cfc7f2cdf78a7f4b91a753d10865a2).

**Comment by nicolasnoble** [comment]
Huh, time flies...

I don't have any other good explanation however.

**Comment by xiaozhongliu** [comment]
We solved this by specifying "target_libc=musl" for npm during packages installation on centos, then the target built binary node-v64-linux-x64-musl/grpc_node.node is ready to be used on alpine, no npm rebuild is needed any more.

**Comment by edap** [comment]
I have the same problem as described in this issue. @xiaozhongliu how can I fix this?
