### ISSUE TITLE
proto-loader: consider providing missing common google protos

### ISSUE THREAD

**Issue by cjihrig** [grpc/grpc-node#771]
### Is your feature request related to a problem? Please describe.
protobufjs provides [some common Google types](https://github.com/dcodeIO/protobuf.js/blob/6fa4c3487c50f9e2647a384bf64cfb009752b6a7/src/common.js#L12-L18), but [not others](https://github.com/dcodeIO/protobuf.js/blob/6fa4c3487c50f9e2647a384bf64cfb009752b6a7/src/common.js#L34-L41). This is pretty confusing behavior, particularly if you've successfully used one, but run into 'unresolvable extensions' errors on another.

### Describe the solution you'd like
It would be great if the proto-loader module provided these. The change is straightforward, and I'm happy to send a PR if the maintainers are OK with it.

### Describe alternatives you've considered
This could be fixed in protobufjs, but I'm honestly not sure how maintained that repo currently is.

It can also be worked around in user code, but as previously mentioned, the current behavior is extremely confusing (and frustrating).

**Comment by murgatroid99** [comment]
The first option for changing this should be Protobuf.js. If the change is rejected there then we can see about modifying this library to handle it.

**Comment by cjihrig** [comment]
I agree. The problem I see is that protobufjs doesn't seem very responsive. For example, I opened an issue (unrelated to this) in October that hasn't been responded to at all. I'll open another issue, but how long do we wait if there is no response?

**Comment by cjihrig** [comment]
https://github.com/dcodeIO/protobuf.js/issues/1180

**Comment by xblv** [comment]
meet the same problem... could we have some workarounds here in proto-loader level?
