### ISSUE TITLE
proto-loader: cannot seem to access custom field options

### ISSUE THREAD

**Issue by cjihrig** [grpc/grpc-node#772]
### Is your feature request related to a problem? Please describe.
From what I can tell, protobufjs [drops custom field options](https://github.com/dcodeIO/protobuf.js/blob/master/ext/descriptor/index.js#L827-L835). Given the following .proto file (and after working around #771), I'd like to be able to access the `sensitive` option in JavaScript code.

```
syntax = "proto3";
package example;
import "google/protobuf/descriptor.proto";

extend google.protobuf.FieldOptions {
  bool sensitive = 51059;
}

service ExampleService {
  rpc ExampleRpc (ExampleInput) returns (ExampleOutput) {}
}

message ExampleInput {
  string foo = 1 [(example.sensitive) = true];
}

message ExampleOutput {}
```

### Describe the solution you'd like
I'd like to have access to uninterpreted options (`sensitive` in this example). If this is already possible, I apologize, but I haven't been able to find it.

### Describe alternatives you've considered
This could be fixed in protobufjs, but it seems lightly maintained.

### Additional context
I'm happy to contribute the code to address the issue.

**Comment by murgatroid99** [comment]
This should be changed in Protobuf.js. I suspect that the changes needed here are deeper than just that one function: Protobuf.js may need to integrate full extension support into the proto3 implementation just to handle custom options.

**Comment by kpsrinivas** [comment]
Any update or workaround for this ?
