### ISSUE TITLE
grpc-tools@1.7.1: failing with version `CXXABI_1.3.8' not found

### ISSUE THREAD

**Issue by rodaine** [grpc/grpc-node#777]
### Problem description
Running the instructions from the [example application,](https://github.com/grpc/grpc/tree/master/examples/node/static_codegen) getting the following stacktrace:

```
/usr/lib/node_modules/grpc-tools/bin/grpc_node_plugin: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /usr/lib/node_modules/grpc-tools/bin/grpc_node_plugin)
/usr/lib/node_modules/grpc-tools/bin/grpc_node_plugin: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/lib/node_modules/grpc-tools/bin/grpc_node_plugin)
/usr/lib/node_modules/grpc-tools/bin/protoc_plugin.js:37
    throw error;
    ^

Error: Command failed: /usr/lib/node_modules/grpc-tools/bin/grpc_node_plugin
/usr/lib/node_modules/grpc-tools/bin/grpc_node_plugin: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /usr/lib/node_modules/grpc-tools/bin/grpc_node_plugin)
/usr/lib/node_modules/grpc-tools/bin/grpc_node_plugin: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/lib/node_modules/grpc-tools/bin/grpc_node_plugin)

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)
--grpc_out: protoc-gen-grpc: Plugin failed with status code 1.
```

### Reproduction steps
- From the [examples/protos](https://github.com/grpc/grpc/tree/master/examples/protos) directory
- `npm install -g grpc-tools@1.7.1`
- `grpc_tools_node_protoc --js_out=import_style=commonjs,binary:../node/static_codegen/ --grpc_out=../node/static_codegen --plugin=protoc-gen-grpc=`which grpc_tools_node_protoc_plugin` helloworld.proto`

### Environment
 - OS name, version and architecture: Ubuntu 14.04.4
 - Node version: 6.9.1
 - Node installation method: internal debian package (built from source)
 - If applicable, compiler version: gcc 4.8.4
 - Package name and version: grpc-tools@1.7.1

### Additional context
- Same error with `1.7.0`
- No error with `1.6.6`
- Also able to repro directly by executing `/usr/lib/node_modules/grpc-tools/bin/grpc_node_plugin`

**Comment by nicolasnoble** [comment]
Ubuntu 14 LTS is having its end of life next month, and we're not able to support it. Please upgrade your operating system.

**Comment by rodaine** [comment]
That's a reasonable response (if a touch dismissive). While I agree you shouldn't have to support EOL OS's, I think it's worth documenting these requirements. Where would it make sense to call this out?

**Comment by nicolasnoble** [comment]
I think there's something on the main repository where we state that we basically try to support operating systems that are currently under support themselves, although the "10 years LTS" thing from Ubuntu 18.04 may give us second thoughts.

@vjpai do we have that anywhere?
