### ISSUE TITLE
Typescript issue with a missing generic on "Message"

### ISSUE THREAD

**Issue by lostpebble** [grpc/grpc-node#779]
### Environment
 - OS name, version and architecture: Windows 10
 - Node installation method : nvm
 - Package name and version grpc@1.19.0 and grpc@1.18.0

```
../../node_modules/grpc/index.d.ts:69:50 - error TS2314: Generic type 'Message<T>' requires 1 type argument(s).

69     [name: string]: GrpcObject | typeof Client | Message;
                                                    ~~~~~~~
```

I've been running into all kinds of type errors with `grpc` and `google-gax` since trying to update my `@google-cloud` dependencies. This is one of them - these kinds of errors should definitely be caught by the Typescript build process before releasing the library, so I'm kind of surprised that it made it through.

I use `esModuleInterop: true` and `"allowSyntheticDefaultImports": true,` which was causing issues in `google-gax` for some reason - but I've turned them off to test and this `grpc` error remains the same, so its not related to those.

**Comment by murgatroid99** [comment]
See #176, #393, #422, and #425, and this should have been fixed by dcodeIO/protobuf.js#1086. Do you have a separate (possibly transitive) dependency on Protobuf.js that is pinned to an earlier version?

**Comment by lostpebble** [comment]
Ah that could be it.. I'm using a few libraries across `@google-cloud`. Trying to get them to all play nice is always a bit of a pain. I've rolled back for now because of some other TypeScript issues in `google-gax`, but will try again when they have been resolved.
