### ISSUE TITLE
Error building from source for Electron 5.0.0-beta.5 on Mac OSX

### ISSUE THREAD

**Issue by vsimon** [grpc/grpc-node#786]
### Problem description
Noticing an error where npm rebuild is trying to build grpc from source and it is failing on OSX 10.14.3.

### Reproduction steps
Give very precise steps you've discovered to reproduce your problem. If possible and applicable, provide us with a repository we can clone that contains a reproduction case. Also if possible and applicable, please include a Dockerfile that exhibits the problem if it's specific to a certain environment. Bug reports with no reproduction steps will be closed.

### Environment
 - OSX 10.14.3
 - Node version v10.14.1
 - Node installation method: homebrew
 - If applicable, compiler version: clang-1000.11.45.5
 - Package name and version: grpc@1.19.0

### Additional context

On OSX, trying to install electron + firebase (which I believe uses grpc) then doing npm rebuild results in an error building grpc for electron 5.

With electron 5
```
npm init -f
npm install firebase@5.9.0
npm install electron@5.0.0-beta.5
npm rebuild --target=5.0.0-beta.5 --runtime=electron --dist-url=https://atom.io/download/electron


...
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/security/credentials/google_default/google_default_credentials.o
In file included from ../deps/grpc/src/core/lib/security/credentials/google_default/google_default_credentials.cc:41:
In file included from ../deps/grpc/src/core/lib/security/credentials/jwt/jwt_credentials.h:25:
In file included from ../deps/grpc/src/core/lib/security/credentials/jwt/json_token.h:27:
In file included from ../deps/grpc/third_party/boringssl/include/openssl/rsa.h:60:
../deps/grpc/third_party/boringssl/include/openssl/base.h:143:9: error: 'OPENSSL_THREADS' macro redefined [-Werror,-Wmacro-redefined]
#define OPENSSL_THREADS
        ^
<command line>:16:9: note: previous definition is here
#define OPENSSL_THREADS 1
        ^
1 error generated.
make: *** [Release/obj.target/grpc/deps/grpc/src/core/lib/security/credentials/google_default/google_default_credentials.o] Error 1

```

Errors

With electron 4, works.
```
npm init -f
npm install firebase@5.9.0
npm install electron@4.1.0
npm rebuild --target=4.1.0 --runtime=electron --dist-url=https://atom.io/download/electron
```

**Comment by nicolasnoble** [comment]
You can't build node-pre-gyp native modules on beta versions of Electron due to non canonical header location.

**Comment by vsimon** [comment]
Good to know! Thanks

**Comment by zkiiito** [comment]
i have the same problem with electron 5.0.0 (not beta), grpc 1.2.0, on linux and osx. on windows, it's fine.
https://travis-ci.org/zkiiito/map-gallery-editor/jobs/526812271#L795
https://travis-ci.org/zkiiito/map-gallery-editor/jobs/526812270#L3773

**Comment by nicolasnoble** [comment]
Grpc 1.2.0 is way too old to even be able to work on any version of Electron.

**Comment by zkiiito** [comment]
sorry, 1.20.0, firebase tries to install this.

**Comment by nicolasnoble** [comment]
I just realized that Electron 5.0.0 has been published as of a few hours ago. We do not support it at the moment.

**Comment by zkiiito** [comment]
well, about a week ago. when could we expect support?

**Comment by nicolasnoble** [comment]
When we are finished with the work needed to support it.

**Comment by murgatroid99** [comment]
Version 1.20.3 of the package is now out with Electron 5 support.
