### ISSUE TITLE
grpc_tools_node_protoc cannot find libstdc++ GLIBCXX_3.4.21

### ISSUE THREAD

**Issue by jonahbron** [grpc/grpc-node#797]
### Problem description
I'm trying to run grpc_tools_node_protoc in a Docker container based on Debian Stretch.  It seems that protoc is depending on one patch version above what is installed on the machine by default.  Running `strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX` on the container gives this output:

```
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_DEBUG_MESSAGE_LENGTH
```

The error produced when I run protoc is:

```
Error: Command failed: /opt/app/node_modules/grpc-tools/bin/protoc --plugin=protoc-gen-grpc=/opt/app/node_modules/grpc-tools/bin/grpc_node_plugin
/opt/app/node_modules/grpc-tools/bin/protoc: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /opt/app/node_modules/grpc-tools/bin/protoc)
```
The version it expects (3.4.21) is just above the highest installed (3.4.20).

According to the Debian wiki, Stretch is the current stable version of the distro:

https://wiki.debian.org/DebianStretch

### Reproduction steps
1. Install grpc-tools from NPM in a Debian Stretch container
2. Run `grpc_tools_node_protoc`

### Environment
 - Debian Stretch x86_64
 - Node version 8
 - Installed on Docker
 - grpc-tools 1.7.1

**Comment by jonahbron** [comment]
To ensure this wasn't an outdated image problem, I added the following to my Dockerfile on build before running `grpc_tools_node_protoc`

```
ADD apt update && apt upgrade -y
```
This updated all packages to the latest, but it still did not add the needed 3.4.21 version.

**Comment by jonahbron** [comment]
I also tried downgrading to grpc-tools 1.7.0, but the same error appeared.

**Comment by jonahbron** [comment]
The solution I've found for this is to not use grpc_tools_node_protoc, and instead install it directly in the Docker container, and frankly I like this approach better.  Here's an excerpt from my Dockerfile:

```
# Install Protocol Buffers compiler and GRPC-Web compiler plugin
ARG PROTOC_VERSION=3.7.0
ARG PROTOC_GEN_GRPC_WEB_VERSION=1.0.3
RUN apt update && \
    apt install unzip && \
    wget -O /tmp/protoc.zip https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOC_VERSION}/protoc-${PROTOC_VERSION}-linux-x86_64.zip && \
    unzip /tmp/protoc.zip bin/protoc -d /tmp && \
    rm /tmp/protoc.zip && \
    mv /tmp/bin/protoc /usr/local/bin/ && \
    rm -rf /tmp/bin/ && \
    wget -O /usr/local/bin/protoc-gen-grpc-web https://github.com/grpc/grpc-web/releases/download/${PROTOC_GEN_GRPC_WEB_VERSION}/protoc-gen-grpc-web-${PROTOC_GEN_GRPC_WEB_VERSION}-linux-x86_64 && \
    chmod +x /usr/local/bin/protoc-gen-grpc-web
```

Even though it's no-longer a problem for me, I still feel that this is a bug with grpc-tools, since one would expect it to work properly on the stable version of Debian.

**Comment by nicolasnoble** [comment]
Well... we're building using a jessie docker image, so I'm confused as to why stretch would have issues:

https://github.com/grpc/grpc-node/blob/master/tools/release/native/Dockerfile

**Comment by nicolasnoble** [comment]
So, I just tried with a `debian:stretch` docker image, and the package works properly here. Please share more information on what you're doing.

In fact, using the following Dockerfile:

```
FROM debian:stretch

RUN apt update
RUN apt -y dist-upgrade
RUN apt install -y binutils
```

I get:

```
$ docker run -t -i stretch-test bash -l
root@fed9054d878c:/# strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBCXX_3.4.22
GLIBCXX_DEBUG_MESSAGE_LENGTH
```

**Comment by nicolasnoble** [comment]
Meaning that the official debian:stretch image has a `libstdc++.so.6` file with more symbols than yours. So there's something more about your environment that you haven't told us about.

**Comment by jonahbron** [comment]
@nicolasnoble Hmmm, weird.  Here is the list of docker image/tags I'm using and their parents:

```
teracy/angular-cli:1.7.4
node:8
buildpack-deps:stretch
buildpack-deps:stretch-scm
buildpack-deps:stretch-curl
debian:stretch
```

But I notice you're running `dist-upgrade`, while I only ran `upgrade`.  I'm guessing that's the problem.  With that I think we can close this ticket, it's still useful for anyone else who runs into this to know that `dist-upgrade` is the likely solution.

**Comment by nicolasnoble** [comment]
I just tried without the dist-upgrade, and I get the same result. I added the dist-upgrade as a force of habit.

Are you using a composite docker image? If that's the case, your culprit is `teracy/angular-cli:1.7.4`:

```
$ docker run -t -i teracy/angular-cli:1.7.4 bash -l
Starting virtual X frame buffer: Xvfb.
Executing command bash -l
root@28898a9220f1:/# strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_DEBUG_MESSAGE_LENGTH
```

**Comment by nicolasnoble** [comment]
That angular-cli:1.7.4 docker image is based off a fairly old version of the debian:jessie image apparently. Doing a dist-upgrade in it brings in 102 updates, including the libstdc++ library.

**Comment by jonahbron** [comment]
@nicolasnoble Interesting.  I'm guessing it (or another image in the chain) haven't been rebuilt in a while.  I may need to migrate away from it and set up the container for Angular myself.
