### ISSUE TITLE
grpc does not re-establish duplex streams when writes are pending

### ISSUE THREAD

**Issue by connor4312** [grpc/grpc-node#80]
The sequence of events I'm hitting is:

 1. An existing connection fails; the client tries to reconnect
 2. I create a new grpc stream. It seems like this gets created lazily, and is connected before the remote server actually recovers and starts accepting connections.
 3. I write on the stream
 4. The server recovers and starts accepting connections
 5. But, the write never goes through and the TCP connection does not get created. Eventually the test case times out.

I have traced the call to [this `startBatch` call](https://github.com/grpc/grpc-node/blob/master/packages/grpc-native-core/src/client.js#L161). The call is made, but the callback never fires, and eventually the test case times out. No TCP connection is made to the remote server and calls are not recorded. If I switch the order of step 3 and 4, adding a delay before the write happens, it works fine.

[This](https://github.com/mixer/etcd3/blob/bcf75e1a44eeeab89f1e0e9b10f9617d667c255d/test/watch.test.ts#L85-L114) is the full test case I'm running. I have grpc set up to hit a simple TLS proxy server which I can use to simulate network disruptions. `pause()` tears down the server and terminates all existing connections, `resume()` recreates the server. By manually adding a delay before the `proxy.resume()`, I can guarantee this event ordering--the library will try to reconnect to the server as in step 2-3 in the meantime.

**Comment by murgatroid99** [comment]
I'm sorry for taking so long to respond to this. What you describe does not match our own observations, so I'm not sure what might be happening there. Also, the objects you are working with in that test don't seem to have the same semantics as a gRPC client, so I can't tell what exactly should be happening at the gRPC level. Is it possible that you're trying to use a single stream that you created before the proxy was shutdown? If you did that, then the stream would not be moved over to the new server, and it would block until the client realizes that the connection is broken.

If you are still experiencing this problem, can you provide the log output from running the test with the environment variables `GRPC_TRACE=all GRPC_VERBOSITY=DEBUG`?

**Comment by nicolasnoble** [comment]
Closing, since it got no response for 40 days.
