### ISSUE TITLE
Incorrect load/loadSync method signature

### ISSUE THREAD

**Issue by jroper** [grpc/grpc-node#805]
The protobuf.js `load`/`loadSync` methods accept a filename parameter that is [either a string, or an array of strings](https://github.com/dcodeIO/protobuf.js/blob/6fa4c3487c50f9e2647a384bf64cfb009752b6a7/src/index-light.js#L17).

But the grpc proto-loader `load`/`loadSync` method defines the method to be a [single string only](https://github.com/grpc/grpc-node/blob/master/packages/proto-loader/src/index.ts#L268).

This parameter is not used other than to be passed as is to protobuf.js, so effectively it can be either, and if using from JavaScript, then you can pass an array of strings and it works, but an array of strings won't compile if using from TypeScript. So the `filename` parameter type should be changed to a union of `string` and `string[]`.

**Comment by murgatroid99** [comment]
This is not a mistake, it is a deliberate API choice. We do not explicitly prevent users from passing arrays, but we only specify/guarantee the behavior when you pass a single string.

That being said, it might make sense to make this change. If we do, it is a minor-level API change, so it should go though an API review process on our [proposal repository](https://github.com/grpc/proposal). The proper way to handle this would be a proposed edit to [the proposal document](https://github.com/grpc/proposal/blob/master/L23-node-protobufjs-library.md) that originally described the proto-loader library. In my opinion, the fact that the underlying library accepts that argument is not a good enough reason to make the change; why would this change help your use case?

**Comment by alexander-fenster** [comment]
@jroper @nicolasnoble @murgatroid99 Here's my +1 on the original request. I have submitted a PR to the proposal you mentioned.
