### ISSUE TITLE
Provide access to message objects loaded by protobuf.js from proto-loader load methods

### ISSUE THREAD

**Issue by jroper** [grpc/grpc-node#807]
Currently, the proto-loader only allows you to access the grpc services defined in a protobuf file. If you want to access the message objects, for example, to be able to use oneof constants, you need to load the same protobuf file again, with the same options, using protobufjs, eg:

```javascript
let protoLoader = require("@grpc/proto-loader");
let protobufjs = require("protobufjs");
let packageDefinition = protoLoader.loadSync(
  "myfile.proto",
  {keepCase: true,
    longs: String,
    enums: String,
    defaults: true,
    oneofs: true
  });
let root = protobufjs.loadSync(
  "myfile.proto",
  {keepCase: true,
    longs: String,
    enums: String,
    defaults: true,
    oneofs: true
  });
```

This seems like a superfluous step, given that grpc proto-loader has already loaded it. Perhaps proto-loader should just modify the returned root namespace, replacing the grpc services with service definitions, and leaving the messages as is. Or, maybe proto-loader could accept an already loaded protobufjs root namespace (essentially, export the `createPackageDefinition` function).

**Comment by nicolasnoble** [comment]
This would mean exposing the protobufjs API directly, which is the opposite of the purpose of this code, that tries to abstract and hide protobufjs to  protect the end user against API breaking changes coming from protobufjs.

**Comment by murgatroid99** [comment]
First, the correspondence between the two functions isn't as close as you think. Most of the options to `protoLoader.loadSync` actually go to `Message#toObject`, not `protobufjs.loadSync`, and you don't mention `includeDirs`, but that is actually unique to `proto-loader`.

Second, the resolution here depends on how you want to use the message types:

 - If you want to construct `Protobuf.js` message objects, that is explicitly out of scope for this library. The library purposely accepts and outputs plain JS objects representing messages.

 - If you want to use information about the message type, the message and enum descriptor objects exported by `proto-loader` may be able to help with that.

**Comment by novemberborn** [comment]
> Or, maybe proto-loader could accept an already loaded protobufjs root namespace (essentially, export the `createPackageDefinition` function).

This would be tremendously helpful. It would allow me to pre-process a root and rewrite certain types, dealing with `gogoproto` annotations.

I'm perfectly fine handling any `protobufjs` incompatibilities that may arise. Not that it's updated frequently anyway.

**Comment by murgatroid99** [comment]
Avoiding those incompatibilities was one of the primary goals of creating this library, and I am not willing to compromise that.

**Comment by novemberborn** [comment]
Sure, that's fair enough. I guess I'll take the relevant pieces and put together my own loader.
