### ISSUE TITLE
Is http2 still considered experimental?

### ISSUE THREAD

**Issue by rubensayshi** [grpc/grpc-node#808]
### Is your feature request related to a problem? Please describe.
The README mentions that the pure JS implementation is based on the http2 stdlib, 
https://nodejs.org/api/http2.html says it's stable already, does this mean the README is outdated?

### Describe the solution you'd like
Updated README I guess ...

**Comment by DRoet** [comment]
yeah its no longer experimental since `>= v8.13.0` and `>= v10.10.0`

**Comment by murgatroid99** [comment]
Thank you. I did not realize it was no longer experimental. I will fix the README when I get a chance, unless someone wants to send a PR...

**Comment by rubensayshi** [comment]
awesome! <3 for having a pure JS implementation
