### ISSUE TITLE
ServiceError Example

### ISSUE THREAD

**Issue by dvisztempacct** [grpc/grpc-node#825]
An example of instantiating a `ServiceError` value would be nice.

Is there a constructor for this? Can it be a POJO? (i.e. `{ code: myErrCode, details: "something went wrong", metadata: myTrailingMetadata}`)

Thanks!

**Comment by murgatroid99** [comment]
`ServiceError` is not a POJO, but I am pretty sure any function that accepts a `ServiceError` also accepts a `StatusObject`, which is a POJO.

**Comment by dvisztempacct** [comment]
Hi again @murgatroid99!

I don't see any functions declared in `index.d.ts` that would allow me to construct a `ServiceError` instance.

I did find one in `grpc-node/packages/grpc-native-core/src/common.js` but I'm skeptical that the intended use is to `require('grpc/common')` and use that function. Also, this function always defines a `metadata` property on the returned value, which causes problems in `handleError` later:

https://github.com/grpc/grpc-node/blob/master/packages/grpc-native-core/src/server.js#L62-L64

**Comment by dvisztempacct** [comment]
This WFM:

```javascript
class ServiceError extends Error {
  constructor(message, code, metadata, details) {
    super(message)
    if (code != null)
      this.code = code
    if (metadata != null)
      this.metadata = metadata
    if (details != null)
      this.details = details
  }
}
```

**Comment by murgatroid99** [comment]
The point of accepting `ServiceError` objects is to allow server application code to pass along an `Error` object, and possibly attach a status code or metadata before passing it along. In particular, this allows the server to make outgoing gRPC calls and then pass along any errors from those calls.

If you don't already have an `Error` object, you're probably better off just passing a `StatusObject`.

That function in `common.js` is intended to be used internally in grpc client code, and the status objects passed to it are supposed to be fully populated.

**Comment by dvisztempacct** [comment]
Thanks @murgatroid99

**Comment by SHSP-DavidTombs** [comment]
It seems that the `sendUnaryData` callback does not allow passing a StatusObject in TypeScript, though: https://github.com/grpc/grpc-node/blob/39f1152/packages/grpc-native-core/index.d.ts#L550. `ServiceError` or `null`.

**Comment by murgatroid99** [comment]
You're right. That argument should accept a `StatusObject` too.
