### ISSUE TITLE
INTERNAL: Illegal value for datavalue element of type string: object (not a string)

### ISSUE THREAD

**Issue by yanqi321** [grpc/grpc-node#829]
### Problem description
INTERNAL: Illegal value for datavalue element of type string: object (not a string)

### Reproduction steps
1. create client:
```
const ORDER_PATH = path.join(__dirname, 'protos/order.proto')
const packageDefinition = protoLoader.loadSync(ORDER_PATH, {})
const orderProto = grpc.loadPackageDefinition(packageDefinition).order
const client = new orderProto.Order(
  orderHost,
  grpc.credentials.createInsecure()
)
```
2. my protobuf file:
```
syntax = "proto3";
package order;
service Order {
  rpc Add (OrderInfo) returns (AddReply) {};
}
message OrderInfo { 
  string postID = 1;
  int32 orderType = 2;
}
message AddReply {
  bool succ = 1;
  int32 code = 2;
  string msg = 3;
  string data = 4;
}
```
Usually I can use this interface normally. But some time it show the error below:
``INTERNAL: Illegal value for datavalue element of type string: object (not a string)``
I had not defined the field of data, only postID and orderType, i dont understood the error message.
after it show the error , i stored the data to redis server, and Call this interface by the same data 3 minutes later,  it can work fine. This is really weird

### Environment
 - OS name, version and architecture: Centos
 - Node version 8.15.0
 - Node installation method: rpm
 - Package name and version 1.18.0

### Additional context
error log message:
[2019-04-15T19:46:39.534] [ERROR] info - addOrder error: 13 INTERNAL: Illegal value for datavalue element of type string: object (not a string)
[2019-04-15T19:48:40.564] [INFO] info - addOrder post info f65c43208e178260358302addf3688f9:1 success

**Comment by nicolasnoble** [comment]
That's not an error from grpc itself. We don't have nearly enough context to help you here. Please provide us with a reproduction case that we can run ourselves.

**Comment by murgatroid99** [comment]
That looks like a protobuf serialization error.  Some code on either the client or server is passing an incorrectly typed value for one of the message fields that should be a string.

**Comment by yanqi321** [comment]
@murgatroid99 , @nicolasnoble Thank you very much, because my function returns an object, but the string is defined. and the server side did not using protoLoader(protoLoader can auto translate Object to the type of string).
