### ISSUE TITLE
Getting Error: Failed to connect before the deadline URL:grpc://localhost:7051

### ISSUE THREAD

**Issue by SanaNawazkhan** [grpc/grpc-node#831]
This is my package.json file 
```
{
  "name": "nodejs",
  "version": "1.0.0",
  "description": "",
  "main": "issue.js",
  "scripts": {
    "test": "rm -rf _idwallet && node addToWallet.js && node issue.js"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "fabric-client": "*",
    "fabric-network": "^1.4.1",
    "grpc": "^1.20.0",
    "js-yaml": "*"
  },
  "devDependencies": {
    "eslint": "*"
  }
}
```

Using node 10.15.3

When i try to run the command issue.js in commercial-paper tutorial. I get below error:
```
$ node issue.js
Connect to Fabric gateway.
Use network channel: mychannel.
2019-04-21T07:16:19.161Z - error: [Remote.js]: Error: Failed to connect before the deadline URL:grpc://localhost:7051
2019-04-21T07:16:19.169Z - error: [Channel.js]: Error: Failed to connect before the deadline URL:grpc://localhost:7051
2019-04-21T07:16:19.172Z - error: [Network]: _initializeInternalChannel: Unable to initialize channel. Attempted to contact 1 Peers. Last error was Error: Failed to connect before the deadline URL:grpc://localhost:7051
Error processing transaction. Error: Unable to initialize channel. Attempted to contact 1 Peers. Last error was Error: Failed to connect before the deadline URL:grpc://localhost:7051
Error: Unable to initialize channel. Attempted to contact 1 Peers. Last error was Error: Failed to connect before the deadline URL:grpc://localhost:7051
    at Network._initializeInternalChannel (\hyperledger\fabric-samples\commercial-paper\organization\magnetocorp\application\node_modules\fabric-network\lib\network.js:86:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Disconnect from Fabric gateway.
Issue program complete.
```

**Comment by nicolasnoble** [comment]
We need more information about what you're doing exactly.

**Comment by SanaNawazkhan** [comment]
Hi,

I am trying to execute the commercial paper tutorial in the hyperledger
fabric learning.

I performed exactly the same steps as mentioned in the tutorial however
when I try to do issue of the commercial paper using command node issue.js
I get the error I pasted earlier.

I even used node 8.6.0 with npm 5.6 still same error

Thanks
Sana

**Comment by nicolasnoble** [comment]
Can you at least provide some links or pointers as to what you are talking about?

**Comment by SanaNawazkhan** [comment]
This tutorial I am following. It breaks at the issue part of it.

https://hyperledger-fabric.readthedocs.io/en/latest/tutorial/commercial_paper.html#issue-application

**Comment by murgatroid99** [comment]
That error means that it is trying to connect to a server at the given port and failing to do so. Since this is a localhost address, the most likely explanation is that that server isn't running or isn't properly bound to the port. In the "Create Network" section of that tutorial it describes running a docker container that serves something on the port you are trying to connect to. Is that container running, and have you taken the verification steps described to make sure that it is serving on the correct port on the localhost address?

**Comment by simsekgokhan** [comment]
I had the exact same problem. These steps fixed it for me:

- Open VirtualBox Manager and select the “default” VM
- Click “Settings”, “Network”, “Advanced”, “Port Forwarding”.
- Create a new rule by clicking the “+” sign on the right and entering the following: Name -> “grpc”, Host Port -> 7051, Guest Port -> 7051
- You can leave the Host IP and Guest IP unspecified.

Thx to: https://developer.ibm.com/opentech/2017/11/29/running-hyperledger-fabric-windows-revised/

**Comment by nicolasnoble** [comment]
Alright, this obviously seems to be an issue with the user's setup. Closing.
