### ISSUE TITLE
[Issue] Getting a GOAWAY error for Server Shutdown

### ISSUE THREAD

**Issue by ankurkaushal360** [grpc/grpc-node#847]
Node Version: 10.15.1
GRPC Version: 1.18.0
OS: Mac OS X 10.14.4

While running tests for our GRPC based services, we have been seeing these kinds of error(s) a lot: 

```
I0501 16:20:18.024921000 4478604736 chttp2_transport.cc:1787]          ipv6:[::1]:55067: Sending goaway err={"created":"@1556742018.024910000","description":"Server shutdown","file":"../deps/grpc/src/core/lib/surface/server.cc","file_line":320,"grpc_status":0}
```

I am curious as to what would cause those errors to pop up?

**Comment by murgatroid99** [comment]
That's just an informational message. It says "Sending goaway err", which means that the server is sending an error to the client. The description says "Server shutdown", so the server is shutting down and it is informing clients that are still connected to stop sending requests to that server.

**Comment by ankurkaushal360** [comment]
Thank you for the prompt @murgatroid99, I realized this after messing with `logVerbosity` :( Closing this since its a non-issue now.
