### ISSUE TITLE
Can I only npm install the grpc client part?

### ISSUE THREAD

**Issue by xeoshow** [grpc/grpc-node#857]
### Is your feature request related to a problem? Please describe.
I just would like to reduce the package size, and my app only need the grpc client part.

### Describe the solution you'd like
Just want to compile or npm install the grpc client.

Thanks a lot !

**Comment by nicolasnoble** [comment]
No, sorry, we don't have such feature.

**Comment by murgatroid99** [comment]
You could try the `@grpc/grpc-js` package, which is an alternate implementation of grpc. It will have the server in the future, but it's pretty light-weight so it shouldn't have as much of an impact on the package size.
