### ISSUE TITLE
[Typings issue]ServiceError type got "missing the following properties"

### ISSUE THREAD

**Issue by syq7970** [grpc/grpc-node#858]
### Problem description
When I use ServiceError type to make a error object with typescript, the ts compiler report a error `Type '{ code: status.NOT_FOUND; details: string; }' is missing the following properties from type 'ServiceError': name, message. ts(2739)`，it seems like vscode used local lib.es5.d.ts error type.
How can I resolve this?

### Reproduction steps
`let error: grpc.ServiceError = {
        code: grpc.status.NOT_FOUND,
        details: "error details"
      };
      callback(error, null);`

### Environment
 - macOS 10.14.4
 - node 11.13.0
 - gRPC@1.12.3
 - VSCode 1.33.1
 - typescript@3.4.3

**Comment by murgatroid99** [comment]
The object you are making more closely matches the `grpc.StatusObject` type, which should be accepted by the callback there. The `grpc.ServiceError` type is a subtype of the builtin `Error` type and can't just be constructed as a plain object.

The general use-case for `grpc.ServiceError` is that you already have an `Error` object from the application code, and you can just attach a status code and optionally some metadata and then pass it to grpc. Otherwise, if you are constructing non-OK status information from scratch like in your code, you should make it a `grpc.StatusObject`.

**Comment by syq7970** [comment]
@murgatroid99 thx for the reply.
I tried change `grpc.ServiceError` to the `grpc.StatusObject` type, but get a new issue at callback function line:
`Type 'StatusObject' is missing the following properties from type 'ServiceError': name, message ts(2345)`.

and type `grpc.StatusObject` must have a metadata object, even if I don't need it.

This is my function example: 
```typescript
const login: handleUnaryCall<LoginRequest, LoginResponse> = async (call, callback) => {
    let error: grpc.StatusObject = {
            code: grpc.status.UNKNOWN,
            details: err.message,
            metadata: new grpc.Metadata()
    };
    callback(error, null);
}
```

So is there has a typings defination issue?

**Comment by murgatroid99** [comment]
Yes, there is a type definition issue here. The callback type definitions we have are overly restrictive. They should also accept a `Partial<StatusObject>`, which also means that they wouldn't actually require the `metadata`.

**Comment by fatfatson** [comment]
should the types be updated?
```
type sendUnaryData<ResponseType> =
    (error: ServiceError | null, value: ResponseType | null, trailer?: Metadata, flags?: number) => void;
```

**Comment by murgatroid99** [comment]
I have updated the type, I just haven't published the fix yet.

**Comment by Aadil-Nabi** [comment]
Hi ,

Can some one please help with below error, i am stuck for some days:

error TS2739: Type '{ jwt: string; }' is missing the following properties from type 'CookieSessionObject': isChanged, isNew, isPopulated
←[91m[auth-depl-cc6888574-ljs9l auth] ←[0m

Type Script version Version 3.9.5

Thanks

**Comment by murgatroid99** [comment]
@Aadil-Nabi That error doesn't look relevant to this issue. Please file a new issue using our issue template with a more complete description of the error.
