### ISSUE TITLE
Unable to Install in --modules-folder using Yarn

### ISSUE THREAD

**Issue by AlecHFerguson** [grpc/grpc-node#875]
### Problem description
Error installing this module with the yarn `--modules-folder` argument.
```
error dist/node_modules/grpc: Command failed.
Exit code: 127
Command: node-pre-gyp install --fallback-to-build --library=static_library
Arguments: 
```

### Reproduction steps
```
$ yarn init
$ mkdir dist
$ yarn add grpc
$ yarn install --modules-folder=dist/node_modules
yarn install v1.3.2
(node:21388) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
⠁ 
⠁ 
⠁ 
⠁ 
error dist/node_modules/grpc: Command failed.
Exit code: 127
Command: node-pre-gyp install --fallback-to-build --library=static_library
Arguments: 





```

### Environment
 - OS name, version and architecture: Mac
 - Node version: v10.10.0 (have seen on several others -- 8.X, 9.X)
 - Node installation method: nvm, nodenv (tried both)
 - If applicable, compiler version: N/A
 - Package name and version: `grpc@1.20.3`

### Additional context
Unclear if this is a GRPC bug. Happy to file to `node-pre-gyp`.
As a workaround, I run `yarn install`, then mv node_modules to the location I want them.

**Comment by MichaelBitard** [comment]
Globally installing node-pre-gyp "fixes" the issue.
IMHO, this is related to the NODE_PATH being mixed, and not able to retrieve the dependencies.

For example, with this package.json
```
{
  "name": "plop",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "node-pre-gyp": "0.13.0"
  }
}
```
if you `yarn --modules-folder node_modules_production` and try to execute node-pre-gyp --> `./node_modules_production/.bin/node-pre-gyp` you'll have an error:

```
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module 'nopt'
```

but if you set the `NODE_PATH=$NODE_PATH:node_modules_production/` it'll work.

Not sure where to open this though, it seems related to node, not only node-pre-gyp

**Comment by murgatroid99** [comment]
The `grpc` package has been deprecated, so I don't expect that we will put any work into addressing this. We recommend using `@grpc/grpc-js` instead.
