### ISSUE TITLE
`loadSync` fails when it's given a non-existent file name in 0.5.1

### ISSUE THREAD

**Issue by the9000** [grpc/grpc-node#876]
### Problem description
`loadSync` fails when it's given a non-existent file name.

### Reproduction steps
`npm install @grpc/proto-loader@0.5.1`

Then, in node:
```es6
const protoLoader = require('@grpc/proto-loader');
const packageDefinition = protoLoader.loadSync(
    {root: '/not/existent', name: 'whatever.proto'}, {});
```

The faulty lines:
https://github.com/grpc/grpc-node/blob/master/packages/proto-loader/src/index.ts#L124-L125

As translated to JS, they look like this under debugger:
```es6
>54         if (isNamespaceBase(obj) && typeof obj.nested !== undefined) {
 55             return Object.keys(obj.nested)
```
The data they operate on are:
```
debug> exec obj
{ options: 'undefined',
  name: '',
  parent: null,
  resolved: true,
  comment: null,
  ... }
debug> exec obj.nested
undefined
debug> exec typeof obj.nested
'undefined'
```

The typo is obvious: it should have been either `typeof obj.nested !== 'undefined'` or `obj.nested !== undefined`.

### Environment
 - Alpine Linux in a container built from `envoyproxy/envoy-alpine:v1.8.0` image, on top of up-to-date Void Linux, kernel 4.19.44_1.
 - Node 8.14.10 (sorry).
 - Node installed via Alpine's `apk add` in Dockerfile.
 - If applicable, compiler version: N/A.
 - Package name and version: `@grpc/proto-loader`, `0.5.1`.

### Additional context
Supposedly the calling convention of `loadSync` has recently changed. But the bug is not related to it; it just made the error obvious; `typeof undefined === 'undefined'` [per specification](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/typeof#Description).

**Comment by SunshowerC** [comment]
Any plan to publish this fixed-version ?

**Comment by murgatroid99** [comment]
This fix is in the latest versions of `@grpc/proto-loader`.
