### ISSUE TITLE
remove @types/protobufjs dependency

### ISSUE THREAD

**Issue by callmehiphop** [grpc/grpc-node#883]
The latest release of gRPC has been giving me some TypeScript errors which I think are caused by a conflict between the `@types/protobufjs` and `protobufjs` packages. Upon closer inspection, the `@types/protobufjs` package is [deprecated](https://www.npmjs.com/package/@types/protobufjs), which leads me to believe the correct solution here is to probably just use the types shipped with `protobufjs`.

**Comment by yoitsro** [comment]
I'm experiencing the same thing, causing builds to fail.

**Comment by murgatroid99** [comment]
We actually did remove that dependency in the previous version, but it looks like that change got lost in a git merge. I'll try to get a fix for this out soon.

**Comment by merlinnot** [comment]
For the time being I can recommend adding the following as a `postinstall` step:

```bash
npm ls --parseable @types/protobufjs | xargs rm -r
```

**Comment by murgatroid99** [comment]
Version 1.21.1 is now out with this fixed.

**Comment by novemberborn** [comment]
This has regressed in 1.22.0. Compare the dependencies:

* https://npmfs.com/package/grpc/1.22.0/package.json
* https://npmfs.com/package/grpc/1.21.1/package.json

**Comment by cjihrig** [comment]
See https://github.com/grpc/grpc-node/pull/956

**Comment by murgatroid99** [comment]
Version 1.22.1 is out with the fix
