### ISSUE TITLE
TypeScript ServerUnaryCall should extend EventEmitter

### ISSUE THREAD

**Issue by mhverbakel** [grpc/grpc-node#885]
### Problem description
In the TypeScript definitions file, the `ServerUnaryCall<RequestType>` does not extend the `EventEmitter` class, although it internally does (and says so in the [documentation](https://grpc.io/grpc/node/grpc-ServerUnaryCall.html))...

**Comment by rjmunhoz** [comment]
Any updates on this?

The PR was merged, but, as far as I can tell, it was never published, since I still can't call `.on` on my client calls

**Comment by murgatroid99** [comment]
This is fixed as of version 1.24.1.
