### ISSUE TITLE
Make grpc-js not wait for ready by default

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc-node#896]
The default core behavior is to end a stream with a non-OK status (usually UNAVAILABLE) as soon as the channel enters the TRANSIENT_FAILURE state, with an option `wait_for_ready` to keep waiting instead. The grpc-js library currently always behaves as though the `wait_for_ready` option is set. That should be changed to align the behavior with the C core.

**Comment by LINKIWI** [comment]
Hi @murgatroid99, curious if there has been any progress on this bug. This bug prevents fail-fast behavior in my client, which is necessary for my use case. I'm happy to contribute if the fix is accessible to someone new to gRPC internals.

**Comment by murgatroid99** [comment]
I'm working on it but it's taking some time. I'm fixing this as part of a larger overhaul of how channel connectivity is handled.

**Comment by murgatroid99** [comment]
This has been fixed as of 0.6.x.
