### ISSUE TITLE
Is 0.4.1 unpublished from npm? Looks like it's not there

### ISSUE THREAD

**Issue by kirillgroshkov** [grpc/grpc-node#898]
Sorry for quick reaction, maybe it's a temporary npm registry issue, but looks like `@grpc/grpc-js@0.4.1` is not present (unpublished?) in npm and our CI builds fail because of that:

![image](https://user-images.githubusercontent.com/4757745/58791413-73a0ab00-85f2-11e9-96da-7e61701aad54.png)

**Comment by kirillgroshkov** [comment]
Ok, found other mention that it was unpublished: https://github.com/firebase/firebase-admin-node/issues/545

**Comment by kirillgroshkov** [comment]
What worked for me is to remove `@google-cloud/datastore` dependency from package.json, then **manually move grpc-js lines from yarn.lock** then add datastore lib again, which put grpc-js@0.4.0 into yarn.lock and then it's working. Not a trivial operation.

**Comment by murgatroid99** [comment]
Sorry about the friction. The original intention was to publish 0.4.2 soon after with the bugs fixed, but that has turned out to be more complicated than anticipated.

**Comment by rh389** [comment]
@murgatroid99  0.4.2 was published to npm yesterday but isn't tagged in this repo (yet). Is that version stable as far as we know or should we prefer 0.4.0?

**Comment by murgatroid99** [comment]
Yes, 0.4.2 should be stable. I just haven't written up the release notes yet.
