### ISSUE TITLE
Application aborted

### ISSUE THREAD

**Issue by fcrisciani** [grpc/grpc-node#91]
I see this error:
```
E1115 06:01:59.641457364     198 completion_queue.cc:67]     assertion failed: !uv_is_active((uv_handle_t *)&prepare)
```
This is the line: https://github.com/grpc/grpc/blame/v1.7.x/src/node/ext/completion_queue.cc#L67

What I'm doing differently from before is to call the `client.waitForReady` every time before calling an RPC method.

Any idea?

**Comment by hhamilto** [comment]
I'm having the same issue -- had to downgrade to 1.6.6

**Comment by fcrisciani** [comment]
@hhamilto do you use a similar approach to guarantee that the connection is established before issueing an RPC call?
I have a series of microservices in node all interacting with grpc. I did not find a good way to track the connection status and restart it if drops, so I was opting for triggering the waitForReady before each call. Do you use any other approach? (I was also trying to inspect the channel connection status and eventually create a new client but anyway you should call the wait for ready on that one too)

**Comment by hhamilto** [comment]
I'm not calling `client.waitForReady` directly in my code, but I am calling `grpc.waitForClientReady` in different places.

I haven't come up with anything I consider a completely sure way of restarting the connection if it drops, but I do listen for the error event on the connection and restart if the code is 14:

```
		connection.on('error', function(err){
			if (err.code === 14) {
			    // ... reconnect code

```

**Comment by murgatroid99** [comment]
Thank you for bringing this to our attention. That assertion itself is incorrect due to a recent change that makes `waitForReady` work as intended. We will publish a patch release soon with the fix.
