### ISSUE TITLE
Prebuilt binaries for Electron running on Alpine

### ISSUE THREAD

**Issue by sstone1** [grpc/grpc-node#920]
### Is your feature request related to a problem? Please describe.
I cannot currently get the grpc module installing on Alpine 3.9 when targeting Electron 3.0. No prebuilt binaries are available at: https://node-precompiled-binaries.grpc.io/grpc/v1.17.0/electron-v3.0-linux-x64-musl.tar.gz

The compile phase fails with GCC errors due to additional `-Werror` checks introduced with the newer GCC versions, which are still not fixed in gRPC: https://github.com/grpc/grpc/issues/18689

### Describe the solution you'd like
Please could you start publishing prebuilt binaries for the combination of Alpine 3.9 and Electron?

### Describe alternatives you've considered
N/A

### Additional context
N/A

**Comment by murgatroid99** [comment]
We are not going to do this. I suggest trying the `@grpc/grpc-js` package instead. It is a new implementation of the same functionality as in the `grpc` library.
