### ISSUE TITLE
Question:  are there API docs for @grpc/grpc-js?

### ISSUE THREAD

**Issue by mastersingh24** [grpc/grpc-node#936]
might have missed this somewhere, but I don't see any API docs for the pure JS package

**Comment by murgatroid99** [comment]
Sort of. For all APIs that are implemented in `@grpc/grpc-js`, the [API docs for `grpc`](https://grpc.github.io/grpc/node/) give the correct information. Other APIs will throw a "not implemented" error or otherwise indicate that they are not supported.

**Comment by mastersingh24** [comment]
ah - ok ... I was basically going with this approach but was not sure if I had missed any other doc.
