### ISSUE TITLE
Service IP Address change during connection

### ISSUE THREAD

**Issue by mewild** [grpc/grpc-node#94]
Lets say I have a grpc server running on 192.168.99.100

I have a client connection to this server. 

For one reason or another the server is brought down and then goes back up again, with lets say an ip address of 192.168.99.102

The client that was connected to the server before the IP change is still sending requests to the old IP address.

Is there any way that to restart the connection to the new IP address?

Just a note these IP's are discovered through DNS, so I assumed that every GRPC request would require a DNS resolution query, but this is not the case. The DNS resolution is cached and the client needs to be restarted to resolve to the new, correct, IP address.

**Comment by murgatroid99** [comment]
A gRPC client opens a persistent connection to the server, and it will continue to use that connection as long as it can. So, what the client does in a situation like this depends on what the first server does. In order for the client to know that it has to re-resolve the address, the server needs to drop the connection.

**Comment by mewild** [comment]
@murgatroid99 Is there a supported way to do this on the server side? I can't seem to find anything in the docs that support dropping all incoming connections.

**Comment by mewild** [comment]
The above solved the problem.

Calling tryShutdown or forceShutdown will do the job.
