### ISSUE TITLE
Not enough responses received

### ISSUE THREAD

**Issue by mrfelton** [grpc/grpc-node#941]
### Problem description

When connecting to some gRPC servers with grpc-js I'm getting the error message `Not enough responses received` when trying to call a method against one of the exposed services.

I'm trying to understand exactly what this error message means or what could be the cause of it. Any light that you could shed on it would be appreciated.

### Reproduction steps
I don't really have reproducible steps that I can provide at this point. I'm more just lloking for information on possible causes of this error.

### Environment
 - OS name, version and architecture: mac
 - Node version [e.g. 8.10.0]: 12
 - Node installation method [e.g. nvm]: nvm
 - If applicable, compiler version [e.g. clang 3.8.0-2ubuntu4]
 - Package name and version [e.g. gRPC@1.12.0]: grpc-js

### Additional context
N/A

**Comment by mrfelton** [comment]
To add a little more info to this. I switched out `grpc-js` for `grpc` and I get a different error:

`Received http2 header with status: 404`

This is actually the error that I was expecting since I know that the service in question is not available.

So, this leads me to believe that there is a difference in how grpc and grpc-js handle the 404 case, with grpc handling it correctly and grpc-js providing a very obscure error message.

**Comment by mrfelton** [comment]
A little more info from trying to debug this.

Whilst this doesn't fix this issue, I believe there is a bug in the code here:

https://github.com/grpc/grpc-node/blob/master/packages/grpc-js/src/call-stream.ts#L246-L268

You are checking the http headers against strings, but the status is returned in the headers as a Number. So this switch will always fall back to the default case and set the status code to `UNKNOWN`

**Comment by mrfelton** [comment]
What I can't quite figure out is that even with that fixed and `mappedStatusCode` getting set correctly to `UNIMPLEMENTED` in the case of a 404, this status code does not make its way to the response.

**Comment by murgatroid99** [comment]
Thank you for pointing this out. I totally missed that `:status` would be represented as a number. And I think I see what's happening here: [this error](https://github.com/grpc/grpc-node/blob/master/packages/grpc-js/src/client.ts#L144) is overriding the one from the HTTP status code.
