### ISSUE TITLE
Latest releast breaks -noImplicitAny typescript builds.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [grpc/grpc-node#950]
The latest release of grpc-node cannot be used in a typescript project that uses -noImplicitAny. This is due to a signature being added without a specified return type. This causes the return type to implicitly be 'any' which TS explicitly disallows. For projects that use strict flags to catch lots of bugs, this prevents usage of this version of grpc entirely.

Fix is simple, just actually provide an annotation for this method.

See PR https://github.com/grpc/grpc-node/pull/949 for location of the issue and the proposed fix.

**Comment by murgatroid99** [comment]
Version 1.22.2 is now out with this fix.

**Comment by CyrusNajmabadi** [comment]
Awesome.  Thanks for letting us know!
