### ISSUE TITLE
typecript check fails on grpc/index.d.ts::setOptions 

### ISSUE THREAD

**Issue by CapOM** [grpc/grpc-node#951]
grpc 1.22.0

node_modules/grpc/index.d.ts:582:5 - error TS7010: 'setOptions', which lacks return-type annotation, implicitly has an 'any' return type.

582     setOptions(options: MetadataOptions);
        ~~~~~~~~~~

**Comment by cjihrig** [comment]
Duplicate of https://github.com/grpc/grpc-node/issues/950 and will likely be fixed in https://github.com/grpc/grpc-node/pull/949.

**Comment by CapOM** [comment]
Great, thx!
