### ISSUE TITLE
Unable to install grpc 1.22.2 on Windows 10 using Node.js 8.16.0

### ISSUE THREAD

**Issue by ashishchandr70** [grpc/grpc-node#961]
### Problem description
Unable to install grpc 1.22.2 on Windows 10

Here is an extract from the log generated. This is the warning that then leads to source-install option, which fails.

node-pre-gyp WARN Using needle for node-pre-gyp https download
node-pre-gyp WARN Pre-built binaries not installable for grpc@1.22.2 and node@8.16.0 (node-v57 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error getaddrinfo ENOTFOUND node-precompiled-binaries.grpc.io node-precompiled-binaries.grpc.io:443

### Reproduction steps
npm install -g grpc  

### Environment
 - Windows 10 Enterprise
 - Node version 8.16
 - Installed Node.js 8.16 from x64 msi 
 - gRPC@1.22.2

### Additional context
npm log extract:

node-pre-gyp WARN Using needle for node-pre-gyp https download
node-pre-gyp WARN Pre-built binaries not installable for grpc@1.22.2 and node@8.16.0 (node-v57 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error getaddrinfo ENOTFOUND node-precompiled-binaries.grpc.io node-precompiled-binaries.grpc.io:443

**Comment by murgatroid99** [comment]
It looks like it is failing to do a DNS lookup for the server with the precompiled binary files. That is most likely to be a problem specific to your computer or ISP or something.

**Comment by ashishchandr70** [comment]
Thanks for the prompt response Michael. I am checking with our network support team. 

I am behind a corporate proxy and nslookup on node-precompiled-binaries.grpc.io returns a Non-existent domain error. Do you think the following approach might resolve it?

I think if we can figure out a way to get this file: https://storage.cloud.google.com/node-precompiled-binaries.grpc.io/grpc/v1.22.2/node-v57-win32-x64-unknown.tar.gz?_ga=2.219851792.-826371871.1562871445 (which is the pre-built binary being referred to above) and point to it either on my computer or in jFrog repo, we can use the --grpc_node_binary_host_mirror=”<URL>” switch and install using the precompiled binaries.

**Comment by nicolasnoble** [comment]
`node-precompiled-binaries.grpc.io` is mirrored on cloudflare. Sure, the main storage is google's, but what the domain name hits is in fact cloudflare's reverse proxy.

**Comment by ashishchandr70** [comment]
Thanks Nick. My approach, since we are restricted in where we can get to and the recommended npm registry is internal, is to download the tar.gz above and host it on our registry location where I can use the --grpc_node_binary_host_mirror=<URL of the location of tgz>. This should work I think.

**Comment by murgatroid99** [comment]
Yes, that should work. Just make sure that you are hosting it at a URL that ends with a string matching the `binary.remote_path` and `binary.package_name` patterns in the package.json file. In the case of that specific binary that would be

```
grpc/v1.22.2/node-v57-win32-x64-unknown.tar.gz
```

**Comment by ashishchandr70** [comment]
Thanks again.
