### ISSUE TITLE
Namespace '"grpc"' has no exported member 'ServerWritableStream'.

### ISSUE THREAD

**Issue by tatianafrank** [grpc/grpc-node#965]
Im writing a node GRPC app using typescript and have a method that is streaming on the server side only. But I get a warning in my IDE when I try to define the type of the call as a 'ServerWritableStream', it says grpc doesnt have that exported member. If I try to use 'ClientReadableStream' (I dont know the difference) as the type then the error I get is that "write" and "end" dont exist as methods on that type. 

```
watch(call: grpc.ServerWritableStream<grpc.Call>): void { 
    // I think the type should be grpc.ClientReadableStream<grpc.Call> but throws error that says "Namespace '"grpc"' has no exported member 'ServerWritableStream'"
    try {
      call.write({ status: ServingStatus.SERVING });
      call.end();
    } catch (error) {
      call.write({ status: ServingStatus.NOT_SERVING });
      call.end();
    }
  }
```
Protobuf:
`rpc Watch(HealthCheckRequest) returns (stream HealthCheckResponse);`

### Environment
 - mac
 - Node version 10.16
 - Node installation method- NVM
 - gRPC@1.21.1
 - @grpc/proto-loader@0.3.0

**Comment by murgatroid99** [comment]
The `Server` and `Client` prefix in those types depend on whether you are writing server code or client code. It looks like you are writing a server method implementation so `ServerWritableStream` is correct there. It is a bug that that type is not exported.

**Comment by murgatroid99** [comment]
Also,`ServerWritableStream` takes two type parameters, the request message type and the response message type.

**Comment by tatianafrank** [comment]
Revisited this morning and it looks like changing it from ServerWrit**a**bleStream to ServerWrit**ea**bleStream fixed the issue!
