### ISSUE TITLE
ClientUnaryCall missing EventEmitter type

### ISSUE THREAD

**Issue by khaosdoctor** [grpc/grpc-node#966]
### Problem description
According to #891, the `index.d.ts` at the native core was updated on branch `1.21.x` as of the following:

https://github.com/grpc/grpc-node/blob/9ee58379c235f0c184ba653febbfd3857c32c0f4/packages/grpc-native-core/index.d.ts#L1205

However, both in versions 1.21.1 and 1.22.1 there's no such alteration:
- https://unpkg.com/grpc@1.21.1/index.d.ts
- https://unpkg.com/grpc@1.22.1/index.d.ts

**Comment by murgatroid99** [comment]
This is fixed in version 1.24.1.
