### ISSUE TITLE
node-v59-linux-x64/grpc_node.node is missing

### ISSUE THREAD

**Issue by Jasperav** [grpc/grpc-node#97]
I am trying to use Firebase admin SDK in my server. When I deploy I get the error I am missing file node-v59-linux-x64/grpc_node.node in firebase-admin node_module map. I added "grpc": "1.7.1" in my package, but I still do not get that file after NPM update. I get an older version, node-v57. I also checked this path https://registry.npmjs.org/grpc/-/grpc-1.7.1.tgz, but I could not locate the file. I deleted my node_modules map and ran npm install again, still no node-v59.

How/where can I download that file? Is there any one who can put the file here so I can manually add it?

Error: Cannot find module '/data/app/node_modules/grpc/src/node/extension_binary/node-v59-linux-x64/grpc_node.node'

**Comment by murgatroid99** [comment]
This will probably be fixed by running `npm rebuild` on the server that you deploy to.

**Comment by Jasperav** [comment]
No it still can not find that module. If anyone can place it here I can manually fix it.

**Comment by nicolasnoble** [comment]
The file is being downloaded by the node-pre-gyp package during the installation, it's not supposed to be inside the npm package. I would recommend looking at the installation logs to see why node-pre-gyp didn't properly download and/or install that file.

As described in the [`binary` section of the package.json](https://github.com/grpc/grpc-node/blob/v1.7.1/packages/grpc-native-core/package.json#L44) file, the URL for these binary files are https://storage.googleapis.com/grpc-precompiled-binaries/node/{name}/v{version}/{node_abi}-{platform}-{arch}.tar.gz so if you insist on hacking at your installation, you can find that file here: https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.7.1/node-v59-linux-x64.tar.gz

**Comment by Jasperav** [comment]
@nicolasnoble thanks that worked. I had the problem before with node-v57 as well. I am running the server on Evennode. On both mac and windows I had the missing file, so maybe it is a problem on there server?

**Comment by kirillgroshkov** [comment]
Same here, missing: `node-v57-darwin-x64-unknown/grpc_node.node`

**Comment by SJAnderson** [comment]
Seeing this on production, can't deploy to our servers without running `npm rebuild`.

**Comment by E3V3A** [comment]
How can you tell what versions are available?

**Comment by nicolasnoble** [comment]
Without logs from what `npm install` says it's going to be difficult to troubleshoot this any further.

For the list of what we are currently releasing as binary packages, unfortunately google compute storage doesn't seem to allow us to share directories trees so we can't directly show what we have. But this is kind of inferable from [these scripts](https://github.com/grpc/grpc-node/tree/master/packages/grpc-native-core/tools/run_tests/artifacts).

**Comment by nicolasnoble** [comment]
With no further information nor logs, this issue is getting stale. Closing it.

**Comment by buoyantair** [comment]
This issue persists for me,
Here is the log I get

```
/usr/bin/node: symbol lookup error: /mnt/c/Users/buoyantair/Documents/jobwork/oyez/monoprix/monoprix-monkey/node_modules/grpc/src/node/extension_binary/node-v57-linux-x64-glibc/grpc_node.node: undefined symbol: SSL_library_init
[nodemon] failed to start process, "babel-node" exec not found
[nodemon] Error
    at Bus.utils.bus.on (/mnt/c/Users/buoyantair/Documents/jobwork/oyez/monoprix/monoprix-monkey/node_modules/nodemon/lib/nodemon.js:147:25)
    at emitOne (events.js:121:20)
    at Bus.emit (events.js:211:7)
    at ChildProcess.<anonymous> (/mnt/c/Users/buoyantair/Documents/jobwork/oyez/monoprix/monoprix-monkey/node_modules/nodemon/lib/monitor/run.js:157:11)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```
