### ISSUE TITLE
Installation Error Log could be more detailed when OS is Windows

### ISSUE THREAD

**Issue by serkanz** [grpc/grpc-node#975]
Because of the problem stated [https://github.com/nodejs/node/issues/4932](https://github.com/nodejs/node/issues/4932) installing the module **via npm** install or **yarn add** in Windows fails with errors. In order to find the root cause of the error, error log could include to solution stated link above.

**Comment by murgatroid99** [comment]
The linked issue should not generally cause installation failures. Rather, it's the reason for some things we had to do to make installation work in the first place.

**Comment by serkanz** [comment]
I think I caused a misunderstanding, of course it's not an error. However as we know the root cause of not completing module installation, an information could be written in the logs to delete that openssl folder.

**Comment by murgatroid99** [comment]
Oh, I see what you mean. It should already be outputting an instruction to the error log that says to delete that folder.
