### ISSUE TITLE
`@grpc/grpc-js`: Path-awareness in gRPC client implementation

### ISSUE THREAD

**Issue by wcjohnson** [grpc/grpc-node#980]
### Is your feature request related to a problem? Please describe.
We use an Envoy service mesh to route traffic around our cluster by URL, so a particular target service may be mounted at, say `http://localhost:4000/grpc/cluster1`. The Client objects created by grpc-js completely ignore any `pathname` in the URL and just route using the gRPC method name:

```js
// The `grpc/cluster1` portion of the URL will be ignored by grpc-js.
client = new protos.TestService('localhost:4000/grpc/cluster1', grpc.credentials.createInsecure())
```

### Describe the solution you'd like
The `pathname` of the parsed URL should be prepended to the gRPC method information to create the final path.

### Describe alternatives you've considered
In fact I was able to resolve the problem by digging into the gRPC code a bit and discovering that the channel object can be overridden:

```js
// Rewire Google's channel implementation to support URL path prefix.
// (should it do this by default?)
class PathAwareChannel extends grpc.Channel:
  createCall(method, deadline, host, parentCall, propagateFlags) ->
    if this.target?.pathname:
      super.createCall(this.target.pathname + method, deadline, host, parentCall, propagateFlags)
    else:
      super.createCall(method, deadline, host, parentCall, propagateFlags)

channelFactoryOverride(address, credentials, options) ->
  // Remove the "channelFactoryOverride" option or grpc will log a warning
  // to the console
  nextOptions = Object.assign({}, options)
  delete nextOptions.channelFactoryOverride

  new PathAwareChannel(address, credentials, nextOptions)

// Now it works!
client = new protos.TestService('localhost:4000/grpc/cluster1', grpc.credentials.createInsecure(), { channelFactoryOverride })
```

It may well be that this solution is adequate and this is a non-issue. However, as gRPC is an HTTP-based protocol, URL-first routing should be preferred over port number routing.

**Comment by murgatroid99** [comment]
We are not going to make this change. We have a [naming spec](https://github.com/grpc/grpc/blob/master/doc/naming.md) that describes how we interpret server names in channel construction, and the path name is not part of that.

You can use a solution like the one you posted here, but keep in mind that the `target` channel member is private for a reason. I'm surprised you could access it at all, and we will provide no guarantees that it will continue to be there with the same type. I recommend instead doing the URL parsing in your own `PathAwareChannel` constructor and tracking the `pathname` there.

The note about needing to remove the option to avoid a warning is an actual bug in our code. That option should not be passed through to the channel factory function in the first place.

**Comment by wcjohnson** [comment]
Understood, thank you.

**Comment by orgads** [comment]
@wcjohnson Thanks for your example code!

Here is my implementation in js, without using internal implementation details. Copying it here for reference:
```js
class PathAwareChannel extends grpc.Channel {
  constructor(target, credentials, options) {
    super(target, credentials, options);
    this.pathPrefix = options['grpc.pathPrefix'] || '';
  }

  createCall(method, deadline, host, parentCall, propagateFlags) {
    return super.createCall(`${this.pathPrefix}${method}`, deadline, host, parentCall, propagateFlags);
  }
}

function channelFactoryOverride(address, credentials, options) {
  return new PathAwareChannel(address, credentials, options);
}

function createClient() {
  const clientOptions = {
    'grpc.channelFactoryOverride': channelFactoryOverride,
    'grpc.pathPrefix': '/google'
  };
  // Create the client here
}
```
