### ISSUE TITLE
Example code for https/socks proxy usage

### ISSUE THREAD

**Issue by k7eon** [grpc/grpc-node#982]
### Is your feature request related to a problem? Please describe.
I dont find any proxy examples for grpc-node.

### Describe the solution you'd like
I would ask to add setting up proxy via ENV or like 'agent' in 'request' lib or something else.
For example: ENV.HTTP_PROXY='http://proxy.c:1234'

**Comment by murgatroid99** [comment]
As of the latest versions of both libraries (`grpc` and `@grpc/grpc-js`) the proxy-related environment variables described in [this document](https://github.com/grpc/grpc/blob/master/doc/environment_variables.md) can be used to configure proxy behavior.
