### ISSUE TITLE
Error: Argument mismatch in makeUnaryRequest

### ISSUE THREAD

**Issue by burke212** [grpc/grpc-node#987]
### Problem description
On my website the click of a button attempts to fetch a particular resource (http://127.0.0.1:3000/api/products, GET). Once the code gets to the gRPC client.js, it uses promises to make a call to the gRPC server.js. This error is caught in the promise chain in client.js when the call to the server.js is made. 

**client.js**
```javascript
const path = require('path');
const protoLoader = require('@grpc/proto-loader');
const grpc = require('grpc');
const util = require('util');

const productProtoPath = path.join(__dirname, '..', '..', 'protos', 'product.proto');
const productProtoDefinition = protoLoader.loadSync(productProtoPath);
const productPackageDefinition = grpc.loadPackageDefinition(productProtoDefinition).product;
const client = new productPackageDefinition.ProductService(
  'localhost:50051', grpc.credentials.createInsecure());

const Promise = require('bluebird');

const listProducts = function(req, res) {
  Promise.try(() => {
    console.log("lol2");
    return client.listProducts(req, res); //ERROR TIGGERED HERE, OH NO!
  }).then((result) => {
    console.log("lol3"+res.json(result));
    res.json(result);
  }).catch(console.error);
}

module.exports = {
  listProducts,
};
```

**server.js**
```javascript
const path = require('path');
const protoLoader = require('@grpc/proto-loader');
const grpc = require('grpc');

const fs = require('fs');
const { promisify } = require('util')
const readFile = promisify(fs.readFile)

const sqlite3 = require('sqlite3').verbose();
const util = require('util');

// grpc service definition
const productProtoPath = path.join(__dirname, '..', 'protos', 'product.proto');
const productProtoDefinition = protoLoader.loadSync(productProtoPath);
const productPackageDefinition = grpc.loadPackageDefinition(productProtoDefinition).product;

const Promise = require('bluebird');

const listProducts = function(req, res){
  console.log("This bette work...");
  return new Promise(function(resolve, reject){
    let sql = 'SELECT NAME as name FROM PEEPS';
      
      var db = new sqlite3.Database('../data/testDB.db', sqlite3.OPEN_READONLY, (err) => {
        if(err){
          console.error(err.message);
        }
        console.log("connected to DB");
      });

      db.get(sql, (err, row) => {
        if(err){
          console.error(err.message);
          return reject(err);
        }
        console.log(row);
        return resolve(row);
      });

      // callback(null, data);//BAD - CHANGE TO PROMISE

      db.close((err) => {
        if(err) {
          console.error(err.message);
        }
        console.log('closed db');
      });
  });
}

// main
function main() {
  const server = new grpc.Server();
  // gRPC service
  server.addService(productPackageDefinition.ProductService.service, {
    listProducts: listProducts,
  });
  // gRPC server
  server.bind('localhost:50051', grpc.ServerCredentials.createInsecure());
  server.start();
  console.log('gRPC server running at http://127.0.0.1:50051');
}

main();

```

### Reproduction steps
Repo: https://github.com/burke212/grpc-node 
*You'll want to open 3 terminals/ tabs in a terminal.
1. After `cd` to the project folder...
2. In one terminal, `cd` to */server*. Run `npm install`. Then run `npm start`. 
2.1 Expect a `gRPC server running at http://127.0.0.1:50051` message upon success.
3. In another terminal, `cd` to */client*. Run `npm install`. Then run `npm start`.
3.1 Expect a `Server listening on port 3000` message upon success.
4. In the third terminal, run `npm install`. Then run `npm start`. Follow the localhost link in the message to your browser. It will be the 4th line in the message. (i.e. `ℹ ｢wds｣: Project is running at http://localhost:8080/`).
4.1 Expect `Compiled successfully` at the bottom of the message upon success.
5. In the browser, open your console. 
6. Click the button in the webpage. 
7. The error will be displayed in the terminal that is running the client. 

### Environment
Ubuntu 16.04 amd64
Node version 12.6.0
Express version 4.16.4
gRPC@1.22.2

**Comment by murgatroid99** [comment]
The problem here is that `req, res` is not the right set of arguments when making a grpc call. The first argument has to be the method argument object (`{name: productName}`, in this case). The second argument has to be a callback that handles the response object.
