### ISSUE TITLE
grpc-js: should provide a way to pause the underlying http2 stream

### ISSUE THREAD

**Issue by callmehiphop** [grpc/grpc-node#988]
### Is your feature request related to a problem? Please describe.
I want to be able to pause the actual http2 client stream. As it is today pausing behaves like core streams, meaning the stream continues to write to an internal buffer, but I would expect it to behave like an http2 stream which does not include this behavior.

### Describe the solution you'd like
Ideally just calling `pause()` would pause the underlying http2 stream immediately.

### Describe alternatives you've considered
A separate method like `pauseRequest()` etc., anything that would allow us to pause the underlying request.

### Additional context
My issue is pretty specific to a Cloud PubSub feature. We essentially combine several Duplex streams together and want to provide the incoming data in the exact order we receive it. If at some point we need to pause the streams, they continue to buffer and we lose the ability to determine the order of the buffered messages.

**Comment by murgatroid99** [comment]
We have actually had some requests before to modify the buffering behavior. The simplest solution here may be to add call options that get translated into stream construction options, including the `highWaterMark` option that controls the buffer size.

However, I have to ask what you expect to accomplish here. Message arrival time is affected by a number of factors, and gRPC does not guarantee anything about message arrival order in different streams. A more accurate way to accomplish this would probably involve using a single stream, or adding a timestamp or global sequence number to the response message.

**Comment by callmehiphop** [comment]
@murgatroid99 `highWaterMark` would be a great option, however in some cases I don't want to buffer anything. Even if I were to set `highWaterMark` to `0` the core stream module can still buffer up to 1 response. On the other hand `http2` streams in Node do not do any sort of internal buffering, so pausing it would prevent this from happening entirely.

In addition to that, it looks like grpc-js wraps the http2 stream in a duplex (`Http2CallStream`) and then pipes that into another stream (`ClientReadableStream`) which I believe would effectively double the number of buffered responses.

**Comment by murgatroid99** [comment]
Doesn't that mean that even if I add your original solution, there could always still be one or more messages in the buffer that are not accounted for?

Also, I would still really like to know how making one of these changes would actually solve the overall problem.

**Comment by callmehiphop** [comment]
Yeah, that was a mistake on my part, when I opened this issue I thought that the http2 stream was directly piped into the `ClientReadableStream`, which I think would have made my suggestion feasible?

Looks like my only option would be to use a single stream. Thanks for the suggestion and sorry for the noise!
