### ISSUE TITLE
[Question]How can I set the deadline in the client @grpc/proto-loader

### ISSUE THREAD

**Issue by silas1984** [grpc/grpc-node#991]
In the guide, the client created code is 
“var routeguide = grpc.loadPackageDefinition(packageDefinition).routeguide;
var client = new routeguide.RouteGuide('localhost:50051',  grpc.credentials.createInsecure());”.

How can I set the deadline into the client, Can the third parameter which in the new Client function be used? What options can I set into the third parameter?

Thank you for your help.

**Comment by murgatroid99** [comment]
The deadline is a parameter for each individual request. It goes in the `options` parameter, which goes after the `argument` parameter, if the method takes one, and before the callback, if the method takes one. See the [`Client` class API documentation](https://grpc.github.io/grpc/node/grpc.Client.html) for details. Also as mentioned there, [this list](https://grpc.github.io/grpc/core/group__grpc__arg__keys.html) has the options that can be passed to that third `options` parameter in the client.

**Comment by silas1984** [comment]
Thank you for your help.
